// Source-of-truth UI strings, in English. Everything else is generated by the
// `translate` edge function on demand and cached in localStorage. We also
// hand-author Chinese here because that's the original copy and we want zero
// AI calls for the existing zh-CN audience.
import type { LangCode } from "./languages";

export type StringKey =
  // Header / nav
  | "nav.myStats"
  | "nav.account"
  | "nav.signIn"
  | "nav.signOut"
  | "nav.home"
  | "nav.back"
  // Index page
  | "index.title"
  | "index.subtitle"
  | "index.placement.badge"
  | "index.placement.title"
  | "index.placement.duration"
  | "index.placement.skills"
  | "index.placement.rating"
  | "index.slang.title"
  | "index.slang.subtitle"
  | "index.scenes.title"
  | "index.scenes.subtitle"
  | "index.workplace.title"
  | "index.workplace.subtitle"
  | "index.levels.label"
  | "index.levels.count"
  | "index.levels.units"
  | "index.levels.locked"
  | "index.levels.lockedToast"
  | "index.levels.comingSoon"
  | "index.progress.savedLessons"
  | "index.progress.minutes"
  | "index.progress.streak"
  | "index.progress.cta"
  | "index.progress.save"
  // Auth toasts
  | "auth.signedOut"
  // Language picker
  | "lang.pickerTitle"
  | "lang.pickerSubtitle"
  | "lang.confirm"
  | "lang.changeLater";

// English source strings.
export const EN: Record<StringKey, string> = {
  "nav.myStats": "My stats",
  "nav.account": "Account",
  "nav.signIn": "Sign in / Sign up",
  "nav.signOut": "Sign out",
  "nav.home": "Home",
  "nav.back": "Back",

  "index.title": "Choose your level",
  "index.subtitle": "Pick a level that fits you and start learning",
  "index.placement.badge": "Adaptive · Aligned with CEFR",
  "index.placement.title": "Not sure where to start? Take a placement test",
  "index.placement.duration": "About 25 min",
  "index.placement.skills": "Listening / Speaking / Reading / Writing",
  "index.placement.rating": "A1–C1 rating",
  "index.slang.title": "American slang · {count} entries",
  "index.slang.subtitle": "TikTok / Gen Z / social media · with examples",
  "index.scenes.title": "🎬 Scene dialogues · {count} sets",
  "index.scenes.subtitle": "14 everyday scenes · 1900 native expressions",
  "index.workplace.title": "💼 Workplace English · {count} scenes",
  "index.workplace.subtitle": "Real Bay Area workplace dialogues · high-frequency expressions · monthly updates",
  "index.levels.label": "Learning path · Levels",
  "index.levels.count": "{n} levels · A1 → C2",
  "index.levels.units": "{n} units",
  "index.levels.locked": "Content updating…",
  "index.levels.lockedToast": "This level is being updated, stay tuned ✨",
  "index.levels.comingSoon": "Coming soon",

  "index.progress.savedLessons": "Studied {n} lessons",
  "index.progress.minutes": "{n} min",
  "index.progress.streak": "🔥 {n}-day streak",
  "index.progress.cta": "Sign in to save progress, syncs to your phone in 3s",
  "index.progress.save": "Save",

  "auth.signedOut": "Signed out",

  "lang.pickerTitle": "Choose your language",
  "lang.pickerSubtitle": "We'll show the app in your language alongside English so you can learn faster.",
  "lang.confirm": "Continue",
  "lang.changeLater": "You can change this anytime from the header.",
};

// Hand-authored Chinese (the original copy used throughout the app).
export const ZH: Record<StringKey, string> = {
  "nav.myStats": "我的数据",
  "nav.account": "账户",
  "nav.signIn": "登录 / 注册",
  "nav.signOut": "退出",
  "nav.home": "首页",
  "nav.back": "返回",

  "index.title": "选择学习级别",
  "index.subtitle": "选择适合你的级别，开始学习之旅",
  "index.placement.badge": "自适应 · 参照 CEFR",
  "index.placement.title": "不知道从哪里开始？做个水平测试",
  "index.placement.duration": "约 25 分钟",
  "index.placement.skills": "听 / 说 / 读 / 写",
  "index.placement.rating": "A1–C1 评级",
  "index.slang.title": "美国流行俚语 · {count} 条",
  "index.slang.subtitle": "TikTok / Z 世代 / 社交媒体 · 每条带例句",
  "index.scenes.title": "🎬 场景对话 · {count} 组",
  "index.scenes.subtitle": "14 个生活场景 · 1900 句地道表达",
  "index.workplace.title": "💼 职场英语 · {count} 个场景",
  "index.workplace.subtitle": "湾区职场真实对话 · 高频表达 · 每月更新",
  "index.levels.label": "学习路径 · Levels",
  "index.levels.count": "{n} 级 · A1 → C2",
  "index.levels.units": "{n} 单元",
  "index.levels.locked": "内容更新中…",
  "index.levels.lockedToast": "该级别内容正在更新中，敬请期待 ✨",
  "index.levels.comingSoon": "即将推出",

  "index.progress.savedLessons": "已学 {n} 节",
  "index.progress.minutes": "{n} 分钟",
  "index.progress.streak": "🔥{n}天",
  "index.progress.cta": "登录保存进度，3 秒同步到手机",
  "index.progress.save": "保存",

  "auth.signedOut": "已退出登录",

  "lang.pickerTitle": "选择你的母语",
  "lang.pickerSubtitle": "我们会用你的母语和英语双语显示，帮助你更快学会。",
  "lang.confirm": "继续",
  "lang.changeLater": "之后可以随时在顶部切换。",
};

// Built-in catalogs. Other languages are translated on demand.
export const BUILTIN: Partial<Record<LangCode, Record<StringKey, string>>> = {
  en: EN,
  zh: ZH,
};

export function interpolate(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? String(vars[k]) : `{${k}}`));
}