// Source-of-truth UI strings, in English. Everything else is generated by the
// `translate` edge function on demand and cached in localStorage. We also
// hand-author Chinese here because that's the original copy and we want zero
// AI calls for the existing zh-CN audience.
import type { LangCode } from "./languages";

export type StringKey =
  // Header / nav
  | "nav.myStats"
  | "nav.account"
  | "nav.signIn"
  | "nav.signOut"
  | "nav.home"
  | "nav.back"
  // Index page
  | "index.title"
  | "index.subtitle"
  | "index.sectionsLabel"
  | "index.section.placement.eyebrow"
  | "index.section.placement.title"
  | "index.section.placement.desc"
  | "index.section.aitalk.eyebrow"
  | "index.section.aitalk.title"
  | "index.section.aitalk.desc"
  | "index.section.slang.eyebrow"
  | "index.section.slang.title"
  | "index.section.slang.desc"
  | "index.section.scenes.eyebrow"
  | "index.section.scenes.title"
  | "index.section.scenes.desc"
  | "index.section.workplace.eyebrow"
  | "index.section.workplace.title"
  | "index.section.workplace.desc"
  | "index.section.path.eyebrow"
  | "index.section.path.title"
  | "index.section.path.desc"
  | "index.section.cta"
  | "index.placement.badge"
  | "index.placement.title"
  | "index.placement.duration"
  | "index.placement.skills"
  | "index.placement.rating"
  | "index.slang.title"
  | "index.slang.subtitle"
  | "index.scenes.title"
  | "index.scenes.subtitle"
  | "index.workplace.title"
  | "index.workplace.subtitle"
  | "index.levels.label"
  | "index.levels.count"
  | "index.levels.units"
  | "index.levels.locked"
  | "index.levels.lockedToast"
  | "index.levels.comingSoon"
  | "index.progress.savedLessons"
  | "index.progress.minutes"
  | "index.progress.streak"
  | "index.progress.cta"
  | "index.progress.save"
  // Auth toasts
  | "auth.signedOut"
  // Language picker
  | "lang.pickerTitle"
  | "lang.pickerSubtitle"
  | "lang.confirm"
  | "lang.changeLater"
  // Support / donation
  | "support.cta"
  | "support.thanks"
  | "support.qrTitle"
  | "support.qrSubtitle"
  | "support.qrWechat"
  | "support.qrAlipay"
  | "support.qrHowTo"
  | "support.qrClose";

// English source strings.
export const EN: Record<StringKey, string> = {
  "nav.myStats": "My stats",
  "nav.account": "Account",
  "nav.signIn": "Sign in / Sign up",
  "nav.signOut": "Sign out",
  "nav.home": "Home",
  "nav.back": "Back",

  "index.title": "Choose your level",
  "index.subtitle": "Pick a level that fits you and start learning",
  "index.sectionsLabel": "Five ways to learn",
  "index.section.placement.eyebrow": "01 · Level Check",
  "index.section.placement.title": "Discover your English level",
  "index.section.placement.desc": "Adaptive 25-min test · Listening, speaking, reading, writing · A1–C1 rating",
  "index.section.aitalk.eyebrow": "AI VOICE",
  "index.section.aitalk.title": "Chat 10 minutes in English with Alex",
  "index.section.aitalk.desc": "A real young Californian · all-English live conversation · auto bilingual review + vocabulary quiz at the end",
  "index.section.slang.eyebrow": "02 · Slang Lab",
  "index.section.slang.title": "Sound like a native today",
  "index.section.slang.desc": "TikTok / Gen Z / social media slang · {count} entries with real examples",
  "index.section.scenes.eyebrow": "03 · Everyday Scenes",
  "index.section.scenes.title": "Real life, real conversations",
  "index.section.scenes.desc": "14 daily scenes · {count} dialogue sets · 1900 native expressions",
  "index.section.workplace.eyebrow": "04 · Workplace English",
  "index.section.workplace.title": "Win at work in English",
  "index.section.workplace.desc": "Bay Area workplace dialogues · {count} scenes · high-frequency phrases",
  "index.section.path.eyebrow": "05 · Learning Path",
  "index.section.path.title": "Systematic courses, A1 → C2",
  "index.section.path.desc": "{count} levels · structured units · vocabulary, grammar & writing in one flow",
  "index.section.cta": "Start",
  "index.placement.badge": "Adaptive · Aligned with CEFR",
  "index.placement.title": "Not sure where to start? Take a placement test",
  "index.placement.duration": "About 25 min",
  "index.placement.skills": "Listening / Speaking / Reading / Writing",
  "index.placement.rating": "A1–C1 rating",
  "index.slang.title": "American slang · {count} entries",
  "index.slang.subtitle": "TikTok / Gen Z / social media · with examples",
  "index.scenes.title": "🎬 Scene dialogues · {count} sets",
  "index.scenes.subtitle": "14 everyday scenes · 1900 native expressions",
  "index.workplace.title": "💼 Workplace English · {count} scenes",
  "index.workplace.subtitle": "Real Bay Area workplace dialogues · high-frequency expressions · monthly updates",
  "index.levels.label": "Learning path · Levels",
  "index.levels.count": "{n} levels · A1 → C2",
  "index.levels.units": "{n} units",
  "index.levels.locked": "Content updating…",
  "index.levels.lockedToast": "This level is being updated, stay tuned ✨",
  "index.levels.comingSoon": "Coming soon",

  "index.progress.savedLessons": "Studied {n} lessons",
  "index.progress.minutes": "{n} min",
  "index.progress.streak": "🔥 {n}-day streak",
  "index.progress.cta": "Sign in to save progress, syncs to your phone in 3s",
  "index.progress.save": "Save",

  "auth.signedOut": "Signed out",

  "lang.pickerTitle": "Choose your mother language",
  "lang.pickerSubtitle": "Pick the language you think in — we'll show the app in your native language alongside English so you can learn faster.",
  "lang.confirm": "Continue",
  "lang.changeLater": "You can change this anytime from the header.",

  "support.cta": "If you like this app, buy me a coffee ☕",
  "support.thanks": "Thanks for your support — it helps make Big Moon English better.",
  "support.qrTitle": "Buy me a coffee ☕",
  "support.qrSubtitle": "Scan with WeChat or Alipay to send a tip directly. Every bit helps keep FluentPath ad-free.",
  "support.qrWechat": "WeChat Pay",
  "support.qrAlipay": "Alipay",
  "support.qrHowTo": "Long-press the image to save, then open WeChat / Alipay → Scan.",
  "support.qrClose": "Close",
};

// Hand-authored Chinese (the original copy used throughout the app).
export const ZH: Record<StringKey, string> = {
  "nav.myStats": "我的数据",
  "nav.account": "账户",
  "nav.signIn": "登录 / 注册",
  "nav.signOut": "退出",
  "nav.home": "首页",
  "nav.back": "返回",

  "index.title": "选择学习级别",
  "index.subtitle": "选择适合你的级别，开始学习之旅",
  "index.sectionsLabel": "五种学习方式",
  "index.section.placement.eyebrow": "01 · 水平测试",
  "index.section.placement.title": "英语水平测试",
  "index.section.placement.desc": "25 分钟自适应测试 · 听说读写四项 · A1–C1 评级",
  "index.section.aitalk.eyebrow": "AI 语音",
  "index.section.aitalk.title": "和 Alex 聊 10 分钟英语",
  "index.section.aitalk.desc": "地道美国年轻人 · 全英文真人对话 · 结束自动双语讲解 + 词汇测试",
  "index.section.slang.eyebrow": "02 · 流行俚语",
  "index.section.slang.title": "今天就说得像 native",
  "index.section.slang.desc": "TikTok / Z 世代 / 社交媒体俚语 · 共 {count} 条 · 每条带例句",
  "index.section.scenes.eyebrow": "03 · 生活场景",
  "index.section.scenes.title": "真实生活，真实对话",
  "index.section.scenes.desc": "14 个日常场景 · {count} 组对话 · 1900 句地道表达",
  "index.section.workplace.eyebrow": "04 · 职场英语",
  "index.section.workplace.title": "在工作中自信用英文",
  "index.section.workplace.desc": "湾区职场真实对话 · {count} 个场景 · 高频实战表达",
  "index.section.path.eyebrow": "05 · 系统课程",
  "index.section.path.title": "系统化学习路径 A1 → C2",
  "index.section.path.desc": "{count} 个级别 · 结构化单元 · 词汇、语法、写作一站式",
  "index.section.cta": "开始",
  "index.placement.badge": "自适应 · 参照 CEFR",
  "index.placement.title": "不知道从哪里开始？做个水平测试",
  "index.placement.duration": "约 25 分钟",
  "index.placement.skills": "听 / 说 / 读 / 写",
  "index.placement.rating": "A1–C1 评级",
  "index.slang.title": "美国流行俚语 · {count} 条",
  "index.slang.subtitle": "TikTok / Z 世代 / 社交媒体 · 每条带例句",
  "index.scenes.title": "🎬 场景对话 · {count} 组",
  "index.scenes.subtitle": "14 个生活场景 · 1900 句地道表达",
  "index.workplace.title": "💼 职场英语 · {count} 个场景",
  "index.workplace.subtitle": "湾区职场真实对话 · 高频表达 · 每月更新",
  "index.levels.label": "学习路径 · Levels",
  "index.levels.count": "{n} 级 · A1 → C2",
  "index.levels.units": "{n} 单元",
  "index.levels.locked": "内容更新中…",
  "index.levels.lockedToast": "该级别内容正在更新中，敬请期待 ✨",
  "index.levels.comingSoon": "即将推出",

  "index.progress.savedLessons": "已学 {n} 节",
  "index.progress.minutes": "{n} 分钟",
  "index.progress.streak": "🔥{n}天",
  "index.progress.cta": "登录保存进度，3 秒同步到手机",
  "index.progress.save": "保存",

  "auth.signedOut": "已退出登录",

  "lang.pickerTitle": "请选择你的母语",
  "lang.pickerSubtitle": "选择你最熟悉的语言 —— 我们会用你的母语和英语双语显示，帮助你学得更快。",
  "lang.confirm": "继续",
  "lang.changeLater": "之后可以随时在顶部切换。",

  "support.cta": "如果喜欢这个 App，请我喝杯咖啡 ☕",
  "support.thanks": "感谢你的支持，让 Big Moon English 变得更好。",
  "support.qrTitle": "请我喝杯咖啡 ☕",
  "support.qrSubtitle": "微信或支付宝扫一扫，随心打赏。你的支持让 FluentPath 保持无广告、持续更新。",
  "support.qrWechat": "微信支付",
  "support.qrAlipay": "支付宝",
  "support.qrHowTo": "长按图片保存，再打开微信 / 支付宝 → 扫一扫即可。",
  "support.qrClose": "关闭",
};

// Built-in catalogs. Other languages are translated on demand.
export const BUILTIN: Partial<Record<LangCode, Record<StringKey, string>>> = {
  en: EN,
  zh: ZH,
};

export function interpolate(template: string, vars?: Record<string, string | number>): string {
  if (!vars) return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? String(vars[k]) : `{${k}}`));
}