// Localized strings used across card-og (HTML) and card-og-image (PNG) edge functions.
// Keep this list in sync with src/i18n/languages.ts.
// Each entry has BCP-47-ish lang tag for og:locale plus short, OG-image-friendly copy.

export type CardI18n = {
  locale: string;        // og:locale, e.g. "zh_CN"
  htmlLang: string;      // <html lang="...">
  label: string;         // top label on image, e.g. "KNOWLEDGE CARD · 知识卡片"
  cta: string;           // bottom-left tagline (image)
  scanCta: string;       // under QR code on image
  fallbackTitle: string; // when card not found, og:title
  fallbackDesc: string;  // when card not found, og:description
  titleSuffix: string;   // appended to question for og:title, e.g. " — Big Moon English"
};

const SUFFIX = " — Big Moon English";

export const CARD_I18N: Record<string, CardI18n> = {
  en:    { locale: "en_US", htmlLang: "en",    label: "KNOWLEDGE CARD",                  cta: "Unlock the full explanation · 5 min a day", scanCta: "Scan to try this question",   fallbackTitle: "Big Moon English Knowledge Card", fallbackDesc: "AI-crafted English knowledge cards. Crack one exam point in 5 minutes.", titleSuffix: SUFFIX },
  zh:    { locale: "zh_CN", htmlLang: "zh-CN", label: "知识卡片 · KNOWLEDGE CARD",        cta: "答对解锁全部解析 · 5 分钟搞懂一个考点",   scanCta: "扫码做这道题",                fallbackTitle: "Big Moon English 知识卡片",       fallbackDesc: "AI 生成英语知识卡片，5 分钟搞懂一个考点。",                              titleSuffix: SUFFIX },
  "zh-TW": { locale: "zh_TW", htmlLang: "zh-TW", label: "知識卡片 · KNOWLEDGE CARD",      cta: "答對解鎖全部解析 · 5 分鐘搞懂一個考點",   scanCta: "掃碼做這道題",                fallbackTitle: "Big Moon English 知識卡片",       fallbackDesc: "AI 生成英文知識卡片，5 分鐘搞懂一個考點。",                              titleSuffix: SUFFIX },
  es:    { locale: "es_ES", htmlLang: "es",    label: "TARJETA DE CONOCIMIENTO",          cta: "Desbloquea la explicación completa · 5 min al día", scanCta: "Escanea para intentar",  fallbackTitle: "Tarjeta de Big Moon English",     fallbackDesc: "Tarjetas de inglés con IA. Domina un punto en 5 minutos.",                titleSuffix: SUFFIX },
  hi:    { locale: "hi_IN", htmlLang: "hi",    label: "ज्ञान कार्ड",                       cta: "पूरी व्याख्या अनलॉक करें · रोज़ 5 मिनट",   scanCta: "स्कैन करके हल करें",         fallbackTitle: "Big Moon English ज्ञान कार्ड",     fallbackDesc: "AI से बने अंग्रेज़ी ज्ञान कार्ड। 5 मिनट में एक टॉपिक।",                            titleSuffix: SUFFIX },
  ar:    { locale: "ar_SA", htmlLang: "ar",    label: "بطاقة معرفية",                     cta: "افتح الشرح الكامل · 5 دقائق يوميًا",       scanCta: "امسح لتجربة السؤال",         fallbackTitle: "بطاقة Big Moon English",          fallbackDesc: "بطاقات إنجليزية بالذكاء الاصطناعي. اتقن نقطة في 5 دقائق.",                titleSuffix: SUFFIX },
  pt:    { locale: "pt_BR", htmlLang: "pt",    label: "CARTÃO DE CONHECIMENTO",           cta: "Desbloqueie a explicação · 5 min por dia", scanCta: "Escaneie para tentar",       fallbackTitle: "Cartão Big Moon English",         fallbackDesc: "Cartões de inglês com IA. Domine um ponto em 5 minutos.",                  titleSuffix: SUFFIX },
  ru:    { locale: "ru_RU", htmlLang: "ru",    label: "КАРТОЧКА ЗНАНИЙ",                  cta: "Откройте полный разбор · 5 минут в день",  scanCta: "Сканируй и реши",            fallbackTitle: "Карточка Big Moon English",       fallbackDesc: "Английские карточки с ИИ. Один пункт за 5 минут.",                         titleSuffix: SUFFIX },
  ja:    { locale: "ja_JP", htmlLang: "ja",    label: "ナレッジカード",                    cta: "全解説を解除 · 1日5分でマスター",          scanCta: "スキャンして挑戦",            fallbackTitle: "Big Moon English ナレッジカード", fallbackDesc: "AI製の英語ナレッジカード。5分で1ポイント攻略。",                          titleSuffix: SUFFIX },
  pa:    { locale: "pa_IN", htmlLang: "pa",    label: "ਗਿਆਨ ਕਾਰਡ",                          cta: "ਪੂਰੀ ਵਿਆਖਿਆ ਖੋਲ੍ਹੋ · ਰੋਜ਼ 5 ਮਿੰਟ",       scanCta: "ਸਕੈਨ ਕਰੋ ਅਤੇ ਹੱਲ ਕਰੋ",        fallbackTitle: "Big Moon English ਗਿਆਨ ਕਾਰਡ",      fallbackDesc: "AI ਨਾਲ ਬਣੇ ਅੰਗਰੇਜ਼ੀ ਕਾਰਡ। 5 ਮਿੰਟ ਵਿੱਚ ਇੱਕ ਪੁਆਇੰਟ।",                                titleSuffix: SUFFIX },
  de:    { locale: "de_DE", htmlLang: "de",    label: "WISSENSKARTE",                     cta: "Komplette Erklärung freischalten · 5 Min/Tag", scanCta: "Scannen und ausprobieren", fallbackTitle: "Big Moon English Wissenskarte",  fallbackDesc: "KI-Englischkarten. Ein Punkt in 5 Minuten.",                              titleSuffix: SUFFIX },
  jv:    { locale: "jv_ID", htmlLang: "jv",    label: "KARTU KAWRUH",                     cta: "Bukak panjelasan lengkap · 5 menit saben dina", scanCta: "Pindai kanggo nyoba",   fallbackTitle: "Kartu Big Moon English",          fallbackDesc: "Kartu Inggris AI. Kuwasani siji topik 5 menit.",                          titleSuffix: SUFFIX },
  ko:    { locale: "ko_KR", htmlLang: "ko",    label: "지식 카드",                          cta: "전체 해설 해제 · 하루 5분",                scanCta: "스캔해서 풀어보기",          fallbackTitle: "Big Moon English 지식 카드",       fallbackDesc: "AI 영어 지식 카드. 5분에 한 포인트.",                                       titleSuffix: SUFFIX },
  fr:    { locale: "fr_FR", htmlLang: "fr",    label: "CARTE DE SAVOIR",                  cta: "Débloque l'explication complète · 5 min/jour", scanCta: "Scanne pour essayer",   fallbackTitle: "Carte Big Moon English",          fallbackDesc: "Cartes d'anglais IA. Maîtrise un point en 5 minutes.",                    titleSuffix: SUFFIX },
  tr:    { locale: "tr_TR", htmlLang: "tr",    label: "BİLGİ KARTI",                      cta: "Tüm açıklamayı aç · Günde 5 dakika",        scanCta: "Soruyu denemek için tara",  fallbackTitle: "Big Moon English Bilgi Kartı",     fallbackDesc: "Yapay zeka İngilizce kartları. 5 dakikada bir konu.",                     titleSuffix: SUFFIX },
  vi:    { locale: "vi_VN", htmlLang: "vi",    label: "THẺ KIẾN THỨC",                    cta: "Mở khoá lời giải đầy đủ · 5 phút mỗi ngày", scanCta: "Quét để thử câu này",     fallbackTitle: "Thẻ Big Moon English",            fallbackDesc: "Thẻ tiếng Anh AI. Nắm một điểm trong 5 phút.",                            titleSuffix: SUFFIX },
  it:    { locale: "it_IT", htmlLang: "it",    label: "CARTA DEL SAPERE",                 cta: "Sblocca la spiegazione · 5 min al giorno",  scanCta: "Scansiona e prova",          fallbackTitle: "Carta Big Moon English",          fallbackDesc: "Schede d'inglese con IA. Un punto in 5 minuti.",                          titleSuffix: SUFFIX },
  th:    { locale: "th_TH", htmlLang: "th",    label: "การ์ดความรู้",                       cta: "ปลดล็อกคำอธิบาย · วันละ 5 นาที",          scanCta: "สแกนเพื่อลองทำ",             fallbackTitle: "การ์ด Big Moon English",          fallbackDesc: "การ์ดภาษาอังกฤษด้วย AI พิชิตจุดหนึ่งใน 5 นาที",                              titleSuffix: SUFFIX },
  fa:    { locale: "fa_IR", htmlLang: "fa",    label: "کارت دانش",                        cta: "توضیح کامل را باز کن · روزی ۵ دقیقه",      scanCta: "اسکن کنید و امتحان کنید",     fallbackTitle: "کارت Big Moon English",           fallbackDesc: "کارت‌های انگلیسی هوش مصنوعی. یک نکته در ۵ دقیقه.",                          titleSuffix: SUFFIX },
  pl:    { locale: "pl_PL", htmlLang: "pl",    label: "KARTA WIEDZY",                     cta: "Odblokuj pełne wyjaśnienie · 5 min dziennie", scanCta: "Zeskanuj, by spróbować",  fallbackTitle: "Karta Big Moon English",          fallbackDesc: "Karty angielskiego z AI. Jedno zagadnienie w 5 minut.",                   titleSuffix: SUFFIX },
  nl:    { locale: "nl_NL", htmlLang: "nl",    label: "KENNISKAART",                      cta: "Ontgrendel de uitleg · 5 min per dag",      scanCta: "Scan om te proberen",        fallbackTitle: "Big Moon English Kenniskaart",    fallbackDesc: "AI-Engelse kaarten. Eén punt in 5 minuten.",                              titleSuffix: SUFFIX },
  uk:    { locale: "uk_UA", htmlLang: "uk",    label: "КАРТКА ЗНАНЬ",                     cta: "Відкрий повне пояснення · 5 хв на день",   scanCta: "Скануй і спробуй",           fallbackTitle: "Картка Big Moon English",         fallbackDesc: "Англійські картки з ШІ. Один пункт за 5 хвилин.",                         titleSuffix: SUFFIX },
  id:    { locale: "id_ID", htmlLang: "id",    label: "KARTU PENGETAHUAN",                cta: "Buka penjelasan lengkap · 5 menit/hari",    scanCta: "Pindai untuk mencoba",       fallbackTitle: "Kartu Big Moon English",          fallbackDesc: "Kartu Inggris AI. Kuasai satu poin dalam 5 menit.",                       titleSuffix: SUFFIX },
  ms:    { locale: "ms_MY", htmlLang: "ms",    label: "KAD PENGETAHUAN",                  cta: "Buka penjelasan penuh · 5 minit sehari",    scanCta: "Imbas untuk cuba",           fallbackTitle: "Kad Big Moon English",            fallbackDesc: "Kad Inggeris AI. Kuasai satu poin dalam 5 minit.",                        titleSuffix: SUFFIX },
  ro:    { locale: "ro_RO", htmlLang: "ro",    label: "CARD DE CUNOAȘTERE",               cta: "Deblochează explicația · 5 min pe zi",      scanCta: "Scanează și încearcă",       fallbackTitle: "Card Big Moon English",           fallbackDesc: "Carduri de engleză cu AI. Un punct în 5 minute.",                         titleSuffix: SUFFIX },
  el:    { locale: "el_GR", htmlLang: "el",    label: "ΚΑΡΤΑ ΓΝΩΣΗΣ",                     cta: "Ξεκλείδωσε την εξήγηση · 5 λεπτά/ημέρα",    scanCta: "Σκάναρε για να δοκιμάσεις",  fallbackTitle: "Κάρτα Big Moon English",          fallbackDesc: "Αγγλικές κάρτες με AI. Ένα σημείο σε 5 λεπτά.",                            titleSuffix: SUFFIX },
  cs:    { locale: "cs_CZ", htmlLang: "cs",    label: "KARTA VĚDOMOSTÍ",                  cta: "Odemkni celé vysvětlení · 5 min denně",     scanCta: "Naskenuj a vyzkoušej",       fallbackTitle: "Karta Big Moon English",          fallbackDesc: "AI angličtinové karty. Jeden bod za 5 minut.",                            titleSuffix: SUFFIX },
  sv:    { locale: "sv_SE", htmlLang: "sv",    label: "KUNSKAPSKORT",                     cta: "Lås upp förklaringen · 5 min om dagen",     scanCta: "Skanna för att prova",       fallbackTitle: "Big Moon English-kort",           fallbackDesc: "AI-engelskakort. En punkt på 5 minuter.",                                 titleSuffix: SUFFIX },
  hu:    { locale: "hu_HU", htmlLang: "hu",    label: "TUDÁSKÁRTYA",                      cta: "Nyisd meg a teljes magyarázatot · napi 5 perc", scanCta: "Olvasd be és próbáld ki",  fallbackTitle: "Big Moon English Tudáskártya",     fallbackDesc: "AI angol kártyák. Egy pont 5 perc alatt.",                                titleSuffix: SUFFIX },
  he:    { locale: "he_IL", htmlLang: "he",    label: "כרטיס ידע",                          cta: "פתח את ההסבר המלא · 5 דקות ביום",          scanCta: "סרוק כדי לנסות",              fallbackTitle: "כרטיס Big Moon English",          fallbackDesc: "כרטיסי אנגלית עם AI. נקודה אחת ב-5 דקות.",                                titleSuffix: SUFFIX },
  fil:   { locale: "fil_PH", htmlLang: "fil",  label: "KARD NG KAALAMAN",                 cta: "I-unlock ang buong paliwanag · 5 min kada araw", scanCta: "I-scan para subukan",   fallbackTitle: "Card ng Big Moon English",        fallbackDesc: "AI English cards. Isang punto sa 5 minuto.",                              titleSuffix: SUFFIX },
  bn:    { locale: "bn_BD", htmlLang: "bn",    label: "জ্ঞান কার্ড",                        cta: "পুরো ব্যাখ্যা আনলক করুন · দিনে ৫ মিনিট",    scanCta: "স্ক্যান করে চেষ্টা করুন",     fallbackTitle: "Big Moon English জ্ঞান কার্ড",     fallbackDesc: "AI ইংরেজি কার্ড। ৫ মিনিটে এক পয়েন্ট।",                                   titleSuffix: SUFFIX },
};

export function pickI18n(lang: string | null | undefined): CardI18n {
  if (!lang) return CARD_I18N.en;
  if (CARD_I18N[lang]) return CARD_I18N[lang];
  const base = lang.split("-")[0];
  return CARD_I18N[base] || CARD_I18N.en;
}