-- 九年级 U9 题库灌库(幂等)。volume='9' unit='U9' grade=9。vocab 不在此(已单独按 '9' 灌)。
BEGIN;

-- ===== junior_grammar_points (预期 3) =====
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), 'c49e0d84-1b6d-4bea-bb83-35ff7558dc8f', 'g9u9.01', '①定语从句:that/which 指物', 'B1', 9, '对应:九年级 U9', 1, '9', 'U9' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u9.01');
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), 'c49e0d84-1b6d-4bea-bb83-35ff7558dc8f', 'g9u9.02', '②定语从句:who 指人', 'B1', 9, '对应:九年级 U9', 2, '9', 'U9' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u9.02');
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), 'c49e0d84-1b6d-4bea-bb83-35ff7558dc8f', 'g9u9.03', '③定语从句:关系词选择(人用who、物用that/which)', 'B1', 9, '对应:九年级 U9', 3, '9', 'U9' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u9.03');

-- ===== junior_grammar_questions (预期 60) =====
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'I like music ____ I can dance to.','whose','who','that','where','C','[指物] 先行词music是物→that(who指人错)',1,1,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='I like music ____ I can dance to.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'This is the book ____ changed my life.','that','where','who','whom','A','[指物] book是物→that',2,2,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='This is the book ____ changed my life.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'He prefers movies ____ make him laugh.','whose','who','that','where','C','[指物] movies是物→that',3,3,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='He prefers movies ____ make him laugh.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'I love songs ____ have great lyrics.','who','where','whom','that','D','[指物] songs是物→that',1,4,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='I love songs ____ have great lyrics.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'The film ____ we watched was moving.','who','which','whom','where','B','[指物] film是物→which',2,5,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='The film ____ we watched was moving.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'She likes food ____ tastes spicy.','who','that','where','whose','B','[指物] food是物→that',3,6,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='She likes food ____ tastes spicy.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'This is the phone ____ I bought last week.','who','whom','where','that','D','[指物] phone是物→that',1,7,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='This is the phone ____ I bought last week.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'The music ____ he plays is electronic.','which','who','where','whom','A','[指物] music是物→which',2,8,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='The music ____ he plays is electronic.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'I want a bag ____ has many pockets.','that','where','who','whose','A','[指物] bag是物→that',3,9,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='I want a bag ____ has many pockets.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'The movie ____ won the prize is a documentary.','who','that','where','whom','B','[指物] movie是物→that',1,10,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='The movie ____ won the prize is a documentary.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'He told a story ____ made everyone cry.','who','that','where','whose','B','[指物] story是物→that',2,11,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='He told a story ____ made everyone cry.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'The CD ____ I lost was a gift.','whom','where','who','which','D','[指物] CD是物→which',3,12,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='The CD ____ I lost was a gift.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'I prefer clothes ____ are comfortable.','where','who','whose','that','D','[指物] clothes是物→that',1,13,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='I prefer clothes ____ are comfortable.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'This is the song ____ I want to sing.','whom','where','that','who','C','[指物] song是物→that',2,14,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='This is the song ____ I want to sing.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'The book ____ is on the desk is mine.','whom','where','which','who','C','[指物] book是物→which',3,15,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='The book ____ is on the desk is mine.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'She likes shows ____ have happy endings.','who','where','that','whose','C','[指物] shows是物→that',1,16,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='She likes shows ____ have happy endings.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'I need a pen ____ writes smoothly.','where','whom','who','that','D','[指物] pen是物→that',2,17,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='I need a pen ____ writes smoothly.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'The food ____ my mom cooks is delicious.','who','that','where','whose','B','[指物] food是物→that',3,18,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='The food ____ my mom cooks is delicious.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'The picture ____ hangs on the wall is old.','which','whom','who','where','A','[指物] picture是物→which',1,19,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='The picture ____ hangs on the wall is old.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.01'), 'I like films ____ give me something to think about.','that','who','where','whose','A','[指物] films是物→that',2,20,'mcq','g9u9.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.01' AND x.stem='I like films ____ give me something to think about.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'She likes musicians ____ play different kinds of music.','which','who','whose','where','B','[指人] musicians是人→who(which指物错)',1,1,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='She likes musicians ____ play different kinds of music.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'I know a girl ____ can speak three languages.','who','which','whose','where','A','[指人] girl是人→who',2,2,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='I know a girl ____ can speak three languages.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'The man ____ lives next door is a teacher.','which','who','where','whose','B','[指人] man是人→who',3,3,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='The man ____ lives next door is a teacher.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'He is a singer ____ writes his own songs.','whose','which','where','who','D','[指人] singer是人→who',1,4,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='He is a singer ____ writes his own songs.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'I have a friend ____ loves electronic music.','which','who','whose','where','B','[指人] friend是人→who',2,5,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='I have a friend ____ loves electronic music.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'The doctor ____ helped me was very kind.','which','whose','who','where','C','[指人] doctor是人→who',3,6,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='The doctor ____ helped me was very kind.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'She is the teacher ____ teaches us English.','whose','which','who','where','C','[指人] teacher是人→who',1,7,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='She is the teacher ____ teaches us English.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'I met a boy ____ comes from Australia.','where','which','who','whose','C','[指人] boy是人→who',2,8,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='I met a boy ____ comes from Australia.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'The people ____ work here are friendly.','which','where','whose','who','D','[指人] people是人→who',3,9,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='The people ____ work here are friendly.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'He is a director ____ makes great films.','who','where','whose','which','A','[指人] director是人→who',1,10,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='He is a director ____ makes great films.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'I like writers ____ tell interesting stories.','who','which','whose','where','A','[指人] writers是人→who',2,11,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='I like writers ____ tell interesting stories.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'The woman ____ sang that song is famous.','whose','which','where','who','D','[指人] woman是人→who',3,12,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='The woman ____ sang that song is famous.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'She is an artist ____ paints beautiful pictures.','which','who','whose','where','B','[指人] artist是人→who',1,13,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='She is an artist ____ paints beautiful pictures.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'I respect people ____ help others.','where','which','who','whose','C','[指人] people是人→who',2,14,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='I respect people ____ help others.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'The student ____ won the prize is my friend.','who','which','whose','where','A','[指人] student是人→who',3,15,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='The student ____ won the prize is my friend.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'He is a player ____ never gives up.','where','which','who','whose','C','[指人] player是人→who',1,16,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='He is a player ____ never gives up.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'I know a man ____ can play the violin well.','which','who','whose','where','B','[指人] man是人→who',2,17,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='I know a man ____ can play the violin well.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'The cook ____ made this cake is talented.','whose','which','where','who','D','[指人] cook是人→who',3,18,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='The cook ____ made this cake is talented.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'She likes friends ____ are honest and kind.','who','which','whose','where','A','[指人] friends是人→who',1,19,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='She likes friends ____ are honest and kind.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.02'), 'The musician ____ performed last night was great.','whose','which','where','who','D','[指人] musician是人→who',2,20,'mcq','g9u9.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.02' AND x.stem='The musician ____ performed last night was great.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'I like a teacher ____ is patient and kind.','which','what','who','where','C','[人] teacher→who',1,1,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='I like a teacher ____ is patient and kind.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'This is a song ____ makes me happy.','that','who','what','where','A','[物] song→that',2,2,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='This is a song ____ makes me happy.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'She is a person ____ I admire very much.','what','who','where','which','B','[人] person→who',3,3,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='She is a person ____ I admire very much.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'I want a job ____ pays well.','that','who','what','where','A','[物] job→that',1,4,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='I want a job ____ pays well.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'He is the boy ____ broke the window.','where','which','what','who','D','[人] boy→who',2,5,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='He is the boy ____ broke the window.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'The car ____ he drives is very fast.','where','that','who','what','B','[物] car→that',3,6,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='The car ____ he drives is very fast.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'I have a dog ____ loves to run.','that','whose','where','what','A','[物/动物] dog→that',1,7,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='I have a dog ____ loves to run.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'The girl ____ helped me is my classmate.','where','which','who','what','C','[人] girl→who',2,8,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='The girl ____ helped me is my classmate.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'I read a book ____ was very moving.','that','who','where','what','A','[物] book→that',3,9,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='I read a book ____ was very moving.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'She is a writer ____ lives in our city.','where','who','which','what','B','[人] writer→who',1,10,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='She is a writer ____ lives in our city.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'This is the house ____ has a red door.','that','where','who','what','A','[物] house→that',2,11,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='This is the house ____ has a red door.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'The nurse ____ took care of me was gentle.','what','who','which','where','B','[人] nurse→who',3,12,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='The nurse ____ took care of me was gentle.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'I like movies ____ have a happy ending.','where','what','who','that','D','[物] movies→that',1,13,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='I like movies ____ have a happy ending.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'He is a man ____ everyone respects.','what','which','who','where','C','[人] man→who',2,14,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='He is a man ____ everyone respects.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'The pen ____ you gave me writes well.','what','where','that','who','C','[物] pen→that',3,15,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='The pen ____ you gave me writes well.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'I know a singer ____ has a beautiful voice.','which','what','where','who','D','[人] singer→who',1,16,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='I know a singer ____ has a beautiful voice.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'The food ____ she made was delicious.','who','that','where','what','B','[物] food→that',2,17,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='The food ____ she made was delicious.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'She is the doctor ____ saved his life.','where','which','who','what','C','[人] doctor→who',3,18,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='She is the doctor ____ saved his life.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'I bought a watch ____ shows the date.','what','who','where','that','D','[物] watch→that',1,19,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='I bought a watch ____ shows the date.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u9.03'), 'The children ____ play here are happy.','which','where','what','who','D','[人] children→who',2,20,'mcq','g9u9.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u9.03' AND x.stem='The children ____ play here are happy.');

-- ===== junior_reading (预期 6) =====
DELETE FROM public.junior_reading WHERE volume='9' AND unit='U9';
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'What Music Do You Like?', 'People like different kinds of music. Some people prefer music that has great lyrics, because the words tell a story. Other people like music that they can dance to. They enjoy fast songs with a strong beat. Some like quiet, smooth music that helps them relax. Others love electronic music that is loud and exciting. There are also people who like singers that play their own instruments. Music is a part of our lives. It can make us happy when we are sad. No matter what kind of music you like, the best music is the music that touches your heart.', '说明文', 101, '[{"q": "What do some people prefer in music?", "answer": "C", "options": ["Silence.", "Loud noise.", "Music that has great lyrics.", "Music with no words."], "explanation": "原文:prefer music that has great lyrics"}, {"q": "Why do some people like music with lyrics?", "answer": "D", "options": ["It is fast.", "It is loud.", "It is cheap.", "The words tell a story."], "explanation": "原文:the words tell a story"}, {"q": "What kind of music helps people relax?", "answer": "C", "options": ["Fast music.", "Loud music.", "Quiet, smooth music.", "Electronic music."], "explanation": "原文:quiet, smooth music that helps them relax"}, {"q": "What do some people love about electronic music?", "answer": "B", "options": ["It is quiet.", "It is loud and exciting.", "It has no beat.", "It is slow."], "explanation": "原文:loud and exciting"}, {"q": "What is the best music according to the writer?", "answer": "A", "options": ["Music that touches your heart.", "Loud music.", "Fast music.", "Old music."], "explanation": "原文:touches your heart"}]'::jsonb, '[{"word": "prefer", "cn": "更喜欢"}, {"word": "lyrics", "cn": "歌词"}, {"word": "smooth", "cn": "悦耳的;平滑的"}]'::jsonb, 3, '9', 'U9');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'What Do You Feel Like Watching?', 'When I am tired, I prefer movies that can cheer me up. Comedies like Kung Fu Panda are funny. The characters may not be perfect, but they try their best to solve their problems. After I watch them, my problems suddenly seem less serious, and I feel much better again. I don''t often like dramas or documentaries when I am sad or tired. Dramas like Titanic make me feel even sadder. Documentaries like March of the Penguins are slow and quiet. But sometimes, when I am bored, I like to watch movies that are scary. They give me something to think about. Once in a while, scary movies are fun.', '说明文', 110, '[{"q": "What kind of movies does the writer prefer when tired?", "answer": "A", "options": ["Movies that can cheer him up.", "Scary movies.", "Slow movies.", "Sad movies."], "explanation": "原文:movies that can cheer me up"}, {"q": "Why does the writer like comedies?", "answer": "C", "options": ["They are sad.", "They are scary.", "The characters try their best.", "They are slow."], "explanation": "原文:try their best to solve their problems"}, {"q": "How does Titanic make the writer feel?", "answer": "D", "options": ["Calmer.", "Happier.", "Braver.", "Even sadder."], "explanation": "原文:make me feel even sadder"}, {"q": "When does the writer like scary movies?", "answer": "B", "options": ["When he is happy.", "When he is bored.", "When he is sad.", "When he is tired."], "explanation": "原文:when I am bored"}, {"q": "What do scary movies give the writer?", "answer": "C", "options": ["A happy ending.", "A quiet night.", "Something to think about.", "A good sleep."], "explanation": "原文:something to think about"}]'::jsonb, '[{"word": "prefer", "cn": "更喜欢"}, {"word": "comedies", "cn": "喜剧片"}, {"word": "serious", "cn": "严重的;严肃的"}]'::jsonb, 3, '9', 'U9');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Sad but Beautiful', 'Abing was a folk musician who was born in the city of Wuxi in 1893. His mother died when he was very young. Abing''s father taught him to play many musical instruments. Sadly, Abing later became ill and could not see. Life grew worse for Abing. He was very poor. Not only that, but he developed a serious illness. He had no home. But Abing did not give up. He kept playing music in the streets. In his lifetime, Abing wrote over 600 pieces of music. His most famous piece is Erquan Yingyue. It is a piece that reflects his hard life, but it is also full of hope. Today, Abing''s music is loved by people all over the world.', '记叙文', 120, '[{"q": "When was Abing born?", "answer": "A", "options": ["In 1893.", "In 1938.", "In 1983.", "In 1839."], "explanation": "原文:born...in 1893"}, {"q": "Who taught Abing to play instruments?", "answer": "A", "options": ["His father.", "His friend.", "His teacher.", "His mother."], "explanation": "原文:father taught him"}, {"q": "What happened to Abing later?", "answer": "A", "options": ["He became ill and could not see.", "He moved away.", "He stopped music.", "He became rich."], "explanation": "原文:became ill and could not see"}, {"q": "How many pieces of music did Abing write?", "answer": "B", "options": ["Over 6000.", "Over 600.", "Over 6.", "Over 60."], "explanation": "原文:over 600 pieces"}, {"q": "What does Erquan Yingyue reflect?", "answer": "D", "options": ["His rich life.", "His travels.", "His happy childhood.", "His hard life."], "explanation": "原文:reflects his hard life"}]'::jsonb, '[{"word": "musician", "cn": "音乐家"}, {"word": "instruments", "cn": "乐器"}, {"word": "lifetime", "cn": "一生"}]'::jsonb, 3, '9', 'U9');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Why We Love Music', 'Why do people all over the world love music? One reason is that music can express our feelings. When we are happy, we sing happy songs. When we feel down, sad music helps us. Music can also bring people together. At a concert, thousands of people who don''t know each other share the same joy. Music has no language. A person who speaks Chinese and a person who speaks English can enjoy the same song. Music can even help us remember things. A song that we heard long ago can bring back old memories. Music is truly a gift that everyone can enjoy.', '议论文', 103, '[{"q": "What is one reason people love music?", "answer": "A", "options": ["It can express our feelings.", "It is free.", "It is fast.", "It is loud."], "explanation": "原文:music can express our feelings"}, {"q": "What do we do when we are happy?", "answer": "C", "options": ["Stay quiet.", "Sing sad songs.", "Sing happy songs.", "Stop singing."], "explanation": "原文:When we are happy, we sing happy songs"}, {"q": "What can music do at a concert?", "answer": "A", "options": ["Bring people together.", "Send people home.", "Stop the noise.", "Make people sad."], "explanation": "原文:bring people together"}, {"q": "Can people who speak different languages enjoy the same song?", "answer": "C", "options": ["Only with words.", "No.", "Yes.", "Only sometimes."], "explanation": "原文:Music has no language"}, {"q": "What can a song from long ago bring back?", "answer": "B", "options": ["New friends.", "Old memories.", "Money.", "Energy."], "explanation": "原文:bring back old memories"}]'::jsonb, '[{"word": "express", "cn": "表达"}, {"word": "feelings", "cn": "情感"}, {"word": "memories", "cn": "回忆"}]'::jsonb, 3, '9', 'U9');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Different Kinds of Movies', 'There are many kinds of movies, and people enjoy different ones. Comedies are movies that make us laugh. They are great when we want to relax. Action movies are movies that are full of exciting scenes. They often have superheroes who save the world. Documentaries are movies that teach us about real life, like nature or history. Some people find them a little slow, but others love to learn from them. Dramas are movies that show strong feelings. They may make us cry. Scary movies are movies that frighten us. Some people love them, while others can''t watch them at all. Which kind of movie do you prefer?', '说明文', 108, '[{"q": "What are comedies?", "answer": "B", "options": ["Movies that scare us.", "Movies that make us laugh.", "Movies that teach us.", "Movies that make us cry."], "explanation": "原文:comedies...make us laugh"}, {"q": "What do action movies often have?", "answer": "B", "options": ["Slow scenes.", "Superheroes who save the world.", "Real history.", "Sad endings."], "explanation": "原文:superheroes who save the world"}, {"q": "What do documentaries teach us about?", "answer": "A", "options": ["Real life, like nature or history.", "Made-up heroes.", "Music.", "Funny stories."], "explanation": "原文:teach us about real life"}, {"q": "What may dramas make us do?", "answer": "D", "options": ["Dance.", "Laugh.", "Sleep.", "Cry."], "explanation": "原文:may make us cry"}, {"q": "What do scary movies do?", "answer": "C", "options": ["Relax us.", "Make us laugh.", "Frighten us.", "Teach us."], "explanation": "原文:scary movies...frighten us"}]'::jsonb, '[{"word": "comedies", "cn": "喜剧片"}, {"word": "superheroes", "cn": "超级英雄"}, {"word": "frighten", "cn": "使害怕"}]'::jsonb, 3, '9', 'U9');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'School Music Club Notice', 'JOIN THE SCHOOL MUSIC CLUB! Do you love music? Come and join us! WHO CAN JOIN: Any student who enjoys music is welcome. You don''t need to be a master. WHAT WE DO: We listen to music that comes from around the world. We also learn to play instruments that are easy for beginners, like the guitar. SPECIAL EVENT: This month, we will watch a documentary that tells the story of Abing, a famous Chinese musician. WHEN: Every Friday, 4:00 p.m. to 5:30 p.m. WHERE: Music Room 203. Come and meet friends who share your love of music. Music is a gift that everyone can enjoy!', '应用文', 106, '[{"q": "Who can join the music club?", "answer": "C", "options": ["Only singers.", "Only teachers.", "Any student who enjoys music.", "Only masters."], "explanation": "原文:Any student who enjoys music"}, {"q": "What instruments do they learn?", "answer": "D", "options": ["Hard instruments.", "Only the piano.", "No instruments.", "Instruments easy for beginners, like the guitar."], "explanation": "原文:easy for beginners, like the guitar"}, {"q": "What is the special event this month?", "answer": "D", "options": ["A test.", "A concert.", "A dance.", "A documentary about Abing."], "explanation": "原文:documentary that tells the story of Abing"}, {"q": "When does the club meet?", "answer": "D", "options": ["Every Monday.", "On weekends.", "Every day.", "Every Friday."], "explanation": "原文:Every Friday"}, {"q": "Where does the club meet?", "answer": "B", "options": ["The gym.", "Music Room 203.", "Room 105.", "The library."], "explanation": "原文:Music Room 203"}]'::jsonb, '[{"word": "master", "cn": "大师;能手"}, {"word": "documentary", "cn": "纪录片"}, {"word": "instrument", "cn": "乐器;器械"}]'::jsonb, 3, '9', 'U9');

-- ===== junior_cloze (预期 6) =====
DELETE FROM public.junior_cloze WHERE volume='9' AND unit='U9';
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U9', 'The Music I Love', 'I love music more than anything. I prefer music (1)____ I can sing along with. When I feel (2)____, a happy song can cheer me up. My favorite (3)____ are pop and rock. I like songs that have great (4)____, because the words tell a story. My friend Lisa likes (5)____ music that helps her relax. My brother prefers (6)____ music that is loud and fast. We all like (7)____ kinds of music, but that''s okay. Music is a (8)____ that everyone can enjoy. No matter what kind you like, the best music is the music that (9)____ your heart. That''s why I will always (10)____ music.', 107, 3, '[{"q": "1", "answer": "A", "options": ["that", "where", "whose", "who"], "explanation": "[定从] music是物→that"}, {"q": "2", "answer": "A", "options": ["down", "glad", "happy", "up"], "explanation": "沮丧 feel down"}, {"q": "3", "answer": "A", "options": ["kinds", "game", "color", "price"], "explanation": "种类 kinds"}, {"q": "4", "answer": "C", "options": ["game", "price", "lyrics", "color"], "explanation": "歌词 lyrics"}, {"q": "5", "answer": "D", "options": ["loud", "fast", "sour", "smooth"], "explanation": "悦耳 smooth"}, {"q": "6", "answer": "B", "options": ["soft", "electronic", "slow", "quiet"], "explanation": "电子 electronic"}, {"q": "7", "answer": "B", "options": ["quiet", "different", "empty", "same"], "explanation": "不同 different"}, {"q": "8", "answer": "C", "options": ["game", "color", "gift", "price"], "explanation": "礼物 gift"}, {"q": "9", "answer": "B", "options": ["breaks", "touches", "loses", "throws"], "explanation": "触动 touches"}, {"q": "10", "answer": "D", "options": ["leave", "lose", "hate", "love"], "explanation": "爱 love"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U9', 'My Favorite Movies', 'I love watching movies in my (1)____ time. I prefer movies (2)____ make me laugh. Comedies are my favorite (3)____. When I am tired, a funny movie can (4)____ me up. I don''t like movies that are too (5)____, because they make me feel down. My sister likes (6)____ that teach her about real life, like nature films. My father prefers (7)____ movies with superheroes who save the world. Once in a (8)____, I watch a scary movie, but only with friends. After a movie, I always feel more (9)____. Watching movies is a great way to (10)____ after a busy week.', 102, 3, '[{"q": "1", "answer": "B", "options": ["work", "spare", "study", "busy"], "explanation": "空闲 spare time"}, {"q": "2", "answer": "D", "options": ["where", "who", "whose", "that"], "explanation": "[定从] movies是物→that"}, {"q": "3", "answer": "A", "options": ["kind", "price", "color", "game"], "explanation": "种类 kind"}, {"q": "4", "answer": "B", "options": ["lose", "cheer", "break", "throw"], "explanation": "使振奋 cheer up"}, {"q": "5", "answer": "D", "options": ["funny", "glad", "happy", "sad"], "explanation": "悲伤 sad"}, {"q": "6", "answer": "B", "options": ["prices", "documentaries", "games", "colors"], "explanation": "纪录片 documentaries"}, {"q": "7", "answer": "A", "options": ["action", "soft", "quiet", "slow"], "explanation": "动作 action movies"}, {"q": "8", "answer": "C", "options": ["color", "time", "while", "price"], "explanation": "偶尔 once in a while"}, {"q": "9", "answer": "A", "options": ["relaxed", "sad", "tired", "busy"], "explanation": "放松 relaxed"}, {"q": "10", "answer": "C", "options": ["study", "cry", "relax", "work"], "explanation": "放松 relax"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U9', 'Abing''s Story', 'Abing was a folk musician (1)____ was born in Wuxi. When he was young, his mother (2)____. His father taught him to play many musical (3)____. Sadly, Abing later became (4)____ and could not see. His life grew very (5)____. He was poor and had no home. But Abing never gave (6)____. He kept playing music in the (7)____. In his lifetime, he wrote over 600 (8)____ of music. His most famous piece (9)____ his hard life but is full of hope. Today, his music is (10)____ by people all over the world. Abing''s story is sad but beautiful.', 99, 3, '[{"q": "1", "answer": "A", "options": ["who", "where", "which", "whose"], "explanation": "[定从] musician是人→who"}, {"q": "2", "answer": "B", "options": ["lived", "died", "ran", "sang"], "explanation": "去世 died"}, {"q": "3", "answer": "B", "options": ["prices", "instruments", "games", "colors"], "explanation": "乐器 instruments"}, {"q": "4", "answer": "D", "options": ["strong", "happy", "rich", "ill"], "explanation": "生病 ill"}, {"q": "5", "answer": "B", "options": ["rich", "hard", "easy", "good"], "explanation": "艰难 hard"}, {"q": "6", "answer": "C", "options": ["off", "on", "up", "in"], "explanation": "放弃 give up"}, {"q": "7", "answer": "A", "options": ["streets", "color", "game", "price"], "explanation": "街头 streets"}, {"q": "8", "answer": "D", "options": ["prices", "games", "colors", "pieces"], "explanation": "首 pieces of music"}, {"q": "9", "answer": "A", "options": ["reflects", "loses", "breaks", "throws"], "explanation": "反映 reflects"}, {"q": "10", "answer": "C", "options": ["hated", "lost", "loved", "sold"], "explanation": "被喜爱 loved"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U9', 'A Concert Night', 'Last weekend, I went to a concert with my (1)____. The singer was an artist (2)____ writes her own songs. The music hall was full of people (3)____ love music. When the music started, everyone felt (4)____. The singer''s voice was (5)____ and beautiful. She sang songs that had great (6)____. Some songs were happy, and some were (7)____. One song was so (8)____ that many people cried. Music can (9)____ our feelings in a special way. After the concert, I felt (10)____ and happy. It was a night I will never forget. I hope to go to another concert soon.', 101, 3, '[{"q": "1", "answer": "B", "options": ["color", "friends", "game", "price"], "explanation": "朋友 friends"}, {"q": "2", "answer": "B", "options": ["whose", "who", "where", "which"], "explanation": "[定从] artist是人→who"}, {"q": "3", "answer": "D", "options": ["which", "where", "whose", "who"], "explanation": "[定从] people是人→who"}, {"q": "4", "answer": "D", "options": ["tired", "sad", "bored", "excited"], "explanation": "兴奋 excited"}, {"q": "5", "answer": "C", "options": ["sour", "fast", "smooth", "loud"], "explanation": "悦耳 smooth"}, {"q": "6", "answer": "A", "options": ["lyrics", "prices", "games", "colors"], "explanation": "歌词 lyrics"}, {"q": "7", "answer": "A", "options": ["sad", "funny", "fast", "quiet"], "explanation": "悲伤 sad"}, {"q": "8", "answer": "B", "options": ["boring", "moving", "cheap", "easy"], "explanation": "动人 moving"}, {"q": "9", "answer": "A", "options": ["express", "lose", "throw", "break"], "explanation": "表达 express"}, {"q": "10", "answer": "C", "options": ["busy", "tired", "relaxed", "angry"], "explanation": "放松 relaxed"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U9', 'Kinds of Movies', 'There are many kinds of movies (1)____ people enjoy. Comedies are movies that make us (2)____. They are great when we want to (3)____. Action movies are full of exciting (4)____. They often have superheroes (5)____ save the world. Documentaries are movies that (6)____ us about real life. Some people find them (7)____, but others love them. Dramas are movies that show strong (8)____. They may make us cry. Scary movies (9)____ us, and not everyone likes them. There is a kind of movie for everyone. Which kind do you (10)____?', 91, 3, '[{"q": "1", "answer": "D", "options": ["who", "where", "whose", "that"], "explanation": "[定从] movies是物→that"}, {"q": "2", "answer": "A", "options": ["laugh", "sleep", "run", "cry"], "explanation": "笑 laugh"}, {"q": "3", "answer": "C", "options": ["fight", "study", "relax", "work"], "explanation": "放松 relax"}, {"q": "4", "answer": "B", "options": ["colors", "scenes", "prices", "games"], "explanation": "场面 scenes"}, {"q": "5", "answer": "A", "options": ["who", "which", "where", "whose"], "explanation": "[定从] superheroes是人→who"}, {"q": "6", "answer": "A", "options": ["teach", "lose", "throw", "break"], "explanation": "教 teach"}, {"q": "7", "answer": "B", "options": ["loud", "slow", "fast", "sweet"], "explanation": "慢 slow"}, {"q": "8", "answer": "D", "options": ["colors", "games", "prices", "feelings"], "explanation": "情感 feelings"}, {"q": "9", "answer": "B", "options": ["help", "frighten", "teach", "save"], "explanation": "使害怕 frighten"}, {"q": "10", "answer": "C", "options": ["lose", "break", "prefer", "throw"], "explanation": "更喜欢 prefer"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U9', 'Music Brings Us Together', 'Music is something (1)____ everyone in the world can enjoy. It has no (2)____. A person who speaks Chinese and a person (3)____ speaks English can love the same song. Music can (4)____ our feelings. When we are happy, we sing happy (5)____. When we feel down, sad music (6)____ us. Music can also bring people (7)____. At a concert, thousands of strangers share the same (8)____. A song that we heard long ago can bring back old (9)____. Music is truly a (10)____ that everyone can enjoy. That is why music is loved all over the world.', 98, 3, '[{"q": "1", "answer": "B", "options": ["who", "that", "whose", "where"], "explanation": "[定从] something是物→that"}, {"q": "2", "answer": "D", "options": ["color", "price", "game", "language"], "explanation": "语言 language"}, {"q": "3", "answer": "C", "options": ["where", "which", "who", "whose"], "explanation": "[定从] person是人→who"}, {"q": "4", "answer": "B", "options": ["break", "express", "lose", "throw"], "explanation": "表达 express"}, {"q": "5", "answer": "C", "options": ["colors", "prices", "songs", "games"], "explanation": "歌 songs"}, {"q": "6", "answer": "B", "options": ["throws", "helps", "breaks", "loses"], "explanation": "帮助 helps"}, {"q": "7", "answer": "A", "options": ["together", "apart", "away", "alone"], "explanation": "一起 together"}, {"q": "8", "answer": "A", "options": ["joy", "game", "price", "color"], "explanation": "喜悦 joy"}, {"q": "9", "answer": "D", "options": ["colors", "prices", "games", "memories"], "explanation": "回忆 memories"}, {"q": "10", "answer": "A", "options": ["gift", "game", "color", "price"], "explanation": "礼物 gift"}]'::jsonb, 6);

-- ===== junior_listening_exercises (预期 6) =====
DELETE FROM public.junior_listening_exercises WHERE volume='9' AND unit='U9';
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U9 听力·对话 What Music Do You Like', '九年级 Unit9 听力·音乐与电影/定语从句', 2, 'W: What kind of music do you like?
M: I like music that I can dance to. What about you?
W: I prefer music that has great lyrics.
M: Do you like the Australian singer Dan Dervish?
W: Yes! I love musicians who write their own songs.', '女:你喜欢哪种音乐?
男:我喜欢能跟着跳舞的音乐。你呢?
女:我更喜欢有好歌词的音乐。
男:你喜欢澳大利亚歌手丹·德维什吗?
女:喜欢!我爱那些自己写歌的音乐人。', 'us_male', '[{"q": "What kind of music does the man like?", "type": "choice", "answer": "C", "options": ["Electronic music.", "Music with great lyrics.", "Music that he can dance to.", "Quiet music."]}, {"q": "What does the woman prefer?", "type": "choice", "answer": "C", "options": ["Music to dance to.", "Slow music.", "Music that has great lyrics.", "Loud music."]}, {"q": "Where is Dan Dervish from?", "type": "choice", "answer": "A", "options": ["Australia.", "China.", "Britain.", "America."]}, {"q": "What musicians does the woman love?", "type": "choice", "answer": "A", "options": ["Those who write their own songs.", "Those who dance.", "Those who are young.", "Those who are famous."]}, {"q": "Do they like the same music?", "type": "choice", "answer": "C", "options": ["Sometimes.", "Yes.", "No.", "Always."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U9');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U9 听力·短文 Abing''s Story', '九年级 Unit9 听力·音乐与电影/定语从句', 2, 'Abing was a folk musician who was born in Wuxi.
His father taught him to play many instruments.
Sadly, Abing became ill and could not see.
But he never gave up and played music in the streets.
He wrote over 600 pieces of music in his lifetime.', '阿炳是出生在无锡的民间音乐家。
他的父亲教他演奏许多乐器。
不幸的是,阿炳生病了,看不见东西。
但他从不放弃,在街头演奏音乐。
他一生创作了600多首乐曲。', 'us_female', '[{"q": "Where was Abing born?", "type": "choice", "answer": "C", "options": ["In Beijing.", "In Wuhan.", "In Wuxi.", "In Shanghai."]}, {"q": "Who taught Abing to play instruments?", "type": "choice", "answer": "C", "options": ["His teacher.", "His friend.", "His father.", "His mother."]}, {"q": "What happened to Abing?", "type": "choice", "answer": "A", "options": ["He became ill and could not see.", "He became rich.", "He stopped music.", "He moved away."]}, {"q": "Did Abing give up?", "type": "choice", "answer": "A", "options": ["No.", "Yes.", "At first.", "Sometimes."]}, {"q": "How many pieces did Abing write?", "type": "choice", "answer": "C", "options": ["Over 6000.", "Over 60.", "Over 600.", "Over 6."]}]'::jsonb, '[]'::jsonb, 'short', '9', 'U9');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U9 听力·对话 Choosing a Movie', '九年级 Unit9 听力·音乐与电影/定语从句', 2, 'W: Do you want to watch a movie tonight?
M: Sure! I like movies that make me laugh.
W: So you prefer comedies?
M: Yes. I don''t like movies that are too scary.
W: Then let''s watch a funny one.', '女:今晚想看电影吗?
男:好啊!我喜欢能让我发笑的电影。
女:所以你更喜欢喜剧?
男:是的。我不喜欢太吓人的电影。
女:那我们看一部搞笑的吧。', 'us_male', '[{"q": "What kind of movies does the man like?", "type": "choice", "answer": "D", "options": ["Sad movies.", "Slow movies.", "Scary movies.", "Movies that make him laugh."]}, {"q": "What does the man prefer?", "type": "choice", "answer": "B", "options": ["Horror films.", "Comedies.", "Documentaries.", "Dramas."]}, {"q": "What movies does the man not like?", "type": "choice", "answer": "D", "options": ["Short movies.", "Funny movies.", "New movies.", "Movies that are too scary."]}, {"q": "What will they watch?", "type": "choice", "answer": "D", "options": ["A long one.", "A sad one.", "A scary one.", "A funny one."]}, {"q": "When will they watch the movie?", "type": "choice", "answer": "A", "options": ["Tonight.", "Next week.", "Tomorrow.", "This morning."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U9');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U9 听力·短文 Why We Love Music', '九年级 Unit9 听力·音乐与电影/定语从句', 2, 'People all over the world love music.
One reason is that music can express our feelings.
Music can also bring people together at a concert.
Music has no language, so everyone can enjoy it.
A song from long ago can bring back old memories.', '全世界的人都热爱音乐。
一个原因是音乐能表达我们的情感。
音乐还能在音乐会上把人们聚到一起。
音乐没有语言界限,所以人人都能欣赏。
一首很久以前的歌能唤起旧日的回忆。', 'us_female', '[{"q": "Who loves music?", "type": "choice", "answer": "B", "options": ["Only singers.", "People all over the world.", "Only teachers.", "Only young people."]}, {"q": "What can music express?", "type": "choice", "answer": "C", "options": ["Our names.", "Our age.", "Our feelings.", "Our money."]}, {"q": "What can music do at a concert?", "type": "choice", "answer": "A", "options": ["Bring people together.", "Send people home.", "Stop the show.", "Make people sad."]}, {"q": "Why can everyone enjoy music?", "type": "choice", "answer": "D", "options": ["Music is loud.", "Music is cheap.", "Music is short.", "Music has no language."]}, {"q": "What can an old song bring back?", "type": "choice", "answer": "B", "options": ["Money.", "Old memories.", "Energy.", "New friends."]}]'::jsonb, '[]'::jsonb, 'short', '9', 'U9');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U9 听力·对话 At the Music Club', '九年级 Unit9 听力·音乐与电影/定语从句', 2, 'W: I want to join the music club. Can anyone join?
M: Yes, any student who enjoys music is welcome.
W: Great! What do you do there?
M: We listen to music that comes from around the world.
W: That sounds fun. I''ll join this Friday.', '女:我想加入音乐社。任何人都能加入吗?
男:是的,任何喜欢音乐的学生都欢迎。
女:太好了!你们在那里做什么?
男:我们听来自世界各地的音乐。
女:听起来很有趣。我这周五就加入。', 'us_male', '[{"q": "What does the woman want to do?", "type": "choice", "answer": "D", "options": ["Start a club.", "Watch a movie.", "Leave the club.", "Join the music club."]}, {"q": "Who can join the club?", "type": "choice", "answer": "D", "options": ["Only masters.", "Only teachers.", "Only singers.", "Any student who enjoys music."]}, {"q": "What do they do in the club?", "type": "choice", "answer": "D", "options": ["Watch films.", "Play sports.", "Read books.", "Listen to music from around the world."]}, {"q": "When will the woman join?", "type": "choice", "answer": "A", "options": ["This Friday.", "Next week.", "Today.", "This Monday."]}, {"q": "What does the woman think of the club?", "type": "choice", "answer": "C", "options": ["It sounds boring.", "It sounds hard.", "It sounds fun.", "It sounds strange."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U9');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U9 听力·短文 Kinds of Movies', '九年级 Unit9 听力·音乐与电影/定语从句', 2, 'There are many kinds of movies for people to enjoy.
Comedies are movies that make us laugh.
Action movies have superheroes who save the world.
Documentaries teach us about real life.
Everyone can find a kind of movie that they like.', '有许多种电影供人们欣赏。
喜剧是让我们发笑的电影。
动作片里有拯救世界的超级英雄。
纪录片教我们了解真实生活。
每个人都能找到自己喜欢的电影类型。', 'us_female', '[{"q": "What do comedies do?", "type": "choice", "answer": "B", "options": ["Make us cry.", "Make us laugh.", "Scare us.", "Teach us."]}, {"q": "What do action movies have?", "type": "choice", "answer": "A", "options": ["Superheroes who save the world.", "Sad endings.", "Slow scenes.", "Real history."]}, {"q": "What do documentaries teach us about?", "type": "choice", "answer": "B", "options": ["Made-up stories.", "Real life.", "Sports.", "Music."]}, {"q": "Can everyone find a movie they like?", "type": "choice", "answer": "B", "options": ["Only adults.", "Yes.", "Only children.", "No."]}, {"q": "What is the passage about?", "type": "choice", "answer": "B", "options": ["How to make movies.", "Kinds of movies.", "Where to buy tickets.", "Why movies are cheap."]}]'::jsonb, '[]'::jsonb, 'short', '9', 'U9');

-- ===== junior_writing_prompts (预期 1) =====
INSERT INTO public.junior_writing_prompts (id, grade, topic, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, difficulty, title_en, high_sentences, error_pairs, paragraph_template, volume, unit) SELECT gen_random_uuid(), 9, 'The Music (or Movies) I Like', '用定语从句(that/which/who)介绍你喜欢的音乐或电影。写清你喜欢哪种、为什么喜欢、它给你什么感受。60词左右。', 'Write a short passage on the topic: "The Music (or Movies) I Like".', '["你喜欢哪种音乐/电影(用定语从句:music/movies that...)", "为什么喜欢", "你喜欢的歌手/导演(用who:singers who...)", "它给你的感受"]'::jsonb, 70, 100, 'I love music that I can sing along with. I prefer pop songs that have great lyrics, because the words tell a story. My favorite singer is a musician who writes her own songs. When I feel down, music that is happy can cheer me up. When I am tired, smooth music that is quiet helps me relax. Music is a gift that touches my heart, and that is why I love it so much.', 'content:含喜欢的类型/原因/歌手/感受(4分)；language:正确使用定语从句that/which/who(3分)；structure:语句通顺、衔接得当(2分)；wordcount:词数达标、书写规范(1分)', 3, 'The Music (or Movies) I Like', '["I like music/movies that ...", "I prefer ... that ...", "singers/people who ...", "music that I can dance to", "movies that make me laugh", "It makes me feel ..."]'::jsonb, '[]'::jsonb, '要点:你喜欢哪种音乐/电影(用定语从句:music/movies that...)；为什么喜欢；你喜欢的歌手/导演(用who:singers who...)；它给你的感受', '9', 'U9' WHERE NOT EXISTS (SELECT 1 FROM public.junior_writing_prompts WHERE volume='9' AND unit='U9' AND topic='The Music (or Movies) I Like');

COMMIT;

-- ===== count 校验 =====
SELECT 'grammar_points' k, count(*) v, 3 expect FROM public.junior_grammar_points WHERE volume='9' AND unit='U9'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.volume='9' AND p.unit='U9'
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='9' AND unit='U9'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='9' AND unit='U9'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='9' AND unit='U9'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='9' AND unit='U9';