-- ===== U14 vocab 覆盖灌库(volume='9',44词)。分步跑。=====

SELECT 'U14 灌前' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14';

DELETE FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14';
SELECT 'U14 DELETE后' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14';  -- 应0

INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'survey', 'n.', '/ˈsɜː(r)veɪ/', '调查', 'a class survey', 1, 'jr-9-U14-0001', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='survey');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'standard', 'n.', '/ˈstændə(r)d/', '标准;水平', 'a high standard', 2, 'jr-9-U14-0002', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='standard');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'row', 'n.', '/rəʊ/', '一排;一列;一行', 'the front row', 3, 'jr-9-U14-0003', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='row');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'in a row', '', '', '连续几次地', 'three times in a row', 4, 'jr-9-U14-0004', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='in a row');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'keyboard', 'n.', '/ˈkiːbɔː(r)d/', '键盘式电子乐器;键盘', 'play the keyboard', 5, 'jr-9-U14-0005', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='keyboard');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'method', 'n.', '/ˈmeθəd/', '方法;措施', 'a good method', 6, 'jr-9-U14-0006', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='method');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'instruction', 'n.', '/ɪnˈstrʌkʃn/', '指示;命令', 'follow the instructions', 7, 'jr-9-U14-0007', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='instruction');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'double', 'v.', '/ˈdʌbl/', '加倍;是……的两倍;adj. 两倍的', 'double the number', 8, 'jr-9-U14-0008', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='double');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'shall', 'modal v.', '/ʃæl, ʃəl/', '将要;将会', 'shall we go', 9, 'jr-9-U14-0009', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='shall');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'look back at', '', '', '回首(往事);回忆;回顾', 'look back at the past', 10, 'jr-9-U14-0010', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='look back at');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'overcome', 'v.', '/ˌəʊvə(r)ˈkʌm/', '(overcame, overcome)克服;战胜', 'overcome a problem', 11, 'jr-9-U14-0011', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='overcome');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'make a mess', '', '', '弄得一团糟(一塌糊涂)', 'make a mess', 12, 'jr-9-U14-0012', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='make a mess');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'graduate', 'v.', '/ˈɡrædʒueɪt/', '毕业;获得学位', 'graduate from', 13, 'jr-9-U14-0013', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='graduate');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'keep one''s cool', '', '', '沉住气;保持冷静', 'keep one''s cool', 14, 'jr-9-U14-0014', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='keep one''s cool');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'caring', 'adj.', '/ˈkeərɪŋ/', '体贴人的;关心他人的', 'a caring teacher', 15, 'jr-9-U14-0015', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='caring');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'ours', 'pron.', '/ˈaʊə(r)z/', '我们的', 'ours is better', 16, 'jr-9-U14-0016', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='ours');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'senior', 'adj.', '/ˈsiːniə(r)/', '级别(或地位)高的', 'senior students', 17, 'jr-9-U14-0017', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='senior');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'senior high (school)', '', '', '高中', 'senior high school', 18, 'jr-9-U14-0018', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='senior high (school)');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'text', 'n.', '/tekst/', '课文;文本', 'read the text', 19, 'jr-9-U14-0019', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='text');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'go by', '', '', '(时间)逝去;过去', 'time goes by', 20, 'jr-9-U14-0020', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='go by');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'level', 'n.', '/ˈlevl/', '水平', 'a high level', 21, 'jr-9-U14-0021', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='level');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'degree', 'n.', '/dɪˈɡriː/', '(大学)学位;度数;程度', 'a college degree', 22, 'jr-9-U14-0022', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='degree');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'manager', 'n.', '/ˈmænɪdʒə(r)/', '经理;经营者', 'a shop manager', 23, 'jr-9-U14-0023', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='manager');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'believe in', '', '', '信任;信赖', 'believe in yourself', 24, 'jr-9-U14-0024', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='believe in');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'gentleman', 'n.', '/ˈdʒentlmən/', '先生;绅士', 'a kind gentleman', 25, 'jr-9-U14-0025', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='gentleman');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'graduation', 'n.', '/ˌɡrædʒuˈeɪʃn/', '毕业', 'graduation day', 26, 'jr-9-U14-0026', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='graduation');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'ceremony', 'n.', '/ˈserəməni/', '典礼;仪式', 'a graduation ceremony', 27, 'jr-9-U14-0027', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='ceremony');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'first of all', '', '', '首先', 'first of all', 28, 'jr-9-U14-0028', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='first of all');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'congratulate', 'v.', '/kənˈɡrætʃuleɪt/', '祝贺', 'congratulate you', 29, 'jr-9-U14-0029', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='congratulate');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'thirsty', 'adj.', '/ˈθɜː(r)sti/', '渴望的;口渴的', 'thirsty for knowledge', 30, 'jr-9-U14-0030', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='thirsty');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'be thirsty for', '', '', '渴望;渴求', 'be thirsty for success', 31, 'jr-9-U14-0031', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='be thirsty for');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'thankful', 'adj.', '/ˈθæŋkfl/', '感谢;感激', 'be thankful', 32, 'jr-9-U14-0032', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='thankful');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'be thankful to sb.', '', '', '对某人心存感激', 'be thankful to them', 33, 'jr-9-U14-0033', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='be thankful to sb.');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'lastly', 'adv.', '/ˈlɑːstli, ˈlæstli/', '最后', 'lastly, thank you', 34, 'jr-9-U14-0034', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='lastly');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'task', 'n.', '/tɑːsk, tæsk/', '任务;工作', 'a hard task', 35, 'jr-9-U14-0035', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='task');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'ahead', 'adv.', '/əˈhed/', '向前面;在前面', 'go ahead', 36, 'jr-9-U14-0036', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='ahead');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'ahead of', '', '', '在……前面', 'ahead of others', 37, 'jr-9-U14-0037', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='ahead of');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'along with', '', '', '连同;除……以外还', 'along with others', 38, 'jr-9-U14-0038', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='along with');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'responsible', 'adj.', '/rɪˈspɒnsəbl, rɪˈspɑːnsəbl/', '有责任心的', 'a responsible person', 39, 'jr-9-U14-0039', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='responsible');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'be responsible for', '', '', '对……有责任;负责任', 'responsible for it', 40, 'jr-9-U14-0040', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='be responsible for');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'separate', 'adj.', '/ˈsepərət/', '单独的;分离的;/ˈsepəreɪt/ v. 分开', 'separate rooms', 41, 'jr-9-U14-0041', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='separate');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'set out', '', '', '出发;启程', 'set out early', 42, 'jr-9-U14-0042', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='set out');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'separate from', '', '', '分离;隔开', 'separate from others', 43, 'jr-9-U14-0043', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='separate from');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'wing', 'n.', '/wɪŋ/', '翅膀;翼', 'spread its wings', 44, 'jr-9-U14-0044', 'junior', '9', 'U14', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' AND word='wing');

SELECT 'U14 INSERT后' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14';  -- 应44
SELECT word, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U14' GROUP BY word HAVING count(*)>1;  -- 查重应0行