-- ===== U3/U4 vocab 覆盖灌库(volume='9')。分步跑,每步贴回 count。=====


-- ========================= U3 (39 词) =========================
-- [step0] 灌前 count(预期 31)
SELECT 'U3 灌前' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3';

-- [step1] DELETE 旧词(键对准旧骨架实际存储:grade=9 volume='9' unit='U3')
DELETE FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3';
-- [step1 验证] 预期 0
SELECT 'U3 DELETE后' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3';

-- [step2] INSERT 官方 39 词(volume='9';含 WHERE NOT EXISTS 防重)
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'restroom', 'n.', '/ˈrestruːm/', '(美)洗手间;公共厕所', 'find the restroom', 1, 'jr-9-U3-0001', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='restroom');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'stamp', 'n.', '/stæmp/', '邮票;印章', 'buy some stamps', 2, 'jr-9-U3-0002', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='stamp');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'bookstore', 'n.', '/ˈbʊkstɔː(r)/', '书店', 'go to the bookstore', 3, 'jr-9-U3-0003', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='bookstore');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'beside', 'prep.', '/bɪˈsaɪd/', '在……旁边;在……附近', 'beside the bank', 4, 'jr-9-U3-0004', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='beside');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'postcard', 'n.', '/ˈpəʊstkɑːd/', '明信片', 'send a postcard', 5, 'jr-9-U3-0005', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='postcard');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'pardon', 'interj. & v.', '/ˈpɑːdn/', '请再说一遍;原谅', 'Pardon me?', 6, 'jr-9-U3-0006', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='pardon');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'washroom', 'n.', '/ˈwɒʃruːm/', '洗手间;厕所', 'go to the washroom', 7, 'jr-9-U3-0007', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='washroom');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'bathroom', 'n.', '/ˈbɑːθruːm/', '浴室;洗手间', 'clean the bathroom', 8, 'jr-9-U3-0008', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='bathroom');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'normally', 'adv.', '/ˈnɔːməli/', '通常;正常情况下', 'normally open', 9, 'jr-9-U3-0009', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='normally');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'rush', 'v. & n.', '/rʌʃ/', '仓促;急促', 'rush to school', 10, 'jr-9-U3-0010', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='rush');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'suggest', 'v.', '/səˈdʒest/', '建议;提议', 'suggest a place', 11, 'jr-9-U3-0011', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='suggest');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'pass by', '', '', '路过;经过', 'pass by the shop', 12, 'jr-9-U3-0012', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='pass by');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'staff', 'n.', '/stɑːf/', '管理人员;职工', 'ask the staff', 13, 'jr-9-U3-0013', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='staff');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'grape', 'n.', '/ɡreɪp/', '葡萄', 'buy some grapes', 14, 'jr-9-U3-0014', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='grape');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'central', 'adj.', '/ˈsentrəl/', '中心的;中央的', 'the central park', 15, 'jr-9-U3-0015', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='central');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'nearby', 'adj. & adv.', '/ˌnɪəˈbaɪ/', '附近的;在附近', 'a shop nearby', 16, 'jr-9-U3-0016', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='nearby');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'mail', 'n. & v.', '/meɪl/', '邮寄;邮件;信件', 'mail a letter', 17, 'jr-9-U3-0017', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='mail');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'east', 'adj. & adv.', '/iːst/', '东方的;向东;东方', 'in the east', 18, 'jr-9-U3-0018', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='east');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'fascinating', 'adj.', '/ˈfæsɪneɪtɪŋ/', '迷人的;极有吸引力的', 'a fascinating city', 19, 'jr-9-U3-0019', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='fascinating');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'inexpensive', 'adj.', '/ˌɪnɪkˈspensɪv/', '不昂贵的', 'inexpensive food', 20, 'jr-9-U3-0020', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='inexpensive');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'uncrowded', 'adj.', '/ˌʌnˈkraʊdɪd/', '不拥挤的;人少的', 'an uncrowded street', 21, 'jr-9-U3-0021', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='uncrowded');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'convenient', 'adj.', '/kənˈviːniənt/', '便利的;方便的', 'very convenient', 22, 'jr-9-U3-0022', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='convenient');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'mall', 'n.', '/mɔːl/', '商场;购物中心', 'a shopping mall', 23, 'jr-9-U3-0023', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='mall');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'clerk', 'n.', '/klɑːk/', '职员', 'ask the clerk', 24, 'jr-9-U3-0024', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='clerk');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'corner', 'n.', '/ˈkɔːnə(r)/', '拐角;角落', 'at the corner', 25, 'jr-9-U3-0025', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='corner');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'politely', 'adv.', '/pəˈlaɪtli/', '礼貌地;客气地', 'ask politely', 26, 'jr-9-U3-0026', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='politely');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'request', 'n. & v.', '/rɪˈkwest/', '要求;请求', 'make a request', 27, 'jr-9-U3-0027', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='request');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'direction', 'n.', '/dəˈrekʃn, daɪˈrekʃn/', '方向;方位', 'ask for directions', 28, 'jr-9-U3-0028', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='direction');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'correct', 'adj.', '/kəˈrekt/', '正确的;恰当的', 'the correct way', 29, 'jr-9-U3-0029', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='correct');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'polite', 'adj.', '/pəˈlaɪt/', '有礼貌的;客气的', 'a polite question', 30, 'jr-9-U3-0030', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='polite');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'direct', 'adj.', '/dəˈrekt, daɪˈrekt/', '直接的;直率的', 'a direct question', 31, 'jr-9-U3-0031', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='direct');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'speaker', 'n.', '/ˈspiːkə(r)/', '讲(某种语言)的人;发言者', 'a native speaker', 32, 'jr-9-U3-0032', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='speaker');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'whom', 'pron.', '/huːm/', '谁;什么人', 'with whom', 33, 'jr-9-U3-0033', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='whom');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'impolite', 'adj.', '/ˌɪmpəˈlaɪt/', '不礼貌的;粗鲁的', 'sound impolite', 34, 'jr-9-U3-0034', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='impolite');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'address', 'n.', '/əˈdres, ˈædres/', '住址;地址;通信处', 'write the address', 35, 'jr-9-U3-0035', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='address');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'underground', 'adj.', '/ˈʌndəɡraʊnd/', '地下的;n. 地铁', 'the underground', 36, 'jr-9-U3-0036', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='underground');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'parking lot', 'n.', '', '停车场;停车区', 'in the parking lot', 37, 'jr-9-U3-0037', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='parking lot');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'course', 'n.', '/kɔː(r)s/', '课程;学科', 'take a course', 38, 'jr-9-U3-0038', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='course');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'Italian', 'adj. & n.', '/ɪˈtæliən/', '意大利(人)的;意大利人;意大利语', 'an Italian restaurant', 39, 'jr-9-U3-0039', 'junior', '9', 'U3', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3' AND word='Italian');
-- [step2 验证] 预期 39
SELECT 'U3 INSERT后' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U3';

-- ========================= U4 (39 词) =========================
-- [step0] 灌前 count(预期 29)
SELECT 'U4 灌前' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4';

-- [step1] DELETE 旧词(键对准旧骨架实际存储:grade=9 volume='9' unit='U4')
DELETE FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4';
-- [step1 验证] 预期 0
SELECT 'U4 DELETE后' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4';

-- [step2] INSERT 官方 39 词(volume='9';含 WHERE NOT EXISTS 防重)
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'humorous', 'adj.', '/ˈhjuːmərəs/', '有幽默感的;滑稽有趣的', 'a humorous person', 1, 'jr-9-U4-0001', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='humorous');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'silent', 'adj.', '/ˈsaɪlənt/', '不说话的;沉默的', 'stay silent', 2, 'jr-9-U4-0002', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='silent');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'helpful', 'adj.', '/ˈhelpfl/', '有用的;有帮助的', 'be helpful to others', 3, 'jr-9-U4-0003', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='helpful');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'from time to time', '', '', '时常;有时', 'change from time to time', 4, 'jr-9-U4-0004', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='from time to time');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'score', 'n. & v.', '/skɔː(r)/', '得分;进球', 'score a goal', 5, 'jr-9-U4-0005', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='score');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'background', 'n.', '/ˈbækɡraʊnd/', '背景', 'a family background', 6, 'jr-9-U4-0006', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='background');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'interview', 'v.', '/ˈɪntəvjuː/', '采访;面试;n. 面试;访谈', 'an interview at school', 7, 'jr-9-U4-0007', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='interview');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'Asian', 'adj.', '/ˈeɪʃn, ˈeɪʒn/', '亚洲(人)的;n. 亚洲人', 'an Asian pop star', 8, 'jr-9-U4-0008', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='Asian');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'deal', 'v.', '/diːl/', '对付;对待', 'deal with problems', 9, 'jr-9-U4-0009', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='deal');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'deal with', '', '', '应对;处理', 'deal with a problem', 10, 'jr-9-U4-0010', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='deal with');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'shyness', 'n.', '/ˈʃaɪnəs/', '害羞;腼腆', 'overcome shyness', 11, 'jr-9-U4-0011', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='shyness');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'dare', 'v.', '/deə(r)/', '敢于;胆敢', 'dare to ask', 12, 'jr-9-U4-0012', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='dare');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'crowd', 'n.', '/kraʊd/', '人群;观众', 'get lost in a crowd', 13, 'jr-9-U4-0013', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='crowd');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'ton', 'n.', '/tʌn/', '吨;(pl.)大量;许多', 'tons of fans', 14, 'jr-9-U4-0014', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='ton');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'private', 'adj.', '/ˈpraɪvət/', '私人的;私密的', 'a private school', 15, 'jr-9-U4-0015', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='private');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'guard', 'n.', '/ɡɑːd/', '警卫;看守;v. 守卫;保卫', 'guard the gate', 16, 'jr-9-U4-0016', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='guard');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'require', 'v.', '/rɪˈkwaɪə(r)/', '需要;要求', 'require help', 17, 'jr-9-U4-0017', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='require');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'European', 'adj.', '/ˌjʊərəˈpiːən/', '欧洲(人)的;n. 欧洲人', 'European history', 18, 'jr-9-U4-0018', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='European');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'African', 'adj.', '/ˈæfrɪkən/', '非洲(人)的;n. 非洲人', 'African culture', 19, 'jr-9-U4-0019', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='African');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'British', 'adj.', '/ˈbrɪtɪʃ/', '英国(人)的;n. 英国人', 'British English', 20, 'jr-9-U4-0020', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='British');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'speech', 'n.', '/spiːtʃ/', '讲话;发言', 'give a speech', 21, 'jr-9-U4-0021', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='speech');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'public', 'n.', '/ˈpʌblɪk/', '民众;adj. 公开的;公众的', 'speak in public', 22, 'jr-9-U4-0022', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='public');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'in public', '', '', '公开地;在别人(尤指生人)面前', 'speak in public', 23, 'jr-9-U4-0023', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='in public');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'ant', 'n.', '/ænt/', '蚂蚁', 'afraid of ants', 24, 'jr-9-U4-0024', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='ant');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'insect', 'n.', '/ˈɪnsekt/', '昆虫', 'ants and other insects', 25, 'jr-9-U4-0025', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='insect');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'seldom', 'adv.', '/ˈseldəm/', '不常;很少', 'seldom go out', 26, 'jr-9-U4-0026', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='seldom');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'influence', 'v. & n.', '/ˈɪnfluəns/', '影响', 'influence others', 27, 'jr-9-U4-0027', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='influence');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'absent', 'adj.', '/ˈæbsənt/', '缺席的;不在', 'be absent from class', 28, 'jr-9-U4-0028', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='absent');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'fail', 'v.', '/feɪl/', '不及格;失败;未能(做到)', 'fail a test', 29, 'jr-9-U4-0029', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='fail');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'examination', 'n.', '/ɪɡˌzæmɪˈneɪʃn/', '考试;审查', 'pass the examination', 30, 'jr-9-U4-0030', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='examination');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'boarding school', '', '/ˈbɔːdɪŋ skuːl/', '寄宿学校', 'go to a boarding school', 31, 'jr-9-U4-0031', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='boarding school');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'in person', '', '', '亲身;亲自', 'talk to him in person', 32, 'jr-9-U4-0032', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='in person');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'exactly', 'adv.', '/ɪɡˈzæktli/', '确切地;精确地', 'know exactly', 33, 'jr-9-U4-0033', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='exactly');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'pride', 'n.', '/praɪd/', '自豪;骄傲', 'take pride in', 34, 'jr-9-U4-0034', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='pride');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'take pride in', '', '', '为……感到自豪', 'take pride in his work', 35, 'jr-9-U4-0035', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='take pride in');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'proud', 'adj.', '/praʊd/', '自豪的;骄傲的', 'be proud of', 36, 'jr-9-U4-0036', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='proud');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'be proud of', '', '', '为……自豪;感到自豪', 'be proud of yourself', 37, 'jr-9-U4-0037', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='be proud of');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'general', 'adj.', '/ˈdʒenrəl/', '总的;普遍的;常规的;n. 将军', 'a general introduction', 38, 'jr-9-U4-0038', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='general');
INSERT INTO public.junior_vocab (id, grade, word, pos, phonetic, meaning_cn, phrase_en, freq_rank, word_id, stage, volume, unit, source_type, confidence) SELECT gen_random_uuid(), 9, 'introduction', 'n.', '/ˌɪntrəˈdʌkʃn/', '介绍', 'a general introduction', 39, 'jr-9-U4-0039', 'junior', '9', 'U4', 'wordlist', 'high' WHERE NOT EXISTS (SELECT 1 FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4' AND word='introduction');
-- [step2 验证] 预期 39
SELECT 'U4 INSERT后' tag, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit='U4';

-- ========================= 末尾查重(预期 0 行) =========================
SELECT word, unit, count(*) FROM public.junior_vocab WHERE grade=9 AND volume='9' AND unit IN ('U3','U4') GROUP BY word, unit HAVING count(*) > 1;