-- ============================================================
-- 选择性必修四 U3(Sea Exploration)灌库(junior_* 表,volume='elective4' unit='U3' grade=12)。幂等。
-- preflight(grade 7-12 + senior 分类)已随必修一跑过,不必再跑。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 46 =====
DELETE FROM public.junior_vocab WHERE volume='elective4' AND unit='U3';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'coral', 'n.', '/ˈkɒrəl/', '珊瑚;珊瑚虫', 'Divers found a colourful coral reef on the sea floor.', '潜水员在海底发现了一片色彩斑斓的珊瑚礁。', 'Sea Exploration', 1, 0, 'senior', 'wordlist', 'elective4', 'U3', 'coral reef', '美音 /ˈkɔːrəl/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'coverage', 'n.', '/ˈkʌvərɪdʒ/', '新闻报道;覆盖范围', 'The deep-sea dive received wide media coverage around the world.', '这次深海下潜得到了全世界广泛的新闻报道。', 'Sea Exploration', 2, 0, 'senior', 'wordlist', 'elective4', 'U3', 'media coverage', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'directory', 'n.', '/dəˈrektəri/', '名录;号码簿;(计算机)目录', 'Each whale was added to a directory so scientists could track it later.', '每头鲸都被录入名录,以便科学家日后追踪。', 'Sea Exploration', 3, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a species directory', '美音 /dəˈrektəri/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'exploit', 'vt.', '/ɪkˈsplɔɪt/', '开发;利用;剥削', 'Some people want to exploit the ocean only for its oil and minerals.', '有些人只想为了石油和矿产而开发海洋。', 'Sea Exploration', 4, 0, 'senior', 'wordlist', 'elective4', 'U3', 'exploit the ocean', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'extend', 'vt.', '/ɪkˈstend/', '扩展;延伸;延长', 'Deep-sea research has greatly extended our knowledge of marine life.', '深海研究极大地扩展了我们对海洋生物的了解。', 'Sea Exploration', 5, 0, 'senior', 'wordlist', 'elective4', 'U3', 'extend our knowledge', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'fleet', 'n.', '/fliːt/', '舰队;船队;机群;车队', 'Zheng He led a huge fleet across the sea to many distant lands.', '郑和率领一支庞大的船队跨海到达许多遥远的国度。', 'Sea Exploration', 6, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a huge fleet', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'gallon', 'n.', '/ˈɡælən/', '加仑(容积单位)', 'The oil spill released over 200 million gallons of oil into the sea.', '那次漏油事故向海里排放了超过两亿加仑石油。', 'Sea Exploration', 7, 0, 'senior', 'wordlist', 'elective4', 'U3', 'millions of gallons', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'league', 'n.', '/liːɡ/', '等级;水平;联合会;联赛', 'As a research vessel, Kexue is in a league of its own.', '作为一艘科考船,“科学号”可谓独领风骚。', 'Sea Exploration', 8, 0, 'senior', 'wordlist', 'elective4', 'U3', 'in a league of its own', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'log', 'vt./n.', '/lɒɡ/', '记录;载入正式记录;日志;原木', 'Scientists log new species to improve our understanding of ocean life.', '科学家记录新物种,以增进我们对海洋生命的理解。', 'Sea Exploration', 9, 0, 'senior', 'wordlist', 'elective4', 'U3', 'log new species', '美音 /lɔːɡ/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'manned', 'adj.', '/mænd/', '有人控制的;需人操纵的', 'The Jiaolong is a manned submersible that can dive seven kilometres deep.', '“蛟龙号”是一艘可下潜七千米的载人潜水器。', 'Sea Exploration', 10, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a manned submersible', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'marine', 'adj.', '/məˈriːn/', '海的;海产的;海生的', 'Plastic pollution is a serious danger to marine life.', '塑料污染对海洋生物是一个严重的威胁。', 'Sea Exploration', 11, 0, 'senior', 'wordlist', 'elective4', 'U3', 'marine life', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'maritime', 'adj.', '/ˈmærɪtaɪm/', '海的;海运的;海事的', 'Zheng He''s voyages are a proud part of China''s maritime history.', '郑和的航行是中国海运史上令人自豪的一部分。', 'Sea Exploration', 12, 0, 'senior', 'wordlist', 'elective4', 'U3', 'maritime history', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'meanwhile', 'adv.', '/ˈmiːnwaɪl/', '与此同时;另一方面', 'Meanwhile, the researchers noted the location of each group of whales.', '与此同时,研究人员记下了每群鲸的位置。', 'Sea Exploration', 13, 0, 'senior', 'wordlist', 'elective4', 'U3', 'meanwhile we noted', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'merchant', 'n./adj.', '/ˈmɜːtʃənt/', '商人;批发商;海上货运的', 'Along the ancient sea routes, a merchant could trade silk for spices.', '沿着古老的海上航线,商人可以用丝绸换取香料。', 'Sea Exploration', 14, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a merchant ship', '美音 /ˈmɜːrtʃənt/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'mercy', 'n.', '/ˈmɜːsi/', '仁慈;宽恕;怜悯', 'Some countries still hunt these intelligent creatures without mercy.', '一些国家仍然毫不留情地捕猎这些聪明的生物。', 'Sea Exploration', 15, 0, 'senior', 'wordlist', 'elective4', 'U3', 'without mercy', '美音 /ˈmɜːrsi/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'migration', 'n.', '/maɪˈɡreɪʃn/', '迁徙;迁移;移居', 'Researchers track whales to plot their long migration path south.', '研究人员追踪鲸,以绘制它们南下的漫长迁徙路线。', 'Sea Exploration', 16, 0, 'senior', 'wordlist', 'elective4', 'U3', 'migration path', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'mixture', 'n.', '/ˈmɪkstʃə(r)/', '混合;混合物;结合体', 'Sailing around the world is a mixture of danger and boredom.', '环球航行是危险与无聊的混合体。', 'Sea Exploration', 17, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a mixture of', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'murder', 'vt./n.', '/ˈmɜːdə(r)/', '谋杀;凶杀;残害', 'The writer says some fishermen are "murdering" whales for so-called research.', '作者说一些渔民正以所谓研究的名义“残害”鲸。', 'Sea Exploration', 18, 0, 'senior', 'wordlist', 'elective4', 'U3', 'murder these creatures', '美音 /ˈmɜːrdər/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'negotiate', 'vt./vi.', '/nɪˈɡəʊʃieɪt/', '谈判;协商;商定', 'Nations now negotiate to protect the deep sea together.', '各国如今通过协商来共同保护深海。', 'Sea Exploration', 19, 0, 'senior', 'wordlist', 'elective4', 'U3', 'negotiate a deal', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'opponent', 'n.', '/əˈpəʊnənt/', '反对者;对手;竞争者', 'Opponents of sea mining warn that it badly damages the ocean floor.', '反对海底采矿的人警告说,这会严重破坏海底。', 'Sea Exploration', 20, 0, 'senior', 'wordlist', 'elective4', 'U3', 'opponents of mining', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'politics', 'n.', '/ˈpɒlətɪks/', '政治;政治观点', 'Protecting the sea is not only science but also a matter of global politics.', '保护海洋不仅是科学,也是一个全球政治问题。', 'Sea Exploration', 21, 0, 'senior', 'wordlist', 'elective4', 'U3', 'ocean politics', '美音 /ˈpɑːlətɪks/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'possession', 'n.', '/pəˈzeʃn/', '财产;拥有;占有', 'The sea is home to life, not human beings'' possessions.', '大海是生命的家园,而不是人类的财产。', 'Sea Exploration', 22, 0, 'senior', 'wordlist', 'elective4', 'U3', 'human possessions', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'profession', 'n.', '/prəˈfeʃn/', '职业;行业', 'Deep-sea exploration has become a respected profession in China.', '深海探测在中国已成为一项受人尊敬的职业。', 'Sea Exploration', 23, 0, 'senior', 'wordlist', 'elective4', 'U3', 'the diving profession', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'royal', 'adj.', '/ˈrɔɪəl/', '皇家的;王室的;高贵的', 'In the story, the Sea King''s mother was born into the royal family.', '在故事里,海王的母亲出生于王室。', 'Sea Exploration', 24, 0, 'senior', 'wordlist', 'elective4', 'U3', 'the royal family', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'spice', 'n.', '/spaɪs/', '香料;调味品;情趣', 'Early merchants set sail to trade in silk, tea and precious spices.', '早期商人起航出海,以买卖丝绸、茶叶和珍贵的香料。', 'Sea Exploration', 25, 0, 'senior', 'wordlist', 'elective4', 'U3', 'trade in spices', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'submersible', 'n.', '/səbˈmɜːsəbl/', '潜水器;可潜船', 'A deep-sea submersible can reach places that no diver could ever go.', '深海潜水器能到达任何潜水员都无法到达的地方。', 'Sea Exploration', 26, 0, 'senior', 'wordlist', 'elective4', 'U3', 'deep-sea submersible', '美音 /səbˈmɜːrsəbl/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'tale', 'n.', '/teɪl/', '故事;传说;叙述', 'Sailors used to tell exciting tales of storms and strange sea creatures.', '水手们过去常讲述关于风暴和奇异海洋生物的精彩故事。', 'Sea Exploration', 27, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a sea tale', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'tax', 'vt./n.', '/tæks/', '征税;使纳税;税;税款', 'Some experts say we should tax plastic bottles so that people use fewer.', '一些专家说我们应当对塑料瓶征税,以便人们少用。', 'Sea Exploration', 28, 0, 'senior', 'wordlist', 'elective4', 'U3', 'tax plastic bottles', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'tournament', 'n.', '/ˈtʊənəmənt/', '锦标赛;联赛', 'The young sailor missed an important sailing tournament because of a storm.', '那位年轻水手因风暴错过了一场重要的帆船锦标赛。', 'Sea Exploration', 29, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a sailing tournament', '美音 /ˈtɜːrnəmənt/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'underwater', 'adj./adv.', '/ˌʌndəˈwɔːtə(r)/', '水下的;在水下', 'Special cameras allow scientists to do underwater research in the dark deep.', '特殊的摄像机让科学家能在黑暗的深海进行水下研究。', 'Sea Exploration', 30, 0, 'senior', 'wordlist', 'elective4', 'U3', 'underwater research', '美音 /ˌʌndərˈwɔːtər/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'withdraw', 'vi./vt.', '/wɪðˈdrɔː/', '撤回;撤离;退出', 'Because of injury, the sailor had to withdraw from the long voyage.', '由于受伤,那名水手不得不退出这次漫长的航行。', 'Sea Exploration', 31, 0, 'senior', 'wordlist', 'elective4', 'U3', 'withdraw from', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'spill', 'vt./n.', '/spɪl/', '溢出;泼洒;泄漏;泄漏事故', 'A single oil spill can kill thousands of birds and fish along the coast.', '一次漏油事故就能杀死沿岸成千上万的鸟和鱼。', 'Sea Exploration', 32, 0, 'senior', 'wordlist', 'elective4', 'U3', 'an oil spill', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'fossil', 'n.', '/ˈfɒsl/', '化石', 'Burning fossil fuels makes the sea ice melt faster than before.', '燃烧化石燃料使海冰比以前融化得更快。', 'Sea Exploration', 33, 0, 'senior', 'wordlist', 'elective4', 'U3', 'fossil fuels', '美音 /ˈfɑːsl/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'mineral', 'n.', '/ˈmɪnərəl/', '矿物;矿物质', 'There may be valuable minerals hidden deep under the sea.', '深海之下可能藏有珍贵的矿物。', 'Sea Exploration', 34, 0, 'senior', 'wordlist', 'elective4', 'U3', 'valuable minerals', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'voyage', 'n.', '/ˈvɔɪɪdʒ/', '航行;航海;航程', 'Magellan made the first voyage around the whole world.', '麦哲伦完成了首次环球航行。', 'Sea Exploration', 35, 0, 'senior', 'wordlist', 'elective4', 'U3', 'make a voyage', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'vessel', 'n.', '/ˈvesl/', '船;舰;容器', 'Kexue is China''s most advanced research vessel on the sea.', '“科学号”是中国海上最先进的科考船。', 'Sea Exploration', 36, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a research vessel', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'expedition', 'n.', '/ˌekspəˈdɪʃn/', '探险;远征;考察队', 'China has joined other nations on several expeditions to the Arctic.', '中国已与其他国家一起进行了数次北极考察。', 'Sea Exploration', 37, 0, 'senior', 'wordlist', 'elective4', 'U3', 'join an expedition', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'overfishing', 'n.', '/ˌəʊvəˈfɪʃɪŋ/', '过度捕捞', 'Overfishing has left fewer fish in many parts of the ocean.', '过度捕捞使海洋许多地方的鱼变少了。', 'Sea Exploration', 38, 0, 'senior', 'wordlist', 'elective4', 'U3', 'stop overfishing', '美音 /ˌoʊvərˈfɪʃɪŋ/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'pollution', 'n.', '/pəˈluːʃn/', '污染', 'Plastic pollution has even been found in our tap water.', '塑料污染甚至已在我们的自来水中被发现。', 'Sea Exploration', 39, 0, 'senior', 'wordlist', 'elective4', 'U3', 'plastic pollution', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'resource', 'n.', '/rɪˈsɔːs/', '资源;财力', 'The deep sea may hold vast natural resources for the future.', '深海可能蕴藏着供未来使用的大量自然资源。', 'Sea Exploration', 40, 0, 'senior', 'wordlist', 'elective4', 'U3', 'natural resources', '美音 /ˈriːsɔːrs/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'creature', 'n.', '/ˈkriːtʃə(r)/', '生物;动物', 'Whales and dolphins are among the most intelligent sea creatures.', '鲸和海豚是最聪明的海洋生物之一。', 'Sea Exploration', 41, 0, 'senior', 'wordlist', 'elective4', 'U3', 'sea creatures', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'sensitive', 'adj.', '/ˈsensətɪv/', '敏感的;脆弱的;善解人意的', 'The ocean is huge, but it is more sensitive than we think.', '海洋很大,但它比我们想象的更脆弱。', 'Sea Exploration', 42, 0, 'senior', 'wordlist', 'elective4', 'U3', 'a sensitive system', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'ban', 'vt./n.', '/bæn/', '禁止;取缔;禁令', 'Although whaling was banned in 1982, some ships still ignore the rule.', '尽管1982年捕鲸已被禁止,一些船只仍无视这条规定。', 'Sea Exploration', 43, 0, 'senior', 'wordlist', 'elective4', 'U3', 'ban whaling', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'enhance', 'vt.', '/ɪnˈhɑːns/', '提高;增强;改善', 'The desire to enhance relationships drives China to reach across the sea.', '增进关系的愿望推动中国跨越海洋伸出友谊之手。', 'Sea Exploration', 44, 0, 'senior', 'wordlist', 'elective4', 'U3', 'enhance relationships', '美音 /ɪnˈhæns/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'identify', 'vt.', '/aɪˈdentɪfaɪ/', '辨认;识别;确认', 'Different marks on their fins help us identify the whales later.', '鳍上不同的标记帮助我们日后辨认这些鲸。', 'Sea Exploration', 45, 0, 'senior', 'wordlist', 'elective4', 'U3', 'identify the whales', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (12, 'track', 'vt./n.', '/træk/', '追踪;跟踪;轨迹;小路', 'Scientists track their movements to learn where the whales travel.', '科学家追踪它们的活动,以了解这些鲸去往何处。', 'Sea Exploration', 46, 0, 'senior', 'wordlist', 'elective4', 'U3', 'track their movements', NULL);

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3');
DELETE FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e4u3.01', '①长句中的从句连接词(定语/状语/名词性从句:which/where/when/that/because/although/so that 等)', 'A2', 12, '选择性必修四 U3 — 在复合长句里先找主句,再看空格引导的从句:看先行词与从句缺失成分(主/宾/状)选关系词;看逻辑关系(原因/让步/目的)选状语连词;看名词性从句是否完整选 that/whether/what 等。', 1, 'elective4', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e4u3.02', '②长句中的非谓语动词(doing / done / to do 作定语/状语/宾补)', 'A2', 12, '选择性必修四 U3 — 句中已有谓语,空格处的动词只能用非谓语:与逻辑主语主动/进行→doing;被动/完成→done;表目的/将来/在 too…/be said 等结构→to do。', 2, 'elective4', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e4u3.03', '③长句中的并列、强调与倒装(not only…but also;it is…that 强调;Only…倒装;neither/so 倒装)', 'A2', 12, '选择性必修四 U3 — 并列连词连接对等成分;强调句 it is/was…that 去掉后仍是完整句;Only+状语 / 否定词置于句首引起部分倒装(助动词提前);so/neither + 倒装表''也(不)''。', 3, 'elective4', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'The Jiaolong, ____ can dive seven kilometres deep, has helped Chinese scientists study the dark ocean floor.', 'which', 'what', 'where', 'whose', 'A', '非限制性定语从句先行词 the Jiaolong 指物、从句缺主语 → which。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'We must explore the oceans ____ cover most of our planet if we want to truly understand the earth.', 'what', 'which', 'where', 'when', 'B', '先行词 oceans 指物、从句缺主语(cover 的主语)→ which/that,此处给 which。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'In recent years China has joined several expeditions to the Arctic, ____ scientists study how the climate is changing.', 'which', 'that', 'where', 'when', 'C', '先行词 the Arctic 表地点、从句不缺主宾(只缺地点状语)→ where。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'I will never forget the moment ____ the manned submersible finally touched the deepest part of the sea.', 'which', 'where', 'that', 'when', 'D', '先行词 moment 表时间、从句完整(只缺时间状语)→ when。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'Although the ancient sea routes of Zheng He have been travelled many times, there are still places ____ no modern ship has reached.', 'that', 'when', 'why', 'whose', 'A', '先行词 places、从句缺宾语(reached 的宾语)→ that(或 which),此处给 that。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'Scientists keep logging new species, ____ greatly improves our understanding of life in the deep sea.', 'what', 'which', 'that', 'where', 'B', '非限制性定语从句指代整个前一句、作从句主语 → which。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), '____ the ice is melting faster now, ships can look for more fossil fuels further north in the Arctic.', 'Although', 'Unless', 'Because', 'Whether', 'C', '前后是因果关系(冰融化得快→船能往北找燃料)→ Because。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), '____ whaling was banned in 1982, some countries are still hunting these intelligent creatures without mercy.', 'Because', 'So that', 'If', 'Although', 'D', '前后让步转折(虽被禁,仍有人捕猎)→ Although。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'We need to understand exactly ____ is happening to our oceans so that we can take real action in time.', 'what', 'that', 'which', 'whether', 'A', '宾语从句缺主语、表''什么''→ what。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'Researchers took photos of each whale''s fins ____ they could identify the animals on future trips.', 'as if', 'so that', 'even if', 'now that', 'B', '表目的(为了日后能辨认)→ so that。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'The research vessel Kexue, ____ home port is in Qingdao, can carry out a wide range of marine tasks.', 'which', 'that', 'whose', 'where', 'C', '定语从句表所属(船的母港)→ whose。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'This is the very database ____ the researchers store the photos and locations of every group of whales.', 'which', 'that', 'what', 'where', 'D', '先行词 database 视作抽象地点、从句完整 → where(= in which)。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'It still remains to be seen ____ the tiny capsule can really work under such crushing pressure.', 'whether', 'that', 'which', 'where', 'A', '主语从句表''是否''、句意不确定 → whether。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'Hundreds of years ago, merchants set sail across the sea ____ they could trade silk and tea for precious spices.', 'as though', 'so that', 'even if', 'in case', 'B', '表目的(为了换香料)→ so that。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'The Deepwater Horizon disaster, ____ spilled millions of gallons of oil, killed countless sea birds and fish.', 'what', 'where', 'which', 'when', 'C', '非限制性定语从句指物、缺主语 → which。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), '1405 was the year ____ Zheng He first led his huge fleet out onto the open sea.', 'which', 'where', 'that', 'when', 'D', '先行词 year 表时间、从句完整 → when。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'No one yet knows ____ lies in the deepest parts of the ocean, because we have explored less than five percent of it.', 'what', 'that', 'which', 'where', 'A', '宾语从句缺主语、表''什么''→ what。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'The sea is home to life, not a possession ____ human beings may use up however they like.', 'what', 'that', 'when', 'whose', 'B', '先行词 possession、从句缺宾语(use up 的宾语)→ that(或 which)。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), '____ technology improves, we may have more options for keeping a balance between protection and exploitation.', 'Although', 'Unless', 'As', 'Whether', 'C', '表''随着''(技术进步,选择变多)→ As。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.01'), 'Opponents may be worried, but sea exploration matters so much ____ it can help us face climate change.', 'which', 'what', 'where', 'that', 'D', 'so + adj./adv. + that 结果状语从句 → that。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), '____ after a mythical dragon, the manned submersible Jiaolong carried Chinese scientists into the deep sea.', 'Named', 'Naming', 'To name', 'Name', 'A', 'submersible 与 name 是被动关系(被命名)、作状语 → 过去分词 Named。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'The research ship Kexue is designed ____ a wide range of difficult tasks far out at sea.', 'conducting', 'to conduct', 'conducted', 'conduct', 'B', 'be designed to do 表用途/目的 → 不定式 to conduct。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'New technology makes it possible ____ the deepest spots of the ocean that no diver could ever reach.', 'explored', 'exploring', 'to explore', 'explore', 'C', 'make it possible to do,it 为形式宾语 → to explore。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'The ship struggled on through the storm, ____ wildly with each huge wave that hit its side.', 'roll', 'rolled', 'to roll', 'rolling', 'D', 'ship 与 roll 主动、表伴随 → 现在分词 rolling 作状语。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'Plastic pollution, ____ in our tap water in recent years, has become a serious danger to marine life.', 'found', 'finding', 'to find', 'find', 'A', 'pollution 与 find 被动 → 过去分词 found 作后置定语。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'Young people came to the camp ____ more about whales and other amazing sea creatures.', 'learn', 'to learn', 'learned', 'learning', 'B', '表目的状语 → 不定式 to learn。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'The deep ocean is too dark and too cold ____ without special equipment and powerful lights.', 'exploring', 'explored', 'to explore', 'explore', 'C', 'too…to do 结构 → to explore。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'Standing on the deck, the campers watched the whales ____ slowly out of the cold blue water.', 'leaped', 'to leap', 'leap to', 'leaping', 'D', 'watch sb doing 表正在进行 → 现在分词 leaping 作宾补。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'The Jiaolong submersible is said ____ able to reach a depth of seven kilometres below the surface.', 'to be', 'being', 'be', 'been', 'A', 'be said to do/be 表传闻 → to be。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'China has invested billions in systems and services along these routes, ____ the whole area develop for future trade.', 'help', 'helping', 'helped', 'to helping', 'B', '与前句主动、表结果伴随 → 现在分词 helping。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), '____ the most advanced research vessel in the country, Kexue draws the attention of scientists worldwide.', 'Regard as', 'Regarding', 'Regarded as', 'To regard', 'C', 'vessel 与 regard 被动(被视为)→ 过去分词 Regarded as 作状语。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'There is an urgent need ____ the Arctic in order to understand climate change and its effects.', 'studying', 'studied', 'study', 'to study', 'D', 'need 后接不定式作定语 → to study。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'We saw a database ____ to store the photos and locations of every whale the team had followed.', 'built', 'build', 'building', 'to building', 'A', 'database 与 build 被动 → 过去分词 built 作后置定语。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'The young sailor read books all day on the boat, ____ his family every evening using a small laptop.', 'email', 'emailing', 'emailed', 'to email', 'B', '与主句主动、表伴随 → 现在分词 emailing。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'Accessing the deep ocean may also help scientists ____ events such as earthquakes long before they happen.', 'predicting', 'predicted', 'predict', 'to predicting', 'C', 'help (sb) (to) do,空后接原形 → predict。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), '____ for two years, the old sea routes were finally reopened to merchant ships from many nations.', 'Closing', 'To close', 'Close', 'Closed', 'D', 'routes 与 close 被动、表完成 → 过去分词 Closed 作状语。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'The camp gives students a real chance ____ whale songs and watch these huge animals at close range.', 'to hear', 'hearing', 'heard', 'hear', 'A', 'chance to do 不定式作定语 → to hear。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'With the latest technology in hand, China keeps reaching out across the sea, ____ stronger bonds with the world.', 'build', 'building', 'built', 'to building', 'B', '与主句主动、表伴随结果 → 现在分词 building。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'It is not rare ____ the most unique flowers and plants dancing in the fast-moving water of the deep.', 'seeing', 'seen', 'to see', 'see', 'C', 'It is + adj. + to do,it 为形式主语 → to see。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.02'), 'The mother of the Sea King, ____ proud to be born into the royal family, takes care of his six daughters.', 'feels', 'felt', 'to feel', 'feeling', 'D', '与逻辑主语主动、表状态 → 现在分词 feeling 作状语。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Sea exploration not only helps us find new medicines ____ also leads us to new sources of food and energy.', 'but', 'and', 'or', 'so', 'A', 'not only … but also 固定并列结构 → but。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'It was the writing of the ships'' logs ____ allowed later sailors to follow the very same routes safely.', 'which', 'that', 'what', 'who', 'B', '强调句 It was … that 强调主语 the writing → that。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Only after the storm finally passed ____ the exhausted sailor able to see the distant shore.', 'be', 'is', 'was', 'being', 'C', 'Only + 状语置句首引起部分倒装,主句用 was the sailor able → was。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'We can explore the sea to learn from it, ____ we can exploit it carelessly until nothing is left.', 'and', 'but', 'for', 'or', 'D', '两种相反选择(学习它 / 或耗尽它)→ or。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'The ocean is huge, ____ it is far more sensitive than most people are willing to believe.', 'yet', 'or', 'so', 'nor', 'A', '前后转折(很大,然而脆弱)→ yet。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'It is climate change ____ this melting Arctic ice is warning us about so clearly and so urgently.', 'who', 'that', 'which', 'what', 'B', '强调句 It is … that 强调宾语 climate change → that。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Not until we protect the deep sea today ____ future generations forgive us for our choices.', 'would', 'do', 'will', 'are', 'C', 'Not until 置句首引起部分倒装,主句将来时 → will。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Mining damages the ocean floor, and ____ does overfishing harm the balance of marine life.', 'neither', 'nor', 'either', 'so', 'D', '前句肯定、后句''也''(同样有害)→ so + 倒装。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Scientists must study the deep sea, ____ they cannot manage the planet''s resources wisely.', 'or', 'and', 'so', 'for', 'A', '''否则''(不研究就无法管好资源)→ or。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'It was in 2010 ____ the Deepwater Horizon spilled over two hundred million gallons of oil into the sea.', 'when', 'that', 'which', 'what', 'B', '强调句 It was … that 强调时间状语 in 2010 → that(非 when)。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'The sailor did not give up his dream, ____ did the heavy storms ever break his quiet courage.', 'so', 'either', 'nor', 'and', 'C', '前句否定、后句''也不''→ nor + 倒装。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Sea exploration brings real risks, ____ these should be carefully balanced against our economic needs.', 'or', 'nor', 'for', 'but', 'D', '前后转折(有风险,但应权衡)→ but。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Rarely ____ the public realise just how little of the vast deep ocean we have actually explored.', 'does', 'do', 'is', 'has', 'A', '否定副词 Rarely 置句首引起部分倒装,主语 the public 视作单数 → does。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'It is the writing system of ships'' charts ____ has guided fleets safely across the open sea for centuries.', 'who', 'that', 'which', 'what', 'B', '强调句 It is … that 强调主语 → that。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'The deep sea may hide not only valuable minerals ____ also new sources of clean energy for the future.', 'and', 'or', 'but', 'so', 'C', 'not only … but also → but。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Whales are hunted for their meat, ____ are dolphins killed for so-called scientific research.', 'either', 'and so', 'as', 'so', 'D', '前句肯定、''海豚也(被捕)''→ so + 倒装(so are dolphins killed)。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Only then ____ the campers fully understand why protecting sea creatures truly matters.', 'did', 'do', 'had', 'were', 'A', 'Only then 置句首引起部分倒装,过去语境 → did。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'We may imagine there is nothing under the sea but sand, ____ the deep is in fact full of life.', 'and', 'yet', 'so', 'or', 'B', '前后转折(以为只有沙,然而满是生命)→ yet。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'It was courage and passion ____ made the young sailor''s dream of crossing the ocean come true.', 'who', 'which', 'that', 'what', 'C', '强调句 It was … that 强调主语 → that。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3' AND code='e4u3.03'), 'Sailing alone around the world is a mixture of danger and boredom, ____ few people are brave enough to try it.', 'or', 'nor', 'yet', 'so', 'D', '因果(因此很少人敢尝试)→ so。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE volume='elective4' AND unit='U3';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (12, 'Jiaolong: Into the Deep', 'Named after a dragon from ancient Chinese legend, the Jiaolong is a manned submersible that has carried scientists deep into the dark ocean. It is said to be able to reach a depth of about seven kilometres, far below where any diver could ever go. At such depths, the water is freezing cold and the pressure is strong enough to crush an ordinary ship, so the submersible must be built from very special materials. Inside the small capsule, three people can sit and work, using powerful lights and cameras to study the sea floor that human eyes have never seen. Each dive is carefully planned, because a tiny mistake far underwater could be deadly. Thanks to the Jiaolong, Chinese scientists have logged new sea creatures, collected rare minerals and extended our knowledge of life in the deep. Every successful dive reminds us how much of the ocean still waits to be explored.', '说明·载人潜水器蛟龙号', 152, '[{"q":"Why must the Jiaolong be made from very special materials?","answer":"A","options":["Because the deep water is icy and the pressure could destroy a normal ship.","Because it has to float on the surface for years.","Because it is too heavy to lift onto a boat.","Because divers cannot fit inside it."],"explanation":"原文 ''the water is freezing cold and the pressure is strong enough to crush an ordinary ship'' 的转述。"},{"q":"What have scientists achieved with the help of the Jiaolong?","answer":"B","options":["They have stopped all deep-sea diving.","They have recorded new creatures and gathered rare minerals.","They have proved the deep sea is empty.","They have built a city on the sea floor."],"explanation":"原文 ''logged new sea creatures, collected rare minerals and extended our knowledge''(后段)的转述。"},{"q":"What does the last sentence suggest about the ocean?","answer":"A","options":["A great deal of it is still unexplored.","Most of it has already been fully mapped.","It is no longer worth studying.","It is too dangerous to enter at all."],"explanation":"末句 ''how much of the ocean still waits to be explored'' 的转述。"}]'::jsonb, '[{"word":"submersible","cn":"潜水器"},{"word":"manned","cn":"载人的"},{"word":"capsule","cn":"舱"}]'::jsonb, 2, 'elective4', 'U3');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (12, 'Zheng He and the Treasure Fleet', 'More than six hundred years ago, the explorer Zheng He led one of the largest fleets the world had ever seen. Starting in 1405, he made seven great voyages across the sea, reaching lands as far away as East Africa. His fleet carried hundreds of ships and tens of thousands of sailors, along with silk, tea and fine porcelain. Wherever the ships set sail, Zheng He came not to conquer but to trade and to make friends. Local merchants happily exchanged spices, jewels and strange animals for Chinese goods, and many rulers sent gifts back to the Chinese emperor in return. Unlike some later European voyages, Zheng He''s journeys were peaceful, and they helped build bonds between China and distant nations. Today his name still stands for openness and friendship across the sea. Although the ancient routes he sailed have been travelled many times since, the spirit of reaching out to the wider world remains a proud part of China''s maritime history.', '记叙·郑和下西洋', 162, '[{"q":"What was the main purpose of Zheng He''s voyages?","answer":"B","options":["To conquer foreign lands by force.","To trade peacefully and make friends abroad.","To search for a lost treasure ship.","To draw maps of unknown islands."],"explanation":"原文 ''came not to conquer but to trade and to make friends'' 的转述。"},{"q":"How did local rulers often respond to the fleet?","answer":"C","options":["They refused to meet the sailors.","They attacked the Chinese ships.","They often sent presents to China''s emperor in return.","They kept all the silk for themselves."],"explanation":"原文 ''many rulers sent gifts back to the Chinese emperor in return''(中段)的转述。"},{"q":"What does Zheng He''s name stand for today?","answer":"D","options":["Fear of the open sea.","The end of Chinese trade.","A failed and forgotten journey.","A spirit of openness and friendship."],"explanation":"末段 ''his name still stands for openness and friendship across the sea'' 的转述。"}]'::jsonb, '[{"word":"fleet","cn":"船队"},{"word":"merchant","cn":"商人"},{"word":"maritime","cn":"海运的"}]'::jsonb, 2, 'elective4', 'U3');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (12, 'Why Explore the Sea?', 'Human beings have explored less than five percent of the world''s oceans, yet the sea covers most of our planet. To truly understand the earth, we must learn far more about these vast waters. Some opponents argue that sea exploration is a waste of money, but the benefits are hard to ignore. Research ships can help us face urgent problems such as climate change, because the ocean stores heat and shapes the weather everywhere. Studying the deep may also lead to new medicines, as well as fresh sources of food and energy for a growing population. Logging new species improves our understanding of life itself, and reaching the sea floor might even help scientists predict earthquakes before they strike. Of course, exploration brings real risks to the fragile sea, and these must be balanced against our economic needs. Yet as technology keeps improving, we will have more ways to keep that balance. The more we know about the ocean, the better we can protect it for the future.', '议论·为何探索海洋', 168, '[{"q":"Why does the writer say we should learn more about the ocean?","answer":"A","options":["Because most of the planet lies under water that is still little known.","Because it is easy and cheap to study.","Because no one lives near the sea.","Because the ocean has already been fully explored."],"explanation":"原文 ''the sea covers most of our planet… explored less than five percent'' 的转述。"},{"q":"How can sea research help with climate change?","answer":"B","options":["By stopping all ships from sailing.","Because it holds heat and helps shape weather everywhere.","By making the ocean smaller.","By removing all the water from the air."],"explanation":"原文 ''the ocean stores heat and shapes the weather everywhere''(中段)的转述。"},{"q":"What is the writer''s attitude towards the risks of exploration?","answer":"C","options":["The risks mean we should never explore the sea.","The risks do not exist at all.","The risks should be weighed against our needs, not ignored.","The risks matter more than anything else."],"explanation":"原文 ''these must be balanced against our economic needs'' 的转述。"}]'::jsonb, '[{"word":"opponent","cn":"反对者"},{"word":"resource","cn":"资源"},{"word":"predict","cn":"预测"}]'::jsonb, 2, 'elective4', 'U3');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (12, 'A Sea in Danger', 'When some people talk about exploring the sea more, they really mean exploiting it, and that has already caused many problems. More activity at sea often means more pollution. A single oil spill can release millions of gallons of oil, killing countless birds and fish along the coast. Plastic pollution is just as worrying; it harms marine creatures and has even been found in our tap water. Mining for resources damages the ocean floor, and overfishing leaves fewer and fewer fish each year. Whales and dolphins, among the most intelligent creatures in the sea, are sometimes hunted without mercy, even though whaling was banned long ago. The sea is home to life, not a possession that humans may use up however they please. It is enormous, but it is far more sensitive than we think. If we keep taking from it carelessly and give nothing back, future generations may never forgive us. Protecting the ocean is not a choice but a duty we all share.', '议论·海洋污染与保护', 165, '[{"q":"What does the writer mean when many people talk of exploring the sea?","answer":"D","options":["They want to clean it up completely.","They want to leave it untouched.","They want to give it back to the fish.","They mainly want to use it for their own profit."],"explanation":"原文 ''they really mean exploiting it'' 的转述。"},{"q":"Why is plastic pollution described as worrying?","answer":"A","options":["Because it harms sea life and has reached our drinking water.","Because it makes the sea look bright.","Because it helps birds build nests.","Because it disappears within a day."],"explanation":"原文 ''harms marine creatures and has even been found in our tap water'' 的转述。"},{"q":"How does the writer describe our duty towards the sea?","answer":"B","options":["As something only scientists need to think about.","As a shared responsibility, not just a free choice.","As an old idea we can safely forget.","As far less important than making money."],"explanation":"末句 ''Protecting the ocean is not a choice but a duty we all share'' 的转述。"}]'::jsonb, '[{"word":"exploit","cn":"开发;剥削"},{"word":"mercy","cn":"仁慈"},{"word":"sensitive","cn":"脆弱的"}]'::jsonb, 2, 'elective4', 'U3');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (12, 'The Whale Watching Camp', 'Last summer I joined a whale watching camp, and it was the best week of my life. We were not just there to enjoy the view; we became part of a real research team. First, we followed a group of whales in our boat, keeping a safe distance so as not to frighten them. Then we took photographs of their fins, because most whales have slightly different marks that help us tell them apart. Meanwhile, we noted exactly where each group was, so the scientists could track their movements and plot their long migration path south. After that, we gave the group a name and gave every whale a number, adding them all to a directory for future trips. Finally, we contacted other whale research groups around the world to share what we had learned. Listening to whales singing and watching them leap out of the cold blue water, I understood for the first time why studying these intelligent creatures truly matters. I came home tired but proud of the small part I had played.', '记叙·鲸类研究营', 175, '[{"q":"Why did the campers photograph the whales'' fins?","answer":"C","options":["Because the fins are the prettiest part.","Because the whales asked them to.","Because different marks on the fins help tell the whales apart.","Because the cameras only worked on fins."],"explanation":"原文 ''different marks that help us tell them apart'' 的转述。"},{"q":"What was the last thing the team did?","answer":"D","options":["They went straight home to rest.","They released all the whales they had caught.","They gave each whale a colour.","They got in touch with other research groups to share findings."],"explanation":"原文 ''Finally, we contacted other whale research groups… to share'' 的转述。"},{"q":"How did the writer feel about the experience?","answer":"A","options":["Proud to have helped with real research.","Bored and eager to leave early.","Disappointed that nothing happened.","Sorry to have joined at all."],"explanation":"末句 ''tired but proud of the small part I had played'' 的转述。"}]'::jsonb, '[{"word":"fin","cn":"鳍"},{"word":"migration","cn":"迁徙"},{"word":"directory","cn":"名录"}]'::jsonb, 2, 'elective4', 'U3');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (12, 'Kexue: A Lab at Sea', 'Kexue, whose name means science in Chinese, is one of the country''s most advanced research vessels. Often described as a moving laboratory on the sea, it is designed to carry out a wide range of difficult tasks far from land. On board are deep-sea robots, powerful computers and laboratories where scientists can study samples within hours of collecting them. One of its remote vehicles, called Faxian, can dive far below the surface to survey the sea floor and bring back tons of geological samples. With such tools in hand, researchers no longer have to wait for months to learn what lies in the deep ocean. Based on Kexue, China has taken the lead in building a world-class platform for marine research, putting the vessel in a league of its own. The ship has explored parts of the Western Pacific that few people had ever reached. As one scientist put it, every voyage of Kexue adds another page to our growing book of knowledge about the sea.', '说明·科考船科学号', 166, '[{"q":"Why is Kexue called a moving laboratory on the sea?","answer":"B","options":["Because it can only stay in port.","Because scientists can study samples on board soon after collecting them.","Because it is shaped like a school.","Because it never actually sails anywhere."],"explanation":"原文 ''laboratories where scientists can study samples within hours of collecting them'' 的转述。"},{"q":"What can the vehicle Faxian do?","answer":"C","options":["Fly over the ocean to take photos.","Carry passengers across the sea.","Go deep down to examine the ocean bottom and return with samples.","Clean plastic from the beaches."],"explanation":"原文 ''dive far below the surface to survey the sea floor and bring back… samples'' 的转述。"},{"q":"What does the final sentence suggest about each voyage?","answer":"D","options":["It wastes both time and money.","It teaches us nothing new.","It marks the end of marine research.","It adds to our understanding of the sea."],"explanation":"末句 ''adds another page to our growing book of knowledge about the sea'' 的转述。"}]'::jsonb, '[{"word":"vessel","cn":"船;舰"},{"word":"league","cn":"等级;水平"},{"word":"geological","cn":"地质的"}]'::jsonb, 2, 'elective4', 'U3');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE volume='elective4' AND unit='U3';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (12, 'elective4', 'U3', 'The Youngest Sailor', 'In 2008, a sixteen-year-old boy set (1)____ on an amazing journey: to sail alone around the whole world. As a child, he had read a (2)____ about another young sailor and dreamed of doing the same. Using his own money, he bought a boat and (3)____ off. The voyage was a (4)____ of danger and boredom. He had to fight through heavy storms and get by on very little (5)____. To pass the time, he read many books and (6)____ his family every evening using a small laptop. After thirteen long months, he returned home with a new world (7)____ as the youngest person ever to sail around the world alone. His adventure received wide media (8)____ everywhere. At his press conference, he said that passion and (9)____ had made his dream come true. In his opinion, there is so much that people can (10)____ if they simply go for it.', 151, 2, '[{"q":"1","answer":"A","options":["sail","fire","table","music"],"explanation":"set sail 起航。"},{"q":"2","answer":"B","options":["price","tale","machine","garden"],"explanation":"a tale 一个故事。"},{"q":"3","answer":"C","options":["put","took","set","made"],"explanation":"set off 出发。"},{"q":"4","answer":"D","options":["price","ticket","machine","mixture"],"explanation":"a mixture of 混合体。"},{"q":"5","answer":"A","options":["sleep","money","noise","paper"],"explanation":"little sleep 几乎不睡。"},{"q":"6","answer":"B","options":["ate","emailed","sold","lost"],"explanation":"emailed his family 给家人发邮件。"},{"q":"7","answer":"C","options":["weather","garden","record","noise"],"explanation":"a world record 世界纪录。"},{"q":"8","answer":"D","options":["garden","machine","ticket","coverage"],"explanation":"media coverage 媒体报道。"},{"q":"9","answer":"A","options":["courage","money","weather","noise"],"explanation":"passion and courage 激情与勇气。"},{"q":"10","answer":"B","options":["lose","achieve","forget","waste"],"explanation":"achieve 取得。"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (12, 'elective4', 'U3', 'World Oceans Day', 'World Oceans Day takes (1)____ on the eighth of June every year. It is now celebrated in over a hundred (2)____, with hundreds of special events held across the globe. The day is (3)____ in many ways, including new campaigns and special programmes, all working to (4)____ ocean conservation and education. Young people are an important (5)____ of the project, because the future of the sea belongs to them. The day gives them a platform (6)____ they can share ideas and express their concerns. Each year there is a different (7)____ for the events, such as ''Our oceans, our future''. Schools often ask students to clean a (8)____, watch a film about marine life, or listen to talks by sea (9)____. Through such activities, more and more people come to (10)____ how precious and how fragile the ocean really is.', 140, 2, '[{"q":"1","answer":"C","options":["noise","money","place","weather"],"explanation":"take place 举行。"},{"q":"2","answer":"D","options":["machines","gardens","prices","countries"],"explanation":"over a hundred countries 一百多个国家。"},{"q":"3","answer":"A","options":["marked","sold","lost","eaten"],"explanation":"be marked 以……方式纪念。"},{"q":"4","answer":"B","options":["forget","advance","waste","lose"],"explanation":"advance conservation 推动保护。"},{"q":"5","answer":"C","options":["price","noise","part","garden"],"explanation":"an important part 重要部分。"},{"q":"6","answer":"D","options":["which","when","why","where"],"explanation":"a platform where 地点关系副词。"},{"q":"7","answer":"A","options":["theme","price","noise","garden"],"explanation":"a theme 主题。"},{"q":"8","answer":"B","options":["machine","beach","garden","ticket"],"explanation":"clean a beach 清理海滩。"},{"q":"9","answer":"C","options":["drivers","farmers","scientists","singers"],"explanation":"sea scientists 海洋科学家。"},{"q":"10","answer":"D","options":["forget","lose","waste","realise"],"explanation":"realise 意识到。"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (12, 'elective4', 'U3', 'Working in the Deep', 'Few jobs are as exciting or as difficult as exploring the deep sea. The ocean floor is so dark and so cold that humans cannot go there without a special (1)____. Engineers must (2)____ machines that can stand huge pressure far below the surface. A manned (3)____ may carry only two or three people, so every member of the team must be calm and well (4)____. Before each dive, the crew (5)____ every detail of the journey, because a tiny mistake underwater could be (6)____. Once at the bottom, they use powerful lights and cameras to (7)____ creatures that no human eye has ever seen. They also collect rare (8)____ from the sea floor to bring back for study. Their work has greatly (9)____ our knowledge of marine life. Though the deep sea remains a dangerous place, these brave workers believe it is a (10)____ well worth the risk.', 149, 2, '[{"q":"1","answer":"A","options":["machine","song","garden","ticket"],"explanation":"special machine 特殊机器。"},{"q":"2","answer":"B","options":["lose","build","sell","forget"],"explanation":"build machines 建造机器。"},{"q":"3","answer":"C","options":["garden","market","submersible","ticket"],"explanation":"manned submersible 载人潜水器。"},{"q":"4","answer":"D","options":["sold","lost","eaten","trained"],"explanation":"well trained 训练有素。"},{"q":"5","answer":"A","options":["plans","sells","loses","forgets"],"explanation":"plans every detail 规划每个细节。"},{"q":"6","answer":"B","options":["funny","deadly","cheap","easy"],"explanation":"could be deadly 可能致命。"},{"q":"7","answer":"C","options":["sell","lose","study","throw"],"explanation":"study creatures 研究生物。"},{"q":"8","answer":"D","options":["songs","tickets","prices","minerals"],"explanation":"rare minerals 稀有矿物。"},{"q":"9","answer":"A","options":["extended","lost","wasted","broken"],"explanation":"extended our knowledge 拓展知识。"},{"q":"10","answer":"B","options":["price","profession","noise","garden"],"explanation":"a profession 一种职业。"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (12, 'elective4', 'U3', 'The Boy from the Sea', 'An old story tells of an old couple who lived by the sea. One day they heard a baby (1)____ near the water, and when they hurried over, they found a baby seal instead. They took it home, fed it, and (2)____ it as their own son. Gradually the seal grew up (3)____ just like a human boy. The couple loved him deeply and allowed him to go (4)____ except near the sea, for they were (5)____ of losing him. The boy loved his parents so much that he (6)____ never to swim. One day the father went fishing, (7)____ the weather suddenly changed. As the ship rolled in the wild waves, the mother watched the horrible (8)____ helplessly. All of a sudden, the son jumped into the stormy sea (9)____ his father. Swimming as fast as lightning, he pushed the old man safely back to the (10)____, but the couple never saw their brave son again.', 157, 2, '[{"q":"1","answer":"C","options":["sell","buy","cry","throw"],"explanation":"heard a baby cry 听到婴儿哭。"},{"q":"2","answer":"D","options":["sold","lost","ate","raised"],"explanation":"raised it 把它养大。"},{"q":"3","answer":"A","options":["looking","to look","looked","looks"],"explanation":"现在分词作伴随状语 looking。"},{"q":"4","answer":"B","options":["nowhere","anywhere","never","always"],"explanation":"go anywhere 去任何地方。"},{"q":"5","answer":"C","options":["proud","fond","afraid","sure"],"explanation":"afraid of losing 害怕失去。"},{"q":"6","answer":"D","options":["refused","forgot","failed","promised"],"explanation":"promised never to swim 承诺绝不游泳。"},{"q":"7","answer":"A","options":["when","which","where","why"],"explanation":"..., when 突然(并列时间)→ when。"},{"q":"8","answer":"B","options":["price","scene","noise","garden"],"explanation":"the horrible scene 可怕的景象。"},{"q":"9","answer":"C","options":["save","saving","to save","saved"],"explanation":"to save 表目的的不定式。"},{"q":"10","answer":"D","options":["price","garden","ticket","shore"],"explanation":"back to the shore 回到岸边。"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (12, 'elective4', 'U3', 'Studying the Arctic', 'In recent years, China has joined other nations on several (1)____ to explore the far north. From a scientific point of (2)____, there is an urgent need to study the Arctic in order to understand climate (3)____ and its effects. Because of warming, there is less ice now, (4)____ means ships can travel further north than before. Scientists worry that if we (5)____ more fossil fuels, the ice will melt even faster, and this negative (6)____ will continue. On these expeditions, researchers (7)____ the temperature of the water, the thickness of the ice and the movements of (8)____ animals such as seals and whales. The data they collect helps the whole world (9)____ how quickly our planet is changing. Studying the Arctic is hard and dangerous work, but most scientists agree that it is absolutely (10)____ for our shared future.', 140, 2, '[{"q":"1","answer":"A","options":["expeditions","machines","gardens","tickets"],"explanation":"join expeditions 参加考察。"},{"q":"2","answer":"B","options":["price","view","noise","garden"],"explanation":"point of view 观点。"},{"q":"3","answer":"C","options":["price","garden","change","ticket"],"explanation":"climate change 气候变化。"},{"q":"4","answer":"D","options":["what","who","where","which"],"explanation":"非限制性定语从句指代整句、作主语 → which。"},{"q":"5","answer":"A","options":["burn","sell","lose","forget"],"explanation":"burn fossil fuels 燃烧化石燃料。"},{"q":"6","answer":"B","options":["price","cycle","garden","ticket"],"explanation":"negative cycle 恶性循环。"},{"q":"7","answer":"C","options":["sell","lose","measure","forget"],"explanation":"measure 测量。"},{"q":"8","answer":"D","options":["city","school","office","sea"],"explanation":"sea animals 海洋动物。"},{"q":"9","answer":"A","options":["understand","forget","lose","waste"],"explanation":"understand 理解。"},{"q":"10","answer":"B","options":["useless","necessary","boring","cheap"],"explanation":"absolutely necessary 绝对必要。"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (12, 'elective4', 'U3', 'Friends Across the Sea', 'China has long wished to (1)____ out across the sea and build friendly bonds with the rest of the world. One modern plan aims to encourage cooperation and (2)____ along the historic Silk Road areas. Trade has grown greatly in recent years and is likely to (3)____ to grow in years to come. China has (4)____ billions in systems and services along these routes, (5)____ will help develop the whole area for future trade and cultural (6)____. China has also joined its friends across the sea on other important (7)____, such as studying the Arctic together. Hundreds of years ago, (8)____ like Zheng He sailed these waters to trade in silk and spices. Today, with the latest technology in (9)____, the need to trade and the desire to (10)____ relationships still drive China far out across the sea.', 138, 2, '[{"q":"1","answer":"C","options":["sell","lose","reach","throw"],"explanation":"reach out 伸出(友谊之手)。"},{"q":"2","answer":"D","options":["noise","garden","ticket","trade"],"explanation":"cooperation and trade 合作与贸易。"},{"q":"3","answer":"A","options":["continue","stop","refuse","fail"],"explanation":"continue to grow 继续增长。"},{"q":"4","answer":"B","options":["lost","invested","sold","eaten"],"explanation":"invested billions 投入数十亿。"},{"q":"5","answer":"C","options":["what","who","which","where"],"explanation":"非限制性定语从句指物、作主语 → which。"},{"q":"6","answer":"D","options":["price","noise","garden","exchange"],"explanation":"cultural exchange 文化交流。"},{"q":"7","answer":"A","options":["projects","songs","tickets","prices"],"explanation":"important projects 重要项目。"},{"q":"8","answer":"B","options":["singers","explorers","drivers","farmers"],"explanation":"explorers like Zheng He 像郑和这样的探险家。"},{"q":"9","answer":"C","options":["price","noise","hand","garden"],"explanation":"in hand 在手头。"},{"q":"10","answer":"D","options":["forget","lose","waste","enhance"],"explanation":"enhance relationships 增进关系。"}]'::jsonb, 6);

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE volume='elective4' AND unit='U3';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (12, 'U3 听力·对话 Choosing a Sea Camp', '选择性必修四 U3 · dialogue', 3, 'Lucy: Have you decided which sea camp to join this summer, Tom?
Tom: I''m thinking about the whale watching camp. We''d help a real research team.
Lucy: That sounds exciting. What would you actually do there?
Tom: We''d follow whales in a boat and take photos of their fins to tell them apart.
Lucy: I''d rather try the diving camp, where you learn to use underwater cameras.
Tom: Why diving? Isn''t it a bit dangerous for beginners?
Lucy: Maybe, but I really want to see coral reefs with my own eyes.
Tom: Fair enough. Let''s each choose our own camp and share our stories afterwards.', 'Lucy 问 Tom 选了哪个海洋夏令营;Tom 想去观鲸营,能协助真正的研究团队,跟踪鲸并拍鳍照辨认;Lucy 更想去潜水营学用水下摄像机,因为想亲眼看珊瑚礁;两人决定各选各的,之后分享见闻。', 'uk_female', '[{"q":"Which camp is Tom thinking of joining?","type":"choice","answer":"A","options":["The whale watching camp.","The diving camp.","The sailing camp.","The fishing camp."]},{"q":"What would Tom do at his camp?","type":"choice","answer":"B","options":["Clean the beaches all day.","Follow whales and photograph their fins.","Drive a research ship.","Catch fish for dinner."]},{"q":"Why does Lucy prefer the diving camp?","type":"choice","answer":"A","options":["She wants to see coral reefs herself.","It is much cheaper.","It is closer to home.","Her teacher chose it for her."]},{"q":"What is Tom''s worry about diving?","type":"choice","answer":"B","options":["It takes too long.","It may be dangerous for beginners.","There are no cameras.","It is boring for beginners."]},{"q":"What do they finally decide to do?","type":"choice","answer":"C","options":["Join the same camp together.","Stay at home all summer.","Each choose a camp and share stories later.","Give up both camps."]}]'::jsonb, '[]'::jsonb, 'long', 'elective4', 'U3');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (12, 'U3 听力·短文 All About Whales', '选择性必修四 U3 · passage', 2, 'Whales are among the largest and most intelligent creatures in the sea.
Scientists divide the main types of whales by the way they feed.
Whales use sounds both to talk to one another and to find their way.
Each whale has slightly different fins, which help researchers tell them apart.
By studying whales, we learn a great deal about the health of the ocean.', '鲸是海里最大、最聪明的生物之一;科学家按进食方式划分鲸的主要类型;鲸用声音彼此交流并辨别方向;每头鲸的鳍略有不同,帮助研究者辨认;通过研究鲸,我们能了解海洋的健康状况。', 'uk_female', '[{"q":"How are the main types of whales divided?","type":"choice","answer":"D","options":["By their colour.","By their age.","By where they sleep.","By the way they feed."]},{"q":"What do whales use sounds for?","type":"choice","answer":"A","options":["To communicate and to find their way.","Only to scare ships away.","Only to sleep better.","To break the ice."]},{"q":"What helps researchers tell whales apart?","type":"choice","answer":"B","options":["Their names.","Their slightly different fins.","Their numbers painted on them.","Their songs alone."]},{"q":"What does the passage say about whales'' intelligence?","type":"choice","answer":"C","options":["They are among the most foolish animals.","They cannot learn anything.","They are among the most intelligent sea creatures.","They are no smarter than fish."]},{"q":"Why is studying whales useful?","type":"choice","answer":"D","options":["It helps us catch more of them.","It makes the sea smaller.","It has no real purpose.","It teaches us about the health of the ocean."]}]'::jsonb, '[]'::jsonb, 'short', 'elective4', 'U3');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (12, 'U3 听力·对话 A Visit to the Research Ship', '选择性必修四 U3 · dialogue', 3, 'Guide: Welcome aboard Kexue, one of China''s most advanced research vessels.
Student: It''s huge! People call it a moving laboratory on the sea, don''t they?
Guide: That''s right. We can study samples within hours of bringing them up.
Student: How deep can your robots go?
Guide: Our vehicle Faxian can dive far below the surface to survey the sea floor.
Student: And it brings samples back to the ship?
Guide: Yes, tons of geological samples that our scientists then examine here.
Student: No wonder Kexue is in a league of its own. Thank you for the tour!', '讲解员欢迎学生登上“科学号”科考船;学生说它被称作海上移动实验室;讲解员说采样后几小时内就能研究;深潜器“发现号”能下潜到海底进行勘测并带回大量地质样本供船上科学家研究;学生感叹科学号独领风骚并致谢。', 'uk_female', '[{"q":"What is Kexue often called?","type":"choice","answer":"A","options":["A moving laboratory on the sea.","A floating hotel.","A fishing boat.","A war ship."]},{"q":"How soon can the team study the samples?","type":"choice","answer":"B","options":["After several years.","Within hours of bringing them up.","Never on the ship.","Only back on land."]},{"q":"What does the vehicle Faxian do?","type":"choice","answer":"C","options":["It flies above the ship.","It cleans the deck.","It dives deep to survey the sea floor.","It carries the students home."]},{"q":"What does Faxian bring back?","type":"choice","answer":"D","options":["Fresh fish for lunch.","Photos of the sky.","Empty boxes.","Tons of geological samples."]},{"q":"How does the student feel about Kexue at the end?","type":"choice","answer":"A","options":["It is unusual and impressive.","It is too small to matter.","It is just an ordinary boat.","It is not worth visiting."]}]'::jsonb, '[]'::jsonb, 'long', 'elective4', 'U3');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (12, 'U3 听力·短文 The Trouble with Plastic', '选择性必修四 U3 · passage', 2, 'Plastic pollution has become one of the biggest dangers to our oceans.
Tiny pieces of plastic harm fish, birds and other marine creatures.
Shockingly, plastic has even been found in the tap water we drink.
Some experts say we should tax plastic bottles so that people use fewer.
Every small action, from using less plastic to cleaning a beach, can help.', '塑料污染已成为海洋最大的危险之一;细小的塑料碎片伤害鱼、鸟和其他海洋生物;令人震惊的是,塑料甚至已在我们喝的自来水中被发现;一些专家说应对塑料瓶征税,以便人们少用;从少用塑料到清理海滩,每个小行动都有帮助。', 'uk_female', '[{"q":"What is described as one of the biggest dangers to the oceans?","type":"choice","answer":"B","options":["Loud noise.","Plastic pollution.","Cold weather.","Too many ships."]},{"q":"Where has plastic shockingly been found?","type":"choice","answer":"C","options":["In the sun.","In the moon.","In our tap water.","In the desert sand."]},{"q":"What do some experts suggest doing?","type":"choice","answer":"D","options":["Drinking less water.","Catching more fish.","Banning all beaches.","Taxing plastic bottles."]},{"q":"What harms fish, birds and other creatures?","type":"choice","answer":"A","options":["Tiny pieces of plastic.","Fresh rain.","Soft music.","Warm sunshine."]},{"q":"What does the speaker say about small actions?","type":"choice","answer":"B","options":["Small actions are useless.","Each small action can help.","Only governments can help.","Nothing can be done."]}]'::jsonb, '[]'::jsonb, 'short', 'elective4', 'U3');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (12, 'U3 听力·对话 Planning a Dive', '选择性必修四 U3 · dialogue', 3, 'Captain: Tomorrow''s dive will take us to a depth of about three hundred metres.
Diver: That''s deep. Will we use the manned submersible?
Captain: Yes, but only two of us can go inside the small capsule.
Diver: What''s our main task down there?
Captain: We''ll film the coral and collect a few samples from the sea floor.
Diver: Should I worry about the cold and the pressure?
Captain: The capsule keeps us safe, but follow every step of the plan exactly.
Diver: Understood. I''ll check all the cameras and lights tonight.', '船长说明天下潜约三百米深;潜水员问是否用载人潜水器;船长说会用,但小舱只能进两人;主要任务是拍珊瑚并从海底采几份样本;潜水员问要不要担心寒冷和压力;船长说舱内安全,但要严格按计划每一步执行;潜水员表示今晚检查所有摄像机和灯。', 'uk_female', '[{"q":"How deep will tomorrow''s dive go?","type":"choice","answer":"C","options":["About three metres.","About thirty kilometres.","About three hundred metres.","Just below the surface."]},{"q":"How many people can go inside the capsule?","type":"choice","answer":"D","options":["The whole crew.","Exactly ten.","Nobody at all.","Only two."]},{"q":"What is the main task during the dive?","type":"choice","answer":"A","options":["To film coral and collect samples.","To catch large fish.","To race another submersible.","To clean the ship''s deck."]},{"q":"What does the captain tell the diver to do about safety?","type":"choice","answer":"B","options":["Ignore the plan and improvise.","Follow every step of the plan exactly.","Stay on the ship instead.","Swim outside the capsule."]},{"q":"What will the diver do tonight?","type":"choice","answer":"C","options":["Go straight to sleep.","Cancel the whole dive.","Check all the cameras and lights.","Repaint the submersible."]}]'::jsonb, '[]'::jsonb, 'long', 'elective4', 'U3');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (12, 'U3 听力·短文 Why We Explore the Sea', '选择性必修四 U3 · passage', 2, 'People have explored less than five percent of the world''s oceans.
Yet the sea covers most of our planet and shapes our climate.
Exploring it may lead to new medicines, food and sources of energy.
It can also help scientists predict events such as earthquakes.
The more we understand the sea, the better we can protect it.', '人类对世界海洋的探索还不到百分之五;然而海洋覆盖了地球大部分并影响着气候;探索海洋也许会带来新药、新食物和新能源;还能帮助科学家预测地震等事件;我们越了解海洋,就越能保护它。', 'uk_female', '[{"q":"How much of the oceans have people explored?","type":"choice","answer":"D","options":["Almost all of it.","Exactly half of it.","None of it at all.","Less than five percent."]},{"q":"What does the sea do to our planet?","type":"choice","answer":"A","options":["It covers most of it and shapes the climate.","It makes the land disappear.","It has no effect on us.","It stops the weather completely."]},{"q":"What might exploring the sea lead to?","type":"choice","answer":"B","options":["Less food for everyone.","New medicines, food and energy.","The end of all medicine.","Fewer scientists."]},{"q":"What event can sea research help predict?","type":"choice","answer":"C","options":["Birthday parties.","Football matches.","Earthquakes.","School exams."]},{"q":"What is the main message of the passage?","type":"choice","answer":"D","options":["We should never study the sea.","The sea is not important.","Exploration is a waste of time.","Understanding the sea helps us protect it."]}]'::jsonb, '[]'::jsonb, 'short', 'elective4', 'U3');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE volume='elective4' AND unit='U3';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit) VALUES (12, 'Write a News Report about a Sea Exploration Achievement(写一篇海洋探索成就的新闻报道)', 'A Breakthrough Beneath the Waves', '假设你是校英文报记者李华。某科研团队的载人潜水器近日成功完成一次深海下潜。请用英语写一篇约120词的新闻报道,内容包括:① 报道这一海洋探索成就(何时/何地/谁/取得了什么);② 简述这次下潜的意义(发现新物种、采集样本等);③ 简要说明我们为什么要探索海洋。注意:导语点明核心事实,行文用一般过去时为主、长句拆分清楚。', 'Suppose you are Li Hua, a reporter for your school''s English newspaper. A research team''s manned submersible has just completed a successful deep-sea dive. Write a news report (about 120 words) including: 1) the achievement (when / where / who / what was done); 2) why the dive matters (new species, samples, etc.); 3) a brief reason why exploring the ocean is important.', '["导语报道成就(A research team announced that … / … successfully reached …)","细节:下潜深度、载人潜水器、采集了什么(reached a depth of … / collected … / logged new species)","意义与背景(The dive extends our knowledge of marine life …)","为何探海(We must explore the oceans, which cover most of our planet, to … )"]'::jsonb, 70, 100, 'A Breakthrough Beneath the Waves

Last week, a Chinese research team announced that its manned submersible, named after a dragon, had successfully reached a depth of about seven kilometres in the Pacific Ocean. Three scientists spent hours in the small capsule, using powerful lights and cameras to study the dark sea floor that human eyes had never seen.

During the dive, the team logged several new sea creatures and collected rare minerals, achievements that greatly extend our knowledge of marine life. "Every voyage adds another page to our book of knowledge about the sea," one scientist said.

Why does such work matter? Because the ocean covers most of our planet, exploring it may bring new medicines and help us protect a fragile world for future generations.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["A Chinese research team announced that its manned submersible had successfully reached a depth of about seven kilometres.","Using powerful lights and cameras, the scientists studied the dark sea floor that human eyes had never seen.","During the dive, the team logged several new sea creatures and collected rare minerals.","Because the ocean covers most of our planet, exploring it may bring new medicines and help us protect a fragile world."]'::jsonb, '[{"wrong":"The submersible reached at a depth of seven kilometres.","correct":"The submersible reached a depth of seven kilometres.","note":"reach 是及物动词,后面直接跟宾语,不加 at。"},{"wrong":"The team logged new creatures which extend our knowledge.","correct":"The team logged new creatures, which extended our knowledge.","note":"非限制性定语从句前加逗号;且与主句时态一致用过去式 extended。"},{"wrong":"Named after a dragon, the team built the submersible.","correct":"Named after a dragon, the submersible carried the team into the deep.","note":"过去分词作状语的逻辑主语须与主句主语一致(被命名的是潜水器,不是团队)。"}]'::jsonb, '【海洋探索新闻报道结构】
标题:A Breakthrough Beneath the Waves
第1段 导语:A research team announced that … had successfully reached … (时间/地点/谁/做了什么)
第2段 细节+意义:During the dive, the team logged … and collected …, which extended … 加一句引语 "…," one scientist said.
第3段 为何探海:Because the ocean covers most of our planet, exploring it may … and help us protect …', 2, 'elective4', 'U3');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE volume='elective4' AND unit='U3';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content) VALUES (12, 'elective4', 'U3', '{"title":"长难句速查:从句连接词 · 非谓语 · 强调与倒装","intro":"长句看着吓人,其实先做三步就稳:① 找出主句的主谓宾(主干);② 圈出多余的动词——它一定是非谓语(doing/done/to do);③ 看连接词引导的是哪种从句(定语/状语/名词性)。拆完主干,空格该填什么自然就清楚了。","table":{"headers":["结构","怎么判断 / 例句"],"rows":[["定语从句","看先行词+从句缺成分:缺主/宾→which/that/who;缺地点状语→where;缺时间→when;表所属→whose。The ship which can dive deep…"],["状语从句","看逻辑:原因 because;让步 although;目的 so that;随着 as。Although whaling was banned, …"],["名词性从句","看是否完整+意思:完整用 that;不确定用 whether;缺成分表''什么''用 what。We know what is happening to the sea."],["非谓语","句中已有谓语:主动/进行 doing;被动/完成 done;目的/将来 to do。Named after a dragon, … / designed to … / making it possible to …"],["强调句","It is/was + 被强调部分 + that…;去掉 It is…that 仍是完整句。It was courage that made his dream come true."],["倒装","Only+状语 / 否定词(Not until, Rarely)置句首→助动词提前。Only then did they understand …"]]},"specialRules":[{"rule":"强调句去掉 It is…that 后剩下的仍是完整句;定语从句去掉关系词后从句缺成分","mark":"It was in 2010 that…(强调时间,that 不可换 when 之外)"},{"rule":"强调时间/地点也用 that,不用 when/where(强调句≠定语从句)","mark":"It was here that I saw it. √ It was here where… ×"},{"rule":"过去分词/现在分词作状语,逻辑主语必须等于主句主语","mark":"Named after a dragon, the submersible…(被命名的是潜水器)"},{"rule":"否定词(Not until / Rarely / Only+状语)置句首 → 部分倒装(助动词提前)","mark":"Not until we act will they forgive us."}],"why":["长句的难点从来不是''生词'',而是''看不出谁是主句'';一旦把多余的动词判成非谓语、把连接词归对从句类型,整句结构就立刻清晰,空格答案唯一。"],"gaokaoPoints":["语法填空高频:which/that/where/when/whose 的判断(看先行词+缺什么成分);so that / although / because 状语连词。","非谓语三选一(doing/done/to do)在长句里作定语、状语、宾补——看主被动与时间关系。","强调句 It is…that 与定语从句辨析;Only/否定词置句首的部分倒装是写作高分点。"],"examVsReal":[{"exam":"It was the writing of logs that allowed sailors to follow the route.（考试:强调句）","real":"The ships'' logs let later sailors follow the same route.","note":"考试爱考强调句辨析;真实英语更常用普通句直接表达"},{"exam":"Only then did they understand why it matters.（考试:倒装）","real":"They only understood then why it mattered.","note":"考试考 Only+状语的部分倒装;口语里很少真的把助动词提前"}]}'::jsonb);

COMMIT;

-- ===== 自带校验 =====
SELECT 'vocab' k, count(*) v, 46 expect FROM public.junior_vocab WHERE volume='elective4' AND unit='U3'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='elective4' AND unit='U3'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='elective4' AND unit='U3'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='elective4' AND unit='U3'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='elective4' AND unit='U3'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE volume='elective4' AND unit='U3' ORDER BY k;
SELECT 'grammar' rel, correct_answer ans, count(*) FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective4' AND unit='U3') GROUP BY 2 ORDER BY 2;
