-- ============================================================
-- 外研社(fltrp) 必修一 U3(Times Change!)灌库(junior_* 表,publisher='fltrp' volume='elective2' unit='U3' grade=11)。幂等。
-- ★DELETE 全带 publisher='fltrp',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 50 =====
DELETE FROM public.junior_vocab WHERE publisher='fltrp' AND volume='elective2' AND unit='U3';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'decade', 'n.', '/ˈdekeɪd/', '十年;十年期', 'The town has changed beyond recognition in the past decade.', '在过去十年里,这座小镇已经变得认不出来了。', 'Times Change', 1, 0, 'senior', 'wordlist', 'elective2', 'U3', 'in just a few decades', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'legendary', 'adj.', '/ˈledʒəndri/', '大名鼎鼎的;传奇式的', 'The legendary old bookstore was once the heart of the neighbourhood.', '这家大名鼎鼎的老书店曾是社区的中心。', 'Times Change', 2, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a legendary bookstore', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'elderly', 'adj.', '/ˈeldəli/', '年老的;上了年纪的', 'The elderly owner found it harder and harder to run his shop.', '上了年纪的店主发现经营店铺越来越难。', 'Times Change', 3, 0, 'senior', 'wordlist', 'elective2', 'U3', 'the elderly owner', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'tablet', 'n.', '/ˈtæblɪt/', '平板电脑', 'More and more young people now read e-books on a tablet.', '如今越来越多的年轻人在平板电脑上读电子书。', 'Times Change', 4, 0, 'senior', 'wordlist', 'elective2', 'U3', 'read e-books on a tablet', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'sympathy', 'n.', '/ˈsɪmpəθi/', '同情;同情心', 'I tried to find some words of sympathy for the old shopkeeper.', '我努力想为那位老店主说几句同情的话。', 'Times Change', 5, 0, 'senior', 'wordlist', 'elective2', 'U3', 'words of sympathy', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'bunch', 'n.', '/bʌntʃ/', '一群,一伙;一束', 'A bunch of us kids used to drop by the store after school.', '我们一群孩子过去常在放学后顺路去那家店。', 'Times Change', 6, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a bunch of kids', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'dusty', 'adj.', '/ˈdʌsti/', '布满灰尘的', 'He would pick the perfect book for us from a dusty shelf.', '他总能从布满灰尘的架子上为我们挑出最合适的书。', 'Times Change', 7, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a dusty shelf', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'shelf', 'n.', '/ʃelf/', '搁板;架子', 'Customers were poring over the shelves selling posters and gifts.', '顾客们正仔细查看摆放海报和礼品的架子。', 'Times Change', 8, 0, 'senior', 'wordlist', 'elective2', 'U3', 'books on the shelf', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'furniture', 'n.', '/ˈfɜːnɪtʃə/', '家具', 'We spent hours reading on the store''s old but comfortable furniture.', '我们坐在店里那些陈旧却舒适的家具上读了几个小时。', 'Times Change', 9, 0, 'senior', 'wordlist', 'elective2', 'U3', 'old but comfortable furniture', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'mist', 'n.', '/mɪst/', '薄雾;雾霭', 'Both the old man and his bookstore were hidden in a thick mist.', '那位老人和他的书店都隐没在浓浓的雾霭中。', 'Times Change', 10, 0, 'senior', 'wordlist', 'elective2', 'U3', 'hidden in a thick mist', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'brick', 'n.', '/brɪk/', '砖;砖块', 'The shop''s old brick exterior had not changed at all.', '这家店那古旧的砖砌外墙一点也没变。', 'Times Change', 11, 0, 'senior', 'wordlist', 'elective2', 'U3', 'the old brick exterior', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'exterior', 'n.', '/ɪkˈstɪəriə/', '外部;外观', 'Outside, the brick exterior looked the same, but inside it was a different world.', '外面的砖墙外观依旧,里面却是另一番天地。', 'Times Change', 12, 0, 'senior', 'wordlist', 'elective2', 'U3', 'the brick exterior', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'stationery', 'n.', '/ˈsteɪʃənri/', '文具', 'Nearby, customers were looking at shelves selling stationery and posters.', '旁边,顾客们正在看摆着文具和海报的货架。', 'Times Change', 13, 0, 'senior', 'wordlist', 'elective2', 'U3', 'shelves selling stationery', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'leadership', 'n.', '/ˈliːdəʃɪp/', '领导;领导地位', 'Under Jennifer''s leadership, the bookstore became a place to get together.', '在珍妮弗的领导下,这家书店成了人们相聚的地方。', 'Times Change', 14, 0, 'senior', 'wordlist', 'elective2', 'U3', 'under her leadership', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'organic', 'adj.', '/ɔːˈɡænɪk/', '有机的;绿色的', 'The new café in the bookstore sells healthy organic food.', '书店里新开的咖啡馆售卖健康的有机食品。', 'Times Change', 15, 0, 'senior', 'wordlist', 'elective2', 'U3', 'organic food', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'jazz', 'n.', '/dʒæz/', '爵士乐', 'The store now holds jazz concerts and movie nights for the community.', '这家店如今为社区举办爵士音乐会和电影之夜。', 'Times Change', 16, 0, 'senior', 'wordlist', 'elective2', 'U3', 'jazz concerts', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'humble', 'adj.', '/ˈhʌmbl/', '简陋的;谦逊的', 'Creativity has brought my humble bookstore into the 21st century.', '创意把我这简陋的小书店带进了21世纪。', 'Times Change', 17, 0, 'senior', 'wordlist', 'elective2', 'U3', 'my humble bookstore', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'compete', 'v.', '/kəmˈpiːt/', '竞争', 'Small shops find it hard to compete with large chain stores.', '小店很难与大型连锁店竞争。', 'Times Change', 18, 0, 'senior', 'wordlist', 'elective2', 'U3', 'compete with chain stores', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'emphasise', 'v.', '/ˈemfəsaɪz/', '强调;着重', 'This sentence is used to emphasise the process rather than the result.', '这个句子用来强调过程而非结果。', 'Times Change', 19, 0, 'senior', 'wordlist', 'elective2', 'U3', 'emphasise the process', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'reconstruction', 'n.', '/ˌriːkənˈstrʌkʃn/', '重建;修复', 'People were doing reconstruction work on the old market last week.', '上周人们正在对那座旧市场进行重建。', 'Times Change', 20, 0, 'senior', 'wordlist', 'elective2', 'U3', 'reconstruction work', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'journalist', 'n.', '/ˈdʒɜːnəlɪst/', '新闻工作者;新闻记者', 'While all this was going on, a journalist was taking photos.', '当这一切正在发生时,一位记者在拍照。', 'Times Change', 21, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a local journalist', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'era', 'n.', '/ˈɪərə/', '时代;年代', 'The reform led the country into a new era of prosperity.', '这场改革把国家带入了一个繁荣的新时代。', 'Times Change', 22, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a new era', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'reform', 'n.', '/rɪˈfɔːm/', '改革;改进', 'The reform and opening-up policy has changed Chinese society greatly.', '改革开放政策极大地改变了中国社会。', 'Times Change', 23, 0, 'senior', 'wordlist', 'elective2', 'U3', 'the reform and opening-up', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'pave', 'v.', '/peɪv/', '铺(路);(为……)铺平道路', 'The policy paved the way for the country to become modern.', '这项政策为国家走向现代化铺平了道路。', 'Times Change', 24, 0, 'senior', 'wordlist', 'elective2', 'U3', 'pave the way', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'socialist', 'adj.', '/ˈsəʊʃəlɪst/', '社会主义的', 'The journey is paving the way for a fully modernised socialist country.', '这段历程正在为一个全面现代化的社会主义国家铺平道路。', 'Times Change', 25, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a socialist country', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'alongside', 'prep.', '/əˌlɒŋˈsaɪd/', '(与……)一起;在……旁边', 'China continues to develop further alongside other countries.', '中国继续与其他国家一起向前发展。', 'Times Change', 26, 0, 'senior', 'wordlist', 'elective2', 'U3', 'develop alongside others', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'initiative', 'n.', '/ɪˈnɪʃətɪv/', '倡议;主动性', 'The Belt and Road Initiative means a new dawn for trade between countries.', '“一带一路”倡议意味着国家间贸易的新曙光。', 'Times Change', 27, 0, 'senior', 'wordlist', 'elective2', 'U3', 'the Belt and Road Initiative', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'solid', 'adj.', '/ˈsɒlɪd/', '坚实的;牢固的', 'The park formed a solid basis for future business development.', '这个园区为未来的商业发展打下了坚实的基础。', 'Times Change', 28, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a solid basis', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'economic', 'adj.', '/ˌiːkəˈnɒmɪk/', '经济(上)的', 'Shenzhen was the first special economic zone in China.', '深圳是中国第一个经济特区。', 'Times Change', 29, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a special economic zone', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'occupation', 'n.', '/ˌɒkjuˈpeɪʃn/', '工作;职业', 'On the form, she wrote down her occupation as a teacher.', '在表格上,她把职业一栏填成了教师。', 'Times Change', 30, 0, 'senior', 'wordlist', 'elective2', 'U3', 'state your occupation', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'cafeteria', 'n.', '/ˌkæfəˈtɪəriə/', '自助餐厅', 'While waiting outside the cafeteria, I received a strange message.', '在自助餐厅外等候时,我收到了一条奇怪的消息。', 'Times Change', 31, 0, 'senior', 'wordlist', 'elective2', 'U3', 'outside the cafeteria', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'emoji', 'n.', '/ɪˈməʊdʒi/', '表情符号', 'Today people often communicate with emojis instead of words.', '如今人们常常用表情符号而非文字来交流。', 'Times Change', 32, 0, 'senior', 'wordlist', 'elective2', 'U3', 'communicate with emojis', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'integral', 'adj.', '/ˈɪntɪɡrəl/', '不可缺少的;必需的', 'Emojis are becoming an integral component of the language we use.', '表情符号正成为我们所用语言中不可缺少的组成部分。', 'Times Change', 33, 0, 'senior', 'wordlist', 'elective2', 'U3', 'an integral component', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'component', 'n.', '/kəmˈpəʊnənt/', '组成部分;成分', 'Pictures have become a key component of online messages.', '图画已成为网络消息的一个关键组成部分。', 'Times Change', 34, 0, 'senior', 'wordlist', 'elective2', 'U3', 'an important component', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'category', 'n.', '/ˈkætəɡri/', '类别;种类', 'Emojis come in different categories, such as faces, animals and food.', '表情符号分为不同类别,如表情、动物和食物。', 'Times Change', 35, 0, 'senior', 'wordlist', 'elective2', 'U3', 'different categories', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'expand', 'v.', '/ɪkˈspænd/', '(使)扩大;增加', 'New emojis expand the way in which we communicate every year.', '每年都有新的表情符号拓展着我们交流的方式。', 'Times Change', 36, 0, 'senior', 'wordlist', 'elective2', 'U3', 'expand the way we communicate', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'emotional', 'adj.', '/ɪˈməʊʃənl/', '情绪(上)的;情感的', 'People like emojis because they add emotional meaning to a message.', '人们喜欢表情符号,因为它们给信息增添了情感意味。', 'Times Change', 37, 0, 'senior', 'wordlist', 'elective2', 'U3', 'add emotional meaning', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'gesture', 'n.', '/ˈdʒestʃə/', '手势;姿势', 'Using emojis is similar to the gestures we make when we speak.', '使用表情符号就像我们说话时做的手势。', 'Times Change', 38, 0, 'senior', 'wordlist', 'elective2', 'U3', 'similar to gestures', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'intention', 'n.', '/ɪnˈtenʃn/', '意图;目的', 'The intention of these new versions is to attract young readers.', '这些新版本的意图是吸引年轻读者。', 'Times Change', 39, 0, 'senior', 'wordlist', 'elective2', 'U3', 'the intention of the change', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'adaptation', 'n.', '/ˌædæpˈteɪʃn/', '改编版;改编', 'The adaptation replaced some of Shakespeare''s words with emojis.', '这个改编版用表情符号替换了莎士比亚的一些词句。', 'Times Change', 40, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a modern adaptation', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'accessible', 'adj.', '/əkˈsesəbl/', '易懂的;可使用的', 'The aim is to make the classics more accessible to young readers.', '其目的是让经典作品对年轻读者来说更易懂。', 'Times Change', 41, 0, 'senior', 'wordlist', 'elective2', 'U3', 'make the classics accessible', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'soul', 'n.', '/səʊl/', '精神;灵魂', 'Some people feel the new versions have lost the heart and soul of the plays.', '有些人觉得这些新版本失去了戏剧的精髓。', 'Times Change', 42, 0, 'senior', 'wordlist', 'elective2', 'U3', 'the heart and soul', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'tendency', 'n.', '/ˈtendənsi/', '趋势;倾向', 'Emojis have a tendency to pop up all over the place these days.', '如今表情符号有到处冒出来的趋势。', 'Times Change', 43, 0, 'senior', 'wordlist', 'elective2', 'U3', 'have a tendency to', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'facilitate', 'v.', '/fəˈsɪlɪteɪt/', '促进;使便利', 'Users say that emojis facilitate the way in which we communicate.', '使用者说表情符号让我们的交流方式更加便利。', 'Times Change', 44, 0, 'senior', 'wordlist', 'elective2', 'U3', 'facilitate communication', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'educator', 'n.', '/ˈedjʊkeɪtə/', '教育工作者', 'Some educators worry that we are losing the ability to write properly.', '一些教育工作者担心我们正在失去好好写字的能力。', 'Times Change', 45, 0, 'senior', 'wordlist', 'elective2', 'U3', 'worry educators', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'secondary', 'adj.', '/ˈsekəndri/', '次要的;第二位的', 'To many young users, spelling has become of secondary importance.', '对许多年轻用户来说,拼写已变得次要了。', 'Times Change', 46, 0, 'senior', 'wordlist', 'elective2', 'U3', 'of secondary importance', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'comic', 'n.', '/ˈkɒmɪk/', '连环漫画', 'In the comics, Clark Kent would change into his Superman costume in a phone box.', '在连环漫画里,克拉克·肯特会在电话亭里换上超人服装。', 'Times Change', 47, 0, 'senior', 'wordlist', 'elective2', 'U3', 'in the comics', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'costume', 'n.', '/ˈkɒstjuːm/', '化装服;服装', 'He used to pop into a phone box to change into his costume.', '他过去常钻进电话亭去换上他的服装。', 'Times Change', 48, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a Superman costume', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'urgently', 'adv.', '/ˈɜːdʒəntli/', '紧急地;急迫地', 'Even if we needed to call someone urgently, we would borrow a mobile phone.', '即使我们急需给某人打电话,也会借一部手机。', 'Times Change', 49, 0, 'senior', 'wordlist', 'elective2', 'U3', 'need to call urgently', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'convincing', 'adj.', '/kənˈvɪnsɪŋ/', '有说服力的;令人信服的', 'The writer gives several convincing reasons why phone boxes are disappearing.', '作者给出了几个有说服力的理由来解释电话亭为何正在消失。', 'Times Change', 50, 0, 'senior', 'wordlist', 'elective2', 'U3', 'a convincing argument', NULL, 'fltrp');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3');
DELETE FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('fe2u3.01', '①was/were being done(过去某刻动作正在被进行)', 'A2', 11, '外研社版选择性必修第二册 U3 — 过去某一时刻某动作正在进行、且主语是动作的承受者时,用 was/were being + 过去分词。常见标志:when I arrived / at that moment / right then / still / not finished yet。', 1, 'elective2', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('fe2u3.02', '②过去进行被动 vs 过去进行主动(看主语是不是施动者)', 'A2', 11, '外研社版选择性必修第二册 U3 — 主语是动作承受者用被动 was/were being done;若主语自己在执行动作才用主动 was/were doing。常配 by 短语;助动词单复数须与主语一致。', 2, 'elective2', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('fe2u3.03', '③过去进行被动 vs 一般过去被动(过程未完 vs 已完成的结果)', 'A2', 11, '外研社版选择性必修第二册 U3 — 强调过去某刻动作仍在进行、尚未完成,用 was/were being done;强调到某时动作已完成、只看结果(already/by then/completely),用一般过去被动 was/were done。', 3, 'elective2', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'When I hurried into the shop, the books ____ into boxes right in front of me.', 'were being packed', 'were packing', 'were packed', 'packed', 'A', '过去那一刻书正被装箱、书是承受者 → were being packed;''right in front of me''示进行中,排除表结果的 were packed,书不能自己装箱排除主动。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'As I walked past the market, the old gate ____ down by the workers.', 'was tearing', 'was being torn', 'was torn', 'tore', 'B', '门正被工人拆、门是承受者且有 by 短语 → was being torn;主语不会自己拆排除主动,正在进行排除表结果的 was torn。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'While all this was going on, photos ____ by a local journalist.', 'were taking', 'were taken', 'were being taken', 'took', 'C', '照片正被记者拍 → were being taken;while 引导同时进行,排除表结果的 were taken,照片是承受者排除主动。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'When I looked up, customers'' comments ____ on the big screen at that very moment.', 'were displaying', 'were displayed', 'displayed', 'were being displayed', 'D', '评论那一刻正被显示 → were being displayed;''at that very moment''示进行,排除 were displayed,评论是承受者排除主动。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'I arrived just as the wooden stands ____ from the old market.', 'were being removed', 'were removing', 'were removed', 'removed', 'A', '''just as''示动作正进行、货摊被搬走 → were being removed;货摊是承受者排除主动,进行中排除表结果。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'When the bell rang, the rubbish ____ away from the floor.', 'was clearing', 'was being cleared', 'was cleared', 'cleared', 'B', '铃响那刻垃圾正被清走 → was being cleared;垃圾是承受者排除主动,正在进行排除表结果的 was cleared。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'As we entered the store, a book reading ____ in one corner.', 'was delivering', 'was delivered', 'was being delivered', 'delivered', 'C', '我们进门时朗读会正在进行 → was being delivered;活动是承受者排除主动,进行中排除表结果。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'Right then, the tired old market ____ into a modern shopping mall.', 'was turning', 'was turned', 'turned', 'was being turned', 'D', '''right then''示那刻正被改造 → was being turned;市场是承受者排除主动,进行中排除表结果的 was turned。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'When I passed by last week, new roads ____ across the whole district.', 'were being paved', 'were paving', 'were paved', 'paved', 'A', '经过时道路正被铺设 → were being paved;道路是承受者排除主动,正在进行排除表结果。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'At that moment, the large board in the corner ____ by a big screen.', 'was replacing', 'was being replaced', 'was replaced', 'replaced', 'B', '''at that moment''+ by 短语,板子正被替换 → was being replaced;板子是承受者排除主动,进行中排除表结果。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'As I watched, the dusty shelves ____ with fresh new books.', 'were filling', 'were filled', 'were being filled', 'filled', 'C', '''as I watched''示动作正进行、书架被摆满 → were being filled;书架是承受者排除主动,进行中排除表结果。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'When the reporter called, the news story ____ for the morning paper.', 'was writing', 'was written', 'wrote', 'was being written', 'D', '记者打来时稿子正被赶写 → was being written;稿子是承受者排除主动,进行中排除表结果的 was written。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'As the camera turned on, an interview ____ live online.', 'was being done', 'was doing', 'was done', 'did', 'A', '镜头开时采访正被进行 → was being done;采访是承受者排除主动,正在进行排除表结果。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'When I stepped inside, the café tables ____ for the evening jazz concert.', 'were setting', 'were being set', 'were set', 'set', 'B', '进门那刻桌子正被布置 → were being set;桌子是承受者排除主动,进行中排除表结果的 were set。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'As I came in, fresh organic food ____ in the new café.', 'was serving', 'was served', 'was being served', 'served', 'C', '进来时食物正被供应 → was being served;食物是承受者排除主动,进行中排除表结果。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'When I returned, the shop''s brick exterior ____ by a team of builders.', 'was repairing', 'was repaired', 'repaired', 'was being repaired', 'D', '回来时外墙正被工人修缮、有 by 短语 → was being repaired;外墙是承受者排除主动,进行中排除表结果。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'Just as I sat down, posters and gifts ____ on the front shelves.', 'were being arranged', 'were arranging', 'were arranged', 'arranged', 'A', '坐下那刻海报礼品正被摆放 → were being arranged;它们是承受者排除主动,进行中排除表结果。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'When the manager arrived, the day''s best-seller ____ in the window.', 'was showing', 'was being shown', 'was shown', 'showed', 'B', '经理到时畅销书正被展示 → was being shown;书是承受者排除主动,进行中排除表结果的 was shown。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'As the crowd gathered, an old phone box ____ away from the street corner.', 'was taking', 'was taken', 'was being taken', 'took', 'C', '人群聚拢时电话亭正被搬走 → was being taken (away);电话亭是承受者排除主动,进行中排除表结果。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.01'), 'While I waited, the classic play ____ into a version full of emojis.', 'was adapting', 'was adapted', 'adapted', 'was being adapted', 'D', '等候时剧本正被改编 → was being adapted;剧本是承受者排除主动,进行中排除表结果的 was adapted。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'When the photographer arrived, the old market ____ into a shopping mall.', 'was being turned', 'was turning', 'were being turned', 'turned', 'A', '市场是承受者、那刻正被改造 → was being turned;主语并非施动者排除主动 was turning,单数主语排除 were。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'All through that decade, Shenzhen ____ from a small town into a huge city.', 'was transforming', 'was being transformed', 'were being transformed', 'transformed', 'B', '深圳是被改变的对象 → was being transformed;城市不自行改造排除主动,单数主语排除 were。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'While the policy was new, thousands of factories ____ across the south by investors.', 'were building', 'was being built', 'were being built', 'built', 'C', '工厂是承受者、有 by 短语 → were being built;工厂不会自己建排除主动,复数主语排除 was。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'When I visited, tall skyscrapers ____ up along the river by the construction teams.', 'were putting', 'was being put', 'put', 'were being put', 'D', '摩天楼是被建造的对象、有 by 短语 → were being put (up);它们不会自己建排除主动,复数主语排除 was。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'As the reform went on, old wooden houses ____ down one by one by the workers.', 'were being pulled', 'were pulling', 'was being pulled', 'pulled', 'A', '房子是被拆的对象、有 by 短语 → were being pulled (down);房子不会自己拆排除主动,复数主语排除 was。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'Right then, a brand-new road ____ through the busy district.', 'was laying', 'was being laid', 'were being laid', 'laid', 'B', '道路是被铺设的对象 → was being laid;道路不自己铺排除主动,单数主语排除 were。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'When the journalist arrived, the news ____ straight onto the Internet.', 'was releasing', 'were being released', 'was being released', 'released', 'C', '新闻是被发布的对象 → was being released;新闻不会自己发布排除主动,单数主语排除 were。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'In those years, more and more stories ____ on computers rather than on paper.', 'were editing', 'was being edited', 'edited', 'were being edited', 'D', '稿件是被编辑的对象 → were being edited;稿件不会自己编排除主动,复数主语排除 was。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'As I watched the documentary, an old interview ____ face to face.', 'was being done', 'was doing', 'were being done', 'did', 'A', '采访是被进行的对象 → was being done;采访不会自己进行排除主动,单数主语排除 were。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'When the bell rang, the morning papers ____ to people''s doors by the staff.', 'were delivering', 'were being delivered', 'was being delivered', 'delivered', 'B', '报纸是被投送的对象、有 by 短语 → were being delivered;报纸不会自己送排除主动,复数主语排除 was。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'While the campaign went on, the bookstore ____ back to life by the whole community.', 'was bringing', 'were being brought', 'was being brought', 'brought', 'C', '书店是被挽救的对象、有 by 短语 → was being brought (back);书店不会自己复活排除主动,单数主语排除 were。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'When I came back, the dusty old shelves ____ with bright new books by two assistants.', 'were stocking', 'was being stocked', 'stocked', 'were being stocked', 'D', '书架是被摆放的对象、有 by 短语 → were being stocked;书架不会自己上货排除主动,复数主语排除 was。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'As the café opened, organic meals ____ to literature lovers by the new staff.', 'were being offered', 'were offering', 'was being offered', 'offered', 'A', '餐食是被提供的对象、有 by 短语 → were being offered;餐食不会自己提供排除主动,复数主语排除 was。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'Right at that moment, customers ____ away by online discounts and chain stores.', 'were attracting', 'were being attracted', 'was being attracted', 'attracted', 'B', '顾客是被吸引的对象、有 by 短语 → were being attracted;此处顾客是承受者排除主动,复数主语排除 was。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'When the new owner took over, the corner board ____ by a digital screen.', 'was replacing', 'were being replaced', 'was being replaced', 'replaced', 'C', '板子是被替换的对象、有 by 短语 → was being replaced;板子不会自己替换排除主动,单数主语排除 were。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'Throughout the spring, the town''s old streets ____ by the builders.', 'were widening', 'was being widened', 'widened', 'were being widened', 'D', '街道是被拓宽的对象、有 by 短语 → were being widened;街道不会自己变宽排除主动,复数主语排除 was。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'As trade grew, new markets ____ by local entrepreneurs across the region.', 'were being opened', 'were opening', 'was being opened', 'opened', 'A', '市场是被开办的对象、有 by 短语 → were being opened;市场不会自己开排除主动,复数主语排除 was。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'When I arrived at the park, a welcome speech ____ to the new companies.', 'was giving', 'was being given', 'were being given', 'gave', 'B', '致辞是被发表的对象 → was being given;致辞不会自己发表排除主动,单数主语排除 were。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'During the festival, jazz concerts ____ in the bookshop café by young musicians.', 'were holding', 'was being held', 'were being held', 'held', 'C', '音乐会是被举办的对象、有 by 短语 → were being held;音乐会不会自己举办排除主动,复数主语排除 was。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.02'), 'While reporters watched, the old printing machines ____ out of the building by the staff.', 'were moving', 'was being moved', 'moved', 'were being moved', 'D', '机器是被搬走的对象、有 by 短语 → were being moved;机器不会自己搬排除主动,复数主语排除 was。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'When I rushed in, the books ____ into boxes — the work was not finished yet.', 'were being packed', 'were packed', 'were packing', 'packed', 'A', '''not finished yet''示动作仍在进行 → were being packed;若用 were packed 就成了已完成的结果,与''尚未完成''矛盾。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'As I watched, the old gate ____ down; half of it still stood there.', 'was pulled', 'was being pulled', 'was pulling', 'pulled', 'B', '''half still stood''示拆除未完 → was being pulled (down);was pulled 表已拆完的结果,与''还剩一半''矛盾。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'Right at that moment, the news ____ onto the website, line by line.', 'was uploaded', 'was uploading', 'was being uploaded', 'uploaded', 'C', '''line by line''+ at that moment 示正在上传 → was being uploaded;was uploaded 表已传完的结果,不合。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'While the builders worked, the brick wall ____ piece by piece.', 'was repaired', 'was repairing', 'repaired', 'was being repaired', 'D', '''while…piece by piece''示修缮正进行 → was being repaired;was repaired 表已修好的结果,不合。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'When the reporter phoned, the story ____ and was only half done.', 'was being written', 'was written', 'was writing', 'wrote', 'A', '''only half done''示写作未完 → was being written;was written 表已写完的结果,与''只写了一半''矛盾。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'As customers looked on, fresh books ____ onto the empty shelves.', 'were placed', 'were being placed', 'were placing', 'placed', 'B', '''as customers looked on''示动作正进行 → were being placed;were placed 表已摆好的结果,不合。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'Just then, the corner board ____ with a new screen, and wires still hung loose.', 'was replaced', 'was replacing', 'was being replaced', 'replaced', 'C', '''wires still hung loose''示更换未完 → was being replaced;was replaced 表已换好的结果,与''电线还松垂''矛盾。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'While I waited, my friend''s message ____ in emojis, one symbol at a time.', 'was typed', 'was typing', 'typed', 'was being typed', 'D', '''one symbol at a time''示正在输入 → was being typed;was typed 表已打完的结果,不合。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'As the festival opened, a jazz concert ____ on the little stage right then.', 'was being held', 'was held', 'was holding', 'held', 'A', '''right then''示那刻正在举办 → was being held;was held 表已结束的一次活动,与''正进行''不合。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'When I returned at noon, the market ____ into a mall, with cranes still working.', 'was turned', 'was being turned', 'was turning', 'turned', 'B', '''cranes still working''示改造未完 → was being turned;was turned 表已改造完的结果,与''吊车还在作业''矛盾。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'By the time I got there, the books ____ into boxes, and the shelves were already empty.', 'were being packed', 'were packing', 'were packed', 'packed', 'C', '''by the time…already empty''示动作已完成、只看结果 → were packed;were being packed 表过程进行,与''已装完、架空了''矛盾。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'When I arrived, the old gate ____ down completely; only a pile of bricks remained.', 'was being pulled', 'was pulling', 'pulled', 'was pulled', 'D', '''completely…only bricks remained''示已拆完 → was pulled (down);was being pulled 表正在拆,与''已全拆完''矛盾。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'By last night, the news ____ on every website, and everyone had already read it.', 'was released', 'was being released', 'was releasing', 'released', 'A', '''by last night…already read''示已发布完 → was released;was being released 表正在发布,与''大家都读过了''矛盾。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'When the editor checked it, the story ____ and ready to print.', 'was being finished', 'was finished', 'was finishing', 'finished', 'B', '''ready to print''示已完成 → was finished;was being finished 表正在收尾,与''已可付印''不合。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'By the time the café opened, the new shelves ____ with hundreds of books.', 'were being filled', 'were filling', 'were filled', 'filled', 'C', '''by the time…opened''示开门前已摆满 → were filled;were being filled 表正在摆放,与''已摆满''不合。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'When I looked again, the corner board ____ by a screen, and the change was complete.', 'was being replaced', 'was replacing', 'replaced', 'was replaced', 'D', '''the change was complete''示已换好 → was replaced;was being replaced 表正在更换,与''更换已完成''矛盾。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'By spring, the whole market ____ into a modern mall, and shoppers were already inside.', 'was turned', 'was being turned', 'was turning', 'turned', 'A', '''by spring…already inside''示已改造完 → was turned;was being turned 表正在改造,与''顾客已在里面''矛盾。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'When the staff arrived, the morning papers ____ and stacked neatly by the door.', 'were being delivered', 'were delivered', 'were delivering', 'delivered', 'B', '''stacked neatly''示已送达并码好 → were delivered;were being delivered 表正在投送,与''已码好''不合。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'By the end of the week, the old phone box ____ from the corner, and the street looked bare.', 'was being removed', 'was removing', 'was removed', 'removed', 'C', '''by the end…looked bare''示已搬走 → was removed;was being removed 表正在搬,与''已不见、街角空了''矛盾。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' AND code='fe2u3.03'), 'When I opened the book, I saw that some scenes ____ into emojis already.', 'were being adapted', 'were adapting', 'adapted', 'were adapted', 'D', '''already''示已改编完 → were adapted;were being adapted 表正在改编,与''已经改完''矛盾。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='fltrp' AND volume='elective2' AND unit='U3';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'The Day the Bookstore Closed', 'The day I heard that the Rainbow Bookstore was closing after fifty years, I felt heartbroken. For decades it had been a legendary fixture in our neighbourhood, a place where anyone could drop in and connect through a love of books. When I hurried over, I saw that the books were already being packed into boxes. I had a long chat with Casey, the elderly owner. Sighing deeply, he told me how hard it had become to run an independent shop. Most young people now preferred reading e-books on a tablet, and more and more customers were being attracted by chain stores and online discounts. I tried to think of some words of sympathy, but I had to admit that the little store could not stay in business much longer. As I left, the shop was hidden in a thick mist, and I feared that everything Casey had given the community might soon disappear for good.', '记叙·老书店即将关张', 156, '[{"q":"How did the writer feel on hearing the news about the bookstore?","answer":"A","options":["Deeply upset and sad.","Pleased and relieved.","Bored and uninterested.","Angry at the customers."],"explanation":"原文 ''I felt heartbroken'' 的转述。"},{"q":"According to Casey, why was the shop hard to keep running?","answer":"B","options":["Because the staff were lazy.","Because young readers chose e-books and chains instead.","Because the rent had suddenly doubled.","Because the books were too expensive to print."],"explanation":"原文 ''preferred reading e-books… attracted by chain stores and online discounts'' 的转述。"},{"q":"What did the writer fear as he left the store?","answer":"A","options":["That the town might lose all the old shop had meant.","That the prices would rise.","That Casey would move abroad.","That a chain store would buy the building."],"explanation":"末句 ''everything Casey had given the community might soon disappear'' 的转述。"}]'::jsonb, '[{"word":"legendary","cn":"大名鼎鼎的"},{"word":"elderly","cn":"年老的"},{"word":"sympathy","cn":"同情"}]'::jsonb, 2, 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'A Bookstore Brought Back to Life', 'A few months later, I returned to the neighbourhood during my spring break and was amazed to see the Rainbow Bookstore still open. Its old brick exterior had not changed, but inside it was like a different world. In one area, a book reading was being delivered, while nearby customers looked at shelves selling stationery, posters and other gifts. The large board in the corner had been replaced by a big screen on which readers'' comments were being displayed. I soon learned that the community had decided to work together on a campaign to save the shop. The campaign was led by Jennifer Oakley, a saleswoman who had grown up locally and had now taken over from Casey. Under her leadership, the store was being turned into a place for book lovers to gather. It had a café selling organic food, and there were now poetry recitals and even jazz concerts, where people could share an experience that could not simply be downloaded.', '记叙·社区救活书店', 163, '[{"q":"What surprised the writer when he came back?","answer":"B","options":["The store was still open and full of life.","The shop had moved to a new street.","Casey had reopened it alone.","The brick walls had been painted bright red."],"explanation":"原文 ''was amazed to see the Rainbow Bookstore still open'' 的转述;干扰项与原文相反或未提。"},{"q":"Who was behind the campaign to save the bookstore?","answer":"C","options":["A famous national company.","The local community led by Jennifer Oakley.","Casey''s own children.","A group of visiting tourists."],"explanation":"原文 ''the community had decided to work together… led by Jennifer Oakley'' 的转述。"},{"q":"What did the new store offer that could not be downloaded?","answer":"D","options":["Cheaper e-books online.","Free tablets for readers.","Shared live events like recitals and concerts.","A faster delivery service."],"explanation":"末句 ''poetry recitals and even jazz concerts… could not simply be downloaded'' 的转述。"}]'::jsonb, '[{"word":"exterior","cn":"外观"},{"word":"leadership","cn":"领导"},{"word":"recital","cn":"朗诵会"}]'::jsonb, 2, 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'How the News Industry Changed', 'Not long ago, the way we received the news looked completely different. Reporters would travel to meet people, and most interviews were done face to face. Stories were written by hand or typed, then edited with a pen before being printed on paper. Each morning, fresh newspapers were delivered to homes, and readers waited a whole day for the next edition. Today the picture has changed beyond recognition. Many interviews are now done online, and a story can be released on the Internet the moment it is finished. Editors work on computers instead of paper, and readers can follow events minute by minute on their phones. Some older people miss the feel of a paper in their hands, yet few would give up the speed of digital news. The tools have changed, but the job of a good journalist stays the same: to find the truth and share it clearly with the public, whatever form the news may take.', '说明·新闻业的变迁', 159, '[{"q":"How were most interviews carried out in the past?","answer":"A","options":["In person, with reporters meeting people directly.","Only through long phone calls.","Entirely by sending letters.","By reading comments online."],"explanation":"原文 ''most interviews were done face to face'' 的转述。"},{"q":"What is one main change in today''s news industry?","answer":"B","options":["Newspapers are no longer written at all.","A story can appear online as soon as it is ready.","Reporters never use computers now.","Readers must wait several days for news."],"explanation":"原文 ''a story can be released on the Internet the moment it is finished'' 的转述。"},{"q":"According to the writer, what has stayed the same?","answer":"C","options":["The price of every newspaper.","The time readers wait for news.","The reporter''s duty to seek and share the truth.","The habit of editing with a pen."],"explanation":"末句 ''the job of a good journalist stays the same: to find the truth and share it'' 的转述。"}]'::jsonb, '[{"word":"journalist","cn":"记者"},{"word":"edit","cn":"编辑"},{"word":"release","cn":"发布"}]'::jsonb, 2, 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'A Small Town Becomes a City', 'More than forty years ago, China began the reform and opening-up policy, starting a journey that would pave the way for the country to modernise. Few places show this change more clearly than Shenzhen. Within living memory it was only a small fishing town, where people made a living from the sea and one quiet day was much like the next. After it became the first special economic zone, everything began to move quickly. Roads were being laid, factories were being built, and tall skyscrapers were being put up almost faster than the eye could follow. In just a few decades, the small town developed into a modern city of millions, full of energy and new ideas. Older residents still remember the muddy lanes of their childhood, while their grandchildren grow up surrounded by glass towers and busy trade. To many, Shenzhen stands as living proof that a place, like the times, can be completely remade.', '说明·深圳的改革变迁', 156, '[{"q":"What was Shenzhen like before the reform policy?","answer":"D","options":["Already a city of millions.","A famous centre of trade.","An empty stretch of desert.","A small town living mainly off the sea."],"explanation":"原文 ''only a small fishing town, where people made a living from the sea'' 的转述。"},{"q":"What happened after Shenzhen became a special economic zone?","answer":"A","options":["Rapid building and growth began.","Most people moved away.","The sea trade was banned.","Nothing changed for years."],"explanation":"原文 ''everything began to move quickly. Roads were being laid…'' 的转述。"},{"q":"What does Shenzhen prove, according to the writer?","answer":"B","options":["That fishing towns never change.","That a place can be completely transformed over time.","That cities should stay small.","That old lanes are better than towers."],"explanation":"末句 ''a place, like the times, can be completely remade'' 的转述。"}]'::jsonb, '[{"word":"reform","cn":"改革"},{"word":"economic","cn":"经济的"},{"word":"decade","cn":"十年"}]'::jsonb, 2, 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Emojis: A New Language?', 'Not so long ago, a written message was made only of words. Now a single smiling face or a string of tiny pictures can carry a whole feeling. The word emoji comes from Japanese and means picture character. When these little symbols first appeared in 1999, there were only a couple of hundred designs; today there are thousands, sorted into categories such as faces, animals and food. People enjoy them because they are quick to use and add emotional meaning, working rather like the gestures we make when we speak. With a smiling or sad face beside your words, a reader can almost see your expression. The trend has even reached classical literature, where some plays have been adapted with emojis to make them more accessible to young readers. Yet a few educators worry that, if we rely too much on pictures, we may slowly lose the ability to express ourselves in careful written words. For now, perhaps we should simply enjoy using them wisely.', '议论·表情符号的兴起', 165, '[{"q":"What does the word ''emoji'' originally mean?","answer":"C","options":["Quick message.","Happy face.","Picture character.","Spoken word."],"explanation":"原文 ''comes from Japanese and means picture character'' 的转述。"},{"q":"Why do many people enjoy using emojis?","answer":"D","options":["They cost extra money to send.","They make spelling harder.","They replace all written words.","They are fast to use and add feeling."],"explanation":"原文 ''quick to use and add emotional meaning'' 的转述。"},{"q":"What concern do some educators have about emojis?","answer":"A","options":["That heavy use may weaken careful writing.","That they are too expensive.","That they cannot show feelings.","That children cannot understand them."],"explanation":"原文 ''we may slowly lose the ability to express ourselves in careful written words'' 的转述。"}]'::jsonb, '[{"word":"emoji","cn":"表情符号"},{"word":"category","cn":"类别"},{"word":"accessible","cn":"易懂的"}]'::jsonb, 2, 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Where Did the Phone Box Go?', 'Watching an old superhero film the other day, I had a sudden thought: where would Superman get changed these days? In the comics and earlier films, Clark Kent would pop into a phone box and come out in his costume. But phone boxes are now hard to find, and the reason is simple — we no longer need them. Almost everyone carries a mobile phone, and it is far easier to make a call at the touch of a button than to press a long row of numbers in a cold box. Even someone who leaves their phone at home gains little, since few of us still remember the numbers we want; our phones do that for us. And if we truly needed to call someone urgently, it would be quicker to borrow a phone than to hunt for a box. So the phone box is quietly becoming a thing of the past, and poor Clark Kent will have to find somewhere else to change.', '议论·消失的电话亭', 165, '[{"q":"What made the writer think about Superman?","answer":"B","options":["Reading a new comic book.","He saw an old film about a superhero.","Losing his own phone.","Visiting a phone box."],"explanation":"原文 ''Watching an old superhero film the other day, I had a sudden thought'' 的转述。"},{"q":"Why does the writer say phone boxes are disappearing?","answer":"C","options":["Because they have become too expensive.","Because they take up too much space.","Because people simply no longer need them.","Because they are ugly to look at."],"explanation":"原文 ''the reason is simple — we no longer need them'' 的转述。"},{"q":"Why does forgetting a phone at home no longer matter much?","answer":"D","options":["Because phone boxes are everywhere.","Because numbers are printed on every street.","Because nobody makes calls any more.","Because our mobiles remember the numbers for us."],"explanation":"原文 ''few of us still remember the numbers… our phones do that for us'' 的转述。"}]'::jsonb, '[{"word":"comic","cn":"连环漫画"},{"word":"costume","cn":"服装"},{"word":"urgently","cn":"紧急地"}]'::jsonb, 2, 'elective2', 'U3', 'fltrp');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='fltrp' AND volume='elective2' AND unit='U3';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U3', 'A Child''s Bookstore Memory', 'When I was young, a (1)____ of us would drop by the Rainbow Bookstore after school every day. The shop was old and (2)____, with books piled on every shelf, but we loved it. Old Casey knew every book in the store and would always (3)____ the perfect one for us from a dusty corner. We spent hours (4)____, sitting on the comfortable old furniture. Casey often (5)____ us to share our ideas by writing them on a large (6)____ in one corner. To us, the bookstore was not just a shop; it was a second (7)____. Years later, when I heard that it might (8)____, I felt heartbroken. I could still (9)____ the smell of the old pages and the sound of Casey''s voice. That little store had quietly (10)____ the way I saw the world.', 137, 2, '[{"q":"1","answer":"A","options":["bunch","slice","sheet","drop"],"explanation":"a bunch of us 我们一群人;其余不与''人''搭配。"},{"q":"2","answer":"B","options":["shiny","dusty","modern","new"],"explanation":"old and dusty 又旧又布满灰尘;其余与''old''矛盾。"},{"q":"3","answer":"C","options":["throw","sell","pick","drop"],"explanation":"pick the perfect one 挑出最合适的一本。"},{"q":"4","answer":"D","options":["sleeping","cooking","shopping","reading"],"explanation":"spent hours reading 读了几个小时。"},{"q":"5","answer":"A","options":["encouraged","refused","disappeared","competed"],"explanation":"encouraged us to share 鼓励我们分享;其余搭配或语义不通。"},{"q":"6","answer":"B","options":["fridge","board","river","cloud"],"explanation":"a large board 一块大板子,用来写评论。"},{"q":"7","answer":"C","options":["airport","factory","home","prison"],"explanation":"a second home 第二个家,表温馨。"},{"q":"8","answer":"D","options":["open","grow","win","close"],"explanation":"might close 可能关张,呼应 heartbroken。"},{"q":"9","answer":"A","options":["remember","forget","lose","throw"],"explanation":"still remember the smell 仍记得那气味。"},{"q":"10","answer":"B","options":["broken","changed","sold","cleaned"],"explanation":"changed the way I saw the world 改变了我看世界的方式。"}]'::jsonb, 1, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U3', 'From Letters to Instant Messages', 'Fifty years ago, if you wanted to send a (1)____ to a friend far away, you wrote a letter by hand. You then had to (2)____ it to the post office and wait many days for a reply. Today, everything is (3)____. A message can reach the other side of the world in a (4)____. We can add photos, voice notes and even tiny pictures called emojis to (5)____ our feelings. Young people often (6)____ with emojis instead of words, because they are quick and fun. Some older people find this strange and (7)____ that we are forgetting how to write properly. Others believe it is simply a new (8)____ of communicating. Whatever you think, one thing is (9)____: the way we keep in touch has changed for ever, and there is probably no going (10)____.', 136, 2, '[{"q":"1","answer":"C","options":["weather","dinner","message","garden"],"explanation":"send a message 发一条消息。"},{"q":"2","answer":"D","options":["eat","lose","sing","carry"],"explanation":"carry it to the post office 把信带到邮局。"},{"q":"3","answer":"A","options":["instant","slow","heavy","silent"],"explanation":"everything is instant 一切都是即时的;slow 与下文矛盾。"},{"q":"4","answer":"B","options":["year","second","week","month"],"explanation":"in a second 一秒钟内,表极快。"},{"q":"5","answer":"C","options":["hide","forget","express","sell"],"explanation":"express our feelings 表达感受。"},{"q":"6","answer":"D","options":["sleep","travel","cook","communicate"],"explanation":"communicate with emojis 用表情符号交流。"},{"q":"7","answer":"A","options":["worry","hope","promise","agree"],"explanation":"find strange and worry 觉得奇怪并担心,语义为负面。"},{"q":"8","answer":"B","options":["price","way","box","road"],"explanation":"a new way of communicating 一种新的交流方式。"},{"q":"9","answer":"C","options":["wrong","empty","certain","late"],"explanation":"one thing is certain 有一点是确定的。"},{"q":"10","answer":"D","options":["up","out","down","back"],"explanation":"no going back 无法回头。"}]'::jsonb, 2, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U3', 'Grandmother''s Old Town', 'My grandmother loves to tell me how much our town has (1)____ over the years. When she was young, she says, it was just a (2)____ village by the river. There were only a few low houses made of (3)____, and most people made a (4)____ from farming. There were no tall buildings, no traffic and no bright lights at (5)____. Then, decade by decade, everything began to (6)____. New roads were laid, factories opened, and skyscrapers slowly (7)____ where the green fields had once been. Today our town is a busy (8)____ full of shops and offices. Grandmother is proud of the change, though she sometimes (9)____ the quiet lanes of her childhood. ''Times always change,'' she tells me with a smile, ''and we must learn to change (10)____ them.''', 131, 2, '[{"q":"1","answer":"A","options":["changed","waited","failed","closed"],"explanation":"how much our town has changed 镇子变了多少。"},{"q":"2","answer":"B","options":["huge","small","modern","busy"],"explanation":"a small village 一个小村庄,与后文 busy city 形成对比。"},{"q":"3","answer":"C","options":["glass","gold","brick","paper"],"explanation":"houses made of brick 砖房。"},{"q":"4","answer":"D","options":["noise","mistake","promise","living"],"explanation":"made a living from farming 靠种田谋生。"},{"q":"5","answer":"A","options":["night","school","work","noon"],"explanation":"bright lights at night 夜晚的灯光。"},{"q":"6","answer":"B","options":["stop","change","sleep","rest"],"explanation":"everything began to change 一切开始改变。"},{"q":"7","answer":"C","options":["sank","fell","rose","slept"],"explanation":"skyscrapers slowly rose 高楼缓缓拔地而起;其余表向下或不通。"},{"q":"8","answer":"D","options":["village","farm","forest","city"],"explanation":"a busy city 繁忙的城市,与 village 对比。"},{"q":"9","answer":"A","options":["misses","hates","sells","breaks"],"explanation":"misses the quiet lanes 怀念安静的小巷。"},{"q":"10","answer":"B","options":["against","with","without","behind"],"explanation":"change with them 随时代一起改变。"}]'::jsonb, 3, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U3', 'Learning to Use Emojis', 'When my friend first sent me a message full of tiny pictures, it took me a (1)____ to understand it. I had no idea what the little symbols meant! Feeling out of (2)____, I decided to learn how to use emojis myself. I soon found that they come in different (3)____, such as faces, animals and food. Adding a smiling face to a message can show your (4)____ far better than words alone. In a way, emojis are like the (5)____ we make with our hands when we speak. Now I use them every day, and they make chatting more (6)____. Of course, I am careful not to (7)____ on them too much. In a school essay, for example, careful written words are still far more (8)____ than pictures. My teacher says emojis are fun, but they should never (9)____ proper writing. I think she is (10)____: there is a time for pictures and a time for words.', 158, 2, '[{"q":"1","answer":"C","options":["box","song","while","road"],"explanation":"took me a while 花了我一会儿。"},{"q":"2","answer":"D","options":["money","breath","luck","touch"],"explanation":"out of touch 跟不上、脱节。"},{"q":"3","answer":"A","options":["categories","prices","mistakes","seasons"],"explanation":"different categories 不同类别。"},{"q":"4","answer":"B","options":["price","feelings","weight","address"],"explanation":"show your feelings 表达你的感受。"},{"q":"5","answer":"C","options":["mistakes","prices","gestures","tickets"],"explanation":"the gestures we make with our hands 我们做的手势。"},{"q":"6","answer":"D","options":["boring","slow","sad","fun"],"explanation":"more fun 更有趣;其余与积极语境矛盾。"},{"q":"7","answer":"A","options":["rely","win","sleep","travel"],"explanation":"rely on them 依赖它们。"},{"q":"8","answer":"B","options":["cheap","useful","loud","round"],"explanation":"far more useful 更有用。"},{"q":"9","answer":"C","options":["help","open","replace","clean"],"explanation":"never replace proper writing 永远取代不了正式书写。"},{"q":"10","answer":"D","options":["wrong","late","busy","right"],"explanation":"she is right 她说得对。"}]'::jsonb, 4, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U3', 'The Old Newspaper Round', 'My uncle still remembers his first job as a boy: (1)____ newspapers before school. Every morning he got up while it was still (2)____ outside. At the printing house, the fresh papers were being (3)____ off the machines, smelling of ink. He would load them onto his old (4)____ and ride from street to street. At each house he pushed a paper through the (5)____ in the door. People waited eagerly for the news, because back then it was the only (6)____ they had. There was no Internet, and a story might be a whole day (7)____ by the time they read it. Today, my uncle says, the news arrives on our phones the (8)____ it happens. He is amazed by how fast everything has (9)____. Still, he is proud of those early mornings, and he believes that hard work never goes out of (10)____.', 145, 2, '[{"q":"1","answer":"A","options":["delivering","eating","drawing","cooking"],"explanation":"delivering newspapers 送报纸。"},{"q":"2","answer":"B","options":["bright","dark","warm","loud"],"explanation":"still dark outside 外面天还黑,呼应早起。"},{"q":"3","answer":"C","options":["eaten","sold","printed","washed"],"explanation":"being printed off the machines 正从机器上印出来。"},{"q":"4","answer":"D","options":["plane","boat","desk","bike"],"explanation":"load them onto his old bike 装到旧自行车上去骑。"},{"q":"5","answer":"A","options":["gap","roof","wall","floor"],"explanation":"through the gap in the door 从门缝塞进去。"},{"q":"6","answer":"B","options":["price","source","noise","game"],"explanation":"the only source they had 他们唯一的(新闻)来源。"},{"q":"7","answer":"C","options":["late","dark","old","busy"],"explanation":"a whole day old 已经过了整整一天(消息变旧)。"},{"q":"8","answer":"D","options":["year","week","hope","moment"],"explanation":"the moment it happens 一发生就(到达)。"},{"q":"9","answer":"A","options":["changed","stopped","failed","slept"],"explanation":"how fast everything has changed 一切变化有多快。"},{"q":"10","answer":"B","options":["money","fashion","sight","time"],"explanation":"goes out of fashion 过时;此处指勤奋永不过时。"}]'::jsonb, 5, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U3', 'New Life in the Old Bookstore', 'The new Rainbow Bookstore is nothing like the quiet shop I remember. Under Jennifer''s (1)____, it has become a lively centre for the whole community. The old wooden board in the corner has been (2)____ by a bright screen, where readers'' comments pop up all day. In one room there is now a small café selling healthy (3)____ food. People come not only to buy books but also to (4)____ events such as poetry recitals and jazz (5)____. On the evening I visited, a book reading was being (6)____ in one corner while soft music played. The shop can no longer (7)____ with huge chain stores on price, so Jennifer has made it special in another (8)____. ''We sell an experience that cannot be (9)____,'' she told me proudly. Looking around at the happy faces, I felt sure that the old store had found a bright new (10)____.', 148, 2, '[{"q":"1","answer":"C","options":["weather","price","leadership","garden"],"explanation":"under Jennifer''s leadership 在珍妮弗的领导下。"},{"q":"2","answer":"D","options":["eaten","sold","washed","replaced"],"explanation":"has been replaced by a screen 被屏幕取代。"},{"q":"3","answer":"A","options":["organic","broken","loud","round"],"explanation":"healthy organic food 健康的有机食品。"},{"q":"4","answer":"B","options":["sell","attend","break","cook"],"explanation":"attend events 参加活动。"},{"q":"5","answer":"C","options":["prices","mistakes","concerts","roads"],"explanation":"jazz concerts 爵士音乐会。"},{"q":"6","answer":"D","options":["eaten","sold","cleaned","delivered"],"explanation":"a book reading was being delivered 朗读会正在进行。"},{"q":"7","answer":"A","options":["compete","sleep","travel","cook"],"explanation":"compete with chain stores on price 在价格上与连锁店竞争。"},{"q":"8","answer":"B","options":["price","way","box","song"],"explanation":"special in another way 以另一种方式与众不同。"},{"q":"9","answer":"C","options":["opened","cleaned","downloaded","sold"],"explanation":"an experience that cannot be downloaded 无法被下载的体验。"},{"q":"10","answer":"D","options":["mistake","price","noise","future"],"explanation":"a bright new future 崭新光明的未来。"}]'::jsonb, 6, 'fltrp');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='elective2' AND unit='U3';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U3 听力·对话 How the News Has Changed', '外研社版选择性必修第二册 U3 · dialogue', 3, 'Lily: My grandpa says the news used to come only once a day. Is that true?
Tom: Yes. In the past, papers were delivered to the door every morning.
Lily: So people waited a whole day for the next story?
Tom: Exactly. And most interviews were done face to face back then.
Lily: How is it different now?
Tom: Now a story can be put online the moment it happens.
Lily: That''s so fast! Do reporters still use paper?
Tom: Hardly ever. They write and edit almost everything on computers.', '莉莉问爷爷说过去新闻一天才来一次是否属实;汤姆说没错,过去报纸每天早上送到门口;人们要等一整天才有下一条;过去采访多是面对面;如今一条新闻一发生就能发到网上;记者几乎不用纸,都在电脑上写稿编辑。', 'uk_female', '[{"q":"How often did the news arrive in the past?","type":"choice","answer":"A","options":["Only once a day.","Every hour.","Several times a minute.","Once a week."]},{"q":"How were papers given to readers in the past?","type":"choice","answer":"B","options":["Sent by email.","Delivered to the door each morning.","Read aloud on the radio.","Picked up at a station."]},{"q":"How were most interviews done back then?","type":"choice","answer":"A","options":["Face to face.","Only by letter.","Through a screen.","By text message."]},{"q":"What can happen to a story now?","type":"choice","answer":"B","options":["It must wait a whole day.","It can be put online the moment it happens.","It is printed by hand.","It is never shared."]},{"q":"What do reporters mainly use to work now?","type":"choice","answer":"C","options":["Pens and paper.","Typewriters.","Computers.","Phone boxes."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U3 听力·短文 From Fishing Town to City', '外研社版选择性必修第二册 U3 · passage', 2, 'Over forty years ago, a small fishing town stood by the southern sea.
People there made a living from fishing, and life was slow and quiet.
Then the town became a special economic zone, and everything began to change.
Roads were laid and tall buildings were put up year after year.
In just a few decades, the town grew into a busy modern city full of energy.', '四十多年前,南方海边有一座小渔镇;那里的人靠打鱼为生,生活缓慢而安静;后来小镇成了经济特区,一切开始改变;道路被铺设,高楼一年年盖起来;短短几十年,小镇就变成了一座充满活力的现代化城市。', 'uk_female', '[{"q":"What was the place like over forty years ago?","type":"choice","answer":"D","options":["A huge capital city.","An empty desert.","A mountain village.","A small fishing town."]},{"q":"How did the people there make a living?","type":"choice","answer":"A","options":["By fishing.","By farming rice.","By selling cars.","By making films."]},{"q":"What change made things move quickly?","type":"choice","answer":"B","options":["A new river appeared.","It became a special economic zone.","The sea dried up.","Everyone moved away."]},{"q":"What was happening year after year?","type":"choice","answer":"C","options":["Houses were being pulled down.","Boats were being sold.","Roads and tall buildings were going up.","Fields were growing larger."]},{"q":"What did the town become in a few decades?","type":"choice","answer":"D","options":["A quiet seaside resort.","A small market town.","A national park.","A busy modern city."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U3 听力·对话 The Bookstore Lives On', '外研社版选择性必修第二册 U3 · dialogue', 3, 'Anna: I can''t believe the old bookstore is still here!
Ben: I know. The whole community worked together to save it.
Anna: And look — there''s a café selling organic food now.
Ben: Yes, and the corner board has been replaced by a big screen.
Anna: People are writing their comments on it.
Ben: They even hold jazz concerts and poetry readings here.
Anna: It feels alive again. Who is in charge now?
Ben: A woman called Jennifer. She grew up in this very neighbourhood.', '安娜不敢相信老书店还在;本说是整个社区一起努力把它救了下来;现在还有卖有机食品的咖啡馆;角落里的木板被大屏幕取代,人们在上面写评论;店里甚至举办爵士音乐会和诗歌朗诵;书店重新焕发生机;现在的负责人是在这个社区长大的珍妮弗。', 'uk_female', '[{"q":"Why is the old bookstore still open?","type":"choice","answer":"A","options":["The community worked together to save it.","A big company bought it.","The government rebuilt it.","It was never going to close."]},{"q":"What does the new café sell?","type":"choice","answer":"B","options":["Second-hand books.","Organic food.","Mobile phones.","Newspapers."]},{"q":"What has replaced the corner board?","type":"choice","answer":"C","options":["A tall bookshelf.","A coffee machine.","A big screen.","A glass window."]},{"q":"What kind of events are held in the store now?","type":"choice","answer":"D","options":["Football matches.","Cooking classes.","Car shows.","Jazz concerts and poetry readings."]},{"q":"Who is in charge of the bookstore now?","type":"choice","answer":"A","options":["Jennifer, who grew up nearby.","Old Casey''s brother.","A famous singer.","A visitor from abroad."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U3 听力·短文 A Short History of Emojis', '外研社版选择性必修第二册 U3 · passage', 2, 'The word emoji comes from Japanese and means picture character.
The first emojis appeared in Japan in 1999, with only about a hundred and seventy designs.
Today there are thousands of them, sorted into groups such as faces, animals and food.
People like emojis because they are quick to use and add feeling to a message.
Whatever we think, these little pictures are clearly here to stay.', 'emoji 一词来自日语,意为“图画文字”;最早的表情符号1999年出现在日本,只有约170种设计;如今已有成千上万种,分成表情、动物、食物等类别;人们喜欢表情符号,因为用起来快、还能给信息添情感;不管我们怎么看,这些小图画显然会一直存在下去。', 'uk_female', '[{"q":"Where does the word ''emoji'' come from?","type":"choice","answer":"B","options":["English.","Japanese.","French.","Korean."]},{"q":"What does the word ''emoji'' mean?","type":"choice","answer":"C","options":["Happy face.","Quick note.","Picture character.","Spoken word."]},{"q":"When did the first emojis appear?","type":"choice","answer":"D","options":["In 2015.","In 1970.","In 2020.","In 1999."]},{"q":"Why do people like emojis, according to the passage?","type":"choice","answer":"A","options":["They are quick and add feeling.","They cost nothing to design.","They are hard to use.","They replace whole books."]},{"q":"What does the speaker say about the future of emojis?","type":"choice","answer":"B","options":["They will soon disappear.","They are here to stay.","They will be banned.","They will become words."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U3 听力·对话 The Vanished Phone Box', '外研社版选择性必修第二册 U3 · dialogue', 3, 'Grandpa: When I was young, we used phone boxes on every street corner.
Mia: Phone boxes? What were they for?
Grandpa: To make calls when you were out. You put in coins and dialled.
Mia: But now everyone just uses a mobile phone.
Grandpa: That''s right. Mobiles are far easier to carry and use.
Mia: So the phone boxes all disappeared?
Grandpa: Almost. People simply stopped needing them.
Mia: Times really do change, Grandpa!', '爷爷说他年轻时街角到处是电话亭;米娅问那是干什么的;爷爷说是在外面打电话用的,投币后拨号;可现在大家都用手机;手机更便于携带和使用;所以电话亭几乎都消失了;因为人们不再需要它们了;米娅感叹时代真的在变。', 'uk_female', '[{"q":"Where were phone boxes found when Grandpa was young?","type":"choice","answer":"C","options":["Only inside homes.","Only at airports.","On every street corner.","Deep in the countryside."]},{"q":"What were phone boxes used for?","type":"choice","answer":"D","options":["Storing letters.","Selling tickets.","Keeping warm.","Making calls when you were out."]},{"q":"How did you pay to use a phone box?","type":"choice","answer":"A","options":["By putting in coins.","By showing a card.","By scanning a code.","It was free."]},{"q":"Why did phone boxes almost disappear?","type":"choice","answer":"B","options":["They were too expensive to build.","People simply stopped needing them.","They were against the law.","Nobody could find them."]},{"q":"What has taken the place of phone boxes?","type":"choice","answer":"C","options":["Public radios.","Street computers.","Mobile phones.","Postboxes."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U3 听力·短文 Moving With the Times', '外研社版选择性必修第二册 U3 · passage', 2, 'Here is a simple thought about change.
The world around us never stays still; tools, jobs and habits are always being made new.
Some people fear change and hold on to the past.
But change can also bring fresh chances and better ways of living.
The best idea is not to fight every change, but to learn from it and move forward with the times.', '关于“变化”有个简单的想法:我们周围的世界从不静止,工具、工作和习惯一直在更新;有些人害怕变化、紧抓过去;但变化也能带来新机会和更好的生活方式;最好的办法不是抗拒每一次变化,而是从中学习、随时代向前。', 'uk_female', '[{"q":"What does the passage say about the world around us?","type":"choice","answer":"D","options":["It is always the same.","It is slowly stopping.","It only changes at night.","It never stays still."]},{"q":"What is always being made new?","type":"choice","answer":"A","options":["Tools, jobs and habits.","Mountains and rivers.","The sun and the moon.","Only old books."]},{"q":"How do some people react to change?","type":"choice","answer":"B","options":["They welcome every bit of it.","They fear it and hold on to the past.","They never notice it.","They write about it."]},{"q":"What can change also bring, according to the speaker?","type":"choice","answer":"C","options":["Only trouble and loss.","More fishing towns.","Fresh chances and better ways of living.","Cheaper phone boxes."]},{"q":"What is the best idea about change?","type":"choice","answer":"D","options":["To fight every single change.","To ignore it completely.","To go back to the past.","To learn from it and move forward."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U3', 'fltrp');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='elective2' AND unit='U3';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (11, 'Writing about a Change(写一篇关于某种变化的短文)', 'Something That Will Disappear', '时代在变,有些事物正悄悄退出我们的生活。请用英语写一篇约100词的短文,内容包括:① 指出一样你认为未来会消失的事物;② 说明它消失的主要原因;③ 给出一两条支持你观点的理由。注意:行文连贯、围绕中心,适当用上过去进行被动语态(如 was being replaced)。', 'Times are changing, and some things are quietly disappearing from our lives. Write a passage of about 100 words including: 1) one thing you think will disappear in the future; 2) the main reason why it will disappear; 3) one or two arguments to support your view. Try to use the past continuous passive (e.g. was being replaced) where it fits naturally.', '["点明会消失的事物(I believe … will soon disappear.)","说明主要原因(The main reason is that …)","给出支持理由(What''s more, … / Besides, …)","围绕中心、衔接自然,适当用过去进行被动"]'::jsonb, 70, 100, 'I believe the printed paper map will soon disappear from our daily lives. The main reason is simple: we no longer need it. Almost everyone now carries a mobile phone that can show the way at the touch of a button. Last year, when I visited a bookshop, I noticed that the shelves of paper maps were already being replaced by other goods. What''s more, a phone map is always up to date, while a paper one quickly becomes old. It is also far lighter to carry. So, like the phone box before it, the paper map is becoming a thing of the past.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["I believe the printed paper map will soon disappear from our daily lives.","The shelves of paper maps were already being replaced by other goods.","A phone map is always up to date, while a paper one quickly becomes old.","Like the phone box before it, the paper map is becoming a thing of the past."]'::jsonb, '[{"wrong":"The maps were replacing by other goods.","correct":"The maps were being replaced by other goods.","note":"过去某刻''正被替换'',主语是承受者,用 was/were being done,而非主动 -ing。"},{"wrong":"We don''t need it no more.","correct":"We no longer need it.","note":"避免双重否定;no longer = 不再。"},{"wrong":"The paper map is becoming a thing of past.","correct":"The paper map is becoming a thing of the past.","note":"固定短语 a thing of the past,需带 the。"}]'::jsonb, '【关于变化的短文结构】
第1句 点题:I believe … will soon disappear.
第2-3句 原因:The main reason is … (可用过去进行被动举例 … was being replaced …)
第4-5句 理由:What''s more, … Besides, …
第6句 收束:…, it is becoming a thing of the past.', 2, 'elective2', 'U3', 'fltrp');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='elective2' AND unit='U3';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (11, 'elective2', 'U3', '{"title":"过去进行被动语态 was/were being done 速查","intro":"过去某一时刻,某事正在被做(动作进行中 + 主语是承受者),用 was/were being + 过去分词。它把''进行体''和''被动''合在一起:强调那一刻动作正在进行、且尚未完成。判断口诀:看主语是不是被动作的对象→是,就用被动;再看动作是''正进行''还是''已完成''→正进行用 being,已完成不用 being。","table":{"headers":["结构 / 用法","例句"],"rows":[["was/were being + 过去分词","The books were being packed.(书正被装箱)"],["过去某刻动作正被进行","When I arrived, the gate was being torn down."],["常见时间标志","when… / at that moment / right then / still / not finished yet"],["常配 by 短语点明施动者","Customers were being attracted by chain stores."]]},"specialRules":[{"rule":"主语是动作承受者才用被动;主语自己施动则用主动 was/were doing","mark":"The gate was being torn down.(门被拆)/ The workers were tearing it down.(工人在拆)"},{"rule":"过程未完用 was/were being done;到某时已完成、只看结果用一般过去被动 was/were done","mark":"were being packed(正在装)/ were already packed(已装完)"},{"rule":"助动词 was/were 须与主语单复数一致","mark":"the book was being… / the books were being…"},{"rule":"否定、疑问时把 not / 主语放在 was/were 之后","mark":"was not being repaired / Was it being repaired?"}],"why":["被动强调''什么被怎样了'',进行体强调''当时正在进行、尚未完成'';两者合起来,就是''过去某刻某事正被做''——既不是已完成的结果(was done),也不是主语自己在做(was doing)。"],"gaokaoPoints":["语法填空/短文改错高频:给动词原形 + 进行时间状语(when I arrived 等)→ 判断 was/were being done。","三组对比要分清:进行被动(过程·being)vs 一般过去被动(结果·无 being);被动(主语被动)vs 主动(主语施动);was vs were(数一致)。"],"examVsReal":[{"exam":"The road was being repaired then.（考试/书面,强调过程被动)","real":"They were repairing the road then.","note":"施动者明确时,口语更爱用主动"},{"exam":"The old shop was being turned into a café.（考试)","real":"They were turning the old shop into a café.","note":"日常口语多用主动;被动多见于正式/书面或不想点明施动者时"}]}'::jsonb, 'fltrp');

COMMIT;

-- ===== 自带校验(publisher='fltrp') =====
SELECT 'vocab' k, count(*) v, 50 expect FROM public.junior_vocab WHERE publisher='fltrp' AND volume='elective2' AND unit='U3'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective2' AND unit='U3')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='fltrp' AND volume='elective2' AND unit='U3'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='fltrp' AND volume='elective2' AND unit='U3'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='elective2' AND unit='U3'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='elective2' AND unit='U3'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='elective2' AND unit='U3' ORDER BY k;
