-- ============================================================
-- 外研社(fltrp) 必修一 U2(Onwards and Upwards)灌库(junior_* 表,publisher='fltrp' volume='elective1' unit='U2' grade=11)。幂等。
-- ★DELETE 全带 publisher='fltrp',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 48 =====
DELETE FROM public.junior_vocab WHERE publisher='fltrp' AND volume='elective1' AND unit='U2';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'debt', 'n.', '/det/', '债务;欠款', 'Before her success, the young writer was deep in debt.', '在成功之前,这位年轻作家负债累累。', 'Onwards and Upwards', 1, 0, 'senior', 'wordlist', 'elective1', 'U2', 'be in debt', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'pace', 'n.', '/peɪs/', '速度;进度;步速', 'She wrote at a steady pace and finished the novel within a year.', '她以稳定的进度写作,一年内完成了这部小说。', 'Onwards and Upwards', 2, 0, 'senior', 'wordlist', 'elective1', 'U2', 'at a steady pace', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'inform', 'v.', '/ɪnˈfɔːm/', '通知;告知', '"We regret to inform you that your work has not been chosen."', '“我们遗憾地通知您,您的作品未被选中。”', 'Onwards and Upwards', 3, 0, 'senior', 'wordlist', 'elective1', 'U2', 'regret to inform', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'dread', 'v.', '/dred/', '畏惧;惧怕', 'Every writer dreads receiving a letter of rejection.', '每位作家都害怕收到拒稿信。', 'Onwards and Upwards', 4, 0, 'senior', 'wordlist', 'elective1', 'U2', 'dread receiving', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'rarely', 'adv.', '/ˈreəli/', '很少;难得', 'Everyone knows that success rarely happens overnight.', '人人都知道成功很少会一蹴而就。', 'Onwards and Upwards', 5, 0, 'senior', 'wordlist', 'elective1', 'U2', 'rarely happen', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'overnight', 'adv.', '/ˌəʊvəˈnaɪt/', '突然;一夜之间', 'Nobody becomes a great writer overnight.', '没有人能一夜之间成为伟大的作家。', 'Onwards and Upwards', 6, 0, 'senior', 'wordlist', 'elective1', 'U2', 'become famous overnight', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'rejection', 'n.', '/rɪˈdʒekʃ(ə)n/', '拒绝;否决', 'She faced twelve rejections before her book was finally printed.', '在书最终付印之前,她遭遇了十二次拒绝。', 'Onwards and Upwards', 7, 0, 'senior', 'wordlist', 'elective1', 'U2', 'face rejection', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'nevertheless', 'adv.', '/ˌnevəðəˈles/', '然而;不过', 'The work was hard; nevertheless, she persevered.', '工作很艰难;然而,她坚持了下来。', 'Onwards and Upwards', 8, 0, 'senior', 'wordlist', 'elective1', 'U2', 'nevertheless, she persevered', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'persevere', 'v.', '/ˌpɜːsɪˈvɪə/', '锲而不舍;坚持不懈', 'If you persevere, you will reach your goal in the end.', '只要坚持不懈,你终将实现目标。', 'Onwards and Upwards', 9, 0, 'senior', 'wordlist', 'elective1', 'U2', 'persevere with sth', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'criticism', 'n.', '/ˈkrɪtɪsɪz(ə)m/', '批评;指责', 'Great writers often face criticism along with rejection.', '伟大的作家常常既遭拒绝又受批评。', 'Onwards and Upwards', 10, 0, 'senior', 'wordlist', 'elective1', 'U2', 'face criticism', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'manuscript', 'n.', '/ˈmænjʊskrɪpt/', '手稿;底稿', 'He carried the manuscript of his novel everywhere he went.', '他走到哪里都带着小说的手稿。', 'Onwards and Upwards', 11, 0, 'senior', 'wordlist', 'elective1', 'U2', 'carry the manuscript', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'best-seller', 'n.', '/ˌbestˈselə/', '畅销书;畅销产品', 'When it was finally published, the book became a best-seller.', '当它最终出版时,这本书成了畅销书。', 'Onwards and Upwards', 12, 0, 'senior', 'wordlist', 'elective1', 'U2', 'become a best-seller', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'classic', 'n.', '/ˈklæsɪk/', '名著;经典作品', 'Today these novels are regarded as classics of world literature.', '如今这些小说被视为世界文学的经典。', 'Onwards and Upwards', 13, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a classic of literature', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'endurance', 'n.', '/ɪnˈdjʊərəns/', '耐力;忍耐力', 'Writing a long book takes great endurance.', '写一本长篇巨著需要极大的耐力。', 'Onwards and Upwards', 14, 0, 'senior', 'wordlist', 'elective1', 'U2', 'great endurance', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'guarantee', 'v.', '/ˌɡærənˈtiː/', '保证;确保', 'Talent alone cannot guarantee success.', '仅有天赋并不能保证成功。', 'Onwards and Upwards', 15, 0, 'senior', 'wordlist', 'elective1', 'U2', 'guarantee success', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'delighted', 'adj.', '/dɪˈlaɪtɪd/', '愉快的;高兴的', '"We are delighted to inform you that you have won."', '“我们高兴地通知您,您获奖了。”', 'Onwards and Upwards', 16, 0, 'senior', 'wordlist', 'elective1', 'U2', 'be delighted to', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'outcome', 'n.', '/ˈaʊtkʌm/', '结果;后果', 'After years of effort, the outcome was finally a success.', '经过多年努力,结果终于是成功的。', 'Onwards and Upwards', 17, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a happy outcome', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'worthwhile', 'adj.', '/ˌwɜːθˈwaɪl/', '值得做的;有意义的', 'Even with its challenges, the experience felt worthwhile.', '尽管有种种挑战,这段经历仍让人觉得值得。', 'Onwards and Upwards', 18, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a worthwhile experience', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'blanket', 'n.', '/ˈblæŋkɪt/', '毯子;毛毯', 'A person who spoils everyone''s fun is called a wet blanket.', '扫大家兴的人被称作“扫兴鬼”。', 'Onwards and Upwards', 19, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a wet blanket', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'enthusiastic', 'adj.', '/ɪnˌθjuːziˈæstɪk/', '热心的;热情的', 'She stayed enthusiastic even when things went wrong.', '即使事情出了差错,她依然保持热情。', 'Onwards and Upwards', 20, 0, 'senior', 'wordlist', 'elective1', 'U2', 'stay enthusiastic', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'contest', 'n.', '/ˈkɒntest/', '比赛;竞赛', 'He felt sad because he had failed in a writing contest.', '他很难过,因为在写作比赛中失利了。', 'Onwards and Upwards', 21, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a writing contest', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'upset', 'adj.', '/ˌʌpˈset/', '心烦的;烦恼的', 'Don''t be too upset; you really did your best.', '别太难过,你确实尽力了。', 'Onwards and Upwards', 22, 0, 'senior', 'wordlist', 'elective1', 'U2', 'be upset about', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'elect', 'v.', '/ɪˈlekt/', '选举;推选', 'She ran for class leader but was not elected.', '她竞选班长,但没有当选。', 'Onwards and Upwards', 23, 0, 'senior', 'wordlist', 'elective1', 'U2', 'be elected', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'blessing', 'n.', '/ˈblesɪŋ/', '幸事;福气', 'A few days of silence can be a real blessing.', '几天的安静有时是一种真正的福气。', 'Onwards and Upwards', 24, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a blessing in disguise', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'appreciative', 'adj.', '/əˈpriːʃətɪv/', '感激的;欣赏的', 'Darkness can make us more appreciative of light.', '黑暗能让我们更懂得珍惜光明。', 'Onwards and Upwards', 25, 0, 'senior', 'wordlist', 'elective1', 'U2', 'appreciative of', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'worthy', 'adj.', '/ˈwɜːði/', '值得的;值得尊敬的', 'Her endless effort made her worthy of the prize.', '她不懈的努力使她配得上这个奖。', 'Onwards and Upwards', 26, 0, 'senior', 'wordlist', 'elective1', 'U2', 'worthy of', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'mere', 'adj.', '/mɪə/', '仅仅的;只不过的', 'Through the mere touch of her fingers she found great beauty.', '仅凭手指的触摸,她就发现了极大的美。', 'Onwards and Upwards', 27, 0, 'senior', 'wordlist', 'elective1', 'U2', 'mere touch', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'gentleness', 'n.', '/ˈdʒentlnɪs/', '温和;和蔼', 'She still remembers the gentleness of her teacher''s words.', '她仍记得老师话语中的温和。', 'Onwards and Upwards', 28, 0, 'senior', 'wordlist', 'elective1', 'U2', 'the gentleness of sb', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'companionship', 'n.', '/kəmˈpænjənʃɪp/', '友谊;陪伴', 'The companionship of good friends makes life worth living.', '好友的陪伴让生活值得过。', 'Onwards and Upwards', 29, 0, 'senior', 'wordlist', 'elective1', 'U2', 'the companionship of friends', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'fingertip', 'n.', '/ˈfɪŋɡəˌtɪp/', '指尖', 'She could read the shape of a face with her fingertips.', '她能用指尖读出一张脸的轮廓。', 'Onwards and Upwards', 30, 0, 'senior', 'wordlist', 'elective1', 'U2', 'with one''s fingertips', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'outline', 'n.', '/ˈaʊtlaɪn/', '外形;轮廓;提纲', 'In the dark he could feel only the outline of the room.', '在黑暗中他只能摸到房间的轮廓。', 'Onwards and Upwards', 31, 0, 'senior', 'wordlist', 'elective1', 'U2', 'the outline of sth', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'probe', 'v.', '/prəʊb/', '探究;调查', 'In the museum she wanted to probe the story of human progress.', '在博物馆里,她想探究人类进步的故事。', 'Onwards and Upwards', 32, 0, 'senior', 'wordlist', 'elective1', 'U2', 'probe into', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'dawn', 'n.', '/dɔːn/', '黎明;破晓', 'Each morning he greeted the dawn with new hope.', '每天清晨,他都以新的希望迎接黎明。', 'Onwards and Upwards', 33, 0, 'senior', 'wordlist', 'elective1', 'U2', 'greet the dawn', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'delight', 'n.', '/dɪˈlaɪt/', '快乐;乐事', 'Discovering new beauty was a real delight to her.', '发现新的美对她来说是一件真正的乐事。', 'Onwards and Upwards', 34, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a real delight', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'revelation', 'n.', '/ˌrevəˈleɪʃ(ə)n/', '展现;揭示', 'Each new day brought fresh revelations of beauty.', '每一个新的日子都带来美的新展现。', 'Onwards and Upwards', 35, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a revelation of beauty', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'amid', 'prep.', '/əˈmɪd/', '在……之中', 'He kept writing amid criticism and rejection.', '在批评与拒绝之中,他坚持写作。', 'Onwards and Upwards', 36, 0, 'senior', 'wordlist', 'elective1', 'U2', 'amid criticism', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'permanent', 'adj.', '/ˈpɜːmənənt/', '长久的;永久的', 'At midnight, permanent darkness would close in again.', '午夜时分,永久的黑暗会再次袭来。', 'Onwards and Upwards', 37, 0, 'senior', 'wordlist', 'elective1', 'U2', 'permanent darkness', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'descend', 'v.', '/dɪˈsend/', '降临;下降', 'Only when night descended did she realise how much she had missed.', '直到夜幕降临,她才意识到自己错过了多少。', 'Onwards and Upwards', 38, 0, 'senior', 'wordlist', 'elective1', 'U2', 'night descends', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'mighty', 'adj.', '/ˈmaɪti/', '强有力的;雄伟的', 'Hear the mighty music of an orchestra while you still can.', '趁还能听,去听管弦乐队雄壮的乐声吧。', 'Onwards and Upwards', 39, 0, 'senior', 'wordlist', 'elective1', 'U2', 'the mighty music', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'orchestra', 'n.', '/ˈɔːkɪstrə/', '管弦乐队', 'The mighty sound of the orchestra filled the whole hall.', '管弦乐队雄壮的乐声充满了整个大厅。', 'Onwards and Upwards', 40, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a full orchestra', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'perfume', 'n.', '/ˈpɜːfjuːm/', '香味;香水', 'Smell the perfume of flowers as if for the last time.', '像是最后一次那样,去闻花的芳香。', 'Onwards and Upwards', 41, 0, 'senior', 'wordlist', 'elective1', 'U2', 'the perfume of flowers', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'relish', 'n.', '/ˈrelɪʃ/', '享受;乐趣', 'She tasted each small meal with great relish.', '她津津有味地品尝每一顿简单的饭菜。', 'Onwards and Upwards', 42, 0, 'senior', 'wordlist', 'elective1', 'U2', 'with relish', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'delightful', 'adj.', '/dɪˈlaɪtf(ə)l/', '令人愉快的;讨人喜欢的', 'Of all the senses, sight may be the most delightful.', '在所有感官中,视觉也许是最令人愉快的。', 'Onwards and Upwards', 43, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a delightful sight', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'literary', 'adj.', '/ˈlɪt(ə)rəri/', '文学的', 'Their novels are now seen as great literary works.', '他们的小说如今被视为伟大的文学作品。', 'Onwards and Upwards', 44, 0, 'senior', 'wordlist', 'elective1', 'U2', 'literary works', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'embarrassed', 'adj.', '/ɪmˈbærəst/', '难堪的;尴尬的', 'He felt embarrassed when he spilled the soup in the dark.', '在黑暗中打翻汤时,他感到很尴尬。', 'Onwards and Upwards', 45, 0, 'senior', 'wordlist', 'elective1', 'U2', 'feel embarrassed', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'beaver', 'n.', '/ˈbiːvə/', '河狸;海狸', 'An eager beaver is someone who loves to work very hard.', '“拼命三郎”指特别热衷于努力工作的人。', 'Onwards and Upwards', 46, 0, 'senior', 'wordlist', 'elective1', 'U2', 'an eager beaver', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'cucumber', 'n.', '/ˈkjuːkʌmbə/', '黄瓜', 'He stayed as cool as a cucumber during the difficult contest.', '在艰难的比赛中,他始终镇定自若。', 'Onwards and Upwards', 47, 0, 'senior', 'wordlist', 'elective1', 'U2', 'cool as a cucumber', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'haunt', 'n.', '/hɔːnt/', '常去的地方', 'The old library was a favourite haunt of the young writer.', '那座旧图书馆是这位年轻作家常去的地方。', 'Onwards and Upwards', 48, 0, 'senior', 'wordlist', 'elective1', 'U2', 'a favourite haunt', NULL, 'fltrp');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2');
DELETE FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('fe1u2.01', '①后接动名词作宾语的动词(enjoy/finish/avoid/mind/practise/suggest/consider 等)', 'A2', 11, '外研社版选择性必修第一册 U2 — enjoy、finish、avoid、mind、practise、suggest、consider、admit、keep、give up、miss、imagine、deny、put off、can''t help、feel like、be busy 等后面只能接 doing 作宾语,不能接 to do。', 1, 'elective1', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('fe1u2.02', '②后接不定式作宾语的动词(decide/hope/agree/promise/manage/offer/refuse 等)', 'A2', 11, '外研社版选择性必修第一册 U2 — decide、hope、agree、promise、manage、offer、refuse、want、learn、fail、choose、plan、expect、wish、afford、pretend、prepare、seem、happen、aim 等后面只能接 to do 作宾语,不能接 doing。', 2, 'elective1', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('fe1u2.03', '③接 doing 与 to do 意义不同的动词(remember/forget/regret/stop/try/mean)', 'A2', 11, '外研社版选择性必修第一册 U2 — remember/forget/regret + to do 指''去做(未做)''、+ doing 指''做过(已做)'';stop to do ''停下来去做''、stop doing ''停止做'';try to do ''设法''、try doing ''试着'';mean to do ''打算''、mean doing ''意味着''。靠句子语境判断。', 3, 'elective1', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'Even now, Liu Wei still enjoys ____ music to his many fans.', 'playing', 'to play', 'play', 'plays', 'A', 'enjoy 后接动名词作宾语 → playing。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'She did not rest until she had finished ____ the whole novel.', 'to read', 'reading', 'read', 'reads', 'B', 'finish 后只能接动名词 → reading。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'Good writers cannot always avoid ____ mistakes in their early drafts.', 'to make', 'make', 'making', 'makes', 'C', 'avoid 后接动名词 → making。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'Would you mind ____ a little longer for the results of the contest?', 'to wait', 'wait', 'waits', 'waiting', 'D', 'mind 后接动名词 → waiting。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'He practises ____ English aloud every single morning.', 'speaking', 'to speak', 'speak', 'speaks', 'A', 'practise 后接动名词 → speaking。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'My teacher suggested ____ a different ending for my story.', 'to try', 'trying', 'try', 'tries', 'B', 'suggest 后接动名词 → trying。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'After school, she seriously considered ____ literature at university.', 'to study', 'study', 'studying', 'studies', 'C', 'consider 后接动名词 → studying。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'He admitted ____ very nervous before the writing contest.', 'to feel', 'feel', 'feels', 'feeling', 'D', 'admit 后接动名词 → feeling。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'She kept ____ until every single publisher had answered her.', 'trying', 'to try', 'try', 'tries', 'A', 'keep 后接动名词 → trying。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'Even during the war, he never gave up ____ on the novel.', 'to work', 'working', 'work', 'works', 'B', 'give up 后接动名词 → working。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'She missed ____ her old writing group after she moved away.', 'to meet', 'meet', 'meeting', 'meets', 'C', 'miss 后接动名词 → meeting。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'Few people imagine ____ famous after so many rejections.', 'to become', 'become', 'becomes', 'becoming', 'D', 'imagine 后接动名词 → becoming。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'The young poet firmly denied ____ anyone else''s work.', 'copying', 'to copy', 'copy', 'copies', 'A', 'deny 后接动名词 → copying。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'Don''t put off ____ your story to the magazine any longer.', 'to send', 'sending', 'send', 'sends', 'B', 'put off(推迟)后接动名词 → sending。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'We can''t help ____ writers who never give in to failure.', 'to admire', 'admire', 'admiring', 'admires', 'C', 'can''t help(禁不住)后接动名词 → admiring。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'Sometimes she felt like ____ up, but in the end she carried on.', 'to give', 'give', 'gives', 'giving', 'D', 'feel like 后接动名词 → giving。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'He was busy ____ for the speech contest the whole week.', 'preparing', 'to prepare', 'prepare', 'prepares', 'A', 'be busy 后接动名词 → preparing。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'The blind writer enjoyed ____ to the songs of the birds.', 'to listen', 'listening', 'listen', 'listens', 'B', 'enjoy 后接动名词 → listening。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'She practises ____ a little every day to improve her calligraphy.', 'to draw', 'draw', 'drawing', 'draws', 'C', 'practise 后接动名词 → drawing。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.01'), 'After ____ the last page, the tired editor finally smiled.', 'to correct', 'correct', 'corrects', 'correcting', 'D', '介词 after 后接动名词 → correcting。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'After many rejections, she decided ____ writing in her own way.', 'to keep', 'keeping', 'keep', 'keeps', 'A', 'decide 后接不定式作宾语 → to keep。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'The young author hoped ____ a friendly publisher one day.', 'finding', 'to find', 'find', 'finds', 'B', 'hope 后接不定式 → to find。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'At last one publisher agreed ____ five hundred copies of her book.', 'printing', 'print', 'to print', 'prints', 'C', 'agree 后接不定式 → to print。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'He promised ____ the novel even while serving in the army.', 'finishing', 'finish', 'finishes', 'to finish', 'D', 'promise 后接不定式 → to finish。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'She finally managed ____ her first book at the age of thirty.', 'to publish', 'publishing', 'publish', 'publishes', 'A', 'manage 后接不定式 → to publish。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'A kind editor offered ____ her with the most difficult chapter.', 'helping', 'to help', 'help', 'helps', 'B', 'offer 后接不定式 → to help。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'Despite all the criticism, Salinger refused ____ up on his book.', 'giving', 'give', 'to give', 'gives', 'C', 'refuse 后接不定式 → to give。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'After his accident, Liu Wei still wanted ____ life to the full.', 'living', 'live', 'lives', 'to live', 'D', 'want 后接不定式 → to live。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'He learned ____ his feet for everyday activities such as eating.', 'to use', 'using', 'use', 'uses', 'A', 'learn 后接不定式 → to use。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'On the fourth day he was so tired that he failed ____ out of bed.', 'getting', 'to get', 'get', 'gets', 'B', 'fail 后接不定式 → to get。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'Many students choose ____ a summer camp to build their character.', 'taking', 'take', 'to take', 'takes', 'C', 'choose 后接不定式 → to take。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'As a child, she already planned ____ a story about a young wizard.', 'writing', 'write', 'writes', 'to write', 'D', 'plan 后接不定式 → to write。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'No one expected the shy boy ____ such a confident speaker.', 'to become', 'becoming', 'become', 'becomes', 'A', 'expect sb 后接不定式 → to become。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'The three sisters only wished ____ their words in print.', 'seeing', 'to see', 'see', 'sees', 'B', 'wish 后接不定式 → to see。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'She could not afford ____ her own poetry published.', 'having', 'have', 'to have', 'has', 'C', 'afford 后接不定式 → to have。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'He pretended ____ calm, though his heart was beating fast.', 'staying', 'stay', 'stays', 'to stay', 'D', 'pretend 后接不定式 → to stay。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'The whole team prepared ____ in the school debate that afternoon.', 'to compete', 'competing', 'compete', 'competes', 'A', 'prepare 后接不定式 → to compete。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'After years of effort, her hard work seemed ____ off at last.', 'paying', 'to pay', 'pay', 'pays', 'B', 'seem 后接不定式 → to pay。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'I happened ____ her lost manuscript in an old wooden desk.', 'finding', 'find', 'to find', 'finds', 'C', 'happen 后接不定式 → to find。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.02'), 'Many campers aim ____ stronger and braver day by day.', 'growing', 'grow', 'grows', 'to grow', 'D', 'aim 后接不定式 → to grow。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'Remember ____ the library books tomorrow; don''t leave them at home.', 'to return', 'returning', 'return', 'returns', 'A', 'remember to do 指''记得去做(未做)'';句中是明天该做的事 → to return。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'I still clearly remember ____ my very first rejection letter years ago.', 'to receive', 'receiving', 'receive', 'receives', 'B', 'remember doing 指''记得做过'';是多年前发生的事 → receiving。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'She fondly remembers ____ the prize on that happy spring day.', 'to win', 'win', 'winning', 'wins', 'C', 'remember doing 指''记得做过'';那天获奖已发生 → winning。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'Don''t forget ____ your dad tonight; he is waiting for your news.', 'phoning', 'phone', 'phones', 'to phone', 'D', 'forget to do 指''忘记去做(还没做)'';今晚要打的电话 → to phone。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'I will never forget ____ on that big stage for the very first time.', 'standing', 'to stand', 'stand', 'stands', 'A', 'forget doing 指''忘不了做过的事'';第一次登台已发生 → standing。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'He forgot ____ the window, so the cold wind blew in all night.', 'closing', 'to close', 'close', 'closes', 'B', 'forget to do 指''忘记去做'';他没关窗 → to close。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), '"We regret ____ you that your story has not been chosen this time."', 'informing', 'inform', 'to inform', 'informs', 'C', 'regret to do 指''遗憾地(现在)去做'';常用于通知 → to inform。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'She has never regretted ____ so many weekends to her writing.', 'to give', 'give', 'gives', 'giving', 'D', 'regret doing 指''后悔做过'';是过去付出的事 → giving。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'He later regretted ____ so rudely to the kind old editor.', 'speaking', 'to speak', 'speak', 'speaks', 'A', 'regret doing 指''后悔做过'';无礼说话已发生 → speaking。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'On the fourth day he was so tired that he stopped ____ for a rest.', 'resting', 'to rest', 'rest', 'rests', 'B', 'stop to do 指''停下来去做另一件事'';停下来休息 → to rest。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'When his health failed, Liu Wei had to stop ____ in competitions.', 'to swim', 'swim', 'swimming', 'swims', 'C', 'stop doing 指''停止做某事'';不再参加游泳 → swimming。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'Even when only two copies sold, the sisters never stopped ____.', 'to believe', 'believe', 'believes', 'believing', 'D', 'stop doing 指''停止做某事'';她们不曾停止相信 → believing。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'If the first plan does not work, try ____ a completely new ending.', 'writing', 'to write', 'write', 'writes', 'A', 'try doing 指''试着做(看效果)'';换种写法试试 → writing。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'She tried hard ____ the whole race, but it was simply too long.', 'finishing', 'to finish', 'finish', 'finishes', 'B', 'try to do 指''努力去做'';她竭力想跑完 → to finish。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'Whenever you feel low, try ____ on the bright side of things.', 'to look', 'look', 'looking', 'looks', 'C', 'try doing 指''试着做(一种方法)'';试着往好处看 → looking。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'Real success means ____ on even after many painful failures.', 'to carry', 'carry', 'carries', 'carrying', 'D', 'mean doing 指''意味着'';成功意味着坚持下去 → carrying。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'He meant ____ his parents proud, so he kept practising every day.', 'to make', 'making', 'make', 'makes', 'A', 'mean to do 指''打算'';他打算让父母骄傲 → to make。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'I''m sorry — I didn''t mean ____ you; I only wanted to help.', 'upsetting', 'to upset', 'upset', 'upsets', 'B', 'mean to do 指''有意(打算)'';我并非有意让你难过 → to upset。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'Please remember ____ off the lights before the show finally ends.', 'turning', 'turn', 'to turn', 'turns', 'C', 'remember to do 指''记得去做'';演出结束前要关灯 → to turn。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' AND code='fe1u2.03'), 'She stopped ____ to the music and picked up her pen to write.', 'to listen', 'listen', 'listens', 'listening', 'D', 'stop doing 指''停止做某事'';她不再听音乐 → listening。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='fltrp' AND volume='elective1' AND unit='U2';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Twelve Times Rejected', '"We regret to inform you..." These are the words that every writer dreads receiving. When J.K. Rowling got her first rejection letter, she did not throw it away. Instead, she decided that it now gave her something in common with her favourite writers, and she stuck it on her kitchen wall. For years she had been living on very little money, spending all her time writing. When she finished her first book, publishers told her it was too long and that children would not be interested in it. Nevertheless, she persevered. She was not going to give up until every single publisher had turned her down. After twelve rejections, one publisher at last agreed to print just five hundred copies. As we all know, the story of the young wizard went on to become a global success, selling hundreds of millions of books around the world. Her endless effort had finally paid off.', '记叙·罗琳的坚持', 153, '[{"q":"What did Rowling do with her first rejection letter?","answer":"A","options":["She kept it and put it on her wall.","She threw it straight into the bin.","She sent it back to the publisher.","She tore it into small pieces."],"explanation":"原文 ''stuck it on her kitchen wall'' 的转述;其余动作文中未发生。"},{"q":"Why did the early publishers turn her book down?","answer":"B","options":["They said it was far too short.","They thought it was too long for children.","They could not read her handwriting.","They had no money to print books."],"explanation":"原文 ''too long and that children would not be interested'' 的转述。"},{"q":"What finally happened to the book about the young wizard?","answer":"A","options":["It became a huge success worldwide.","It was never printed at all.","It sold only five hundred copies.","It was rewritten by another author."],"explanation":"末段 ''became a global success, selling hundreds of millions'' 的转述。"}]'::jsonb, '[{"word":"rejection","cn":"拒绝"},{"word":"persevere","cn":"坚持不懈"},{"word":"dread","cn":"畏惧"}]'::jsonb, 2, 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'The Soldier with a Novel', 'Many writers of great works have had to face criticism as well as rejection. J.D. Salinger began writing short stories while he was still in high school, but later he struggled to get his work published. One editor told him that they did not feel they knew the central character well enough. Several publishers turned the book down, yet Salinger refused to give up. Even when he was serving in the army during the Second World War, he carried six chapters of his unfinished novel with him. Amid the noise and danger of war, he kept working on the story whenever he could. He was determined to finish it, no matter how long it took. When the book was finally published, it became an immediate best-seller and went on to sell millions and millions of copies. His patience and endurance had turned years of hard struggle into a lasting success.', '记叙·塞林格的坚持', 150, '[{"q":"When did Salinger start writing short stories?","answer":"B","options":["Only after he left the army.","During his time in high school.","After his first book was printed.","When he became a famous editor."],"explanation":"原文 ''began writing short stories while he was still in high school'' 的转述。"},{"q":"What did Salinger do with his novel during the war?","answer":"C","options":["He stopped writing completely.","He sold the chapters to a publisher.","He kept working on it whenever he could.","He left the chapters safely at home."],"explanation":"原文 ''kept working on the story whenever he could''(中段)。"},{"q":"How did the book sell once it was published?","answer":"D","options":["It sold very few copies.","It was banned by the army.","It was forgotten within a year.","It quickly became a best-seller."],"explanation":"末段 ''became an immediate best-seller'' 的转述。"}]'::jsonb, '[{"word":"criticism","cn":"批评"},{"word":"manuscript","cn":"手稿"},{"word":"endurance","cn":"耐力"}]'::jsonb, 2, 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Three Sisters Who Never Gave In', 'Perhaps the greatest prize for perseverance should go to three sisters from a small English village who dreamt of seeing their words in print. Sadly, theirs was a time when women were not encouraged to become writers. One important poet of the day even wrote to one of them, saying that writing could not and should not be the business of a woman''s life. Nevertheless, the sisters did not stop trying. Their answer was to publish a book of poems under men''s names so that readers would take them seriously. Even when that book sold only two copies, the sisters still refused to give up. They turned instead to writing novels. Today their stories are regarded as classics of world literature, loved by readers everywhere. Their lives show that talent alone is never enough; it is patience and a refusal to give in that finally open the door to success.', '记叙·勃朗特三姐妹', 150, '[{"q":"Why did the sisters publish their poems under men''s names?","answer":"A","options":["To win readers'' respect for their work.","Because they had forgotten their own names.","Because the publisher chose the names.","So that they could win a money prize."],"explanation":"原文 ''so that readers would take them seriously'' 的转述(意为想获得读者认真对待)。"},{"q":"How well did the sisters'' book of poems sell?","answer":"B","options":["It became a best-seller.","It sold only two copies.","It sold millions of copies.","It was never printed."],"explanation":"原文 ''that book sold only two copies''(中段)。"},{"q":"What does the writer say finally leads to success?","answer":"C","options":["Natural talent on its own.","A large amount of money.","Patience and never giving in.","Being born into a rich family."],"explanation":"末句 ''it is patience and a refusal to give in'' 的转述。"}]'::jsonb, '[{"word":"classic","cn":"名著"},{"word":"literary","cn":"文学的"},{"word":"persevere","cn":"坚持"}]'::jsonb, 2, 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Playing the Piano with His Toes', 'At the age of ten, Liu Wei lost both of his arms in a terrible accident. Many people might have given up hope, but Liu Wei wanted to live life to the full. He learned to use his feet for everyday activities, such as eating and brushing his teeth. He also took up swimming, and he won two gold medals at the National Games for People with Disabilities. Later, health problems forced him to stop swimming, but he refused to feel sorry for himself. Instead, he decided to learn how to play the piano with his toes. It was extremely difficult, and progress was slow. Yet he kept practising, hour after hour, until at last he reached his goal. In 2010, he won a famous national talent show and became known across the whole country. Today Liu Wei still enjoys playing music, and his positive attitude is an inspiration to us all.', '记叙·刘伟', 152, '[{"q":"What did Liu Wei learn to do with his feet?","answer":"D","options":["Only how to drive a car.","Nothing at all for years.","Just how to write letters.","Everyday tasks like eating."],"explanation":"原文 ''use his feet for everyday activities, such as eating''(中段)的转述。"},{"q":"Why did Liu Wei stop swimming?","answer":"A","options":["Because of some health problems.","He lost interest in the sport.","He was not good at it.","His coach told him to stop."],"explanation":"原文 ''health problems forced him to stop swimming'' 的转述。"},{"q":"What does the writer say about Liu Wei''s attitude?","answer":"B","options":["It is rather sad and hopeless.","It inspires everyone around him.","It changes from day to day.","It matters less than his talent."],"explanation":"末句 ''his positive attitude is an inspiration to us all'' 的转述。"}]'::jsonb, '[{"word":"attitude","cn":"态度"},{"word":"disability","cn":"残疾"}]'::jsonb, 2, 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'If I Could See for Three Days', 'The writer Helen Keller, who was both blind and deaf, once imagined what she would most like to see if she were given the use of her eyes for just three days. On the first day, she said, she would want to look at the faces of the people whose kindness and companionship had made her life worth living. She could only know these faces through the mere touch of her fingertips. On the second day, she would rise at dawn to watch the world wake up, and then go to the museums to follow the long story of human progress. In the afternoon she would take a long walk in the woods. She gave one simple piece of advice to those who can see: use your eyes as if tomorrow you would lose them. Smell the perfume of flowers and hear the mighty music of an orchestra as if you would never enjoy them again.', '议论·海伦·凯勒的愿望', 156, '[{"q":"What would Helen Keller most want to see on the first day?","answer":"C","options":["A large and busy city.","The inside of a museum.","The faces of her loved ones.","A famous orchestra playing."],"explanation":"原文 ''look at the faces of the people whose kindness and companionship'' 的转述。"},{"q":"How did Helen Keller normally come to know people''s faces?","answer":"D","options":["By hearing their voices.","By reading about them.","Through old photographs.","Through the touch of her fingertips."],"explanation":"原文 ''only know these faces through the mere touch of her fingertips'' 的转述。"},{"q":"What advice does Helen Keller give to people who can see?","answer":"A","options":["Use their eyes as if they might lose them.","Spend more time indoors.","Stop using their other senses.","Visit a museum every single day."],"explanation":"末段 ''use your eyes as if tomorrow you would lose them'' 的转述。"}]'::jsonb, '[{"word":"companionship","cn":"陪伴"},{"word":"fingertip","cn":"指尖"},{"word":"dawn","cn":"黎明"}]'::jsonb, 2, 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Looking on the Bright Side', 'Life is made up of ups and downs, so it is not always easy to keep a good and enthusiastic attitude. Nevertheless, looking on the bright side is one of the best things we can do, both for ourselves and for the people around us. A positive attitude can spread from one person to another, just as a cold can. When someone you know is feeling low and upset, you do not need to solve all their problems. Often it is enough simply to lend them an ear and to try to cheer them up with a few kind words. Remember that your mood is catching, so make sure you pass on a good one. A person who always finds fault and spoils the fun is like a wet blanket, while an enthusiastic, hard-working friend can lift the whole group. Choosing to stay hopeful, even after failure, is a small daily act of courage.', '议论·积极心态', 154, '[{"q":"Why is keeping a good attitude not always easy?","answer":"B","options":["Because friends are hard to find.","Because life has both ups and downs.","Because money is always short.","Because attitudes never change."],"explanation":"原文 ''Life is made up of ups and downs'' 的转述。"},{"q":"What does the writer suggest doing for an upset friend?","answer":"C","options":["Solving every one of their problems.","Leaving them completely alone.","Listening and cheering them up.","Telling them to stop complaining."],"explanation":"原文 ''lend them an ear and to try to cheer them up''(中段)的转述。"},{"q":"What does the writer compare a positive attitude to?","answer":"D","options":["A heavy wet blanket.","A long and tiring walk.","A difficult maths problem.","Something catching, like a cold."],"explanation":"原文 ''can spread… just as a cold can / your mood is catching'' 的转述。"}]'::jsonb, '[{"word":"enthusiastic","cn":"热情的"},{"word":"upset","cn":"心烦的"},{"word":"blanket","cn":"毯子(wet blanket=扫兴的人)"}]'::jsonb, 2, 'elective1', 'U2', 'fltrp');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='fltrp' AND volume='elective1' AND unit='U2';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective1', 'U2', 'Anna''s First Rejection', 'When Anna finished her first short story, she proudly sent it to a magazine. A week later, a letter arrived that began, "We regret to (1)____ you..." Like every young writer, she had (2)____ those very words. For a moment she felt like (3)____ up writing altogether. But then she remembered that many famous authors had (4)____ the same kind of rejection before they became successful. So, instead of throwing the letter away, she decided to (5)____ it on her wall as a reminder. Success, she told herself, (6)____ happens overnight. She kept (7)____ a little every day, and slowly her stories grew better. Two years later, a (8)____ finally agreed to print one of them. Anna learned that one letter could not decide her future, and that (9)____ is the real key to success. Today she still (10)____ writing stories for young readers.', 144, 2, '[{"q":"1","answer":"A","options":["inform","enjoy","forget","carve"],"explanation":"regret to inform 遗憾地通知。"},{"q":"2","answer":"B","options":["sold","dreaded","printed","watered"],"explanation":"dread 畏惧;她早就害怕这些字眼。"},{"q":"3","answer":"C","options":["winning","buying","giving","growing"],"explanation":"feel like giving up 想放弃;feel like 后接动名词。"},{"q":"4","answer":"D","options":["lost","sold","eaten","faced"],"explanation":"face rejection 面对拒绝。"},{"q":"5","answer":"A","options":["stick","throw","burn","drop"],"explanation":"stick it on her wall 把它贴在墙上。"},{"q":"6","answer":"B","options":["always","rarely","loudly","quickly"],"explanation":"success rarely happens overnight 成功很少一蹴而就。"},{"q":"7","answer":"C","options":["stopping","losing","writing","selling"],"explanation":"keep writing 坚持写;keep 后接动名词。"},{"q":"8","answer":"D","options":["garden","weather","machine","publisher"],"explanation":"a publisher agreed to print 出版商同意付印。"},{"q":"9","answer":"A","options":["perseverance","money","luck","beauty"],"explanation":"perseverance is the key 坚持是关键。"},{"q":"10","answer":"B","options":["forgets","enjoys","hides","stops"],"explanation":"enjoys writing 喜欢写;enjoy 后接动名词。"}]'::jsonb, 1, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective1', 'U2', 'The Runner Who Wouldn''t Stop', 'On the morning of the race, Daniel felt both nervous and (1)____. He had trained hard for months and did not want to give (2)____ now. The route was long, and after the first few kilometres his legs began to (3)____. Many runners around him slowed down, but Daniel kept (4)____ at a steady pace. Halfway through, he wanted to stop and (5)____, yet he reminded himself why he had started. "A medal is never (6)____ overnight," he thought. As the finish line came into (7)____, his heart filled with hope. He did not win first place, but he managed (8)____ the whole race, and that was a real success for him. His friends were (9)____ to inform him that he had beaten his own record. Daniel realised that the true (10)____ of the day was not a prize, but the courage never to give in.', 146, 2, '[{"q":"1","answer":"C","options":["asleep","absent","excited","empty"],"explanation":"nervous and excited 紧张又兴奋。"},{"q":"2","answer":"D","options":["off","out","in","up"],"explanation":"give up 放弃。"},{"q":"3","answer":"A","options":["hurt","sing","grow","smile"],"explanation":"his legs began to hurt 双腿开始疼。"},{"q":"4","answer":"B","options":["crying","running","sleeping","leaving"],"explanation":"kept running 一直跑;keep 后接动名词。"},{"q":"5","answer":"C","options":["win","sell","rest","print"],"explanation":"stop and rest 停下来休息。"},{"q":"6","answer":"D","options":["broken","lost","carried","won"],"explanation":"a medal is never won overnight 奖牌绝非一夜得来。"},{"q":"7","answer":"A","options":["view","debt","noise","order"],"explanation":"come into view 进入视野。"},{"q":"8","answer":"B","options":["finishing","to finish","to win","winning"],"explanation":"manage to finish 设法跑完;manage 后接不定式。"},{"q":"9","answer":"C","options":["afraid","sorry","delighted","late"],"explanation":"delighted to inform 高兴地告知。"},{"q":"10","answer":"D","options":["price","machine","garden","outcome"],"explanation":"the true outcome 真正的收获/结果。"}]'::jsonb, 2, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective1', 'U2', 'Jamie at the Sports Camp', 'Last summer, Jamie joined a sports camp, hoping (1)____ his character and make new friends. The camp was fun, but it was not (2)____ its challenges. Each day began with a five-kilometre run at six in the morning. At first Jamie could not (3)____ the whole route, and on the fourth day he was so tired that he did not even want (4)____ out of bed. He felt homesick and almost (5)____ his dad to take him home. But he did not give (6)____. Slowly, things got better. He learned to (7)____ each early morning instead of dreading it. By the end of the camp, Jamie felt much (8)____ and more confident than before. He had also made several good friends. Even though being a camper had its (9)____, Jamie felt the whole experience was truly (10)____. He came home tired but proud of what he had done.', 148, 2, '[{"q":"1","answer":"A","options":["to build","building","to lose","losing"],"explanation":"hope to build 希望塑造;hope 后接不定式。"},{"q":"2","answer":"B","options":["into","without","before","across"],"explanation":"not without its challenges 不无挑战。"},{"q":"3","answer":"C","options":["sell","hide","finish","throw"],"explanation":"could not finish the route 跑不完全程。"},{"q":"4","answer":"D","options":["getting","to sell","selling","to get"],"explanation":"want to get out of bed 想起床;want 后接不定式。"},{"q":"5","answer":"A","options":["phoned","sold","carved","watered"],"explanation":"almost phoned his dad 差点打电话给爸爸。"},{"q":"6","answer":"B","options":["off","up","in","out"],"explanation":"give up 放弃。"},{"q":"7","answer":"C","options":["fear","miss","enjoy","spoil"],"explanation":"learned to enjoy each morning 学会享受每个清晨。"},{"q":"8","answer":"D","options":["weaker","smaller","slower","stronger"],"explanation":"felt much stronger 觉得强壮多了。"},{"q":"9","answer":"A","options":["challenges","prices","gardens","machines"],"explanation":"had its challenges 有它的挑战。"},{"q":"10","answer":"B","options":["useless","worthwhile","boring","empty"],"explanation":"truly worthwhile 真正值得。"}]'::jsonb, 3, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective1', 'U2', 'Dinner in the Dark', 'Last week I went to a "dark restaurant", where guests eat in complete darkness and are (1)____ by blind waiters. My friend and I wanted to understand what it is like (2)____ blind, and we thought eating would be the hardest part. It was a difficult (3)____. Because we could not see anything, we kept (4)____ over our glasses and dropping our food. My sense of smell suddenly became more (5)____, and I ate much more slowly, trying to (6)____ what was on my plate. After failing (7)____ up any food with a fork, I decided to use my hands instead. Even then, I (8)____ most of the soup on my shirt. I felt rather (9)____, although of course no one could see me. When I finally left, I was still hungry, but I was much more (10)____ of the daily challenges that blind people bravely face.', 147, 2, '[{"q":"1","answer":"C","options":["sold","printed","served","carved"],"explanation":"served by blind waiters 由盲人服务员招待。"},{"q":"2","answer":"D","options":["being","to do","doing","to be"],"explanation":"what it is like to be blind 失明是什么感觉;固定句式用不定式。"},{"q":"3","answer":"A","options":["meal","song","price","garden"],"explanation":"a difficult meal 一顿艰难的饭。"},{"q":"4","answer":"B","options":["singing","knocking","winning","printing"],"explanation":"kept knocking over our glasses 不断碰倒杯子;keep 后接动名词。"},{"q":"5","answer":"C","options":["empty","silent","sensitive","absent"],"explanation":"became more sensitive 变得更灵敏。"},{"q":"6","answer":"D","options":["forget","throw","lose","guess"],"explanation":"trying to guess 试着猜。"},{"q":"7","answer":"A","options":["to pick","picking","to sell","selling"],"explanation":"fail to pick up 没能夹起;fail 后接不定式。"},{"q":"8","answer":"B","options":["sold","spilled","saved","hid"],"explanation":"spilled most of the soup 把汤洒了大半。"},{"q":"9","answer":"C","options":["proud","delighted","embarrassed","calm"],"explanation":"felt rather embarrassed 感到相当尴尬。"},{"q":"10","answer":"D","options":["afraid","tired","bored","aware"],"explanation":"more aware of the challenges 更了解那些挑战。"}]'::jsonb, 4, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective1', 'U2', 'Turning Over a New Leaf', 'At the start of the new term, Sam decided to turn over a new (1)____ and become a better student. In the past, he had often (2)____ his feet and put off doing his homework until the last minute. He also used to be a wet (3)____, spoiling the fun whenever his friends were excited about a project. This year, he promised (4)____ harder and to support the people around him. He started (5)____ a short plan every evening, so that he would no longer fall behind. Soon his classmates noticed the change and called him an eager (6)____, because he was always ready to help. Of course, change is never (7)____; there were days when Sam felt like giving (8)____. But he reminded himself that real success (9)____ trying again after each failure. Step by step, he became more (10)____ and confident, and his whole class felt happier for it.', 151, 2, '[{"q":"1","answer":"A","options":["leaf","price","noise","garden"],"explanation":"turn over a new leaf 翻开新的一页(改过自新)。"},{"q":"2","answer":"B","options":["sold","dragged","printed","watered"],"explanation":"drag one''s feet 拖拖拉拉。"},{"q":"3","answer":"C","options":["orchestra","manuscript","blanket","contest"],"explanation":"a wet blanket 扫兴的人。"},{"q":"4","answer":"D","options":["working","to lose","losing","to work"],"explanation":"promise to work 答应努力;promise 后接不定式。"},{"q":"5","answer":"A","options":["making","forgetting","hiding","selling"],"explanation":"start making a plan 开始制定计划;此处用动名词亦可,语境为养成习惯。"},{"q":"6","answer":"B","options":["price","beaver","noise","garden"],"explanation":"an eager beaver 拼命三郎。"},{"q":"7","answer":"C","options":["loud","empty","easy","late"],"explanation":"change is never easy 改变从不容易。"},{"q":"8","answer":"D","options":["off","in","out","up"],"explanation":"give up 放弃。"},{"q":"9","answer":"A","options":["means","forgets","sells","hides"],"explanation":"success means trying again 成功意味着再试;mean doing 意味着。"},{"q":"10","answer":"B","options":["absent","enthusiastic","asleep","silent"],"explanation":"more enthusiastic 更有热情。"}]'::jsonb, 5, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective1', 'U2', 'After the Contest', 'When Dawei came out of the speech (1)____, his face looked sad and (2)____. He had hoped (3)____ first place, but the judges had chosen someone else. His friend Jack noticed at once that something was (4)____, so he asked Dawei what had happened. "I did my best, but I still didn''t (5)____," Dawei said quietly. Jack reminded him that one result could not (6)____ his whole future. "Try (7)____ on the bright side," Jack said gently. "You spoke far better than last year." Slowly, Dawei began to (8)____ that he had actually enjoyed the experience and learned a lot. He had met new friends and felt more (9)____ on stage than ever before. By the time they walked home, Dawei was smiling again. He had learned that failure is only painful if you stop (10)____ in yourself.', 138, 2, '[{"q":"1","answer":"C","options":["garden","machine","contest","price"],"explanation":"the speech contest 演讲比赛。"},{"q":"2","answer":"D","options":["happy","proud","calm","upset"],"explanation":"sad and upset 难过又心烦。"},{"q":"3","answer":"A","options":["to win","winning","to lose","losing"],"explanation":"hope to win 希望获胜;hope 后接不定式。"},{"q":"4","answer":"B","options":["right","wrong","easy","ready"],"explanation":"something was wrong 有些不对劲。"},{"q":"5","answer":"C","options":["sleep","leave","win","sell"],"explanation":"I still didn''t win 我还是没赢。"},{"q":"6","answer":"D","options":["forget","carve","water","decide"],"explanation":"could not decide his future 决定不了他的未来。"},{"q":"7","answer":"A","options":["looking","to look","to sell","selling"],"explanation":"try looking on the bright side 试着往好处看;try doing 试着。"},{"q":"8","answer":"B","options":["forget","realise","lose","deny"],"explanation":"began to realise 开始意识到。"},{"q":"9","answer":"C","options":["afraid","absent","confident","asleep"],"explanation":"more confident on stage 在台上更自信。"},{"q":"10","answer":"D","options":["winning","selling","hiding","believing"],"explanation":"stop believing in yourself 停止相信自己;stop doing 停止做。"}]'::jsonb, 6, 'fltrp');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='elective1' AND unit='U2';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·对话 Practising for the Exam', '外研社版选择性必修第一册 U2 · dialogue', 3, 'Mia: You look tired, Tom. Have you been practising the piano again?
Tom: Yes. My music exam is next week, and I still can''t play one part well.
Mia: Don''t give up. Remember how badly you played a month ago?
Tom: That''s true. I have improved a lot, but it''s so slow.
Mia: Success rarely happens overnight. Just keep practising a little every day.
Tom: You''re right. I decided to practise one hour each evening until the exam.
Mia: That''s the spirit. I''m sure all your hard work will pay off.
Tom: Thanks, Mia. I won''t stop trying until I get it right.', '米娅看出汤姆又在练钢琴而疲惫;汤姆下周有音乐考试,有一段还弹不好;米娅劝他别放弃,想想一个月前弹得多差;汤姆承认进步很大但很慢;米娅说成功很少一蹴而就,每天坚持练一点;汤姆决定每晚练一小时直到考试;米娅鼓励他,努力终会有回报。', 'uk_female', '[{"q":"Why does Tom look tired?","type":"choice","answer":"A","options":["He has been practising the piano.","He stayed up watching films.","He ran a long race.","He has been ill all week."]},{"q":"When is Tom''s music exam?","type":"choice","answer":"B","options":["Next month.","Next week.","Tomorrow.","Yesterday."]},{"q":"What does Mia say about success?","type":"choice","answer":"A","options":["It rarely happens overnight.","It is impossible for Tom.","It comes only with luck.","It needs no practice."]},{"q":"What does Tom decide to do?","type":"choice","answer":"B","options":["Give up the exam.","Practise one hour each evening.","Practise only at weekends.","Ask Mia to play for him."]},{"q":"How does Mia feel about Tom''s effort?","type":"choice","answer":"C","options":["She thinks it is a waste of time.","She wants him to stop.","She is sure it will pay off.","She is angry with him."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·短文 Success Takes Time', '外研社版选择性必修第一册 U2 · passage', 2, 'Many people believe that famous writers became successful at once.
In fact, success rarely happens overnight.
A lot of well-known authors faced rejection again and again.
What made them different was that they refused to give up.
So keep trying, and one day your hard work may finally pay off.', '许多人以为著名作家是一举成名;事实上成功很少一蹴而就;不少知名作家曾一次次遭拒;他们与众不同之处在于不肯放弃;所以请坚持下去,有一天你的努力终会有回报。', 'uk_female', '[{"q":"What do many people wrongly believe about writers?","type":"choice","answer":"D","options":["That they never wrote at all.","That they hated reading.","That they were always poor.","That they became successful at once."]},{"q":"What does the speaker say about success?","type":"choice","answer":"A","options":["It rarely happens overnight.","It is easy for everyone.","It never comes to writers.","It depends only on luck."]},{"q":"What did many well-known authors face?","type":"choice","answer":"B","options":["No problems at all.","Rejection again and again.","Easy and quick fame.","A lack of ideas."]},{"q":"What made these authors different?","type":"choice","answer":"C","options":["They had rich families.","They wrote very fast.","They refused to give up.","They knew famous people."]},{"q":"What advice does the speaker give at the end?","type":"choice","answer":"D","options":["Stop writing immediately.","Wait for good luck.","Copy other authors.","Keep trying until it pays off."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·对话 Comforting a Friend', '外研社版选择性必修第一册 U2 · dialogue', 3, 'Jack: You look upset, Dawei. Why don''t you tell me what''s up?
Dawei: I ran for Head of the Student Committee, but I wasn''t elected.
Jack: I''m sorry to hear that. I''m sure you did your best.
Dawei: I did, but it still hurts. Maybe I''m just not good enough.
Jack: Don''t say that. You should be proud of how hard you worked.
Dawei: Thanks. I suppose one election can''t decide everything.
Jack: Exactly. Try to look on the bright side and cheer up.
Dawei: You''re a good friend, Jack. I already feel a little better.', '杰克看出大伟心烦,问他怎么了;大伟竞选学生会主席却落选;杰克表示遗憾,相信他尽力了;大伟很受伤,觉得自己不够好;杰克让他别这么说,应为努力而自豪;大伟想通一次落选决定不了一切;杰克劝他往好处看、振作起来;大伟感谢这位好友,已经好受了些。', 'uk_female', '[{"q":"Why is Dawei upset?","type":"choice","answer":"A","options":["He was not elected to the committee.","He lost his homework.","He failed a music exam.","He missed the school bus."]},{"q":"What does Jack say about Dawei''s effort?","type":"choice","answer":"B","options":["That it was useless.","That he is sure Dawei did his best.","That he should have tried harder.","That nobody noticed it."]},{"q":"What does Dawei slowly realise?","type":"choice","answer":"C","options":["That he will never try again.","That Jack is wrong.","That one election can''t decide everything.","That the result was unfair."]},{"q":"What does Jack advise Dawei to do?","type":"choice","answer":"D","options":["Forget all his friends.","Stop going to school.","Blame the other students.","Look on the bright side and cheer up."]},{"q":"How does Dawei feel by the end of the talk?","type":"choice","answer":"A","options":["A little better.","Much angrier.","Completely hopeless.","Bored and sleepy."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·短文 The Swimmer Who Kept Going', '外研社版选择性必修第一册 U2 · passage', 2, 'When Ben first joined the swimming team, he was the slowest of all.
Some of the other boys laughed and told him to quit.
But Ben enjoyed swimming, so he decided to keep practising every day.
Little by little, he grew stronger and faster than before.
Two years later, he won a gold medal at the city games.', '本刚加入游泳队时是最慢的;有些男孩取笑他,叫他退出;但本喜欢游泳,于是决定每天坚持训练;一点点地,他比以前更强更快;两年后,他在市运动会上夺得金牌。', 'uk_female', '[{"q":"What was Ben like when he first joined the team?","type":"choice","answer":"B","options":["He was already the fastest.","He was the slowest of all.","He was the team captain.","He was a famous swimmer."]},{"q":"What did some of the other boys tell him to do?","type":"choice","answer":"C","options":["To train even harder.","To become the coach.","To quit the team.","To join another sport."]},{"q":"What did Ben decide to do?","type":"choice","answer":"D","options":["Stop swimming for good.","Change to a new school.","Laugh at the others.","Keep practising every day."]},{"q":"How did Ben change over time?","type":"choice","answer":"A","options":["He grew stronger and faster.","He grew weaker.","He stayed exactly the same.","He lost interest."]},{"q":"What did Ben win two years later?","type":"choice","answer":"B","options":["A writing prize.","A gold medal at the city games.","A new bike.","A free holiday."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·对话 Two Kinds of Workers', '外研社版选择性必修第一册 U2 · dialogue', 3, 'Lily: Our group project is due on Friday. How is everyone doing?
Sam: I''ve already finished my part. I couldn''t wait to start.
Lily: You really are an eager beaver, Sam. That''s a great help.
Sam: Thanks. But I''m worried about Leo. He keeps putting off his part.
Lily: Yes, he''s been dragging his feet all week.
Sam: Maybe we should ask him kindly instead of getting angry.
Lily: Good idea. A wet blanket helps no one; let''s cheer him on.
Sam: Agreed. If we stay positive, he might catch our energy.', '莉莉问小组项目周五截止大家进度如何;萨姆已完成自己的部分,迫不及待就开始了;莉莉夸他是“拼命三郎”,帮了大忙;萨姆担心利奥老是拖着自己那部分;莉莉说他整周都在拖拖拉拉;萨姆建议好言相劝而非发火;莉莉同意,扫兴帮不了人,不如给他打气;萨姆赞同,保持积极也许会感染他。', 'uk_female', '[{"q":"When is the group project due?","type":"choice","answer":"C","options":["On Monday.","Next month.","On Friday.","Today."]},{"q":"Why does Lily call Sam an eager beaver?","type":"choice","answer":"D","options":["Because he is often late.","Because he never helps.","Because he is very quiet.","Because he finished his part early."]},{"q":"What is the problem with Leo?","type":"choice","answer":"A","options":["He keeps putting off his part.","He has left the school.","He has done too much.","He is angry with Sam."]},{"q":"What do Sam and Lily decide to do about Leo?","type":"choice","answer":"B","options":["Report him to the teacher.","Ask him kindly and cheer him on.","Do his part for him.","Stop talking to him."]},{"q":"What does Sam hope will happen if they stay positive?","type":"choice","answer":"C","options":["The project will be cancelled.","Leo will leave the group.","Leo might catch their energy.","Lily will do everything."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·短文 Use Your Eyes Today', '外研社版选择性必修第一册 U2 · passage', 2, 'A famous blind writer once gave us a simple piece of advice.
Use your eyes today as if tomorrow you would lose them.
Look closely at the faces of the people you love.
Listen to the mighty music of an orchestra while you still can.
If we treasure each small thing now, every day becomes a blessing.', '一位著名的盲人作家曾给我们一个简单的忠告;今天就用好你的眼睛,仿佛明天就会失去它们;仔细看看你所爱之人的脸;趁还能听,去听管弦乐队雄壮的乐声;若我们珍惜眼前的每件小事,每一天都会成为一种福气。', 'uk_female', '[{"q":"Who gave this piece of advice?","type":"choice","answer":"D","options":["A young athlete.","A school teacher.","A music student.","A famous blind writer."]},{"q":"How should we use our eyes today?","type":"choice","answer":"A","options":["As if tomorrow we would lose them.","As if we will never need them.","Only for reading books.","As little as possible."]},{"q":"What should we listen to while we still can?","type":"choice","answer":"B","options":["The noise of traffic.","The mighty music of an orchestra.","Our own voices.","A silent room."]},{"q":"What should we look closely at?","type":"choice","answer":"C","options":["The walls of a museum.","The pages of a book.","The faces of people we love.","Distant mountains."]},{"q":"What happens if we treasure small things now?","type":"choice","answer":"D","options":["We waste a lot of time.","We grow tired of life.","Nothing changes at all.","Every day becomes a blessing."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U2', 'fltrp');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='elective1' AND unit='U2';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (11, 'Write about Overcoming a Challenge(写一篇克服困难的经历)', 'A Challenge I Overcame', '假设你叫李华,学校英语报正在征集“勇往直前”主题的故事。请用英语写一篇约100词的短文,内容包括:① 你曾遇到的一个困难是什么;② 最难的地方在哪里、你当时的感受;③ 你如何坚持并克服了它;④ 你从中学到了什么。注意:恰当使用本单元 doing / to do 作宾语的结构(如 enjoy doing、decide to do、keep doing、stop doing 等)。', 'Suppose you are Li Hua. Your school English newspaper is collecting stories on the theme "Onwards and Upwards". Write a short passage (about 100 words) including: 1) a challenge you once faced; 2) what the hardest part was and how you felt; 3) how you kept going and overcame it; 4) what you learnt. Try to use object structures from this unit, such as enjoy doing, decide to do, keep doing and stop doing.', '["清楚交代困难(The biggest challenge I faced was …)","写出最难处与感受(The hardest part was … and I felt like giving up)","如何坚持克服(But I decided to … and kept …)","收获与感悟(I learnt that success rarely happens overnight)"]'::jsonb, 70, 100, 'Last year, the biggest challenge I faced was learning to swim before our school sports day. At first I was the slowest in the class, and the hardest part was the fear of deep water. More than once I felt like giving up. However, I decided to keep trying. I asked my coach to help me, and I practised swimming a little every morning before lessons. Slowly, I stopped feeling afraid and began to enjoy moving through the water. On sports day, I did not win, but I managed to finish my first race. This experience taught me that success rarely happens overnight, and that we should never give up.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["The biggest challenge I faced was learning to swim before our school sports day.","More than once I felt like giving up, but I decided to keep trying.","Slowly, I stopped feeling afraid and began to enjoy moving through the water.","This experience taught me that success rarely happens overnight."]'::jsonb, '[{"wrong":"I decided keeping trying.","correct":"I decided to keep trying.","note":"decide 后接不定式作宾语 to do。"},{"wrong":"I enjoy to swim every morning.","correct":"I enjoy swimming every morning.","note":"enjoy 后接动名词作宾语 doing。"},{"wrong":"I stopped to feel afraid and relaxed.","correct":"I stopped feeling afraid and relaxed.","note":"''不再害怕''用 stop doing;stop to do 意为''停下来去做''。"}]'::jsonb, '【克服困难记叙结构】
第1句 点题困难:The biggest challenge I faced was …
第2-3句 最难处与感受:The hardest part was … I felt like giving up.
第4-6句 如何坚持克服:However, I decided to … I kept … Slowly, I …
第7句 收获:This experience taught me that success rarely happens overnight.', 2, 'elective1', 'U2', 'fltrp');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='elective1' AND unit='U2';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (11, 'elective1', 'U2', '{"title":"-ing 与不定式作宾语·doing / to do 速查","intro":"有些动词后面只能接 doing,有些只能接 to do,还有一组接两者意义不同。判断口诀:看前面的主句动词;意义变化组再看句子语境是''未做/已做''。","table":{"headers":["类别","代表动词 / 例句"],"rows":[["只接 doing","enjoy / finish / avoid / mind / practise / suggest / consider / keep / give up:She enjoys writing stories."],["只接 to do","decide / hope / agree / promise / manage / offer / refuse / want / learn / fail:He decided to keep writing."],["接两者意义不同","remember / forget / regret / stop / try / mean:remember to do(未做) vs remember doing(已做)"],["stop 特例","stop to do = 停下来去做另一件事;stop doing = 停止正在做的事"]]},"specialRules":[{"rule":"remember/forget/regret + to do 指''该做、还没做'';+ doing 指''已经做过''","mark":"Remember to post it(还没寄) / I remember posting it(寄过了)"},{"rule":"stop to do = 停下来去做;stop doing = 停止做某事","mark":"He stopped to rest(停下休息) / He stopped swimming(不再游泳)"},{"rule":"try to do = 努力设法;try doing = 试着做(看效果)","mark":"try to finish(竭力做完) / try looking on the bright side(试着换个角度)"},{"rule":"mean to do = 打算;mean doing = 意味着","mark":"I meant to help(本打算) / Success means trying again(意味着)"}],"why":["doing 强调动作本身或经历(已发生/正进行),to do 强调一次具体的、往往尚未发生的动作或目的;主句动词的性质决定了它后面要搭配哪一种,意义变化组则进一步靠语境区分''未做''还是''已做''。"],"gaokaoPoints":["语法填空高频:给出动词原形,按主句动词判断填 doing 还是 to do。","remember/forget/stop/try + doing vs to do 的意义辨析是改错与单选常考点;尤其 stop to do 与 stop doing。"],"examVsReal":[{"exam":"I enjoy reading.（考试要求 doing）","real":"I love to read. / I love reading.","note":"考试里 enjoy 只能接 doing;但 love/like/begin/start 两种都行,口语里更随意"},{"exam":"Remember to lock the door.（考试强调未做）","real":"Don''t forget the door! / Lock up, yeah?","note":"考试看 to do/doing 辨意;真实口语常省略动词、直接点到名词或短句"}]}'::jsonb, 'fltrp');

COMMIT;

-- ===== 自带校验(publisher='fltrp') =====
SELECT 'vocab' k, count(*) v, 48 expect FROM public.junior_vocab WHERE publisher='fltrp' AND volume='elective1' AND unit='U2'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='elective1' AND unit='U2')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='fltrp' AND volume='elective1' AND unit='U2'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='fltrp' AND volume='elective1' AND unit='U2'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='elective1' AND unit='U2'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='elective1' AND unit='U2'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='elective1' AND unit='U2' ORDER BY k;
