-- ============================================================
-- 外研社(fltrp) 必修一 U2(Let's Celebrate!)灌库(junior_* 表,publisher='fltrp' volume='required2' unit='U2' grade=10)。幂等。
-- ★DELETE 全带 publisher='fltrp',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 50 =====
DELETE FROM public.junior_vocab WHERE publisher='fltrp' AND volume='required2' AND unit='U2';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'celebrate', 'v.', '/ˈselɪbreɪt/', '庆祝;颂扬', 'Families gather to celebrate the festival every year.', '每年家家户户都团聚庆祝这个节日。', 'Lets Celebrate', 1, 0, 'senior', 'wordlist', 'required2', 'U2', 'celebrate a festival', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'celebration', 'n.', '/ˌselɪˈbreɪʃn/', '庆祝;庆祝活动', 'The Lantern Festival celebrations attract crowds of people.', '元宵节庆祝活动吸引了大批人群。', 'Lets Celebrate', 2, 0, 'senior', 'wordlist', 'required2', 'U2', 'festival celebrations', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'festival', 'n.', '/ˈfestɪvl/', '节日;庆典', 'The Spring Festival is the most important festival in China.', '春节是中国最重要的节日。', 'Lets Celebrate', 3, 0, 'senior', 'wordlist', 'required2', 'U2', 'a traditional festival', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'tradition', 'n.', '/trəˈdɪʃn/', '传统;惯例', 'Eating dumplings is a tradition many families keep.', '吃饺子是许多家庭保留的传统。', 'Lets Celebrate', 4, 0, 'senior', 'wordlist', 'required2', 'U2', 'keep a tradition', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'decorate', 'v.', '/ˈdekəreɪt/', '装饰;布置', 'We decorate our windows with red posters before the festival.', '节前我们用红色海报装饰窗户。', 'Lets Celebrate', 5, 0, 'senior', 'wordlist', 'required2', 'U2', 'decorate with lanterns', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'decoration', 'n.', '/ˌdekəˈreɪʃn/', '装饰物;装饰品', 'The streets were full of colourful decorations for the New Year.', '为庆祝新年,街道上挂满了五彩的装饰物。', 'Lets Celebrate', 6, 0, 'senior', 'wordlist', 'required2', 'U2', 'colourful decorations', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'lantern', 'n.', '/ˈlæntən/', '灯笼', 'Children carry bright red lanterns through the streets.', '孩子们提着明亮的红灯笼走过街道。', 'Lets Celebrate', 7, 0, 'senior', 'wordlist', 'required2', 'U2', 'red lanterns', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'firework', 'n.', '/ˈfaɪəwɜːk/', '烟花;烟火', 'At midnight, fireworks lit up the whole sky.', '午夜时分,烟花照亮了整个天空。', 'Lets Celebrate', 8, 0, 'senior', 'wordlist', 'required2', 'U2', 'set off fireworks', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'riddle', 'n.', '/ˈrɪdl/', '谜;谜语', 'People love to guess the riddles written on the lanterns.', '人们喜欢猜写在灯笼上的谜语。', 'Lets Celebrate', 9, 0, 'senior', 'wordlist', 'required2', 'U2', 'guess a riddle', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'competition', 'n.', '/ˌkɒmpəˈtɪʃn/', '比赛;竞赛', 'Our school held a lantern riddle competition for the festival.', '我们学校为这个节日举办了灯谜比赛。', 'Lets Celebrate', 10, 0, 'senior', 'wordlist', 'required2', 'U2', 'a riddle competition', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'dessert', 'n.', '/dɪˈzɜːt/', '(饭后)甜点', 'Rice balls are a popular dessert during the Lantern Festival.', '汤圆是元宵节里很受欢迎的甜点。', 'Lets Celebrate', 11, 0, 'senior', 'wordlist', 'required2', 'U2', 'a sweet dessert', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'attract', 'v.', '/əˈtrækt/', '吸引;引起兴趣', 'The lantern fair attracts thousands of visitors each year.', '灯会每年吸引数千名游客。', 'Lets Celebrate', 12, 0, 'senior', 'wordlist', 'required2', 'U2', 'attract visitors', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'host', 'n.', '/həʊst/', '主人;东道主;主办方', 'The host welcomed every guest at the door.', '主人在门口迎接每一位客人。', 'Lets Celebrate', 13, 0, 'senior', 'wordlist', 'required2', 'U2', 'a kind host', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'guest', 'n.', '/ɡest/', '客人;宾客', 'The host prepared a big meal for all the guests.', '主人为所有客人准备了一顿大餐。', 'Lets Celebrate', 14, 0, 'senior', 'wordlist', 'required2', 'U2', 'invite guests', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'formal', 'adj.', '/ˈfɔːml/', '正式的', 'A wedding usually needs a formal written invitation.', '婚礼通常需要正式的书面邀请。', 'Lets Celebrate', 15, 0, 'senior', 'wordlist', 'required2', 'U2', 'a formal invitation', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'occasion', 'n.', '/əˈkeɪʒn/', '场合;时刻;盛会', 'We wear our best clothes on such a special occasion.', '在这样特别的场合,我们会穿上最好的衣服。', 'Lets Celebrate', 16, 0, 'senior', 'wordlist', 'required2', 'U2', 'a special occasion', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'occur', 'v.', '/əˈkɜː/', '发生;出现', 'The festival occurs on the fifteenth day of the first lunar month.', '这个节日在农历正月十五举行。', 'Lets Celebrate', 17, 0, 'senior', 'wordlist', 'required2', 'U2', 'occur every year', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'lunar', 'adj.', '/ˈluːnə/', '月球的;农历的', 'The date of the festival follows the lunar calendar.', '这个节日的日期按农历计算。', 'Lets Celebrate', 18, 0, 'senior', 'wordlist', 'required2', 'U2', 'the lunar calendar', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'harvest', 'n.', '/ˈhɑːvɪst/', '收成;丰收;收获', 'The Mid-Autumn Festival celebrates the autumn harvest.', '中秋节庆祝秋天的丰收。', 'Lets Celebrate', 19, 0, 'senior', 'wordlist', 'required2', 'U2', 'celebrate the harvest', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'dragon', 'n.', '/ˈdræɡən/', '龙', 'A colourful dragon dance opened the festival.', '一场多彩的舞龙表演拉开了节日的序幕。', 'Lets Celebrate', 20, 0, 'senior', 'wordlist', 'required2', 'U2', 'a dragon dance', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'poet', 'n.', '/ˈpəʊɪt/', '诗人', 'The Dragon Boat Festival honours an ancient poet.', '端午节是为了纪念一位古代诗人。', 'Lets Celebrate', 21, 0, 'senior', 'wordlist', 'required2', 'U2', 'honour a poet', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'poetry', 'n.', '/ˈpəʊɪtri/', '诗;诗歌', 'People read his poetry aloud to remember him.', '人们大声朗读他的诗歌来纪念他。', 'Lets Celebrate', 22, 0, 'senior', 'wordlist', 'required2', 'U2', 'read poetry', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'honour', 'v.', '/ˈɒnə/', '向……表示敬意;给……以荣誉', 'The festival is held to honour a famous poet.', '举办这个节日是为了纪念一位著名的诗人。', 'Lets Celebrate', 23, 0, 'senior', 'wordlist', 'required2', 'U2', 'honour the dead', '美式拼 honor;美音 /ˈɑːnər/', 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'literature', 'n.', '/ˈlɪtrətʃə/', '文学;文学作品', 'Tolkien is a famous name in English literature.', '托尔金是英国文学中的一个著名人物。', 'Lets Celebrate', 24, 0, 'senior', 'wordlist', 'required2', 'U2', 'English literature', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'novel', 'n.', '/ˈnɒvl/', '(长篇)小说', 'He is best known for his fantasy novels.', '他以奇幻小说而闻名。', 'Lets Celebrate', 25, 0, 'senior', 'wordlist', 'required2', 'U2', 'a fantasy novel', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'fantasy', 'n.', '/ˈfæntəsi/', '幻想;想象;奇幻作品', 'His books created a rich world of fantasy for readers.', '他的书为读者创造了一个丰富的奇幻世界。', 'Lets Celebrate', 26, 0, 'senior', 'wordlist', 'required2', 'U2', 'a world of fantasy', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'envelope', 'n.', '/ˈenvələʊp/', '信封', 'Inside the envelope was a handwritten letter.', '信封里是一封手写的信。', 'Lets Celebrate', 27, 0, 'senior', 'wordlist', 'required2', 'U2', 'open an envelope', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'regular', 'adj.', '/ˈreɡjələ/', '频繁的;经常的;规律的', 'Polar Bear was a regular character in the letters.', '北极熊是这些信中的常客。', 'Lets Celebrate', 28, 0, 'senior', 'wordlist', 'required2', 'U2', 'a regular visitor', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'complain', 'v.', '/kəmˈpleɪn/', '抱怨;投诉', 'In one letter, Father Christmas complained about his helpers.', '在一封信里,圣诞老人抱怨他的助手。', 'Lets Celebrate', 29, 0, 'senior', 'wordlist', 'required2', 'U2', 'complain about', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'warning', 'n.', '/ˈwɔːnɪŋ/', '警告;告诫', 'The letters did not contain the usual warning to children.', '这些信里没有给孩子们通常的那种告诫。', 'Lets Celebrate', 30, 0, 'senior', 'wordlist', 'required2', 'U2', 'give a warning', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'indicate', 'v.', '/ˈɪndɪkeɪt/', '表明;显示;指出', 'The bold words indicate how sure the speaker is.', '黑体字表明了说话人有多么确定。', 'Lets Celebrate', 31, 0, 'senior', 'wordlist', 'required2', 'U2', 'indicate a meaning', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'request', 'n./v.', '/rɪˈkwest/', '请求;要求', 'She sent a polite request asking him to the party.', '她发出礼貌的请求,邀请他参加聚会。', 'Lets Celebrate', 32, 0, 'senior', 'wordlist', 'required2', 'U2', 'a polite request', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'fancy', 'adj.', '/ˈfænsi/', '花哨的;别致的;盛装的', 'Everyone came to the fancy dress party in costume.', '每个人都穿着戏服来参加化装舞会。', 'Lets Celebrate', 33, 0, 'senior', 'wordlist', 'required2', 'U2', 'fancy dress', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'guy', 'n.', '/ɡaɪ/', '(尤指年轻)男子;家伙', 'That guy dressed as Batman is my classmate.', '那个打扮成蝙蝠侠的男生是我同学。', 'Lets Celebrate', 34, 0, 'senior', 'wordlist', 'required2', 'U2', 'that guy', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'wave', 'v.', '/weɪv/', '挥手;招手;挥动', 'The two guys in costume waved at us happily.', '那两个穿着戏服的男生高兴地向我们挥手。', 'Lets Celebrate', 35, 0, 'senior', 'wordlist', 'required2', 'U2', 'wave at someone', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'participate', 'v.', '/pɑːˈtɪsɪpeɪt/', '参加;参与', 'Students from many schools participate in the celebrations.', '许多学校的学生都参加这些庆祝活动。', 'Lets Celebrate', 36, 0, 'senior', 'wordlist', 'required2', 'U2', 'participate in', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'editor', 'n.', '/ˈedɪtə/', '编辑;主编', 'He wrote a letter to the editor about the festival.', '他就这个节日给主编写了一封信。', 'Lets Celebrate', 37, 0, 'senior', 'wordlist', 'required2', 'U2', 'a letter to the editor', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'admit', 'v.', '/ədˈmɪt/', '(不情愿地)承认;准许进入', 'I have to admit that cooking the dinner is hard work.', '我得承认做这顿饭很辛苦。', 'Lets Celebrate', 38, 0, 'senior', 'wordlist', 'required2', 'U2', 'admit the truth', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'effort', 'n.', '/ˈefət/', '努力;力气;尝试', 'Preparing the festival meal takes a lot of effort.', '准备节日大餐要花很多力气。', 'Lets Celebrate', 39, 0, 'senior', 'wordlist', 'required2', 'U2', 'make an effort', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'loss', 'n.', '/lɒs/', '失去;丧失;损失', 'Eating out has nothing to do with the loss of traditions.', '在外面吃饭与传统的丧失毫无关系。', 'Lets Celebrate', 40, 0, 'senior', 'wordlist', 'required2', 'U2', 'the loss of traditions', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'eve', 'n.', '/iːv/', '前夕;前一天', 'On Spring Festival Eve the whole family eats together.', '除夕之夜,全家人一起吃饭。', 'Lets Celebrate', 41, 0, 'senior', 'wordlist', 'required2', 'U2', 'New Year''s Eve', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'adult', 'n.', '/ˈædʌlt/', '成人;成年人', 'I loved listening to the adults chatting about their year.', '我喜欢听大人们聊他们这一年的事。', 'Lets Celebrate', 42, 0, 'senior', 'wordlist', 'required2', 'U2', 'the adults', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'process', 'n.', '/ˈprəʊses/', '过程;进程', 'To me, the process of cooking together matters most.', '对我来说,一起做饭的过程最重要。', 'Lets Celebrate', 43, 0, 'senior', 'wordlist', 'required2', 'U2', 'the whole process', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'retired', 'adj.', '/rɪˈtaɪəd/', '退休的', 'The retired teacher shared his memory of the festival.', '这位退休教师分享了他对节日的回忆。', 'Lets Celebrate', 44, 0, 'senior', 'wordlist', 'required2', 'U2', 'a retired teacher', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'exist', 'v.', '/ɪɡˈzɪst/', '存在;实际上有', 'Many old festival customs still exist today.', '许多古老的节日习俗至今仍然存在。', 'Lets Celebrate', 45, 0, 'senior', 'wordlist', 'required2', 'U2', 'still exist', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'overseas', 'adv.', '/ˌəʊvəˈsiːz/', '在海外;在国外', 'Chinese people living overseas also celebrate the festival.', '生活在海外的华人也庆祝这个节日。', 'Lets Celebrate', 46, 0, 'senior', 'wordlist', 'required2', 'U2', 'live overseas', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'global', 'adj.', '/ˈɡləʊbl/', '全球的;全世界的', 'The Spring Festival is becoming a global celebration of joy.', '春节正成为一场全球性的欢乐庆典。', 'Lets Celebrate', 47, 0, 'senior', 'wordlist', 'required2', 'U2', 'a global celebration', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'nationality', 'n.', '/ˌnæʃəˈnæləti/', '国籍;民族', 'People of many nationalities now enjoy the festival.', '如今许多国籍的人都喜欢这个节日。', 'Lets Celebrate', 48, 0, 'senior', 'wordlist', 'required2', 'U2', 'many nationalities', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'audience', 'n.', '/ˈɔːdiəns/', '观众;听众', 'The concert drew a large audience of local people.', '音乐会吸引了大量当地观众。', 'Lets Celebrate', 49, 0, 'senior', 'wordlist', 'required2', 'U2', 'a large audience', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'joy', 'n.', '/dʒɔɪ/', '欢乐;喜悦', 'The festival fills the streets with joy and laughter.', '节日让街道充满欢乐与笑声。', 'Lets Celebrate', 50, 0, 'senior', 'wordlist', 'required2', 'U2', 'full of joy', NULL, 'fltrp');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2');
DELETE FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f2u2.01', '①must have done(对过去的肯定推测:几乎确定发生过)', 'A2', 10, '外研社版必修第二册 U2 — 句中有确凿证据(看得见的结果、明显的痕迹)、说话人非常肯定某事过去发生过时,用 must have done。', 1, 'required2', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f2u2.02', '②might / may / could have done(对过去的可能推测:也许发生过)', 'A2', 10, '外研社版必修第二册 U2 — 句中表示不确定(maybe/perhaps/I''m not sure/也许)、只是一种可能时,用 might/may/could have done。', 2, 'required2', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f2u2.03', '③can''t / couldn''t have done(对过去的否定推测:几乎不可能发生过)', 'A2', 10, '外研社版必修第二册 U2 — 句中证据说明某事过去绝不可能发生(时间、地点、能力上对不上)时,用 can''t/couldn''t have done。', 3, 'required2', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'The floor is covered with wrapping paper, so the children ____ their presents already.', 'must have opened', 'might have opened', 'can''t have opened', 'must open', 'A', '满地包装纸是确凿结果,对过去的肯定推测用 must have done;只是可能(might have)太弱、can''t have 与证据相反、must open 不是对过去的推测。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'Look at all these empty plates — the guests ____ the whole feast.', 'might have eaten', 'must have eaten', 'can''t have eaten', 'must eat', 'B', '盘子全空是明显证据,肯定推测过去已发生用 must have eaten;其余或太不确定、或与事实相反、或不是过去推测。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'Tolkien drew every letter so beautifully, so each one ____ him hours to finish.', 'might have taken', 'can''t have taken', 'must have taken', 'must take', 'C', '画得如此精美是确凿依据,肯定推测过去花了很久用 must have taken。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'The hall is full of balloons and flowers, so someone ____ very hard last night.', 'may have worked', 'can''t have worked', 'must work', 'must have worked', 'D', '满屋气球鲜花是结果,肯定推测昨晚有人忙过用 must have worked。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'She knew every answer to the lantern riddles, so she ____ them somewhere before.', 'must have seen', 'could have seen', 'can''t have seen', 'must see', 'A', '每题都会是确凿证据,肯定推测她以前见过用 must have seen。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'Their faces were red and sweaty, so the dragon dancers ____ for hours.', 'might have practised', 'must have practised', 'can''t have practised', 'must practise', 'B', '满脸通红冒汗是明显结果,肯定推测练了好几个小时用 must have practised。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'The fireworks went off perfectly, so the team ____ everything very carefully.', 'may have planned', 'can''t have planned', 'must have planned', 'must plan', 'C', '烟花完美是结果,肯定推测事先精心安排过用 must have planned。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'There is a North Pole stamp on it, so the letter ____ a very long way.', 'might have travelled', 'can''t have travelled', 'must travel', 'must have travelled', 'D', '贴着北极邮票是确凿依据,肯定推测信走了很远用 must have travelled。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'Grandpa keeps smiling at the old photo, so that family dinner ____ him very happy.', 'must have made', 'could have made', 'can''t have made', 'must make', 'A', '一直对着老照片微笑是依据,肯定推测那顿饭让他很开心用 must have made。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'The whole street smells of food, so the neighbours ____ all morning for the festival.', 'might have cooked', 'must have cooked', 'can''t have cooked', 'must cook', 'B', '满街饭菜香是结果,肯定推测邻居们做了一上午饭用 must have cooked。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'Her eyes were shining with joy, so the surprise party ____ her a lot.', 'may have pleased', 'can''t have pleased', 'must have pleased', 'must please', 'C', '双眼放光是明显结果,肯定推测惊喜派对让她很高兴用 must have pleased。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'All the lanterns were already hung up, so the volunteers ____ very early this morning.', 'might have arrived', 'can''t have arrived', 'must arrive', 'must have arrived', 'D', '灯笼全挂好了是结果,肯定推测志愿者一早就到了用 must have arrived。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'He could describe every float in the parade, so he ____ it himself.', 'must have watched', 'could have watched', 'can''t have watched', 'must watch', 'A', '每辆花车都说得出是依据,肯定推测他亲眼看过用 must have watched。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'The mooncakes are still warm, so someone ____ them just a moment ago.', 'might have baked', 'must have baked', 'can''t have baked', 'must bake', 'B', '月饼还热着是确凿证据,肯定推测刚有人烤过用 must have baked。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'The children were jumping up and down, so they ____ the good news.', 'may have heard', 'can''t have heard', 'must have heard', 'must hear', 'C', '高兴得直跳是结果,肯定推测他们已听到好消息用 must have heard。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'There was a red envelope on every chair, so the host ____ them for the guests.', 'might have prepared', 'can''t have prepared', 'must prepare', 'must have prepared', 'D', '每把椅子上都有红包是结果,肯定推测主人事先备好用 must have prepared。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'The square was packed at midnight, so thousands of people ____ to see the show.', 'must have come', 'could have come', 'can''t have come', 'must come', 'A', '午夜广场挤满人是依据,肯定推测成千上万人来过用 must have come。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'Her costume was covered in dust, so she ____ in the attic for it.', 'may have searched', 'must have searched', 'can''t have searched', 'must search', 'B', '戏服落满灰是结果,肯定推测她在阁楼里翻找过用 must have searched。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'Everyone is still talking about his speech, so it ____ a deep impression.', 'might have left', 'can''t have left', 'must have left', 'must leave', 'C', '大家还在议论是依据,肯定推测他的演讲留下了深刻印象用 must have left。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.01'), 'The poet''s name is on every banner, so the town ____ to honour him.', 'could have decided', 'can''t have decided', 'must decide', 'must have decided', 'D', '处处横幅都是诗人名字是依据,肯定推测全镇已决定纪念他用 must have decided。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'I''m not sure who sent the card, but it ____ from my cousin overseas.', 'might have come', 'must have come', 'can''t have come', 'might come', 'A', 'I''m not sure 表不确定,对过去只是一种可能用 might have come;must have 太肯定、can''t have 是否定、might come 不是过去推测。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'Nobody answered the door — they ____ out to watch the parade.', 'must have gone', 'may have gone', 'can''t have gone', 'may go', 'B', '没人应门只是推测原因之一,可能推测用 may have gone。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'Perhaps the lights went out because someone ____ the wrong switch.', 'must have pressed', 'can''t have pressed', 'could have pressed', 'could press', 'C', 'Perhaps 表不确定,对过去的可能推测用 could have pressed。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'He didn''t reply to the invitation; maybe he ____ it in his inbox.', 'must have missed', 'can''t have missed', 'might miss', 'might have missed', 'D', 'maybe 表也许,可能推测他没看到用 might have missed。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'The cake tastes a little sweet — they ____ some extra sugar.', 'may have added', 'must have added', 'can''t have added', 'may add', 'A', '尝起来甜只是一种猜测,可能推测加了糖用 may have added。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'I can''t find my lantern; a younger child ____ it by mistake.', 'must have taken', 'could have taken', 'can''t have taken', 'could take', 'B', '只是猜可能被谁拿走,可能推测用 could have taken。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'She looks tired today; she ____ up late at the festival last night.', 'must have stayed', 'can''t have stayed', 'might have stayed', 'might stay', 'C', '看起来累只是猜测原因,可能推测昨晚熬夜用 might have stayed。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'The hall is half empty — some guests ____ the time of the party.', 'must have forgotten', 'can''t have forgotten', 'may forget', 'may have forgotten', 'D', '半空只是推测,可能推测有人忘了时间用 may have forgotten。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'We''re not certain, but Polar Bear ____ through the roof once again.', 'could have fallen', 'must have fallen', 'can''t have fallen', 'could fall', 'A', 'not certain 表不确定,可能推测用 could have fallen。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'His phone is off; perhaps he ____ it at the dinner table.', 'must have left', 'might have left', 'can''t have left', 'might leave', 'B', 'perhaps 表也许,可能推测他把手机落下了用 might have left。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'The riddle was tricky, so a few people ____ the wrong answer.', 'must have given', 'can''t have given', 'may have given', 'may give', 'C', '只是猜测有人答错,可能推测用 may have given。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'I heard a loud bang outside — someone ____ off a firework.', 'must have set', 'can''t have set', 'could set', 'could have set', 'D', '听到响声只是一种猜测来源,可能推测用 could have set。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'Maybe the parcel is late because it ____ stuck in the snow.', 'might have got', 'must have got', 'can''t have got', 'might get', 'A', 'Maybe 表也许,可能推测包裹被雪困住用 might have got。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'There''s mud on his shoes; he ____ across the park to the square.', 'must have walked', 'may have walked', 'can''t have walked', 'may walk', 'B', '鞋上有泥只是一种猜测,可能推测他穿过公园走来用 may have walked。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'We don''t know why she''s crying; the film ____ her deeply.', 'must have moved', 'can''t have moved', 'could have moved', 'could move', 'C', 'don''t know 表不确定,可能推测影片打动了她用 could have moved。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'The food is all gone; the guests ____ hungry after the long show.', 'must have felt', 'can''t have felt', 'might feel', 'might have felt', 'D', '只是推测原因之一,可能推测客人饿了用 might have felt。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'I''m not sure, but Tony ____ Hugo to his apartment for Thanksgiving.', 'may have invited', 'must have invited', 'can''t have invited', 'may invite', 'A', 'not sure 表不确定,可能推测用 may have invited。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'Her hands are covered in flour; she ____ dumplings earlier.', 'must have made', 'could have made', 'can''t have made', 'could make', 'B', '手上有面粉只是一种猜测,可能推测她包过饺子用 could have made。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'Perhaps they''re so quiet because the long day ____ them out.', 'must have worn', 'can''t have worn', 'might have worn', 'might wear', 'C', 'Perhaps 表也许,可能推测累坏了他们用 might have worn。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.02'), 'We can''t be sure, but the loud music ____ the neighbours late at night.', 'must have woken', 'can''t have woken', 'may wake', 'may have woken', 'D', 'can''t be sure 表不确定,可能推测吵醒了邻居用 may have woken。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'Lucy is quite short, so that tall girl in the bride costume ____ her.', 'can''t have been', 'must have been', 'might have been', 'can''t be', 'A', 'Lucy 个子矮是确凿矛盾,对过去的否定推测用 can''t have been;must have 与事实相反、might have 太弱、can''t be 不是过去推测。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The shops were shut all day, so he ____ the decorations there.', 'must have bought', 'couldn''t have bought', 'may have bought', 'couldn''t buy', 'B', '整天关门是确凿矛盾,否定推测过去不可能买到用 couldn''t have bought。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'She was on a plane at noon, so she ____ at the lantern fair then.', 'must have been', 'might have been', 'can''t have been', 'can''t be', 'C', '中午在飞机上,时间对不上,否定推测用 can''t have been。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'There was no snow that winter, so Polar Bear ____ a snowman at all.', 'must have built', 'could have built', 'couldn''t build', 'couldn''t have built', 'D', '那年没下雪是确凿矛盾,否定推测堆不成雪人用 couldn''t have built。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The letter is in perfect English, so a small child ____ it alone.', 'can''t have written', 'must have written', 'might have written', 'can''t write', 'A', '英文写得完美,小孩子做不到,否定推测用 can''t have written。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'He hates anything sweet, so he ____ all the mooncakes.', 'must have eaten', 'couldn''t have eaten', 'may have eaten', 'couldn''t eat', 'B', '他讨厌甜食是确凿矛盾,否定推测不可能吃光月饼用 couldn''t have eaten。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The fireworks only start at eight, so people ____ them at six.', 'must have seen', 'might have seen', 'can''t have seen', 'can''t see', 'C', '八点才放,时间对不上,否定推测六点看不到用 can''t have seen。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'Grandma can''t drive, so she ____ the family to the square herself.', 'must have driven', 'could have driven', 'couldn''t drive', 'couldn''t have driven', 'D', '奶奶不会开车是确凿矛盾,否定推测用 couldn''t have driven。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The museum was closed all week, so they ____ the old lanterns inside.', 'can''t have seen', 'must have seen', 'may have seen', 'can''t see', 'A', '整周闭馆是确凿矛盾,否定推测看不到馆内灯笼用 can''t have seen。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'He was abroad last week, so he ____ at the Spring Festival dinner.', 'must have been', 'couldn''t have been', 'might have been', 'couldn''t be', 'B', '上周在国外,地点对不上,否定推测用 couldn''t have been。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The envelope was completely empty, so it ____ any money.', 'must have held', 'could have held', 'can''t have held', 'can''t hold', 'C', '信封空空如也是确凿矛盾,否定推测里面没装钱用 can''t have held。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'She doesn''t know him at all, so she ____ him to her party.', 'must have invited', 'may have invited', 'couldn''t invite', 'couldn''t have invited', 'D', '根本不认识是确凿矛盾,否定推测不可能请他用 couldn''t have invited。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The river was frozen solid, so they ____ a dragon boat race that day.', 'can''t have held', 'must have held', 'might have held', 'can''t hold', 'A', '河面结冰是确凿矛盾,否定推测办不成龙舟赛用 can''t have held。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The power was off all evening, so the lights ____ the riddles.', 'must have shown', 'couldn''t have shown', 'could have shown', 'couldn''t show', 'B', '整晚停电是确凿矛盾,否定推测灯照不出谜语用 couldn''t have shown。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'He only arrived today, so he ____ the parade yesterday.', 'must have joined', 'might have joined', 'can''t have joined', 'can''t join', 'C', '今天才到,时间对不上,否定推测昨天没法参加游行用 can''t have joined。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The bakery had sold out, so she ____ a cake there for the guests.', 'must have got', 'may have got', 'couldn''t get', 'couldn''t have got', 'D', '面包店售罄是确凿矛盾,否定推测买不到蛋糕用 couldn''t have got。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'Their team lost every single game, so they ____ the competition.', 'can''t have won', 'must have won', 'might have won', 'can''t win', 'A', '每场都输是确凿矛盾,否定推测不可能赢得比赛用 can''t have won。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'It poured with rain all night, so the firework show ____ on time.', 'must have started', 'couldn''t have started', 'could have started', 'couldn''t start', 'B', '整夜大雨是确凿矛盾,否定推测准点办不成烟花秀用 couldn''t have started。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'He can''t cook at all, so he ____ this lovely dinner by himself.', 'must have prepared', 'may have prepared', 'can''t have prepared', 'can''t prepare', 'C', '他完全不会做饭是确凿矛盾,否定推测独自做不出这顿饭用 can''t have prepared。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2' AND code='f2u2.03'), 'The small hall holds only fifty people, so a thousand guests ____ inside.', 'must have fitted', 'might have fitted', 'couldn''t fit', 'couldn''t have fitted', 'D', '小厅只能容五十人是确凿矛盾,否定推测千名客人挤不进去用 couldn''t have fitted。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='fltrp' AND volume='required2' AND unit='U2';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'The Real Father Christmas', 'Many children still remember the magic of Father Christmas. The book Letters from Father Christmas could be the perfect gift for those who love this time of year. The letters were written by J.R.R. Tolkien, one of the most famous names in English literature. For more than twenty years, he wrote them to keep the magic alive for his four children. Every Christmas, an envelope with a North Pole stamp arrived. The children must have been very excited as they opened it. Inside, they found a handwritten letter, beautifully drawn. Each one must have taken Tolkien a long time to finish. The letters told wonderful stories about Father Christmas and his helper, Polar Bear, who once fell through the roof. By showing his love in such a special way, Tolkien may indeed have been a real Father Christmas to his family.', '说明·圣诞老人书信', 141, '[{"q":"Why did Tolkien write the letters every year?","answer":"A","options":["To keep the joy of Father Christmas alive for his children.","To earn money from a famous publisher.","To teach his children how to draw.","To complain about the cold North Pole."],"explanation":"原文说他写信是为了为四个孩子保留圣诞老人的魔力,即让欢乐延续,是其转述。"},{"q":"What can we learn about each letter?","answer":"B","options":["It was printed by a machine in minutes.","It was carefully drawn and took a long time.","It was thrown away after Christmas.","It was written by the children themselves."],"explanation":"原文称每封都画得很美、花了很长时间完成,是其概括。"},{"q":"What does the writer think of Tolkien at the end?","answer":"A","options":["His loving way made him like a real Father Christmas.","He was too busy to care for his family.","He disliked the Christmas season.","He copied the letters from another writer."],"explanation":"末句说他用特别方式表达爱,堪称真正的圣诞老人,是转述。"}]'::jsonb, '[{"word":"envelope","cn":"信封"},{"word":"literature","cn":"文学"},{"word":"handwritten","cn":"手写的"}]'::jsonb, 2, 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Lights of the Lantern Festival', 'The Lantern Festival falls on the fifteenth day of the first lunar month, marking the end of the Spring Festival season. On this evening, streets and parks glow with thousands of red lanterns. Families come out to enjoy the warm light and the lively crowds. One of the most popular activities is guessing lantern riddles. Each riddle is written on a slip of paper and hung beneath a lantern; anyone who works out the answer can win a small prize. The festival also has its own special food. Sweet rice balls, served warm in a bowl, are a favourite dessert because their round shape stands for family and togetherness. In many cities, the lantern fair attracts huge crowds, so the traffic police are kept very busy keeping everyone safe. For children and adults alike, the glowing lanterns turn an ordinary night into a celebration full of joy.', '说明·元宵灯会', 147, '[{"q":"When does the Lantern Festival take place?","answer":"B","options":["On the first morning of the new year.","As the Spring Festival holidays come to an end.","In the middle of the summer harvest.","On the eve of the Mid-Autumn Festival."],"explanation":"原文说它在正月十五、标志春节季的结束,即春节季尾声,是转述。"},{"q":"Why are sweet rice balls eaten at the festival?","answer":"C","options":["They are the cheapest food in the market.","They can only be made in winter.","Their round form is a sign of family unity.","They are difficult to cook at home."],"explanation":"原文说圆形象征家庭团圆,是其概括。"},{"q":"Why are the traffic police very busy that night?","answer":"D","options":["Many cars break down in the cold.","The lanterns block all the main roads.","People forget the date of the festival.","Large crowds gather for the lantern fair."],"explanation":"原文说灯会吸引大批人群,警察忙着保障安全,是转述。"}]'::jsonb, '[{"word":"lantern","cn":"灯笼"},{"word":"riddle","cn":"谜语"},{"word":"dessert","cn":"甜点"}]'::jsonb, 2, 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Dinner Out or Dinner at Home?', 'Every year before the Spring Festival, families face the same question: should the family dinner be cooked at home or eaten at a restaurant? Mr Wang, a software engineer, prefers eating out. He argues that preparing the meal is hard work, and that cleaning up afterwards takes hours. For him, the festival should be a day for relaxing and spending time with family, not for tiring cooking. The dishes, he adds, often taste better in a restaurant. Mr Liu, a retired teacher, sees things differently. When he was a boy, the dinner on the eve of Spring Festival was what he looked forward to most. He remembers watching his mother make dumplings and listening to the adults chat about their year. To him, preparing the meal together is even more important than the meal itself. Both men, however, agree on one thing: the love shared around the table never changes.', '议论·春节家宴之争', 150, '[{"q":"Why does Mr Wang prefer eating out?","answer":"A","options":["He thinks cooking and cleaning up take too much time and effort.","He cannot afford to buy food for cooking.","He dislikes spending the day with his family.","He believes restaurants are quieter than home."],"explanation":"原文说做饭辛苦、收拾费时,他想轻松过节,是转述。"},{"q":"What does Mr Liu value most about the dinner?","answer":"B","options":["Eating at the most expensive restaurant.","Preparing the meal together with the family.","Receiving gifts from his old students.","Watching television after the meal."],"explanation":"原文说一起准备这顿饭比饭本身更重要,是其概括。"},{"q":"What do the two men agree on?","answer":"C","options":["Home cooking always tastes the best.","Restaurants should be closed at festivals.","The love shared at the table stays the same.","Young people should cook for the old."],"explanation":"末句说桌边分享的爱永不改变,是转述。"}]'::jsonb, '[{"word":"eve","cn":"前夕"},{"word":"retired","cn":"退休的"},{"word":"process","cn":"过程"}]'::jsonb, 2, 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'A Thanksgiving Invitation', 'In the United States, Thanksgiving is celebrated on the fourth Thursday in November. It is a warm family occasion, and people often invite close friends to share the meal. This year, Tony has decided to invite his classmate Hugo to his apartment for the holiday. On the phone, Hugo happily accepts and asks what he should bring. Tony tells him that guests usually bring some flowers or a small dessert, but the host prepares the main dishes. The centre of the meal is always a large roast turkey, served with many side dishes and a homemade pie. Before they eat, the family takes turns saying what they are thankful for. Hugo is a little nervous because he has never been to a Thanksgiving dinner, but Tony promises to help him feel at home. After the meal, they plan to watch a football game together, just as many American families do.', '说明·感恩节邀请', 150, '[{"q":"What does Tony ask Hugo to bring to the dinner?","answer":"D","options":["A large roast turkey.","Tickets for a football game.","A formal written invitation.","A few flowers or a sweet treat."],"explanation":"原文说客人通常带花或甜点,主菜由主人准备,是转述。"},{"q":"What do the family do before they start eating?","answer":"A","options":["Everyone takes a turn to share their thanks.","They send out written invitations.","They watch a football game.","They guess lantern riddles."],"explanation":"原文说饭前轮流说出感恩之事,是其概括。"},{"q":"Why does Hugo feel a little nervous?","answer":"B","options":["He dislikes turkey and pie.","It is his first Thanksgiving dinner.","He has lost Tony''s address.","He has to cook the whole meal."],"explanation":"原文说他从没参加过感恩节晚餐,是转述。"}]'::jsonb, '[{"word":"occasion","cn":"场合"},{"word":"host","cn":"主人"},{"word":"guest","cn":"客人"}]'::jsonb, 2, 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Spring Festival Goes Global', 'More and more countries around the world are now holding celebrations for the Chinese Spring Festival. These events are enjoyed not only by Chinese people living overseas, but also by people of many other nationalities. With colourful decorations of lanterns and lamps, shopping centres in many cities organise activities to mark the festival, while concerts prove a great success. Tickets for one grand New Year concert in St Petersburg sold out, and most of the audience were local Russians. People are also discovering the fun of joining in, rather than simply watching. To celebrate one recent festival, over a thousand school students in Ghana got up on stage to perform Chinese songs and dances. In New York City, students have even been able to enjoy an official day off for the festival. It seems clear that the Spring Festival is fast becoming a global celebration of joy and friendship that crosses borders.', '说明·春节走向世界', 152, '[{"q":"Who enjoys the overseas Spring Festival events?","answer":"C","options":["Only Chinese citizens living in China.","Only government officials and editors.","Both Chinese people abroad and people of other nationalities.","Only retired teachers and their students."],"explanation":"原文说不仅海外华人、也有许多其他国籍的人,是转述。"},{"q":"What was special about the concert in St Petersburg?","answer":"D","options":["It was performed only by Chinese singers.","Nobody bought any of the tickets.","It was held in a small village hall.","Most of its audience were local Russians."],"explanation":"原文说门票售罄、九成观众是当地俄罗斯人,是其概括。"},{"q":"What does the passage suggest about the festival?","answer":"A","options":["It is turning into a worldwide celebration of joy.","It is slowly being forgotten abroad.","It is celebrated only by watching, never joining.","It can be held only in shopping centres."],"explanation":"末句说春节正迅速成为全球性的欢乐庆典,是转述。"}]'::jsonb, '[{"word":"overseas","cn":"在海外"},{"word":"nationality","cn":"国籍"},{"word":"global","cn":"全球的"}]'::jsonb, 2, 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'The Festival that Honours a Poet', 'The Dragon Boat Festival falls on the fifth day of the fifth lunar month. Unlike many holidays, it is held to honour a person: Qu Yuan, a great poet who lived more than two thousand years ago. He loved his country deeply, and when it was in danger, he was so sad that he drowned himself in a river. Local people rushed out in their boats to search for him, beating drums and throwing rice into the water so that the fish would not harm his body. Today, these old actions have grown into the festival''s main customs. People race long, narrow dragon boats, with a drummer beating time at the front. They also eat zongzi, sticky rice wrapped in leaves. Through these activities, families remember the poet and pass his story on to their children. The festival shows how a celebration can keep the memory of one good person alive for centuries.', '说明·端午纪念诗人', 153, '[{"q":"Why is the Dragon Boat Festival different from many holidays?","answer":"B","options":["It has no special food at all.","It is held to remember one particular person.","It is celebrated only at night.","It lasts for a whole month."],"explanation":"原文说它不同于许多节日,是为纪念屈原一人而设,是转述。"},{"q":"Why did people throw rice into the river long ago?","answer":"C","options":["Because they had too much rice to eat.","To make the river water taste better.","To stop the fish from harming his body.","To start a boat race for fun."],"explanation":"原文说投米是为了让鱼不伤害他的身体,是其概括。"},{"q":"What does the festival show, according to the passage?","answer":"D","options":["Old customs are no longer worth keeping.","Boat races are dangerous and should stop.","Poems are too hard for children to learn.","A celebration can keep a good person''s memory alive for ages."],"explanation":"末句说庆典能让一个好人的记忆延续数百年,是转述。"}]'::jsonb, '[{"word":"honour","cn":"纪念;敬重"},{"word":"poet","cn":"诗人"},{"word":"dragon","cn":"龙"}]'::jsonb, 2, 'required2', 'U2', 'fltrp');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='fltrp' AND volume='required2' AND unit='U2';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U2', 'A Surprise Birthday Party', 'Last Saturday we planned a surprise party for my best friend Mia. We wanted to (1)____ her birthday in a special way. In the afternoon, we (2)____ the living room with balloons and bright paper flowers. My brother hid the cake in the kitchen so that Mia would not (3)____ it. At six o''clock, we turned off the lights and waited (4)____. When she opened the door, we all shouted, and the look of (5)____ on her face was wonderful. She said she had never expected such a warm (6)____. We sang together, and then everyone (7)____ a small gift in front of her. Mia was so happy that she almost (8)____. Later we played games and guessed funny (9)____ written on cards. It was a night full of (10)____, and none of us wanted it to end.', 138, 2, '[{"q":"1","answer":"A","options":["celebrate","sell","repair","count"],"explanation":"celebrate her birthday 庆祝生日。"},{"q":"2","answer":"B","options":["washed","decorated","sold","counted"],"explanation":"decorated the room with balloons 用气球布置房间。"},{"q":"3","answer":"C","options":["drink","sell","find","drive"],"explanation":"so that she would not find it 以免她发现。"},{"q":"4","answer":"D","options":["loudly","sadly","hungrily","quietly"],"explanation":"是惊喜,所以安静地等待 quietly。"},{"q":"5","answer":"A","options":["surprise","anger","fear","boredom"],"explanation":"脸上是惊喜的表情 the look of surprise。"},{"q":"6","answer":"B","options":["warning","welcome","loss","defeat"],"explanation":"such a warm welcome 如此热情的欢迎。"},{"q":"7","answer":"C","options":["threw","broke","placed","burnt"],"explanation":"placed a gift in front of her 把礼物放在她面前。"},{"q":"8","answer":"D","options":["slept","left","complained","cried"],"explanation":"so happy that she almost cried 高兴得几乎哭出来。"},{"q":"9","answer":"A","options":["riddles","prices","tickets","plates"],"explanation":"guessed funny riddles 猜有趣的谜语。"},{"q":"10","answer":"B","options":["fear","joy","anger","silence"],"explanation":"a night full of joy 充满欢乐的夜晚。"}]'::jsonb, 1, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U2', 'Making a Paper Lantern', 'During the festival season, my grandmother taught me how to make a paper (1)____ at home. First, we chose a sheet of bright red (2)____, because red is the colour of good luck. She showed me how to (3)____ the paper neatly in half and cut thin lines along one side. Then we (4)____ the two ends together to form a round shape. We added a handle made of (5)____ so that it could be carried easily. Grandmother told me to work (6)____, or the thin paper would tear. When it was (7)____, we placed a small light inside, and the whole lantern began to (8)____ softly. I felt very (9)____ of the bright little lamp I had made with my own hands. That evening, we hung it by the (10)____ for everyone passing by to enjoy.', 137, 2, '[{"q":"1","answer":"C","options":["dragon","poet","lantern","harvest"],"explanation":"make a paper lantern 做纸灯笼。"},{"q":"2","answer":"D","options":["water","bread","glass","paper"],"explanation":"a sheet of red paper 一张红纸。"},{"q":"3","answer":"A","options":["fold","drink","drive","sing"],"explanation":"fold the paper in half 把纸对折。"},{"q":"4","answer":"B","options":["dropped","joined","sold","washed"],"explanation":"joined the two ends together 把两端接在一起。"},{"q":"5","answer":"C","options":["sugar","ice","string","mud"],"explanation":"a handle made of string 用绳子做的提手。"},{"q":"6","answer":"D","options":["loudly","angrily","sleepily","carefully"],"explanation":"薄纸易破,要小心地做 carefully。"},{"q":"7","answer":"A","options":["finished","broken","empty","wet"],"explanation":"when it was finished 做好之后。"},{"q":"8","answer":"B","options":["fall","glow","melt","shout"],"explanation":"the lantern began to glow 灯笼开始发光。"},{"q":"9","answer":"C","options":["afraid","bored","proud","angry"],"explanation":"proud of the lamp I made 为自己做的灯感到自豪。"},{"q":"10","answer":"D","options":["river","forest","ocean","window"],"explanation":"hung it by the window 把它挂在窗边。"}]'::jsonb, 2, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U2', 'The Mid-Autumn Festival', 'The Mid-Autumn Festival is one of the most loved (1)____ in China. It is held in the eighth lunar month, when the moon is at its (2)____ and roundest. On this night, families gather outdoors to (3)____ the bright full moon together. The round shape of the moon stands for (4)____, so being with family really matters. The special food of the festival is the (5)____, a small round cake filled with sweet paste. People often (6)____ mooncakes to friends and relatives as gifts. Long ago, farmers also used this time to celebrate the autumn (7)____, giving thanks for a good year. Children love to listen to old (8)____ about a lady who flew to the moon. Today, even Chinese people living (9)____ look up at the same moon and think of home. The festival fills people''s hearts with warmth and (10)____.', 142, 2, '[{"q":"1","answer":"A","options":["festivals","machines","deserts","sports"],"explanation":"one of the most loved festivals 最受喜爱的节日之一。"},{"q":"2","answer":"B","options":["darkest","brightest","smallest","coldest"],"explanation":"the moon is at its brightest 月亮最亮。"},{"q":"3","answer":"C","options":["drink","drive","admire","dig"],"explanation":"admire the full moon 赏月。"},{"q":"4","answer":"D","options":["danger","illness","darkness","togetherness"],"explanation":"round shape stands for togetherness 圆象征团圆。"},{"q":"5","answer":"A","options":["mooncake","lantern","envelope","riddle"],"explanation":"the special food is the mooncake 节日特色食物是月饼。"},{"q":"6","answer":"B","options":["throw","send","break","lose"],"explanation":"send mooncakes as gifts 把月饼当礼物送人。"},{"q":"7","answer":"C","options":["winter","machine","harvest","river"],"explanation":"celebrate the autumn harvest 庆祝秋收。"},{"q":"8","answer":"D","options":["prices","roofs","plates","stories"],"explanation":"old stories about a lady 关于一位仙女的古老故事。"},{"q":"9","answer":"A","options":["overseas","quietly","sadly","loudly"],"explanation":"Chinese people living overseas 居住海外的华人。"},{"q":"10","answer":"B","options":["fear","joy","silence","anger"],"explanation":"warmth and joy 温暖与欢乐。"}]'::jsonb, 3, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U2', 'The School Fancy Dress Party', 'Our class held a (1)____ dress party last Friday to celebrate the end of term. Everyone was asked to come (2)____ as a favourite character. I spent the whole evening before putting up balloons and (3)____, so by the night I felt quite tired. When the guests arrived, the classroom looked (4)____ and full of colour. One tall (5)____ came dressed as Batman, and a girl wore a beautiful bride''s dress. We could not always (6)____ who was who, which made everyone laugh. Two students dressed as chickens kept (7)____ their arms and waving at us. Our teacher, who is usually very (8)____, even wore a funny hat. We played music, danced, and shared a big (9)____ that one parent had baked. By the end of the night, everyone agreed it had been an evening full of (10)____.', 138, 2, '[{"q":"1","answer":"C","options":["lunar","polar","fancy","starving"],"explanation":"a fancy dress party 化装舞会。"},{"q":"2","answer":"D","options":["washed","sold","cooked","dressed"],"explanation":"come dressed as a character 打扮成某个角色来。"},{"q":"3","answer":"A","options":["decorations","deserts","machines","warnings"],"explanation":"balloons and decorations 气球和装饰物。"},{"q":"4","answer":"B","options":["empty","bright","dull","silent"],"explanation":"looked bright and full of colour 看上去明亮多彩。"},{"q":"5","answer":"C","options":["roof","riddle","guy","lantern"],"explanation":"one tall guy dressed as Batman 一个高个子男生扮成蝙蝠侠。"},{"q":"6","answer":"D","options":["eat","sell","build","tell"],"explanation":"could not tell who was who 分不清谁是谁。"},{"q":"7","answer":"A","options":["moving","selling","washing","cooking"],"explanation":"moving their arms and waving 摆动手臂招手。"},{"q":"8","answer":"B","options":["hungry","strict","lunar","global"],"explanation":"usually very strict 平时很严格。"},{"q":"9","answer":"C","options":["lantern","envelope","cake","riddle"],"explanation":"shared a big cake 分享一个大蛋糕。"},{"q":"10","answer":"D","options":["danger","silence","anger","laughter"],"explanation":"an evening full of laughter 充满笑声的夜晚。"}]'::jsonb, 4, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U2', 'Fireworks on New Year''s Eve', 'On New Year''s (1)____, my family always goes down to the river to watch the fireworks. We arrive early to find a good (2)____ near the water. As the night grows dark, the crowd by the bank gets (3)____ and more excited. Just before midnight, everyone counts down (4)____ together. Then the first firework shoots up and (5)____ into a thousand points of light. The colours are so (6)____ that the whole sky seems to come alive. Children point upwards and (7)____ with delight, while parents lift the smallest ones onto their shoulders. The light shines on the water, so it looks as if the river is (8)____, too. When the show finally (9)____, we walk home slowly, still talking about the most beautiful moment. For me, those few minutes by the river are the best (10)____ of the whole year.', 141, 2, '[{"q":"1","answer":"A","options":["Eve","river","roof","plate"],"explanation":"New Year''s Eve 除夕。"},{"q":"2","answer":"B","options":["price","spot","warning","loss"],"explanation":"find a good spot 找个好位置。"},{"q":"3","answer":"C","options":["smaller","quieter","larger","colder"],"explanation":"the crowd gets larger 人群越来越多。"},{"q":"4","answer":"D","options":["sadly","secretly","nervously","loudly"],"explanation":"counts down loudly 大声倒数。"},{"q":"5","answer":"A","options":["bursts","sleeps","sells","melts"],"explanation":"shoots up and bursts into light 升空后炸开成光点。"},{"q":"6","answer":"B","options":["dull","bright","dark","grey"],"explanation":"the colours are so bright 颜色如此鲜艳。"},{"q":"7","answer":"C","options":["sleep","complain","cheer","leave"],"explanation":"point upwards and cheer 指着上方欢呼。"},{"q":"8","answer":"D","options":["sleeping","falling","freezing","shining"],"explanation":"the river is shining 河面也在闪光。"},{"q":"9","answer":"A","options":["ends","begins","rains","snows"],"explanation":"when the show finally ends 表演终于结束时。"},{"q":"10","answer":"B","options":["prices","moments","warnings","losses"],"explanation":"the best moments of the year 一年里最美的时刻。"}]'::jsonb, 5, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U2', 'Creating a Special Day', 'Have you ever wondered why people (1)____ special days like World Smile Day? Such days are not old traditions; they are (2)____ by ordinary people who want to share a good idea. World Smile Day, for example, (3)____ people to be kind and to pass a smile on to others. The idea is (4)____: one friendly smile can brighten a stranger''s whole day. On this day, some schools ask students to do one kind (5)____ for someone else, such as helping a classmate. Shops may give away free badges with a smiling (6)____ on them. The day does not cost much, yet it can (7)____ a lot of warmth among people. Our class once decided to (8)____ our own special day, which we called Thank-You Day. Everyone wrote a short note to someone they were (9)____ to. By the end, the whole school was full of (10)____ faces.', 148, 2, '[{"q":"1","answer":"C","options":["sell","break","create","count"],"explanation":"why people create special days 人们为何创立特别的日子。"},{"q":"2","answer":"D","options":["washed","sold","eaten","invented"],"explanation":"they are invented by ordinary people 由普通人发明。"},{"q":"3","answer":"A","options":["encourages","sells","breaks","counts"],"explanation":"the day encourages people to be kind 鼓励人们友善。"},{"q":"4","answer":"B","options":["heavy","simple","wet","loud"],"explanation":"the idea is simple 这个想法很简单。"},{"q":"5","answer":"C","options":["price","roof","act","plate"],"explanation":"do one kind act 做一件善事。"},{"q":"6","answer":"D","options":["river","machine","desert","face"],"explanation":"a smiling face 一张微笑的脸。"},{"q":"7","answer":"A","options":["bring","sell","break","lose"],"explanation":"it can bring warmth 能带来温暖。"},{"q":"8","answer":"B","options":["throw","create","drive","wash"],"explanation":"decided to create our own day 决定创立自己的节日。"},{"q":"9","answer":"C","options":["angry","cruel","grateful","afraid"],"explanation":"someone they were grateful to 他们感激的人。"},{"q":"10","answer":"D","options":["crying","sleeping","empty","smiling"],"explanation":"full of smiling faces 满是笑脸。"}]'::jsonb, 6, 'fltrp');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='required2' AND unit='U2';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U2 听力·对话 A Wedding Invitation', '外研社版必修第二册 U2 · dialogue', 3, 'Mia: Hi, David. I have some exciting news. My sister is getting married next month.
David: Congratulations! That''s wonderful.
Mia: Thank you. We''d like to invite you to the wedding. A formal invitation will come by post.
David: I''d be honoured to come. When and where is it?
Mia: It''s on the second Saturday in June, at the Garden Hotel.
David: Lovely. Is there anything special I should wear?
Mia: It''s quite a formal occasion, so please wear a suit.
David: Of course. Should I bring a gift?
Mia: A small present is always welcome, but your good wishes matter most.
David: I''ll be there for sure. Please pass on my best wishes to your sister.', 'Mia 告诉 David 她姐姐下个月结婚,想邀请他参加婚礼,正式请柬会邮寄过去;婚礼在六月第二个星期六、花园酒店;这是正式场合,请穿西装;送小礼物当然好,但最重要的是祝福;David 一定会到,并请代向她姐姐致意。', 'uk_female', '[{"q":"What is Mia''s exciting news?","type":"choice","answer":"A","options":["Her sister is getting married.","She has won a competition.","She is moving overseas.","She has bought a new house."]},{"q":"How will the invitation be sent?","type":"choice","answer":"B","options":["By phone call.","By post.","Through a friend.","On the day itself."]},{"q":"When is the wedding?","type":"choice","answer":"A","options":["The second Saturday in June.","The first Sunday in July.","The last Friday in May.","New Year''s Eve."]},{"q":"What does Mia ask David to wear?","type":"choice","answer":"B","options":["A fancy costume.","A suit.","Something warm.","A school uniform."]},{"q":"What does Mia say matters most?","type":"choice","answer":"C","options":["An expensive gift.","Arriving very early.","David''s good wishes.","Bringing flowers."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U2 听力·独白 Red Envelopes', '外研社版必修第二册 U2 · passage', 2, 'During the Spring Festival, one of the customs children love most is receiving red envelopes. These small red packets hold some money inside and are given by adults to younger family members. The red colour is a sign of good luck, and the money is meant to bring a safe and happy year. Children usually say a few kind words of thanks before taking the envelope with both hands. In the past, the money was wrapped in red paper, but today many people send the gift on their phones instead. Whatever the form, the warm wish behind it stays the same.', '春节期间,孩子们最喜欢的习俗之一就是收红包。这些红色小包里装着钱,由大人给晚辈。红色象征好运,钱意在带来平安幸福的一年。孩子通常会先说几句感谢的话,再用双手接过红包。过去钱用红纸包好,如今许多人改用手机发送,但背后温暖的祝愿始终不变。', 'uk_female', '[{"q":"Who gives red envelopes to whom?","type":"choice","answer":"D","options":["Children give them to teachers.","Shops give them to customers.","Guests give them to the host.","Adults give them to younger family members."]},{"q":"What is inside a red envelope?","type":"choice","answer":"A","options":["Some money.","A handwritten letter.","A small toy.","A lantern riddle."]},{"q":"What does the red colour stand for?","type":"choice","answer":"B","options":["Hard work.","Good luck.","A warning.","A loss."]},{"q":"What do children do before taking the envelope?","type":"choice","answer":"C","options":["Open it at once to count the money.","Throw it back politely.","Say a few words of thanks and use both hands.","Hide it from the adults."]},{"q":"How do many people send the gift today?","type":"choice","answer":"D","options":["By train.","Through the school.","By drawing it on paper.","On their phones."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U2 听力·对话 Watching the New Year Parade', '外研社版必修第二册 U2 · dialogue', 3, 'Leo: Are you going to watch the New Year parade tomorrow, Emma?
Emma: I''d like to, but I don''t know where the best place to stand is.
Leo: The main street near the square is perfect. The dragon dance passes right there.
Emma: A dragon dance? That sounds exciting. How early should we get there?
Leo: Quite early. The parade attracts huge crowds, so good spots fill up fast.
Emma: All right. Shall we meet at nine outside the bookshop?
Leo: Nine is fine. Wear something warm — we''ll be standing for a while.
Emma: Good point. Will there be music too?
Leo: Yes, drums and gongs all the way. The audience always joins in.
Emma: I can''t wait. See you at nine.', 'Leo 问 Emma 明天去不去看新年巡游;Emma 想去但不知最佳观看点;Leo 说广场旁的大街最好,舞龙正好经过那里;要早点去,因为巡游吸引大批人群,好位置很快被占;两人约九点在书店外见面;Leo 提醒穿暖和点,要站很久;一路上有锣鼓,观众也会一起参与;Emma 很期待。', 'uk_female', '[{"q":"What are Leo and Emma going to watch?","type":"choice","answer":"A","options":["The New Year parade.","A football game.","A fireworks show by the river.","A book fair."]},{"q":"Where is the best place to stand?","type":"choice","answer":"B","options":["Outside Emma''s home.","The main street near the square.","On the school playground.","Beside the river bank."]},{"q":"Why should they get there early?","type":"choice","answer":"C","options":["The parade ends very early.","The bookshop closes at nine.","Huge crowds fill the good spots fast.","It is going to rain."]},{"q":"Where will they meet?","type":"choice","answer":"D","options":["At the square gate.","By the river.","At the Garden Hotel.","Outside the bookshop."]},{"q":"What does Leo tell Emma to wear?","type":"choice","answer":"A","options":["Something warm.","A bride''s dress.","A Batman costume.","A school uniform."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U2 听力·独白 World Book Day', '外研社版必修第二册 U2 · passage', 2, 'World Book Day is celebrated in many countries every April. It is a fairly new day, created to help people of all ages enjoy reading. On this day, schools hold all kinds of activities. Children sometimes dress up as their favourite characters from books, and teachers read stories aloud to the class. Some shops give away free books or sell them at a lower price. The aim is simple: to show how much joy a good book can bring. Through these activities, more young people slowly learn to love reading.', '世界读书日每年四月在许多国家庆祝。这是一个相当新的节日,创立的目的是帮助各年龄段的人享受阅读。这一天,学校会举办各种活动:孩子们有时打扮成书中喜爱的人物,老师给全班朗读故事;有些商店免费赠书或低价出售。其目的很简单——展示一本好书能带来多少欢乐。通过这些活动,越来越多的年轻人渐渐爱上阅读。', 'uk_female', '[{"q":"When is World Book Day celebrated?","type":"choice","answer":"B","options":["Every December.","Every April.","On New Year''s Eve.","In the eighth lunar month."]},{"q":"Why was the day created?","type":"choice","answer":"C","options":["To sell more lanterns.","To honour an old poet.","To help people enjoy reading.","To welcome the autumn harvest."]},{"q":"What do children sometimes do at school that day?","type":"choice","answer":"D","options":["Race dragon boats.","Set off fireworks.","Make mooncakes.","Dress up as characters from books."]},{"q":"What do some shops do?","type":"choice","answer":"A","options":["Give away free books or lower the price.","Close for the whole day.","Hand out red envelopes.","Sell tickets to a concert."]},{"q":"What is the simple aim of the day?","type":"choice","answer":"B","options":["To raise money for schools.","To show the joy a good book can bring.","To test students'' reading speed.","To choose the best writer."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U2 听力·对话 A Retirement Party for Mr Lee', '外研社版必修第二册 U2 · dialogue', 3, 'Sara: Our teacher Mr Lee is retiring at the end of term. We should do something for him.
Tom: Good idea. Why don''t we hold a small party in the classroom?
Sara: Perfect. We can decorate the room and prepare a card for everyone to sign.
Tom: What about a gift? He has taught us for three years.
Sara: I was thinking of a book of poetry. He loves reading.
Tom: He''ll like that. Should we also order a cake?
Sara: Yes, a small one. And we can ask a few parents to help.
Tom: Great. When shall we have it?
Sara: On the last Friday afternoon, after the final lesson.
Tom: I''ll tell the others. It''ll be a lovely surprise for him.', 'Sara 说 Lee 老师学期末就要退休,大家该为他做点什么;Tom 提议在教室办个小派对;Sara 同意,可以布置教室、准备一张卡片让大家签名;说到礼物,Lee 老师教了他们三年;Sara 想送一本诗集,因为他爱读书;Tom 觉得好,还可订个小蛋糕,并请几位家长帮忙;派对定在最后一个周五下午、最后一节课后;Tom 去通知其他人,这会是给老师的惊喜。', 'uk_female', '[{"q":"Why are Sara and Tom planning a party?","type":"choice","answer":"C","options":["It is Tom''s birthday.","The term has just started.","Their teacher Mr Lee is retiring.","They won a competition."]},{"q":"Where will they hold the party?","type":"choice","answer":"D","options":["At a restaurant.","In the school hall.","By the river.","In the classroom."]},{"q":"What gift does Sara suggest?","type":"choice","answer":"A","options":["A book of poetry.","A red lantern.","A football.","A box of mooncakes."]},{"q":"When will they have the party?","type":"choice","answer":"B","options":["On the first Monday morning.","On the last Friday afternoon.","On New Year''s Eve.","During the lunch break."]},{"q":"What does Tom say the party will be for Mr Lee?","type":"choice","answer":"C","options":["A hard test.","A boring meeting.","A lovely surprise.","A long lecture."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U2', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U2 听力·独白 A Leavers'' Celebration', '外研社版必修第二册 U2 · passage', 2, 'At the end of their last school year, students in many countries hold a leavers'' celebration to mark the moment. It is both a happy and a slightly sad occasion, because friends who have studied together for years are about to go their own ways. Teachers often give short speeches, and students share photos and write kind messages in each other''s books. Some schools hold a small concert, where an audience of parents and teachers watches the leavers sing and dance. The celebration is a way of saying thank you for the past and good luck for the future.', '在最后一个学年结束时,许多国家的学生会举办毕业告别会来纪念这一刻。这是一个既快乐又略带伤感的场合,因为一起学习多年的朋友即将各奔东西。老师常发表简短讲话,学生们互相分享照片、在彼此的本子上写下友善的留言。有些学校会办一场小型音乐会,由家长和老师组成的观众观看毕业生唱歌跳舞。这场庆祝是为了感谢过去、祝福未来。', 'uk_female', '[{"q":"When do students hold a leavers'' celebration?","type":"choice","answer":"D","options":["On the first day of school.","In the middle of summer holidays.","On the eve of the Spring Festival.","At the end of their last school year."]},{"q":"Why is the occasion slightly sad?","type":"choice","answer":"A","options":["Friends are about to go their own ways.","The food is never enough.","The speeches are too long.","It always rains that day."]},{"q":"What do teachers often do?","type":"choice","answer":"B","options":["Race dragon boats.","Give short speeches.","Hand out red envelopes.","Sell books at a lower price."]},{"q":"Who watches the small concert?","type":"choice","answer":"C","options":["Only the school cooks.","Visitors from overseas.","An audience of parents and teachers.","The traffic police."]},{"q":"What is the celebration a way of doing?","type":"choice","answer":"D","options":["Choosing the best student in the school.","Raising money for new books.","Testing the students one last time.","Saying thank you for the past and good luck for the future."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U2', 'fltrp');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='required2' AND unit='U2';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (10, 'Describe a Chinese Festival to a Foreign Friend(向外国朋友介绍一个中国节日)', 'My Favourite Chinese Festival', '假设你叫李华,你的英国笔友 Jack 想了解中国的节日。请用英语写一篇约80词的短文,介绍一个你最喜欢的中国节日,内容包括:① 这个节日在什么时候、为什么庆祝;② 人们会做哪些活动(如装饰、吃特色食物、参加庆祝);③ 这个节日对你和家人意味着什么。注意:行文连贯、句句围绕节日。', 'Suppose you are Li Hua. Your British pen-friend Jack wants to learn about Chinese festivals. Write a short passage (about 80 words) introducing your favourite Chinese festival, including: 1) when and why it is celebrated; 2) what people do (e.g. decorating, eating special food, joining celebrations); 3) what the festival means to you and your family.', '["点明节日名称与时间(My favourite festival is … / It falls on …)","介绍活动与特色食物(People decorate … / We eat … / Families gather to …)","说明意义/感受(To me, it means … / It brings my family joy)","句句围绕节日、连贯有条理"]'::jsonb, 70, 100, 'Hi Jack! My favourite Chinese festival is the Lantern Festival. It falls on the fifteenth day of the first lunar month and marks the end of the Spring Festival season. On that evening, people decorate the streets with red lanterns, and families go out to enjoy the lights together. We love guessing the riddles written on the lanterns, and we always eat sweet rice balls, a special dessert. To me, the festival is not only about the bright lanterns, but also about the joy of being with my family. I hope you can join us one day!', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["My favourite Chinese festival is the Lantern Festival.","It falls on the fifteenth day of the first lunar month and marks the end of the Spring Festival season.","We love guessing the riddles written on the lanterns.","To me, the festival is about the joy of being with my family."]'::jsonb, '[{"wrong":"The festival is on fifteenth day of first lunar month.","correct":"The festival falls on the fifteenth day of the first lunar month.","note":"序数词前加 the;表示节日在某天用 fall on。"},{"wrong":"People decorate the streets with red lantern.","correct":"People decorate the streets with red lanterns.","note":"lantern 可数,复数加 s。"},{"wrong":"We celebrate to be with family.","correct":"We celebrate the festival to be with family.","note":"celebrate 是及物动词,后面要接宾语。"}]'::jsonb, '【介绍节日结构】
第1句 点题:My favourite Chinese festival is …
第2句 时间/原因:It falls on … and marks …
第3-4句 活动/食物:People decorate … We eat …
第5句 意义:To me, the festival is about …', 2, 'required2', 'U2', 'fltrp');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='required2' AND unit='U2';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (10, 'required2', 'U2', '{"title":"情态动词·对过去的推测(must / may / might / could / can''t + have done)速查","intro":"推测「过去」发生过的事,统一用「情态动词 + have + 过去分词」。关键看证据有多强:几乎确定→must;只是可能→may/might/could;几乎不可能→can''t/couldn''t。注意:这是对过去的推测,绝不是 must do / may be 那种现在式。","table":{"headers":["确定程度","结构 / 例句"],"rows":[["几乎确定(肯定)","must have done:The children must have been very excited.(孩子们一定很激动。)"],["也许(可能)","may / might / could have done:He might have missed the invitation.(他也许没看到邀请。)"],["几乎不可能(否定)","can''t / couldn''t have done:She can''t have been at the fair then.(她那时不可能在灯会。)"]]},"specialRules":[{"rule":"肯定推测过去用 must have done,不用 may have done(那是「也许」)","mark":"证据确凿→must have done"},{"rule":"否定推测过去用 can''t/couldn''t have done,不能用 mustn''t have done","mark":"mustn''t 表「禁止」,不表「不可能」"},{"rule":"could have done = 可能做过(推测);区别于 could do(过去能力/委婉)","mark":"看上下文是推测还是能力"},{"rule":"推测的是过去,动词一定是 have + 过去分词,不是原形或现在式","mark":"must have gone √ / must go ×"}],"why":["have done 表示动作已经发生在过去;前面的情态动词只负责表达说话人「有多确定」。证据越强→词越肯定(must),证据越弱→词越松(might),证据相反→否定(can''t)。"],"gaokaoPoints":["看句中证据(看得见的结果、时间地点能力)选 must / might / can''t,语法填空与改错高频。","易混:对现在的推测用 must be / may be(无 have);对过去的推测才用 must have been / may have been。"],"examVsReal":[{"exam":"He must have left already.(考试:对过去的肯定推测)","real":"He''s definitely gone already.","note":"口语常用 definitely/probably 直接表达确定程度"},{"exam":"She can''t have seen it.(考试:对过去的否定推测)","real":"There''s no way she saw it.","note":"口语常说 there''s no way 表示「绝不可能」"}]}'::jsonb, 'fltrp');

COMMIT;

-- ===== 自带校验(publisher='fltrp') =====
SELECT 'vocab' k, count(*) v, 50 expect FROM public.junior_vocab WHERE publisher='fltrp' AND volume='required2' AND unit='U2'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required2' AND unit='U2')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='fltrp' AND volume='required2' AND unit='U2'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='fltrp' AND volume='required2' AND unit='U2'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='required2' AND unit='U2'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='required2' AND unit='U2'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='required2' AND unit='U2' ORDER BY k;
