-- ============================================================
-- 外研社(fltrp) 必修一 U3(The World of Science)灌库(junior_* 表,publisher='fltrp' volume='required3' unit='U3' grade=10)。幂等。
-- ★DELETE 全带 publisher='fltrp',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 48 =====
DELETE FROM public.junior_vocab WHERE publisher='fltrp' AND volume='required3' AND unit='U3';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'press', 'v.', '/pres/', '按;压', 'You only need to press a button to start the machine.', '你只需按一个按钮就能启动机器。', 'The World of Science', 1, 0, 'senior', 'wordlist', 'required3', 'U3', 'press a button', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'shoot', 'v.', '/ʃuːt/', '射出(光线等);放射', 'The new laser can shoot a thin beam of light at the target.', '这种新激光能向目标射出一束细光。', 'The World of Science', 2, 0, 'senior', 'wordlist', 'required3', 'U3', 'shoot out', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'gunpowder', 'n.', '/ˈɡʌnˌpaʊdə/', '火药', 'Gunpowder was one of the four great inventions of ancient China.', '火药是中国古代四大发明之一。', 'The World of Science', 3, 0, 'senior', 'wordlist', 'required3', 'U3', 'the invention of gunpowder', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'compass', 'n.', '/ˈkʌmpəs/', '指南针;罗盘', 'Sailors used a compass to find their way far out at sea.', '水手用指南针在远海中辨别方向。', 'The World of Science', 4, 0, 'senior', 'wordlist', 'required3', 'U3', 'use a compass', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'virtual', 'adj.', '/ˈvɜːtʃuəl/', '虚拟的;模拟的', 'Many games now create a virtual world that looks almost real.', '如今许多游戏创造出几乎逼真的虚拟世界。', 'The World of Science', 5, 0, 'senior', 'wordlist', 'required3', 'U3', 'virtual reality', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'virtual reality', 'n.', '/ˌvɜːtʃuəl riˈæləti/', '虚拟现实', 'Virtual reality has been used to train new doctors safely.', '虚拟现实已被用来安全地培训新医生。', 'The World of Science', 6, 0, 'senior', 'wordlist', 'required3', 'U3', 'virtual reality', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'wearable tech', 'n.', '/ˈweərəbl tek/', '可穿戴技术', 'Wearable tech such as smart watches has become very popular.', '智能手表等可穿戴技术已变得非常流行。', 'The World of Science', 7, 0, 'senior', 'wordlist', 'required3', 'U3', 'wearable tech', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'flexible', 'adj.', '/ˈfleksɪbl/', '易弯曲的;柔韧的', 'The new battery is thin and flexible, so it can bend easily.', '这种新电池又薄又柔韧,可以轻松弯曲。', 'The World of Science', 8, 0, 'senior', 'wordlist', 'required3', 'U3', 'a flexible battery', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'battery', 'n.', '/ˈbætri/', '电池', 'A flexible battery can power a wearable device for days.', '一块柔性电池可以为可穿戴设备供电数天。', 'The World of Science', 9, 0, 'senior', 'wordlist', 'required3', 'U3', 'a flexible battery', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'in addition', 'phr.', '/ɪn əˈdɪʃn/', '除此之外;另外', 'In addition, important advances have been made in medicine.', '除此之外,医学上也取得了重要进展。', 'The World of Science', 10, 0, 'senior', 'wordlist', 'required3', 'U3', 'in addition', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'compute', 'v.', '/kəmˈpjuːt/', '计算', 'Powerful computers can compute millions of numbers each second.', '强大的计算机每秒能计算数百万个数字。', 'The World of Science', 11, 0, 'senior', 'wordlist', 'required3', 'U3', 'compute the result', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'capable', 'adj.', '/ˈkeɪpəbl/', '有能力的', 'The walking house is capable of moving to a safer place by itself.', '这座会走的房子能自行移动到更安全的地方。', 'The World of Science', 12, 0, 'senior', 'wordlist', 'required3', 'U3', 'be capable of', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'stuff', 'n.', '/stʌf/', '东西;物品', 'Impressive stuff like this has been made by a big team.', '这样令人惊叹的东西是由一个大团队制造的。', 'The World of Science', 13, 0, 'senior', 'wordlist', 'required3', 'U3', 'impressive stuff', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'desire', 'n.', '/dɪˈzaɪə/', '渴望;欲望', 'The desire to create new things drives every great inventor.', '创造新事物的渴望驱动着每一位伟大的发明家。', 'The World of Science', 14, 0, 'senior', 'wordlist', 'required3', 'U3', 'the desire to create', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'passive', 'adj.', '/ˈpæsɪv/', '被动的', 'In a passive sentence, the action is done to the subject.', '在被动句中,动作是施加在主语身上的。', 'The World of Science', 15, 0, 'senior', 'wordlist', 'required3', 'U3', 'the passive form', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'beyond', 'prep.', '/bɪˈjɒnd/', '无法……;超出;在……那边', 'Our lives may be changed beyond recognition by new technology.', '新技术可能把我们的生活改变得面目全非。', 'The World of Science', 16, 0, 'senior', 'wordlist', 'required3', 'U3', 'beyond recognition', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'instance', 'n.', '/ˈɪnstəns/', '例子;实例', 'For instance, some restaurants have served 3D-printed food.', '例如,有些餐馆已供应过3D打印的食物。', 'The World of Science', 17, 0, 'senior', 'wordlist', 'required3', 'U3', 'for instance', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'significant', 'adj.', '/sɪɡˈnɪfɪkənt/', '重要的;影响深远的', 'Significant advances have been made in solar technology.', '太阳能技术取得了重大进步。', 'The World of Science', 18, 0, 'senior', 'wordlist', 'required3', 'U3', 'a significant advance', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'injure', 'v.', '/ˈɪndʒə/', '使受伤;弄伤', 'A turtle that had been injured in a fire was given a new shell.', '一只在火灾中受伤的乌龟得到了一个新壳。', 'The World of Science', 19, 0, 'senior', 'wordlist', 'required3', 'U3', 'be injured in a fire', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'chemist', 'n.', '/ˈkemɪst/', '化学家', 'A chemist studies what different materials are made of.', '化学家研究各种材料的构成。', 'The World of Science', 20, 0, 'senior', 'wordlist', 'required3', 'U3', 'a famous chemist', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'astronomer', 'n.', '/əˈstrɒnəmə/', '天文学家', 'An astronomer studies the stars, planets and other objects in space.', '天文学家研究恒星、行星等太空中的天体。', 'The World of Science', 21, 0, 'senior', 'wordlist', 'required3', 'U3', 'a young astronomer', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'biologist', 'n.', '/baɪˈɒlədʒɪst/', '生物学家', 'A biologist studies living things such as plants and animals.', '生物学家研究植物和动物等生物。', 'The World of Science', 22, 0, 'senior', 'wordlist', 'required3', 'U3', 'a leading biologist', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'accurate', 'adj.', '/ˈækjʊrət/', '精确的;准确的', 'The old calendar was almost as accurate as the modern one.', '这部古老的历法几乎和现代历法一样精确。', 'The World of Science', 23, 0, 'senior', 'wordlist', 'required3', 'U3', 'an accurate calendar', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'minor', 'adj.', '/ˈmaɪnə/', '小的;次要的', 'A minor planet was named after the great scientist.', '一颗小行星以这位伟大科学家的名字命名。', 'The World of Science', 24, 0, 'senior', 'wordlist', 'required3', 'U3', 'a minor planet', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'origin', 'n.', '/ˈɒrɪdʒɪn/', '起源;起因', 'Darwin''s famous book explains the origin of different species.', '达尔文的名著解释了不同物种的起源。', 'The World of Science', 25, 0, 'senior', 'wordlist', 'required3', 'U3', 'the origin of species', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'species', 'n.', '/ˈspiːʃiːz/', '物种', 'Many species change very slowly over a long time.', '许多物种在漫长的时间里非常缓慢地变化。', 'The World of Science', 26, 0, 'senior', 'wordlist', 'required3', 'U3', 'a new species', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'stream', 'n.', '/striːm/', '小河;小溪', 'The scientist studied more than a thousand rivers and streams.', '这位科学家研究了一千多条河流和小溪。', 'The World of Science', 27, 0, 'senior', 'wordlist', 'required3', 'U3', 'rivers and streams', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'extraordinary', 'adj.', '/ɪkˈstrɔːdnri/', '非凡的;出色的', 'Marie Curie did extraordinary work and won the Nobel Prize twice.', '玛丽·居里做出了非凡的工作,两次获得诺贝尔奖。', 'The World of Science', 28, 0, 'senior', 'wordlist', 'required3', 'U3', 'extraordinary work', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'brilliant', 'adj.', '/ˈbrɪljənt/', '聪颖的;才华横溢的', 'She was regarded as a brilliant chemist by everyone in the lab.', '实验室里的每个人都把她视为一位才华横溢的化学家。', 'The World of Science', 29, 0, 'senior', 'wordlist', 'required3', 'U3', 'a brilliant mind', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'theory', 'n.', '/ˈθɪəri/', '学说;理论', 'A falling apple is said to have led Newton to his theory of gravity.', '据说一个落下的苹果让牛顿想到了万有引力理论。', 'The World of Science', 30, 0, 'senior', 'wordlist', 'required3', 'U3', 'the theory of gravity', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'mental', 'adj.', '/ˈmentl/', '精神的;心理的', 'Alzheimer''s is a common mental disease among older people.', '阿尔茨海默病是老年人中常见的一种精神疾病。', 'The World of Science', 31, 0, 'senior', 'wordlist', 'required3', 'U3', 'a mental disease', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'cure', 'n.', '/kjʊə/', '药剂;疗法', 'At present there is still no cure for this disease.', '目前这种疾病仍无治愈的方法。', 'The World of Science', 32, 0, 'senior', 'wordlist', 'required3', 'U3', 'no cure for', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'draft', 'v.', '/drɑːft/', '起草;草拟', 'Franklin helped to draft the Declaration of Independence.', '富兰克林参与起草了《独立宣言》。', 'The World of Science', 33, 0, 'senior', 'wordlist', 'required3', 'U3', 'draft a document', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'declaration', 'n.', '/ˌdekləˈreɪʃn/', '声明;宣告', 'The Declaration of Independence has been read by millions of people.', '《独立宣言》已被数百万人阅读。', 'The World of Science', 34, 0, 'senior', 'wordlist', 'required3', 'U3', 'a declaration', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'experiment', 'n.', '/ɪkˈsperɪmənt/', '(科学)实验', 'Franklin''s experiment with lightning made him famous.', '富兰克林的闪电实验使他声名远扬。', 'The World of Science', 35, 0, 'senior', 'wordlist', 'required3', 'U3', 'carry out an experiment', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'lightning', 'n.', '/ˈlaɪtnɪŋ/', '闪电', 'A flash of lightning hit the kite during the storm.', '一道闪电在暴风雨中击中了风筝。', 'The World of Science', 36, 0, 'senior', 'wordlist', 'required3', 'U3', 'a flash of lightning', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'fiction', 'n.', '/ˈfɪkʃn/', '虚构的事;小说', 'New research suggests the story may be fiction rather than fact.', '新研究表明这个故事也许是虚构而非事实。', 'The World of Science', 37, 0, 'senior', 'wordlist', 'required3', 'U3', 'fiction or fact', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'metal', 'n.', '/ˈmetl/', '金属', 'A metal key was attached to the wet string of the kite.', '一把金属钥匙被系在风筝湿润的线上。', 'The World of Science', 38, 0, 'senior', 'wordlist', 'required3', 'U3', 'a metal key', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'attach', 'v.', '/əˈtætʃ/', '系;绑;贴', 'A key was attached to the string so the electricity could pass down.', '钥匙被系在线上,这样电流就能传下来。', 'The World of Science', 39, 0, 'senior', 'wordlist', 'required3', 'U3', 'attach to', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'flash', 'n.', '/flæʃ/', '闪光', 'A bright flash of light suddenly appeared in the dark sky.', '一道亮光突然出现在黑暗的天空中。', 'The World of Science', 40, 0, 'senior', 'wordlist', 'required3', 'U3', 'a flash of light', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'conduct', 'v.', '/kənˈdʌkt/', '传导(热、电)', 'The wet string can conduct electricity from the sky to the key.', '湿绳能把电从天空传导到钥匙上。', 'The World of Science', 41, 0, 'senior', 'wordlist', 'required3', 'U3', 'conduct electricity', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'scientific', 'adj.', '/ˌsaɪənˈtɪfɪk/', '科学(上)的', 'Scientific experiments help us to find out the truth.', '科学实验帮助我们查明真相。', 'The World of Science', 42, 0, 'senior', 'wordlist', 'required3', 'U3', 'a scientific approach', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'entirely', 'adv.', '/ɪnˈtaɪəli/', '完全地;彻底地', 'Scientists found that the old story was not entirely true.', '科学家发现那个旧故事并不完全属实。', 'The World of Science', 43, 0, 'senior', 'wordlist', 'required3', 'U3', 'not entirely true', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'gravity', 'n.', '/ˈɡrævəti/', '重力;引力', 'Gravity is the force that pulls a falling apple to the ground.', '引力是把落下的苹果拉向地面的力。', 'The World of Science', 44, 0, 'senior', 'wordlist', 'required3', 'U3', 'the force of gravity', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'account', 'n.', '/əˈkaʊnt/', '记述;描述', 'More than one account of the experiment has been written.', '关于这个实验已有不止一种记述。', 'The World of Science', 45, 0, 'senior', 'wordlist', 'required3', 'U3', 'an account of', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'proof', 'n.', '/pruːf/', '证明;证据', 'There is no proof that the apple hit Newton on the head.', '没有证据表明苹果砸到了牛顿的头上。', 'The World of Science', 46, 0, 'senior', 'wordlist', 'required3', 'U3', 'no proof that', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'procedure', 'n.', '/prəˈsiːdʒə/', '程序;步骤', 'Follow each step of the procedure carefully during the experiment.', '做实验时请仔细遵循每一个步骤。', 'The World of Science', 47, 0, 'senior', 'wordlist', 'required3', 'U3', 'follow the procedure', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'natural selection', 'n.', '/ˌnætʃrəl sɪˈlekʃn/', '自然选择', 'Darwin explained how species change through natural selection.', '达尔文解释了物种如何通过自然选择而演变。', 'The World of Science', 48, 0, 'senior', 'wordlist', 'required3', 'U3', 'natural selection', NULL, 'fltrp');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3');
DELETE FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f3u3.01', '①现在完成被动语态基本形式(have/has been + 过去分词)', 'A2', 10, '外研社版必修第三册 U3 — 主语是动作的承受者、且有现在完成时间标志(recently / so far / over the past years / by + 施动者)时,用 have/has been + 过去分词。', 1, 'required3', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f3u3.02', '②现在完成被动 vs 现在完成主动(主语承受 or 发出动作)', 'A2', 10, '外研社版必修第三册 U3 — 看主语是动作的承受者还是发出者:承受者(常带 by 施动者、空后无宾语)用 have/has been done;发出者(空后跟宾语)用 have/has done。', 2, 'required3', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f3u3.03', '③现在完成被动 vs 一般现在/一般过去被动(时间标志定时态)', 'A2', 10, '外研社版必修第三册 U3 — 四个选项都是被动,但时态不同;already / so far / up to now / by now 等标志要求现在完成被动 have/has been done,而非 is/are done 或 was/were done。', 3, 'required3', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'A great many new inventions ____ by scientists over the past few years.', 'have been made', 'have made', 'are making', 'make', 'A', '主语 inventions 是动作承受者,又有 over the past few years → have been + made。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Recently, 3D printers ____ by doctors to create replacement hearts.', 'have used', 'have been used', 'are using', 'use', 'B', 'printers 被使用、有 recently → have been used。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Since 2010, several new medicines ____ by researchers for this illness.', 'have developed', 'develop', 'have been developed', 'are developing', 'C', 'medicines 被研发、since 2010 → have been developed。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'So far, an intelligent walking house ____ by a clever young team.', 'has built', 'is building', 'builds', 'has been built', 'D', 'house 被建造、so far → has been built。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Up to now, only part of the energy problem ____ by engineers.', 'has been solved', 'has solved', 'solves', 'is solving', 'A', 'problem 被解决、up to now → has been solved。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'In recent years, the flexible battery ____ greatly by engineers.', 'has improved', 'has been improved', 'improves', 'is improving', 'B', 'battery 被改进、有 by engineers 施动者 → has been improved。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Just now, a strange new instrument ____ by the inventor.', 'has designed', 'designs', 'has been designed', 'is designing', 'C', 'instrument 被设计、by the inventor → has been designed。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Over the past decade, many electric cars ____ by Chinese companies.', 'have produced', 'produce', 'are producing', 'have been produced', 'D', 'cars 被生产、over the past decade → have been produced。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Lately, a smart watch for blind people ____ by a small start-up.', 'has been created', 'has created', 'creates', 'is creating', 'A', 'watch 被创造、lately + by 短语 → has been created。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'This year, a cheaper solar panel ____ by the research centre.', 'has introduced', 'has been introduced', 'introduces', 'is introducing', 'B', 'panel 被推出、by the research centre → has been introduced。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Already, the new heart pump ____ by the hospital team.', 'has tested', 'tests', 'has been tested', 'is testing', 'C', 'pump 被测试、already + by 短语 → has been tested。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'For many years, the compass ____ by sailors all over the world.', 'has used', 'uses', 'is using', 'has been used', 'D', 'compass 被使用、for many years + by 短语 → has been used。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Since last spring, the broken robot ____ by the students.', 'has been repaired', 'has repaired', 'repairs', 'is repairing', 'A', 'robot 被修理、since last spring → has been repaired。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Recently, two damaged machines ____ by the workers.', 'have replaced', 'have been replaced', 'replace', 'are replacing', 'B', 'machines 被更换、recently + by 短语 → have been replaced。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'So far, the old experiment ____ by several scientists.', 'has examined', 'examines', 'has been examined', 'is examining', 'C', 'experiment 被检验、so far + by 短语 → has been examined。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Over the years, the inventor''s story ____ by many writers.', 'has recorded', 'records', 'is recording', 'has been recorded', 'D', 'story 被记述、over the years + by 短语 → has been recorded。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'This month, the team''s results ____ by a famous science magazine.', 'have been published', 'have published', 'publish', 'are publishing', 'A', 'results 被发表、by 短语 → have been published。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Recently, a minor planet ____ after the great scientist.', 'has named', 'has been named', 'names', 'is naming', 'B', 'planet 被命名、recently → has been named。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Up to now, thousands of stars ____ by that astronomer.', 'have studied', 'study', 'have been studied', 'are studying', 'C', 'stars 被研究、up to now + by 短语 → have been studied。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.01'), 'Since the fire, a new 3D-printed shell ____ to the injured turtle.', 'has given', 'gives', 'is giving', 'has been given', 'D', 'shell 被给予、since the fire → has been given。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'So far, many great inventions ____ by ordinary people, not just experts.', 'have been made', 'have made', 'are made', 'make', 'A', '主语 inventions 是承受者、带 by 短语 → have been made。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'So far, ordinary people ____ many great inventions, not just experts.', 'have been made', 'have made', 'are making', 'makes', 'B', '主语 people 是发出者、空后跟宾语 inventions → 主动 have made。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Recently, the old theory ____ by more than one scientist.', 'has questioned', 'is questioned', 'has been questioned', 'questions', 'C', 'theory 是承受者、带 by 短语 → has been questioned。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Recently, more than one scientist ____ the old theory.', 'has been questioned', 'is questioning', 'question', 'has questioned', 'D', 'scientist 是发出者、空后跟宾语 theory → 主动 has questioned。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Up to now, the experiment ____ by students all over the country.', 'has been repeated', 'has repeated', 'is repeated', 'repeats', 'A', 'experiment 是承受者、带 by 短语 → has been repeated。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Up to now, students all over the country ____ the experiment.', 'have been repeated', 'have repeated', 'are repeating', 'repeats', 'B', 'students 是发出者、空后跟宾语 experiment → 主动 have repeated。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'For centuries, the compass ____ by sailors crossing the sea.', 'has used', 'is used', 'has been used', 'uses', 'C', 'compass 是承受者、带 by 短语 → has been used。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'For centuries, sailors crossing the sea ____ the compass.', 'have been used', 'are using', 'uses', 'have used', 'D', 'sailors 是发出者、空后跟宾语 compass → 主动 have used。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Lately, replacement body parts ____ by clever 3D printers.', 'have been produced', 'have produced', 'are produced', 'produce', 'A', 'parts 是承受者、带 by 短语 → have been produced。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Lately, clever 3D printers ____ replacement body parts.', 'have been produced', 'have produced', 'are producing', 'produces', 'B', 'printers 是发出者、空后跟宾语 parts → 主动 have produced。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'This year, a new energy car ____ by that young engineer.', 'has designed', 'is designed', 'has been designed', 'designs', 'C', 'car 是承受者、带 by 短语 → has been designed。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'This year, that young engineer ____ a new energy car.', 'has been designed', 'is designing', 'design', 'has designed', 'D', 'engineer 是发出者、空后跟宾语 car → 主动 has designed。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Already, the patient''s heart problem ____ by the doctors.', 'has been treated', 'has treated', 'is treated', 'treats', 'A', 'problem 是承受者、带 by 短语 → has been treated。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Already, the doctors ____ the patient''s heart problem.', 'have been treated', 'have treated', 'are treating', 'treats', 'B', 'doctors 是发出者、空后跟宾语 problem → 主动 have treated。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Since then, Franklin''s story ____ by generations of children.', 'has loved', 'is loved', 'has been loved', 'loves', 'C', 'story 是承受者、带 by 短语 → has been loved。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Since then, generations of children ____ Franklin''s story.', 'have been loved', 'are loving', 'loves', 'have loved', 'D', 'children 是发出者、空后跟宾语 story → 主动 have loved。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Over time, the truth about the apple ____ by several writers.', 'has been doubted', 'has doubted', 'is doubted', 'doubts', 'A', 'truth 是承受者、带 by 短语 → has been doubted。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Over time, several writers ____ the truth about the apple.', 'have been doubted', 'have doubted', 'are doubting', 'doubts', 'B', 'writers 是发出者、空后跟宾语 truth → 主动 have doubted。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Recently, many human body parts ____ with this new technology.', 'have made', 'are made', 'have been made', 'make', 'C', 'parts 是承受者、with 表方式而非施动 → have been made。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.02'), 'Recently, this new technology ____ many human body parts.', 'has been made', 'is making', 'makes', 'has made', 'D', 'technology 是发出者、空后跟宾语 parts → 主动 has made。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'By now, the new vaccine ____ to thousands of patients.', 'has been given', 'is given', 'was given', 'will be given', 'A', 'by now 表到目前为止 → 现在完成被动 has been given。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Over the past ten years, many electric cars ____ in this city.', 'are produced', 'have been produced', 'were produced', 'will be produced', 'B', 'over the past ten years → 现在完成被动 have been produced。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'So far, the broken telescope ____ twice this year.', 'is repaired', 'was repaired', 'has been repaired', 'will be repaired', 'C', 'so far → 现在完成被动 has been repaired。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Already, the team''s results ____ in a famous journal.', 'are published', 'were published', 'will be published', 'have been published', 'D', 'already → 现在完成被动 have been published。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Up to now, the old theory ____ many times.', 'has been tested', 'is tested', 'was tested', 'will be tested', 'A', 'up to now → 现在完成被动 has been tested。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Since last year, three new instruments ____ for the lab.', 'are bought', 'have been bought', 'were bought', 'will be bought', 'B', 'since last year → 现在完成被动 have been bought。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Recently, the famous experiment ____ by several teams.', 'is copied', 'was copied', 'has been copied', 'will be copied', 'C', 'recently → 现在完成被动 has been copied。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Lately, a great deal of money ____ on medical research.', 'is spent', 'was spent', 'will be spent', 'has been spent', 'D', 'lately → 现在完成被动 has been spent。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'In the last decade, much progress ____ in solar power.', 'has been made', 'is made', 'was made', 'will be made', 'A', 'in the last decade → 现在完成被动 has been made。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'This week, the damaged robot ____ at last.', 'is fixed', 'has been fixed', 'was fixed', 'will be fixed', 'B', 'this week + at last → 现在完成被动 has been fixed。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Up to now, no time machine ____ anywhere in the world.', 'is invented', 'was invented', 'has been invented', 'will be invented', 'C', 'up to now → 现在完成被动 has been invented。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'So far, the new heart pump ____ on many patients.', 'is used', 'was used', 'will be used', 'has been used', 'D', 'so far → 现在完成被动 has been used。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'By now, the science museum ____ by millions of visitors.', 'has been visited', 'is visited', 'was visited', 'will be visited', 'A', 'by now → 现在完成被动 has been visited。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Recently, the rare planet ____ after a Chinese scientist.', 'is named', 'has been named', 'was named', 'will be named', 'B', 'recently → 现在完成被动 has been named。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Over the years, the inventor''s name ____ almost everywhere.', 'is heard', 'was heard', 'has been heard', 'will be heard', 'C', 'over the years → 现在完成被动 has been heard。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Already, the new calendar ____ across the whole country.', 'is introduced', 'was introduced', 'will be introduced', 'has been introduced', 'D', 'already → 现在完成被动 has been introduced。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Since the fire, the injured turtle ____ a 3D-printed shell.', 'has been given', 'is given', 'was given', 'will be given', 'A', 'since the fire → 现在完成被动 has been given。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Up to now, thousands of stars ____ through this telescope.', 'are studied', 'have been studied', 'were studied', 'will be studied', 'B', 'up to now → 现在完成被动 have been studied。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'Lately, several old machines ____ with safer ones.', 'are replaced', 'were replaced', 'have been replaced', 'will be replaced', 'C', 'lately → 现在完成被动 have been replaced。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3' AND code='f3u3.03'), 'By now, the whole report ____ into three languages.', 'is translated', 'was translated', 'will be translated', 'has been translated', 'D', 'by now → 现在完成被动 has been translated。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='fltrp' AND volume='required3' AND unit='U3';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'The New Age of Invention', 'Many people believe that the great age of invention is over, but in fact we have entered an exciting new one. In the past, the world was changed by inventions such as gunpowder, printing and the compass in ancient China, and later by the steam engine and the telephone in the West. Today, however, most great inventions are based on technology. Advances in virtual reality, wearable tech and flexible batteries mean that new products appear almost every month. Important progress has also been made in medicine and environmental science, thanks to the growing power of computers. What has not changed is the human desire to think and to create. According to one writer, most inventions begin when a person notices a problem that needs a solution. As long as people keep asking questions, the age of invention will never truly come to an end.', '说明·我们正进入科技驱动的新发明时代', 144, '[{"q":"What is the writer''s main point?","answer":"A","options":["The age of invention is far from over.","Ancient inventions were better than modern ones.","Computers have stopped people from inventing.","Only Western countries can invent things."],"explanation":"全文主旨''we have entered an exciting new one''的转述。"},{"q":"What are most great inventions based on today?","answer":"B","options":["Gunpowder and printing.","Technology.","The steam engine.","Old farming tools."],"explanation":"原文''most great inventions are based on technology''。"},{"q":"According to the writer, how do most inventions begin?","answer":"A","options":["When a problem needs to be solved.","When the government orders them.","When old machines break down.","When money runs out."],"explanation":"末段''begin when a person notices a problem that needs a solution''的转述。"}]'::jsonb, '[{"word":"advance","cn":"进展;进步"},{"word":"desire","cn":"渴望"}]'::jsonb, 2, 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'When Machines Print Body Parts', 'Within the next eighty years, our lives may be changed beyond recognition by 3D printing. This technology has already affected many areas, right down to the food on our plates; in London, some restaurants have served 3D-printed hamburgers to their customers. Yet the most significant success so far has been in medicine. Using special printers, scientists have made human body parts, including a beating heart and strong new bones. These parts can be designed to fit each patient exactly, which makes operations safer. It is not only humans who benefit. In Brazil, a turtle that had been hurt in a forest fire was given a new 3D-printed shell, and soon it could swim again. Doctors believe that, in the future, fewer patients will have to wait for a suitable donor, because the parts they need will simply be printed in a lab.', '说明·3D打印在医疗中的应用', 142, '[{"q":"Where has 3D printing had its most important success?","answer":"B","options":["In cooking only.","In medicine.","In space travel.","In farming."],"explanation":"原文''the most significant success so far has been in medicine''。"},{"q":"Why is a printed body part safer for an operation?","answer":"C","options":["It is much cheaper than food.","It is printed in a restaurant.","It can be made to fit the patient exactly.","It is larger than a normal part."],"explanation":"原文''designed to fit each patient exactly, which makes operations safer''的转述。"},{"q":"What happened to the turtle in Brazil?","answer":"D","options":["It learned to fly.","It was sent to London.","It was never found.","It received a new printed shell."],"explanation":"原文''was given a new 3D-printed shell''的转述。"}]'::jsonb, '[{"word":"donor","cn":"捐献者"},{"word":"significant","cn":"重要的"}]'::jsonb, 2, 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'The House That Walks', 'Imagine a house that can pick itself up and move to a new place. Thanks to advances in technology, such a house has now been built. The intelligent walking house uses GPS to find its way, while computers control its six metal legs. If the weather turns bad, or if the owners simply want a different view, the house can slowly walk to somewhere better. Because it is powered by the sun, it does not harm the environment, and it produces almost no waste. The idea may sound like science fiction, but every part of it depends on real science that already exists. Engineers say that homes like this could one day help people who live in places where floods or storms are common. When the danger comes, the house will not be left behind; instead, it will quietly carry its owners to safety.', '说明·能自行移动的智能房屋', 144, '[{"q":"How does the walking house find its way?","answer":"A","options":["By using GPS.","By asking neighbours.","By following a paper map.","By guessing."],"explanation":"原文''uses GPS to find its way''。"},{"q":"Why is the house friendly to the environment?","answer":"B","options":["It is made of paper.","It runs on solar power.","It never moves at all.","It burns coal."],"explanation":"原文''powered by the sun, it does not harm the environment''的转述。"},{"q":"Who might such houses help in the future?","answer":"C","options":["Only rich tourists.","People who dislike science.","People in places with floods or storms.","Drivers on long trips."],"explanation":"末段''help people who live in places where floods or storms are common''的转述。"}]'::jsonb, '[{"word":"GPS","cn":"全球定位系统"},{"word":"waste","cn":"废物"}]'::jsonb, 2, 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Franklin''s Experiment: How True?', 'Benjamin Franklin''s experiment with lightning has introduced generations of children to science. The famous story says that in 1752 he flew a kite during a storm, with a metal key tied to the wet string. When lightning struck, electricity was carried down the string, and Franklin touched the key to prove that lightning is a form of electricity. For many years this story has been taught in schools, and children have been amazed by his courage. New research, however, suggests that the tale may be more fiction than fact. Although it has been proved that the experiment really took place, scientists agree that if Franklin had truly touched the key, the shock would have killed him. The lesson is an important one. In science, facts should be tested by experiment and proof, and we should not believe everything we read, even when it makes a wonderful story.', '议论·富兰克林闪电实验的真相', 147, '[{"q":"What did Franklin''s experiment try to prove?","answer":"D","options":["That kites are dangerous toys.","That metal keys are valuable.","That storms never happen.","That lightning is really a kind of electricity."],"explanation":"原文''to prove that lightning is a form of electricity''的转述。"},{"q":"Why do scientists doubt the famous story?","answer":"A","options":["He would probably have died from the shock.","Franklin never lived in America.","Kites cannot fly in storms.","Electricity did not exist then."],"explanation":"原文''if Franklin had truly touched the key, the shock would have killed him''的转述。"},{"q":"What lesson does the writer want readers to learn?","answer":"B","options":["Good stories are always true.","Facts should be tested, not simply believed.","Science is a waste of time.","Children should not study Franklin."],"explanation":"末段''facts should be tested by experiment and proof''的转述。"}]'::jsonb, '[{"word":"shock","cn":"电击"},{"word":"courage","cn":"勇气"}]'::jsonb, 2, 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Careers in Science', 'The world of science offers many different careers, and the words we use for them often come from the subjects themselves. A person who studies living things is called a biologist, while someone who studies the stars and planets is an astronomer. A chemist works with the materials that everything is made of, and a physicist tries to understand energy and forces such as gravity. History is full of brilliant examples. Charles Darwin, a famous biologist, explained how species change over time through natural selection. Marie Curie, working as both a physicist and a chemist, was awarded the Nobel Prize twice for her extraordinary research. What these scientists shared was not only great ability but also patience and curiosity. They were not afraid to ask difficult questions, and they kept working even when the answers were slow to come. Their stories show that science needs both a clever mind and a brave heart.', '说明·不同的科学职业', 153, '[{"q":"What does an astronomer study?","answer":"C","options":["Living animals.","Ancient languages.","The stars and planets.","City traffic."],"explanation":"原文''someone who studies the stars and planets is an astronomer''。"},{"q":"What was Marie Curie awarded twice?","answer":"D","options":["A new planet.","A teaching job.","A sports medal.","The Nobel Prize."],"explanation":"原文''awarded the Nobel Prize twice''。"},{"q":"According to the writer, what did these scientists share?","answer":"A","options":["Patience and curiosity.","A dislike of questions.","A fear of hard work.","The same birthday."],"explanation":"原文''patience and curiosity''的转述。"}]'::jsonb, '[{"word":"physicist","cn":"物理学家"},{"word":"curiosity","cn":"好奇心"}]'::jsonb, 2, 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'An Invention to Remember', 'Alzheimer''s disease is a brain illness that causes problems with memory and thinking, and most of the people who suffer from it are over sixty-five. At present there is no cure, but clever inventions can still make daily life safer. One young inventor named Kenneth designed a small device after watching his own grandmother, who has Alzheimer''s, lose her way near home. The device is worn like a watch. If the person wearing it walks too far from home, a signal is sent to a family member''s mobile phone, rather like an alarm. In this way, help can arrive before the person becomes lost or frightened. Kenneth says the idea came from love, not from money. He hopes that, as computers grow more powerful, many more tools like this will be created to help people who are living with the disease and the families who care for them.', '记叙·帮助阿尔茨海默病患者的小发明', 148, '[{"q":"Who mainly suffers from Alzheimer''s disease?","answer":"B","options":["Young children.","People over sixty-five.","Only scientists.","Newborn babies."],"explanation":"原文''most of the people who suffer from it are over sixty-five''的转述。"},{"q":"What does Kenneth''s device do when the wearer walks too far?","answer":"C","options":["It stops the person from moving.","It plays loud music in the street.","It sends a signal to a family member''s phone.","It calls the police station."],"explanation":"原文''a signal is sent to a family member''s mobile phone''的转述。"},{"q":"Where did Kenneth get the idea for his invention?","answer":"D","options":["From a science magazine.","From a large company.","From a school exam.","From love for his grandmother."],"explanation":"原文''the idea came from love, not from money''的转述。"}]'::jsonb, '[{"word":"device","cn":"装置"},{"word":"signal","cn":"信号"}]'::jsonb, 2, 'required3', 'U3', 'fltrp');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='fltrp' AND volume='required3' AND unit='U3';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U3', 'The Wheel and the Car', 'Most inventions begin when someone notices a (1)____ that needs solving. Long ago, moving heavy loads was very hard, so people invented the (2)____. Much later, this simple idea (3)____ into the car. Today cars are everywhere, but they also (4)____ pollution and use a lot of energy. For this (5)____, engineers have worked hard to build cleaner cars. New energy vehicles are now (6)____ by many companies around the world. They are (7)____ by electricity instead of petrol, so they are kinder to the (8)____. Some people think the great age of invention is (9)____, but they are wrong. As long as we keep (10)____ questions, new ideas will always appear.', 112, 2, '[{"q":"1","answer":"A","options":["problem","holiday","song","garden"],"explanation":"a problem that needs solving 待解决的问题。"},{"q":"2","answer":"B","options":["river","wheel","story","market"],"explanation":"invented the wheel 发明了轮子。"},{"q":"3","answer":"C","options":["ate","sold","developed","lost"],"explanation":"developed into the car 发展成汽车。"},{"q":"4","answer":"D","options":["enjoy","forget","sing","cause"],"explanation":"cause pollution 造成污染。"},{"q":"5","answer":"A","options":["reason","weather","noise","price"],"explanation":"for this reason 因此。"},{"q":"6","answer":"B","options":["eaten","produced","sung","thrown"],"explanation":"are produced by companies 被公司生产。"},{"q":"7","answer":"C","options":["eaten","sold","powered","hidden"],"explanation":"powered by electricity 由电力驱动。"},{"q":"8","answer":"D","options":["music","holiday","price","environment"],"explanation":"kinder to the environment 对环境更友好。"},{"q":"9","answer":"A","options":["over","hungry","green","loud"],"explanation":"the age is over 时代结束了。"},{"q":"10","answer":"B","options":["eating","asking","sleeping","selling"],"explanation":"keep asking questions 不断提问。"}]'::jsonb, 1, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U3', 'The Four Great Inventions', 'Ancient China gave the world four great (1)____: gunpowder, papermaking, printing and the compass. Each of them (2)____ the world deeply. The compass, for (3)____, allowed sailors to find their way far from (4)____. Printing made books cheaper, so knowledge could be (5)____ more widely. These inventions were not made by a single (6)____, but by many people over time. Even today, the compass is still (7)____ in ships and planes. When we study the past, we (8)____ that invention has always been part of human (9)____. The desire to (10)____ is something all of us share.', 97, 2, '[{"q":"1","answer":"C","options":["holidays","gardens","inventions","prices"],"explanation":"four great inventions 四大发明。"},{"q":"2","answer":"D","options":["ate","sold","lost","changed"],"explanation":"changed the world 改变了世界。"},{"q":"3","answer":"A","options":["instance","sale","sleep","noise"],"explanation":"for instance 例如。"},{"q":"4","answer":"B","options":["music","land","price","song"],"explanation":"far from land 远离陆地。"},{"q":"5","answer":"C","options":["eaten","sung","shared","thrown"],"explanation":"could be shared 能被分享。"},{"q":"6","answer":"D","options":["river","garden","price","person"],"explanation":"a single person 一个人。"},{"q":"7","answer":"A","options":["used","eaten","sold","hidden"],"explanation":"is still used 仍被使用。"},{"q":"8","answer":"B","options":["sell","learn","sleep","throw"],"explanation":"we learn that 我们懂得。"},{"q":"9","answer":"C","options":["weather","noise","history","price"],"explanation":"human history 人类历史。"},{"q":"10","answer":"D","options":["sleep","sell","lose","create"],"explanation":"the desire to create 创造的渴望。"}]'::jsonb, 2, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U3', 'A Young Inventor', 'My cousin Tom is only seventeen, but he is already a young (1)____. Last year he joined a small (2)____ of students who love science. Together they (3)____ a cheap robot that can help blind people cross the road. At first their robot did not (4)____ well, and many parts had to be (5)____ again and again. Tom almost wanted to give (6)____, but his teammates encouraged him to keep trying. Finally, after months of hard (7)____, the robot worked. Tom says that no great thing is ever done by one person (8)____. Most modern inventions are created by big (9)____ in which everyone shares ideas. He is proud to be (10)____ of such a group.', 116, 2, '[{"q":"1","answer":"A","options":["inventor","farmer","singer","driver"],"explanation":"a young inventor 年轻发明家。"},{"q":"2","answer":"B","options":["river","team","price","song"],"explanation":"a small team 一个小团队。"},{"q":"3","answer":"C","options":["ate","sold","built","lost"],"explanation":"built a robot 制造了机器人。"},{"q":"4","answer":"D","options":["sing","sleep","eat","work"],"explanation":"did not work well 运转不好。"},{"q":"5","answer":"A","options":["changed","eaten","sung","thrown"],"explanation":"had to be changed 不得不更换。"},{"q":"6","answer":"B","options":["in","up","off","out"],"explanation":"give up 放弃。"},{"q":"7","answer":"C","options":["weather","music","effort","price"],"explanation":"hard effort 努力。"},{"q":"8","answer":"D","options":["happy","green","loud","alone"],"explanation":"by one person alone 仅靠一人。"},{"q":"9","answer":"A","options":["teams","gardens","prices","songs"],"explanation":"big teams 大团队。"},{"q":"10","answer":"B","options":["price","part","noise","song"],"explanation":"be part of 成为……的一员。"}]'::jsonb, 3, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U3', 'The Story of the Telephone', 'The telephone is one of the most important (1)____ in history. It was (2)____ by Alexander Graham Bell in 1876. Bell was interested in sound because his mother and his wife were (3)____ to hear well. He wanted to build a machine that could (4)____ the human voice along a wire. After many (5)____, the first words were finally sent from one room to (6)____. Since that day, the telephone has been (7)____ by billions of people all over the world. It has completely (8)____ the way we live and work. Of course, the phones we use today look nothing like Bell''s first (9)____. Yet the basic idea behind them is still the (10)____.', 114, 2, '[{"q":"1","answer":"C","options":["holidays","gardens","inventions","prices"],"explanation":"important inventions 重要发明。"},{"q":"2","answer":"D","options":["eaten","sung","thrown","invented"],"explanation":"was invented by 由……发明。"},{"q":"3","answer":"A","options":["unable","happy","green","loud"],"explanation":"unable to hear well 听不清。"},{"q":"4","answer":"B","options":["sleep","carry","sell","lose"],"explanation":"carry the voice 传送声音。"},{"q":"5","answer":"C","options":["songs","prices","tries","gardens"],"explanation":"after many tries 多次尝试后。"},{"q":"6","answer":"D","options":["music","price","noise","another"],"explanation":"from one room to another 从一间到另一间。"},{"q":"7","answer":"A","options":["used","eaten","sung","thrown"],"explanation":"has been used by 被使用。"},{"q":"8","answer":"B","options":["eaten","changed","sold","hidden"],"explanation":"has changed the way 改变了方式。"},{"q":"9","answer":"C","options":["river","song","model","price"],"explanation":"Bell''s first model 贝尔最早的型号。"},{"q":"10","answer":"D","options":["hungry","loud","green","same"],"explanation":"still the same 仍然相同。"}]'::jsonb, 4, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U3', 'Marie Curie', 'Marie Curie was one of the most (1)____ scientists in history. She was born in Poland but did most of her (2)____ in France. For years she worked in a cold, poor (3)____, studying a strange new material. Her research was so (4)____ that she was awarded the Nobel Prize, not once but (5)____. Sadly, the very material she studied slowly (6)____ her health. Even so, she never (7)____ to stop her work. Today her discoveries are still (8)____ by doctors to treat serious illnesses. Marie Curie showed that a (9)____ mind and a brave heart can change the world. Her story has (10)____ many young women to become scientists.', 110, 2, '[{"q":"1","answer":"A","options":["famous","hungry","loud","green"],"explanation":"the most famous scientists 最著名的科学家。"},{"q":"2","answer":"B","options":["weather","research","music","price"],"explanation":"did her research 做研究。"},{"q":"3","answer":"C","options":["river","song","lab","garden"],"explanation":"a poor lab 简陋的实验室。"},{"q":"4","answer":"D","options":["hungry","loud","green","significant"],"explanation":"so significant that 如此重要。"},{"q":"5","answer":"A","options":["twice","slowly","sadly","loudly"],"explanation":"not once but twice 不止一次,而是两次。"},{"q":"6","answer":"B","options":["ate","harmed","sold","lost"],"explanation":"harmed her health 损害了她的健康。"},{"q":"7","answer":"C","options":["ate","sold","chose","lost"],"explanation":"never chose to stop 从未选择停下。"},{"q":"8","answer":"D","options":["eaten","sung","thrown","used"],"explanation":"are still used 仍被使用。"},{"q":"9","answer":"A","options":["brilliant","hungry","loud","green"],"explanation":"a brilliant mind 才华横溢的头脑。"},{"q":"10","answer":"B","options":["eaten","inspired","sold","hidden"],"explanation":"has inspired many 激励了许多人。"}]'::jsonb, 5, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U3', 'Question Everything', 'Good scientists never stop (1)____ questions, even about ideas that everyone (2)____. Take the famous story of the apple that (3)____ on Newton''s head and led him to his theory of (4)____. For a long time, people simply (5)____ this story. Recently, however, more than one writer has (6)____ whether it is really true. They agree that Newton was (7)____ inspired by a falling apple, but there is no (8)____ that it hit him on the head. This does not make Newton less great. It only shows that, in science, every claim should be (9)____ by evidence. We should enjoy a good story, but we must not (10)____ everything we hear.', 111, 2, '[{"q":"1","answer":"C","options":["eating","sleeping","asking","selling"],"explanation":"stop asking questions 停止提问。"},{"q":"2","answer":"D","options":["eats","sells","loses","accepts"],"explanation":"everyone accepts 人人接受。"},{"q":"3","answer":"A","options":["fell","ate","sold","lost"],"explanation":"the apple that fell 落下的苹果。"},{"q":"4","answer":"B","options":["weather","gravity","music","price"],"explanation":"theory of gravity 万有引力理论。"},{"q":"5","answer":"C","options":["eaten","sung","believed","thrown"],"explanation":"simply believed 只是相信。"},{"q":"6","answer":"D","options":["eaten","sung","thrown","questioned"],"explanation":"has questioned whether 质疑是否。"},{"q":"7","answer":"A","options":["certainly","loudly","sadly","quickly"],"explanation":"certainly inspired 的确受到启发。"},{"q":"8","answer":"B","options":["weather","proof","music","song"],"explanation":"no proof that 没有证据。"},{"q":"9","answer":"C","options":["eaten","sung","tested","thrown"],"explanation":"should be tested by evidence 应由证据检验。"},{"q":"10","answer":"D","options":["sleep","sell","lose","believe"],"explanation":"must not believe everything 不可全信。"}]'::jsonb, 6, 'fltrp');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='required3' AND unit='U3';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·对话 Visiting the Science Museum', '外研社版必修第三册 U3 · dialogue', 3, 'Mia: Have you ever been to the new science museum, Leo?
Leo: Not yet. I''ve heard a robot has been built there that can talk.
Mia: Yes, it''s amazing. It answers your questions about space and stars.
Leo: That sounds great. What else can we see?
Mia: There''s a model of an electric car that has been designed by students.
Leo: Wow. I''d love to know how it works.
Mia: Then let''s go this Saturday. Tickets have already been booked for us.
Leo: Perfect. I can''t wait to learn something new!', '米娅问利奥去没去新科技馆;利奥没去,听说那里造了会说话的机器人;它能回答关于太空和星星的问题;还有学生设计的电动车模型;两人决定周六去,门票已经订好了。', 'uk_female', '[{"q":"Where are Mia and Leo talking about going?","type":"choice","answer":"A","options":["The new science museum.","A football match.","A music concert.","A book shop."]},{"q":"What can the talking robot do?","type":"choice","answer":"B","options":["Cook dinner for visitors.","Answer questions about space and stars.","Drive an electric car.","Sell tickets."]},{"q":"Who designed the electric car model?","type":"choice","answer":"A","options":["Students.","Famous actors.","The museum cleaners.","Leo''s parents."]},{"q":"When will they go to the museum?","type":"choice","answer":"B","options":["Next year.","This Saturday.","Tonight.","Never."]},{"q":"What has already been done for them?","type":"choice","answer":"C","options":["Dinner has been cooked.","A car has been bought.","Tickets have been booked.","A robot has been sold."]}]'::jsonb, '[]'::jsonb, 'long', 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·短文 The Four Great Inventions', '外研社版必修第三册 U3 · passage', 2, 'Ancient China is famous for four great inventions.
They are gunpowder, papermaking, printing and the compass.
Each of these inventions has changed the world in a deep way.
Thanks to the compass, sailors could travel far across the sea.
Even today, these old ideas are still used in modern life.', '古代中国以四大发明闻名:火药、造纸、印刷和指南针;每一项都深刻改变了世界;有了指南针,水手能远渡重洋;直到今天,这些古老的智慧仍用于现代生活。', 'uk_female', '[{"q":"How many great inventions is ancient China famous for?","type":"choice","answer":"D","options":["Two.","Ten.","None.","Four."]},{"q":"Which of these is one of the four inventions?","type":"choice","answer":"A","options":["The compass.","The television.","The aeroplane.","The computer."]},{"q":"What did each invention do to the world?","type":"choice","answer":"B","options":["Made it smaller.","Changed it deeply.","Left it the same.","Destroyed it."]},{"q":"How did the compass help sailors?","type":"choice","answer":"C","options":["They could fly to the Moon.","They could stop the wind.","They could travel far across the sea.","They could speak new languages."]},{"q":"Are these old ideas still useful today?","type":"choice","answer":"D","options":["No, they are forgotten.","Only in museums.","Only in books.","Yes, they are still used."]}]'::jsonb, '[]'::jsonb, 'short', 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·对话 Acting Out the Telephone Story', '外研社版必修第三册 U3 · dialogue', 3, 'Anna: Let''s practise the conversation about how the telephone was invented.
Ben: Good idea. You ask the questions, and I''ll be the expert.
Anna: So, who was the telephone invented by?
Ben: It was invented by Alexander Graham Bell in 1876.
Anna: What gave him the idea?
Ben: His mother could not hear well, so he became interested in sound.
Anna: And what was the first phone call about?
Ben: He simply called his helper in the next room to test the machine.', '安娜和本排练关于电话发明的对话;安娜提问,本扮专家;电话由亚历山大·格雷厄姆·贝尔于1876年发明;因母亲听力不好,他对声音产生兴趣;第一通电话只是叫隔壁房间的助手来测试机器。', 'uk_female', '[{"q":"What are Anna and Ben practising?","type":"choice","answer":"A","options":["A conversation about the telephone''s invention.","A song about the sea.","A play about a king.","A maths lesson."]},{"q":"Who was the telephone invented by?","type":"choice","answer":"B","options":["Benjamin Franklin.","Alexander Graham Bell.","Charles Darwin.","Isaac Newton."]},{"q":"In which year was it invented?","type":"choice","answer":"C","options":["1752.","1920.","1876.","2005."]},{"q":"Why did Bell become interested in sound?","type":"choice","answer":"D","options":["He loved loud music.","He worked on ships.","He sold radios.","His mother could not hear well."]},{"q":"What was the first phone call about?","type":"choice","answer":"A","options":["Testing the machine with his helper.","Ordering a new kite.","Calling a doctor.","Buying a car."]}]'::jsonb, '[]'::jsonb, 'long', 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·短文 Printing Body Parts', '外研社版必修第三册 U3 · passage', 2, 'Scientists have found an amazing new use for 3D printers.
These machines can now make parts of the human body.
A patient once received a new ear that had been printed in a lab.
Because each part is made to fit one person, operations become safer.
In the future, fewer sick people may have to wait for help.', '科学家为3D打印机找到惊人新用途:这些机器如今能制造人体部件;曾有病人获得一只在实验室打印出的新耳朵;由于每个部件都为一个人量身打印,手术更安全;未来,需要等待救治的病人也许会更少。', 'uk_female', '[{"q":"What new use have scientists found for 3D printers?","type":"choice","answer":"B","options":["Printing newspapers.","Making parts of the human body.","Building cars.","Cooking food."]},{"q":"What did one patient receive?","type":"choice","answer":"C","options":["A new car.","A gold medal.","A printed ear.","A pet turtle."]},{"q":"Why are these operations safer?","type":"choice","answer":"D","options":["The parts are very cheap.","The parts are very large.","The parts are made of paper.","Each part fits one person exactly."]},{"q":"What may happen in the future?","type":"choice","answer":"A","options":["Fewer patients may have to wait.","Printers will disappear.","Doctors will stop working.","Bodies will stop growing."]},{"q":"Where was the new part printed?","type":"choice","answer":"B","options":["In a kitchen.","In a lab.","On a ship.","In a garden."]}]'::jsonb, '[]'::jsonb, 'short', 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·对话 Choosing a Science Career', '外研社版必修第三册 U3 · dialogue', 3, 'Teacher: Have you decided what kind of scientist you want to be, Grace?
Grace: I think I''d like to be an astronomer and study the stars.
Teacher: That''s wonderful. And what about you, Sam?
Sam: I''m more interested in living things, so maybe a biologist.
Teacher: Both are excellent choices. Science needs curious minds.
Grace: But the maths looks really hard.
Teacher: Don''t worry. With patience, every difficult subject can be learned.
Sam: Then we''ll both keep trying!', '老师问格蕾丝想当哪种科学家;格蕾丝想当天文学家研究星星;山姆对生物更感兴趣,想当生物学家;老师说两者都很好,科学需要好奇心;格蕾丝担心数学太难;老师鼓励说只要有耐心,再难的科目也能学会;两人决定继续努力。', 'uk_female', '[{"q":"What does Grace want to be?","type":"choice","answer":"C","options":["A biologist.","A driver.","An astronomer.","A singer."]},{"q":"What is Sam more interested in?","type":"choice","answer":"D","options":["The stars.","Old cars.","Cooking.","Living things."]},{"q":"What does the teacher say science needs?","type":"choice","answer":"A","options":["Curious minds.","A lot of money.","Big machines only.","Quiet students."]},{"q":"What is Grace worried about?","type":"choice","answer":"B","options":["The stars are far.","The maths is hard.","The class is boring.","The room is cold."]},{"q":"What does the teacher say about difficult subjects?","type":"choice","answer":"C","options":["They should be avoided.","They are useless.","They can be learned with patience.","They never change."]}]'::jsonb, '[]'::jsonb, 'long', 'required3', 'U3', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·短文 Where Inventions Begin', '外研社版必修第三册 U3 · passage', 2, 'Here is a simple truth about invention.
Most new ideas begin with a problem that needs a solution.
When something annoys us, we start to ask how it could be better.
That small question is often the first step of a great invention.
So never stop being curious, because every question may change the world.', '关于发明有个简单的道理:大多数新点子始于一个需要解决的问题;当某件事让我们烦恼时,我们便开始思考如何让它变得更好;那个小小的问题,往往是伟大发明的第一步;所以永远别停止好奇,因为每个问题都可能改变世界。', 'uk_female', '[{"q":"Where do most new ideas begin?","type":"choice","answer":"D","options":["With a lot of money.","With a famous name.","With a big factory.","With a problem that needs solving."]},{"q":"What do we do when something annoys us?","type":"choice","answer":"A","options":["We ask how it could be better.","We forget about it.","We go to sleep.","We sell it."]},{"q":"What is often the first step of a great invention?","type":"choice","answer":"B","options":["A long holiday.","A small question.","A new car.","A loud noise."]},{"q":"What should we never stop being?","type":"choice","answer":"C","options":["Angry.","Tired.","Curious.","Silent."]},{"q":"Why is curiosity important?","type":"choice","answer":"D","options":["It makes us rich.","It saves time.","It ends all problems.","Every question may change the world."]}]'::jsonb, '[]'::jsonb, 'short', 'required3', 'U3', 'fltrp');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='required3' AND unit='U3';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (10, 'Write an Experiment Report(写一篇实验报告)', 'The Magic Bottle: How Air Pushes an Egg into a Bottle', '你在科学课上做了一个"魔法瓶"实验:把一个剥壳的熟鸡蛋放在瓶口,鸡蛋竟被吸进瓶里。请用英语写一篇约90词的实验报告,内容包括:① 实验目的;② 所用材料和主要步骤(多用被动语态,如 the shell was removed / hot water was poured in);③ 实验结果和你得出的结论。注意:步骤清楚、用词准确。', 'In a science class you did a ''magic bottle'' experiment: a peeled boiled egg was placed on the mouth of a bottle and was suddenly pulled inside. Write an experiment report (about 90 words) including: 1) the aim of the experiment; 2) the materials used and the main steps (use the passive voice, e.g. the shell was removed / hot water was poured in); 3) the result and the conclusion you draw.', '["说明实验目的(This experiment is designed to …)","列出材料和步骤、多用被动语态(First, the shell was removed …)","报告结果(After a few seconds, the egg was pulled inside.)","得出结论(I can draw the conclusion that …)"]'::jsonb, 70, 100, 'This experiment is designed to show how air pressure can push an egg into a bottle. To do this, I prepared a boiled egg, a glass bottle and some hot water. First, the shell of the egg was removed. Then hot water was poured into the bottle, shaken gently and poured out again. Finally, the egg was quickly placed on the mouth of the bottle. After a few seconds, the egg was pulled inside. From this, I can draw the conclusion that cooling air takes up less space, so the outside air pushes the egg in.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["This experiment is designed to show how air pressure can push an egg into a bottle.","First, the shell of the egg was removed.","After a few seconds, the egg was pulled inside.","From this, I can draw the conclusion that cooling air takes up less space."]'::jsonb, '[{"wrong":"The shell was remove.","correct":"The shell was removed.","note":"被动语态用 be + 过去分词,remove 要变 removed。"},{"wrong":"Hot water poured into the bottle.","correct":"Hot water was poured into the bottle.","note":"water 是动作承受者,描述步骤用被动 was poured。"},{"wrong":"This experiment is design to test air.","correct":"This experiment is designed to test air.","note":"is designed to 固定被动结构,design 要变 designed。"}]'::jsonb, '【实验报告结构】
第1句 目的:This experiment is designed to …
第2句 材料:I prepared … to do this experiment.
第3-4句 步骤(被动):First, … was removed. Then … was poured … Finally, … was placed …
第5句 结果+结论:After a few seconds, … was pulled inside. From this, I can draw the conclusion that …', 2, 'required3', 'U3', 'fltrp');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='required3' AND unit='U3';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (10, 'required3', 'U3', '{"title":"现在完成被动语态 have/has been done 速查","intro":"结构 = have/has + been + 过去分词。表示\"到现在为止\"某动作已经被完成,且对现在有影响。主语是动作的承受者。判断口诀:主语挨打(承受动作)+ 现在完成时间标志(already / so far / recently / since…)→ have/has been done。","table":{"headers":["对比项","形式 / 例句"],"rows":[["现在完成被动","have/has been + done:New parts have been printed.(部件已被打印)"],["现在完成主动","have/has + done:Scientists have printed new parts.(科学家已打印部件)"],["一般现在被动","am/is/are + done:The part is printed in a lab.(经常性事实)"],["一般过去被动","was/were + done:The part was printed last week.(过去某时)"]]},"specialRules":[{"rule":"主语单数用 has been done,复数/I/you/we/they 用 have been done","mark":"A house has been built. / Many cars have been made."},{"rule":"施动者用 by 引出,可省略","mark":"The robot has been fixed (by the students)."},{"rule":"时间标志定时态:already/so far/up to now/since/recently → 现在完成,不用 is done / was done","mark":"So far, no time machine has been invented."},{"rule":"主语后若还跟宾语,说明主语是发出者 → 改用主动,不用被动","mark":"Scientists have made parts.(✓主动)/ Scientists have been made parts.(✗)"}],"why":["选被动还是主动,先看主语:主语是\"做动作的人/物\"用主动 have done;主语是\"被动作影响的东西\"(后面常带 by …、且空后没有宾语)用被动 have been done。","选什么时态,看时间标志:有 already / so far / recently 等强调\"到现在\"的词,就用现在完成,而不是一般现在或一般过去。"],"gaokaoPoints":["语法填空/改错高频:给出动词原形,需根据主语单复数和语态填 has/have been + 过去分词。","易错点:把现在完成被动错写成现在完成主动(漏掉 been),或与一般过去被动(was/were done)混淆——靠时间标志区分。"],"examVsReal":[{"exam":"Much progress has been made in this field.(考试/书面)","real":"We''ve made a lot of progress here.(口语)","note":"考试爱考被动强调结果;日常口语常用主动、更直接。"},{"exam":"The work has been finished.(强调完成、不提是谁)","real":"I''ve finished the work.(口语点明施动者)","note":"被动多用于科技、报告等正式语体,隐去或弱化施动者。"}]}'::jsonb, 'fltrp');

COMMIT;

-- ===== 自带校验(publisher='fltrp') =====
SELECT 'vocab' k, count(*) v, 48 expect FROM public.junior_vocab WHERE publisher='fltrp' AND volume='required3' AND unit='U3'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required3' AND unit='U3')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='fltrp' AND volume='required3' AND unit='U3'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='fltrp' AND volume='required3' AND unit='U3'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='required3' AND unit='U3'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='required3' AND unit='U3'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='required3' AND unit='U3' ORDER BY k;
