-- ============================================================
-- 外研社(fltrp) 必修一 U5(Into the Wild)灌库(junior_* 表,publisher='fltrp' volume='required1' unit='U5' grade=10)。幂等。
-- ★DELETE 全带 publisher='fltrp',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 45 =====
DELETE FROM public.junior_vocab WHERE publisher='fltrp' AND volume='required1' AND unit='U5';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'charity', 'n.', '/ˈtʃærəti/', '慈善机构;慈善团体', 'A local wildlife charity is working to save the rare cranes.', '一个本地野生动物慈善机构正在努力拯救稀有的鹤。', 'Into the Wild', 1, 0, 'senior', 'wordlist', 'required1', 'U5', 'a wildlife charity', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'monarch', 'n.', '/ˈmɒnək/', '君主;(monarch butterfly)黑脉金斑蝶', 'The monarch butterfly is famous for its long autumn journey south.', '黑脉金斑蝶以其漫长的秋季南迁而闻名。', 'Into the Wild', 2, 0, 'senior', 'wordlist', 'required1', 'U5', 'the monarch butterfly', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'whale', 'n.', '/weɪl/', '鲸', 'A huge whale rose slowly to the surface near our boat.', '一头巨大的鲸缓缓浮到我们船边的水面上。', 'Into the Wild', 3, 0, 'senior', 'wordlist', 'required1', 'U5', 'a killer whale', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'annual', 'adj.', '/ˈænjuəl/', '一年一度的;每年的', 'Every autumn these birds begin their annual journey to warmer lands.', '每年秋天这些鸟都开始它们一年一度的迁往温暖地区的旅程。', 'Into the Wild', 4, 0, 'senior', 'wordlist', 'required1', 'U5', 'the annual migration', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'migration', 'n.', '/maɪˈɡreɪʃn/', '迁徙;迁移', 'The migration of the monarch butterfly is one of nature''s wonders.', '黑脉金斑蝶的迁徙是大自然的奇迹之一。', 'Into the Wild', 5, 0, 'senior', 'wordlist', 'required1', 'U5', 'animal migration', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'migrate', 'v.', '/maɪˈɡreɪt/', '迁徙;移栖', 'Many animals migrate to find food or warmer weather.', '许多动物迁徙是为了寻找食物或更温暖的天气。', 'Into the Wild', 6, 0, 'senior', 'wordlist', 'required1', 'U5', 'migrate south', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'seek', 'v.', '/siːk/', '寻找;寻求', 'These insects migrate to seek a partner and warmer weather.', '这些昆虫迁徙是为了寻找配偶和更温暖的天气。', 'Into the Wild', 7, 0, 'senior', 'wordlist', 'required1', 'U5', 'seek warmer weather', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'professor', 'n.', '/prəˈfesə/', '教授', 'A professor and his team finally solved the mystery of the butterfly.', '一位教授和他的团队终于解开了这种蝴蝶之谜。', 'Into the Wild', 8, 0, 'senior', 'wordlist', 'required1', 'U5', 'a professor of biology', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'measure', 'v.', '/ˈmeʒə/', '测量;衡量', 'The butterfly uses its eyes to measure the position of the sun.', '这种蝴蝶用眼睛来测量太阳的位置。', 'Into the Wild', 9, 0, 'senior', 'wordlist', 'required1', 'U5', 'measure the position', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'position', 'n.', '/pəˈzɪʃn/', '位置;方位', 'By checking the sun''s position, the bird knows which way to fly.', '通过查看太阳的位置,这只鸟便知道该往哪个方向飞。', 'Into the Wild', 10, 0, 'senior', 'wordlist', 'required1', 'U5', 'the position of the sun', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'determine', 'v.', '/dɪˈtɜːmɪn/', '确定;测定;决定', 'These two clues help the butterfly determine the way to go.', '这两条线索帮助蝴蝶确定前进的方向。', 'Into the Wild', 11, 0, 'senior', 'wordlist', 'required1', 'U5', 'determine the way', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'eventually', 'adv.', '/ɪˈventʃuəli/', '终于;最终', 'Eventually, the monarchs reach the forests where they spend the winter.', '最终,这些黑脉金斑蝶到达它们过冬的森林。', 'Into the Wild', 12, 0, 'senior', 'wordlist', 'required1', 'U5', 'eventually reach', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'solution', 'n.', '/səˈluːʃn/', '解决方法;答案', 'Scientists searched for years before they found the solution to the puzzle.', '科学家们找了多年才找到这个谜题的答案。', 'Into the Wild', 13, 0, 'senior', 'wordlist', 'required1', 'U5', 'find a solution', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'mystery', 'n.', '/ˈmɪstri/', '谜;难以理解的事物', 'How these tiny insects find their way was a mystery for a long time.', '这些小昆虫如何找到路曾长期是个谜。', 'Into the Wild', 14, 0, 'senior', 'wordlist', 'required1', 'U5', 'solve a mystery', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'amazing', 'adj.', '/əˈmeɪzɪŋ/', '惊人的;了不起的', 'The monarch''s amazing ability to navigate surprised everyone.', '黑脉金斑蝶惊人的导航能力让所有人都很吃惊。', 'Into the Wild', 15, 0, 'senior', 'wordlist', 'required1', 'U5', 'an amazing ability', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'crash', 'v.', '/kræʃ/', '暴跌;猛撞', 'The number of these butterflies has crashed in the last few years.', '这些蝴蝶的数量在过去几年里暴跌。', 'Into the Wild', 16, 0, 'senior', 'wordlist', 'required1', 'U5', 'numbers crash', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'destroy', 'v.', '/dɪˈstrɔɪ/', '破坏;毁掉', 'People are destroying the natural environment that wild animals need.', '人们正在破坏野生动物所需要的自然环境。', 'Into the Wild', 17, 0, 'senior', 'wordlist', 'required1', 'U5', 'destroy the environment', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'chemical', 'n.', '/ˈkemɪkl/', '化学品', 'Farmers use chemicals that kill the plants the caterpillars eat.', '农民使用的化学品杀死了毛虫所吃的植物。', 'Into the Wild', 18, 0, 'senior', 'wordlist', 'required1', 'U5', 'harmful chemicals', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'creature', 'n.', '/ˈkriːtʃə/', '生物;动物', 'The more we know about this creature, the better we can protect it.', '我们对这种生物了解得越多,就越能保护它。', 'Into the Wild', 19, 0, 'senior', 'wordlist', 'required1', 'U5', 'a lovely creature', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'survive', 'v.', '/səˈvaɪv/', '幸存;活下来', 'With our help, these butterflies have a better chance to survive.', '有了我们的帮助,这些蝴蝶就更有可能存活下来。', 'Into the Wild', 20, 0, 'senior', 'wordlist', 'required1', 'U5', 'survive in the wild', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'effect', 'n.', '/ɪˈfekt/', '影响;结果;效果', 'Cutting down trees has a serious effect on wild animals.', '砍伐树木对野生动物有严重的影响。', 'Into the Wild', 21, 0, 'senior', 'wordlist', 'required1', 'U5', 'a cause-effect chart', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'caterpillar', 'n.', '/ˈkætəpɪlə/', '毛虫(蝴蝶等的幼虫)', 'Each caterpillar must eat a lot of leaves before it becomes a butterfly.', '每条毛虫在变成蝴蝶之前都必须吃很多叶子。', 'Into the Wild', 22, 0, 'senior', 'wordlist', 'required1', 'U5', 'a hungry caterpillar', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'accommodation', 'n.', '/əˌkɒməˈdeɪʃn/', '住处;住宿', 'Our accommodation looked out over a waterhole full of wild animals.', '我们的住处俯瞰一处满是野生动物的水塘。', 'Into the Wild', 23, 0, 'senior', 'wordlist', 'required1', 'U5', 'perfect accommodation', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'idiom', 'n.', '/ˈɪdiəm/', '习语;成语', 'Many English idioms use the names of animals, such as ''as busy as a bee''.', '许多英语习语都用到动物的名字,比如"忙得像只蜜蜂"。', 'Into the Wild', 24, 0, 'senior', 'wordlist', 'required1', 'U5', 'animal idioms', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'authority', 'n.', '/ɔːˈθɒrəti/', '当权者;权力;管理机构', 'The local authority has set up a reserve to protect the wild birds.', '当地管理机构设立了一个保护区来保护野生鸟类。', 'Into the Wild', 25, 0, 'senior', 'wordlist', 'required1', 'U5', 'in authority', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'source', 'n.', '/sɔːs/', '来源;源头', 'Wetlands are an important source of food for many wild birds.', '湿地是许多野生鸟类重要的食物来源。', 'Into the Wild', 26, 0, 'senior', 'wordlist', 'required1', 'U5', 'a source of food', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'found', 'v.', '/faʊnd/', '创立;创建', 'The first national park in the world was founded long ago.', '世界上第一个国家公园在很久以前就创立了。', 'Into the Wild', 27, 0, 'senior', 'wordlist', 'required1', 'U5', 'found a park', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'photographer', 'n.', '/fəˈtɒɡrəfə/', '摄影师', 'As a nature photographer, I often work outside in all kinds of weather.', '作为一名自然摄影师,我经常在各种天气下在户外工作。', 'Into the Wild', 28, 0, 'senior', 'wordlist', 'required1', 'U5', 'a nature photographer', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'button', 'n.', '/ˈbʌtn/', '按钮', 'I forced my finger to press the button just before the bear ran away.', '就在那头熊跑开之前,我强迫自己的手指按下了按钮。', 'Into the Wild', 29, 0, 'senior', 'wordlist', 'required1', 'U5', 'press the button', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'recover', 'v.', '/rɪˈkʌvə/', '恢复;康复', 'When I recovered from the shock, I looked down at my camera.', '当我从震惊中恢复过来时,我低头看了看我的相机。', 'Into the Wild', 30, 0, 'senior', 'wordlist', 'required1', 'U5', 'recover from the shock', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'shock', 'n.', '/ʃɒk/', '震惊;吃惊', 'Seeing a bear only metres away gave me a real shock.', '看到一头熊就在几米之外,让我大吃一惊。', 'Into the Wild', 31, 0, 'senior', 'wordlist', 'required1', 'U5', 'recover from the shock', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'element', 'n.', '/ˈelɪmənt/', '要素;(the elements)恶劣天气', 'A wildlife photographer must brave the elements to get a good shot.', '野生动物摄影师必须不顾恶劣天气才能拍到好照片。', 'Into the Wild', 32, 0, 'senior', 'wordlist', 'required1', 'U5', 'brave the elements', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'variety', 'n.', '/vəˈraɪəti/', '多样化;种类', 'The park is famous for the variety of its wildlife.', '这个公园以其野生动物的多样性而闻名。', 'Into the Wild', 33, 0, 'senior', 'wordlist', 'required1', 'U5', 'a variety of wildlife', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'encounter', 'n.', '/ɪnˈkaʊntə/', '意外的相遇;邂逅', 'My encounter with the bear was both frightening and magical.', '我与那头熊的相遇既令人害怕又充满魔力。', 'Into the Wild', 34, 0, 'senior', 'wordlist', 'required1', 'U5', 'an encounter with nature', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'path', 'n.', '/pɑːθ/', '小径;小道', 'I followed a narrow path that led me through a dark forest.', '我沿着一条狭窄的小路穿过一片黑暗的森林。', 'Into the Wild', 35, 0, 'senior', 'wordlist', 'required1', 'U5', 'follow a path', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'breathtaking', 'adj.', '/ˈbreθteɪkɪŋ/', '令人惊叹的;惊人的', 'When I stepped out of the trees, the breathtaking view stopped me.', '当我走出树林时,那令人惊叹的景色让我停下了脚步。', 'Into the Wild', 36, 0, 'senior', 'wordlist', 'required1', 'U5', 'a breathtaking view', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'eagle', 'n.', '/ˈiːɡl/', '鹰;雕', 'An eagle flew high over the snow-capped mountains and the still lake.', '一只鹰在白雪覆盖的群山和平静的湖面上空高高飞过。', 'Into the Wild', 37, 0, 'senior', 'wordlist', 'required1', 'U5', 'a flying eagle', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'concentrate', 'v.', '/ˈkɒnsntreɪt/', '专注;集中(注意力)', 'While I was concentrating on the scene, I felt that I was being watched.', '当我专注于眼前的景色时,我感到自己正被注视着。', 'Into the Wild', 38, 0, 'senior', 'wordlist', 'required1', 'U5', 'concentrate on', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'freeze', 'v.', '/friːz/', '(因恐惧等)呆住;结冰', 'I turned, saw the bear, and froze, unable to move at all.', '我转过身,看见那头熊,然后呆住了,完全动弹不得。', 'Into the Wild', 39, 0, 'senior', 'wordlist', 'required1', 'U5', 'freeze with fear', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'stare', 'v.', '/steə/', '凝视;盯着看', 'With water falling off its hair, the bear stared back at me.', '水从它的毛发上滴落,那头熊回瞪着我。', 'Into the Wild', 40, 0, 'senior', 'wordlist', 'required1', 'U5', 'stare back', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'capture', 'v.', '/ˈkæptʃə/', '(用图片或文字)记录;捕捉;俘获', 'My most frightening experience was now captured forever in one image.', '我最惊险的经历如今被永远地记录在一张图片里。', 'Into the Wild', 41, 0, 'senior', 'wordlist', 'required1', 'U5', 'capture a moment', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'image', 'n.', '/ˈɪmɪdʒ/', '图像;影像', 'The whole magical scene was held forever in a single image.', '整个奇妙的场景被永远定格在一张图像里。', 'Into the Wild', 42, 0, 'senior', 'wordlist', 'required1', 'U5', 'a single image', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'reaction', 'n.', '/riˈækʃn/', '反应', 'His calm reaction when he saw the bear surprised the whole class.', '他看到熊时冷静的反应让全班同学都很惊讶。', 'Into the Wild', 43, 0, 'senior', 'wordlist', 'required1', 'U5', 'a quick reaction', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'file', 'n.', '/faɪl/', '档案;文件', 'We made an animal fact file about the red-crowned crane.', '我们做了一份关于丹顶鹤的动物档案。', 'Into the Wild', 44, 0, 'senior', 'wordlist', 'required1', 'U5', 'an animal fact file', NULL, 'fltrp');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'per cent', 'n.', '/pə ˈsent/', '百分之……', 'The number of monarchs has fallen by as much as ninety per cent.', '黑脉金斑蝶的数量已下降了多达百分之九十。', 'Into the Wild', 45, 0, 'senior', 'wordlist', 'required1', 'U5', 'ninety per cent', NULL, 'fltrp');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5');
DELETE FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f1u5.01', '①when(时间先行词 = on/in/at which)', 'A2', 10, '外研社版必修第一册 U5 — 先行词表时间(day/time/year/moment/season 等)、从句不缺主语或宾语(只缺时间状语)时,用关系副词 when(= 介词+which)。', 1, 'required1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f1u5.02', '②where(地点先行词 = in/at/on which)', 'A2', 10, '外研社版必修第一册 U5 — 先行词表地点(place/country/forest/lake 等)、从句只缺地点状语时,用关系副词 where(= 介词+which)。', 2, 'required1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('f1u5.03', '③why(原因)+ 关系副词 vs 关系代词判断', 'A2', 10, '外研社版必修第一册 U5 — 先行词为 reason、从句缺原因状语时用 why;但若从句缺主语/宾语,即使先行词表时间/地点也要用关系代词 that;介词后只能用 which。', 3, 'required1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'fltrp');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"I still remember the day ____ I first saw a wild eagle in the mountains."', 'when', 'which', 'where', 'that', 'A', '先行词 day 表时间,从句不缺主宾(只缺时间状语)→ when。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"Autumn is the season ____ millions of monarch butterflies fly south."', 'which', 'when', 'where', 'that', 'B', '先行词 season 表时间、从句完整 → when。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"There was a time ____ these forests were full of wild animals."', 'which', 'where', 'when', 'that', 'C', '先行词 time、从句完整 → when。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"Dawn is the hour ____ most birds begin to sing in the wood."', 'which', 'where', 'that', 'when', 'D', '先行词 hour 表时间 → when。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"I will never forget the moment ____ the bear suddenly looked straight at me."', 'when', 'which', 'where', 'that', 'A', '先行词 moment 表时间 → when。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"Spring is the time of year ____ many creatures wake from their long sleep."', 'which', 'when', 'where', 'that', 'B', '先行词 time of year → when。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"That was the year ____ the national park first opened to visitors."', 'which', 'where', 'when', 'that', 'C', '先行词 year 表时间 → when。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"Sunday is the day ____ we usually go bird-watching by the lake."', 'which', 'where', 'that', 'when', 'D', '先行词 day、从句完整 → when。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"He still recalls the night ____ he heard wolves calling across the valley."', 'when', 'which', 'where', 'that', 'A', '先行词 night 表时间 → when。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"There comes a point ____ a young bird is finally ready to fly."', 'which', 'when', 'where', 'that', 'B', 'point 在此表''时刻''→ when。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"Winter is the season ____ food becomes hard for wild animals to find."', 'which', 'where', 'when', 'that', 'C', '先行词 season 表时间 → when。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"I remember the morning ____ the whole wetland was covered with cranes."', 'which', 'where', 'that', 'when', 'D', '先行词 morning 表时间 → when。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"It was an age ____ huge animals like the mammoth still walked the earth."', 'when', 'which', 'where', 'that', 'A', 'age 在此表''时期''→ when。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"That was the moment ____ the eagle spread its wings and rose into the sky."', 'which', 'when', 'where', 'that', 'B', '先行词 moment → when。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"Every autumn there is a week ____ the salmon swim back up the river."', 'which', 'where', 'when', 'that', 'C', '先行词 week 表时间 → when。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"I''ll always remember the day ____ I helped to set a wild bird free."', 'which', 'where', 'that', 'when', 'D', '先行词 day、从句完整 → when。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"Summer is the period ____ the young caterpillars feed on the green leaves."', 'when', 'which', 'where', 'that', 'A', '先行词 period 表时间 → when。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"There was a season ____ this lake was home to thousands of wild ducks."', 'which', 'when', 'where', 'that', 'B', '先行词 season → when。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"Sunset is the time ____ the deer come out to drink at the waterhole."', 'which', 'where', 'when', 'that', 'C', '先行词 time 表时间 → when。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.01'), '"He often talks about the day ____ he photographed his first wild panda."', 'which', 'where', 'that', 'when', 'D', '先行词 day、从句完整 → when。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"Yellowstone is a park ____ visitors can watch bears in the wild."', 'where', 'which', 'when', 'that', 'A', '先行词 park 表地点、从句完整 → where。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"I have finally found a forest ____ wild deer still feel safe."', 'which', 'where', 'when', 'that', 'B', '先行词 forest 表地点 → where。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"This is the lake ____ thousands of cranes spend the winter."', 'which', 'when', 'where', 'that', 'C', '先行词 lake 表地点 → where。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"Mexico is the country ____ the monarch butterflies rest each year."', 'which', 'when', 'that', 'where', 'D', '先行词 country 表地点 → where。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"That is the valley ____ a family of wolves makes its home."', 'where', 'which', 'when', 'that', 'A', '先行词 valley 表地点 → where。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"We visited a wetland ____ many rare birds come to feed."', 'which', 'where', 'when', 'that', 'B', '先行词 wetland 表地点 → where。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"China is a place ____ the giant panda can be seen in the wild."', 'which', 'when', 'where', 'that', 'C', '先行词 place → where。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"He showed me the cave ____ the bears sleep through the cold winter."', 'which', 'when', 'that', 'where', 'D', '先行词 cave 表地点 → where。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"It was a quiet wood ____ I could watch the animals without a sound."', 'where', 'which', 'when', 'that', 'A', '先行词 wood 表地点、从句完整 → where。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"There are still mountains ____ the snow leopard quietly lives."', 'which', 'where', 'when', 'that', 'B', '先行词 mountains 表地点 → where。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"The zoo is the only place ____ many children ever see a real tiger."', 'which', 'when', 'where', 'that', 'C', '先行词 place → where。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"That is the river ____ the salmon lay their eggs every year."', 'which', 'when', 'that', 'where', 'D', '先行词 river 表地点 → where。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"Africa is a land ____ huge herds of animals still move freely."', 'where', 'which', 'when', 'that', 'A', '先行词 land 表地点 → where。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"I found a quiet corner of the park ____ the rabbits like to play."', 'which', 'where', 'when', 'that', 'B', '先行词 corner 表地点 → where。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"This is the field ____ wild flowers feed the hungry caterpillars."', 'which', 'when', 'where', 'that', 'C', '先行词 field 表地点 → where。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"Canada has forests ____ bears and eagles live close together."', 'which', 'when', 'that', 'where', 'D', '先行词 forests 表地点 → where。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"Nature is a world ____ every creature has its own special place."', 'where', 'which', 'when', 'that', 'A', '先行词 world 表抽象地点 → where。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"That is the island ____ thousands of seabirds build their nests."', 'which', 'where', 'when', 'that', 'B', '先行词 island 表地点 → where。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"We reached a hidden pool ____ the deer come to drink at dusk."', 'which', 'when', 'where', 'that', 'C', '先行词 pool 表地点 → where。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.02'), '"It was a small reserve ____ injured wild animals are cared for."', 'which', 'when', 'that', 'where', 'D', '先行词 reserve 表地点 → where。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The reason ____ many monarch butterflies are dying is the loss of plants."', 'why', 'that', 'which', 'where', 'A', '先行词 reason、从句缺原因状语 → why。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"There are many reasons ____ animals migrate to warmer places."', 'that', 'why', 'which', 'where', 'B', '先行词 reasons → why。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"I finally understood the reason ____ the bear had stared at me so long."', 'that', 'which', 'why', 'where', 'C', '先行词 reason → why。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"One reason ____ the red panda is in danger is the cutting of forests."', 'that', 'which', 'where', 'why', 'D', '先行词 reason → why。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"That is the main reason ____ we must protect these wild creatures."', 'why', 'that', 'which', 'where', 'A', '先行词 reason → why。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"Pollution is the reason ____ fish can no longer survive in this river."', 'that', 'why', 'which', 'where', 'B', '先行词 reason → why。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"Nobody knows the real reason ____ the birds changed their usual path."', 'that', 'which', 'why', 'where', 'C', '先行词 reason → why。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"There must be a reason ____ so many whales come to this bay each year."', 'that', 'which', 'where', 'why', 'D', '先行词 reason → why。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The day ____ changed my view of wild animals was truly unforgettable."', 'that', 'when', 'where', 'why', 'A', '先行词 day 虽表时间,但从句缺主语 → 用关系代词 that(不是 when)。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The photo ____ I took of the bear later won a national prize."', 'when', 'that', 'where', 'why', 'B', '先行词 photo、从句缺宾语 → 关系代词 that。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The eagle ____ flew over the lake was the largest I had ever seen."', 'when', 'where', 'that', 'why', 'C', '先行词 eagle、从句缺主语 → that。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The forest ____ we visited last spring was full of singing birds."', 'when', 'where', 'why', 'that', 'D', '先行词 forest 虽表地点,但从句缺宾语(visited ___)→ 用 that(不是 where)。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The animals ____ live in this park are protected by law."', 'that', 'when', 'where', 'why', 'A', '先行词 animals、从句缺主语 → that。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The first creature ____ I photographed in the wild was a red deer."', 'when', 'that', 'where', 'why', 'B', '先行词 creature、从句缺宾语 → that。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The river ____ runs through the valley is home to many fish."', 'when', 'where', 'that', 'why', 'C', '先行词 river、从句缺主语 → that。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"The path ____ we followed led us deep into the dark forest."', 'when', 'where', 'why', 'that', 'D', '先行词 path 虽表地点,但从句缺宾语(followed ___)→ 用 that(不是 where)。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"These are the tall trees on ____ the eagles build their huge nests."', 'which', 'that', 'when', 'where', 'A', '介词 on 后只能用 which(不可 that)。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"That is the way in ____ the butterflies find their direction south."', 'that', 'which', 'when', 'where', 'B', 'the way in which;介词 in 后用 which。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"A camera is the tool with ____ this photographer captures wild animals."', 'that', 'when', 'which', 'where', 'C', '介词 with 后指物用 which。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5' AND code='f1u5.03'), '"Sunlight is the means by ____ green plants make their own food."', 'that', 'when', 'where', 'which', 'D', 'a means by which;介词 by 后用 which。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='fltrp' AND volume='required1' AND unit='U5';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'The Monarch''s Journey', 'Every autumn, millions of monarch butterflies with fine black and orange wings begin a long and difficult journey. Somehow they travel around four thousand kilometres south and find their way to California or Mexico. For a long time, no one knew how such tiny insects could do this. Then a team led by a professor at an American university found the answer. The monarch is able to tell the time of day, and it also uses its eyes to check where the sun sits in the sky. These two clues together allow the butterfly to work out the right direction to fly. In the end, it reaches the warm forests where it will spend the cold winter. The discovery is amazing, yet it has come at a worrying time, because the number of monarchs has dropped sharply in recent years.', 'Into the Wild', 140, '[{"q":"What had long puzzled people about the monarch butterfly?","answer":"A","options":["How such a small insect found its way so far.","Why it had black and orange wings.","When it first appeared on the earth.","Where its name came from."],"explanation":"原文 ''no one knew how such tiny insects could do this'' 的转述。"},{"q":"How does the monarch decide which way to fly?","answer":"B","options":["By following other larger birds.","By noting the hour and the sun''s position above.","By smelling the flowers below.","By listening to the wind."],"explanation":"中段 ''tell the time of day… check where the sun sits… work out the right direction'' 的转述。"},{"q":"Why does the writer call the discovery worrying as well as amazing?","answer":"A","options":["Because monarch numbers have fallen very fast lately.","Because the butterflies fly too slowly.","Because the forests are too warm.","Because no one believes the professor."],"explanation":"末句 ''the number of monarchs has dropped sharply'' 的转述。"}]'::jsonb, '[{"word":"monarch","cn":"黑脉金斑蝶"},{"word":"professor","cn":"教授"},{"word":"direction","cn":"方向"}]'::jsonb, 2, 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Why Animals Migrate', 'Many animals do not stay in one place all year round. At certain times, they move from one area to another, and this regular movement is called migration. There are several reasons why they do this. The most common one is food: when winter comes and food becomes hard to find, animals travel to places where there is still enough to eat. Some move in order to seek a partner and raise their young in a safer area. Others simply follow the warmer weather. Birds, fish, insects and even some large sea animals all make such journeys. The Atlantic salmon, for example, swims back up the very river where it was born, while certain whales travel thousands of kilometres across the ocean each year. These trips are long and full of danger, but the animals that complete them give their young a far better chance to survive.', 'Into the Wild', 147, '[{"q":"What does the word ''migration'' mean in the passage?","answer":"B","options":["Staying in one place all year.","When animals move regularly between different areas.","Sleeping through the whole winter.","Building a nest in a tree."],"explanation":"原文 ''this regular movement is called migration'' 的转述。"},{"q":"According to the text, what is the most common reason for migration?","answer":"C","options":["The wish to be famous.","A dislike of other animals.","The search for food.","The need for exercise."],"explanation":"中段 ''The most common one is food'' 的转述。"},{"q":"What does completing the journey give the animals?","answer":"D","options":["A longer sleep.","A new colour.","A chance to forget the way home.","A better chance for their young to live."],"explanation":"末句 ''give their young a far better chance to survive'' 的转述。"}]'::jsonb, '[{"word":"migration","cn":"迁徙"},{"word":"seek","cn":"寻找"},{"word":"survive","cn":"存活"}]'::jsonb, 2, 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'An Encounter with a Bear', 'Last spring, while taking photos in a national park, I followed a path that led me through a dark forest. When I stepped out of the trees, the view took my breath away. An eagle flew over the snow-capped mountains, which were mirrored in the still lake below. As I was concentrating on this scene, I suddenly felt that I was being watched. Slowly, with my camera still held to my eye, I turned and froze. Only a few metres away stood a large bear, water dropping from its thick brown hair as it stared straight back at me. Time seemed to stop while we both waited to see who would move first. My legs began to shake, but somehow I forced my finger to press the button. A moment later, the bear turned and ran back into the trees. When I recovered, I realised that my most frightening yet magical experience was now saved forever in a single picture.', 'Into the Wild', 160, '[{"q":"What did the writer feel when first stepping out of the trees?","answer":"A","options":["Greatly impressed by the beautiful scene.","Bored by the empty view.","Afraid of getting lost.","Tired and ready to leave."],"explanation":"原文 ''the view took my breath away'' 的转述。"},{"q":"How did the writer react on seeing the bear so close?","answer":"B","options":["He ran away at once.","He froze and could not move at first.","He shouted loudly for help.","He climbed up a tall tree."],"explanation":"原文 ''I turned and froze… My legs began to shake'' 的转述。"},{"q":"What does the writer keep from that day?","answer":"C","options":["A wound on his arm.","A friendship with the bear.","A single photo of the whole experience.","A fear of all forests."],"explanation":"末句 ''saved forever in a single picture'' 的转述。"}]'::jsonb, '[{"word":"concentrate","cn":"专注"},{"word":"freeze","cn":"呆住"},{"word":"stare","cn":"凝视"}]'::jsonb, 2, 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Pandas Far from Home', 'In the spring of 2017, two giant pandas from China arrived at a zoo in the Netherlands. Workers had spent months getting ready for them, and the animals were welcomed into a Chinese-style home built specially for their stay. A few weeks later, after everything was complete, the day finally came for the pandas to meet their fans. People were very excited, partly because this zoo was the only place in the whole country where the public could see pandas, and partly because the last time pandas had lived there was thirty years before. Of course, another reason for the great excitement was simply that pandas are so lovely to look at. The visit was about more than fun, though. It was also a sign of warm feelings between two countries, and it gave local children a chance to learn about a rare creature they might never see in the wild.', 'Into the Wild', 151, '[{"q":"Why was the day the pandas met their fans special?","answer":"D","options":["The pandas had been born at that very zoo.","The zoo was about to close down.","The pandas could already speak Dutch.","It was the country''s only panda zoo, and none had been seen there for thirty years."],"explanation":"中段 ''the only place… the last time pandas had lived there was thirty years before'' 的转述。"},{"q":"Besides being exciting, what did the visit stand for?","answer":"A","options":["Friendly feelings between two countries.","A new kind of food.","A bigger zoo ticket price.","The end of panda research."],"explanation":"末段 ''a sign of warm feelings between two countries'' 的转述。"},{"q":"What chance did the visit give local children?","answer":"B","options":["A chance to feed wild bears.","An up-close look at an unusual creature.","A chance to travel to China.","A chance to keep a panda at home."],"explanation":"末句 ''a chance to learn about a rare creature'' 的转述。"}]'::jsonb, '[{"word":"complete","cn":"完成的"},{"word":"creature","cn":"生物"},{"word":"rare","cn":"稀有的"}]'::jsonb, 2, 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Should Animals Live in Zoos?', 'People often argue about whether wild animals should be kept in zoos. Those who are for zoos say that a good zoo can help protect animals that are in danger. They also believe zoos are a fine way to teach the public, because they let visitors see and learn about animals in surroundings that are made to feel like the wild. Those who are against zoos see things differently. They say that no zoo can truly offer an animal the home that nature gives it. They also worry that zoo animals may lose their natural skills and be unable to live on their own if they are ever set free again. Some even feel that zoos are really built for people rather than for the animals inside them. Both sides care about the same thing, the well-being of the animals, yet they reach very different answers, which is exactly why the debate has gone on for so long.', 'Into the Wild', 158, '[{"q":"What is one point made by people who support zoos?","answer":"C","options":["Zoos should charge much higher prices.","Animals dislike being watched.","A well-run zoo can keep endangered animals safe.","Zoos should only keep insects."],"explanation":"原文 ''a good zoo can help protect animals that are in danger'' 的转述。"},{"q":"Why do some people worry about keeping animals in zoos?","answer":"D","options":["The animals eat too much.","The zoos are always empty.","The animals learn to speak.","The animals may lose the skills needed to live in the wild."],"explanation":"中段 ''may lose their natural skills and be unable to live on their own'' 的转述。"},{"q":"Why has the debate lasted so long, according to the writer?","answer":"A","options":["Because the two sides share one concern yet disagree on the answer.","Because nobody really cares.","Because zoos are too expensive.","Because there are no wild animals left."],"explanation":"末句 ''both sides care about the same thing… reach very different answers'' 的转述。"}]'::jsonb, '[{"word":"argue","cn":"争论"},{"word":"surroundings","cn":"环境"},{"word":"debate","cn":"辩论"}]'::jsonb, 2, 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'The Red-crowned Crane', 'The red-crowned crane is one of the largest cranes in the world, standing about one and a half metres tall. Its feathers are as white as snow, apart from some black ones on its face, neck and wings. Its most special feature, which gives the bird its name, is the bright red skin on the top of its head. This crane can be found in China, Russia, Mongolia, Japan and Korea. In China, it spends the warmer months in the rivers and wetlands of the north-east. When the cold weather arrives, it migrates to the central and eastern parts of the country, where the winter is gentler. Its meals include fish, snails and water plants. To many Chinese people, the red-crowned crane is far more than a beautiful bird, for it has long been a symbol of long life and good luck in their culture.', 'Into the Wild', 145, '[{"q":"What gives the red-crowned crane its name?","answer":"B","options":["Its long white neck.","The bright red patch crowning its head.","The black feathers on its wings.","Its loud morning call."],"explanation":"原文 ''the bright red skin on the top of its head'' 的转述。"},{"q":"Where does the crane go when winter arrives in China?","answer":"C","options":["It flies far across the ocean.","It stays in the frozen north-east.","It moves to the milder central and eastern areas.","It hides inside caves."],"explanation":"中段 ''migrates to the central and eastern parts… winter is gentler'' 的转述。"},{"q":"What does the bird mean in Chinese culture?","answer":"D","options":["Hard work and study.","Bad weather ahead.","A long journey home.","Good fortune and a long life."],"explanation":"末句 ''a symbol of long life and good luck'' 的转述。"}]'::jsonb, '[{"word":"feature","cn":"特征"},{"word":"migrate","cn":"迁徙"},{"word":"symbol","cn":"象征"}]'::jsonb, 2, 'required1', 'U5', 'fltrp');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='fltrp' AND volume='required1' AND unit='U5';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U5', 'A Wildlife Photographer''s Day', 'Being a wildlife photographer is not an easy job. To get a good photo, I often have to (1)____ the elements, working outside in the wind and the rain. Early in the morning I follow a quiet (2)____ into the forest and wait. Sometimes I have to (3)____ very still for hours, holding my camera and watching. When a wild animal finally appears, I try to stay (4)____ so that I do not frighten it away. I must (5)____ on the animal and forget everything else around me. The hardest moment comes when I press the (6)____ at exactly the right time. One single (7)____ can show the beauty of a creature that most people will never (8)____ in the wild. After a long day, I am tired but happy. Each photo is a small (9)____ of a world that we should all learn to (10)____.', 146, 2, '[{"q":"1","answer":"A","options":["brave","buy","sell","lose"],"explanation":"brave the elements 不顾恶劣天气。"},{"q":"2","answer":"B","options":["price","path","noise","season"],"explanation":"a quiet path 一条安静的小路。"},{"q":"3","answer":"C","options":["throw","drop","stay","spend"],"explanation":"stay still 保持不动。"},{"q":"4","answer":"D","options":["loud","angry","busy","calm"],"explanation":"stay calm 保持镇静。"},{"q":"5","answer":"A","options":["concentrate","forget","shout","sleep"],"explanation":"concentrate on 专注于。"},{"q":"6","answer":"B","options":["window","button","garden","market"],"explanation":"press the button 按下按钮。"},{"q":"7","answer":"C","options":["price","noise","image","ticket"],"explanation":"a single image 一张图像。"},{"q":"8","answer":"D","options":["eat","buy","sell","see"],"explanation":"see in the wild 在野外看到。"},{"q":"9","answer":"A","options":["record","machine","shop","city"],"explanation":"a record of 对……的记录。"},{"q":"10","answer":"B","options":["destroy","respect","waste","forget"],"explanation":"respect 尊重(自然世界)。"}]'::jsonb, 1, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U5', 'Saving the Monarch Butterfly', 'The monarch butterfly is in serious (1)____. In just a few years, its numbers have fallen by as much as ninety per (2)____. The main (3)____ for this is human activity. In many of the places (4)____ the butterfly can be found, people are (5)____ the natural environment. They cut down trees and use (6)____ that kill the very plants the caterpillars need to (7)____. Luckily, scientists have helped more people become (8)____ of the problem. Groups now work together to record the butterfly''s (9)____ and to make sure there are enough plants for it to feed on. If this careful work goes on, there may come a time (10)____ the number of monarchs starts to rise once again.', 119, 2, '[{"q":"1","answer":"C","options":["music","price","trouble","game"],"explanation":"in serious trouble 陷入严重困境。"},{"q":"2","answer":"D","options":["hour","metre","minute","cent"],"explanation":"per cent 百分之……。"},{"q":"3","answer":"A","options":["reason","price","noise","garden"],"explanation":"the main reason 主要原因。"},{"q":"4","answer":"B","options":["why","where","when","what"],"explanation":"the places where 地点先行词用 where。"},{"q":"5","answer":"C","options":["building","cleaning","destroying","saving"],"explanation":"destroy the environment 破坏环境。"},{"q":"6","answer":"D","options":["songs","tickets","stories","chemicals"],"explanation":"chemicals 化学品。"},{"q":"7","answer":"A","options":["eat","sell","hide","buy"],"explanation":"plants the caterpillars need to eat 毛虫要吃的植物。"},{"q":"8","answer":"B","options":["afraid","aware","tired","proud"],"explanation":"become aware of 意识到。"},{"q":"9","answer":"C","options":["price","noise","migration","weather"],"explanation":"record its migration 记录其迁徙。"},{"q":"10","answer":"D","options":["which","where","why","when"],"explanation":"a time when 时间先行词用 when。"}]'::jsonb, 2, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U5', 'A Walk in the National Park', 'Last summer my family visited a national park (1)____ a wide variety of wild animals live. As the world''s first park of its kind, it is (2)____ for its beautiful lakes and forests. On our first morning, we got up early and followed a (3)____ that took us deep into the trees. The air was fresh, and everything was so quiet that we hardly dared to (4)____. Suddenly, my sister pointed at the sky. High above the mountains, a huge bird was flying in slow circles. "Look, an (5)____!" she said softly. We all stopped and (6)____ at it until it disappeared. Later, beside a still (7)____, we saw a family of deer come down to drink. My father reminded us to keep our (8)____ low so that we would not (9)____ the animals away. That day taught me that nature is a world (10)____ every creature has its own quiet place.', 152, 2, '[{"q":"1","answer":"A","options":["where","when","why","which"],"explanation":"a park where 地点先行词用 where。"},{"q":"2","answer":"B","options":["afraid","famous","angry","sorry"],"explanation":"be famous for 因……闻名。"},{"q":"3","answer":"C","options":["price","noise","path","ticket"],"explanation":"follow a path 沿着小路。"},{"q":"4","answer":"D","options":["sell","buy","throw","breathe"],"explanation":"hardly dared to breathe 几乎不敢呼吸。"},{"q":"5","answer":"A","options":["eagle","price","market","garden"],"explanation":"an eagle 一只鹰。"},{"q":"6","answer":"B","options":["shouted","stared","slept","sold"],"explanation":"stare at 凝视。"},{"q":"7","answer":"C","options":["price","noise","lake","shop"],"explanation":"a still lake 平静的湖。"},{"q":"8","answer":"D","options":["money","books","shoes","voices"],"explanation":"keep our voices low 压低声音。"},{"q":"9","answer":"A","options":["frighten","help","feed","carry"],"explanation":"frighten the animals away 把动物吓跑。"},{"q":"10","answer":"B","options":["when","where","why","what"],"explanation":"a world where 抽象地点用 where。"}]'::jsonb, 3, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U5', 'The Amazing Eagle', 'The eagle is one of the most (1)____ birds in the world. With its sharp eyes, it can (2)____ a small animal moving far below on the ground. When it sees something to eat, it drops from the sky at an (3)____ speed. Eagles usually build their large nests high on cliffs or in tall (4)____, in places (5)____ few other animals can reach. There they raise their young in (6)____. A young eagle stays in the nest until the day (7)____ it is finally strong enough to fly. Sadly, in some areas the number of eagles has begun to (8)____, because people are destroying the wild land they need. If we want these (9)____ birds to survive, we must protect the quiet, high places (10)____ they make their homes.', 130, 2, '[{"q":"1","answer":"C","options":["boring","ordinary","amazing","empty"],"explanation":"amazing 了不起的。"},{"q":"2","answer":"D","options":["eat","buy","sell","see"],"explanation":"can see 能看见。"},{"q":"3","answer":"A","options":["amazing","empty","easy","early"],"explanation":"an amazing speed 惊人的速度。"},{"q":"4","answer":"B","options":["prices","trees","songs","shops"],"explanation":"in tall trees 在高高的树上。"},{"q":"5","answer":"C","options":["when","why","where","which"],"explanation":"places where 地点先行词用 where。"},{"q":"6","answer":"D","options":["danger","trouble","noise","safety"],"explanation":"in safety 安全地。"},{"q":"7","answer":"A","options":["when","which","where","why"],"explanation":"the day when 时间先行词用 when。"},{"q":"8","answer":"B","options":["rise","fall","grow","win"],"explanation":"the number has begun to fall 数量开始下降。"},{"q":"9","answer":"C","options":["boring","ordinary","amazing","empty"],"explanation":"these amazing birds 这些了不起的鸟。"},{"q":"10","answer":"D","options":["when","why","what","where"],"explanation":"places where 地点先行词用 where。"}]'::jsonb, 4, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U5', 'Helping the Red Panda', 'The red panda is a small, lovely (1)____ that lives in the mountain forests of Asia. Sadly, it is now in (2)____, and its numbers keep falling. One main (3)____ why this is happening is the loss of its forest home. As people cut down trees, the red panda has fewer and fewer places (4)____ it can find food and feel safe. Local (5)____ have now set up reserves to protect the animal. In these protected areas, the forests are not (6)____, and the pandas can live in peace. Workers also (7)____ the plants the pandas like to eat, so that there is always enough food. Scientists carefully (8)____ how many red pandas are left, and they share the (9)____ with people around the world. With this kind of help, there is real hope that the red panda will (10)____ for many years to come.', 145, 2, '[{"q":"1","answer":"A","options":["creature","price","machine","market"],"explanation":"a lovely creature 可爱的生物。"},{"q":"2","answer":"B","options":["safety","danger","music","order"],"explanation":"in danger 处于危险中。"},{"q":"3","answer":"C","options":["price","noise","reason","garden"],"explanation":"the main reason why 主要原因。"},{"q":"4","answer":"D","options":["when","why","what","where"],"explanation":"places where 地点先行词用 where。"},{"q":"5","answer":"A","options":["authorities","songs","tickets","prices"],"explanation":"local authorities 当地管理机构。"},{"q":"6","answer":"B","options":["cleaned","destroyed","opened","saved"],"explanation":"are not destroyed 没有被破坏。"},{"q":"7","answer":"C","options":["sell","hide","grow","throw"],"explanation":"grow the plants 种植植物。"},{"q":"8","answer":"D","options":["forget","lose","waste","record"],"explanation":"record how many 记录数量。"},{"q":"9","answer":"A","options":["results","price","noise","weather"],"explanation":"share the results 分享结果。"},{"q":"10","answer":"B","options":["stop","survive","fail","disappear"],"explanation":"will survive 将存活下来。"}]'::jsonb, 5, 'fltrp');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U5', 'Animals and Their Homes', 'Every wild animal needs a place it can call (1)____. For some, home is a warm cave (2)____ they sleep through the cold winter. For others, it is a (3)____ deep in the forest, far from any road. Fish need clean rivers and lakes, while birds need tall trees (4)____ they can build their nests in safety. When these natural homes are (5)____, the animals lose far more than just a place to rest. They may no longer find enough (6)____ to eat, and their young may not (7)____. This is the real (8)____ why protecting wild places matters so much. By keeping forests, rivers and wetlands clean and safe, we make sure that every (9)____ still has somewhere to live. After (10)____, it is we who are only visitors to their world.', 133, 2, '[{"q":"1","answer":"C","options":["price","noise","home","shop"],"explanation":"call home 称之为家。"},{"q":"2","answer":"D","options":["which","when","why","where"],"explanation":"a cave where 地点先行词用 where。"},{"q":"3","answer":"A","options":["valley","price","market","ticket"],"explanation":"a valley 山谷(地点)。"},{"q":"4","answer":"B","options":["why","where","when","what"],"explanation":"tall trees where 地点先行词用 where。"},{"q":"5","answer":"C","options":["built","cleaned","destroyed","opened"],"explanation":"homes are destroyed 家被毁。"},{"q":"6","answer":"D","options":["money","books","shoes","food"],"explanation":"enough food 足够的食物。"},{"q":"7","answer":"A","options":["survive","sell","buy","throw"],"explanation":"young may not survive 幼崽可能活不下来。"},{"q":"8","answer":"B","options":["price","reason","noise","weather"],"explanation":"the reason why 原因。"},{"q":"9","answer":"C","options":["machine","shop","creature","city"],"explanation":"every creature 每个生物。"},{"q":"10","answer":"D","options":["school","lunch","class","all"],"explanation":"after all 毕竟。"}]'::jsonb, 6, 'fltrp');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='required1' AND unit='U5';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U5 听力·对话 Planning a Wildlife Trip', '外研社版必修第一册 U5 · dialogue', 3, 'Lily: Where do you want to go this weekend, Tom?
Tom: I''d love to visit the national park to watch wild birds.
Lily: That sounds great. What do you hope to see there?
Tom: Mostly eagles. I really want to take a photo of one flying.
Lily: Then we should get up very early in the morning.
Tom: Yes, dawn is the time when most birds are active.
Lily: Good idea. I''ll bring my camera too.
Tom: Perfect. Remember to stay quiet so we don''t frighten them away.', 'Lily 问 Tom 周末想去哪;Tom 想去国家公园观野鸟,主要想拍飞翔的鹰;两人决定清晨早起,因为黎明时鸟最活跃;Lily 也带相机;Tom 提醒要保持安静,以免吓跑鸟。', 'uk_female', '[{"q":"Where does Tom want to go this weekend?","type":"choice","answer":"A","options":["To the national park.","To a shopping centre.","To the seaside.","To a friend''s house."]},{"q":"What does Tom mainly hope to see?","type":"choice","answer":"B","options":["Wild horses.","Eagles.","Whales.","Snakes."]},{"q":"Why do they decide to get up early?","type":"choice","answer":"A","options":["Because most birds are active at dawn.","To avoid the rain.","To buy cheap tickets.","Because the park closes at noon."]},{"q":"What will Lily bring along?","type":"choice","answer":"B","options":["A map.","Her camera.","Some food.","A warm coat."]},{"q":"What does Tom remind Lily to do?","type":"choice","answer":"C","options":["Walk as fast as possible.","Sing on the way.","Stay quiet so they do not frighten the birds.","Leave the camera at home."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U5 听力·短文 Why Animals Travel', '外研社版必修第一册 U5 · passage', 2, 'Many animals do not spend the whole year in one place.
When food runs low in winter, they move to warmer areas.
Some travel a long way to find a safe place for their young.
Birds, fish and even some insects make these yearly journeys.
The trips are full of danger, but they help the animals live on.', '许多动物并非整年待在一个地方;冬天食物变少时,它们迁往温暖地区;有些长途跋涉为幼崽寻找安全之地;鸟、鱼甚至一些昆虫都进行这样的年度旅程;旅途充满危险,但帮助动物生存下去。', 'uk_female', '[{"q":"What do many animals NOT do?","type":"choice","answer":"D","options":["Look for food.","Move in winter.","Care for their young.","Spend the whole year in one place."]},{"q":"Why do animals move when winter comes?","type":"choice","answer":"A","options":["Food becomes hard to find.","They enjoy the cold.","They want to swim.","They are bored."]},{"q":"Why do some animals travel a long way?","type":"choice","answer":"B","options":["To meet people.","To find a safe place for their young.","To find shops.","To get lost."]},{"q":"Which animals make these yearly journeys?","type":"choice","answer":"C","options":["Only large animals.","Only sea animals.","Birds, fish and even some insects.","No animals at all."]},{"q":"What do these dangerous trips help animals do?","type":"choice","answer":"D","options":["Forget the way home.","Stop eating.","Sleep all winter.","Live on and survive."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U5 听力·对话 The Zoo Debate', '外研社版必修第一册 U5 · dialogue', 3, 'Mia: I think zoos are good because they protect animals in danger.
Jack: But a zoo can never give an animal its real home in the wild.
Mia: That''s true, yet zoos help children learn about animals.
Jack: They can learn from films and books instead.
Mia: Still, seeing a real tiger is not the same as watching a film.
Jack: I agree it''s exciting, but I worry the animals are not free.
Mia: So you think zoos are built more for people than for animals?
Jack: Exactly. That''s my biggest reason for being against them.', 'Mia 认为动物园好,因为能保护濒危动物;Jack 认为动物园永远给不了动物真正的野外家园;Mia 说动物园能让孩子了解动物;Jack 说看影片和书也能学;Mia 说亲眼看真老虎和看影片不一样;Jack 担心动物不自由,认为动物园更多是为人而建——这是他反对的最大理由。', 'uk_female', '[{"q":"Why does Mia think zoos are good?","type":"choice","answer":"A","options":["They protect animals in danger.","They make a lot of money.","They are quiet places.","They are easy to build."]},{"q":"What is Jack''s first point against zoos?","type":"choice","answer":"B","options":["Zoos are too small.","A zoo cannot give an animal its real wild home.","Zoos cost too much.","Zoos have no visitors."]},{"q":"How does Mia reply when Jack mentions films and books?","type":"choice","answer":"C","options":["She agrees films are best.","She says books are useless.","She says seeing a real tiger is not the same as a film.","She stops talking."]},{"q":"What does Jack worry about?","type":"choice","answer":"D","options":["The price of tickets.","The weather in the zoo.","The food for visitors.","That the animals are not free."]},{"q":"What is Jack''s biggest reason for being against zoos?","type":"choice","answer":"A","options":["He believes zoos are built more for people than for animals.","He dislikes children.","He thinks animals are boring.","He never visits zoos."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U5 听力·短文 The Monarch Butterfly', '外研社版必修第一册 U5 · passage', 2, 'Each autumn, monarch butterflies fly thousands of kilometres south.
For years, no one knew how they found the right way.
Scientists learned that the insect uses the sun to guide it.
Sadly, the number of monarchs has dropped very fast.
People are now working together to help them survive.', '每年秋天,黑脉金斑蝶向南飞行数千公里;多年来无人知道它们如何找到正确方向;科学家发现这种昆虫靠太阳指引;遗憾的是,金斑蝶数量下降得很快;如今人们正合力帮助它们生存。', 'uk_female', '[{"q":"When do the monarch butterflies fly south?","type":"choice","answer":"B","options":["Every morning.","Each autumn.","In summer only.","Once in their life."]},{"q":"What did people NOT know for years?","type":"choice","answer":"C","options":["What the butterflies ate.","Where the butterflies slept.","How the butterflies found the right way.","How big the butterflies were."]},{"q":"What guides the butterfly, according to scientists?","type":"choice","answer":"D","options":["The wind.","Other birds.","The rivers.","The sun."]},{"q":"What has happened to the number of monarchs?","type":"choice","answer":"A","options":["It has dropped very fast.","It has stayed the same.","It has grown quickly.","It is unknown."]},{"q":"What are people doing now?","type":"choice","answer":"B","options":["Catching all of them.","Working together to help them survive.","Ignoring the problem.","Moving them to zoos."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U5 听力·对话 Advice for Watching Bears', '外研社版必修第一册 U5 · dialogue', 3, 'Ben: I''m going to photograph bears next week. Any advice?
Sara: Yes. Never get too close to a wild bear.
Ben: How close is too close?
Sara: Keep at least a hundred metres away to stay safe.
Ben: What if a bear suddenly looks at me?
Sara: Stay calm, don''t run, and move back slowly.
Ben: That''s good to know. Anything else?
Sara: Yes, always respect the animal. We are visitors in its world.', 'Ben 下周要拍熊,向 Sara 求建议;Sara 说绝不要太靠近野熊,至少保持一百米;若熊忽然看着你,要保持冷静、别跑、慢慢后退;最后她说要永远尊重动物,我们是它世界里的客人。', 'uk_female', '[{"q":"What is Ben going to do next week?","type":"choice","answer":"C","options":["Sell his camera.","Visit a city.","Photograph bears.","Stay at home."]},{"q":"What is Sara''s first piece of advice?","type":"choice","answer":"D","options":["Feed the bears.","Shout at the bears.","Touch the bears.","Never get too close to a wild bear."]},{"q":"How far away should Ben stay to be safe?","type":"choice","answer":"A","options":["At least a hundred metres.","About one metre.","About ten metres.","As close as possible."]},{"q":"What should Ben do if a bear looks at him?","type":"choice","answer":"B","options":["Run away fast.","Stay calm and move back slowly.","Throw something.","Climb a tree."]},{"q":"What does Sara say at the end?","type":"choice","answer":"C","options":["Bears are not real.","Cameras are useless.","Always respect the animal.","Bears love people."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U5', 'fltrp');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U5 听力·短文 Respecting Wild Animals', '外研社版必修第一册 U5 · passage', 2, 'Wild animals are not pets, and they belong in nature.
When we visit their world, we should be quiet and careful.
We must never leave rubbish that could harm them.
Cutting down their forests takes away the homes they need.
If we respect them, both animals and people can live well.', '野生动物不是宠物,它们属于大自然;当我们进入它们的世界时,应保持安静和小心;绝不能留下可能伤害它们的垃圾;砍伐森林会夺走它们所需的家园;如果我们尊重它们,动物和人都能生活得很好。', 'uk_female', '[{"q":"What does the passage say about wild animals?","type":"choice","answer":"D","options":["They make good pets.","They like living in cities.","They are all dangerous.","They are not pets and belong in nature."]},{"q":"How should we behave when visiting their world?","type":"choice","answer":"A","options":["Quietly and carefully.","Loudly and freely.","Quickly and carelessly.","Angrily and rudely."]},{"q":"What must we never leave behind?","type":"choice","answer":"B","options":["Our cameras.","Rubbish that could harm them.","Our footprints.","Our maps."]},{"q":"What does cutting down forests do?","type":"choice","answer":"C","options":["It helps the animals.","It makes them happy.","It takes away the homes they need.","It gives them more food."]},{"q":"What happens if we respect wild animals?","type":"choice","answer":"D","options":["Only people benefit.","Animals disappear faster.","Nothing changes at all.","Both animals and people can live well."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U5', 'fltrp');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='required1' AND unit='U5';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (10, 'Write an Animal Fact File(写一份动物档案)', 'An Animal Fact File', '请用英语写一份约80词的动物档案,介绍一种你喜欢的野生动物。内容包括:① 它长什么样(外貌/独特特征);② 它生活在哪里;③ 它吃什么或它如何迁徙;④ 关于它的一条其他信息(如象征意义或为何需要保护)。注意:用定语从句让句子更连贯。', 'Write an animal fact file (about 80 words) about a wild animal you like. Include: 1) what it looks like (appearance / a special feature); 2) where it lives; 3) what it eats or how it migrates; 4) one piece of other information (such as its symbolic meaning or why it needs protecting). Try to use attributive clauses to link your ideas.', '["外貌/独特特征(It is … tall. / Its unique feature is …)","栖息地(It is found in … / It lives in places where …)","食物或迁徙(Its food includes … / When winter comes, it migrates to …)","其他信息 + 用定语从句连接句子"]'::jsonb, 70, 100, 'The red-crowned crane is one of the largest cranes in the world, standing about 150 cm tall. Its feathers are as white as snow, and its unique feature, which gives the bird its name, is the bright red skin on top of its head. It is found in China, Russia and Japan. In China, it lives in northern wetlands where there is plenty of food, such as fish and water plants. When winter comes, it migrates to milder areas in the east. To Chinese people, this crane is a symbol of long life and good luck.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["Its unique feature, which gives the bird its name, is the bright red skin on its head.","It lives in northern wetlands where there is plenty of food.","When winter comes, it migrates to milder areas in the east.","To Chinese people, this crane is a symbol of long life and good luck."]'::jsonb, '[{"wrong":"It lives in wetlands where it is full of food.","correct":"It lives in wetlands where there is plenty of food.","note":"where 引导地点状语从句,后面用 there is,不再加多余主语 it。"},{"wrong":"Winter comes, it migrates to the east.","correct":"When winter comes, it migrates to the east.","note":"两个句子要用连词 When 连接,不能直接逗号相连。"},{"wrong":"Its food include fish and plants.","correct":"Its food includes fish and plants.","note":"主语 food 第三人称单数,动词加 s。"}]'::jsonb, '【动物档案结构】
第1句 外貌:It is … tall, and its unique feature is …
第2句 栖息地:It is found in … / It lives in places where …
第3句 食物或迁徙:Its food includes … / When winter comes, it migrates to …
第4句 其他信息:It is a symbol of … / We must protect it.', 2, 'required1', 'U5', 'fltrp');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='required1' AND unit='U5';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (10, 'required1', 'U5', '{"title":"限制性定语从句·关系副词 when / where / why 速查","intro":"关系副词在从句中作状语(时间/地点/原因),等于「介词+which」。判断口诀:从句缺状语→用关系副词,缺主语/宾语→用关系代词 that/which。","table":{"headers":["关系副词","用法 / 例句 / 等价"],"rows":[["when","时间先行词(day/time/year/season):the day when = on/in which"],["where","地点先行词(place/forest/lake/park):the place where = in/at which"],["why","原因(reason):the reason why = for which"],["介词+which","从句缺主宾、或表达更正式:on which / in which / by which / with which"]]},"specialRules":[{"rule":"从句只缺状语(时间/地点/原因)→ 才用关系副词","mark":"the forest where I took photos(缺地点状语)"},{"rule":"从句缺主语/宾语 → 即使先行词是时间/地点也用 that","mark":"the day that changed my view(缺主语→that)"},{"rule":"the day when = on/in which;the place where = in/at which;the reason why = for which","mark":"等价替换"},{"rule":"介词后只能用 which,不可用 that","mark":"trees on which √ / trees on that ×"}],"why":["关系副词 = 介词 + which,在从句里充当状语,所以从句的主语、宾语都不缺;一旦主语或宾语缺了,就要换成关系代词 that/which。"],"gaokaoPoints":["when/where/why 与 which/that 的判断(看从句缺什么成分);介词+which;语法填空高频。","the way 后的定语从句:用 that / in which / 或省略,但不用 which 单独引导。"],"examVsReal":[{"exam":"the forest where I work（考试/书面）","real":"the forest I work in","note":"考试用 where;口语常省略关系词、把介词放句末"},{"exam":"the reason why the bird left（考试）","real":"the reason the bird left / the reason that the bird left","note":"考试用 why;口语里 why 常被省略或用 that"}]}'::jsonb, 'fltrp');

COMMIT;

-- ===== 自带校验(publisher='fltrp') =====
SELECT 'vocab' k, count(*) v, 45 expect FROM public.junior_vocab WHERE publisher='fltrp' AND volume='required1' AND unit='U5'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='fltrp' AND volume='required1' AND unit='U5')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='fltrp' AND volume='required1' AND unit='U5'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='fltrp' AND volume='required1' AND unit='U5'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='fltrp' AND volume='required1' AND unit='U5'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='fltrp' AND volume='required1' AND unit='U5'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='fltrp' AND volume='required1' AND unit='U5' ORDER BY k;
