-- ============================================================
-- 必修二 U4(History and Traditions)灌库(junior_* 表,volume='required2' unit='U4' grade=10)。幂等。
-- preflight(grade 7-12 + senior 分类)已随必修一跑过,不必再跑。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 51 =====
DELETE FROM public.junior_vocab WHERE volume='required2' AND unit='U4';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'achievement', 'n.', '/əˈtʃiːvmənt/', '成就;成绩;达到', 'Building towns and roads was a great achievement of the Romans.', '修建城镇和道路是罗马人的一大成就。', 'History and Traditions', 1, 0, 'senior', 'wordlist', 'required2', 'U4', 'a great achievement', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'amount', 'n.', '/əˈmaʊnt/', '金额;数量', 'We were surprised by the amount of noise at the gallery entrance.', '我们对美术馆入口处的噪音之大感到惊讶。', 'History and Traditions', 2, 0, 'senior', 'wordlist', 'required2', 'U4', 'the amount of noise', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'ancestor', 'n.', '/ˈænsestə(r)/', '祖宗;祖先', 'The family''s ancestors once helped soldiers wounded in the war.', '这家人的祖先曾照料过在战争中负伤的士兵。', 'History and Traditions', 3, 0, 'senior', 'wordlist', 'required2', 'U4', 'our ancestors', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'announce', 'vt.', '/əˈnaʊns/', '宣布;通知;声称', 'We heard it announced that there were no audio guides left.', '我们听到广播宣布讲解器已经没有了。', 'History and Traditions', 4, 0, 'senior', 'wordlist', 'required2', 'U4', 'announce that', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'approach', 'v./n.', '/əˈprəʊtʃ/', '接近;着手处理;方法;途径', 'It was hard to approach the painting because of the crowd.', '由于人群拥挤,很难靠近那幅画。', 'History and Traditions', 5, 0, 'senior', 'wordlist', 'required2', 'U4', 'approach the painting', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'battle', 'n./v.', '/ˈbætl/', '战役;搏斗;奋斗', 'The Normans won the famous battle and then conquered England.', '诺曼人赢得了那场著名的战役,随后征服了英格兰。', 'History and Traditions', 6, 0, 'senior', 'wordlist', 'required2', 'U4', 'the famous battle', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'beer', 'n.', '/bɪə(r)/', '(一杯)啤酒', 'Relax in a village pub with a glass of wine or a local beer.', '在乡村酒馆里喝一杯葡萄酒或本地啤酒,放松一下。', 'History and Traditions', 7, 0, 'senior', 'wordlist', 'required2', 'U4', 'a local beer', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'belong', 'vi.', '/bɪˈlɒŋ/', '属于;应在(某处)', 'Four countries belong to the United Kingdom.', '有四个国家属于联合王国。', 'History and Traditions', 8, 0, 'senior', 'wordlist', 'required2', 'U4', 'belong to', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'butter', 'n.', '/ˈbʌtə(r)/', '黄油;奶油', 'The family offered them bread with butter and homemade honey.', '这家人给他们端来涂了黄油的面包和自制蜂蜜。', 'History and Traditions', 9, 0, 'senior', 'wordlist', 'required2', 'U4', 'bread with butter', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'cattle', 'n.', '/ˈkætl/', '牛', 'The green hills were dotted with sheep and cattle.', '绿色的山丘上点缀着绵羊和牛群。', 'History and Traditions', 10, 0, 'senior', 'wordlist', 'required2', 'U4', 'sheep and cattle', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'cemetery', 'n.', '/ˈsemətri/', '墓地;公墓', 'Visitors can walk quietly through the ancient cemetery.', '游客可以安静地穿过这座古老的墓地。', 'History and Traditions', 11, 0, 'senior', 'wordlist', 'required2', 'U4', 'an ancient cemetery', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'charge', 'v./n.', '/tʃɑːdʒ/', '充电;收费;指控;主管', 'We could get our car battery charged near the square.', '我们可以在广场附近给汽车电池充电。', 'History and Traditions', 12, 0, 'senior', 'wordlist', 'required2', 'U4', 'get sth charged', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'chief', 'adj./n.', '/tʃiːf/', '最重要的;首领;酋长', 'One chief advantage of studying history is understanding a country better.', '学习历史的一个主要好处是更好地了解一个国家。', 'History and Traditions', 13, 0, 'senior', 'wordlist', 'required2', 'U4', 'a chief advantage', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'conquer', 'vt.', '/ˈkɒŋkə(r)/', '占领;征服;控制', 'The Normans conquered England after the Battle of Hastings.', '黑斯廷斯战役之后,诺曼人征服了英格兰。', 'History and Traditions', 14, 0, 'senior', 'wordlist', 'required2', 'U4', 'conquer England', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'county', 'n.', '/ˈkaʊnti/', '(英国、爱尔兰的)郡;(美国的)县', 'Ireland''s many green counties are a true feast for the eyes.', '爱尔兰众多翠绿的郡县是一场真正的视觉盛宴。', 'History and Traditions', 15, 0, 'senior', 'wordlist', 'required2', 'U4', 'green counties', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'courtyard', 'n.', '/ˈkɔːtjɑːd/', '庭院;院子', 'Paul wanted to visit the famous family courtyard in Pingyao.', '保罗想去参观平遥那座著名的家族庭院。', 'History and Traditions', 16, 0, 'senior', 'wordlist', 'required2', 'U4', 'a family courtyard', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'crowd', 'n./v.', '/kraʊd/', '人群;一群人;挤满', 'A large crowd had gathered at the entrance of the National Gallery.', '国家美术馆的入口处聚集了一大群人。', 'History and Traditions', 17, 0, 'senior', 'wordlist', 'required2', 'U4', 'a large crowd', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'currency', 'n.', '/ˈkʌrənsi/', '通货;货币', 'The four countries share the same currency and military defence.', '这四个国家共用同一种货币和军事防御。', 'History and Traditions', 18, 0, 'senior', 'wordlist', 'required2', 'U4', 'share the same currency', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'custom', 'n.', '/ˈkʌstəm/', '风俗;习俗;习惯', 'You are likely to experience local culture and customs first-hand.', '你很可能会亲身体验到当地的文化和习俗。', 'History and Traditions', 19, 0, 'senior', 'wordlist', 'required2', 'U4', 'local customs', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'defence', 'n.', '/dɪˈfens/', '防御;保卫', 'The UK countries share the same military defence.', '联合王国各国共用同一套军事防御。', 'History and Traditions', 20, 0, 'senior', 'wordlist', 'required2', 'U4', 'military defence', '美式拼 defense;美音 /dɪˈfens/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'descendant', 'n.', '/dɪˈsendənt/', '后裔;后代;子孙', 'Xiao Kong is a descendant of an ancient Chinese philosopher.', '小孔是一位中国古代哲学家的后裔。', 'History and Traditions', 21, 0, 'senior', 'wordlist', 'required2', 'U4', 'a descendant of', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'dot', 'v./n.', '/dɒt/', '加点;遍布;小圆点', 'The rolling green hills were dotted with white sheep.', '起伏的绿色山丘上点缀着白色的羊群。', 'History and Traditions', 22, 0, 'senior', 'wordlist', 'required2', 'U4', 'dotted with', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'eager', 'adj.', '/ˈiːɡə(r)/', '热切的;渴望的', 'I was eager to learn that the city had such a long history.', '得知这座城市有如此悠久的历史,我十分激动。', 'History and Traditions', 23, 0, 'senior', 'wordlist', 'required2', 'U4', 'be eager to', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'ensure', 'vt.', '/ɪnˈʃʊə(r)/', '保证;确保;担保', 'She had a copy boxed to ensure that it was delivered safely.', '她让人把一份复制品装箱,以确保它被安全送达。', 'History and Traditions', 24, 0, 'senior', 'wordlist', 'required2', 'U4', 'ensure that', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'evidence', 'n.', '/ˈevɪdəns/', '证据;证明', 'Everywhere you go, you find evidence of four groups of people.', '你所到之处,都能发现四群人留下的痕迹。', 'History and Traditions', 25, 0, 'senior', 'wordlist', 'required2', 'U4', 'evidence of', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'fascinating', 'adj.', '/ˈfæsɪneɪtɪŋ/', '极有吸引力的;迷人的', 'The UK is a fascinating mix of history and modern culture.', '英国是历史与现代文化的迷人结合体。', 'History and Traditions', 26, 0, 'senior', 'wordlist', 'required2', 'U4', 'a fascinating mix', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'feast', 'n.', '/fiːst/', '盛宴;宴会;节日', 'The peaceful landscape is a true feast for the eyes.', '宁静的风景是一场真正的视觉盛宴。', 'History and Traditions', 27, 0, 'senior', 'wordlist', 'required2', 'U4', 'a feast for the eyes', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'gallery', 'n.', '/ˈɡæləri/', '(艺术作品的)展览馆;画廊', 'We visited the National Gallery to see the famous paintings.', '我们参观了国家美术馆,去看那些著名的画作。', 'History and Traditions', 28, 0, 'senior', 'wordlist', 'required2', 'U4', 'an art gallery', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'generous', 'adj.', '/ˈdʒenərəs/', '慷慨的;大方的;丰富的', 'A generous family offered the travellers bread and honey.', '一户慷慨的人家给旅行者端来了面包和蜂蜜。', 'History and Traditions', 29, 0, 'senior', 'wordlist', 'required2', 'U4', 'a generous family', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'greet', 'vt.', '/ɡriːt/', '问候;迎接', 'Birds greet the new day with their morning song.', '鸟儿用晨歌迎接新的一天。', 'History and Traditions', 30, 0, 'senior', 'wordlist', 'required2', 'U4', 'greet the day', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'honey', 'n.', '/ˈhʌni/', '蜂蜜', 'They served bread with butter and homemade honey.', '他们端来了涂黄油的面包和自制蜂蜜。', 'History and Traditions', 31, 0, 'senior', 'wordlist', 'required2', 'U4', 'homemade honey', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'individual', 'adj./n.', '/ˌɪndɪˈvɪdʒuəl/', '单独的;个别的;个人', 'The meaning of an idiom is different from each individual word.', '习语的意思与其中每个单独的词都不同。', 'History and Traditions', 32, 0, 'senior', 'wordlist', 'required2', 'U4', 'an individual word', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'kingdom', 'n.', '/ˈkɪŋdəm/', '王国;领域', 'Wales was joined to the Kingdom of England in the 16th century.', '16世纪,威尔士被并入英格兰王国。', 'History and Traditions', 33, 0, 'senior', 'wordlist', 'required2', 'U4', 'the United Kingdom', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'landscape', 'n.', '/ˈlændskeɪp/', '(陆上,尤指乡村的)风景', 'Loch Ness was surrounded by beautiful natural landscape.', '尼斯湖被美丽的自然风景所环绕。', 'History and Traditions', 34, 0, 'senior', 'wordlist', 'required2', 'U4', 'natural landscape', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'legal', 'adj.', '/ˈliːɡl/', '法律的;合法的', 'Each country has its own education and legal systems.', '每个国家都有自己的教育和法律制度。', 'History and Traditions', 35, 0, 'senior', 'wordlist', 'required2', 'U4', 'the legal system', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'location', 'n.', '/ləʊˈkeɪʃn/', '地方;地点;位置', 'The Vikings left behind the names of many locations across the UK.', '维京人在英国各地留下了许多地名。', 'History and Traditions', 36, 0, 'senior', 'wordlist', 'required2', 'U4', 'names of locations', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'mansion', 'n.', '/ˈmænʃn/', '公馆;宅第', 'The Kong Family Mansion is a famous historic site in Qufu.', '孔府是曲阜一处著名的历史遗迹。', 'History and Traditions', 37, 0, 'senior', 'wordlist', 'required2', 'U4', 'a family mansion', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'military', 'adj.', '/ˈmɪlətri/', '军事的;军用的', 'The four countries share the same military defence.', '这四个国家共用同一套军事防御。', 'History and Traditions', 38, 0, 'senior', 'wordlist', 'required2', 'U4', 'military defence', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'nearby', 'adj./adv.', '/ˌnɪəˈbaɪ/', '附近的;邻近的;在附近', 'The nearby country of Wales was joined to England long ago.', '邻近的威尔士很久以前就被并入了英格兰。', 'History and Traditions', 39, 0, 'senior', 'wordlist', 'required2', 'U4', 'the nearby country', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'ocean', 'n.', '/ˈəʊʃn/', '大海;海洋', 'Down by the sea, you can hear the roar of the ocean waves.', '在海边,你能听到海浪的咆哮声。', 'History and Traditions', 40, 0, 'senior', 'wordlist', 'required2', 'U4', 'the ocean waves', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'port', 'n.', '/pɔːt/', '港口(城市)', 'London is an ancient port city with a very long history.', '伦敦是一座历史悠久的古老港口城市。', 'History and Traditions', 41, 0, 'senior', 'wordlist', 'required2', 'U4', 'an ancient port', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'position', 'n./vt.', '/pəˈzɪʃn/', '位置;姿态;安置', 'Their cameras were positioned on the hill above the lake.', '他们的相机被架设在湖上方的小山上。', 'History and Traditions', 42, 0, 'senior', 'wordlist', 'required2', 'U4', 'be positioned on', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'pub', 'n.', '/pʌb/', '酒吧;酒馆', 'Stop by a village pub and relax with a glass of wine.', '在乡村酒馆停下来,喝一杯葡萄酒放松一下。', 'History and Traditions', 43, 0, 'senior', 'wordlist', 'required2', 'U4', 'a village pub', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'puzzle', 'n./vt.', '/ˈpʌzl/', '谜;疑问;使困惑', 'Knowing British history will help you solve this puzzle.', '了解英国历史会帮你解开这个谜题。', 'History and Traditions', 44, 0, 'senior', 'wordlist', 'required2', 'U4', 'solve this puzzle', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'roar', 'n./vi.', '/rɔː(r)/', '吼叫;咆哮', 'The roar of the ocean waves makes up the music of the coast.', '海浪的咆哮谱成了海岸的乐曲。', 'History and Traditions', 45, 0, 'senior', 'wordlist', 'required2', 'U4', 'the roar of the waves', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'scent', 'n.', '/sent/', '气味;气息;香味', 'Breathe in the sweet scent of fresh flowers in the morning.', '在清晨,深吸鲜花的甜美香气。', 'History and Traditions', 46, 0, 'senior', 'wordlist', 'required2', 'U4', 'the sweet scent', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'snack', 'n.', '/snæk/', '点心;小吃', 'There are some great snacks to try near the old street.', '老街附近有一些很棒的小吃可以尝尝。', 'History and Traditions', 47, 0, 'senior', 'wordlist', 'required2', 'U4', 'great snacks', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'stew', 'n./v.', '/stjuː/', '炖菜;炖;煨', 'Enjoy a delicious traditional Irish beef stew at the pub.', '在酒馆里享用一份美味的传统爱尔兰炖牛肉。', 'History and Traditions', 48, 0, 'senior', 'wordlist', 'required2', 'U4', 'Irish stew', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'striking', 'adj.', '/ˈstraɪkɪŋ/', '引人注目的;显著的', 'A striking image can make the reader eager to read on.', '一个醒目的画面能让读者迫不及待地读下去。', 'History and Traditions', 49, 0, 'senior', 'wordlist', 'required2', 'U4', 'a striking image', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'surround', 'vt.', '/səˈraʊnd/', '围绕;包围', 'Almost everywhere, you will be surrounded by evidence of history.', '几乎在任何地方,你都会被历史的痕迹所环绕。', 'History and Traditions', 50, 0, 'senior', 'wordlist', 'required2', 'U4', 'be surrounded by', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'wine', 'n.', '/waɪn/', '葡萄酒;果酒', 'Relax with a glass of wine and enjoy some traditional music.', '喝一杯葡萄酒,享受一些传统音乐,放松一下。', 'History and Traditions', 51, 0, 'senior', 'wordlist', 'required2', 'U4', 'a glass of wine', NULL);

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4');
DELETE FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('r2u4.01', '①过去分词作定语(前置 broken window / 后置 soldiers wounded)', 'A2', 10, '必修二 U4 — 过去分词修饰名词,表被动或完成,相当于定语从句。单个分词前置(a broken window),带短语后置(soldiers wounded in the war)。与表主动进行的现在分词(-ing)对照:被名词承受的动作用过去分词。', 1, 'required2', 'U4', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('r2u4.02', '②have/get sth done(请人做·遭遇)', 'A2', 10, '必修二 U4 — have/get + 宾语 + 过去分词,表示让别人做某事或某事被完成(get our car battery charged / had a copy boxed)。宾语与分词是被动关系,所以用过去分词,不用 doing/to do。', 2, 'required2', 'U4', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('r2u4.03', '③感官/使役动词 + 宾语 + 过去分词(see/hear/find/want/make)', 'A2', 10, '必修二 U4 — see/hear/find/want/make/keep + 宾语 + 过去分词,作宾语补足语,宾语与分词是被动关系(heard it announced / had her eyes fixed / want it done)。与表主动的 doing/动词原形对照。', 3, 'required2', 'U4', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'We looked up at the ____ window and wondered who had thrown the stone.', 'broken', 'breaking', 'to break', 'break', 'A', 'window 被打破、表被动完成,过去分词 broken 作前置定语。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'The ____ visitors sat down on a bench to rest their feet.', 'tiring', 'tired', 'to tire', 'tire', 'B', 'visitors 感到累、被动状态,tired 作前置定语;tiring 表''令人疲惫的''语义不通。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'The soldiers ____ in the First World War were cared for by the family.', 'wounding', 'to wound', 'wounded', 'wound', 'C', 'soldiers 被打伤、带短语后置,过去分词 wounded 作后置定语。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'Loch Ness is a lake ____ by beautiful natural landscape.', 'surrounding', 'to surround', 'surround', 'surrounded', 'D', 'lake 被环绕,过去分词短语 surrounded by... 作后置定语。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'They sent us a copy ____ in a strong wooden box.', 'boxed', 'boxing', 'to box', 'box', 'A', 'copy 被装箱,过去分词短语 boxed in... 作后置定语。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'The castles ____ by the Normans can still be seen across England.', 'building', 'built', 'to build', 'build', 'B', 'castles 被建造,过去分词短语 built by... 作后置定语。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'We followed a ____ trip that took us to three historic towns.', 'organising', 'to organise', 'well-organised', 'organise', 'C', 'trip 被精心安排,过去分词 well-organised 作前置定语。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'Many words ____ by the Vikings are still used in English today.', 'introducing', 'to introduce', 'introduce', 'introduced', 'D', 'words 被引入,过去分词短语 introduced by... 作后置定语。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'The green hills ____ with sheep made a peaceful picture.', 'dotted', 'dotting', 'to dot', 'dot', 'A', 'hills 被点缀,过去分词短语 dotted with... 作后置定语。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'Most people just use the ____ name ''the UK''.', 'shortening', 'shortened', 'to shorten', 'shorten', 'B', 'name 被缩短,过去分词 shortened 作前置定语。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'The flag ____ as the Union Jack is shared by the four countries.', 'knowing', 'to know', 'known', 'know', 'C', 'be known as 固定搭配,过去分词短语 known as... 作后置定语。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'There were lots of museums full of ancient relics ____ from all over the UK.', 'collecting', 'to collect', 'collect', 'collected', 'D', 'relics 被收集,过去分词短语 collected from... 作后置定语。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'We saw beautifully ____ stars arrive at the gallery opening.', 'dressed', 'dressing', 'to dress', 'dress', 'A', 'stars 被打扮,过去分词 dressed(beautifully dressed)作前置定语。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'The names of many places ____ behind by the Vikings still exist.', 'leaving', 'left', 'to leave', 'leave', 'B', 'places(的名字)被留下,过去分词短语 left behind 作后置定语。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'A country ____ by four different groups has a very rich history.', 'conquering', 'to conquer', 'conquered', 'conquer', 'C', 'country 被征服,过去分词短语 conquered by... 作后置定语。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'She bought a copy of the famous painting ____ in London.', 'printing', 'to print', 'print', 'printed', 'D', 'copy 被印制,过去分词短语 printed in... 作后置定语。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'The ____ guidebook helped us find every historic site easily.', 'updated', 'updating', 'to update', 'update', 'A', 'guidebook 被更新,过去分词 updated 作前置定语。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'Cameras ____ on the hill recorded the lake all day long.', 'positioning', 'positioned', 'to position', 'position', 'B', 'cameras 被架设,过去分词短语 positioned on... 作后置定语。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'The new words ____ by the Normans came mostly from French.', 'bringing', 'to bring', 'brought', 'bring', 'C', 'words 被诺曼人带入,过去分词短语 brought by... 作后置定语。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.01'), 'Towns and roads ____ by the Romans were a great achievement.', 'building', 'to build', 'build', 'built', 'D', 'towns and roads 被建造,过去分词短语 built by... 作后置定语。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'Judy and I had our car ____ in an underground car park.', 'parked', 'parking', 'to park', 'park', 'A', 'have sth done:car 被停放,过去分词 parked 作宾补。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'Near the square we could get our car battery ____ quickly.', 'charging', 'charged', 'to charge', 'charge', 'B', 'get sth done:battery 被充电,过去分词 charged 作宾补。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'She had a copy of the painting ____ to keep it safe on the way.', 'boxing', 'to box', 'boxed', 'box', 'C', 'have sth done:copy 被装箱,过去分词 boxed 作宾补。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'We must get the old castle wall ____ before winter comes.', 'repairing', 'to repair', 'repair', 'repaired', 'D', 'get sth done:wall 被修理,过去分词 repaired 作宾补。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'The hostel had the visitors'' bags ____ at the front desk.', 'checked', 'checking', 'to check', 'check', 'A', 'have sth done:bags 被检查,过去分词 checked 作宾补。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'I''d like to have these old photos of the temple ____ this week.', 'printing', 'printed', 'to print', 'print', 'B', 'have sth done:photos 被冲印,过去分词 printed 作宾补。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'Before the trip, we got our tickets ____ at the station office.', 'booking', 'to book', 'booked', 'book', 'C', 'get sth done:tickets 被预订,过去分词 booked 作宾补。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'The museum had the ancient relics ____ in glass cases.', 'displaying', 'to display', 'display', 'displayed', 'D', 'have sth done:relics 被展示,过去分词 displayed 作宾补。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'She wanted to get the guidebook ____ into Chinese for her parents.', 'translated', 'translating', 'to translate', 'translate', 'A', 'get sth done:guidebook 被翻译,过去分词 translated 作宾补。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'We had our audio guides ____ at the service desk inside the gallery.', 'collecting', 'collected', 'to collect', 'collect', 'B', 'have sth done:guides 被领取,过去分词 collected 作宾补。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'The family had their old mansion ____ in soft yellow light at night.', 'lighting', 'to light', 'lit', 'light', 'C', 'have sth done:mansion 被照亮,过去分词 lit 作宾补。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'He got his name ____ in the family tree, just like his ancestors.', 'recording', 'to record', 'record', 'recorded', 'D', 'get sth done:name 被记录,过去分词 recorded 作宾补。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'Before leaving Pingyao, Paul had a few snacks ____ for the long train ride.', 'packed', 'packing', 'to pack', 'pack', 'A', 'have sth done:snacks 被打包,过去分词 packed 作宾补。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'We should get the courtyard floor ____ before the guests arrive.', 'cleaning', 'cleaned', 'to clean', 'clean', 'B', 'get sth done:floor 被打扫,过去分词 cleaned 作宾补。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'The shop will have your purchase ____ to your hotel for free.', 'delivering', 'to deliver', 'delivered', 'deliver', 'C', 'have sth done:purchase 被送达,过去分词 delivered 作宾补。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'They had the historic bridge ____ exactly as it had once looked.', 'rebuilding', 'to rebuild', 'rebuild', 'rebuilt', 'D', 'have sth done:bridge 被重建,过去分词 rebuilt 作宾补。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'I want to get my room ____ before I go out to see the city wall.', 'tidied', 'tidying', 'to tidy', 'tidy', 'A', 'get sth done:room 被整理,过去分词 tidied 作宾补。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'The hotel had a map of the old town ____ for every guest.', 'preparing', 'prepared', 'to prepare', 'prepare', 'B', 'have sth done:map 被准备好,过去分词 prepared 作宾补。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'She got the broken camera ____ just in time for the trip to Scotland.', 'fixing', 'to fix', 'fixed', 'fix', 'C', 'get sth done:camera 被修好,过去分词 fixed 作宾补。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.02'), 'We had our coats and bags ____ before entering the National Gallery.', 'storing', 'to store', 'store', 'stored', 'D', 'have sth done:coats and bags 被寄存,过去分词 stored 作宾补。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'At the service desk, we heard it ____ that no audio guides were left.', 'announced', 'announcing', 'to announce', 'announce', 'A', 'hear sth done:it(消息)被宣布,过去分词 announced 作宾补。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'Judy had her eyes ____ on Van Gogh''s Sunflowers for a long time.', 'fixing', 'fixed', 'to fix', 'fix', 'B', 'have sth done:eyes 被定住,过去分词 fixed 作宾补。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'We found ourselves ____ by the huge crowd at the entrance.', 'surprising', 'to surprise', 'surprised', 'surprise', 'C', 'find sb done:ourselves 被惊到,过去分词 surprised 作宾补。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'The guide wanted the relics ____ exactly where they had been found.', 'keeping', 'to keep', 'keep', 'kept', 'D', 'want sth done:relics 被保留,过去分词 kept 作宾补。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'Standing on the wall, we saw the whole town ____ in golden evening light.', 'bathed', 'bathing', 'to bathe', 'bathe', 'A', 'see sth done:town 被笼罩,过去分词 bathed 作宾补。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'She heard her family name ____ aloud during the temple ceremony.', 'calling', 'called', 'to call', 'call', 'B', 'hear sth done:name 被叫到,过去分词 called 作宾补。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'The receptionist found the guest book ____ open at the right page.', 'leaving', 'to leave', 'left', 'leave', 'C', 'find sth done:book 被翻开放着,过去分词 left 作宾补。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'Visitors want the historic buildings ____ for future generations.', 'protecting', 'to protect', 'protect', 'protected', 'D', 'want sth done:buildings 被保护,过去分词 protected 作宾补。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'We watched the old gate slowly ____ by the workers at sunset.', 'closed', 'closing', 'to close', 'close', 'A', 'watch sth done:gate 被关上(强调被动),过去分词 closed 作宾补。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'From the hill, they kept the lake ____ in view all afternoon.', 'holding', 'held', 'to hold', 'hold', 'B', 'keep sth done:lake 被保持在视野中,过去分词 held 作宾补。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'He found the museum doors ____ when he arrived early in the morning.', 'locking', 'to lock', 'locked', 'lock', 'C', 'find sth done:doors 被锁着,过去分词 locked 作宾补。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'The teacher wanted the report on British history ____ by Friday.', 'finishing', 'to finish', 'finish', 'finished', 'D', 'want sth done:report 被完成,过去分词 finished 作宾补。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'At the entrance, I heard my ticket number ____ over the speaker.', 'read', 'reading', 'to read', 'ready', 'A', 'hear sth done:number 被读出,过去分词 read(/red/)作宾补。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'The crowd saw the famous painting finally ____ to a safer wall.', 'moving', 'moved', 'to move', 'move', 'B', 'see sth done:painting 被移动,过去分词 moved 作宾补。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'She wanted her photos of Loch Ness ____ in a small album.', 'arranging', 'to arrange', 'arranged', 'arrange', 'C', 'want sth done:photos 被整理,过去分词 arranged 作宾补。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'We found the courtyard beautifully ____ with red lanterns for the feast.', 'decorating', 'to decorate', 'decorate', 'decorated', 'D', 'find sth done:courtyard 被装饰,过去分词 decorated 作宾补。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'The visitors heard the old story ____ again by a local guide.', 'told', 'telling', 'to tell', 'tell', 'A', 'hear sth done:story 被讲述,过去分词 told 作宾补。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'He wanted the broken castle gate ____ before the tourists came.', 'mending', 'mended', 'to mend', 'mend', 'B', 'want sth done:gate 被修补,过去分词 mended 作宾补。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'From the boat, we saw the whole valley ____ in thick morning mist.', 'covering', 'to cover', 'covered', 'cover', 'C', 'see sth done:valley 被覆盖,过去分词 covered 作宾补。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4' AND code='r2u4.03'), 'The committee wants these old traditions ____ alive for many years.', 'keeping', 'to keep', 'keep', 'kept', 'D', 'want sth done:traditions 被保持,过去分词 kept 作宾补。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE volume='required2' AND unit='U4';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'What''s in a Name?', 'Many people are confused by the names United Kingdom, Great Britain, Britain and England. So what is the difference between them? Getting to know a little British history will help you solve this puzzle. In the 16th century, the nearby country of Wales was joined to the Kingdom of England. Later, in the 18th century, Scotland was added to create the Kingdom of Great Britain. In the 19th century, Ireland was joined too, forming the United Kingdom of Great Britain and Ireland. Finally, in the 20th century, the southern part of Ireland broke away. This gave us the full name we use today: the United Kingdom of Great Britain and Northern Ireland. Most people just use the shortened name, the UK. People from the UK are called British, which is why the country is also called Britain or Great Britain.', '说明·英国的几个名字由来', 140, '[{"q":"What does the writer say can help solve the puzzle of the names?","answer":"A","options":["Learning a little about British history.","Visiting every city in England.","Asking only people from Wales.","Reading a modern travel map."],"explanation":"原文 ''Getting to know a little British history will help you solve this puzzle'' 的转述。"},{"q":"Which country was joined to England earliest?","answer":"B","options":["Scotland.","Wales.","Ireland.","Northern Ireland."],"explanation":"原文 16 世纪先并入 Wales,故威尔士最早。"},{"q":"Why is the UK also called Britain?","answer":"A","options":["Because its people are known as British.","Because it has only one country.","Because the map shows it that way.","Because Ireland is still part of it."],"explanation":"末句 ''People from the UK are called British, which is why…'' 的转述。"}]'::jsonb, '[{"word":"kingdom","cn":"王国"},{"word":"puzzle","cn":"谜;疑问"},{"word":"nearby","cn":"邻近的"}]'::jsonb, 2, 'required2', 'U4');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Four Groups Who Shaped Britain', 'Almost everywhere you go in the UK, you are surrounded by evidence of four groups of people who took over at different times. The first group, the Romans, arrived in the first century. Among their great achievements were the towns and roads they built. Next came the Anglo-Saxons in the fifth century. They introduced the beginnings of the English language and changed the way houses were built. The Vikings then came in the eighth century. They left behind lots of new vocabulary, as well as the names of many places across the UK. The last group were the Normans, who were French. After the well-known Battle of Hastings in the eleventh century, they conquered England. They had castles built all around the country and made changes to the legal system. Because the Normans spoke French, many French words slowly entered the English language. Each group left its own mark on the country.', '说明·先后占领英国的四群人', 152, '[{"q":"What were two great achievements of the Romans?","answer":"B","options":["The castles and the new flag.","Building towns and roads across the land.","The English language and houses.","The legal system and French words."],"explanation":"原文 ''the towns and roads they built''(罗马人的成就)。"},{"q":"What did the Vikings mainly leave behind?","answer":"C","options":["New roads and bridges.","A brand-new legal system.","New words and many place names.","Large stone castles."],"explanation":"原文 Vikings ''left behind lots of new vocabulary… the names of many places'' 的转述。"},{"q":"What happened after the Battle of Hastings?","answer":"D","options":["The Romans returned to Britain.","The Anglo-Saxons left the country.","All castles were pulled down.","The Normans conquered England."],"explanation":"原文 ''After the… Battle of Hastings… they conquered England''(诺曼人)。"}]'::jsonb, '[{"word":"conquer","cn":"征服"},{"word":"battle","cn":"战役"},{"word":"achievement","cn":"成就"}]'::jsonb, 2, 'required2', 'U4');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Historic London', 'London sits upon the River Thames in the southeast of England. It is the capital of the United Kingdom and, with almost nine million people, one of Europe''s largest cities. London is also an ancient port city, with a history that dates all the way back to Roman times. Because of this, the UK''s capital is a great place to start exploring the country''s past. There are countless historic sites to see, and many museums filled with ancient relics from all over the UK. Visitors can stand on Tower Bridge, a symbol of the city, or look up at the famous bell known as Big Ben. They can walk through Westminster Abbey, where royal funerals and most coronations take place, and enjoy the great art collection kept inside the National Gallery. London is a fascinating mix of old and new, and if you keep your eyes open, you can see both its past and its present at once.', '说明·历史悠久的伦敦', 158, '[{"q":"Why is London a good place to start exploring the UK''s past?","answer":"A","options":["Because this old harbour city has such a long past.","Because it is the smallest city.","Because it has no museums.","Because it is far from the sea."],"explanation":"原文 ''an ancient port city… dates all the way back to Roman times… a great place to start'' 的转述。"},{"q":"What can visitors do at Westminster Abbey?","answer":"B","options":["Charge their car battery.","See where royal funerals and coronations take place.","Buy local beer and stew.","Watch a football match."],"explanation":"原文 ''Westminster Abbey, where royal funerals and most coronations take place'' 的转述。"},{"q":"What is kept inside the National Gallery?","answer":"C","options":["A famous old bell.","The king''s family tree.","A great art collection.","An underground car park."],"explanation":"原文 ''the great art collection kept inside the National Gallery'' 的转述。"}]'::jsonb, '[{"word":"port","cn":"港口"},{"word":"gallery","cn":"美术馆"},{"word":"fascinating","cn":"迷人的"}]'::jsonb, 2, 'required2', 'U4');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'The Legend of Loch Ness', 'Loch Ness is a long, deep lake in the north of Scotland, surrounded by beautiful natural landscape that makes it look amazing. For many years, visitors have been attracted by a famous story: some people believe a large, mysterious animal lives deep in its dark water. Whether the story is true or not, it brings travellers from all over the world. Carl and his friends were among them. They were attracted by the legend and decided to watch over the lake themselves. With their cameras and binoculars positioned on a hill above the water, they waited quietly for hours, their eyes fixed on the surface. They stayed with a generous local family, who offered them fresh bread with butter and homemade honey. The young people never saw the famous animal, but they agreed that the peaceful landscape and the warm welcome had already made the trip worth it.', '记叙·苏格兰尼斯湖的传说', 148, '[{"q":"What attracts many visitors to Loch Ness?","answer":"D","options":["A large modern shopping centre.","A free music festival each summer.","A very long railway station.","A famous story about a mysterious animal."],"explanation":"原文 ''a famous story: some people believe a large, mysterious animal lives'' 的转述。"},{"q":"How did Carl and his friends watch the lake?","answer":"A","options":["With cameras and binoculars set up on a hill.","From a boat in the middle of the water.","Through the windows of a museum.","By swimming close to the surface."],"explanation":"原文 ''cameras and binoculars positioned on a hill above the water'' 的转述。"},{"q":"Why did they feel the trip was worth it in the end?","answer":"B","options":["They finally saw the mysterious animal.","The lovely scenery and warm welcome were enough.","They won a prize for their photos.","They bought many cheap souvenirs."],"explanation":"末句 ''the peaceful landscape and the warm welcome had already made the trip worth it'' 的转述。"}]'::jsonb, '[{"word":"landscape","cn":"风景"},{"word":"surround","cn":"环绕"},{"word":"generous","cn":"慷慨的"}]'::jsonb, 2, 'required2', 'U4');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Beautiful Ireland and Its Traditions', 'Ireland''s beautiful countryside has always had a great influence on its people and their traditions. The country has a long history of producing great writers and poets. Its lovely countryside offers something for each of the senses. The peaceful landscape of the green island and its many counties is a true feast for the eyes, with rolling green hills dotted with sheep and cattle. Down by the sea, the roar of the ocean waves and the cries of the seabirds make up the music of the coast. On a quiet morning in the mountains, you can feel the sun on your skin and breathe in the sweet scent of fresh flowers, while birds greet the new day with their song. With all this beauty, it is no surprise that Ireland has strong traditions of music, dancing and dining. To experience them, stop by a village pub and relax with a glass of wine or a local beer, or enjoy a delicious traditional beef stew.', '说明·爱尔兰乡村与传统', 164, '[{"q":"What has greatly influenced the people and traditions of Ireland?","answer":"C","options":["Its large modern cities.","Its busy port trade.","Its beautiful countryside.","Its long, cold winters."],"explanation":"首句 ''Ireland''s beautiful countryside has always had a great influence'' 的转述。"},{"q":"What makes up ''the music of the coast''?","answer":"D","options":["Songs played in village pubs.","Traditional dancing on the hills.","The bells of an old church.","The sound of the waves and the seabirds."],"explanation":"原文 ''the roar of the ocean waves and the cries of the seabirds make up the music of the coast'' 的转述。"},{"q":"What does the writer suggest doing to experience Irish traditions?","answer":"A","options":["Stopping by a village pub for a drink and a meal.","Climbing the highest mountain.","Visiting a large art gallery.","Staying inside all morning."],"explanation":"末句 ''stop by a village pub and relax… enjoy a… beef stew'' 的转述。"}]'::jsonb, '[{"word":"scent","cn":"香味"},{"word":"feast","cn":"盛宴"},{"word":"stew","cn":"炖菜"}]'::jsonb, 2, 'required2', 'U4');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'One Land, Many Traditions', 'The four countries that belong to the United Kingdom work together in some ways, yet each keeps its own traditions. They use the same flag, known as the Union Jack, and they share the same currency and military defence. In these ways they act as one nation. However, in other ways they remain quite different. England, Wales, Scotland and Northern Ireland each have their own education and legal systems. They also keep their own national days and national dishes, and they are proud of these differences. Most surprising of all to many visitors, each country even sends its own football team to big competitions such as the World Cup. So when you travel around the UK, do not expect everything to be the same everywhere. Part of the fun is discovering how four neighbours can share so much and still hold on to what makes each of them special.', '说明·联合王国共有与差异的传统', 149, '[{"q":"What do the four countries share?","answer":"B","options":["The same education system.","The same flag, currency and military defence.","The same national dishes.","A single football team."],"explanation":"原文 ''use the same flag… share the same currency and military defence'' 的转述。"},{"q":"In what way do the four countries differ?","answer":"C","options":["They use different flags.","They use different money.","They have separate education and legal systems.","They share one national day."],"explanation":"原文 ''each have their own education and legal systems'' 的转述。"},{"q":"What surprises many visitors the most?","answer":"D","options":["Each country has the same dishes.","They all use the euro.","They never compete with each other.","Each one fields a separate football team at big events."],"explanation":"原文 ''each country even sends its own football team to big competitions'' 的转述。"}]'::jsonb, '[{"word":"belong","cn":"属于"},{"word":"currency","cn":"货币"},{"word":"legal","cn":"法律的"}]'::jsonb, 2, 'required2', 'U4');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE volume='required2' AND unit='U4';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required2', 'U4', 'A Day at the National Gallery', 'Last week Judy and I spent a whole day in London. First we had our car (1)____ in an underground car park, where we could also get the car battery (2)____. Then we walked to the National Gallery. We were (3)____ by the large number of visitors and the amount of (4)____ at the entrance. When we reached the service desk, we heard it (5)____ that no audio guides were left, so we had to explore on our own. Inside, Judy had her eyes (6)____ on Van Gogh''s Sunflowers for a long time. It was hard to (7)____ the painting because of the crowd. Before we left, she had a (8)____ of the painting boxed to (9)____ that it would arrive home safely. It was a tiring but wonderful day, and we agreed it was one of the best (10)____ of our whole trip.', 144, 2, '[{"q":"1","answer":"A","options":["parked","sold","lost","eaten"],"explanation":"have the car parked 把车停好。"},{"q":"2","answer":"B","options":["broken","charged","thrown","hidden"],"explanation":"get the battery charged 给电池充电。"},{"q":"3","answer":"C","options":["bored","sold","surprised","freed"],"explanation":"be surprised by 被……惊到。"},{"q":"4","answer":"D","options":["money","water","snow","noise"],"explanation":"the amount of noise 噪音之大。"},{"q":"5","answer":"A","options":["announced","asked","drawn","carved"],"explanation":"hear it announced that 听到宣布……。"},{"q":"6","answer":"B","options":["lost","fixed","sold","left"],"explanation":"have her eyes fixed on 目不转睛地盯着。"},{"q":"7","answer":"C","options":["forget","break","approach","sell"],"explanation":"approach the painting 靠近那幅画。"},{"q":"8","answer":"D","options":["price","noise","weather","copy"],"explanation":"a copy of the painting 一份复制品。"},{"q":"9","answer":"A","options":["ensure","forget","refuse","leave"],"explanation":"ensure that 确保……。"},{"q":"10","answer":"B","options":["mistakes","memories","prices","machines"],"explanation":"the best memories 最美好的回忆。"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required2', 'U4', 'Visiting Qufu', 'When William visited Qufu, a Chinese student named Xiao Kong showed him around. Xiao Kong is a (1)____ of Confucius, and his name is recorded in the family tree. He told William that Confucius is one of his favourite (2)____. They first walked through the Temple of Confucius, then visited the Kong Family (3)____. William noticed that no modern building was allowed to be more (4)____ than the historic ones. He said this was the (5)____ why his own hometown felt so similar. Both places, he explained, are proud of a famous (6)____ who was born there. As they walked, Xiao Kong kept his eyes (7)____ for small details that most tourists miss. He believed that to truly understand a (8)____ site, you must learn about its history first. William was (9)____ to hear so many interesting stories. By the end of the day, he had a much deeper (10)____ for Chinese culture and traditions.', 155, 2, '[{"q":"1","answer":"C","options":["price","machine","descendant","garden"],"explanation":"a descendant of 的后代。"},{"q":"2","answer":"D","options":["machines","prices","gardens","philosophers"],"explanation":"favourite philosophers 最喜欢的哲学家。"},{"q":"3","answer":"A","options":["Mansion","price","noise","weather"],"explanation":"Kong Family Mansion 孔府。"},{"q":"4","answer":"B","options":["cheap","noticeable","quiet","empty"],"explanation":"more noticeable 更引人注目。"},{"q":"5","answer":"C","options":["price","noise","reason","garden"],"explanation":"the reason why 原因。"},{"q":"6","answer":"D","options":["machine","price","garden","person"],"explanation":"a famous person 一位名人。"},{"q":"7","answer":"A","options":["open","closed","shut","sold"],"explanation":"keep your eyes open 留心观察。"},{"q":"8","answer":"B","options":["price","historic","noise","weather"],"explanation":"a historic site 历史遗迹。"},{"q":"9","answer":"C","options":["afraid","angry","eager","bored"],"explanation":"be eager to hear 渴望听到。"},{"q":"10","answer":"D","options":["price","machine","garden","appreciation"],"explanation":"appreciation for 对……的欣赏。"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required2', 'U4', 'Understanding English Idioms', 'Learning a language is not only about words; it is also about idioms. An idiom is an expression whose meaning is different from each (1)____ word in it. For example, when British people say someone has an ''Achilles'' heel'', they do not mean a real (2)____. They mean a person''s weakest point. Some idioms paint a (3)____ that gives a hint about their meaning, while others can only be understood from the (4)____ in which they appear. If you are (5)____ to learn a foreign culture, idioms are a great place to start. They often come from old stories, history or (6)____ that people have followed for years. When you are not sure what an idiom (7)____, the best thing is to ask politely. Little by little, you will (8)____ how colourful a language can be. Knowing idioms also helps you (9)____ native speakers more easily and feel less like a stranger. So keep your ears (10)____, and write down every new idiom you hear.', 165, 2, '[{"q":"1","answer":"A","options":["individual","cheap","empty","quiet"],"explanation":"each individual word 每个单独的词。"},{"q":"2","answer":"B","options":["price","heel","noise","garden"],"explanation":"a real heel 真正的脚跟。"},{"q":"3","answer":"C","options":["price","noise","picture","machine"],"explanation":"paint a picture 描绘画面。"},{"q":"4","answer":"D","options":["price","noise","weather","context"],"explanation":"the context in which 出现的语境。"},{"q":"5","answer":"A","options":["eager","afraid","sorry","late"],"explanation":"be eager to 渴望。"},{"q":"6","answer":"B","options":["prices","customs","noises","machines"],"explanation":"customs 风俗习惯。"},{"q":"7","answer":"C","options":["sells","buys","means","throws"],"explanation":"what an idiom means 习语的意思。"},{"q":"8","answer":"D","options":["forget","lose","drop","appreciate"],"explanation":"appreciate 欣赏、领会。"},{"q":"9","answer":"A","options":["greet","sell","forget","lose"],"explanation":"greet native speakers 与母语者打招呼。"},{"q":"10","answer":"B","options":["closed","open","shut","sold"],"explanation":"keep your ears open 注意聆听。"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required2', 'U4', 'Different Tea Cultures', 'Tea is enjoyed all around the world, but every country has its own (1)____. In China, where tea has a very long (2)____, people often drink it without milk and value its natural (3)____. Friends greet each other and then sit down to share a quiet pot of tea together. In Britain, tea is also an important (4)____. Many families enjoy ''afternoon tea'', and they usually add milk and sometimes a little (5)____ to make it sweet. People often eat small (6)____ such as cakes and sandwiches with their tea. To make a good cup, the British (7)____ that the water must be very hot. In some places, you can get your tea (8)____ to your table in a beautiful pot. Whatever the country, tea brings people together and helps them (9)____. Trying a new tea custom is a simple but lovely way to (10)____ another culture first-hand.', 148, 2, '[{"q":"1","answer":"C","options":["price","noise","custom","machine"],"explanation":"its own custom 自己的风俗。"},{"q":"2","answer":"D","options":["price","noise","garden","history"],"explanation":"a long history 悠久的历史。"},{"q":"3","answer":"A","options":["scent","price","noise","weather"],"explanation":"natural scent 天然的香气。"},{"q":"4","answer":"B","options":["price","custom","noise","machine"],"explanation":"an important custom 重要的习俗。"},{"q":"5","answer":"C","options":["stone","paper","honey","metal"],"explanation":"add honey 加蜂蜜。"},{"q":"6","answer":"D","options":["prices","noises","machines","snacks"],"explanation":"small snacks 小点心。"},{"q":"7","answer":"A","options":["ensure","sell","buy","lose"],"explanation":"ensure that 确保。"},{"q":"8","answer":"B","options":["sold","delivered","lost","broken"],"explanation":"get your tea delivered 让茶被送到。"},{"q":"9","answer":"C","options":["fail","forget","relax","leave"],"explanation":"helps them relax 帮他们放松。"},{"q":"10","answer":"D","options":["forget","lose","sell","experience"],"explanation":"experience another culture 体验另一种文化。"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required2', 'U4', 'A Trip to Pingyao', 'Paul, a backpacker, was staying at a youth hostel in Pingyao. He was (1)____ to explore the ancient town, so the receptionist gave him a map. First he walked along Ming-Qing Street, where he tried some local (2)____ that smelled wonderful. He was (3)____ by how well the old buildings had been kept. Next he visited a famous family (4)____, with its quiet rooms and peaceful gardens. Paul said it was like walking into (5)____. Later he climbed the city (6)____, which surrounded the whole town like a stone belt. From the top he could (7)____ the rooftops bathed in golden evening light. He had not (8)____ such a beautiful view, and he felt a little surprised. Before leaving, he had a few (9)____ packed for the long train ride home. Paul agreed that learning about a place''s history makes a (10)____ much more enjoyable.', 145, 2, '[{"q":"1","answer":"A","options":["eager","afraid","sorry","angry"],"explanation":"be eager to 渴望。"},{"q":"2","answer":"B","options":["prices","snacks","noises","machines"],"explanation":"local snacks 当地小吃。"},{"q":"3","answer":"C","options":["bored","freed","surprised","sold"],"explanation":"be surprised by 被……惊到。"},{"q":"4","answer":"D","options":["price","noise","weather","courtyard"],"explanation":"a family courtyard 家族庭院。"},{"q":"5","answer":"A","options":["history","money","water","snow"],"explanation":"walking into history 走进历史。"},{"q":"6","answer":"B","options":["price","wall","noise","garden"],"explanation":"the city wall 城墙。"},{"q":"7","answer":"C","options":["sell","forget","see","lose"],"explanation":"see the rooftops 看到屋顶。"},{"q":"8","answer":"D","options":["sold","lost","broken","expected"],"explanation":"had not expected 没有料到。"},{"q":"9","answer":"A","options":["snacks","prices","noises","machines"],"explanation":"a few snacks 一些小吃。"},{"q":"10","answer":"B","options":["price","visit","noise","machine"],"explanation":"makes a visit enjoyable 让一次参观更愉快。"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required2', 'U4', 'A British Street Festival', 'Every summer, our small British town holds a street (1)____ that brings the whole community together. People work hard for weeks: they have the streets (2)____ with colourful flags, and they get the old town square (3)____ for the big day. In the morning, you can hear the festival (4)____ over loud speakers, and a happy (5)____ soon gathers in the square. There are stalls selling cakes, local (6)____ and other small snacks. A band plays while families relax with a cup of tea or a glass of (7)____. Children watch dancers, their eyes (8)____ on the bright costumes. The festival is a wonderful way to keep our local (9)____ alive and to share them with visitors. By the time the sun goes down, everyone agrees it has been a (10)____ day to remember.', 134, 2, '[{"q":"1","answer":"C","options":["price","noise","festival","machine"],"explanation":"a street festival 街头节日。"},{"q":"2","answer":"D","options":["sold","lost","broken","decorated"],"explanation":"have the streets decorated 把街道装饰好。"},{"q":"3","answer":"A","options":["prepared","sold","lost","broken"],"explanation":"get the square prepared 把广场准备好。"},{"q":"4","answer":"B","options":["price","announced","noise","weather"],"explanation":"hear the festival announced 听到节日被宣布。"},{"q":"5","answer":"C","options":["price","machine","crowd","garden"],"explanation":"a happy crowd 欢乐的人群。"},{"q":"6","answer":"D","options":["prices","noises","machines","snacks"],"explanation":"local snacks 当地小吃。"},{"q":"7","answer":"A","options":["wine","stone","paper","metal"],"explanation":"a glass of wine 一杯葡萄酒。"},{"q":"8","answer":"B","options":["sold","fixed","lost","broken"],"explanation":"their eyes fixed on 目不转睛地盯着。"},{"q":"9","answer":"C","options":["prices","noises","traditions","machines"],"explanation":"local traditions 当地传统。"},{"q":"10","answer":"D","options":["cheap","empty","quiet","striking"],"explanation":"a striking day 难忘的一天。"}]'::jsonb, 6);

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE volume='required2' AND unit='U4';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U4 听力·对话 Planning a Day in London', '必修二 U4 · dialogue', 3, 'Emma: So, where should we start our day in London, Tom?
Tom: Let''s begin near the river. London is an ancient port city with a long history.
Emma: Great. Can we see Tower Bridge first? People say it''s a symbol of the city.
Tom: Of course. After that, we can visit the National Gallery to see the paintings.
Emma: Wonderful! But first I need to get my phone charged. The battery is almost dead.
Tom: No problem. There''s a café nearby where you can charge it.
Emma: Perfect. Then let''s keep our eyes open for the historic sites along the way.', 'Emma 和 Tom 商量在伦敦怎样开始一天;Tom 建议从河边开始,因为伦敦是历史悠久的古老港口城市;先去看作为城市象征的塔桥,再去国家美术馆看画;Emma 想先给手机充电,Tom 说附近咖啡馆可以充;然后一路留心历史古迹。', 'uk_female', '[{"q":"Where does Tom suggest starting their day?","type":"choice","answer":"A","options":["Near the river.","At the airport.","In a shopping mall.","Outside the city."]},{"q":"What does Tom say about London?","type":"choice","answer":"B","options":["It has no history.","It is an ancient port city.","It is a very small town.","It is far from the river."]},{"q":"What is Tower Bridge said to be?","type":"choice","answer":"A","options":["A symbol of the city.","A new railway station.","A modern art gallery.","A famous restaurant."]},{"q":"Why does Emma need to stop first?","type":"choice","answer":"B","options":["To buy a new map.","To get her phone charged.","To meet a friend.","To have lunch."]},{"q":"What will they do along the way?","type":"choice","answer":"C","options":["Sleep on a bench.","Look for a car park only.","Keep their eyes open for historic sites.","Avoid all old buildings."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U4');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U4 听力·短文 The Names of the UK', '必修二 U4 · passage', 2, 'Many people are confused by the different names for the UK.
In the 16th century, Wales was joined to the Kingdom of England.
Later, Scotland and then Ireland were added.
In the 20th century, the southern part of Ireland broke away.
Today most people simply use the shortened name, the UK.', '许多人被英国的各种名字弄糊涂;16世纪威尔士并入英格兰王国;后来苏格兰、再后来爱尔兰也加入;20世纪爱尔兰南部脱离;如今大多数人就用简称 the UK。', 'uk_female', '[{"q":"What confuses many people?","type":"choice","answer":"D","options":["The weather in London.","The price of tickets.","The number of museums.","The different names for the UK."]},{"q":"Which country was joined to England in the 16th century?","type":"choice","answer":"A","options":["Wales.","Scotland.","France.","Ireland."]},{"q":"What happened in the 20th century?","type":"choice","answer":"B","options":["Wales joined England.","The south of Ireland broke away.","Scotland left the UK.","London was built."]},{"q":"What name do most people use today?","type":"choice","answer":"C","options":["Great England.","The Roman land.","The UK.","The Kingdom of Wales."]},{"q":"In what order were the countries added?","type":"choice","answer":"D","options":["Ireland, then Wales, then Scotland.","Scotland, then Ireland, then Wales.","France, then Wales, then Scotland.","Wales, then Scotland, then Ireland."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U4');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U4 听力·对话 A Traditional Village Pub', '必修二 U4 · dialogue', 3, 'Lily: This village pub looks so old and cosy. Is it part of a tradition here?
Jack: Yes, the pub is at the heart of village life. People come here to meet friends.
Lily: What should I try? I''d love to taste something traditional.
Jack: You must try the beef stew. And many people enjoy a glass of wine or a local beer.
Lily: That sounds lovely. Is there music too?
Jack: Yes, sometimes there''s traditional music and dancing in the evening.
Lily: How wonderful! It''s a great way to experience the local culture first-hand.', 'Lily 觉得乡村酒馆古老温馨,问这是否是当地传统;Jack 说酒馆是村庄生活的中心,人们来这儿见朋友;推荐 Lily 尝炖牛肉,还有人喝葡萄酒或本地啤酒;晚上有时有传统音乐和舞蹈;Lily 觉得这是亲身体验当地文化的好方式。', 'uk_female', '[{"q":"What does Jack say the pub is?","type":"choice","answer":"A","options":["At the heart of village life.","A brand-new building.","A place no one visits.","An empty old house."]},{"q":"What traditional food does Jack suggest trying?","type":"choice","answer":"B","options":["Fried rice.","Beef stew.","Cold pizza.","Sweet cakes."]},{"q":"What drinks do many people enjoy there?","type":"choice","answer":"C","options":["Only cold water.","Hot coffee only.","Wine or local beer.","Fruit juice only."]},{"q":"What sometimes happens in the evening?","type":"choice","answer":"D","options":["The pub closes early.","Everyone goes home.","No one speaks.","There is traditional music and dancing."]},{"q":"How does Lily feel about the pub?","type":"choice","answer":"A","options":["It''s a great way to experience local culture.","It is boring and cold.","It is too modern.","It has nothing to offer."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U4');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U4 听力·短文 Four Groups in British History', '必修二 U4 · passage', 2, 'Four groups of people took over Britain at different times.
The Romans came first and built many towns and roads.
Then the Anglo-Saxons introduced the beginnings of the English language.
The Vikings left behind new words and many place names.
Finally the Normans conquered England and changed the legal system.', '四群人在不同时期先后占领了英国;罗马人最先到来,修建了许多城镇和道路;接着盎格鲁-撒克逊人带来了英语的雏形;维京人留下了新词和许多地名;最后诺曼人征服了英格兰并改变了法律制度。', 'uk_female', '[{"q":"How many groups took over Britain?","type":"choice","answer":"B","options":["Two.","Four.","Six.","Ten."]},{"q":"What did the Romans build?","type":"choice","answer":"C","options":["Castles only.","A new flag.","Many towns and roads.","A football team."]},{"q":"What did the Vikings leave behind?","type":"choice","answer":"D","options":["Only castles.","A new legal system.","Roman roads.","New words and place names."]},{"q":"What did the Normans do?","type":"choice","answer":"A","options":["They conquered England and changed the law.","They left Britain at once.","They built no castles.","They spoke only English."]},{"q":"Who introduced the beginnings of English?","type":"choice","answer":"B","options":["The Romans.","The Anglo-Saxons.","The Vikings.","The Normans."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U4');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U4 听力·对话 Back from Pingyao', '必修二 U4 · dialogue', 3, 'Anna: I''ve just come back from Pingyao, and it was amazing!
Ben: Oh, I love Pingyao! Did you walk along Ming-Qing Street?
Anna: Of course, but I didn''t expect to see so many tourists there.
Ben: I know what you mean. But the snacks on that street are wonderful, aren''t they?
Anna: They really are. I also climbed the old city wall. It was like walking into history.
Ben: Did you visit the famous family courtyard as well?
Anna: Yes, but it wasn''t as big as I had expected. Still, the whole trip was great fun.', 'Anna 刚从平遥回来,觉得很棒;Ben 也爱平遥,问她有没有走明清街;Anna 走了,但没料到游客那么多;Ben 说那条街的小吃很棒;Anna 还爬了古城墙,像走进了历史;问她有没有去著名的家族庭院;去了,但没她想的那么大,不过整趟旅行很有趣。', 'uk_female', '[{"q":"Where has Anna just come back from?","type":"choice","answer":"C","options":["London.","Ireland.","Pingyao.","Scotland."]},{"q":"What surprised Anna on Ming-Qing Street?","type":"choice","answer":"D","options":["There were no shops.","It was completely empty.","It had closed down.","There were so many tourists."]},{"q":"What does Ben say is wonderful on that street?","type":"choice","answer":"A","options":["The snacks.","The tall buildings.","The quiet rooms.","The car park."]},{"q":"How did Anna feel on the old city wall?","type":"choice","answer":"B","options":["Bored and tired.","As if walking into history.","Cold and hungry.","Angry and lost."]},{"q":"What did Anna think of the family courtyard?","type":"choice","answer":"C","options":["It was the biggest she had seen.","It was completely closed.","It wasn''t as big as she had expected.","It had no rooms at all."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U4');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U4 听力·短文 British Afternoon Tea', '必修二 U4 · passage', 2, 'Afternoon tea is an old British tradition that many families still enjoy.
People usually add a little milk to their tea.
They often eat small snacks such as cakes and sandwiches.
Friends greet each other warmly and sit down to chat.
It is a relaxing way to share time and keep an old custom alive.', '下午茶是许多英国家庭至今仍喜爱的古老传统;人们通常往茶里加一点牛奶;常配蛋糕、三明治等小点心;朋友们热情地相互问候、坐下闲聊;这是分享时光、让古老习俗延续下来的轻松方式。', 'uk_female', '[{"q":"What is afternoon tea?","type":"choice","answer":"D","options":["A new kind of sport.","A type of museum.","A famous castle.","An old British tradition."]},{"q":"What do people usually add to their tea?","type":"choice","answer":"A","options":["A little milk.","A lot of salt.","Cold water.","Hot oil."]},{"q":"What small snacks do people often eat?","type":"choice","answer":"B","options":["Only fruit.","Cakes and sandwiches.","Beef stew.","Rice and soup."]},{"q":"What do friends do at afternoon tea?","type":"choice","answer":"C","options":["They argue loudly.","They leave at once.","They greet each other and chat.","They stay silent."]},{"q":"Why is afternoon tea special, according to the passage?","type":"choice","answer":"D","options":["It costs a lot of money.","It is very tiring.","It ends all traditions.","It keeps an old custom alive."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U4');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE volume='required2' AND unit='U4';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit) VALUES (10, 'Introduce a Place, Festival or Tradition of the UK or China(介绍英国或中国的一个地方/节日/传统)', 'A Place I Want to Introduce', '假设你叫李华,一位外国笔友想了解你最喜欢的一个地方、节日或传统(英国或中国均可)。请用英语写一篇约100词的短文,内容包括:① 用一个醒目的画面、引语或问题开头,介绍这个地方/节日/传统是什么;② 用不同感官(看、听、闻、尝、触)描写细节;③ 说说它为什么重要或为什么打动你,并以有力的句子结尾。注意:可适当使用过去分词作定语/宾补(如 a well-organised festival / have the streets decorated)。', 'Suppose you are Li Hua. A foreign pen-friend wants to learn about your favourite place, festival or tradition (in the UK or China). Write a passage of about 100 words including: 1) an opening with a striking image, quote or question that says what it is; 2) sensory details (what you can see, hear, smell, taste or feel); 3) why it matters or moves you, with an effective ending. Try to use past participles as the attribute or object complement where natural.', '["醒目开头(A striking image / a question / introduce the place or tradition)","感官细节(see / hear / smell / taste / feel)","为什么重要或动人 + 有力结尾","适当用过去分词作定语/宾补(a well-organised festival / have the streets decorated)"]'::jsonb, 70, 100, 'Have you ever walked into a town that feels like a living history book? My favourite place is the ancient town of Pingyao in China. The first thing you see is the old city wall, surrounded by narrow stone streets dotted with red lanterns. You can hear the soft sound of festival music and smell the warm scent of local snacks. If you are lucky, you can taste a delicious bowl of stew in a small courtyard, with your eyes fixed on the beautiful old roofs. Pingyao matters to me because it keeps so many traditions alive. Walking through it really feels like walking into history.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["Have you ever walked into a town that feels like a living history book?","The old city wall is surrounded by narrow streets dotted with red lanterns.","You can taste a delicious bowl of stew with your eyes fixed on the old roofs.","Pingyao matters to me because it keeps so many traditions alive."]'::jsonb, '[{"wrong":"The streets dotting with lanterns looked lovely.","correct":"The streets dotted with lanterns looked lovely.","note":"streets 被点缀,被动用过去分词 dotted,不用现在分词。"},{"wrong":"We had the streets decorating before the festival.","correct":"We had the streets decorated before the festival.","note":"have sth done:streets 被装饰,用过去分词 decorated。"},{"wrong":"I want introduce a place to you.","correct":"I want to introduce a place to you.","note":"want to do sth,want 后接动词不定式。"}]'::jsonb, '【介绍地方/节日/传统结构】
第1句 醒目开头:Have you ever …? / My favourite … is …
第2-4句 感官细节:You can see … hear … smell … taste …
第5句 为什么重要:… matters to me because …
第6句 有力结尾:It really feels like …', 2, 'required2', 'U4');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE volume='required2' AND unit='U4';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content) VALUES (10, 'required2', 'U4', '{"title":"过去分词作定语 & 作宾语补足语 速查","intro":"过去分词(done)表被动或完成。作定语时修饰名词(a broken window / soldiers wounded in the war);作宾语补足语时跟在 have/get/see/hear/find/want/make + 宾语后(get the car charged / heard it announced)。核心判断:宾语/名词与动作是被动关系→用过去分词,主动进行→用现在分词(doing)。","table":{"headers":["用法","结构 / 例句"],"rows":[["前置定语","单个分词修饰名词:a broken window / tired visitors / the shortened name"],["后置定语","分词带短语:soldiers wounded in the war / a lake surrounded by hills"],["have/get sth done","请人做或被完成:get the battery charged / had a copy boxed"],["感官/使役 + 宾 + done","see/hear/find/want/make:heard it announced / had her eyes fixed"]]},"specialRules":[{"rule":"名词/宾语承受动作(被动)→ 用过去分词 done","mark":"a broken window(窗户被打破)"},{"rule":"名词/宾语主动发出动作(主动·进行)→ 用现在分词 doing","mark":"a crying baby(婴儿在哭=主动)对照 a wounded soldier(士兵被伤)"},{"rule":"have/get sth done = 让别人做某事 / 某事被完成","mark":"get the car parked / have the photos printed"},{"rule":"see/hear/find/want + 宾 + done,强调宾语被动","mark":"heard it announced(它被宣布)"}],"why":["过去分词本身含被动、完成的意味,相当于一个被动的定语从句:soldiers wounded = soldiers who were wounded;heard it announced = heard that it was announced。宾语或名词是动作的承受者,所以不能用主动的 doing 或动词原形。"],"gaokaoPoints":["过去分词 vs 现在分词作定语/宾补:看名词或宾语是被动(done)还是主动(doing);语法填空、短文改错高频。","have/get sth done 与 have sb do sth 的区别:sth 被动用 done,sb 主动用 do/to do。"],"examVsReal":[{"exam":"I had my car repaired.(考试/书面)","real":"I got my car fixed.","note":"考试常用 have sth done;口语里 get sth done、用 fix 等更随意的词更常见"},{"exam":"soldiers wounded in the war（考试,后置定语）","real":"soldiers who got hurt in the war","note":"考试爱用过去分词短语;口语常还原成定语从句、用 get hurt"}]}'::jsonb);

COMMIT;

-- ===== 自带校验 =====
SELECT 'vocab' k, count(*) v, 51 expect FROM public.junior_vocab WHERE volume='required2' AND unit='U4'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='required2' AND unit='U4'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='required2' AND unit='U4'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='required2' AND unit='U4'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='required2' AND unit='U4'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE volume='required2' AND unit='U4' ORDER BY k;
SELECT 'grammar' rel, correct_answer ans, count(*) FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='required2' AND unit='U4') GROUP BY 2 ORDER BY 2;
