-- ============================================================
-- 上外(sufe) 必修一 U2(Learning about Trade and Economy)灌库(junior_* 表,publisher='sufe' volume='elective4' unit='U2' grade=12)。幂等。
-- ★DELETE 全带 publisher='sufe',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 48 =====
DELETE FROM public.junior_vocab WHERE publisher='sufe' AND volume='elective4' AND unit='U2';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'trade', 'n./v.', '/treɪd/', '贸易;交易;做买卖', 'China''s foreign trade has grown quickly in recent years.', '近年来中国的对外贸易增长迅速。', 'Learning about Trade and Economy', 1, 0, 'senior', 'wordlist', 'elective4', 'U2', 'foreign trade', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'economy', 'n.', '/ɪˈkɒnəmi/', '经济;经济体;节约', 'A strong economy creates more jobs for ordinary people.', '强劲的经济能为普通人创造更多就业机会。', 'Learning about Trade and Economy', 2, 0, 'senior', 'wordlist', 'elective4', 'U2', 'the global economy', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'economic', 'adj.', '/ˌiːkəˈnɒmɪk/', '经济的;经济上的', 'China has made great economic progress over the years.', '多年来中国取得了巨大的经济进步。', 'Learning about Trade and Economy', 3, 0, 'senior', 'wordlist', 'elective4', 'U2', 'economic growth', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'invest', 'v.', '/ɪnˈvest/', '投资;投入', 'Many companies invest in new technology in order to grow.', '许多公司投资新技术以求发展。', 'Learning about Trade and Economy', 4, 0, 'senior', 'wordlist', 'elective4', 'U2', 'invest in', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'investment', 'n.', '/ɪnˈvestmənt/', '投资;投资额', 'Foreign investment has helped this poor region develop.', '外来投资帮助这个贫困地区发展起来。', 'Learning about Trade and Economy', 5, 0, 'senior', 'wordlist', 'elective4', 'U2', 'foreign investment', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'import', 'n./v.', '/ˈɪmpɔːt/', '进口;进口商品;输入', 'China''s imports of goods have risen almost every year.', '中国的商品进口几乎逐年增长。', 'Learning about Trade and Economy', 6, 0, 'senior', 'wordlist', 'elective4', 'U2', 'imports and exports', '美音 /ˈɪmpɔːrt/', 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'export', 'n./v.', '/ˈekspɔːt/', '出口;出口商品;输出', 'These products are mainly made for export to other countries.', '这些产品主要为出口到其他国家而生产。', 'Learning about Trade and Economy', 7, 0, 'senior', 'wordlist', 'elective4', 'U2', 'the export market', '美音 /ˈekspɔːrt/', 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'merchandise', 'n.', '/ˈmɜːtʃəndaɪz/', '商品;货品', 'The shop sells all kinds of merchandise from abroad.', '这家商店销售各种各样的进口商品。', 'Learning about Trade and Economy', 8, 0, 'senior', 'wordlist', 'elective4', 'U2', 'general merchandise', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'goods', 'n.', '/ɡʊdz/', '商品;货物', 'Cheap goods from China are sold all around the world.', '来自中国的廉价商品销往世界各地。', 'Learning about Trade and Economy', 9, 0, 'senior', 'wordlist', 'elective4', 'U2', 'consumer goods', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'customs', 'n.', '/ˈkʌstəmz/', '海关', 'All imported goods must be checked by customs first.', '所有进口商品都必须先经过海关检查。', 'Learning about Trade and Economy', 10, 0, 'senior', 'wordlist', 'elective4', 'U2', 'go through customs', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'statistic', 'n.', '/stəˈtɪstɪk/', '统计数字;统计资料', 'The report gives clear statistics about world trade.', '报告给出了关于世界贸易的清晰统计数字。', 'Learning about Trade and Economy', 11, 0, 'senior', 'wordlist', 'elective4', 'U2', 'official statistics', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'annual', 'adj.', '/ˈænjuəl/', '每年的;年度的', 'The company''s annual sales reached a new high last year.', '公司去年的年度销售额创下新高。', 'Learning about Trade and Economy', 12, 0, 'senior', 'wordlist', 'elective4', 'U2', 'annual average', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'yearly', 'adj./adv.', '/ˈjɪəli/', '每年的;一年一次地', 'Trade between the two countries grows on a yearly basis.', '两国之间的贸易逐年增长。', 'Learning about Trade and Economy', 13, 0, 'senior', 'wordlist', 'elective4', 'U2', 'on a yearly basis', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'billion', 'num./n.', '/ˈbɪljən/', '十亿', 'The huge trade deal was worth several billion dollars.', '这笔庞大的贸易协议价值数十亿美元。', 'Learning about Trade and Economy', 14, 0, 'senior', 'wordlist', 'elective4', 'U2', 'billions of dollars', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'boost', 'v./n.', '/buːst/', '促进;使增长;推动', 'New roads can boost trade in poor mountain areas.', '新修的道路能促进贫困山区的贸易。', 'Learning about Trade and Economy', 15, 0, 'senior', 'wordlist', 'elective4', 'U2', 'boost growth', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'stimulate', 'v.', '/ˈstɪmjuleɪt/', '刺激;促进;激励', 'Lower taxes may stimulate the economy and create jobs.', '降低税收可能刺激经济并创造就业。', 'Learning about Trade and Economy', 16, 0, 'senior', 'wordlist', 'elective4', 'U2', 'stimulate the economy', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'generate', 'v.', '/ˈdʒenəreɪt/', '产生;创造', 'Foreign trade can generate millions of jobs for a country.', '对外贸易能为一个国家创造数百万就业岗位。', 'Learning about Trade and Economy', 17, 0, 'senior', 'wordlist', 'elective4', 'U2', 'generate jobs', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'exceed', 'v.', '/ɪkˈsiːd/', '超过;超出', 'Last year, the country''s exports exceeded all earlier records.', '去年该国的出口超过了以往所有记录。', 'Learning about Trade and Economy', 18, 0, 'senior', 'wordlist', 'elective4', 'U2', 'exceed expectations', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'absorb', 'v.', '/əbˈsɔːb/', '吸纳;吸收;吞并', 'Rich markets absorb much of the poorer nations'' exports.', '富裕市场吸纳了较贫穷国家的大量出口产品。', 'Learning about Trade and Economy', 19, 0, 'senior', 'wordlist', 'elective4', 'U2', 'absorb exports', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'sustain', 'v.', '/səˈsteɪn/', '使持续;维持;支撑', 'It is hard to sustain such fast growth for many years.', '如此快速的增长很难维持很多年。', 'Learning about Trade and Economy', 20, 0, 'senior', 'wordlist', 'elective4', 'U2', 'sustain growth', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'represent', 'v.', '/ˌreprɪˈzent/', '代表;相当于;意味着', 'These figures represent a large part of world trade.', '这些数字相当于世界贸易的很大一部分。', 'Learning about Trade and Economy', 21, 0, 'senior', 'wordlist', 'elective4', 'U2', 'represent a share', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'innovation', 'n.', '/ˌɪnəˈveɪʃn/', '创新;革新;新事物', 'Innovation in trade models has changed the way we shop.', '贸易模式的创新改变了我们的购物方式。', 'Learning about Trade and Economy', 22, 0, 'senior', 'wordlist', 'elective4', 'U2', 'innovation in trade', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'e-commerce', 'n.', '/ˈiː ˌkɒmɜːs/', '电子商务', 'Cross-border e-commerce is growing very fast in China.', '跨境电子商务在中国发展得非常快。', 'Learning about Trade and Economy', 23, 0, 'senior', 'wordlist', 'elective4', 'U2', 'e-commerce platform', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'mode', 'n.', '/məʊd/', '方式;模式;样式', 'Selling online is a new mode of doing business.', '网上销售是一种新的经商方式。', 'Learning about Trade and Economy', 24, 0, 'senior', 'wordlist', 'elective4', 'U2', 'a new mode', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'previous', 'adj.', '/ˈpriːviəs/', '以前的;先前的', 'Sales this season were higher than in the previous year.', '本季的销售额高于前一年。', 'Learning about Trade and Economy', 25, 0, 'senior', 'wordlist', 'elective4', 'U2', 'the previous year', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'outbound', 'adj.', '/ˈaʊtbaʊnd/', '向外的;出境的', 'The number of outbound tourists has risen sharply.', '出境游客的数量急剧上升。', 'Learning about Trade and Economy', 26, 0, 'senior', 'wordlist', 'elective4', 'U2', 'outbound tourists', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'overseas', 'adj./adv.', '/ˌəʊvəˈsiːz/', '海外的;在海外', 'The company hopes to sell more in overseas markets.', '公司希望在海外市场卖出更多产品。', 'Learning about Trade and Economy', 27, 0, 'senior', 'wordlist', 'elective4', 'U2', 'overseas markets', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'region', 'n.', '/ˈriːdʒən/', '地区;区域', 'Foreign trade has brought new jobs to this region.', '对外贸易为这个地区带来了新的就业机会。', 'Learning about Trade and Economy', 28, 0, 'senior', 'wordlist', 'elective4', 'U2', 'a poor region', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'poverty', 'n.', '/ˈpɒvəti/', '贫穷;贫困', 'Trade has helped lift millions of people out of poverty.', '贸易帮助数百万人摆脱了贫困。', 'Learning about Trade and Economy', 29, 0, 'senior', 'wordlist', 'elective4', 'U2', 'lift out of poverty', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'emerge', 'v.', '/ɪˈmɜːdʒ/', '(从困境中)摆脱出来;显现;露出', 'Many families have emerged from poverty in recent years.', '近年来许多家庭已摆脱了贫困。', 'Learning about Trade and Economy', 30, 0, 'senior', 'wordlist', 'elective4', 'U2', 'emerge from poverty', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'moderate', 'adj.', '/ˈmɒdərət/', '适度的;中等的;温和的', 'The country has reached a level of moderate prosperity.', '这个国家已达到小康（适度繁荣）的水平。', 'Learning about Trade and Economy', 31, 0, 'senior', 'wordlist', 'elective4', 'U2', 'moderate prosperity', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'effect', 'n.', '/ɪˈfekt/', '影响;效应;结果', 'Trade has a strong effect on people''s daily lives.', '贸易对人们的日常生活有很大影响。', 'Learning about Trade and Economy', 32, 0, 'senior', 'wordlist', 'elective4', 'U2', 'have an effect on', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'release', 'v.', '/rɪˈliːs/', '公布;发布;释放', 'The bank will release a report on economic growth tomorrow.', '银行明天将发布一份关于经济增长的报告。', 'Learning about Trade and Economy', 33, 0, 'senior', 'wordlist', 'elective4', 'U2', 'release a report', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'financial', 'adj.', '/faɪˈnænʃl/', '财政的;金融的;财务的', 'The world is still recovering from the financial crisis.', '世界仍在从金融危机中恢复。', 'Learning about Trade and Economy', 34, 0, 'senior', 'wordlist', 'elective4', 'U2', 'a financial crisis', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'establish', 'v.', '/ɪˈstæblɪʃ/', '建立;使确立;开创', 'The deal helped establish a new trade partnership.', '这笔交易帮助建立了一种新的贸易伙伴关系。', 'Learning about Trade and Economy', 35, 0, 'senior', 'wordlist', 'elective4', 'U2', 'establish a partnership', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'opt', 'v.', '/ɒpt/', '选择;挑选', 'Buyers often opt for cheaper goods when prices rise.', '价格上涨时，买家往往选择更便宜的商品。', 'Learning about Trade and Economy', 36, 0, 'senior', 'wordlist', 'elective4', 'U2', 'opt for', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'benefit', 'n./v.', '/ˈbenɪfɪt/', '益处;好处;使受益', 'We weigh the costs and benefits before every purchase.', '每次购买前我们都会权衡成本与收益。', 'Learning about Trade and Economy', 37, 0, 'senior', 'wordlist', 'elective4', 'U2', 'costs and benefits', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'various', 'adj.', '/ˈveəriəs/', '各种不同的;各种各样的', 'Trade affects various sectors of the whole economy.', '贸易影响着整个经济的各个部门。', 'Learning about Trade and Economy', 38, 0, 'senior', 'wordlist', 'elective4', 'U2', 'various sectors', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'transfer', 'v.', '/trænsˈfɜː/', '转移;转账;调动', 'You can transfer money to the seller online in seconds.', '你可以在网上几秒内把钱转给卖家。', 'Learning about Trade and Economy', 39, 0, 'senior', 'wordlist', 'elective4', 'U2', 'transfer money', '美音 /trænsˈfɜːr/', 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'extend', 'v.', '/ɪkˈstend/', '延伸;扩展;延续', 'The firm wants to extend its market to other countries.', '这家公司想把市场扩展到其他国家。', 'Learning about Trade and Economy', 40, 0, 'senior', 'wordlist', 'elective4', 'U2', 'extend a market', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'foundation', 'n.', '/faʊnˈdeɪʃn/', '基础;地基;根基', 'We should lay a firm foundation for future growth.', '我们应为未来的发展打下坚实的基础。', 'Learning about Trade and Economy', 41, 0, 'senior', 'wordlist', 'elective4', 'U2', 'lay a foundation', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'improvement', 'n.', '/ɪmˈpruːvmənt/', '改善;改进;改进之处', 'An improvement in trade brought more jobs to the town.', '贸易的改善给小镇带来了更多就业。', 'Learning about Trade and Economy', 42, 0, 'senior', 'wordlist', 'elective4', 'U2', 'an improvement in', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'ambitious', 'adj.', '/æmˈbɪʃəs/', '雄心勃勃的;有抱负的;宏大的', 'The country has an ambitious plan for economic growth.', '这个国家有一个雄心勃勃的经济增长计划。', 'Learning about Trade and Economy', 43, 0, 'senior', 'wordlist', 'elective4', 'U2', 'an ambitious plan', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'undergo', 'v.', '/ˌʌndəˈɡəʊ/', '经历(变化、苦难等)', 'The Chinese economy has undergone great changes.', '中国经济经历了巨大的变化。', 'Learning about Trade and Economy', 44, 0, 'senior', 'wordlist', 'elective4', 'U2', 'undergo change', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'account for', 'phr.', '/əˈkaʊnt fə/', '(数量、比例上)占;解释', 'Exports account for a large share of the country''s total.', '出口在该国总量中占很大份额。', 'Learning about Trade and Economy', 45, 0, 'senior', 'wordlist', 'elective4', 'U2', 'account for', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'on average', 'phr.', '/ɒn ˈævərɪdʒ/', '平均', 'On average, trade grew by about ten percent each year.', '平均而言，贸易每年增长约百分之十。', 'Learning about Trade and Economy', 46, 0, 'senior', 'wordlist', 'elective4', 'U2', 'on average', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'in a row', 'phr.', '/ɪn ə ˈrəʊ/', '连续几次地;接连地', 'Retail sales rose for six months in a row this year.', '今年零售额连续六个月上升。', 'Learning about Trade and Economy', 47, 0, 'senior', 'wordlist', 'elective4', 'U2', 'in a row', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (12, 'speed up', 'phr.', '/ˌspiːd ˈʌp/', '(使)加速;加快', 'China has tried hard to speed up its trade reform.', '中国努力加快其贸易改革。', 'Learning about Trade and Economy', 48, 0, 'senior', 'wordlist', 'elective4', 'U2', 'speed up', NULL, 'sufe');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2');
DELETE FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('se4u2.01', '①动词后接动名词还是不定式作宾语', 'A2', 12, '上外版选择性必修第四册 U2 — 有些动词后只接动名词(enjoy/finish/avoid/suggest/consider/mind/practise/keep/admit/give up 等),有些只接不定式(decide/hope/agree/offer/refuse/manage/plan/promise/afford/expect 等);按动词搭配在 -ing 和 to do 之间选择。', 1, 'elective4', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('se4u2.02', '②-ing 与 -ed 分词作定语/状语', 'A2', 12, '上外版选择性必修第四册 U2 — -ing 分词表主动或正在进行(修饰发出动作的名词,或主语主动发出动作);-ed 分词表被动或已完成(修饰承受动作的名词,或主语被动);据主动/被动关系选 -ing 或 -ed。', 2, 'elective4', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('se4u2.03', '③不定式表目的/结果及固定结构', 'A2', 12, '上外版选择性必修第四册 U2 — to do 表目的(in order to / the way·first·best…to)或结果(too…to / enough to);adj.+to do、be likely/ready/willing/able to 等结构后只能用不定式,不可用 -ing/-ed。', 3, 'elective4', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'The two companies finally finished ____ the trade agreement.', 'signing', 'to sign', 'signed', 'sign', 'A', 'finish 后只接动名词 → signing。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'Many small firms avoid ____ too much money from banks.', 'to borrow', 'borrowing', 'borrowed', 'borrow', 'B', 'avoid 后只接动名词 → borrowing。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'The manager suggested ____ costs before raising any prices.', 'to cut', 'cut', 'cutting', 'to cutting', 'C', 'suggest 后接动名词 → cutting。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'To stay competitive, we should keep ____ in new technology.', 'to invest', 'invested', 'invest', 'investing', 'D', 'keep(继续)后接动名词 → investing。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'The factory considered ____ its production to a cheaper region.', 'moving', 'to move', 'moved', 'move', 'A', 'consider 后接动名词 → moving。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'Many customers enjoy ____ online because it saves them time.', 'to shop', 'shopping', 'shopped', 'shop', 'B', 'enjoy 后只接动名词 → shopping。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'He honestly admitted ____ a poor decision about the budget.', 'to make', 'made', 'making', 'make', 'C', 'admit 后接动名词 → making。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'The shop owner did not mind ____ the price a little for us.', 'to lower', 'lowered', 'lower', 'lowering', 'D', 'mind 后接动名词 → lowering。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'In class we practised ____ costs and benefits before each choice.', 'comparing', 'to compare', 'compared', 'compare', 'A', 'practise 后接动名词 → comparing。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'Once prices rose, many shoppers gave up ____ luxury goods.', 'to buy', 'buying', 'bought', 'buy', 'B', 'give up 后接动名词 → buying。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'In 2014, the government decided ____ the free trade zone.', 'expanding', 'expanded', 'to expand', 'expand', 'C', 'decide 后只接不定式 → to expand。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'The company hopes ____ the overseas market early next year.', 'entering', 'entered', 'enter', 'to enter', 'D', 'hope 后接不定式 → to enter。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'After long talks, both sides agreed ____ the price of the goods.', 'to reduce', 'reducing', 'reduced', 'reduce', 'A', 'agree 后接不定式 → to reduce。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'She kindly offered ____ her friend some money for the trip.', 'lending', 'to lend', 'lent', 'lend', 'B', 'offer 后接不定式 → to lend。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'The young trader refused ____ at such an unfair price.', 'selling', 'sold', 'to sell', 'sell', 'C', 'refuse 后接不定式 → to sell。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'After months of talks, they managed ____ a fair deal at last.', 'reaching', 'reached', 'reach', 'to reach', 'D', 'manage 后接不定式 → to reach。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'Our class plans ____ a small fund for the spring outing.', 'to raise', 'raising', 'raised', 'raise', 'A', 'plan 后接不定式 → to raise。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'He promised ____ back the loan within a single year.', 'paying', 'to pay', 'paid', 'pay', 'B', 'promise 后接不定式 → to pay。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'Few families can afford ____ money on things they do not need.', 'wasting', 'wasted', 'to waste', 'waste', 'C', 'afford 后接不定式 → to waste。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.01'), 'The seller expects buyers ____ prices carefully before paying.', 'comparing', 'compared', 'compare', 'to compare', 'D', 'expect sb 后接不定式 → to compare。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'China has become a ____ engine for the whole world economy.', 'growing', 'grown', 'to grow', 'grow', 'A', 'engine 主动地''增长'' → 现在分词 growing。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'Shoppers like cheap products ____ from other countries.', 'importing', 'imported', 'to import', 'import', 'B', 'products 被进口、被动 → 过去分词 imported。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'A well-____ brand can sell its goods at higher prices.', 'knowing', 'to know', 'known', 'know', 'C', 'brand 被知晓、被动 → 过去分词 known。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'The ____ goods were loaded onto the ship at the busy port.', 'packing', 'to pack', 'pack', 'packed', 'D', 'goods 被打包、被动 → 过去分词 packed。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'Cross-border trade has opened an ever-____ market for sellers.', 'expanding', 'expanded', 'to expand', 'expand', 'A', 'market 主动地''扩大'' → 现在分词 expanding。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'Careful buyers trust ____ goods that pass strict quality tests.', 'manufacturing', 'manufactured', 'to manufacture', 'manufacture', 'B', 'goods 被生产、被动 → 过去分词 manufactured。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'The ____ cost of oil worried many small businesses last year.', 'risen', 'to rise', 'rising', 'rise', 'C', 'cost 主动地''上涨'' → 现在分词 rising。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'Before the trip, we compared the prices of three ____ flights.', 'competed', 'to compete', 'compete', 'competing', 'D', 'flights 主动地''相互竞争'' → 现在分词 competing。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'The manager read the ____ report carefully before the meeting.', 'printed', 'printing', 'to print', 'print', 'A', 'report 被打印、被动 → 过去分词 printed。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'An economy ____ by innovation usually grows much faster.', 'driving', 'driven', 'to drive', 'drive', 'B', 'economy 被创新推动、被动 → 过去分词 driven。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'The goods ____ in this region are both cheap and reliable.', 'producing', 'to produce', 'produced', 'produce', 'C', 'goods 被生产、被动 → 过去分词 produced。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'The free trade zone, ____ in 2013, lies in the Pudong area.', 'founding', 'to found', 'found', 'founded', 'D', 'zone 被建立、被动 → 过去分词 founded。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'Companies ____ reasonable decisions always weigh costs and benefits.', 'making', 'made', 'to make', 'make', 'A', 'companies 主动''作出''决定 → 现在分词 making。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'The money ____ in the bank can later be loaned to others.', 'saving', 'saved', 'to save', 'save', 'B', 'money 被存、被动 → 过去分词 saved。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'The students ____ the trading game learned a lot about money.', 'played', 'to play', 'playing', 'play', 'C', 'students 主动''玩''游戏 → 现在分词 playing。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'A plan ____ to cut waste was warmly welcomed by the board.', 'designing', 'to design', 'design', 'designed', 'D', 'plan 被设计、被动 → 过去分词 designed。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), '____ the costs and benefits, the family made a wise choice.', 'Comparing', 'Compared', 'To compare', 'Compare', 'A', 'family 主动比较(带宾语)、作状语 → 现在分词 Comparing。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), '____ by clever managers, the firm soon began to make a profit.', 'Leading', 'Led', 'To lead', 'Lead', 'B', 'firm 被带领、被动状语 → 过去分词 Led。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), 'The shoppers left the market, ____ bags full of cheap goods.', 'carried', 'to carry', 'carrying', 'carry', 'C', 'shoppers 主动''提着''、伴随状语 → 现在分词 carrying。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.02'), '____ by the good news, investors put more money into the firm.', 'Encouraging', 'To encourage', 'Encourage', 'Encouraged', 'D', 'investors 被鼓舞、被动状语 → 过去分词 Encouraged。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The luxury watch was far too expensive ____ easily.', 'to sell', 'selling', 'sold', 'sell', 'A', 'too…to 结构 → 不定式 to sell。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'These simple products are cheap enough ____ many buyers.', 'attracting', 'to attract', 'attracted', 'attract', 'B', 'enough to 结构 → 不定式 to attract。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'Oil grew so scarce that it was too costly ____ at all.', 'wasting', 'wasted', 'to waste', 'waste', 'C', 'too…to 结构 → 不定式 to waste。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The young company was strong enough ____ foreign markets.', 'entering', 'entered', 'enter', 'to enter', 'D', 'enough to 结构 → 不定式 to enter。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The best way ____ costs is to plan a careful budget.', 'to cut', 'cutting', 'cut', 'cuts', 'A', 'the best way to do 固定结构 → 不定式 to cut。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'Saving a little each day is the first step ____ towards wealth.', 'taking', 'to take', 'taken', 'take', 'B', 'the first step to do → 不定式 to take。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'It takes time and trust ____ a lasting trade partnership.', 'building', 'built', 'to build', 'build', 'C', 'It takes…to do 结构 → 不定式 to build。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'That honest trader was the first ____ a fair price for the goods.', 'offering', 'offered', 'offer', 'to offer', 'D', 'the first to do → 不定式 to offer。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'Cheap imported products are likely ____ from the shelves quickly.', 'to disappear', 'disappearing', 'disappeared', 'disappear', 'A', 'be likely to do → 不定式 to disappear。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'A rational buyer is always willing ____ costs and benefits.', 'comparing', 'to compare', 'compared', 'compare', 'B', 'be willing to do → 不定式 to compare。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The two firms are now ready ____ the new trade agreement.', 'signing', 'signed', 'to sign', 'sign', 'C', 'be ready to do → 不定式 to sign。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'In order ____ money, the family made a careful spending plan.', 'saving', 'saved', 'save', 'to save', 'D', 'in order to do 表目的 → 不定式 to save。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The new policy is likely ____ the local economy this year.', 'to boost', 'boosting', 'boosted', 'boost', 'A', 'be likely to do → 不定式 to boost。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The market was too crowded for the small shop ____ for long.', 'surviving', 'to survive', 'survived', 'survive', 'B', 'too…for sb to do → 不定式 to survive。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'She was very happy ____ cheaper goods at the morning market.', 'finding', 'found', 'to find', 'find', 'C', 'adj.(happy)+ to do → 不定式 to find。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The only way ____ loyal customers is to offer real value.', 'winning', 'won', 'win', 'to win', 'D', 'the only way to do → 不定式 to win。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The struggling firm needs more time ____ its huge debt.', 'to repay', 'repaying', 'repaid', 'repay', 'A', 'time to do → 不定式 to repay。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'Wise families are careful enough ____ running up large debts.', 'avoiding', 'to avoid', 'avoided', 'avoid', 'B', 'enough to do → 不定式 to avoid。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'It is never too late ____ how to manage your own money.', 'learning', 'learned', 'to learn', 'learn', 'C', 'too…to 结构 → 不定式 to learn。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2' AND code='se4u2.03'), 'The manager was glad ____ a fair deal with the friendly buyer.', 'reaching', 'reached', 'reach', 'to reach', 'D', 'adj.(glad)+ to do → 不定式 to reach。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='sufe' AND volume='elective4' AND unit='U2';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (12, 'China''s Trade Story', 'Since it joined the World Trade Organization, China has opened its markets wider and grown faster than almost any other large country. Its rapid development has become a powerful engine driving the growth of the whole world economy. Year after year, China has bought more goods from abroad and sold more products to other nations. Its cheap, high-quality products reach businesses and families on every continent, while its rising demand for imports gives trading partners fresh chances to earn money. China has also created millions of jobs, both at home and overseas, and has helped lift hundreds of millions of its own people out of poverty. Many experts believe that the country''s success in trade has made it one of the most important partners for more than a hundred nations. In this way, the story of a single country''s trade has slowly become part of the story of the wider world.', '说明·中国外贸进步', 151, '[{"q":"What has happened to China''s markets since it joined the WTO?","answer":"A","options":["They were opened wider and the country grew quickly.","They were closed to the rest of the world.","They were sold to foreign companies.","They stopped buying any goods at all."],"explanation":"首句''opened its markets wider and grown faster''的转述。"},{"q":"How do China''s imports help its trading partners?","answer":"B","options":["They force the partners to stop trading.","They give those partners new chances to earn money.","They make all foreign goods cheaper at once.","They close down factories abroad."],"explanation":"原文''rising demand for imports gives trading partners fresh chances to earn money''的概括。"},{"q":"What does the passage say about China''s own people?","answer":"A","options":["Hundreds of millions were freed from poverty.","Most of them became much poorer.","They all moved to other countries.","They were not affected by trade."],"explanation":"原文''helped lift hundreds of millions of its own people out of poverty''的转述。"}]'::jsonb, '[{"word":"import","cn":"进口"},{"word":"export","cn":"出口"},{"word":"poverty","cn":"贫困"}]'::jsonb, 2, 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (12, 'Roads That Carry Trade', 'The Belt and Road Initiative is one of China''s most ambitious plans for trade and development. Its goal is to connect China with many countries across Asia, Africa and Europe by building roads, railways, ports and other links. Supporters say the plan does far more than simply move goods from place to place. By improving transport, it lowers the cost of trade and gives poorer regions a real chance to join the world economy. In Kenya, for example, a railway built with Chinese help is said to have boosted the country''s growth. Cooperation agreements worth tens of billions of dollars have been signed, and many nations have welcomed the new opportunities. Of course, such a huge plan also raises questions about cost and fairness, and not everyone agrees on how the benefits should be shared. Even so, for many developing countries the initiative has opened a door that once seemed firmly shut.', '说明·一带一路', 152, '[{"q":"What is the main aim of the Belt and Road Initiative?","answer":"B","options":["To stop all trade between the continents.","To link China with many other countries through transport and trade.","To build only new schools inside China.","To keep poorer regions out of the world economy."],"explanation":"原文''connect China with many countries… by building roads, railways, ports''的转述。"},{"q":"According to the passage, how does better transport help trade?","answer":"C","options":["It raises the cost of moving goods.","It blocks goods from crossing borders.","It makes trade cheaper for poorer areas.","It closes ports and railways down."],"explanation":"原文''lowers the cost of trade''的转述。"},{"q":"What does the writer admit about such a huge plan?","answer":"D","options":["Everyone fully agrees with every part of it.","It has had no effect at all on trade.","It only helps the very richest nations.","People still argue about its cost and fairness."],"explanation":"原文''raises questions about cost and fairness, and not everyone agrees''的概括。"}]'::jsonb, '[{"word":"ambitious","cn":"雄心勃勃的"},{"word":"link","cn":"连接;纽带"},{"word":"region","cn":"地区"}]'::jsonb, 2, 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (12, 'Why Study Economics?', 'Why should ordinary students bother to learn economics? The simplest answer is that economics is the study of how people deal with scarcity. We all have endless wants, but the time, money and resources to meet them are strictly limited. Because we cannot have everything, every choice we make means giving up something else. Economists call this hidden price the ''opportunity cost''. Imagine you have only ten yuan and you must choose between a book and a film ticket. If you buy the book, the film you miss is the true cost of your choice. Thinking in this way helps us use our limited money and time more wisely. It also explains the choices of families, companies and even whole nations. Once you start to see the world through this lens, shopping, saving and planning all begin to make far more sense. That is exactly why so many schools now teach young people to think like economists.', '议论·稀缺与选择', 157, '[{"q":"According to the passage, what is economics mainly about?","answer":"A","options":["How people cope with limited resources.","How to become rich very quickly.","How to avoid making any choices.","How to spend with no limits at all."],"explanation":"原文''how people deal with scarcity''的转述。"},{"q":"What is the ''opportunity cost'' of a choice?","answer":"B","options":["The money you manage to save.","The thing you give up when you choose.","The price printed on a tag.","The number of things you own."],"explanation":"原文用买书放弃电影说明''机会成本''是放弃的东西。"},{"q":"Why do many schools now teach economics?","answer":"C","options":["To make students spend much more money.","To stop students from thinking carefully.","To help young people make wiser choices.","To teach students to ignore every cost."],"explanation":"末句''teach young people to think like economists''+''make far more sense''的概括。"}]'::jsonb, '[{"word":"scarcity","cn":"稀缺;短缺"},{"word":"resource","cn":"资源"},{"word":"opportunity cost","cn":"机会成本"}]'::jsonb, 2, 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (12, 'Thinking at the Margin', 'Most decisions in real life are not simple choices between everything and nothing. At dinner you rarely decide between starving and eating until you are sick; instead you decide whether to take one more spoonful of rice. Before an exam you do not choose between never studying and studying all day; you choose whether to spend one more hour with your notes. Economists describe these tiny steps as changes ''at the margin''. To make such a decision well, you only need to compare the extra benefit of one more step with its extra cost. Suppose you are deciding whether to stay one more year at school. The useful question is not whether school is good in general, but whether that single extra year is worth its price in time and money. A wise person acts only when the gain from a step is bigger than what the step costs. Learning to think this carefully can improve almost every choice we make.', '议论·边际思考', 161, '[{"q":"What does ''thinking at the margin'' mean here?","answer":"D","options":["Choosing only between everything and nothing.","Never making any small decisions at all.","Ignoring the cost of every decision.","Weighing the added benefit and cost of one more step."],"explanation":"原文''compare the extra benefit of one more step with its extra cost''的转述。"},{"q":"When deciding to stay one more year at school, what should you ask?","answer":"A","options":["Whether one more year of study is really worth what it costs.","Whether school is a good thing in general.","Whether to leave school forever now.","Whether other people enjoy school."],"explanation":"原文''whether that single extra year is worth its price''的转述。"},{"q":"When does a wise person take an action?","answer":"B","options":["When it costs as much money as possible.","When the gain from it outweighs what it costs.","When everyone around them is doing it.","When it brings no benefit whatsoever."],"explanation":"末段''gain from a step is bigger than what the step costs''的转述。"}]'::jsonb, '[{"word":"margin","cn":"边际;边缘"},{"word":"benefit","cn":"收益;好处"},{"word":"extra","cn":"额外的"}]'::jsonb, 2, 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (12, 'The Cheapest Flight', 'When my mother planned a trip abroad, she had to choose among three flights. A Thursday night flight was the cheapest, a Friday flight cost a little more, and a Saturday morning flight was the most expensive of all. At first the choice seemed obvious: pick the cheapest ticket and save some money. But my mother thought like an economist. She worked in a restaurant from Monday to Friday and earned good money on each working day. If she took the cheap Thursday flight, she would lose two days of pay by leaving her job early. Once she added those lost wages to the ticket price, the ''cheap'' flight turned out to be the most costly choice of the three. The expensive Saturday flight, which let her work the whole week, was in fact the best value. Her story taught me a useful lesson: the real price of something is not only the number on the tag, but everything else you give up to get it.', '记叙·机会成本', 166, '[{"q":"Why did the cheapest flight seem the best at first?","answer":"C","options":["Because it left on a Saturday morning.","Because it was the most expensive one.","Because it had the lowest ticket price.","Because the mother had no job at all."],"explanation":"原文''pick the cheapest ticket and save some money''的转述。"},{"q":"Why was the cheap Thursday flight actually costly?","answer":"D","options":["The plane was extremely slow.","Its ticket was the dearest of all.","She simply disliked Thursdays.","She would miss two days'' wages from her job."],"explanation":"原文''lose two days of pay by leaving her job early''的转述。"},{"q":"What lesson did the writer learn from the story?","answer":"A","options":["The true cost includes what you give up, not just the price.","You should always buy the cheapest ticket.","You should never travel by plane again.","Money has no real value to anyone."],"explanation":"末句关于''real price… everything else you give up''的转述。"}]'::jsonb, '[{"word":"wages","cn":"工资"},{"word":"value","cn":"价值;划算"},{"word":"costly","cn":"昂贵的"}]'::jsonb, 2, 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (12, 'Money Before Coins', 'Long before coins and paper notes, people in many places used unusual objects as money. In China, one of the earliest forms of money was the cowrie shell, known as bei. During the Shang dynasty, these small, pretty shells were collected from seas far to the south. Because they were hard to find and could not easily be copied, people trusted them and accepted them in trade. Only kings and rich families could gather large numbers of them, so the shells also became a sign of wealth. As trade grew busier over time, shells were slowly replaced by metal coins, which were easier to make and to carry about. Yet the idea behind shell money has never really changed. Money, whether a shell, a coin or a number on a screen, works only because people are willing to take it. Its true power lies not in the object itself but in the shared trust of those who use it.', '说明·货币史·贝币', 159, '[{"q":"Why did people trust cowrie shells as money?","answer":"B","options":["They were found almost everywhere.","They were rare and hard to copy.","They were all made out of gold.","They were printed by the kings."],"explanation":"原文''hard to find and could not easily be copied''的转述。"},{"q":"What did owning many shells show about a family?","answer":"C","options":["That the family was very poor.","That the family disliked trade.","That the family was wealthy.","That the family lived by the sea."],"explanation":"原文''became a sign of wealth''的转述。"},{"q":"What is the writer''s main point about money in the last lines?","answer":"D","options":["Its power comes from the material it is made of.","Shells are still the main money used today.","Coins are completely worthless to everyone.","Money has value only when people are willing to accept it."],"explanation":"末段''works only because people are willing to take it… shared trust''的转述。"}]'::jsonb, '[{"word":"shell","cn":"贝壳"},{"word":"currency","cn":"货币"},{"word":"wealth","cn":"财富"}]'::jsonb, 2, 'elective4', 'U2', 'sufe');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='sufe' AND volume='elective4' AND unit='U2';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (12, 'elective4', 'U2', 'Learning to Budget', 'When Lily started university, she had to learn how to (1)____ her own money for the first time. Her main (2)____ of income was a small loan from the bank, so she had to spend (3)____. Every month she made a simple (4)____, writing down how much she could use for food, books and travel. She tried hard to (5)____ buying things she did not really need. Whenever she wanted something expensive, she would (6)____ the cost against the benefit before paying. If she ran (7)____ of money, she cut down on treats like coffee and films. Slowly, she learned that a clear plan could (8)____ her a lot of worry. By the end of the year, she had even managed to (9)____ a little money for a holiday. Looking back, Lily felt (10)____ that she had picked up such a useful skill so early.', 145, 2, '[{"q":"1","answer":"A","options":["manage","throw","lose","break"],"explanation":"manage one''s money 管理钱财。"},{"q":"2","answer":"B","options":["price","source","noise","game"],"explanation":"source of income 收入来源。"},{"q":"3","answer":"C","options":["angrily","sleepily","carefully","noisily"],"explanation":"spend carefully 小心花钱。"},{"q":"4","answer":"D","options":["mistake","journey","machine","budget"],"explanation":"make a budget 做预算。"},{"q":"5","answer":"A","options":["avoid","enjoy","continue","risk"],"explanation":"不需要的东西要 avoid buying 避免购买。"},{"q":"6","answer":"B","options":["throw","weigh","sell","hide"],"explanation":"weigh cost against benefit 权衡成本与收益。"},{"q":"7","answer":"C","options":["in","up","out","off"],"explanation":"run out of money 钱花光。"},{"q":"8","answer":"D","options":["cost","lose","waste","save"],"explanation":"save sb worry 省去烦恼。"},{"q":"9","answer":"A","options":["keep","spend","borrow","drop"],"explanation":"为度假 keep a little money 留住一点钱。"},{"q":"10","answer":"B","options":["sorry","proud","afraid","angry"],"explanation":"felt proud 感到自豪。"}]'::jsonb, 1, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (12, 'elective4', 'U2', 'Playing a Trading Game', 'In our economics class, we played a trading (1)____ to understand how markets really work. Each group was given ten cards (2)____ as money, and there were five kinds of goods for (3)____. Gold was the most valuable, while food was the (4)____. The aim was to (5)____ as many points as possible by buying and selling wisely. At first, trading was (6)____, because no one knew the real value of each item. Then the teacher told us that the world was running (7)____ of oil, so its price suddenly went (8)____. Groups that had bought oil early made a big (9)____. By the end of the game, we all understood that prices change when goods become rare. It was a fun (10)____ to learn an important economic idea.', 129, 2, '[{"q":"1","answer":"C","options":["price","noise","game","letter"],"explanation":"trading game 贸易游戏。"},{"q":"2","answer":"D","options":["sold","eaten","lost","used"],"explanation":"cards used as money 当作钱用的卡片。"},{"q":"3","answer":"A","options":["sale","rain","sleep","sport"],"explanation":"goods for sale 待售商品。"},{"q":"4","answer":"B","options":["tallest","cheapest","oldest","loudest"],"explanation":"food was the cheapest 最便宜。"},{"q":"5","answer":"C","options":["lose","drop","win","hide"],"explanation":"win points 赢得分数。"},{"q":"6","answer":"D","options":["silent","empty","asleep","difficult"],"explanation":"trading was difficult 交易很难。"},{"q":"7","answer":"A","options":["out","in","up","over"],"explanation":"running out of oil 石油快用完。"},{"q":"8","answer":"B","options":["down","up","away","off"],"explanation":"石油变稀缺，price went up 价格上涨。"},{"q":"9","answer":"C","options":["mistake","noise","profit","holiday"],"explanation":"made a big profit 赚大钱。"},{"q":"10","answer":"D","options":["price","noise","rule","way"],"explanation":"a fun way to learn 有趣的学习方式。"}]'::jsonb, 2, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (12, 'elective4', 'U2', 'Shopping Online', 'These days, more and more people in China (1)____ to shop online instead of going to busy stores. With just a phone, you can (2)____ goods from all over the world and pay in seconds. Cross-border online shopping has grown (3)____ in recent years. It gives small sellers a chance to (4)____ their products to customers far away. For buyers, it is easy to (5)____ prices from many shops before choosing the best (6)____. Of course, online shopping also has its (7)____: you cannot touch the goods, and sometimes they arrive (8)____ than you hoped. Still, most shoppers feel that the (9)____ are greater than the problems. As technology improves, this new (10)____ of trade is likely to grow even faster.', 121, 2, '[{"q":"1","answer":"A","options":["choose","refuse","forget","sleep"],"explanation":"choose to shop online 选择网购。"},{"q":"2","answer":"B","options":["throw","order","break","lose"],"explanation":"order goods 订购商品。"},{"q":"3","answer":"C","options":["loudly","sadly","quickly","quietly"],"explanation":"grown quickly 增长迅速。"},{"q":"4","answer":"D","options":["hide","lose","eat","sell"],"explanation":"sell their products 卖产品。"},{"q":"5","answer":"A","options":["compare","throw","cook","sleep"],"explanation":"compare prices 比较价格。"},{"q":"6","answer":"B","options":["noise","deal","rain","game"],"explanation":"the best deal 最划算的交易。"},{"q":"7","answer":"C","options":["songs","gardens","problems","holidays"],"explanation":"has its problems 有它的问题。"},{"q":"8","answer":"D","options":["earlier","louder","higher","later"],"explanation":"arrive later than hoped 到货比预期晚。"},{"q":"9","answer":"A","options":["benefits","mistakes","prices","noises"],"explanation":"benefits are greater than problems 好处大于问题。"},{"q":"10","answer":"B","options":["price","mode","noise","garden"],"explanation":"a new mode of trade 新的贸易方式。"}]'::jsonb, 3, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (12, 'elective4', 'U2', 'A Family Decision', 'Last month, my family had to make a difficult (1)____: should we buy a new car or keep our old one? My father suggested that we should (2)____ the costs and benefits carefully before deciding. A new car would be comfortable, but it was very (3)____, and we would have to borrow money from the bank. Keeping the old car would (4)____ us a lot of money, though it sometimes broke down. We sat together and made a (5)____ of all the good and bad points. In the end, we decided to (6)____ for the old car and save the money for my education. My father said this was a (7)____ choice, because the extra cost of a new car was greater than its extra (8)____. I learned that thinking carefully can help a family (9)____ its money wisely. Now I always try to (10)____ before I spend.', 148, 2, '[{"q":"1","answer":"C","options":["holiday","garden","decision","song"],"explanation":"make a difficult decision 做艰难决定。"},{"q":"2","answer":"D","options":["throw","cook","hide","weigh"],"explanation":"weigh costs and benefits 权衡成本收益。"},{"q":"3","answer":"A","options":["expensive","quiet","empty","asleep"],"explanation":"very expensive 很贵。"},{"q":"4","answer":"B","options":["cost","save","lose","waste"],"explanation":"保留旧车 save money 省钱。"},{"q":"5","answer":"C","options":["noise","rain","list","game"],"explanation":"make a list 列清单。"},{"q":"6","answer":"D","options":["wait","sleep","cry","opt"],"explanation":"opt for the old car 选择旧车。"},{"q":"7","answer":"A","options":["wise","silly","empty","loud"],"explanation":"a wise choice 明智的选择。"},{"q":"8","answer":"B","options":["mistake","benefit","noise","garden"],"explanation":"extra benefit 额外收益。"},{"q":"9","answer":"C","options":["throw","break","spend","lose"],"explanation":"spend its money wisely 明智花钱。"},{"q":"10","answer":"D","options":["sleep","shout","run","think"],"explanation":"try to think before spending 花钱前先想。"}]'::jsonb, 4, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (12, 'elective4', 'U2', 'Trade Helps Both Sides', 'China''s factories produce goods that are sold in almost every (1)____ of the world. Because these products are good in quality but low in (2)____, families everywhere can afford them. At the same time, China buys huge amounts of goods from other countries, which (3)____ jobs for workers far away. When China''s demand for imports (4)____, factories abroad become busier and hire more people. In this way, trade (5)____ both sides, not just one. Some people once worried that cheap Chinese goods would (6)____ foreign workers, but in many places the opposite has happened. New trade has helped poorer countries (7)____ their economies and lift people out of (8)____. Of course, no system is (9)____, and leaders must work hard to share the gains fairly. Still, the steady flow of goods across borders has made the world more closely (10)____ than ever before.', 143, 2, '[{"q":"1","answer":"A","options":["part","price","noise","song"],"explanation":"every part of the world 世界各地。"},{"q":"2","answer":"B","options":["weather","price","noise","garden"],"explanation":"low in price 价格低。"},{"q":"3","answer":"C","options":["loses","breaks","creates","hides"],"explanation":"creates jobs 创造就业。"},{"q":"4","answer":"D","options":["falls","sleeps","sings","rises"],"explanation":"工厂更忙→demand rises 需求上升。"},{"q":"5","answer":"A","options":["helps","hurts","stops","ends"],"explanation":"trade helps both sides 贸易惠及双方。"},{"q":"6","answer":"B","options":["help","replace","teach","feed"],"explanation":"怕廉价货 replace 抢走外国工人工作。"},{"q":"7","answer":"C","options":["close","break","grow","lose"],"explanation":"grow their economies 发展经济。"},{"q":"8","answer":"D","options":["music","weather","sport","poverty"],"explanation":"out of poverty 摆脱贫困。"},{"q":"9","answer":"A","options":["perfect","afraid","asleep","hungry"],"explanation":"no system is perfect 没有完美的体系。"},{"q":"10","answer":"B","options":["divided","connected","forgotten","broken"],"explanation":"more closely connected 联系更紧密。"}]'::jsonb, 5, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (12, 'elective4', 'U2', 'A Budget for the Trip', 'Our class has saved one thousand yuan for a spring (1)____, and now we need a good plan to spend it. First, we brainstormed a long (2)____ of things we might buy, such as food, water, tickets and small gifts. Then we put the items in (3)____ of importance, from the most necessary to the least. For each item, we had to (4)____ its cost against how useful it would be. Some students wanted matching T-shirts so that we could easily (5)____ each other in a crowd, but others felt they were too (6)____. In the end, we (7)____ to buy a bright flag instead, which was cheaper and worked just as (8)____. By talking together, we made sure that every yuan was (9)____ wisely. Everyone agreed that careful planning had made our trip both fun and (10)____.', 138, 2, '[{"q":"1","answer":"C","options":["price","machine","outing","song"],"explanation":"spring outing 春游。"},{"q":"2","answer":"D","options":["noise","rain","game","list"],"explanation":"a long list 一长串清单。"},{"q":"3","answer":"A","options":["order","noise","weather","music"],"explanation":"in order of importance 按重要性排序。"},{"q":"4","answer":"B","options":["throw","weigh","cook","hide"],"explanation":"weigh cost against usefulness 权衡。"},{"q":"5","answer":"C","options":["lose","break","find","eat"],"explanation":"find each other 找到彼此。"},{"q":"6","answer":"D","options":["quiet","asleep","empty","expensive"],"explanation":"too expensive 太贵。"},{"q":"7","answer":"A","options":["decided","refused","forgot","slept"],"explanation":"decided to buy a flag 决定买旗子。"},{"q":"8","answer":"B","options":["badly","well","slowly","loudly"],"explanation":"worked just as well 同样管用。"},{"q":"9","answer":"C","options":["lost","thrown","spent","broken"],"explanation":"every yuan was spent wisely 每分钱都花得明智。"},{"q":"10","answer":"D","options":["useless","empty","silent","useful"],"explanation":"fun and useful 既有趣又有用。"}]'::jsonb, 6, 'sufe');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='elective4' AND unit='U2';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (12, 'U2 听力·对话 Bargaining at the Market', '上外版选择性必修第四册 U2 · dialogue', 3, 'Lin: How much is this beautiful silk scarf?
Seller: It''s two hundred yuan. The silk is of very high quality.
Lin: That sounds a bit expensive for me. Could you lower the price?
Seller: Well, how much are you willing to pay for it?
Lin: I was thinking about one hundred and forty yuan.
Seller: That''s too low. But because business is slow today, I can offer one hundred and seventy.
Lin: How about one hundred and sixty, and I''ll take two of them?
Seller: All right, it''s a deal. Two scarves for three hundred and twenty yuan.', '林问丝巾多少钱;卖家要价二百元,说丝绸质量很好;林觉得贵,请求降价;卖家问她愿出多少;林想出一百四;卖家说太低,但因今天生意清淡可降到一百七;林提出一百六并买两条;卖家同意,两条共三百二十元成交。', 'uk_female', '[{"q":"What does Lin want to buy?","type":"choice","answer":"A","options":["A silk scarf.","A pair of shoes.","A gold ring.","A leather bag."]},{"q":"What is the seller''s first price for one scarf?","type":"choice","answer":"B","options":["One hundred and forty yuan.","Two hundred yuan.","One hundred and seventy yuan.","Three hundred and twenty yuan."]},{"q":"Why does the seller agree to lower the price?","type":"choice","answer":"A","options":["Because business is slow today.","Because the scarf is of poor quality.","Because Lin is a close friend.","Because the shop is closing forever."]},{"q":"How much does Lin first offer to pay?","type":"choice","answer":"B","options":["One hundred and sixty yuan.","One hundred and forty yuan.","One hundred and seventy yuan.","Two hundred yuan."]},{"q":"What is the final deal they reach?","type":"choice","answer":"C","options":["One scarf for two hundred yuan.","Three scarves for free.","Two scarves for three hundred and twenty yuan.","One scarf for one hundred and forty yuan."]}]'::jsonb, '[]'::jsonb, 'long', 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (12, 'U2 听力·短文 Chinese Travellers Abroad', '上外版选择性必修第四册 U2 · passage', 2, 'Each year, millions of Chinese travellers visit other countries.
When they spend money on hotels, food and shopping abroad, they help create jobs in those places.
In 2017, Chinese tourists made more than one hundred million trips overseas.
This spending is good for the countries they visit, and it is also a kind of trade.
As more people travel, the world becomes more closely connected.', '每年有数百万中国游客出国;他们在国外的住宿、餐饮和购物花费帮助当地创造就业;2017年中国游客出境超过一亿人次;这种花费有利于所到国家,也是一种贸易;随着更多人出行,世界联系更紧密。', 'uk_female', '[{"q":"Who travels abroad each year, according to the passage?","type":"choice","answer":"D","options":["Only a few rich people.","Only government officials.","Nobody at all.","Millions of Chinese travellers."]},{"q":"How does their spending help other countries?","type":"choice","answer":"A","options":["It helps create jobs there.","It closes local shops.","It makes hotels empty.","It stops local trade."]},{"q":"How many overseas trips did Chinese tourists make in 2017?","type":"choice","answer":"B","options":["About one hundred.","More than one hundred million.","Fewer than ten.","Exactly one thousand."]},{"q":"What is tourist spending described as?","type":"choice","answer":"C","options":["A kind of tax.","A waste of money.","A kind of trade.","A type of farming."]},{"q":"What happens as more people travel?","type":"choice","answer":"D","options":["The world becomes more divided.","Trade comes to an end.","Travel becomes impossible.","The world becomes more closely connected."]}]'::jsonb, '[]'::jsonb, 'short', 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (12, 'U2 听力·对话 Returning a Faulty Phone', '上外版选择性必修第四册 U2 · dialogue', 3, 'Customer: Excuse me, I bought this phone here yesterday, but it won''t turn on.
Manager: I''m very sorry to hear that. Let me have a look at it.
Customer: I''ve already tried charging it all night, and nothing happens.
Manager: You''re right, it does seem broken. Would you like a free repair?
Customer: Considering all the trouble, I''d prefer a new phone or my money back.
Manager: I understand. I can give you a brand-new phone of the same model.
Customer: That sounds fair. Thank you for solving it so quickly.
Manager: It was our mistake, so there is no charge at all.', '顾客说昨天买的手机开不了机;经理道歉并查看;顾客说已充了一整夜电仍无反应;经理承认手机坏了,提出免费维修;顾客考虑到麻烦,更想换新机或退款;经理同意换一部同型号新机;顾客觉得公道并致谢;经理说是店里的过错,不收任何费用。', 'uk_female', '[{"q":"What problem does the customer have?","type":"choice","answer":"A","options":["The phone won''t turn on.","The phone is too expensive.","The phone is the wrong colour.","The phone is too small."]},{"q":"What had the customer already tried?","type":"choice","answer":"B","options":["Selling it online.","Charging it all night.","Dropping it in water.","Giving it away."]},{"q":"What does the manager first offer?","type":"choice","answer":"C","options":["A full refund at once.","A free meal.","A free repair.","A new colour."]},{"q":"What does the customer ask for instead?","type":"choice","answer":"D","options":["Only a free repair.","A free phone case.","Nothing at all.","A new phone or a refund."]},{"q":"What does the manager finally agree to give?","type":"choice","answer":"A","options":["A brand-new phone of the same model.","An older, cheaper phone.","Only an apology.","Half of the money back."]}]'::jsonb, '[]'::jsonb, 'long', 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (12, 'U2 听力·短文 The Hidden Cost', '上外版选择性必修第四册 U2 · passage', 2, 'Every choice you make has a hidden cost.
Suppose you spend a whole afternoon playing games.
The real cost is not zero; it is the homework you did not finish or the book you did not read.
Economists call this the opportunity cost.
Thinking about this hidden cost helps us make wiser choices every day.', '你做的每个选择都有隐藏成本;假设你花整个下午打游戏;真正的成本不是零,而是没写完的作业或没读的书;经济学家称之为机会成本;考虑这种隐藏成本能帮我们每天做出更明智的选择。', 'uk_female', '[{"q":"What does every choice have, according to the speaker?","type":"choice","answer":"B","options":["No cost at all.","A hidden cost.","A free gift.","A fixed price."]},{"q":"If you play games all afternoon, what is the real cost?","type":"choice","answer":"C","options":["Nothing whatsoever.","The money you earn.","The homework or reading you give up.","The new friends you make."]},{"q":"What do economists call this kind of cost?","type":"choice","answer":"D","options":["The yearly tax.","The ticket price.","The interest rate.","The opportunity cost."]},{"q":"What does thinking about the hidden cost help us do?","type":"choice","answer":"A","options":["Make wiser choices.","Spend without thinking.","Forget our homework.","Avoid all decisions."]},{"q":"How long does the example afternoon of games last?","type":"choice","answer":"B","options":["Only five minutes.","A whole afternoon.","A full week.","One short hour."]}]'::jsonb, '[]'::jsonb, 'short', 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (12, 'U2 听力·对话 A New Phone or Save?', '上外版选择性必修第四册 U2 · dialogue', 3, 'Mei: My old phone still works fine, but I really want the new model.
Tom: How much more does the new one cost?
Mei: About a thousand yuan more than I had planned to spend.
Tom: Is the new phone really a thousand yuan better than your old one?
Mei: Hmm, when you put it that way, maybe not.
Tom: You could save that money for your summer trip instead.
Mei: You''re right. The extra features just aren''t worth the extra cost.
Tom: That''s smart thinking. Your old phone is still good enough.', '梅说旧手机还能用,但很想要新款;汤姆问新机贵多少;梅说比预算多约一千元;汤姆问新机真比旧机好一千元吗;梅说这么一想也许不值;汤姆建议把钱留作暑假旅行;梅认同,额外功能不值额外成本;汤姆夸她想得明智,旧手机仍够用。', 'uk_female', '[{"q":"What does Mei want at the start?","type":"choice","answer":"C","options":["A new summer trip.","A cheaper old phone.","The new phone model.","A larger schoolbag."]},{"q":"How much more does the new phone cost?","type":"choice","answer":"D","options":["Exactly the same as the old one.","About ten yuan more.","Nothing extra at all.","About a thousand yuan more than planned."]},{"q":"What question does Tom ask Mei to think about?","type":"choice","answer":"A","options":["Whether the new phone is worth the extra cost.","Whether she likes the colour.","Whether the shop is open.","Whether Tom can borrow it."]},{"q":"What does Tom suggest doing with the money?","type":"choice","answer":"B","options":["Buying two new phones.","Saving it for her summer trip.","Giving it all to him.","Throwing it away."]},{"q":"What does Mei finally decide?","type":"choice","answer":"C","options":["She must buy the new phone today.","Her old phone is useless now.","The extra features aren''t worth the extra cost.","She will never use a phone again."]}]'::jsonb, '[]'::jsonb, 'long', 'elective4', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (12, 'U2 听力·短文 How One Yuan Travels', '上外版选择性必修第四册 U2 · passage', 2, 'Money does not stay still; it travels through the whole economy.
Imagine you put one yuan into the bank.
The bank can lend that yuan to a builder, who pays it to a worker.
The worker then spends it at a shop, and the shopkeeper saves it in the bank again.
In this way, a single coin can help many different people earn a living.', '钱不会静止,它在整个经济中流动;假设你把一元存进银行;银行可把它借给建筑工,后者付给工人;工人在商店花掉,店主又存进银行;这样一枚硬币能帮助许多不同的人谋生。', 'uk_female', '[{"q":"What does money do, according to the passage?","type":"choice","answer":"D","options":["It always stays in one place.","It quickly disappears.","It loses all its value.","It travels through the economy."]},{"q":"What can the bank do with the yuan you save?","type":"choice","answer":"A","options":["Lend it to a builder.","Burn it for fun.","Hide it forever.","Send it abroad by post."]},{"q":"After the worker is paid, what does the worker do with the money?","type":"choice","answer":"B","options":["Buries it underground.","Spends it at a shop.","Tears it into pieces.","Returns it to the builder."]},{"q":"What can a single coin do, according to the speaker?","type":"choice","answer":"C","options":["Stop all trade at once.","Make everyone poorer.","Help many people earn a living.","Be used only one time."]},{"q":"Where does the shopkeeper put the money at the end?","type":"choice","answer":"D","options":["Into the sea.","Onto the street.","Into a fire.","Back into the bank."]}]'::jsonb, '[]'::jsonb, 'short', 'elective4', 'U2', 'sufe');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='elective4' AND unit='U2';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (12, 'Writing a Summary of a Problem-Solution Essay(为问题—解决型短文写摘要)', 'Summarising ''Rational People Think at the Margin''', '阅读短文 ''Rational People Think at the Margin'',用英语写一篇不超过60词的摘要。要求:① 抓住核心观点(生活中的决策多为''边际''上的小调整);② 说清判断方法(比较多走一步的额外收益与额外成本);③ 用自己的话改写、不照抄原句、句型多样。', 'Read the essay ''Rational People Think at the Margin'' and write a summary of no more than 60 words. Capture the main idea (most real-life decisions are small steps ''at the margin''), state how to judge such a step (compare its extra benefit with its extra cost), and use your own words rather than copying the original sentences.', '["抓核心:决策多是边际上的小调整,不是非此即彼","讲方法:比较多走一步的额外收益与额外成本","下结论:额外收益大于额外成本才行动","用同义改写、句型多样、控制在60词内"]'::jsonb, 70, 100, 'Most real-life decisions are not all-or-nothing choices but small steps that economists call marginal changes. To choose wisely, we should compare the extra benefit of one more step with its extra cost. A rational person takes an action only when that added benefit outweighs the added cost. In short, thinking at the margin helps people make better everyday decisions.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["Most real-life decisions are small steps that economists call marginal changes.","We should compare the extra benefit of one more step with its extra cost.","A rational person acts only when the added benefit outweighs the added cost.","Thinking at the margin helps people make better everyday decisions."]'::jsonb, '[{"wrong":"The essay tells about how to decide.","correct":"The essay explains how to make decisions.","note":"摘要用 explain/describe 等更书面的概括动词,避免口语 tell about。"},{"wrong":"Compare the benefit with the cost is important.","correct":"Comparing the benefit with the cost is important.","note":"句首作主语用动名词 Comparing,不能用动词原形。"},{"wrong":"People should act when the benefit is more bigger than the cost.","correct":"People should act when the benefit is bigger than the cost.","note":"bigger 已是比较级,不再加 more。"}]'::jsonb, '【经济短文摘要结构(≤60词)】
第1句 核心:Most decisions are small steps called marginal changes.
第2句 方法:Compare the extra benefit of one more step with its extra cost.
第3句 结论:Act only when the added benefit outweighs the added cost.
第4句 收束:Thinking at the margin helps people decide better.', 2, 'elective4', 'U2', 'sufe');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='elective4' AND unit='U2';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (12, 'elective4', 'U2', '{"title":"非谓语动词速查:-ing / -ed 分词与不定式","intro":"非谓语动词不能单独作谓语,也不受主谓一致影响。判断三步:① 看它在句中作什么(宾语/定语/状语…);② 看与逻辑主语是主动还是被动;③ 看前面的动词或结构有没有固定搭配。","table":{"headers":["形式","核心含义","常见用法"],"rows":[["to do(不定式)","表将要做、目的、结果","作主语/宾语;表目的(to/in order to);too…to、enough to;adj.+to do"],["-ing(现在分词/动名词)","表主动、正在进行","作动名词宾语(enjoy/finish/avoid doing);作定语(a growing market)/状语(主动)"],["-ed(过去分词)","表被动、已完成","作定语(imported goods)/状语(被动);作表语/补语"]]},"specialRules":[{"rule":"只接动名词的动词:enjoy/finish/avoid/suggest/consider/mind/practise/keep/admit/give up","mark":"finish signing √ / finish to sign ×"},{"rule":"只接不定式的动词:decide/hope/agree/offer/refuse/manage/plan/promise/afford/expect","mark":"decide to expand √ / decide expanding ×"},{"rule":"分词作定语/状语:主动且''正在/发出''→ -ing;被动且''被…/已完成''→ -ed","mark":"a growing economy(主动) / goods produced here(被动)"},{"rule":"固定结构后只用不定式:too…to、enough to、the way/first/best…to、be likely/ready/willing/able to","mark":"too expensive to sell;the best way to cut costs"}],"why":["-ing 与 -ed 的根本区别是''主动 vs 被动'':名词自己发出动作用 -ing,名词承受动作用 -ed;同理状语中,逻辑主语主动用 -ing,被动用 -ed。","动名词与不定式哪个作宾语,主要由前面的动词决定,属固定搭配,需要记忆,但多数有''已发生(doing)/将要做(to do)''的语感规律。"],"gaokaoPoints":["语法填空高频:给动词原形,要求填 doing / to do / done;先判成分再判主被动。","分词作状语要找逻辑主语,避免''悬垂分词'';目的状语优先用 to do 或 in order to do。","remember/forget/stop/try + doing 与 + to do 含义不同(高考易考,但本单元以单义动词为主)。"],"examVsReal":[{"exam":"In order to save money, we made a plan.(考试/书面)","real":"To save money, we made a plan. / We made a plan to save money.","note":"口语里 in order 常省略,直接 to do 表目的即可。"},{"exam":"The goods produced here are cheap.(考试用过去分词)","real":"The goods (that are) produced here are cheap.","note":"过去分词作定语本质是被动定语从句的省略形式。"}]}'::jsonb, 'sufe');

COMMIT;

-- ===== 自带校验(publisher='sufe') =====
SELECT 'vocab' k, count(*) v, 48 expect FROM public.junior_vocab WHERE publisher='sufe' AND volume='elective4' AND unit='U2'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective4' AND unit='U2')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='sufe' AND volume='elective4' AND unit='U2'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='sufe' AND volume='elective4' AND unit='U2'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='elective4' AND unit='U2'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='elective4' AND unit='U2'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='elective4' AND unit='U2' ORDER BY k;
