-- ============================================================
-- 上外(sufe) 必修一 U1(Road to Success)灌库(junior_* 表,publisher='sufe' volume='required3' unit='U1' grade=10)。幂等。
-- ★DELETE 全带 publisher='sufe',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 46 =====
DELETE FROM public.junior_vocab WHERE publisher='sufe' AND volume='required3' AND unit='U1';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'success', 'n.', '/səkˈses/', '成功;成就', 'Hard work is often the road to success.', '努力往往是通往成功之路。', 'Road to Success', 1, 0, 'senior', 'wordlist', 'required3', 'U1', 'the road to success', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'successful', 'adj.', '/səkˈsesfl/', '成功的;有成就的', 'A successful person keeps trying after failure.', '成功的人在失败后仍坚持尝试。', 'Road to Success', 2, 0, 'senior', 'wordlist', 'required3', 'U1', 'a successful person', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'struggle', 'n./v.', '/ˈstrʌɡl/', '奋斗;努力;艰难地拼搏', 'Her success came after a long struggle.', '她的成功来自长期的奋斗。', 'Road to Success', 3, 0, 'senior', 'wordlist', 'required3', 'U1', 'a long struggle', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'commitment', 'n.', '/kəˈmɪtmənt/', '献身;投入;承诺', 'Her commitment to her work never weakened.', '她对工作的投入从未减弱。', 'Road to Success', 4, 0, 'senior', 'wordlist', 'required3', 'U1', 'passionate commitment', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'passionate', 'adj.', '/ˈpæʃənət/', '热诚的;热情的', 'He is passionate about helping young scientists.', '他热心于帮助年轻的科学家。', 'Road to Success', 5, 0, 'senior', 'wordlist', 'required3', 'U1', 'passionate about', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'career', 'n.', '/kəˈrɪə(r)/', '职业生涯;职业', 'Winning the prize was the happiest moment in her career.', '获奖是她职业生涯中最快乐的时刻。', 'Road to Success', 6, 0, 'senior', 'wordlist', 'required3', 'U1', 'in her career', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'moment', 'n.', '/ˈməʊmənt/', '时刻;片刻;时机', 'The discovery was a really happy moment for the whole team.', '这一发现对整个团队来说是非常快乐的时刻。', 'Road to Success', 7, 0, 'senior', 'wordlist', 'required3', 'U1', 'a happy moment', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'talent', 'n.', '/ˈtælənt/', '天赋;才能;天才', 'He coupled his talent with years of hard work.', '他把天赋和多年的努力结合在一起。', 'Road to Success', 8, 0, 'senior', 'wordlist', 'required3', 'U1', 'natural talent', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'worthwhile', 'adj.', '/ˌwɜːθˈwaɪl/', '值得做的;值得花时间(或精力)的', 'Her commitment made the long struggle worthwhile.', '她的投入使长期的奋斗变得值得。', 'Road to Success', 9, 0, 'senior', 'wordlist', 'required3', 'U1', 'make it worthwhile', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'modest', 'adj.', '/ˈmɒdɪst/', '谦虚的;谦逊的', 'A modest person, she gave the credit to her team.', '她为人谦逊,把功劳归于团队。', 'Road to Success', 10, 0, 'senior', 'wordlist', 'required3', 'U1', 'a modest person', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'cure', 'n./v.', '/kjʊə(r)/', '药物;疗法;治愈', 'She spent years searching for a cure for the disease.', '她花了多年寻找治疗这种疾病的方法。', 'Road to Success', 11, 0, 'senior', 'wordlist', 'required3', 'U1', 'find a cure', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'treatment', 'n.', '/ˈtriːtmənt/', '治疗;疗法;诊治', 'The team searched for a new treatment in nature.', '团队在自然界中寻找新的疗法。', 'Road to Success', 12, 0, 'senior', 'wordlist', 'required3', 'U1', 'a new treatment', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'disease', 'n.', '/dɪˈziːz/', '病;疾病', 'They found the key to beating the disease in old books.', '他们在古书中找到了战胜这种疾病的关键。', 'Road to Success', 13, 0, 'senior', 'wordlist', 'required3', 'U1', 'beat the disease', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'cancer', 'n.', '/ˈkænsə(r)/', '癌;癌症', 'About a year ago he was diagnosed with cancer.', '大约一年前他被诊断出患有癌症。', 'Road to Success', 14, 0, 'senior', 'wordlist', 'required3', 'U1', 'be diagnosed with cancer', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'curable', 'adj.', '/ˈkjʊərəbl/', '可医治的;可治愈的', 'Luckily, the illness turned out to be curable with surgery.', '幸运的是,这种病通过手术是可以治愈的。', 'Road to Success', 15, 0, 'senior', 'wordlist', 'required3', 'U1', 'be curable with surgery', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'surgery', 'n.', '/ˈsɜːdʒəri/', '外科手术;外科', 'He had the surgery and is fine now.', '他做了手术,现在没事了。', 'Road to Success', 16, 0, 'senior', 'wordlist', 'required3', 'U1', 'have surgery', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'examine', 'v.', '/ɪɡˈzæmɪn/', '审查;考查;(仔细地)检查', 'Her team examined hundreds of old medical books.', '她的团队审查了数百本古医书。', 'Road to Success', 17, 0, 'senior', 'wordlist', 'required3', 'U1', 'examine the books', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'gather', 'v.', '/ˈɡæðə(r)/', '收集;聚集;归拢', 'They interviewed many doctors to gather information.', '他们采访许多医生以收集信息。', 'Road to Success', 18, 0, 'senior', 'wordlist', 'required3', 'U1', 'gather information', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'summarise', 'v.', '/ˈsʌməraɪz/', '总结;概括;概述', 'She summarised hundreds of old prescriptions in one collection.', '她把数百个古方概括进一本集子里。', 'Road to Success', 19, 0, 'senior', 'wordlist', 'required3', 'U1', 'summarise the points', '美式拼 summarize;美音 /ˈsʌməraɪz/', 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'collection', 'n.', '/kəˈlekʃn/', '文集;收藏品;收集物', 'Her work was published as a collection of prescriptions.', '她的成果以一本药方集的形式出版。', 'Road to Success', 20, 0, 'senior', 'wordlist', 'required3', 'U1', 'a collection of', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'conclusive', 'adj.', '/kənˈkluːsɪv/', '结论性的;确凿的;不容置疑的', 'At first the results were not conclusive enough.', '起初实验结果还不够确凿。', 'Road to Success', 21, 0, 'senior', 'wordlist', 'required3', 'U1', 'conclusive results', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'widespread', 'adj.', '/ˈwaɪdspred/', '分布广的;普遍的;广泛的', 'She went to the south, where the disease was widespread.', '她去了南方,那里这种疾病很普遍。', 'Road to Success', 22, 0, 'senior', 'wordlist', 'required3', 'U1', 'widespread disease', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'limited', 'adj.', '/ˈlɪmɪtɪd/', '有限的', 'Your time is limited, so don''t waste it on someone else''s life.', '你的时间有限,别浪费在过别人的生活上。', 'Road to Success', 23, 0, 'senior', 'wordlist', 'required3', 'U1', 'be limited', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'amazing', 'adj.', '/əˈmeɪzɪŋ/', '令人惊奇的;令人惊叹的', 'When he was young there was an amazing magazine he loved.', '他年轻时有一本他喜爱的了不起的杂志。', 'Road to Success', 24, 0, 'senior', 'wordlist', 'required3', 'U1', 'an amazing publication', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'issue', 'n.', '/ˈɪʃuː/', '(报刊的)一期;重要议题;问题', 'The words appeared on the back cover of the final issue.', '这些话印在最后一期的封底上。', 'Road to Success', 25, 0, 'senior', 'wordlist', 'required3', 'U1', 'the final issue', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'path', 'n.', '/pɑːθ/', '(成功的)途径;小路;小径', 'Everyone has to find his own path to success.', '每个人都得找到自己通向成功的路。', 'Road to Success', 26, 0, 'senior', 'wordlist', 'required3', 'U1', 'a path to success', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'further', 'v.', '/ˈfɜːðə(r)/', '促进;增进', 'She went to the capital to further her studies in medicine.', '她去首都深造,继续她的医学研究。', 'Road to Success', 27, 0, 'senior', 'wordlist', 'required3', 'U1', 'further her studies', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'dynasty', 'n.', '/ˈdɪnəsti/', '王朝;朝代', 'The answer lay in a book from the East Jin dynasty.', '答案藏在一本东晋时期的书中。', 'Road to Success', 28, 0, 'senior', 'wordlist', 'required3', 'U1', 'the East Jin dynasty', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'title', 'n.', '/ˈtaɪtl/', '称号;头衔;职称', 'He was honoured with the title "People''s Artist".', '他被授予"人民艺术家"的称号。', 'Road to Success', 29, 0, 'senior', 'wordlist', 'required3', 'U1', 'win the title', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'display', 'n./v.', '/dɪˈspleɪ/', '陈列;展览;展示', 'His paintings of shrimps are often on display.', '他画的虾常常被展出。', 'Road to Success', 30, 0, 'senior', 'wordlist', 'required3', 'U1', 'on display', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'shade', 'n.', '/ʃeɪd/', '(颜色的)浓淡深浅;色度;阴凉处', 'He used different shades of black ink to paint a shrimp.', '他用深浅不同的黑墨来画虾。', 'Road to Success', 31, 0, 'senior', 'wordlist', 'required3', 'U1', 'shades of black', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'harvest', 'n.', '/ˈhɑːvɪst/', '收成;收获;收获量', 'His paintings of vegetables stand for a rich harvest.', '他画的蔬菜象征着丰收。', 'Road to Success', 32, 0, 'senior', 'wordlist', 'required3', 'U1', 'a rich harvest', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'symbolic', 'adj.', '/sɪmˈbɒlɪk/', '象征性的;象征的', 'In his art the dove is symbolic of peace.', '在他的画中鸽子象征着和平。', 'Road to Success', 33, 0, 'senior', 'wordlist', 'required3', 'U1', 'symbolic of', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'beyond', 'prep.', '/bɪˈjɒnd/', '超出;在……之外', 'His works go beyond the simple painting of fish.', '他的作品超越了对鱼的简单描绘。', 'Road to Success', 34, 0, 'senior', 'wordlist', 'required3', 'U1', 'go beyond', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'base', 'v.', '/beɪs/', '以……作为基础(或根据)', 'At first he based his paintings on ancient models.', '起初他以古人的范本为基础作画。', 'Road to Success', 35, 0, 'senior', 'wordlist', 'required3', 'U1', 'base on', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'achieve', 'v.', '/əˈtʃiːv/', '实现;取得;达到', 'He achieved success by coupling talent with hard work.', '他凭借天赋加苦干取得了成功。', 'Road to Success', 36, 0, 'senior', 'wordlist', 'required3', 'U1', 'achieve success', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'achievement', 'n.', '/əˈtʃiːvmənt/', '成就;成绩;达成', 'Reflect on your own greatest achievement and share it.', '回想你自己最大的成就并分享它。', 'Road to Success', 37, 0, 'senior', 'wordlist', 'required3', 'U1', 'a great achievement', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'predictor', 'n.', '/prɪˈdɪktə(r)/', '预示因素;预测因子', 'Grit is a significant predictor of success.', '毅力是预示成功的重要因素。', 'Road to Success', 38, 0, 'senior', 'wordlist', 'required3', 'U1', 'a predictor of success', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'outcome', 'n.', '/ˈaʊtkʌm/', '结果;结局', 'She went away satisfied with the outcome of her work.', '她对工作的结果感到满意而离开。', 'Road to Success', 39, 0, 'senior', 'wordlist', 'required3', 'U1', 'the outcome', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'significant', 'adj.', '/sɪɡˈnɪfɪkənt/', '重要的;意义重大的', 'Hard work is a significant factor in any success.', '努力是任何成功中的一个重要因素。', 'Road to Success', 40, 0, 'senior', 'wordlist', 'required3', 'U1', 'a significant factor', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'tough', 'adj.', '/tʌf/', '困难的;艰苦的;坚强的', 'People with grit do well even in tough situations.', '有毅力的人即使在艰难处境中也能做得好。', 'Road to Success', 41, 0, 'senior', 'wordlist', 'required3', 'U1', 'a tough situation', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'perseverance', 'n.', '/ˌpɜːsɪˈvɪərəns/', '坚持不懈;不屈不挠', 'A person with grit has perseverance for long-term goals.', '有毅力的人对长期目标有不屈不挠的坚持。', 'Road to Success', 42, 0, 'senior', 'wordlist', 'required3', 'U1', 'courage and perseverance', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'factor', 'n.', '/ˈfæktə(r)/', '因素;要素', 'List three factors that led to your achievement.', '列出促成你成就的三个因素。', 'Road to Success', 43, 0, 'senior', 'wordlist', 'required3', 'U1', 'a key factor', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'reflect', 'v.', '/rɪˈflekt/', '反思;思考;反映', 'Reflect on your achievements and write down your secrets.', '反思你的成就并写下你的秘诀。', 'Road to Success', 44, 0, 'senior', 'wordlist', 'required3', 'U1', 'reflect on', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'contribute', 'v.', '/kənˈtrɪbjuːt/', '促成;贡献;捐助', 'List the factors that contribute to this achievement.', '列出促成这一成就的各个因素。', 'Road to Success', 45, 0, 'senior', 'wordlist', 'required3', 'U1', 'contribute to', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'overcome', 'v.', '/ˌəʊvəˈkʌm/', '克服;战胜', 'Through practice I have overcome my fear of public speaking.', '通过练习我克服了当众讲话的恐惧。', 'Road to Success', 46, 0, 'senior', 'wordlist', 'required3', 'U1', 'overcome fear', NULL, 'sufe');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1');
DELETE FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s3u1.01', '①-ing 作补语(感官/使役 + 现在分词:主动、正在进行)', 'A2', 10, '上外版必修第三册 U1 — see/hear/watch/notice/feel/find/keep/leave + sb/sth + 现在分词(doing):宾语主动发出动作、动作正在进行时,补语用 -ing 形式。', 1, 'required3', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s3u1.02', '②-ed 作补语(have/get/make/find/keep sth + 过去分词:被动、已完成)', 'A2', 10, '上外版必修第三册 U1 — have/get/make/find/keep/leave/want + sth + 过去分词(done):宾语承受动作、动作已完成或被动,补语用 -ed 形式,如 have my hair cut。', 2, 'required3', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s3u1.03', '③-ing vs -ed 补语辨析(由宾语与分词的主被动关系判定)', 'A2', 10, '上外版必修第三册 U1 — 宾语主动发出动作、动作进行中 → 用 -ing(I saw him crossing);宾语承受动作、动作被动/已完成 → 用 -ed(I saw the work done)。看宾语和分词谁主动谁被动来选。', 3, 'required3', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'During the interview, the comic star could feel his heart ____ fast.', 'beating', 'beaten', 'to beat', 'beat', 'A', 'his heart 主动跳动、动作正在进行 → 现在分词 beating。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'After midnight, the professor was seen ____ an experiment in the lab.', 'done', 'doing', 'to doing', 'did', 'B', '宾语(被见者)主动做实验、动作进行中 → doing。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'It was friendship that kept me ____ during my hardest time.', 'gone', 'to go', 'going', 'go', 'C', 'keep sb doing:me 主动''坚持下去''、动作持续 → going。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'The teacher found the child ____ on the wall with a piece of chalk.', 'written', 'to write', 'wrote', 'writing', 'D', 'the child 主动在写、动作进行中 → writing。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'We heard Tu Youyou ____ about her years of hard research.', 'talking', 'talked', 'to talk', 'talk about', 'A', 'hear sb doing:她主动讲述、动作进行中 → talking。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'The lecturer was heard ____ his success story in the next room.', 'told', 'telling', 'to tell', 'tells', 'B', '被听者主动讲述、动作进行中 → telling。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'From the window I watched the runners ____ slowly up the long hill.', 'climbed', 'to climb', 'climbing', 'climb up', 'C', 'watch sb doing:runners 主动爬坡、动作进行中 → climbing。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'Don''t leave the tap ____ while you brush your teeth.', 'run', 'to run', 'ran', 'running', 'D', 'leave sth doing:the tap 主动''流''、状态持续 → running。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'She noticed her young students ____ harder than ever before the exam.', 'working', 'worked', 'to work', 'work hard', 'A', 'notice sb doing:students 主动学习、进行中 → working。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'The coach kept the whole team ____ even when they wanted to quit.', 'trained', 'trying', 'to try', 'tries', 'B', 'keep sb doing:team 主动坚持尝试 → trying。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'Late at night, neighbours could hear the young pianist ____ the same piece.', 'practised', 'to practise', 'practising', 'practise', 'C', 'hear sb doing:pianist 主动练习、进行中 → practising。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'I caught my little brother ____ at my secret notebook again.', 'looked', 'to look', 'look', 'looking', 'D', 'catch sb doing:brother 主动偷看、进行中 → looking。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'On the screen we saw the scientist ____ the plant for a cure.', 'testing', 'tested', 'to test', 'test on', 'A', 'see sb doing:scientist 主动测试、进行中 → testing。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'The doctor felt the patient''s hand ____ as the good news arrived.', 'shaken', 'shaking', 'to shake', 'shakes', 'B', 'feel sth doing:hand 主动颤抖、进行中 → shaking。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'During the speech, I could see many graduates ____ with hope.', 'smiled', 'to smile', 'smiling', 'smile', 'C', 'see sb doing:graduates 主动微笑、进行中 → smiling。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'We left the lights ____ so that the late workers could find their way.', 'shone', 'to shine', 'shines', 'shining', 'D', 'leave sth doing:lights 主动''亮着''、状态持续 → shining。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'Through the door, she watched her father ____ over his old medical books.', 'bending', 'bent', 'to bend', 'bend down', 'A', 'watch sb doing:father 主动俯身、进行中 → bending。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'Suddenly we heard the crowd ____ the marathon runner''s name.', 'shouted', 'shouting', 'to shout', 'shout out', 'B', 'hear sb doing:crowd 主动呼喊、进行中 → shouting。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'He found his old teacher still ____ in the same quiet office.', 'worked', 'to work', 'working', 'work', 'C', 'find sb doing:teacher 主动工作、进行中 → working。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.01'), 'The nurse kept the medicine ____ slowly into the patient''s arm.', 'flowed', 'to flow', 'flow in', 'flowing', 'D', 'keep sth doing:medicine 主动''流''、动作持续 → flowing。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'The writer wants his new novel ____ at the book fair next week.', 'displayed', 'displaying', 'to display', 'display', 'A', 'want sth done:novel 被展示、动作被动 → displayed。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'Before the big speech, he went to have his hair ____ short.', 'cutting', 'cut', 'to cut', 'cuts', 'B', 'have sth done:hair 被剪 → 过去分词 cut。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'After much persistence, the team finally got the problem ____.', 'solving', 'to solve', 'solved', 'solve', 'C', 'get sth done:problem 被解决、已完成 → solved。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'All afternoon she worked in the study with the door ____.', 'locking', 'to lock', 'lock', 'locked', 'D', 'with the door done:door 被锁 → locked。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'Tammy was disappointed to find her suggestions ____ down.', 'turned', 'turning', 'to turn', 'turn', 'A', 'find sth done:suggestions 被否决 → turned(down)。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'Tu Youyou wanted the old prescriptions ____ into a single collection.', 'gathering', 'gathered', 'to gather', 'gather', 'B', 'want sth done:prescriptions 被收集 → gathered。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'She finally had the new treatment ____ as safe for humans.', 'proving', 'to prove', 'proved', 'prove', 'C', 'have sth done:treatment 被证明、已完成 → proved。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'He kept his eyes ____ during the last few minutes of the surgery.', 'closing', 'to close', 'close', 'closed', 'D', 'keep sth done:eyes 被闭上、状态已成 → closed。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'The young poet managed to get a collection of her poems ____.', 'published', 'publishing', 'to publish', 'publish', 'A', 'get sth done:poems 被出版 → published。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'With her talent ____ by more and more people, she became famous.', 'recognising', 'recognised', 'to recognise', 'recognise', 'B', 'with sth done:talent 被认可 → recognised。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'Make yourself ____ — speak slowly and clearly to the audience.', 'understanding', 'to understand', 'understood', 'understand', 'C', 'make oneself done:被理解 → understood(make oneself understood 固定)。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'She left most of the work ____ until the results were conclusive.', 'finishing', 'to finish', 'finish', 'unfinished', 'D', 'leave sth done:work 被''未完成''状态 → unfinished(过去分词作补语)。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'The committee wants the meeting room ____ before the guests arrive.', 'prepared', 'preparing', 'to prepare', 'prepare', 'A', 'want sth done:room 被布置好 → prepared。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'He was brave enough to have the test ____ on himself first.', 'running', 'run', 'to run', 'runs', 'B', 'have sth done:test 被进行 → run(过去分词)。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'After the long debate, she finally made her point ____ to everyone.', 'showing', 'to show', 'shown', 'show', 'C', 'make sth done:point 被说清楚 → shown。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'With the experiment ____ at last, the whole team cheered.', 'completing', 'to complete', 'complete', 'completed', 'D', 'with sth done:experiment 被完成 → completed。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'She got the ancient book ____ word by word to find the answer.', 'examined', 'examining', 'to examine', 'examine', 'A', 'get sth done:book 被审查 → examined。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'The artist wanted his shrimps ____ in shades of black ink.', 'painting', 'painted', 'to paint', 'paint', 'B', 'want sth done:shrimps 被画 → painted。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'He kept his goal clearly ____ in his mind for many years.', 'fixing', 'to fix', 'fixed', 'fix', 'C', 'keep sth done:goal 被固定/记牢 → fixed。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.02'), 'Don''t leave your dream ____ — work hard to make it real.', 'forgetting', 'to forget', 'forget', 'forgotten', 'D', 'leave sth done:dream 被遗忘 → forgotten。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'I saw the young researcher ____ tests on the plant all night long.', 'running', 'run', 'to run', 'runs', 'A', '宾语 researcher 主动做测试、进行中 → 现在分词 running。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'She had the final results ____ before she dared to announce them.', 'checking', 'checked', 'to check', 'check', 'B', '宾语 results 被核对、动作被动 → 过去分词 checked。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'We watched the old painter ____ a shrimp with a few quick strokes.', 'drawn', 'to draw', 'drawing', 'draw it', 'C', '宾语 painter 主动作画、进行中 → drawing。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'He finally got his speech ____ in time for the graduation.', 'writing', 'to write', 'write', 'written', 'D', '宾语 speech 被写出、被动完成 → written。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'Through the door we could hear someone ____ the same word again and again.', 'repeating', 'repeated', 'to repeat', 'repeat it', 'A', '宾语 someone 主动重复、进行中 → repeating。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'She kept the difficult question ____ until she found a better answer.', 'asking', 'unanswered', 'to answer', 'answer', 'B', '宾语 question 被''未作答''、被动 → 过去分词 unanswered。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'From the stage, I noticed my parents ____ at me with pride.', 'smiled', 'to smile', 'smiling', 'smile', 'C', '宾语 parents 主动微笑、进行中 → smiling。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'He wanted the whole report ____ before the meeting started.', 'finishing', 'to finish', 'finish', 'finished', 'D', '宾语 report 被完成、被动 → finished。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'I could feel the cold wind ____ against my face as I ran.', 'blowing', 'blown', 'to blow', 'blow', 'A', '宾语 wind 主动吹、进行中 → blowing。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'She had her old photos ____ and put them in a new album.', 'printing', 'printed', 'to print', 'print', 'B', '宾语 photos 被打印、被动 → printed。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'We saw the marathon runner ____ towards the finish line at last.', 'rushed', 'to rush', 'rushing', 'rush there', 'C', '宾语 runner 主动冲刺、进行中 → rushing。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'He kept the office door ____ so that no one would disturb him.', 'shutting', 'to shut', 'shut it', 'shut', 'D', '宾语 door 被关、被动状态 → 过去分词 shut。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'At dawn I found my grandfather already ____ in the garden.', 'working', 'worked', 'to work', 'work', 'A', '宾语 grandfather 主动劳作、进行中 → working。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'She wanted the difficult words ____ on the board for everyone to see.', 'writing', 'written', 'to write', 'write', 'B', '宾语 words 被写、被动 → written。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'We could hear the rain ____ heavily on the roof all night.', 'fallen', 'to fall', 'falling', 'fall down', 'C', '宾语 rain 主动落下、进行中 → falling。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'He had the broken microphone ____ just before his thank-you speech.', 'fixing', 'to fix', 'fix', 'fixed', 'D', '宾语 microphone 被修好、被动 → fixed。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'I watched the little boy ____ on the wall with a piece of chalk.', 'drawing', 'drawn', 'to draw', 'draw on', 'A', '宾语 boy 主动画、进行中 → drawing。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'She got her main points ____ on cue cards before the talk.', 'noting', 'noted', 'to note', 'note', 'B', '宾语 points 被记下、被动 → noted。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'Late at night, he could hear his own heart still ____ with excitement.', 'beaten', 'to beat', 'beating', 'beat fast', 'C', '宾语 heart 主动跳动、进行中 → beating。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1' AND code='s3u1.03'), 'After years of effort, she finally saw her dream ____ true.', 'coming', 'comes', 'to come', 'come', 'D', 'see sth come true 为感官动词后接动词原形的固定用法,强调''梦想实现''这一完整过程 → come。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='sufe' AND volume='required3' AND unit='U1';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Stay Hungry, Stay Foolish', 'In 2005, Steve Jobs gave a famous talk to graduating students at a university. In it he shared three short stories from his own life. He told the young people that their time was limited, so they should not waste it living the way someone else expected. He had once been fired from the very company he started, yet he never stopped loving what he did. Slowly it dawned on him that the only way forward was to start over, and years later that choice paid off. He had also faced a serious illness, which taught him to live each day fully. At the end of his talk, Jobs repeated four words he had read long ago on the back cover of an old magazine: "Stay hungry. Stay foolish." To him, these words meant that a person should always keep learning and never become too proud to try new things.', '记叙·乔布斯的演讲', 150, '[{"q":"Why did Jobs tell the students not to waste their time?","answer":"A","options":["Because the time each person has is short.","Because school rules required it.","Because he disliked young people.","Because money is hard to earn."],"explanation":"原文 ''their time was limited'' 的转述。"},{"q":"How did Jobs react after being fired by his own company?","answer":"B","options":["He gave up working forever.","He kept his love for his work and began again.","He moved to another country.","He blamed all his friends."],"explanation":"原文 ''never stopped loving what he did… start over'' 的转述。"},{"q":"What did Jobs mean by \"Stay hungry. Stay foolish\"?","answer":"A","options":["People should keep learning and stay open to new things.","People should eat very little.","People should stop studying after school.","People should always feel proud of themselves."],"explanation":"末句对这句话含义的概括转述。"}]'::jsonb, '[{"word":"limited","cn":"有限的"},{"word":"dawn on","cn":"使开始明白"},{"word":"start over","cn":"重新开始"}]'::jsonb, 2, 'required3', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'A Fighter Against Malaria', 'In 2015, Tu Youyou became the first scientist from China to win the Nobel Prize in medicine. Years earlier, she had been asked to look for a new way to treat a widespread disease in nature. She and her team examined hundreds of old medical books and talked with many experienced doctors to gather useful ideas. At last they found a hint in a very old book, which said that a certain plant could help patients. After much testing, they took from the plant a substance that could fight the illness. The early results were not conclusive, so to speed things up Tu decided to try the substance on herself first. It proved safe, and the discovery later saved millions of lives across Asia and Africa. Though many people praised her, Tu remained modest. She often said that her training and the help of her team mattered most, but it was her passionate commitment that made the long struggle worthwhile.', '说明·屠呦呦的探索', 160, '[{"q":"How did Tu''s team look for clues to treat the disease?","answer":"B","options":["By guessing without any reading.","By studying old books and asking experienced doctors.","By buying medicine from abroad.","By waiting for the disease to disappear."],"explanation":"原文 ''examined hundreds of old medical books and talked with many experienced doctors'' 的转述。"},{"q":"Why did Tu test the substance on herself?","answer":"C","options":["Because no one else worked with her.","Because her team forced her to.","Because she wanted to move faster while the findings remained uncertain.","Because she enjoyed taking risks for fun."],"explanation":"原文 ''results were not conclusive, so to speed things up… on herself'' 的转述。"},{"q":"What does the passage say about Tu''s character?","answer":"D","options":["She was proud and worked alone.","She cared only about the prize.","She gave up after early failures.","She stayed humble and praised her team."],"explanation":"原文 ''Tu remained modest… the help of her team mattered most'' 的转述。"}]'::jsonb, '[{"word":"widespread","cn":"普遍的"},{"word":"conclusive","cn":"确凿的"},{"word":"commitment","cn":"投入"}]'::jsonb, 2, 'required3', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'From Carpenter to Master', 'Qi Baishi began life as a village carpenter, but he ended it as one of China''s greatest painters. He reached the top not by talent alone, but by joining that talent with years of patient work. In 1953 his country honoured him with a special title. Among all his works, his paintings of shrimps are the best loved. At first he simply copied old models, but later he created his own style by using different shades of black ink so that each shrimp looked almost alive. His art also went beyond water creatures. He painted flowers that stood for good fortune and vegetables that pointed to a rich harvest, and people loved these works because they reminded them of their home villages. In his later years he often painted a dove, which was symbolic of his deep wish for peace in the world.', '记叙·齐白石的艺术之路', 143, '[{"q":"What helped Qi Baishi become a great painter?","answer":"A","options":["His talent together with long, patient effort.","Only his natural gift, with no practice.","The help of foreign teachers.","Luck and rich friends."],"explanation":"原文 ''not by talent alone, but by joining that talent with years of patient work'' 的转述。"},{"q":"How did Qi make his shrimp paintings look real?","answer":"B","options":["By copying photographs exactly.","By using black ink of different darkness.","By painting them in bright colours.","By drawing them very large."],"explanation":"原文 ''different shades of black ink so that each shrimp looked almost alive'' 的转述。"},{"q":"Why did people love Qi''s flowers and vegetables?","answer":"C","options":["Because they were cheap to buy.","Because they were painted in gold.","Because they reminded people of their home villages.","Because they were very modern."],"explanation":"原文 ''reminded them of their home villages'' 的转述。"}]'::jsonb, '[{"word":"shade","cn":"(颜色)浓淡"},{"word":"harvest","cn":"收获"},{"word":"symbolic","cn":"象征的"}]'::jsonb, 2, 'required3', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'What Really Predicts Success', 'A psychologist once studied very different groups of people to learn why some succeed and others do not. She looked at students, soldiers in training, and salespeople, asking the same question each time: who would keep going and who would give up. To her surprise, the answer was not talent, good looks, or even a high test score. The strongest sign of success was something she called grit. A person with grit has great passion and the will to keep working towards a far-off goal for years, not just for weeks. Such a person treats life less like a short race and more like a long marathon. They imagine their future clearly and then work hard, day after day, to make that future real. Her message was simple but powerful: when we want to do something difficult and worthwhile, the habit of never quitting matters more than any single gift we are born with.', '议论·毅力与成功', 154, '[{"q":"What did the psychologist find was the strongest sign of success?","answer":"D","options":["Natural talent above all.","A high test score.","Good looks and luck.","Grit, the steady will to pursue a distant goal over many years."],"explanation":"原文 ''The strongest sign of success was something she called grit'' 的转述。"},{"q":"How does a person with grit treat life?","answer":"A","options":["Like a long marathon rather than a short race.","Like a quick and easy game.","Like a holiday with no goals.","Like a single lucky day."],"explanation":"原文 ''less like a short race and more like a long marathon'' 的转述。"},{"q":"What is the psychologist''s main message?","answer":"B","options":["Talent decides everything.","Refusing to give up counts for more than any inborn gift.","Tests are the best way to judge people.","Success comes only to the lucky few."],"explanation":"末句 ''the habit of never quitting matters more than any single gift'' 的转述。"}]'::jsonb, '[{"word":"predictor","cn":"预示因素"},{"word":"tough","cn":"艰难的"},{"word":"perseverance","cn":"毅力"}]'::jsonb, 2, 'required3', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'A Lucky Discovery', 'Alexander Fleming was one of the most important scientists of his time. He is best remembered for finding a substance that could kill harmful germs. The story began almost by accident. One day, after coming back from a short holiday, he noticed that something strange had grown in a dish he had left behind in his lab. Around it, the germs had been cleared away. A careless person might have washed the dish and thought no more of it, but Fleming kept it and examined the strange growth with great care. He realised that it produced something able to stop germs from spreading. Years of further work by him and other scientists turned this lucky moment into a powerful medicine. Since then it has saved a huge number of lives. Fleming''s story shows that success often depends not only on luck, but on a curious mind ready to notice what others would simply throw away.', '说明·弗莱明与青霉素', 155, '[{"q":"What is Fleming best remembered for?","answer":"C","options":["Building a large hospital.","Writing a famous book of poems.","Finding a substance that kills harmful germs.","Teaching at many universities."],"explanation":"原文 ''finding a substance that could kill harmful germs'' 的转述。"},{"q":"What did Fleming do that a careless person might not have done?","answer":"D","options":["He threw the dish away at once.","He stopped doing science.","He hid his discovery from everyone.","He kept the dish and studied the strange growth carefully."],"explanation":"原文 ''kept it and examined the strange growth with great care'' 的转述。"},{"q":"What lesson does Fleming''s story teach?","answer":"A","options":["A curious mind that notices small things matters.","Luck alone brings success.","Science is a waste of time.","Holidays should never be taken."],"explanation":"末句 ''a curious mind ready to notice what others would simply throw away'' 的转述。"}]'::jsonb, '[{"word":"examine","cn":"检查"},{"word":"moment","cn":"时刻"},{"word":"further","cn":"进一步的"}]'::jsonb, 2, 'required3', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'My Own Secret to Success', 'Last term I was asked to give a short talk in front of the whole class, and the very thought of it filled me with fear. I have always been shy, and standing before so many faces felt like the hardest thing in the world. Instead of running away from the task, I decided to face it step by step. First, I wrote my main points on small cards so that I would not forget anything. Then I practised the talk again and again at home, until the words felt natural on my tongue. Just before I began, I breathed deeply several times to calm my beating heart. To my surprise, the talk went far better than I had feared, and my classmates clapped warmly at the end. Looking back, I am proud that a little daily effort helped me overcome my fear. Now I believe that real success is not about having no fear, but about acting in spite of it.', '记叙·一名中学生的成功秘诀', 162, '[{"q":"How did the writer prepare for the talk?","answer":"B","options":["By asking a friend to speak instead.","By writing key points on cards and practising many times.","By reading the talk for the first time on the day.","By doing nothing at all."],"explanation":"原文 ''wrote my main points on small cards… practised the talk again and again'' 的转述。"},{"q":"What did the writer do just before starting?","answer":"C","options":["Ran out of the classroom.","Shouted at the class.","Breathed deeply to calm down.","Threw away the cards."],"explanation":"原文 ''breathed deeply several times to calm my beating heart'' 的转述。"},{"q":"What does the writer now believe about success?","answer":"D","options":["Successful people never feel afraid.","Success means avoiding all hard tasks.","Success depends only on luck.","Success is acting even when you still feel afraid."],"explanation":"末句 ''not about having no fear, but about acting in spite of it'' 的转述。"}]'::jsonb, '[{"word":"overcome","cn":"克服"},{"word":"reflect","cn":"反思"},{"word":"achievement","cn":"成就"}]'::jsonb, 2, 'required3', 'U1', 'sufe');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='sufe' AND volume='required3' AND unit='U1';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U1', 'Learning to Ride', 'When I was eight, my father tried to teach me to ride a bike, but I was afraid of (1)____. Every time the bike moved, my heart began to (2)____ fast, and I wanted to give up. My father told me that the only way to (3)____ was to keep trying. So each evening after dinner I (4)____ in the small yard behind our house. At first I fell again and again, and my knees were always (5)____. But little by little I learned to keep my balance (6)____. One warm evening, I suddenly felt the bike moving (7)____ under me, and I did not fall. My father stood there, (8)____ at me with pride. That moment taught me an important (9)____: with enough patience, even a hard skill can be learned. Now, whenever something seems too difficult, I remember the day I finally (10)____ my fear of the bike.', 150, 2, '[{"q":"1","answer":"A","options":["falling","eating","reading","singing"],"explanation":"afraid of falling 害怕摔倒。"},{"q":"2","answer":"B","options":["sell","beat","leave","sleep"],"explanation":"heart began to beat fast 心跳加快。"},{"q":"3","answer":"C","options":["forget","lose","succeed","waste"],"explanation":"the only way to succeed 成功之道。"},{"q":"4","answer":"D","options":["slept","shouted","cried","practised"],"explanation":"I practised 我练习。"},{"q":"5","answer":"A","options":["hurt","clean","empty","quiet"],"explanation":"knees were hurt 膝盖受伤。"},{"q":"6","answer":"B","options":["worse","better","lower","louder"],"explanation":"keep my balance better 平衡得更好。"},{"q":"7","answer":"C","options":["sadly","angrily","smoothly","loudly"],"explanation":"moving smoothly 平稳地前行。"},{"q":"8","answer":"D","options":["crying","shouting","sleeping","smiling"],"explanation":"smiling at me 朝我微笑。"},{"q":"9","answer":"A","options":["lesson","price","noise","ticket"],"explanation":"an important lesson 重要的一课。"},{"q":"10","answer":"B","options":["forgot","overcame","lost","sold"],"explanation":"overcame my fear 克服恐惧。"}]'::jsonb, 1, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U1', 'After the First Failure', 'My first science project was a complete (1)____. I had spent weeks on it, yet on the day of the show my model simply would not (2)____. I felt so disappointed that I almost decided to (3)____ science for good. That night, my mother sat with me and said that every great scientist had (4)____ many times before getting things right. Her words slowly (5)____ on me, and I made up my mind to (6)____ over. This time I planned my work more (7)____ and asked my teacher for advice. When the next show came, my model worked, and the judges were (8)____ with it. I learned that one failure is not the end; it is only a (9)____ to do better. Looking back, I am glad I did not let that early failure (10)____ me from trying again.', 139, 2, '[{"q":"1","answer":"C","options":["holiday","garden","failure","song"],"explanation":"a complete failure 彻底的失败。"},{"q":"2","answer":"D","options":["sleep","sing","eat","work"],"explanation":"would not work 不运转。"},{"q":"3","answer":"A","options":["quit","enjoy","buy","open"],"explanation":"quit science 放弃科学。"},{"q":"4","answer":"B","options":["won","failed","slept","danced"],"explanation":"had failed many times 失败过许多次。"},{"q":"5","answer":"C","options":["sold","lost","dawned","broke"],"explanation":"dawned on me 让我开始明白。"},{"q":"6","answer":"D","options":["give","look","turn","start"],"explanation":"start over 重新开始。"},{"q":"7","answer":"A","options":["carefully","sadly","loudly","lazily"],"explanation":"more carefully 更仔细地。"},{"q":"8","answer":"B","options":["angry","pleased","bored","afraid"],"explanation":"pleased with it 对它满意。"},{"q":"9","answer":"C","options":["price","noise","chance","ticket"],"explanation":"a chance to do better 做得更好的机会。"},{"q":"10","answer":"D","options":["help","save","teach","stop"],"explanation":"stop me from trying 阻止我尝试。"}]'::jsonb, 2, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U1', 'The Power of a Team', 'People often think that great success is the work of one (1)____ person, but the truth is usually different. Behind almost every famous achievement there is a (2)____ of people working together. When one member feels tired, the others keep him (3)____ with kind words. When a hard problem appears, many minds can (4)____ ideas and find an answer faster than one mind alone. A good leader (5)____ each person''s strengths and gives everyone a part to play. That is why even a (6)____ scientist often gives the credit to her whole team instead of (7)____ it for herself. A team that trusts each other can stay (8)____ through difficult times. So if you ever feel that a goal is too (9)____ for you alone, remember that asking others for help is not weakness. Together, ordinary people can (10)____ extraordinary things.', 141, 2, '[{"q":"1","answer":"A","options":["single","empty","broken","quiet"],"explanation":"one single person 单独一个人。"},{"q":"2","answer":"B","options":["price","team","noise","garden"],"explanation":"a team of people 一群人/团队。"},{"q":"3","answer":"C","options":["sold","lost","going","thrown"],"explanation":"keep him going 让他坚持下去。"},{"q":"4","answer":"D","options":["break","sell","lose","gather"],"explanation":"gather ideas 汇集想法。"},{"q":"5","answer":"A","options":["knows","hides","sells","loses"],"explanation":"knows each person''s strengths 了解长处。"},{"q":"6","answer":"B","options":["lazy","modest","rude","careless"],"explanation":"a modest scientist 谦逊的科学家。"},{"q":"7","answer":"C","options":["sleeping","buying","keeping","leaving"],"explanation":"keeping it for herself 把功劳留给自己。"},{"q":"8","answer":"D","options":["angry","afraid","asleep","strong"],"explanation":"stay strong 保持坚强。"},{"q":"9","answer":"A","options":["big","small","cheap","near"],"explanation":"too big for you alone 对你独自太艰巨。"},{"q":"10","answer":"B","options":["forget","achieve","lose","waste"],"explanation":"achieve extraordinary things 取得非凡成就。"}]'::jsonb, 3, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U1', 'Before the Big Speech', 'The night before my first English speech, I could hardly (1)____. I kept imagining the audience (2)____ at me, and my hands felt cold. My teacher had told me that even great speakers feel (3)____ before they begin. To calm myself, I wrote my key points on small (4)____ so that I would not forget them. Then I (5)____ the speech aloud in front of a mirror until the words felt (6)____ on my tongue. When the morning came, I breathed deeply several times to keep my heart from (7)____ too fast. As I started to speak, I was surprised to find the room quietly (8)____ to me. My voice grew (9)____ with every sentence. When I finished, the warm clapping told me that all my (10)____ had been worthwhile.', 130, 2, '[{"q":"1","answer":"C","options":["sell","fly","sleep","swim"],"explanation":"could hardly sleep 几乎睡不着。"},{"q":"2","answer":"D","options":["sold","lost","broken","staring"],"explanation":"imagining the audience staring 想象观众盯着。"},{"q":"3","answer":"A","options":["nervous","happy","lazy","sleepy"],"explanation":"feel nervous 感到紧张。"},{"q":"4","answer":"B","options":["prices","cards","noises","songs"],"explanation":"on small cards 在小卡片上。"},{"q":"5","answer":"C","options":["slept","ate","practised","lost"],"explanation":"I practised the speech 我练习演讲。"},{"q":"6","answer":"D","options":["wrong","empty","late","natural"],"explanation":"felt natural 感觉自然。"},{"q":"7","answer":"A","options":["beating","sleeping","selling","leaving"],"explanation":"from beating too fast 跳得太快。"},{"q":"8","answer":"B","options":["shouting","listening","crying","sleeping"],"explanation":"listening to me 在听我讲。"},{"q":"9","answer":"C","options":["weaker","lower","stronger","quieter"],"explanation":"grew stronger 越来越有力。"},{"q":"10","answer":"D","options":["sleep","money","noise","effort"],"explanation":"all my effort 我所有的努力。"}]'::jsonb, 4, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U1', 'Turning a Hobby into a Skill', 'When I was young, drawing was just a (1)____ I did for fun after school. My early pictures were rough, and I almost (2)____ up many times. But my grandfather told me that real skill comes from years of patient (3)____, not from talent alone. So I kept drawing every day, even when I was (4)____. Slowly I learned to use different (5)____ of colour to make my pictures look alive. I (6)____ my work on the styles of painters I loved, and then little by little I found my own way. After a few years, my art teacher asked to (7)____ my best pictures in the school hall. Seeing my work on (8)____ filled me with pride. That experience taught me a simple (9)____: a hobby can grow into a real ability if you are willing to (10)____ time and effort into it.', 144, 2, '[{"q":"1","answer":"A","options":["hobby","price","noise","ticket"],"explanation":"a hobby I did for fun 一项爱好。"},{"q":"2","answer":"B","options":["slept","gave","sold","ate"],"explanation":"gave up 放弃。"},{"q":"3","answer":"C","options":["sleep","money","work","noise"],"explanation":"patient work 耐心的努力。"},{"q":"4","answer":"D","options":["rich","tall","late","tired"],"explanation":"even when I was tired 即使疲倦。"},{"q":"5","answer":"A","options":["shades","prices","noises","tickets"],"explanation":"different shades of colour 不同的色度。"},{"q":"6","answer":"B","options":["sold","based","lost","threw"],"explanation":"based my work on 以……为基础。"},{"q":"7","answer":"C","options":["forget","lose","display","sell"],"explanation":"to display my pictures 展出我的画。"},{"q":"8","answer":"D","options":["sale","fire","sleep","display"],"explanation":"on display 在展出。"},{"q":"9","answer":"A","options":["lesson","price","noise","ticket"],"explanation":"a simple lesson 一个简单的道理。"},{"q":"10","answer":"B","options":["forget","put","waste","lose"],"explanation":"put time and effort into 投入时间和精力。"}]'::jsonb, 5, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required3', 'U1', 'Helping Others Is Success Too', 'Many people think that success only (1)____ being famous or making a lot of money. But my aunt, a village nurse, taught me a different (2)____. For thirty years she has cared for sick people in a poor area, where good doctors are (3)____. She is not rich, and very few people outside the village know her (4)____. Yet every patient she has (5)____ remembers her with thanks. She often says that the happiest (6)____ in her career is seeing a sick child get well again. To her, a life spent (7)____ others is a truly successful one. She is (8)____ and never talks much about what she has done. Watching her, I have come to (9)____ that real success is not always about money or fame. Sometimes it is simply about making other people''s lives a little (10)____.', 139, 2, '[{"q":"1","answer":"C","options":["sells","loses","means","forgets"],"explanation":"success only means 成功仅意味着。"},{"q":"2","answer":"D","options":["price","noise","ticket","lesson"],"explanation":"a different lesson 不同的道理。"},{"q":"3","answer":"A","options":["few","many","cheap","loud"],"explanation":"good doctors are few 好医生很少。"},{"q":"4","answer":"B","options":["price","name","song","game"],"explanation":"know her name 知道她的名字。"},{"q":"5","answer":"C","options":["sold","lost","helped","thrown"],"explanation":"every patient she has helped 她帮助过的每个病人。"},{"q":"6","answer":"D","options":["price","noise","ticket","moment"],"explanation":"the happiest moment 最快乐的时刻。"},{"q":"7","answer":"A","options":["helping","selling","losing","leaving"],"explanation":"spent helping others 用来帮助他人。"},{"q":"8","answer":"B","options":["rude","modest","lazy","careless"],"explanation":"she is modest 她很谦逊。"},{"q":"9","answer":"C","options":["forget","lose","realise","sell"],"explanation":"come to realise 渐渐明白。"},{"q":"10","answer":"D","options":["worse","darker","shorter","better"],"explanation":"a little better 好一点。"}]'::jsonb, 6, 'sufe');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='required3' AND unit='U1';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·对话 What Does Success Mean?', '上外版必修第三册 U1 · dialogue', 3, 'Lucy: Tom, do you think a person is successful only if they are rich and famous?
Tom: Not really. I think success means doing something you love and doing it well.
Lucy: So money is not the most important thing to you?
Tom: No. For me, a happy family and a job I enjoy matter more than money.
Lucy: That makes sense. My uncle is a village nurse, not rich at all, but he feels successful.
Tom: Exactly. He helps others every day, and that is a kind of success too.
Lucy: I agree. Maybe success is different for each person.
Tom: Yes, and the most important thing is to find your own road to it.', 'Lucy 问 Tom 是否只有又富又有名才算成功;Tom 认为成功是做自己热爱并做得好的事;对他来说幸福的家庭和喜欢的工作比金钱更重要;Lucy 提到当乡村护士的叔叔虽不富有却觉得成功;两人一致认为成功因人而异,最重要的是找到自己通向成功的路。', 'uk_female', '[{"q":"What does Tom think success mainly means?","type":"choice","answer":"A","options":["Doing something you love and doing it well.","Being rich and famous only.","Owning a big house.","Winning every prize."]},{"q":"What matters more to Tom than money?","type":"choice","answer":"B","options":["A bigger car.","A happy family and a job he enjoys.","Becoming famous.","Travelling abroad."]},{"q":"Why does Lucy mention her uncle?","type":"choice","answer":"A","options":["Because he feels successful by helping others, though not rich.","Because he is very rich.","Because he is famous on TV.","Because he wants a new job."]},{"q":"What do Lucy and Tom finally agree on?","type":"choice","answer":"B","options":["Only money brings success.","Success can be different for each person.","Success is the same for everyone.","Nobody can be successful."]},{"q":"What does Tom say is the most important thing?","type":"choice","answer":"C","options":["To copy other people exactly.","To give up when it is hard.","To find your own road to success.","To care only about fame."]}]'::jsonb, '[]'::jsonb, 'long', 'required3', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·短文 The Power of Grit', '上外版必修第三册 U1 · passage', 2, 'Many people believe that talent is the key to success.
But studies show that something called grit matters even more.
A person with grit keeps working towards a goal for years, not just for days.
They treat life like a long marathon rather than a short race.
In the end, the habit of never giving up often decides who succeeds.', '许多人认为天赋是成功的关键;但研究表明一种叫''毅力''的品质更重要;有毅力的人会朝目标坚持数年,而非几天;他们把人生当作长跑而非短跑;最终,永不放弃的习惯常常决定谁能成功。', 'uk_female', '[{"q":"What do many people believe is the key to success?","type":"choice","answer":"D","options":["Money.","Luck.","Looks.","Talent."]},{"q":"According to studies, what matters even more?","type":"choice","answer":"A","options":["Grit.","A high score.","Good clothes.","A famous teacher."]},{"q":"How long does a person with grit keep working towards a goal?","type":"choice","answer":"B","options":["For a few minutes.","For years.","For one day.","Never."]},{"q":"What does a person with grit treat life like?","type":"choice","answer":"C","options":["A short race.","A quick game.","A long marathon.","A lazy holiday."]},{"q":"What often decides who succeeds in the end?","type":"choice","answer":"D","options":["Being born rich.","Avoiding all hard work.","Having many friends.","The habit of never giving up."]}]'::jsonb, '[]'::jsonb, 'short', 'required3', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·对话 Cheer Up, You Can Do It', '上外版必修第三册 U1 · dialogue', 3, 'Mia: I''m so nervous about the maths competition tomorrow. I might fail.
Jack: Don''t worry too much. You have practised hard for weeks.
Mia: But what if I forget everything in front of the judges?
Jack: Take a few deep breaths before you start. That always calms me down.
Mia: Do you really think I have a chance?
Jack: Of course. Even great people felt afraid before big moments.
Mia: Thanks, Jack. You always know how to cheer me up.
Jack: Just do your best. Whatever happens, you should be proud of trying.', 'Mia 为明天的数学竞赛紧张,担心会失败;Jack 安慰说她已苦练数周;Mia 怕在评委面前忘光;Jack 建议开始前深呼吸几次来让自己镇定;并说连了不起的人在重要时刻前也会害怕;Mia 感谢 Jack 让她振作;Jack 让她尽力,无论结果如何都该为尝试而自豪。', 'uk_female', '[{"q":"Why is Mia nervous?","type":"choice","answer":"A","options":["Because of a maths competition tomorrow.","Because she lost her book.","Because she is ill.","Because she missed the bus."]},{"q":"What does Jack remind Mia she has done?","type":"choice","answer":"B","options":["She has slept all week.","She has practised hard for weeks.","She has skipped her lessons.","She has given up."]},{"q":"What does Jack suggest doing before she starts?","type":"choice","answer":"C","options":["Shouting loudly.","Running away.","Taking a few deep breaths.","Eating a big meal."]},{"q":"What does Jack say about great people?","type":"choice","answer":"D","options":["They never work hard.","They are always calm.","They never compete.","They also felt afraid before big moments."]},{"q":"What does Jack tell Mia at the end?","type":"choice","answer":"A","options":["To do her best and be proud of trying.","To skip the competition.","To copy others'' answers.","To stop studying maths."]}]'::jsonb, '[]'::jsonb, 'long', 'required3', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·短文 Never Give Up', '上外版必修第三册 U1 · passage', 2, 'Almost every great achievement comes after many failures.
The first try is often the hardest, and many people stop too soon.
But those who keep going slowly learn from their mistakes.
Each failure teaches them something new and brings them closer to the goal.
So when you fail, do not lose heart; instead, start over and try again.', '几乎每一项伟大成就都来自多次失败;第一次尝试往往最难,许多人太早放弃;但坚持下去的人会慢慢从错误中学习;每一次失败都教会他们新东西,使他们更接近目标;所以当你失败时,别灰心,要重新开始再试一次。', 'uk_female', '[{"q":"What does almost every great achievement come after?","type":"choice","answer":"B","options":["A single easy day.","Many failures.","A lot of luck only.","No effort at all."]},{"q":"What do many people do too soon?","type":"choice","answer":"C","options":["Win the prize.","Become famous.","Stop trying.","Help others."]},{"q":"What do those who keep going learn from?","type":"choice","answer":"D","options":["Their money.","Their friends.","Their holidays.","Their mistakes."]},{"q":"What does each failure do, according to the passage?","type":"choice","answer":"A","options":["It teaches something new and brings you closer to the goal.","It makes the goal disappear.","It wastes all your time.","It stops you forever."]},{"q":"What should you do when you fail?","type":"choice","answer":"B","options":["Lose heart and quit.","Start over and try again.","Blame other people.","Forget your goal."]}]'::jsonb, '[]'::jsonb, 'short', 'required3', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·对话 Tips for a Good Speech', '上外版必修第三册 U1 · dialogue', 3, 'Ben: Anna, you always give such great talks. How do you do it?
Anna: Thanks! First, I write my main points on small cards.
Ben: Just the main points, not every word?
Anna: Right. If you read every word, the talk sounds boring.
Ben: What else helps you?
Anna: I practise out loud many times, and I pause at full stops and commas.
Ben: That''s clever. Anything for the nerves?
Anna: Yes. Breathe slowly before you start, and speak to one friendly face at a time.', 'Ben 问 Anna 演讲为何总那么棒;Anna 说先把要点写在小卡片上;只写要点而非逐字;因为逐字读会很无聊;还会大声练习多次,并在句号逗号处停顿;对付紧张则是开始前慢慢呼吸,每次只对一张友善的面孔讲。', 'uk_female', '[{"q":"What does Anna write on her cards?","type":"choice","answer":"C","options":["Every single word.","Other people''s names.","Her main points.","Nothing at all."]},{"q":"Why shouldn''t you read every word?","type":"choice","answer":"D","options":["It takes no time.","It is against the rules.","Cards are too small.","The talk sounds boring."]},{"q":"Where does Anna pause when she speaks?","type":"choice","answer":"A","options":["At full stops and commas.","In the middle of words.","Never at all.","Only at the very end."]},{"q":"How does Anna deal with nerves?","type":"choice","answer":"B","options":["She shouts loudly.","She breathes slowly before starting.","She runs away.","She skips the talk."]},{"q":"Who does Anna suggest speaking to at a time?","type":"choice","answer":"C","options":["The whole crowd at once with eyes shut.","No one in the room.","One friendly face at a time.","Only the judges."]}]'::jsonb, '[]'::jsonb, 'long', 'required3', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·短文 A Little Every Day', '上外版必修第三册 U1 · passage', 2, 'You do not have to do something huge to move towards success.
A small step taken every day adds up over time.
If you learn five new words a day, that is almost two thousand in a year.
The secret is not speed, but doing a little, again and again.
Be patient, keep going, and one day you will be surprised how far you have come.', '你不必做什么惊天动地的大事才能走向成功;每天迈出一小步,日积月累会很可观;如果每天学五个新词,一年就近两千个;秘诀不在快,而在一点一点反复地做;要有耐心,坚持下去,有一天你会惊讶自己走了这么远。', 'uk_female', '[{"q":"What does the passage say you do NOT have to do?","type":"choice","answer":"D","options":["Sleep every night.","Eat breakfast.","Talk to friends.","Do something huge to move towards success."]},{"q":"What adds up over time?","type":"choice","answer":"A","options":["A small step taken every day.","A long holiday.","A single big jump.","A lucky win."]},{"q":"If you learn five new words a day, how many is that in a year?","type":"choice","answer":"B","options":["About fifty.","Almost two thousand.","About five hundred.","Exactly ten."]},{"q":"What is the secret, according to the passage?","type":"choice","answer":"C","options":["Doing everything in one night.","Working only when you feel like it.","Doing a little, again and again.","Being the fastest of all."]},{"q":"What will happen if you keep going patiently?","type":"choice","answer":"D","options":["You will quickly give up.","Nothing will change at all.","You will forget your goal.","One day you will be surprised how far you have come."]}]'::jsonb, '[]'::jsonb, 'short', 'required3', 'U1', 'sufe');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='required3' AND unit='U1';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (10, 'My Secrets to Success(我的成功秘诀)', 'My Secrets to Success', '班委会要开一次以"我的成功秘诀"为题的班会。请用英语写一段约80–100词的短文,内容包括:① 介绍你曾取得的一项成就(如克服当众讲话的恐惧、学会一项技能等);② 用因果结构说明促成这一成就的三个原因;③ 结尾给同学一句鼓励。注意用 because / one factor is / as a result 等表达因果关系。', 'The class committee is holding a meeting on "My Secrets to Success". Write a passage of about 80–100 words including: 1) one achievement you have made (e.g. overcoming a fear, learning a skill); 2) three reasons that led to it, using the cause-effect pattern; 3) one sentence of encouragement for your classmates. Use phrases such as because, one factor is, and as a result.', '["介绍成就(One thing I am proud of is …)","用因果结构说明三个原因(One factor is … Another is … because …)","用结果连接词收束(As a result, I have …)","结尾鼓励同学(If you keep trying, you can succeed too!)"]'::jsonb, 70, 100, 'One achievement I am really proud of is overcoming my fear of public speaking. There are several factors behind this success. The first is careful preparation: I wrote my main points on small cards so that I would not forget anything. The second is practice. I practised the talk again and again at home until the words felt natural. The third is staying calm, because I breathed deeply several times before I began. As a result, I gave my speech well and my classmates clapped warmly. If you keep trying step by step, you can overcome your fears too!', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["One achievement I am really proud of is overcoming my fear of public speaking.","There are several factors behind this success.","I practised the talk again and again until the words felt natural.","As a result, I gave my speech well and my classmates clapped warmly."]'::jsonb, '[{"wrong":"The first factor is I prepared carefully.","correct":"The first factor is careful preparation.","note":"is 后接名词短语,或用 that 从句(The first factor is that I prepared carefully)。"},{"wrong":"I practised the talk again and again until the words felt naturally.","correct":"I practised the talk again and again until the words felt natural.","note":"feel 是系动词,后接形容词 natural 而非副词。"},{"wrong":"As a result, my classmates clapped warm.","correct":"As a result, my classmates clapped warmly.","note":"修饰动词 clapped 用副词 warmly。"}]'::jsonb, '【成功秘诀(因果结构)】
第1句 介绍成就:One achievement I am proud of is …
第2句 总起:There are several factors behind this success.
第3-5句 原因:The first is … The second is … The third is … because …
第6句 结果+鼓励:As a result, … If you keep trying, you can succeed too!', 2, 'required3', 'U1', 'sufe');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='required3' AND unit='U1';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (10, 'required3', 'U1', '{"title":"-ing / -ed 形式作补语速查","intro":"分词作补语,用来补充说明宾语(或主语)的状态。判断口诀:看宾语和动作的关系——宾语主动发出、动作进行中 → 用 -ing;宾语承受动作、被动或已完成 → 用 -ed。","table":{"headers":["分词形式","用法 / 例句"],"rows":[["-ing(主动·进行)","感官/使役 + 宾语 + doing:I saw him crossing the road. / keep me going"],["-ed(被动·完成)","have/get/make/keep + 宾语 + done:I had my hair cut. / get the problem solved"],["with 复合结构","with + 宾语 + 分词:with the door locked / with the lights shining"],["辨析关键","宾语自己做 → -ing;宾语被别人做 → -ed(I saw the work done)"]]},"specialRules":[{"rule":"感官动词(see/hear/watch/feel/notice)+ 宾语 + doing,强调动作正在进行","mark":"I heard her singing(她正在唱)"},{"rule":"have/get sth done = 让某事被(别人)做,宾语是动作的承受者","mark":"have my hair cut / get the car repaired"},{"rule":"make oneself understood / heard 是固定搭配,用过去分词","mark":"make yourself understood(让别人听懂你)"},{"rule":"see/hear sb do(原形)强调动作的全过程或已完成,doing 强调进行中","mark":"saw her dream come true(全过程)vs saw him crossing(进行中)"}],"why":["分词没有''人称、时态''的变化,只表达''主动进行(-ing)''还是''被动完成(-ed)''。所以选哪个,关键看它前面的宾语是动作的发出者还是承受者。"],"gaokaoPoints":["have/get/keep/make/find/leave + 宾语 + 分词:由宾语主被动选 -ing 或 -ed,语法填空与单选高频。","感官动词 + 宾语 + doing/done/do 的区别(进行中用 doing,被动用 done,全过程用 do)。","with 复合结构作状语:with + n. + 分词,常考主被动判断。"],"examVsReal":[{"exam":"I had my hair cut yesterday.(考试/书面)","real":"I got a haircut yesterday.","note":"考试爱考 have sth done;口语里常用更简单的说法表达同一意思"},{"exam":"with the door locked(考试)","real":"and the door was locked","note":"考试用 with 复合结构;口语里常拆成一个并列分句更自然"}]}'::jsonb, 'sufe');

COMMIT;

-- ===== 自带校验(publisher='sufe') =====
SELECT 'vocab' k, count(*) v, 46 expect FROM public.junior_vocab WHERE publisher='sufe' AND volume='required3' AND unit='U1'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required3' AND unit='U1')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='sufe' AND volume='required3' AND unit='U1'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='sufe' AND volume='required3' AND unit='U1'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='required3' AND unit='U1'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='required3' AND unit='U1'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='required3' AND unit='U1' ORDER BY k;
