-- ============================================================
-- 上外(sufe) 必修一 U3(Travel)灌库(junior_* 表,publisher='sufe' volume='required1' unit='U3' grade=10)。幂等。
-- ★DELETE 全带 publisher='sufe',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 48 =====
DELETE FROM public.junior_vocab WHERE publisher='sufe' AND volume='required1' AND unit='U3';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'masterpiece', 'n.', '/ˈmɑːstəpiːs/', '杰作;代表作', 'In Rome I finally saw the famous masterpieces I had only read about.', '在罗马,我终于看到了那些我此前只在书里读过的著名杰作。', 'Travel', 1, 0, 'senior', 'wordlist', 'required1', 'U3', 'a masterpiece of art', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'sculpture', 'n.', '/ˈskʌlptʃə(r)/', '雕像;雕刻品', 'The museum is full of ancient sculptures made of stone and metal.', '这座博物馆里满是用石头和金属制成的古代雕像。', 'Travel', 2, 0, 'senior', 'wordlist', 'required1', 'U3', 'ancient sculptures', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'ceiling', 'n.', '/ˈsiːlɪŋ/', '天花板;顶棚', 'The painted ceiling of the chapel was the best part of my whole trip.', '教堂那绘满壁画的天花板是我整趟旅行最精彩的部分。', 'Travel', 3, 0, 'senior', 'wordlist', 'required1', 'U3', 'a painted ceiling', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'tear', 'v.', '/teə(r)/', '挣开;拽开;撕裂', 'The view was so beautiful that I could not tear my eyes away from it.', '那景色太美了,我的目光怎么也舍不得移开。', 'Travel', 4, 0, 'senior', 'wordlist', 'required1', 'U3', 'tear away', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'quality', 'n.', '/ˈkwɒləti/', '质量;品质', 'Some food sold to tourists is not very good in quality.', '卖给游客的一些食物质量不太好。', 'Travel', 5, 0, 'senior', 'wordlist', 'required1', 'U3', 'good quality', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'effort', 'n.', '/ˈefət/', '努力;尽力;力气', 'I made an effort to find a restaurant that served local meals.', '我努力找到了一家供应当地餐食的餐馆。', 'Travel', 6, 0, 'senior', 'wordlist', 'required1', 'U3', 'make an effort', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'region', 'n.', '/ˈriːdʒən/', '地区;区域', 'I wanted to taste the popular meals of the region.', '我想品尝这个地区受欢迎的餐食。', 'Travel', 7, 0, 'senior', 'wordlist', 'required1', 'U3', 'the region', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'luxury', 'n.', '/ˈlʌkʃəri/', '奢侈品;奢华', 'The city has many luxury stores as well as cheaper shops.', '这座城市既有许多奢侈品店,也有较便宜的商铺。', 'Travel', 8, 0, 'senior', 'wordlist', 'required1', 'U3', 'luxury stores', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'range', 'n.', '/reɪndʒ/', '范围;区间;一系列', 'I looked for souvenirs that were in my price range.', '我寻找在我价位范围内的纪念品。', 'Travel', 9, 0, 'senior', 'wordlist', 'required1', 'U3', 'in my price range', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'opportunity', 'n.', '/ˌɒpəˈtjuːnəti/', '机会;时机', 'The Christmas market was a perfect opportunity to buy presents.', '那个圣诞集市是个买礼物的绝佳机会。', 'Travel', 10, 0, 'senior', 'wordlist', 'required1', 'U3', 'a perfect opportunity', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'relevant', 'adj.', '/ˈreləvənt/', '紧密相关的;切题的', 'Some lessons may not seem relevant to your travel dreams right now.', '有些课程现在看来也许与你的旅行梦想关系不大。', 'Travel', 11, 0, 'senior', 'wordlist', 'required1', 'U3', 'relevant to', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'analyse', 'v.', '/ˈænəlaɪz/', '分析', 'Study skills help you analyse the world around you before you travel.', '学习技能帮助你在出行前分析周遭的世界。', 'Travel', 12, 0, 'senior', 'wordlist', 'required1', 'U3', 'analyse a problem', '美式拼 analyze;美音 /ˈænəlaɪz/', 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'process', 'v./n.', '/ˈprəʊses/', '处理;加工;过程;进程', 'Planning a trip teaches you to process information quickly.', '规划一次旅行能教你迅速处理信息。', 'Travel', 13, 0, 'senior', 'wordlist', 'required1', 'U3', 'process information', '美音 /ˈprɑːses/', 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'overcome', 'v.', '/ˌəʊvəˈkʌm/', '克服;解决', 'These skills will help you overcome the difficulties that stop you from travelling.', '这些技能会帮你克服那些阻碍你出行的困难。', 'Travel', 14, 0, 'senior', 'wordlist', 'required1', 'U3', 'overcome obstacles', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'practical', 'adj.', '/ˈpræktɪkl/', '切实可行的;实际的', 'Dream big, but stay practical when you make a travel plan.', '做旅行计划时要敢于做大梦,但也要切合实际。', 'Travel', 15, 0, 'senior', 'wordlist', 'required1', 'U3', 'stay practical', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'prevent', 'v.', '/prɪˈvent/', '阻止;阻碍', 'A small setback won''t prevent you from reaching your travel dreams.', '小小的挫折不会阻止你实现旅行的梦想。', 'Travel', 16, 0, 'senior', 'wordlist', 'required1', 'U3', 'prevent from', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'goal', 'n.', '/ɡəʊl/', '目标;目的', 'Travel was a goal that I had wanted to reach for many years.', '旅行是我多年来一直想实现的一个目标。', 'Travel', 17, 0, 'senior', 'wordlist', 'required1', 'U3', 'reach a goal', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'amount', 'n.', '/əˈmaʊnt/', '数量;数额', 'The amount of money your family can spend will shape the trip.', '家里能花的钱数会决定这趟旅行的样子。', 'Travel', 18, 0, 'senior', 'wordlist', 'required1', 'U3', 'the amount of money', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'factor', 'n.', '/ˈfæktə(r)/', '因素;要素', 'Cost is an important factor when you plan where to travel.', '在规划去哪里旅行时,花费是一个重要因素。', 'Travel', 19, 0, 'senior', 'wordlist', 'required1', 'U3', 'an important factor', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'determine', 'v.', '/dɪˈtɜːmɪn/', '决定;影响', 'Your budget will determine whether you visit Europe or stay nearby.', '你的预算将决定你是去欧洲还是待在附近。', 'Travel', 20, 0, 'senior', 'wordlist', 'required1', 'U3', 'determine the experience', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'participate', 'v.', '/pɑːˈtɪsɪpeɪt/', '参加;参与', 'You could participate in a student exchange programme abroad.', '你可以参加一个出国的学生交流项目。', 'Travel', 21, 0, 'senior', 'wordlist', 'required1', 'U3', 'participate in', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'exchange', 'n.', '/ɪksˈtʃeɪndʒ/', '交流;互访;交换', 'A student exchange is a cheaper way to travel and learn.', '学生交流是一种更便宜的旅行兼学习的方式。', 'Travel', 22, 0, 'senior', 'wordlist', 'required1', 'U3', 'a student exchange', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'maintain', 'v.', '/meɪnˈteɪn/', '维持;保持', 'I hope you will maintain your travel dreams in spite of the limits.', '我希望你尽管有种种限制,仍能保持你的旅行梦想。', 'Travel', 23, 0, 'senior', 'wordlist', 'required1', 'U3', 'maintain a dream', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'chart', 'v.', '/tʃɑːt/', '制定(计划);筹划', 'Work hard and chart a course ahead before your journey begins.', '在旅程开始前,努力做事并提前规划好路线。', 'Travel', 24, 0, 'senior', 'wordlist', 'required1', 'U3', 'chart a course', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'ahead', 'adv.', '/əˈhed/', '在前面;提前', 'It is wise to plan ahead so that your trip runs smoothly.', '提前规划是明智之举,这样旅行才能顺利进行。', 'Travel', 25, 0, 'senior', 'wordlist', 'required1', 'U3', 'plan ahead', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'rooted', 'adj.', '/ˈruːtɪd/', '根深蒂固的;扎根的', 'Stay rooted in the practical actions that bring your dream closer.', '扎根于那些让梦想更近一步的实际行动。', 'Travel', 26, 0, 'senior', 'wordlist', 'required1', 'U3', 'rooted in', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'journey', 'n.', '/ˈdʒɜːni/', '旅程;旅行', 'We set off early for the long journey to the mountains.', '我们一大早就出发,踏上去山里的漫长旅程。', 'Travel', 27, 0, 'senior', 'wordlist', 'required1', 'U3', 'a long journey', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'holiday', 'n.', '/ˈhɒlədeɪ/', '假日;假期', 'Eleanor spent a wonderful holiday in Rome last week.', '埃莉诺上周在罗马度过了一个美妙的假期。', 'Travel', 28, 0, 'senior', 'wordlist', 'required1', 'U3', 'a Roman holiday', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'tourist', 'n.', '/ˈtʊərɪst/', '游客;旅游者', 'Every year millions of tourists come to see the ancient ruins.', '每年都有数百万游客前来观看这些古代遗址。', 'Travel', 29, 0, 'senior', 'wordlist', 'required1', 'U3', 'a tourist attraction', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'attraction', 'n.', '/əˈtrækʃn/', '景点;吸引人之处', 'The Bell Tower is one of the city''s most famous attractions.', '钟楼是这座城市最著名的景点之一。', 'Travel', 30, 0, 'senior', 'wordlist', 'required1', 'U3', 'famous attractions', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'destination', 'n.', '/ˌdestɪˈneɪʃn/', '目的地;终点', 'Xi''an is a popular travel destination for foreign visitors.', '西安是外国游客喜爱的旅游目的地。', 'Travel', 31, 0, 'senior', 'wordlist', 'required1', 'U3', 'a travel destination', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'scenery', 'n.', '/ˈsiːnəri/', '风景;景色', 'She prefers a city with beautiful scenery and a long history.', '她偏爱一座既有美丽风景又有悠久历史的城市。', 'Travel', 32, 0, 'senior', 'wordlist', 'required1', 'U3', 'beautiful scenery', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'recommend', 'v.', '/ˌrekəˈmend/', '推荐;建议', 'I would strongly recommend Xi''an for your winter trip.', '我会强烈推荐你冬天去西安旅行。', 'Travel', 33, 0, 'senior', 'wordlist', 'required1', 'U3', 'recommend a city', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'explorer', 'n.', '/ɪkˈsplɔːrə(r)/', '探险家;探索者', 'Xu Xiake was a famous explorer who travelled across China.', '徐霞客是一位走遍中国的著名探险家。', 'Travel', 34, 0, 'senior', 'wordlist', 'required1', 'U3', 'a famous explorer', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'valley', 'n.', '/ˈvæli/', '山谷;溪谷', 'For years he visited mountains, valleys and caves all over China.', '多年来,他游遍了中国各地的高山、深谷和洞穴。', 'Travel', 35, 0, 'senior', 'wordlist', 'required1', 'U3', 'rivers and valleys', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'record', 'v.', '/rɪˈkɔːd/', '记录;记载', 'He recorded his travel experiences in a famous travel book.', '他把自己的旅行经历记录在一本著名的游记里。', 'Travel', 36, 0, 'senior', 'wordlist', 'required1', 'U3', 'record a journey', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'limitation', 'n.', '/ˌlɪmɪˈteɪʃn/', '限制;局限', 'As a teenager, you have some limitations when making travel plans.', '作为青少年,你在制定旅行计划时会有一些限制。', 'Travel', 37, 0, 'senior', 'wordlist', 'required1', 'U3', 'some limitations', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'dream', 'v./n.', '/driːm/', '梦想;做梦;梦', 'Many young people dream of travelling far from home.', '许多年轻人梦想着去远离家乡的地方旅行。', 'Travel', 38, 0, 'senior', 'wordlist', 'required1', 'U3', 'dream of travelling', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'imagine', 'v.', '/ɪˈmædʒɪn/', '想象;设想', 'You can''t imagine how lovely the old city is until you go there.', '不到那里,你无法想象这座古城有多美。', 'Travel', 39, 0, 'senior', 'wordlist', 'required1', 'U3', 'imagine a place', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'decoration', 'n.', '/ˌdekəˈreɪʃn/', '装饰;装饰品', 'The streets were lit with bright Christmas decorations.', '街道上点缀着明亮的圣诞装饰。', 'Travel', 40, 0, 'senior', 'wordlist', 'required1', 'U3', 'Christmas decorations', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'wonder', 'n./v.', '/ˈwʌndə(r)/', '奇迹;惊奇;想知道', 'The huge theatre is one of the greatest wonders ever built.', '那座巨大的剧场是有史以来建成的最伟大的奇迹之一。', 'Travel', 41, 0, 'senior', 'wordlist', 'required1', 'U3', 'a wonder of the world', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'ancient', 'adj.', '/ˈeɪnʃənt/', '古代的;古老的', 'Rome is an ancient city that is full of ruins and history.', '罗马是一座满是遗迹和历史的古老城市。', 'Travel', 42, 0, 'senior', 'wordlist', 'required1', 'U3', 'an ancient city', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'ruin', 'n.', '/ˈruːɪn/', '废墟;遗迹', 'You can hardly believe how old the ruins of the temples are.', '你几乎无法相信这些神庙的遗迹有多古老。', 'Travel', 43, 0, 'senior', 'wordlist', 'required1', 'U3', 'the ruins of buildings', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'souvenir', 'n.', '/ˌsuːvəˈnɪə(r)/', '纪念品', 'At the stand I looked for some souvenirs to take home for my friends.', '在摊位前,我找了些纪念品带回家送给朋友。', 'Travel', 44, 0, 'senior', 'wordlist', 'required1', 'U3', 'buy souvenirs', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'luggage', 'n.', '/ˈlʌɡɪdʒ/', '行李', 'The airline allows only one carry-on item of luggage for free.', '这家航空公司只允许免费携带一件随身行李。', 'Travel', 45, 0, 'senior', 'wordlist', 'required1', 'U3', 'carry-on luggage', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'explore', 'v.', '/ɪkˈsplɔː(r)/', '探索;探险;游览', 'We spent the whole afternoon exploring the narrow old streets.', '我们整个下午都在游览那些狭窄的老街。', 'Travel', 46, 0, 'senior', 'wordlist', 'required1', 'U3', 'explore a new place', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'depart', 'v.', '/dɪˈpɑːt/', '离开;出发', 'On the last day we checked out and departed from the airport.', '最后一天我们退了房,从机场出发离开。', 'Travel', 47, 0, 'senior', 'wordlist', 'required1', 'U3', 'depart from', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'register', 'v.', '/ˈredʒɪstə(r)/', '登记;注册', 'After we arrived, we registered at the hotel near the airport.', '到达后,我们在机场附近的酒店办理了入住登记。', 'Travel', 48, 0, 'senior', 'wordlist', 'required1', 'U3', 'register at a hotel', NULL, 'sufe');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3');
DELETE FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s1u3.01', '①时间 / 地点状语从句(when/while/as/before/after/until/since · where/wherever)', 'A2', 10, '上外必修一 U3 — 表''什么时候/在哪里'':时间用 when/while/as/before/after/until/since/as soon as;地点用 where/wherever。看从句表达的是''时间点''还是''地点''来选。', 1, 'required1', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s1u3.02', '②原因 / 条件 / 让步状语从句(because/since/as · if/unless · though/although/even if)', 'A2', 10, '上外必修一 U3 — 原因(给理由)用 because/since/as;条件(如果/除非)用 if/unless/as long as;让步(尽管/即使)用 though/although/even if。看主从句是''因果''''假设''还是''转折''。', 2, 'required1', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s1u3.03', '③目的 / 结果 / 方式 / 比较状语从句(so that/in order that · so…that/such…that · as if/as though · than)', 'A2', 10, '上外必修一 U3 — 目的(为了)用 so that/in order that;结果(如此…以至于)用 so…that/such…that;方式(好像)用 as if/as though;比较(比)用 than。看是''目的''''结果''''仿佛''还是''比较''。', 3, 'required1', 'U3', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'I always feel excited ____ the plane finally takes off for a new country.', 'when', 'though', 'so that', 'than', 'A', '表''……的时候''起飞,是时间关系 → when。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), '____ we were walking along the river, a cold wind began to blow.', 'Unless', 'While', 'Because', 'So that', 'B', '两个动作同时进行(走路时起风)→ 时间 while。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'We talked about our plans ____ we walked back to the hotel.', 'if', 'such that', 'as', 'than', 'C', '''一边……一边……'',边走边聊 → 时间 as。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'Remember to book the tickets ____ you leave for the airport.', 'because', 'although', 'as if', 'before', 'D', '订票在出发''之前'' → 时间 before。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), '____ we arrived in Rome, we went straight to see the ancient ruins.', 'After', 'Unless', 'So that', 'Than', 'A', '先到达后参观,先后顺序 → 时间 after。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'The tourists waited at the gate ____ the museum opened.', 'because', 'until', 'though', 'in order that', 'B', '一直等到开门为止 → 时间 until。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'Eleanor has stayed in this hotel ____ she arrived in the city.', 'unless', 'so that', 'since', 'as if', 'C', '从到达起一直住到现在 → 时间 since。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), '____ the tour guide finished speaking, everyone started taking photos.', 'Because', 'Although', 'Such that', 'As soon as', 'D', '一……就……,导游讲完马上拍照 → 时间 as soon as。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'This is the small square ____ street artists paint pictures for tourists.', 'where', 'because', 'if', 'than', 'A', '表''在……地方''画画 → 地点 where。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), '____ you travel in this region, you will find friendly local people.', 'Because', 'Wherever', 'Unless', 'So that', 'B', '''无论在哪里''旅行 → 地点 wherever。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'I felt a little nervous ____ the train slowly pulled out of the station.', 'unless', 'although', 'as', 'in order that', 'C', '随着火车开出(同时)→ 时间 as。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'We should check the weather ____ we set off on the mountain trip.', 'because', 'even if', 'than', 'before', 'D', '查天气在出发''之前'' → 时间 before。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), '____ I was buying souvenirs, my friend was booking our train tickets.', 'While', 'Since', 'Unless', 'So that', 'A', '两动作同时进行(买纪念品时订票)→ 时间 while。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'The children kept asking questions ____ the bus reached the seaside.', 'because', 'until', 'though', 'as if', 'B', '一直问到到达海边为止 → 时间 until。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'Edinburgh is the city ____ many famous writers once lived and worked.', 'because', 'if', 'where', 'than', 'C', '表''在……城市''居住工作 → 地点 where。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), '____ the holiday ended, we promised to travel together again next year.', 'Unless', 'So that', 'Such that', 'When', 'D', '假期结束的''时候'' → 时间 when。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'He has loved travelling ____ he took his first solo trip at sixteen.', 'since', 'because', 'although', 'in order that', 'A', '从十六岁第一次独自旅行起 → 时间 since。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'Please put a sticker on the map ____ you have already visited a place.', 'because', 'wherever', 'unless', 'than', 'B', '''在凡是去过的地方''贴贴纸 → 地点 wherever。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), 'We had dinner at a riverside café ____ the sun was setting over the water.', 'if', 'though', 'as', 'so that', 'C', '随着太阳西落的''同时'' → 时间 as。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.01'), '____ you check out of the hotel, make sure you take everything with you.', 'Because', 'Even if', 'Such that', 'Before', 'D', '退房''之前''拿好东西 → 时间 before。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'We chose to travel by train ____ it was cheaper than flying.', 'because', 'until', 'where', 'so that', 'A', '给出''选火车''的理由(更便宜)→ 原因 because。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ Eleanor is a first-time visitor, she would like to hire a guide.', 'Unless', 'Since', 'When', 'Than', 'B', '句首给已知原因(她是初次来)→ 原因 since。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ it was getting dark, we decided to head back to the hotel.', 'If', 'Where', 'As', 'So that', 'C', '句首引出原因(天黑了)→ 原因 as。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'We won''t be able to see the old town ____ we get up early tomorrow.', 'because', 'while', 'than', 'unless', 'D', '''除非''早起,否则看不到 → 条件 unless。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ it rains tomorrow, we will visit the museum instead of the beach.', 'If', 'Since', 'Where', 'So that', 'A', '''如果''下雨(真实条件)→ 条件 if。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'You can keep the carry-on bag ____ it weighs less than ten kilograms.', 'because', 'as long as', 'though', 'than', 'B', '''只要''不超重就可以 → 条件 as long as。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'He enjoyed the package tour ____ he disliked the very tight schedule.', 'because', 'until', 'even though', 'so that', 'C', '喜欢却又不喜欢日程,前后转折 → 让步 even though。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ the journey was long and tiring, the beautiful views made it worth it.', 'Because', 'Unless', 'Than', 'Although', 'D', '辛苦但值得,转折关系 → 让步 although。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'I still remember the Terracotta Warriors clearly ____ I went there years ago.', 'though', 'because', 'if', 'so that', 'A', '多年前去过却仍记得,转折 → 让步 though。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'We had to take a taxi to the station ____ there were no buses that early.', 'unless', 'because', 'where', 'than', 'B', '给出''打车''的原因(没有公交)→ 原因 because。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ you are not sure how much luggage you can take, ask the airline first.', 'Since', 'Although', 'If', 'So that', 'C', '''如果''不确定(假设)→ 条件 if。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ Chris prefers a city with history, I will recommend Xi''an to him.', 'Unless', 'While', 'Than', 'Since', 'D', '句首给已知原因(他偏爱历史名城)→ 原因 since。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'We can''t get closer to the sea lions ____ we have enough time today.', 'unless', 'because', 'though', 'so that', 'A', '''除非''有足够时间,否则靠不近 → 条件 unless。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ the food was a bit expensive, the restaurant was packed with tourists.', 'Because', 'Although', 'Unless', 'Than', 'B', '贵却还是满座,转折 → 让步 although。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'I''d love to visit Europe ____ my parents agree to pay for the flight.', 'since', 'where', 'if', 'so that', 'C', '''如果''父母同意(条件)→ 条件 if。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'We took lots of photos ____ we wanted to remember every moment of the trip.', 'unless', 'when', 'than', 'because', 'D', '给出''拍很多照片''的理由 → 原因 because。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ a setback may slow you down, it should never stop your travel dreams.', 'Even if', 'Because', 'Until', 'So that', 'A', '''即使''有挫折(让步)→ 让步 even if。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'The trip cost less ____ we shared one room and cooked our own meals.', 'unless', 'because', 'where', 'than', 'B', '给出''花费更少''的原因(合住自炊)→ 原因 because。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), 'You won''t enjoy the hike ____ you wear a pair of comfortable walking shoes.', 'because', 'though', 'unless', 'so that', 'C', '''除非''穿舒适的鞋,否则不会享受 → 条件 unless。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.02'), '____ she was tired after the flight, she went out to explore the city at once.', 'Because', 'Unless', 'Than', 'Although', 'D', '累却立刻出门,转折 → 让步 although。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'She downloaded a travel app ____ she could plan the whole trip on her phone.', 'so that', 'because', 'until', 'than', 'A', '下载 app 是''为了''能用手机规划 → 目的 so that。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'We left home very early ____ we might catch the first train to the coast.', 'because', 'in order that', 'though', 'as if', 'B', '早出门是''为了''赶上首班车 → 目的 in order that。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'The view from the hill was ____ beautiful that nobody wanted to leave.', 'such', 'as', 'so', 'than', 'C', 'so + 形容词 beautiful + that → 结果 so…that。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'It was ____ a breathtaking ceiling that I couldn''t tear my eyes away from it.', 'so', 'as', 'than', 'such', 'D', 'such + a + 形容词 + 名词 ceiling → 结果 such…that。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'The old explorer described the cave ____ he had walked through it yesterday.', 'as if', 'because', 'until', 'so that', 'A', '''好像''昨天才走过(实际很久前)→ 方式 as if。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'This seaside town attracts far more visitors in summer ____ it does in winter.', 'because', 'than', 'though', 'so that', 'B', 'more…than,夏天比冬天多 → 比较 than。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'I kept a careful diary ____ I could remember every place we visited.', 'because', 'until', 'so that', 'as if', 'C', '记日记是''为了''记住去过的地方 → 目的 so that。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'The guide spoke slowly ____ the foreign tourists could follow her words.', 'because', 'though', 'than', 'in order that', 'D', '说慢是''为了''让游客听懂 → 目的 in order that。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'The square was ____ crowded that we could hardly move toward the fountain.', 'so', 'such', 'as', 'than', 'A', 'so + 形容词 crowded + that → 结果 so…that。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'It was ____ a long flight that everyone fell asleep before the meal arrived.', 'so', 'such', 'as', 'than', 'B', 'such + a + 形容词 + 名词 flight → 结果 such…that。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'He talked about the ancient city ____ he had lived there all his life.', 'because', 'until', 'as though', 'so that', 'C', '''仿佛''他一直住在那里 → 方式 as though。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'Travelling by high-speed train is much faster ____ travelling by coach.', 'because', 'though', 'in order that', 'than', 'D', 'faster…than,比坐长途汽车快 → 比较 than。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'Pack your bag the night before ____ you won''t be in a rush in the morning.', 'so that', 'because', 'until', 'as if', 'A', '前一晚收拾是''为了''早上不慌乱 → 目的 so that。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'We booked the hotel early ____ we would have a room near the old town.', 'because', 'in order that', 'though', 'than', 'B', '早订房是''为了''有靠近老城的房间 → 目的 in order that。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'The waves were ____ high that the boat trip had to be put off until Monday.', 'such', 'as', 'so', 'than', 'C', 'so + 形容词 high + that → 结果 so…that。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'It was ____ a wonderful holiday that we are already planning the next one.', 'so', 'as', 'than', 'such', 'D', 'such + a + 形容词 + 名词 holiday → 结果 such…that。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'The little girl pointed at the map ____ she already knew the whole country.', 'as if', 'because', 'until', 'so that', 'A', '''好像''她已熟知整个国家 → 方式 as if。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'A guided tour usually costs more ____ exploring a city on your own does.', 'because', 'than', 'though', 'in order that', 'B', 'more…than,跟团比自由行贵 → 比较 than。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'Keep your passport in your hand luggage ____ you can reach it quickly.', 'because', 'until', 'so that', 'as though', 'C', '放手提行李是''为了''能快速拿到 → 目的 so that。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3' AND code='s1u3.03'), 'The terracotta figures were ____ lifelike that visitors gasped in surprise.', 'such', 'as', 'than', 'so', 'D', 'so + 形容词 lifelike + that → 结果 so…that。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='sufe' AND volume='required1' AND unit='U3';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'A Roman Holiday', 'Last week Eleanor spent three wonderful days in Rome, an ancient city full of ruins. She first visited the huge old theatre, once the largest outdoor theatre ever built. The ruins of the temples were so old that she could hardly believe her eyes. The best part of her trip, however, was the painted ceiling of a famous chapel. It was so breathtaking that she could not tear her eyes away from it. Eleanor also made an effort to find small restaurants where she could taste the popular meals of the region. In the evenings she enjoyed ice cream under the bright Christmas lights. At a Christmas market she found a perfect opportunity to buy presents that were in her price range. Eleanor loves visiting capital cities because each of them has its own history and its own special feeling, and she hopes to travel even more in the years ahead.', '游记·罗马假日', 151, '[{"q":"What did Eleanor enjoy most during her trip?","answer":"A","options":["The beautifully painted chapel ceiling.","The crowded shopping streets.","The food sold to tourists.","The cold winter weather."],"explanation":"原文 ''The best part of her trip… was the painted ceiling'' 的转述。"},{"q":"Why did Eleanor look for small restaurants?","answer":"B","options":["To meet other travellers there.","To taste the popular local meals.","To save the Christmas presents.","To avoid the busy markets."],"explanation":"原文 ''find small restaurants where she could taste the popular meals of the region'' 的转述。"},{"q":"According to the text, why does Eleanor love capital cities?","answer":"A","options":["Every capital offers a unique past and atmosphere.","They are always cheap to visit.","They have no tourists at all.","They are easy to reach by train."],"explanation":"末句 ''each of them has its own history and its own special feeling'' 的转述。"}]'::jsonb, '[{"word":"ruins","cn":"遗迹;废墟"},{"word":"ceiling","cn":"天花板"},{"word":"breathtaking","cn":"令人赞叹的"},{"word":"opportunity","cn":"机会"}]'::jsonb, 2, 'required1', 'U3', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'A Letter to a Young Dreamer', 'Dear Young Dreamer, you wrote to me that you dream of travelling, but as a teenager you wonder how to make it happen. You are not happy about studying subjects that do not seem relevant to your travel plans right now. Yet these lessons are teaching you valuable skills. You need them to analyse the world around you, to process information, and above all to think for yourself. These very skills will help you overcome the difficulties that stand between you and your dreams. My advice is simple: dream big, but stay practical. Even the most pleasant life has its setbacks, but a setback will not prevent you from reaching your goal if you stay rooted in the actions you can take today. Work hard, chart a course ahead, and then stick to it. Travel was once only a goal for me, too, but in the end I reached it. You can reach yours as well. Sincerely yours, Shannon.', '书信·给青少年旅行者', 159, '[{"q":"Why does the writer say school lessons are useful?","answer":"B","options":["They are all directly about travelling.","They teach skills for thinking and solving problems.","They make travel free for teenagers.","They replace the need for a travel plan."],"explanation":"原文 ''these lessons are teaching you valuable skills… to think for yourself'' 的转述。"},{"q":"What is Shannon''s main piece of advice?","answer":"C","options":["Give up studying and travel at once.","Wait until you are an adult.","Have big dreams while staying realistic.","Forget about travelling completely."],"explanation":"原文 ''dream big, but stay practical'' 的转述。"},{"q":"What does Shannon say about setbacks?","answer":"D","options":["They make all dreams impossible.","They only happen to teenagers.","They should make you stop trying.","They won''t stop you if you keep taking action."],"explanation":"原文 ''a setback will not prevent you… if you stay rooted in the actions you can take'' 的转述。"}]'::jsonb, '[{"word":"relevant","cn":"相关的"},{"word":"overcome","cn":"克服"},{"word":"setback","cn":"挫折"},{"word":"practical","cn":"切实可行的"}]'::jsonb, 2, 'required1', 'U3', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'A Traveller of the Ming Dynasty', 'Xu Xiake, who lived from 1587 to 1641, was one of the greatest travellers in Chinese history. For more than thirty years he journeyed across China, visiting countless mountains, valleys, rivers and caves. He often faced great difficulties and dangers, yet nothing could stop him from exploring new places. Wherever he went, he wrote down what he saw and heard. His careful notes were later collected into a famous travel book. Although it reads like the story of one man''s adventures, the book is also full of useful information about geography and nature. Scientists today still regard it as an early and valuable record of the land. Xu Xiake never travelled for fame or money. He simply loved to see the world with his own eyes. His life reminds us that real travel is not only about reaching famous places, but also about looking closely and recording what we discover along the way.', '人物·徐霞客', 153, '[{"q":"How long did Xu Xiake spend travelling across China?","answer":"A","options":["More than thirty years.","Only a few months.","Exactly ten years.","His whole working life of fifty years."],"explanation":"原文 ''For more than thirty years he journeyed across China'' 的转述。"},{"q":"Besides being an adventure story, what does his book contain?","answer":"B","options":["Only poems about the moon.","Valuable facts on the land and its nature.","A list of famous restaurants.","Letters to his family."],"explanation":"原文 ''full of useful information about geography and nature'' 的转述。"},{"q":"Why did Xu Xiake travel, according to the text?","answer":"C","options":["To become rich and famous.","Because the emperor ordered him to.","Simply out of a personal love for seeing new places.","To sell maps to other travellers."],"explanation":"原文 ''never travelled for fame or money. He simply loved to see the world with his own eyes'' 的转述。"}]'::jsonb, '[{"word":"journey","cn":"旅行;旅程"},{"word":"valley","cn":"山谷"},{"word":"explore","cn":"探索"},{"word":"record","cn":"记录"}]'::jsonb, 2, 'required1', 'U3', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Planning a Trip as a Teenager', 'When teenagers want to travel, they soon find that they cannot decide everything for themselves. Several factors will shape any plan they make. The first factor is their parents, who usually have a say in where and how their children travel. The second factor is money. The amount that a family can spend often determines the kind of trip a teenager can take. With a larger budget, a student might fly to Europe; with a smaller one, the same student might join a local exchange programme or simply stay close to home. None of this means that travel is impossible. A wise young traveller learns to chart a course ahead, comparing prices, checking the weather, and choosing places that fit the family''s plans. It is also helpful to make a clear list of the things to prepare before leaving. Travel may take more planning for a teenager, but with patience and a practical attitude, a good trip is always within reach.', '说明·青少年的旅行计划', 161, '[{"q":"What is the first factor mentioned that shapes a teenager''s trip?","answer":"D","options":["The weather of the season.","The price of train tickets.","The size of their suitcase.","Their parents'' opinions."],"explanation":"原文 ''The first factor is their parents, who usually have a say'' 的转述。"},{"q":"How does money affect a teenager''s travel, according to the text?","answer":"A","options":["It decides what kind of trip is possible.","It has no real effect at all.","It only matters for flights to Europe.","It makes parents change their minds."],"explanation":"原文 ''The amount that a family can spend often determines the kind of trip'' 的转述。"},{"q":"What does the writer suggest a wise young traveller should do?","answer":"B","options":["Travel without telling anyone.","Plan in advance and pick destinations suited to the family.","Ignore prices and the weather.","Wait until they are much older."],"explanation":"原文 ''learns to chart a course ahead, comparing prices… choosing places that fit the family''s plans'' 的转述。"}]'::jsonb, '[{"word":"factor","cn":"因素"},{"word":"amount","cn":"数量"},{"word":"determine","cn":"决定"},{"word":"budget","cn":"预算"}]'::jsonb, 2, 'required1', 'U3', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Rules at the Airport', 'Before Tina flew off for her holiday, she needed some information about the airline''s luggage rules. At the desk, a friendly worker explained the main points clearly. Each passenger may bring only one carry-on item for free. If you want to take a second bag onto the plane, the airline will charge a fee. So the worker gave Tina some simple advice: do not pack anything that you do not really need. A lighter bag is not only cheaper but also much easier to carry through the busy airport. Tina also learned that some objects, such as bottles of water, are not allowed in carry-on luggage at all, because of safety rules. She decided to leave a few heavy items at home and to buy what she needed after she arrived. Thanks to the worker''s help, Tina felt calm and ready. She checked in her large bag, kept her passport in her hand, and walked happily towards the gate.', '实用·机场行李规则', 159, '[{"q":"How many carry-on items can a passenger bring for free?","answer":"C","options":["As many as they like.","Exactly three.","Only one.","None at all."],"explanation":"原文 ''Each passenger may bring only one carry-on item for free'' 的转述。"},{"q":"What advice did the worker give Tina?","answer":"D","options":["To buy a bigger suitcase.","To carry two heavy bags onto the plane.","To leave her passport at home.","Not to pack things she did not really need."],"explanation":"原文 ''do not pack anything that you do not really need'' 的转述。"},{"q":"Why are some objects not allowed in carry-on luggage?","answer":"A","options":["Because of safety rules.","Because they are too cheap.","Because they are too colourful.","Because passengers dislike them."],"explanation":"原文 ''are not allowed in carry-on luggage at all, because of safety rules'' 的转述。"}]'::jsonb, '[{"word":"luggage","cn":"行李"},{"word":"carry-on","cn":"随身携带的"},{"word":"fee","cn":"费用"},{"word":"passport","cn":"护照"}]'::jsonb, 2, 'required1', 'U3', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Why I Recommend Xi''an', 'My Canadian friend Chris is planning a trip to China this winter, and he asked me which city to choose. I strongly recommend Xi''an, an amazing historic city in the northwest. Xi''an enjoys a very long history, as it was once the capital of thirteen dynasties and the starting point of the ancient Silk Road. The most famous attraction there is the army of terracotta warriors, built more than two thousand years ago. They are so lifelike that visitors often gasp in surprise when they first see them. Xi''an also has the old Bell Tower and Drum Tower, which are well worth a visit. If Chris gets hungry, he must try the local food, such as the warm bread soaked in lamb soup. I told Chris that he cannot really know how wonderful the city is unless he goes there himself. A three-day trip, I believe, would give him just enough time to enjoy its history, its sights and its tasty meals.', '推荐·向朋友介绍城市', 162, '[{"q":"Why is Xi''an described as a historic city?","answer":"B","options":["It was built only a few years ago.","It was the capital of many dynasties and start of the Silk Road.","It has the largest airport in China.","It is the coldest place in the northwest."],"explanation":"原文 ''it was once the capital of thirteen dynasties and the starting point of the ancient Silk Road'' 的转述。"},{"q":"What is the most famous attraction in Xi''an?","answer":"C","options":["A modern shopping centre.","A long sandy beach.","The ancient clay soldiers built long ago.","A tall glass tower."],"explanation":"原文 ''The most famous attraction there is the army of terracotta warriors'' 的转述。"},{"q":"What does the writer tell Chris about really knowing the city?","answer":"D","options":["He should read more books about it.","He should ask other tourists first.","He should watch videos online instead.","He won''t know how wonderful it is unless he visits."],"explanation":"原文 ''he cannot really know how wonderful the city is unless he goes there himself'' 的转述。"}]'::jsonb, '[{"word":"recommend","cn":"推荐"},{"word":"historic","cn":"历史悠久的"},{"word":"attraction","cn":"景点"},{"word":"dynasty","cn":"朝代"}]'::jsonb, 2, 'required1', 'U3', 'sufe');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='sufe' AND volume='required1' AND unit='U3';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U3', 'A Day at the Seaside', 'Last summer my family took a short (1)____ to a small seaside town. We set off early in the morning (2)____ we could arrive before the crowds. As soon as we got there, I could not (3)____ my eyes away from the bright blue water. The town was (4)____ beautiful that we decided to stay an extra day. In the afternoon we walked along the beach and looked for shells. My little sister made a great (5)____ to build a sandcastle, but a wave soon washed it away. For lunch we (6)____ the popular seafood of the region, which tasted wonderful. Later we bought a few small (7)____ to take home for our friends. Although we were tired, the trip was (8)____ a happy one that none of us wanted to leave. On the way back, we already began to (9)____ a course for our next holiday. A short journey like this can (10)____ many good memories.', 157, 2, '[{"q":"1","answer":"A","options":["trip","shell","fee","rule"],"explanation":"take a short trip 短途旅行。"},{"q":"2","answer":"B","options":["unless","so that","though","than"],"explanation":"目的''为了''早到 → so that。"},{"q":"3","answer":"C","options":["buy","sell","tear","lose"],"explanation":"tear one''s eyes away 移开目光。"},{"q":"4","answer":"D","options":["such","as","than","so"],"explanation":"so + 形容词 beautiful → so…that。"},{"q":"5","answer":"A","options":["effort","price","noise","season"],"explanation":"make a great effort 努力。"},{"q":"6","answer":"B","options":["forgot","tasted","sold","lost"],"explanation":"tasted the seafood 品尝海鲜。"},{"q":"7","answer":"C","options":["songs","prices","souvenirs","machines"],"explanation":"buy souvenirs 买纪念品。"},{"q":"8","answer":"D","options":["so","as","than","such"],"explanation":"such + a + 形容词 + 名词 → such…that。"},{"q":"9","answer":"A","options":["chart","throw","hide","drop"],"explanation":"chart a course 制定计划。"},{"q":"10","answer":"B","options":["lose","create","waste","sell"],"explanation":"create memories 创造回忆。"}]'::jsonb, 1, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U3', 'Getting Ready to Pack', 'Packing well is an important skill for every (1)____. The night before a trip, you should make a clear (2)____ of everything you need to take. Try to pack light, (3)____ a heavy bag is hard to carry through a busy airport. Most airlines allow only one (4)____ item of hand luggage for free. (5)____ you bring a second bag onto the plane, they will charge you a fee. So a wise traveller never packs anything that is not (6)____ to the trip. Remember to keep your passport and tickets where you can (7)____ them quickly. It is also helpful to (8)____ the weather of the place you are visiting, (9)____ you will know what clothes to bring. With a little planning (10)____, packing becomes quick and easy, and you can start your journey without any worry.', 137, 2, '[{"q":"1","answer":"C","options":["ceiling","valley","traveller","factor"],"explanation":"every traveller 每位旅行者。"},{"q":"2","answer":"D","options":["price","noise","fee","list"],"explanation":"make a list 列清单。"},{"q":"3","answer":"A","options":["because","unless","though","so that"],"explanation":"给出''轻装''的原因 → because。"},{"q":"4","answer":"B","options":["lost","carry-on","broken","sold"],"explanation":"carry-on item 随身物品。"},{"q":"5","answer":"C","options":["Although","Until","If","Than"],"explanation":"''如果''多带一个包 → 条件 If。"},{"q":"6","answer":"D","options":["afraid","asleep","alone","relevant"],"explanation":"relevant to the trip 与旅行相关。"},{"q":"7","answer":"A","options":["reach","throw","hide","drop"],"explanation":"reach them quickly 能快速拿到。"},{"q":"8","answer":"B","options":["sell","check","lose","waste"],"explanation":"check the weather 查天气。"},{"q":"9","answer":"C","options":["unless","though","so that","than"],"explanation":"目的''这样你就……'' → so that。"},{"q":"10","answer":"D","options":["behind","below","inside","ahead"],"explanation":"planning ahead 提前规划。"}]'::jsonb, 2, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U3', 'Lost in the Old Town', 'On our second day, my friend and I got (1)____ in the narrow streets of the old town. The little map was (2)____ confusing that we soon had no idea where we were. (3)____ we felt a little worried, the walk turned into a small adventure. (4)____ we turned a corner, we saw something new and interesting. We passed quiet squares (5)____ old men were playing chess in the sun. We kept walking (6)____ we finally reached a busy market full of colour and noise. A kind shopkeeper (7)____ us the way back to our hotel and even drew a simple map for us. (8)____ we had lost our way, that afternoon became my favourite part of the whole trip. Sometimes getting lost lets you (9)____ a city in a way that no guidebook can. Now I always say that a wrong turn can (10)____ to the best surprises.', 149, 2, '[{"q":"1","answer":"A","options":["lost","rich","late","busy"],"explanation":"get lost 迷路。"},{"q":"2","answer":"B","options":["such","so","as","than"],"explanation":"so + 形容词 confusing → so…that。"},{"q":"3","answer":"C","options":["Because","Unless","Although","Than"],"explanation":"担心却变成冒险,转折 → Although。"},{"q":"4","answer":"D","options":["Because","Unless","Than","Wherever"],"explanation":"''无论拐到哪里'' → 地点 Wherever。"},{"q":"5","answer":"A","options":["where","because","if","than"],"explanation":"quiet squares where 地点状语从句 → where。"},{"q":"6","answer":"B","options":["because","until","unless","so that"],"explanation":"一直走''直到''到达市场 → until。"},{"q":"7","answer":"C","options":["sold","lost","showed","hid"],"explanation":"showed us the way 给我们指路。"},{"q":"8","answer":"D","options":["Because","Unless","Than","Although"],"explanation":"迷了路却成最爱,转折 → Although。"},{"q":"9","answer":"A","options":["explore","sell","waste","forget"],"explanation":"explore a city 探索城市。"},{"q":"10","answer":"B","options":["throw","lead","drop","lose"],"explanation":"lead to surprises 带来惊喜。"}]'::jsonb, 3, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U3', 'Choosing a City to Visit', 'My friend Emily has an (1)____ to visit a Chinese city this winter, so she asked us for some advice. We held a discussion to help her (2)____ which place to choose. I strongly (3)____ Xi''an, an amazing historic city in the northwest. It enjoys a long (4)____, because it was once the capital of many dynasties. Its most famous (5)____ is the army of terracotta warriors, which were built more than two thousand years ago. They are (6)____ lifelike that visitors often gasp in surprise. (7)____ Emily prefers a city with history, Xi''an would be a perfect choice. She should also try the local (8)____, such as warm bread soaked in lamb soup. I told her that she cannot know how wonderful the city is (9)____ she goes there herself. With three days, she will have just enough time to enjoy the sights and (10)____ wonderful memories.', 148, 2, '[{"q":"1","answer":"C","options":["luggage","ceiling","opportunity","valley"],"explanation":"have an opportunity 有机会。"},{"q":"2","answer":"D","options":["sell","lose","throw","decide"],"explanation":"decide which place 决定选哪里。"},{"q":"3","answer":"A","options":["recommend","forget","waste","lose"],"explanation":"recommend Xi''an 推荐西安。"},{"q":"4","answer":"B","options":["price","history","noise","fee"],"explanation":"a long history 悠久历史。"},{"q":"5","answer":"C","options":["mistake","machine","attraction","garden"],"explanation":"famous attraction 著名景点。"},{"q":"6","answer":"D","options":["such","as","than","so"],"explanation":"so + 形容词 lifelike → so…that。"},{"q":"7","answer":"A","options":["Since","Unless","Although","Than"],"explanation":"给原因''因为她偏爱历史'' → Since。"},{"q":"8","answer":"B","options":["song","food","price","noise"],"explanation":"local food 当地食物。"},{"q":"9","answer":"C","options":["because","though","unless","than"],"explanation":"''除非''亲自去,否则不知道 → unless。"},{"q":"10","answer":"D","options":["lose","waste","sell","create"],"explanation":"create memories 创造回忆。"}]'::jsonb, 4, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U3', 'My First Flight', 'I will never forget the day (1)____ I took my very first flight. I was both excited and a little (2)____ as the plane began to move. (3)____ it slowly rose into the sky, the houses below grew smaller and smaller. Soon we were flying above the clouds, and the view was (4)____ amazing that I could not stop staring out of the window. A kind flight worker brought us drinks and a meal (5)____ we felt comfortable. The flight was (6)____ a long one that most passengers fell asleep before we landed. (7)____ I was tired, I stayed awake to watch the sunset from high above the earth. When we finally (8)____ from the plane, I felt like a real traveller. I had learned that flying is much faster (9)____ travelling by train or coach. From that day on, I have (10)____ every chance to see new places by air.', 151, 2, '[{"q":"1","answer":"A","options":["when","where","why","which"],"explanation":"the day when 时间状语从句 → when。"},{"q":"2","answer":"B","options":["rich","afraid","late","busy"],"explanation":"a little afraid 有点害怕。"},{"q":"3","answer":"C","options":["Unless","Because","As","Than"],"explanation":"随着飞机上升(同时)→ 时间 As。"},{"q":"4","answer":"D","options":["such","as","than","so"],"explanation":"so + 形容词 amazing → so…that。"},{"q":"5","answer":"A","options":["so that","unless","though","than"],"explanation":"目的''为了让我们舒适'' → so that。"},{"q":"6","answer":"B","options":["so","such","as","than"],"explanation":"such + a + 形容词 + 名词 → such…that。"},{"q":"7","answer":"C","options":["Because","Unless","Although","Than"],"explanation":"累却保持清醒,转折 → Although。"},{"q":"8","answer":"D","options":["sold","lost","hid","departed"],"explanation":"departed from the plane 下飞机。"},{"q":"9","answer":"A","options":["than","because","though","unless"],"explanation":"faster…than 比……更快 → than。"},{"q":"10","answer":"B","options":["thrown","taken","dropped","lost"],"explanation":"have taken every chance 抓住每个机会。"}]'::jsonb, 5, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required1', 'U3', 'A Mountain Trip to Remember', 'Two friends and I planned a mountain trip (1)____ we wanted to see the sunrise from the top. We got up very early (2)____ we could start climbing before dawn. (3)____ we walked, a cold wind blew across the path, but the beautiful (4)____ kept us going. We did not stop (5)____ we reached a small flat area near the top. (6)____ the climb was hard, none of us wanted to give up. At last the sun rose, and the view was (7)____ breathtaking that we stood in silence for a while. We took many photos (8)____ we could show our families back home. (9)____ you have stood on a mountain at sunrise, it is hard to imagine the feeling. That trip taught me that the best (10)____ are often the ones that take the most effort.', 137, 2, '[{"q":"1","answer":"C","options":["unless","where","because","than"],"explanation":"给出''计划登山''的原因 → because。"},{"q":"2","answer":"D","options":["unless","though","than","so that"],"explanation":"目的''为了天亮前出发'' → so that。"},{"q":"3","answer":"A","options":["As","Unless","Because","Than"],"explanation":"随着我们走(同时)→ 时间 As。"},{"q":"4","answer":"B","options":["price","scenery","noise","fee"],"explanation":"beautiful scenery 美丽风景。"},{"q":"5","answer":"C","options":["because","unless","until","so that"],"explanation":"没停''直到''到达平地 → until。"},{"q":"6","answer":"D","options":["Because","Unless","Than","Although"],"explanation":"难却不放弃,转折 → Although。"},{"q":"7","answer":"A","options":["so","such","as","than"],"explanation":"so + 形容词 breathtaking → so…that。"},{"q":"8","answer":"B","options":["unless","so that","though","than"],"explanation":"目的''为了给家人看'' → so that。"},{"q":"9","answer":"C","options":["Although","Because","Until","Than"],"explanation":"''直到''你站过……(否则难以想象)→ Until。"},{"q":"10","answer":"D","options":["prices","noises","machines","journeys"],"explanation":"the best journeys 最好的旅程。"}]'::jsonb, 6, 'sufe');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='required1' AND unit='U3';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·对话 Booking a Flight', '上外必修一 U3 · dialogue', 3, 'Tina: Hello, I''d like to book a flight to Rome for next Friday.
Agent: Of course. Would you like a morning flight or an afternoon one?
Tina: A morning flight, please, so that I can have the whole day in the city.
Agent: There is one that leaves at nine o''clock. The ticket costs two hundred pounds.
Tina: That sounds fine. Can I take one carry-on bag for free?
Agent: Yes, one carry-on item is free, but a second bag has an extra fee.
Tina: All right, I''ll only bring one. Could you book that morning flight for me?
Agent: Certainly. Your nine o''clock flight to Rome is now booked. Have a good trip!', 'Tina 想订下周五去罗马的机票;她要早班机,这样能玩一整天;九点的航班票价两百英镑;一件随身行李免费,第二件要额外收费;Tina 只带一件,订下了九点的航班。', 'uk_female', '[{"q":"Where does Tina want to fly to?","type":"choice","answer":"A","options":["Rome.","Paris.","Beijing.","Cairo."]},{"q":"Why does Tina choose a morning flight?","type":"choice","answer":"B","options":["It is the cheapest.","So that she can have the whole day in the city.","Because there are no afternoon flights.","Her friend told her to."]},{"q":"How much does the ticket cost?","type":"choice","answer":"A","options":["Two hundred pounds.","Ninety pounds.","Nineteen pounds.","Two thousand pounds."]},{"q":"What does the agent say about luggage?","type":"choice","answer":"B","options":["No bags are allowed.","One carry-on bag is free; a second has a fee.","Two carry-on bags are free.","Carry-on bags are not allowed at all."]},{"q":"Which flight does Tina finally book?","type":"choice","answer":"C","options":["An evening flight.","A flight for next Monday.","The nine o''clock morning flight.","No flight at all."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U3', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·短文 What Travel Means', '上外必修一 U3 · passage', 2, 'A wise man once told me to experience life to the fullest while you are young.
There is no better way to do this than by travelling.
When you travel, you see the beauty of the world with your own eyes.
Being away from home opens your heart and changes the way you think.
So whenever you have the chance, go and discover new places.', '一位智者曾告诉我,趁年轻时要尽情体验生活;没有比旅行更好的方式;旅行时,你用自己的眼睛看到世界之美;离开家会敞开你的心扉,改变你的思维方式;所以一有机会,就去探索新地方。', 'uk_female', '[{"q":"What did the wise man say to do while young?","type":"choice","answer":"D","options":["Stay safely at home.","Save all your money.","Avoid making any plans.","Experience life to the fullest."]},{"q":"According to the passage, what is the best way to do this?","type":"choice","answer":"A","options":["By travelling.","By reading books.","By sleeping more.","By watching films."]},{"q":"What do you see when you travel?","type":"choice","answer":"B","options":["Only your own town.","The beauty of the world with your own eyes.","Nothing new.","The inside of an airport."]},{"q":"What does being away from home do?","type":"choice","answer":"C","options":["It makes you forget everything.","It keeps your mind closed.","It opens your heart and changes how you think.","It makes travel boring."]},{"q":"What advice does the speaker give at the end?","type":"choice","answer":"D","options":["Never leave your hometown.","Travel only when you are old.","Stop dreaming about travel.","Go and discover new places whenever you can."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U3', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·对话 Checking in at a Hotel', '上外必修一 U3 · dialogue', 3, 'Clerk: Good evening, and welcome. Do you have a booking with us?
Mark: Yes, I booked a room for three nights under the name Mark Lee.
Clerk: Let me check. Yes, here it is. May I see your passport, please?
Mark: Here you are. Is breakfast included in the price?
Clerk: Yes, breakfast is served from seven to ten in the morning.
Mark: Great. Could you also tell me how to get to the old town?
Clerk: Of course. It''s a short walk. Turn left when you leave the hotel.
Mark: Thank you so much. I can''t wait to start exploring tomorrow.', 'Mark 用 Mark Lee 的名字订了三晚的房间;前台核对预订并查看护照;房价含早餐,早餐七点到十点供应;前台告诉他去老城的路:出酒店左转,步行很近;Mark 期待明天开始游览。', 'uk_female', '[{"q":"How many nights did Mark book?","type":"choice","answer":"A","options":["Three nights.","One night.","Five nights.","Ten nights."]},{"q":"What does the clerk ask to see?","type":"choice","answer":"B","options":["His plane ticket.","His passport.","His map.","His luggage."]},{"q":"When is breakfast served?","type":"choice","answer":"C","options":["All day long.","Only at noon.","From seven to ten in the morning.","Late at night."]},{"q":"How can Mark get to the old town?","type":"choice","answer":"D","options":["By taking a long bus ride.","By flying there.","By calling a taxi.","By turning left and walking a short way."]},{"q":"How does Mark feel about the next day?","type":"choice","answer":"A","options":["He can''t wait to start exploring.","He wants to go home.","He is too tired to move.","He dislikes the hotel."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U3', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·短文 Advice for Young Travellers', '上外必修一 U3 · passage', 2, 'If you are a teenager who dreams of travelling, here is some simple advice.
Dream big, but always stay practical about what you can do now.
Remember that a small setback will not stop you if you keep taking action.
Work hard, chart a course ahead, and then stick to your plan.
Step by step, your travel dream can slowly come true.', '如果你是个梦想旅行的青少年,这里有些简单的建议:敢于做大梦,但对当下能做的事要切合实际;记住,只要不断行动,小小的挫折阻止不了你;努力做事,提前规划路线,然后坚持计划;一步步地,你的旅行梦想就能慢慢实现。', 'uk_female', '[{"q":"Who is this advice for?","type":"choice","answer":"B","options":["Only adults with lots of money.","A teenager who dreams of travelling.","People who hate travel.","Pilots and flight workers."]},{"q":"What does the speaker say about dreaming?","type":"choice","answer":"C","options":["Never dream at all.","Dream only about money.","Dream big but stay practical.","Forget your dreams quickly."]},{"q":"What will not stop you, according to the passage?","type":"choice","answer":"D","options":["A long flight.","A friendly guide.","A clear travel plan.","A small setback, if you keep acting."]},{"q":"What three things should you do?","type":"choice","answer":"A","options":["Work hard, chart a course, and stick to the plan.","Sleep, wait, and hope.","Spend, borrow, and forget.","Read, talk, and rest."]},{"q":"How does a travel dream come true?","type":"choice","answer":"B","options":["All at once, by luck.","Step by step, slowly.","Only with no effort.","Never, the speaker says."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U3', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·对话 Buying Souvenirs', '上外必修一 U3 · dialogue', 3, 'Lucy: Look at these little painted boxes. They''d make lovely gifts for my friends.
Ben: They are pretty, but the prices here seem a bit high to me.
Lucy: Do you think so? This one costs twenty pounds.
Ben: I saw the same boxes near the station for much less.
Lucy: Really? Then maybe we should walk there before I buy anything.
Ben: Good idea. It''s always wise to compare prices when you buy souvenirs.
Lucy: You''re right. I don''t want to spend more than I need to.
Ben: Let''s go and check. We still have plenty of time before dinner.', 'Lucy 看中一些手绘小盒子想送朋友;Ben 觉得这里价格偏高;一个要二十英镑;Ben 说在车站附近见过便宜得多的同款;两人决定先去那边比比价再买;比价是买纪念品的明智之举,他们晚饭前还有时间。', 'uk_female', '[{"q":"What does Lucy want to buy?","type":"choice","answer":"C","options":["A pair of shoes.","Some food.","Little painted boxes.","A train ticket."]},{"q":"What does Ben think about the prices here?","type":"choice","answer":"D","options":["They are free.","They are the lowest in town.","He doesn''t mention prices.","They seem a bit high."]},{"q":"Where did Ben see the same boxes for less?","type":"choice","answer":"A","options":["Near the station.","At the airport.","Inside the hotel.","On the mountain."]},{"q":"What does Ben say is wise when buying souvenirs?","type":"choice","answer":"B","options":["To buy the first thing you see.","To compare prices.","To pay any price quickly.","To never ask the cost."]},{"q":"What do they decide to do?","type":"choice","answer":"C","options":["Buy everything at once.","Go straight to dinner.","Walk to the other place to compare prices.","Stop shopping for good."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U3', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U3 听力·短文 Packing for a Trip', '上外必修一 U3 · passage', 2, 'Here is a useful tip for anyone who is getting ready for a journey.
The night before you leave, make a clear list of everything you need.
Try to pack light, because a heavy bag is hard to carry around.
Keep your passport and tickets where you can reach them easily.
With a little planning ahead, packing becomes quick and stress-free.', '给准备出行的人一个实用贴士:出发前一晚,把要带的东西列成清单;尽量轻装,因为重包不好带;把护照和机票放在容易拿到的地方;只要提前规划一点,收拾行李就会又快又轻松。', 'uk_female', '[{"q":"Who is this tip for?","type":"choice","answer":"D","options":["Only flight workers.","Only small children.","People who never travel.","Anyone getting ready for a journey."]},{"q":"What should you do the night before you leave?","type":"choice","answer":"A","options":["Make a clear list of what you need.","Pack nothing at all.","Buy a bigger suitcase.","Stay up very late."]},{"q":"Why should you pack light?","type":"choice","answer":"B","options":["Because light bags are colourful.","Because a heavy bag is hard to carry.","Because it looks nicer.","Because the airline says so."]},{"q":"Where should you keep your passport and tickets?","type":"choice","answer":"C","options":["In your large checked bag.","At home.","Where you can reach them easily.","With a stranger."]},{"q":"What does planning ahead do for packing?","type":"choice","answer":"D","options":["It makes packing much harder.","It wastes a lot of time.","It has no effect at all.","It makes packing quick and stress-free."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U3', 'sufe');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='required1' AND unit='U3';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (10, 'Propose a Travel Plan for a Friend(为朋友拟一份旅行计划)', 'A Three-Day Trip for My Friend', '假设你的加拿大朋友 Chris 计划今年十二月来中国旅行。请给他写一封约80词的电子邮件,为他推荐一座城市并拟一份三天的旅行计划,内容包括:① 推荐的城市及推荐理由(历史/风景/美食);② 三天的大致安排(景点、美食、购物等);③ 一句鼓励或祝愿。注意:适当使用状语从句使行文连贯。', 'Suppose your Canadian friend Chris is planning a trip to China this December. Write an email (about 80 words) to recommend a city and make a three-day travel plan for him, including: 1) the city you recommend and why (history, scenery or food); 2) a rough plan for the three days (attractions, food, shopping, etc.); 3) one line of encouragement or good wishes. Try to use some adverbial clauses to link your ideas.', '["推荐城市并说明理由(I strongly recommend … because …)","三天行程安排(On the first day … On the second day … On the last day …)","鼓励或祝愿(I''m sure you''ll love it! / Have a wonderful trip!)","恰当使用状语从句(when / because / so that / unless …)使行文连贯"]'::jsonb, 70, 100, 'Hi Chris, nice to hear from you. As you prefer a city with a long history, I strongly recommend Xi''an. On the first day, visit the terracotta warriors, which are so lifelike that visitors often gasp in surprise. On the second day, explore the old Bell Tower and try the warm bread soaked in lamb soup. On the last day, do some shopping before you depart from the airport. You can''t really know how wonderful the city is unless you go there yourself. Have a great trip! Yours, Li Hua', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["As you prefer a city with a long history, I strongly recommend Xi''an.","The terracotta warriors are so lifelike that visitors often gasp in surprise.","On the last day, do some shopping before you depart from the airport.","You can''t really know how wonderful the city is unless you go there yourself."]'::jsonb, '[{"wrong":"I recommend Xi''an because of it has a long history.","correct":"I recommend Xi''an because it has a long history.","note":"because 引导从句,后接句子,不与 of 连用。"},{"wrong":"Visit the warriors so that lifelike that you gasp.","correct":"The warriors are so lifelike that you gasp.","note":"so + 形容词 + that 表结果;so that 表目的,二者不可混用。"},{"wrong":"You can''t know the city unless you don''t go there.","correct":"You can''t know the city unless you go there.","note":"unless 已含否定(=if not),从句不再加 not。"}]'::jsonb, '【为朋友拟旅行计划·邮件结构】
开头 Hi Chris, nice to hear from you.
推荐 As you prefer …, I strongly recommend …
Day 1 On the first day, visit … which is so … that …
Day 2–3 On the second day … On the last day, … before you depart …
祝愿 You can''t know how wonderful it is unless you go. Have a great trip! Yours, …', 2, 'required1', 'U3', 'sufe');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='required1' AND unit='U3';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (10, 'required1', 'U3', '{"title":"状语从句·六大类连词速查","intro":"状语从句在句中作状语,说明主句动作的时间、地点、原因、条件、让步、目的、结果、方式或比较。判断口诀:先看主从句的逻辑关系(什么时候/在哪里/为什么/如果/尽管/为了/以至于/好像/比),再选对应连词。","table":{"headers":["类型","常用连词 / 例句"],"rows":[["时间","when/while/as/before/after/until/since/as soon as:I felt excited when the plane took off."],["地点","where/wherever:This is the square where artists paint for tourists."],["原因","because/since/as:We chose the train because it was cheaper."],["条件","if/unless/as long as:We can''t see the old town unless we get up early."],["让步","though/although/even though/even if:Although she was tired, she went out at once."],["目的","so that/in order that:She left early so that she could catch the first train."],["结果","so…that / such…that:It was such a long flight that everyone fell asleep."],["方式/比较","as if/as though;than:He spoke as if he had lived there. / Flying is faster than the train."]]},"specialRules":[{"rule":"so + 形容词/副词 + that 表结果;so that(中间不加形/副)表目的——别混","mark":"so beautiful that(结果) ｜ so that I could see(目的)"},{"rule":"such + (a/an) + 形容词 + 名词 + that 表结果","mark":"such a long flight that everyone slept"},{"rule":"unless = if … not,本身含否定,从句不再加 not","mark":"unless you go(=if you don''t go)"},{"rule":"since/as 既可表时间也可表原因,看句意定;though/although 不与 but 连用","mark":"Although …, (× but) …"}],"why":["状语从句的连词不是靠记搭配硬背,而是看主句和从句之间是''时间先后''''因果''''假设''''转折''''目的''''结果''还是''比较''——逻辑关系定连词,所以每题往往只有一个连词说得通。"],"gaokaoPoints":["so…that 与 such…that 的区别(看 that 前是形容词还是''a+形+名'');so that(目的) vs so…that(结果)。","unless / as long as / even if 在语法填空和完形中高频;though/although 引导让步从句、主句不加 but。","as 的多义(当……时/因为/随着/像……一样)需结合语境判断。"],"examVsReal":[{"exam":"Although it was raining, we still went out.(考试用 Although,主句不加 but)","real":"It was raining, but we still went out.","note":"考试常考''although 与 but 不同时用'';真实口语里直接用 but 即可"},{"exam":"He acted as if he had been there before.(考试用虚拟 had been)","real":"He acted like he''d been there before.","note":"考试 as if + 虚拟语气;口语里常用 like 代替 as if,且时态更随意"}]}'::jsonb, 'sufe');

COMMIT;

-- ===== 自带校验(publisher='sufe') =====
SELECT 'vocab' k, count(*) v, 48 expect FROM public.junior_vocab WHERE publisher='sufe' AND volume='required1' AND unit='U3'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required1' AND unit='U3')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='sufe' AND volume='required1' AND unit='U3'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='sufe' AND volume='required1' AND unit='U3'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='required1' AND unit='U3'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='required1' AND unit='U3'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='required1' AND unit='U3' ORDER BY k;
