-- ============================================================
-- 上外(sufe) 必修一 U2(Language and Mind)灌库(junior_* 表,publisher='sufe' volume='elective2' unit='U2' grade=11)。幂等。
-- ★DELETE 全带 publisher='sufe',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 48 =====
DELETE FROM public.junior_vocab WHERE publisher='sufe' AND volume='elective2' AND unit='U2';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'highlight', 'n./v.', '/ˈhaɪlaɪt/', '最精彩的部分;要点;强调', 'The highlight of the lecture was how language shapes the way we think.', '讲座最精彩的部分是语言如何塑造我们的思维方式。', 'Language and Mind', 1, 0, 'senior', 'wordlist', 'elective2', 'U2', 'the highlight of', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'magnetic', 'adj.', '/mæɡˈnetɪk/', '磁的;有磁性的;有吸引力的', 'Doctors used a magnetic scanner to study the bilingual brain.', '医生用磁性扫描仪研究双语者的大脑。', 'Language and Mind', 2, 0, 'senior', 'wordlist', 'elective2', 'U2', 'magnetic resonance', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'resonance', 'n.', '/ˈrezənəns/', '共鸣;共振', 'Magnetic resonance imaging lets scientists watch the brain at work.', '磁共振成像让科学家观察大脑工作的过程。', 'Language and Mind', 3, 0, 'senior', 'wordlist', 'elective2', 'U2', 'magnetic resonance', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'imaging', 'n.', '/ˈɪmɪdʒɪŋ/', '成像', 'Brain imaging shows that learning a language changes its structure.', '脑成像显示,学习语言会改变大脑的结构。', 'Language and Mind', 4, 0, 'senior', 'wordlist', 'elective2', 'U2', 'brain imaging', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'scan', 'n./v.', '/skæn/', '扫描检查;扫描;细看', 'The students were given a brain scan before and after the course.', '学生们在课程前后各做了一次脑部扫描。', 'Language and Mind', 5, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a brain scan', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'promising', 'adj.', '/ˈprɒmɪsɪŋ/', '有希望的;有前途的', 'Language learning is a promising way to keep the mind sharp.', '学语言是保持头脑敏锐的一种有希望的方法。', 'Language and Mind', 6, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a promising way', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'enhanced', 'adj.', '/ɪnˈhɑːnst/', '增强的;提高的', 'Bilingual people often enjoy enhanced memory and attention.', '双语者往往拥有更强的记忆力和注意力。', 'Language and Mind', 7, 0, 'senior', 'wordlist', 'elective2', 'U2', 'enhanced memory', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'cognitive', 'adj.', '/ˈkɒɡnɪtɪv/', '认知的;感知的', 'Learning a second language brings real cognitive benefits.', '学习第二语言能带来实实在在的认知益处。', 'Language and Mind', 8, 0, 'senior', 'wordlist', 'elective2', 'U2', 'cognitive benefits', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'outperform', 'v.', '/ˌaʊtpəˈfɔːm/', '超过;胜过', 'In some memory tests, bilingual children outperform their classmates.', '在一些记忆测试中,双语儿童的表现胜过同学。', 'Language and Mind', 9, 0, 'senior', 'wordlist', 'elective2', 'U2', 'outperform others', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'journal', 'n.', '/ˈdʒɜːnl/', '期刊;杂志;日志', 'The study was published in a well-known science journal.', '这项研究发表在一份知名的科学期刊上。', 'Language and Mind', 10, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a science journal', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'comprehension', 'n.', '/ˌkɒmprɪˈhenʃn/', '理解;理解力', 'A comprehension task tested how quickly they understood each word.', '一项理解任务测试他们理解每个词的速度。', 'Language and Mind', 11, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a comprehension task', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'corresponding', 'adj.', '/ˌkɒrɪˈspɒndɪŋ/', '相应的;对应的', 'They had to choose the corresponding image for each spoken word.', '他们要为每个听到的词选出相应的图片。', 'Language and Mind', 12, 0, 'senior', 'wordlist', 'elective2', 'U2', 'the corresponding image', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'trick', 'n./v.', '/trɪk/', '诀窍;错觉;欺骗', 'The trick was that a similar-sounding word was added to confuse them.', '诀窍在于加入了一个发音相近的词来迷惑他们。', 'Language and Mind', 13, 0, 'senior', 'wordlist', 'elective2', 'U2', 'the trick was that', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'distracting', 'adj.', '/dɪˈstræktɪŋ/', '使分心的;干扰的', 'Bilingual speakers were better at ignoring the distracting words.', '双语者更善于忽略那些干扰的词。', 'Language and Mind', 14, 0, 'senior', 'wordlist', 'elective2', 'U2', 'the distracting word', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'target', 'n.', '/ˈtɑːɡɪt/', '目标;对象;靶子', 'Each list contained one target word and several similar ones.', '每张词表都含有一个目标词和几个相似的词。', 'Language and Mind', 15, 0, 'senior', 'wordlist', 'elective2', 'U2', 'the target word', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'versus', 'prep.', '/ˈvɜːsəs/', '与……相对;对比', 'The test compared simple pairs such as ''candy'' versus ''candle''.', '测试比较了像 candy 与 candle 这样的简单词对。', 'Language and Mind', 16, 0, 'senior', 'wordlist', 'elective2', 'U2', 'candy versus candle', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'filter', 'v./n.', '/ˈfɪltə(r)/', '过滤;筛除;滤器', 'A good listener can filter out sounds that do not matter.', '好的倾听者能过滤掉无关紧要的声音。', 'Language and Mind', 17, 0, 'senior', 'wordlist', 'elective2', 'U2', 'filter out', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'considerable', 'adj.', '/kənˈsɪdərəbl/', '相当大的;相当多的', 'Speaking two languages has considerable benefits for the brain.', '会说两种语言对大脑有相当大的好处。', 'Language and Mind', 18, 0, 'senior', 'wordlist', 'elective2', 'U2', 'considerable benefits', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'bilingual', 'adj.', '/baɪˈlɪŋɡwəl/', '会说两种语言的;双语的', 'Bilingual people can switch between two languages with ease.', '双语者能够轻松地在两种语言之间切换。', 'Language and Mind', 19, 0, 'senior', 'wordlist', 'elective2', 'U2', 'bilingual children', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'cell', 'n.', '/sel/', '细胞', 'Learning a language challenges the grey cells in our brain.', '学习语言会锻炼我们大脑里的灰色细胞。', 'Language and Mind', 20, 0, 'senior', 'wordlist', 'elective2', 'U2', 'grey cells', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'significantly', 'adv.', '/sɪɡˈnɪfɪkəntli/', '显著地;明显地', 'Language can significantly shape the way we see the world.', '语言能显著地塑造我们看待世界的方式。', 'Language and Mind', 21, 0, 'senior', 'wordlist', 'elective2', 'U2', 'significantly shape', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'recognise', 'v.', '/ˈrekəɡnaɪz/', '识别;辨认;承认', 'Russian speakers recognise shades of blue faster than English speakers.', '俄语者比英语者更快地辨认出蓝色的深浅。', 'Language and Mind', 22, 0, 'senior', 'wordlist', 'elective2', 'U2', 'recognise the difference', '美式拼 recognize;美音 /ˈrekəɡnaɪz/', 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'differ', 'v.', '/ˈdɪfə(r)/', '不同;相异', 'Languages differ in how they describe the same accident.', '各种语言在描述同一场意外时各不相同。', 'Language and Mind', 23, 0, 'senior', 'wordlist', 'elective2', 'U2', 'differ in', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'structure', 'n.', '/ˈstrʌktʃə(r)/', '结构;构造;体系', 'The structure of a language can mirror how its speakers think.', '一门语言的结构能映照出使用者的思维方式。', 'Language and Mind', 24, 0, 'senior', 'wordlist', 'elective2', 'U2', 'brain structure', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'reality', 'n.', '/riˈæləti/', '现实;实际;真实情况', 'Each language seems to create its own kind of reality.', '每种语言似乎都创造出自己的一种现实。', 'Language and Mind', 25, 0, 'senior', 'wordlist', 'elective2', 'U2', 'create a reality', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'affect', 'v.', '/əˈfekt/', '影响;作用于', 'The words we use may affect the decisions we make.', '我们使用的词语可能影响我们做出的决定。', 'Language and Mind', 26, 0, 'senior', 'wordlist', 'elective2', 'U2', 'affect our decisions', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'blame', 'n./v.', '/bleɪm/', '责备;归咎;责任', 'Some languages make us less likely to blame a person for an accident.', '有些语言让我们不太会把意外归咎于某个人。', 'Language and Mind', 27, 0, 'senior', 'wordlist', 'elective2', 'U2', 'blame somebody', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'soul', 'n.', '/səʊl/', '灵魂;心灵;精神', 'To have a second language, it is said, is to have a second soul.', '人们说,拥有第二语言就是拥有第二个灵魂。', 'Language and Mind', 28, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a second soul', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'elsewhere', 'adv.', '/ˌelsˈweə(r)/', '在别处;到别处', 'It is not really about how people elsewhere think, but about how you think.', '这其实无关别处的人如何思考,而关乎你如何思考。', 'Language and Mind', 29, 0, 'senior', 'wordlist', 'elective2', 'U2', 'people elsewhere', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'brilliant', 'adj.', '/ˈbrɪliənt/', '聪明的;杰出的;明亮的', 'The variety of languages reveals how brilliant the human mind is.', '语言的多样性揭示了人类心智多么卓越。', 'Language and Mind', 30, 0, 'senior', 'wordlist', 'elective2', 'U2', 'brilliant mind', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'effect', 'n.', '/ɪˈfekt/', '影响;效果;结果', 'Language can have early effects on a child''s thinking.', '语言会对儿童的思维产生早期影响。', 'Language and Mind', 31, 0, 'senior', 'wordlist', 'elective2', 'U2', 'early effects', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'impact', 'n.', '/ˈɪmpækt/', '影响;冲击;撞击', 'Small word choices can have a real impact on our judgement.', '细小的用词选择能对我们的判断产生真实的影响。', 'Language and Mind', 32, 0, 'senior', 'wordlist', 'elective2', 'U2', 'have an impact', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'flexible', 'adj.', '/ˈfleksəbl/', '灵活的;可变通的;柔韧的', 'Our minds are flexible enough to learn many languages.', '我们的心智足够灵活,能学会许多种语言。', 'Language and Mind', 33, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a flexible mind', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'variety', 'n.', '/vəˈraɪəti/', '多样;种类;变化', 'There is a beautiful variety of languages in the world.', '世界上有着丰富多样的语言。', 'Language and Mind', 34, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a variety of', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'distinguish', 'v.', '/dɪˈstɪŋɡwɪʃ/', '区分;辨别;使有别于', 'Even unborn babies can distinguish between two languages.', '甚至尚未出生的婴儿也能区分两种语言。', 'Language and Mind', 35, 0, 'senior', 'wordlist', 'elective2', 'U2', 'distinguish between', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'mindset', 'n.', '/ˈmaɪndset/', '思维方式;心态', 'Learning a language can give you a more global mindset.', '学习一门语言能让你拥有更全球化的思维方式。', 'Language and Mind', 36, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a global mindset', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'hypothesis', 'n.', '/haɪˈpɒθəsɪs/', '假说;假设', 'The famous hypothesis claims that language shapes thought.', '那个著名的假说认为语言塑造思维。', 'Language and Mind', 37, 0, 'senior', 'wordlist', 'elective2', 'U2', 'the Sapir-Whorf hypothesis', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'linguist', 'n.', '/ˈlɪŋɡwɪst/', '语言学家', 'Many linguists are working hard to save dying languages.', '许多语言学家正在努力拯救濒临消亡的语言。', 'Language and Mind', 38, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a team of linguists', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'acquisition', 'n.', '/ˌækwɪˈzɪʃn/', '习得;获得;取得', 'Input and output both matter in language acquisition.', '在语言习得中,输入和输出都很重要。', 'Language and Mind', 39, 0, 'senior', 'wordlist', 'elective2', 'U2', 'language acquisition', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'perceive', 'v.', '/pəˈsiːv/', '感知;察觉;看待', 'The language we speak may change how we perceive the world.', '我们所说的语言可能改变我们感知世界的方式。', 'Language and Mind', 40, 0, 'senior', 'wordlist', 'elective2', 'U2', 'perceive the world', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'determine', 'v.', '/dɪˈtɜːmɪn/', '决定;查明;确定', 'Some argue that language can even determine our thoughts.', '有人主张语言甚至能决定我们的思想。', 'Language and Mind', 41, 0, 'senior', 'wordlist', 'elective2', 'U2', 'determine our thoughts', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'demanding', 'adj.', '/dɪˈmɑːndɪŋ/', '要求高的;费力的', 'The students followed a demanding language-learning programme.', '学生们参加了一个要求很高的语言学习项目。', 'Language and Mind', 42, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a demanding programme', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'switch', 'v./n.', '/swɪtʃ/', '转换;切换;开关', 'The effort to switch between languages strengthens the brain.', '在语言之间切换所付出的努力能强化大脑。', 'Language and Mind', 43, 0, 'senior', 'wordlist', 'elective2', 'U2', 'switch between', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'attention', 'n.', '/əˈtenʃn/', '注意;关注;注意力', 'Different languages make us pay attention to different things.', '不同的语言让我们关注不同的事物。', 'Language and Mind', 44, 0, 'senior', 'wordlist', 'elective2', 'U2', 'pay attention to', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'endangered', 'adj.', '/ɪnˈdeɪndʒəd/', '濒危的;有灭绝危险的', 'There are many endangered languages in Australia today.', '如今澳大利亚有许多濒危语言。', 'Language and Mind', 45, 0, 'senior', 'wordlist', 'elective2', 'U2', 'endangered languages', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'predict', 'v.', '/prɪˈdɪkt/', '预测;预言', 'Experts predict that half of all languages may disappear.', '专家预测,所有语言中或许有一半会消失。', 'Language and Mind', 46, 0, 'senior', 'wordlist', 'elective2', 'U2', 'predict that', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'have an impact on', 'phr.', '/hæv ən ˈɪmpækt ɒn/', '对……有影响', 'The words people use can have an impact on how they feel.', '人们使用的词语能对他们的感受产生影响。', 'Language and Mind', 47, 0, 'senior', 'wordlist', 'elective2', 'U2', 'have an impact on', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (11, 'second language', 'phr.', '/ˈsekənd ˈlæŋɡwɪdʒ/', '第二语言;外语', 'A second language opens up a new way of looking at the world.', '第二语言开启了一种看待世界的新方式。', 'Language and Mind', 48, 0, 'senior', 'wordlist', 'elective2', 'U2', 'a second language', NULL, 'sufe');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2');
DELETE FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('se2u2.01', '①主语从句(句首):连接词选择', 'A2', 11, '上外版选择性必修第二册 U2 — 名词性从句放句首作主语时:从句完整且陈述事实用 that;表''是否''的疑问用 whether(不用 if);从句缺主语或宾语(=所…的事物)用 what;问方式/程度用 how;问原因用 why。', 1, 'elective2', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('se2u2.02', '②it 作形式主语:真正主语后置', 'A2', 11, '上外版选择性必修第二册 U2 — 用 it 作形式主语、真正的主语从句后置:It is + 形容词/名词/过去分词 + that(陈述)/whether(是否)/what·how·why(疑问词)从句。如 It is true that… / It is unknown whether… / It is amazing how…。', 2, 'elective2', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('se2u2.03', '③表语从句(系动词 be 之后)', 'A2', 11, '上外版选择性必修第二册 U2 — 名词性从句跟在系动词 be 后作表语;连接词由主语名词与从句意义决定:fact/truth/idea/belief/point + that;question/problem + whether;The reason is that…;That is why…;主语为 this/that/all、从句缺成分 + what。', 3, 'elective2', 'U2', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ our language really shapes our thoughts has interested scientists for years."', 'Whether', 'What', 'If', 'Because', 'A', '句首主语从句表''是否''的待解疑问 → whether(不用 if);从句完整,what 多余。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ surprised the researchers most was the speed of the answers."', 'That', 'What', 'Whether', 'It', 'B', '从句缺主语(____ surprised…)→ what(=the thing that)。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ language can shape thought is now widely accepted by experts."', 'What', 'Whether', 'That', 'How', 'C', '从句完整、陈述被接受的事实 → that。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ languages describe colours differs from culture to culture."', 'What', 'That', 'Whether', 'How', 'D', '''differs from culture to culture''指方式不同 → how。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ babies can tell two languages apart was tested in the study."', 'Whether', 'What', 'That', 'If', 'A', '研究检验的是''能否''这一疑问 → whether。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ each language asks us to notice can differ a great deal."', 'That', 'What', 'Whether', 'Why', 'B', '从句缺宾语(asks us to notice ____)→ what。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ every healthy child can learn a language is simply a fact."', 'What', 'How', 'That', 'Whether', 'C', '从句完整、点明它''是一个事实''→ that。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ quickly we name a colour varies from language to language."', 'What', 'Whether', 'That', 'How', 'D', '''how quickly''表程度 → how。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ she discovered about colour words changed the debate."', 'What', 'That', 'Whether', 'How', 'A', '从句缺宾语(discovered ____)→ what。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ speaking two languages slows the brain was the real question."', 'What', 'Whether', 'That', 'If', 'B', '''was the real question''指''是否''的疑问 → whether(不用 if)。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ no two languages divide the world alike is well known."', 'Whether', 'What', 'That', 'How', 'C', '从句完整、是众所周知的事实 → that。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ we call ''blue'' may not exist in another language."', 'That', 'Whether', 'Why', 'What', 'D', '从句缺宾语(we call ____ ''blue'')→ what。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ a dying language can be saved depends on its young speakers."', 'Whether', 'What', 'That', 'If', 'A', '''depends on''后接''能否''的疑问 → whether。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ words can shape our feelings is no surprise to linguists."', 'What', 'That', 'Whether', 'How', 'B', '从句完整、是''不足为奇''的事实 → that。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ the speaker described was a simple colour experiment."', 'That', 'Whether', 'What', 'How', 'C', '从句缺宾语(described ____)→ what。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ varies from person to person is the way they picture time."', 'How', 'That', 'Whether', 'What', 'D', '从句缺主语(____ varies…)→ what。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ colour words affect memory was the focus of the test."', 'Whether', 'What', 'That', 'Why', 'A', '测试的焦点是''是否''这一疑问 → whether。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ matters is not where others live but how you think."', 'That', 'What', 'Whether', 'Why', 'B', '从句缺主语(____ matters)→ what。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ the human mind is so flexible is clear from its love of language."', 'What', 'Whether', 'That', 'How', 'C', '从句完整、是''显而易见''的事实 → that。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.01'), '"____ some small languages disappear so fast is still a mystery."', 'That', 'What', 'Whether', 'Why', 'D', '''is still a mystery''指未解的原因 → why。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is true ____ language can change the way we see colour."', 'that', 'whether', 'what', 'how', 'A', 'It is true 后接陈述事实的主语从句 → that。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It remains unknown ____ a dying language can ever be revived."', 'that', 'whether', 'what', 'why', 'B', 'remains unknown 后是''能否''的疑问 → whether。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is amazing ____ quickly Russian speakers spot light blue."', 'that', 'what', 'how', 'whether', 'C', '''how quickly''表程度 → how。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is no surprise ____ bilingual brains often stay sharper."', 'whether', 'what', 'why', 'that', 'D', 'It is no surprise 后接陈述事实 → that。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is doubtful ____ language alone can determine our thoughts."', 'whether', 'that', 'how', 'what', 'A', 'doubtful 表怀疑''是否'' → whether。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is hard to say ____ makes one language die before another."', 'that', 'what', 'whether', 'how', 'B', '从句缺主语(____ makes…)→ what。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is well known ____ no two languages divide the world alike."', 'whether', 'what', 'that', 'why', 'C', 'well known 后接公认的事实 → that。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is still unclear ____ babies can tell two languages apart."', 'that', 'what', 'how', 'whether', 'D', 'unclear 表不确定''能否'' → whether。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is interesting ____ differently languages treat the same event."', 'how', 'that', 'what', 'whether', 'A', '''how differently''表程度/方式 → how。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is widely accepted ____ thought and language influence each other."', 'whether', 'that', 'what', 'why', 'B', 'widely accepted 后接被接受的事实 → that。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is not always obvious ____ a language asks us to pay attention to."', 'that', 'whether', 'what', 'how', 'C', '从句缺宾语(pay attention to ____)→ what。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is a real mystery ____ so many languages are vanishing at once."', 'that', 'what', 'whether', 'why', 'D', 'a mystery 指未解的原因 → why。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is surprising ____ a single kind sentence can lift a whole day."', 'that', 'whether', 'what', 'how', 'A', 'surprising 后陈述令人惊讶的事实 → that。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It matters little ____ you call it ''goluboy'' or ''siniy''."', 'that', 'whether', 'what', 'why', 'B', '''whether…or…''表''不论是否'' → whether。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is fascinating ____ the mind handles two languages at the same time."', 'that', 'what', 'how', 'whether', 'C', '指大脑处理的''方式'' → how。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is often forgotten ____ some thoughts need no language at all."', 'whether', 'what', 'why', 'that', 'D', 'forgotten 后接被遗忘的事实 → that。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is worth asking ____ we think the way that we do."', 'why', 'that', 'what', 'how', 'A', 'asking 后问''为什么这样想'' → why。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is clear ____ our first language leaves a deep mark on us."', 'whether', 'that', 'what', 'how', 'B', 'It is clear 后接清楚的事实 → that。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is uncertain ____ saving a script can save a spoken language."', 'that', 'what', 'whether', 'why', 'C', 'uncertain 表不确定''能否'' → whether。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.02'), '"It is no wonder ____ learning a language reshapes the brain."', 'whether', 'what', 'how', 'that', 'D', 'no wonder 后陈述''难怪''的事实 → that。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The truth is ____ language and thought shape each other."', 'that', 'whether', 'what', 'why', 'A', '主语 truth、从句陈述事实 → 表语从句用 that。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The real question is ____ language shapes thought or the other way round."', 'that', 'whether', 'what', 'how', 'B', '主语 question、表''是否/哪一种'' → whether。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"What still puzzles me is ____ a baby learns to speak so quickly."', 'that', 'what', 'how', 'why', 'C', '表语从句指学说话的''方式'' → how。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"One common belief is ____ any language can be mastered with practice."', 'whether', 'what', 'why', 'that', 'D', '主语 belief、从句陈述内容 → that。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The reason is ____ their language makes them notice such details."', 'that', 'why', 'what', 'how', 'A', '''The reason is + 表语从句''用 that(不用 why)。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The problem is ____ we can ever fully translate one language into another."', 'that', 'whether', 'what', 'how', 'B', '主语 problem、表''能否''的疑问 → whether。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"His greatest fear is ____ his mother tongue will die out."', 'whether', 'what', 'that', 'why', 'C', '表语从句陈述所担心的内容 → that。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"That is ____ Russian speakers react to shades of blue so fast."', 'that', 'what', 'how', 'why', 'D', '''That is why…''说明原因 → why。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The first thing she noticed was ____ the two words sounded almost alike."', 'that', 'whether', 'what', 'how', 'A', '表语从句陈述她注意到的事实 → that。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"This is ____ language can quietly do to our thinking."', 'that', 'what', 'whether', 'why', 'B', '从句缺宾语(do ____ to our thinking)→ what。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The point is ____ small words can steer big decisions."', 'whether', 'what', 'that', 'why', 'C', '主语 point、从句陈述要点 → that。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"What matters most is ____ you pay attention to, not where you live."', 'that', 'whether', 'how', 'what', 'D', '从句缺宾语(pay attention to ____)→ what。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The mystery is ____ so many languages are disappearing today."', 'why', 'that', 'what', 'whether', 'A', '主语 mystery、追问原因 → why。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"Her firm belief is ____ every language opens a new window on the world."', 'whether', 'that', 'what', 'how', 'B', '主语 belief、从句陈述信念 → that。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The strange thing is ____ we rarely ask why we think as we do."', 'whether', 'what', 'that', 'why', 'C', '从句完整、陈述''奇怪的事实'' → that。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The whole point of her talk was ____ language shapes us all."', 'whether', 'what', 'how', 'that', 'D', '从句陈述演讲要点 → that。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The open question is ____ thought can exist without any words."', 'whether', 'that', 'what', 'why', 'A', '主语 question、表''能否''的疑问 → whether。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The best part is ____ learning a language actually reshapes the brain."', 'whether', 'that', 'what', 'how', 'B', '从句陈述''最棒的部分''这一事实 → that。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"His only doubt is ____ a written record can keep a language alive."', 'that', 'what', 'whether', 'why', 'C', '主语 doubt、表''能否''的疑问 → whether。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2' AND code='se2u2.03'), '"The amazing fact is ____ no single language can capture every idea."', 'whether', 'what', 'why', 'that', 'D', '主语 fact、从句陈述事实 → that。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='sufe' AND volume='elective2' AND unit='U2';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Does Language Shape the Mind?', 'One of the oldest questions about language is simple to ask but hard to answer: does the language we speak change the way we think? A scholar named Benjamin Whorf once went very far. He claimed that language does not only influence thought, but actually decides it. In its strongest form, this idea has been turned down by many psychologists. After all, it is not hard to find thoughts that need no words at all. A baby, a dog, or a musician can clearly think without sentences. Yet a softer form of the idea is still hard to argue against. Few people would deny that the language we use can, at least a little, colour the way we see the world. So most experts today take a middle view. Language is probably not a prison for the mind, but it is more like a pair of glasses. It does not decide what is out there, but it can gently change what we notice first and what we easily forget.', '议论·语言与思维之争', 169, '[{"q":"What did Benjamin Whorf claim in his strongest view?","answer":"A","options":["Language completely decides how we think.","Language has no effect on thought at all.","Thought always comes before any language.","Words and thoughts are totally unrelated."],"explanation":"原文 Whorf 称语言''determines thought''的转述,即语言完全决定思维。"},{"q":"Why do many psychologists reject the strongest form?","answer":"B","options":["Because babies are unable to think at all.","Because people can clearly think without using words.","Because language is far too simple to study.","Because no one studies language today."],"explanation":"原文''thoughts that need no words''(婴儿、狗、音乐家)说明能无词而思 → 否定最强版本。"},{"q":"What middle view do most experts hold now?","answer":"A","options":["Language gently shapes what we notice, not what exists.","Language fully controls outside reality.","Language has zero influence on the mind.","Language is a complete prison for thought."],"explanation":"末段''a pair of glasses…gently change what we notice''的转述。"}]'::jsonb, '[{"word":"influence","cn":"影响"},{"word":"psychologist","cn":"心理学家"},{"word":"deny","cn":"否认"}]'::jsonb, 2, 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'The Russian Blues', 'Not every language cuts up the rainbow in the same way. English has one main word for blue, whether the sky is pale or deep. Russian is different. It has no single word that simply means ''blue''. Instead, Russian speakers must choose between ''goluboy'' for light blue and ''siniy'' for dark blue, just as English speakers choose between red and pink. Does this habit change anything real? Scientists decided to test it. They showed people two squares of colour and asked, as fast as possible, whether the shades were the same or different. Russian speakers were quicker when one square was light blue and the other dark blue, because their language forces them to mark that border every day. English speakers, who file both under a single word, were a little slower. The study suggests that the words we grow up with can train our eyes without our noticing. We are not born seeing colour this way; our language quietly teaches us where one shade ends and the next begins.', '说明·颜色词与感知', 170, '[{"q":"How does Russian treat the colour blue?","answer":"B","options":["It has one single word for every shade of blue.","It uses separate words for light and dark blue.","It has no word for blue at all.","It uses the same word as it does for red."],"explanation":"原文''goluboy''与''siniy''分指浅蓝、深蓝的转述。"},{"q":"What were people asked to do in the test?","answer":"C","options":["Name every colour in the room.","Paint two blue squares by hand.","Judge quickly whether two shades matched.","Translate the Russian colour words."],"explanation":"原文''asked…whether the shades were the same or different''的转述。"},{"q":"What does the study suggest about language and colour?","answer":"D","options":["People are born seeing all colours the same way.","Colour words have no effect on the eyes.","Russian speakers cannot see dark blue.","Our language can train how fast we tell shades apart."],"explanation":"末段''words…can train our eyes''的转述。"}]'::jsonb, '[{"word":"rainbow","cn":"彩虹"},{"word":"pale","cn":"浅的;淡的"},{"word":"shade","cn":"色度;浓淡"}]'::jsonb, 2, 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Whose Fault Was It?', 'Imagine a waiter who trips, and a glass falls and breaks. How would you describe it? In English, we usually say, ''He broke the glass,'' naming the person even when nobody meant any harm. Spanish speakers often prefer a different shape: ''The glass broke,'' as if the object had acted on its own. When the event is a pure accident, many languages avoid pointing at a person at all. This small difference may do more than it seems. In one study, people watched the same short films of accidents. Later, English speakers were better at remembering who had been involved, while Spanish speakers remembered the action more than the actor. Their languages had quietly told them what to keep in mind. Some researchers think this can even touch ideas like blame and punishment. If your language always names a doer, you may be quicker to ask whose fault it was. Language does not force us to judge, but it can lean us, softly, in one direction rather than another.', '说明·描述意外与归咎', 169, '[{"q":"How do English and Spanish often differ when describing an accident?","answer":"A","options":["English names the person; Spanish stresses the event itself.","Both of them always blame the person.","Spanish always names the guilty person.","Neither one mentions the accident."],"explanation":"原文''He broke the glass''对''The glass broke''的对比转述。"},{"q":"What did the two groups remember differently after the films?","answer":"B","options":["Both groups forgot the films completely.","English speakers recalled who was involved more easily.","Spanish speakers recalled the person better.","Nobody remembered any action."],"explanation":"原文''English speakers were better at remembering who had been involved''的转述。"},{"q":"What larger idea might this difference affect?","answer":"C","options":["The price of the broken glasses.","The speed of the waiters.","How readily we assign blame.","The colour of the short films."],"explanation":"原文''ideas like blame and punishment…quicker to ask whose fault''的转述。"}]'::jsonb, '[{"word":"trip","cn":"绊倒"},{"word":"actor","cn":"行为者;做事的人"},{"word":"punishment","cn":"惩罚"}]'::jsonb, 2, 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'For a Better Brain', 'Learning a new language can feel a little like magic, but the real magic happens inside the brain. Researchers in Sweden once studied two groups of students. One group began a hard language course, while the other studied medicine and science. Both groups had brain scans at the start and again three months later. Only in the language learners did the scans show clear changes in brain structure. In another study, people were asked to listen to a word and pick the matching picture from four. The trick was that one picture had a name that sounded close to the target, such as ''candy'' and ''candle''. People who spoke two languages found it easier to ignore the distracting choice, while those who spoke only one had to work harder. Other research links speaking two languages to a later start of memory disease, sometimes by several years. None of this means a bilingual person is simply ''smarter''. It means the daily effort of switching between languages gives the brain a healthy, lasting workout.', '说明·双语与大脑', 172, '[{"q":"What did the Swedish brain scans reveal?","answer":"D","options":["Both groups'' brains changed in the same way.","No brain changed at all in three months.","Only the science students'' brains changed.","Only the language learners'' brain structure changed."],"explanation":"原文''brain structure changed only in the language learning group''的转述。"},{"q":"Why was the ''candy/candle'' part tricky?","answer":"A","options":["One picture''s name sounded like the target word.","The pictures were too dark to see.","There were no pictures shown at all.","The words were in a foreign script."],"explanation":"原文''a distracting word…sounds similar to the target word''的转述。"},{"q":"What does the writer conclude about bilingual brains?","answer":"B","options":["Bilingual people are always far cleverer.","Switching languages keeps the brain fit, not simply smarter.","Two languages clearly harm the brain.","Language has no effect on memory."],"explanation":"末段''does make your brain healthier…a workout''的转述,而非简单''更聪明''。"}]'::jsonb, '[{"word":"magic","cn":"魔法;奇迹"},{"word":"medicine","cn":"医学;药"},{"word":"workout","cn":"锻炼"}]'::jsonb, 2, 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Languages Are Disappearing', 'You probably know that many animals and plants are in danger, but languages can vanish too. There are around seven thousand living languages today, yet experts warn that more than half could be gone by the end of this century. When the last speaker of a language dies, something more than words is lost. Each language carries its own stories, jokes, songs, and ways of naming the plants and seasons around it. Much of that knowledge has never been written down, so it simply disappears with the final voice. In Australia, for example, hundreds of languages were once spoken, but only a small number are still used every day. For many communities, their language sits at the very heart of who they are. It links them to their land, their history, and their elders. That is why linguists travel to far and quiet places, recording speakers and helping younger people learn. Saving a language is hard work, but it keeps a whole way of seeing the world alive.', '说明·濒危语言', 168, '[{"q":"What warning do experts give about today''s languages?","answer":"C","options":["All of them are now perfectly safe.","They will all soon become English.","Over half may disappear within this century.","None of them has any speakers left."],"explanation":"原文''more than half will have disappeared by the end of the century''的转述。"},{"q":"Why is losing a language more than losing words?","answer":"D","options":["Only its spelling rules are lost.","Words are very easy to replace.","Nothing of value is actually lost.","Unwritten knowledge and stories vanish along with it."],"explanation":"原文''much knowledge goes with it…never been written down''的转述。"},{"q":"Why do linguists travel to far and quiet places?","answer":"A","options":["To record speakers and help young people learn.","To sell printed dictionaries.","To stop people from speaking.","To search for new animals."],"explanation":"原文''linguists who are studying and trying to save…languages''的转述。"}]'::jsonb, '[{"word":"vanish","cn":"消失"},{"word":"community","cn":"社区;群体"},{"word":"elder","cn":"长者;前辈"}]'::jsonb, 2, 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (11, 'Time, Space and Words', 'Languages can shape something as basic as how we picture time. In English, people often place time on a line that runs from left to right: last week is behind us, and next week lies ahead. Speakers of some Chinese expressions, by contrast, may also think of time as moving up and down, with an earlier month ''above'' and a later month ''below''. Neither way is right or wrong, but each can guide the pictures that form in our minds. Space works in a similar way. A few languages have no words for ''left'' and ''right'' at all. Instead, their speakers always use north, south, east, and west, even indoors. To do this, they must keep track of direction all the time, and they become remarkably good at it. A child raised with such a language can point to the north without thinking. These habits show how a language can quietly train the mind, shaping not only the words we use but the very maps we carry inside our heads.', '说明·时间与空间的语言', 170, '[{"q":"How do many English speakers picture time?","answer":"B","options":["As a circle with no beginning.","As a line running from left to right.","As something moving up and down.","As standing completely still."],"explanation":"原文''a line…left-right terms…next week lies ahead''的转述。"},{"q":"What is special about languages without ''left'' and ''right''?","answer":"C","options":["Their speakers cannot describe space at all.","They never mention any direction.","Their speakers rely on compass directions instead.","They use only the words ''up'' and ''down''."],"explanation":"原文''always use north, south, east, and west''的转述。"},{"q":"What do these examples show about language?","answer":"D","options":["It has no link to the way we think.","It only changes our spelling habits.","It makes people forget all directions.","It can quietly train how the mind maps the world."],"explanation":"末段''quietly train the mind…maps we carry inside our heads''的转述。"}]'::jsonb, '[{"word":"ahead","cn":"在前面;向前"},{"word":"direction","cn":"方向"},{"word":"remarkably","cn":"非凡地;惊人地"}]'::jsonb, 2, 'elective2', 'U2', 'sufe');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='sufe' AND volume='elective2' AND unit='U2';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U2', 'My First Week Abroad', 'When I arrived in London as an exchange student, I quickly learned that having a (1)____ language was like owning a second pair of eyes. At first, switching between Chinese and English was (2)____, and my head felt tired by lunchtime. My host mother told me not to (3)____ myself for every small mistake. She said that the daily effort to (4)____ between two languages would actually make my brain stronger. Slowly, I began to (5)____ sounds that I had never noticed before. What surprised me most was (6)____ a single kind sentence from a stranger could lift my whole day. I started to keep a (7)____ in which I wrote down new words every evening. Reading it later, I could clearly (8)____ how much progress I had made. By the end of the week, English no longer felt like a wall but like a door that had begun to (9)____ up. The (10)____ is that learning a language slowly changes the way you see everything.', 166, 2, '[{"q":"1","answer":"A","options":["second","quiet","empty","silent"],"explanation":"a second language 第二语言。"},{"q":"2","answer":"B","options":["easy","demanding","silent","cheap"],"explanation":"下文''head felt tired''→ demanding 费力的。"},{"q":"3","answer":"C","options":["praise","thank","blame","help"],"explanation":"not to blame myself 不要责备自己。"},{"q":"4","answer":"D","options":["sleep","pay","sell","switch"],"explanation":"switch between two languages 在两种语言间切换。"},{"q":"5","answer":"A","options":["recognise","forget","lose","drop"],"explanation":"recognise sounds 辨认出声音。"},{"q":"6","answer":"B","options":["why","that","where","whether"],"explanation":"表语从句陈述事实 → that。"},{"q":"7","answer":"C","options":["ticket","price","journal","map"],"explanation":"keep a journal 记日志。"},{"q":"8","answer":"D","options":["hide","lose","sell","see"],"explanation":"see how much progress 看出进步。"},{"q":"9","answer":"A","options":["open","break","fall","shut"],"explanation":"open up 打开;拓展。"},{"q":"10","answer":"B","options":["price","truth","noise","weather"],"explanation":"The truth is that… 表语从句结构。"}]'::jsonb, 1, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U2', 'Grandma''s Words', 'My grandmother speaks an old village (1)____ that very few young people still use. When I was small, I thought it sounded strange, and I could not (2)____ many of her words. Now I understand that her way of speaking carries (3)____ that no textbook could ever hold. Each phrase is tied to the fields, the festivals, and the (4)____ of our family. Sadly, languages like hers are (5)____, and experts (6)____ that many will disappear within fifty years. When the last speaker is gone, much local (7)____ goes with them. That is (8)____ I have decided to record my grandmother. Every weekend I sit with her and ask her to tell old stories. The (9)____ is whether young people like me can keep these words alive. I believe even a small effort can have a real (10)____ on the future of a language.', 144, 2, '[{"q":"1","answer":"C","options":["machine","ticket","dialect","garden"],"explanation":"an old dialect 一种古老方言。"},{"q":"2","answer":"D","options":["sell","throw","cook","follow"],"explanation":"could not follow her words 听不懂她的话。"},{"q":"3","answer":"A","options":["knowledge","noise","money","traffic"],"explanation":"carries knowledge 承载知识。"},{"q":"4","answer":"B","options":["prices","stories","engines","tickets"],"explanation":"the stories of our family 家族的故事。"},{"q":"5","answer":"C","options":["modern","cheap","endangered","loud"],"explanation":"languages are endangered 语言濒危。"},{"q":"6","answer":"D","options":["forget","sell","hide","predict"],"explanation":"experts predict that… 专家预测。"},{"q":"7","answer":"A","options":["knowledge","money","noise","weather"],"explanation":"much local knowledge 许多地方知识。"},{"q":"8","answer":"B","options":["what","why","whether","how"],"explanation":"That is why… 表语从句说明原因。"},{"q":"9","answer":"C","options":["price","weather","question","noise"],"explanation":"The question is whether… 问题在于能否。"},{"q":"10","answer":"D","options":["price","noise","holiday","impact"],"explanation":"have an impact on 对……有影响。"}]'::jsonb, 2, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U2', 'How English Changed My World', 'Before I learned English well, I thought a language was just a set of words for naming things. Now I (1)____ that it is much more than that. Learning English has slowly changed the way I (2)____ the world. For example, English made me notice (3)____ differently people can describe the very same event. It also taught me that there is more than one (4)____ behind every story. Sometimes I read an English poem and feel a kind of (5)____ deep inside me, as if the words were ringing a bell. My teacher says that to have a second language is to gain a second (6)____. That idea once sounded strange, but now I fully (7)____ it. The most (8)____ part is that my Chinese has improved too, because comparing the two languages makes each one clearer. (9)____ matters is not which language is better, but how each one opens a new window. The (10)____ is that every language I learn makes me a slightly different person.', 167, 2, '[{"q":"1","answer":"A","options":["realise","forget","doubt","deny"],"explanation":"now I realise 如今我意识到。"},{"q":"2","answer":"B","options":["sell","perceive","cook","throw"],"explanation":"the way I perceive the world 我感知世界的方式。"},{"q":"3","answer":"C","options":["why","whether","how","where"],"explanation":"notice how differently… 名词性从句,表程度/方式用 how。"},{"q":"4","answer":"D","options":["price","ticket","engine","reality"],"explanation":"more than one reality 不止一种现实。"},{"q":"5","answer":"A","options":["resonance","hunger","traffic","silence"],"explanation":"feel a kind of resonance 感到共鸣。"},{"q":"6","answer":"B","options":["coin","soul","road","clock"],"explanation":"a second soul 第二个灵魂。"},{"q":"7","answer":"C","options":["refuse","doubt","accept","ignore"],"explanation":"now I fully accept it 如今我完全接受。"},{"q":"8","answer":"D","options":["boring","silent","empty","surprising"],"explanation":"the most surprising part 最令人惊讶的部分。"},{"q":"9","answer":"A","options":["What","That","Whether","Why"],"explanation":"主语从句缺主语 → What matters is…。"},{"q":"10","answer":"B","options":["price","lesson","noise","weather"],"explanation":"The lesson is that… 表语从句结构。"}]'::jsonb, 3, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U2', 'Should We Learn More Than English?', 'Last week our class held a debate on a simple question: is English the only foreign language (1)____ learning? Those who said yes argued that English is already used in business, science, and (2)____ communication around the world. Their (3)____ was that one global language is enough for everyone. The other side, however, made a (4)____ point. They said that every language is a key that (5)____ a different world for us. (6)____ we learn French, Japanese, or Arabic, each new language lets us reach more people and (7)____ more cultures. One girl said that to give up other languages would be to make our minds (8)____. In the end, most of us agreed (9)____ English alone is not enough. The real (10)____ is whether our school can offer more language courses in the future.', 135, 2, '[{"q":"1","answer":"C","options":["busy","afraid","worth","ready"],"explanation":"worth learning 值得学习。"},{"q":"2","answer":"D","options":["silent","empty","cheap","international"],"explanation":"international communication 国际交流。"},{"q":"3","answer":"A","options":["belief","price","noise","engine"],"explanation":"Their belief was that… 他们的看法是。"},{"q":"4","answer":"B","options":["silent","strong","empty","sleepy"],"explanation":"made a strong point 提出有力观点。"},{"q":"5","answer":"C","options":["closes","breaks","unlocks","sells"],"explanation":"a key that unlocks a world 开启世界的钥匙。"},{"q":"6","answer":"D","options":["That","What","Why","Whether"],"explanation":"whether…or… 不论……还是。"},{"q":"7","answer":"A","options":["appreciate","forget","lose","sell"],"explanation":"appreciate more cultures 欣赏更多文化。"},{"q":"8","answer":"B","options":["richer","smaller","louder","faster"],"explanation":"make our minds smaller 让头脑变得狭小。"},{"q":"9","answer":"C","options":["whether","what","that","why"],"explanation":"agreed that… 宾语从句陈述观点 → that。"},{"q":"10","answer":"D","options":["price","weather","noise","question"],"explanation":"The real question is whether… 真正的问题在于能否。"}]'::jsonb, 4, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U2', 'The Power of Kind Words', 'What was the most beautiful thing someone ever said to you? It could have been a single sentence that (1)____ your whole day, or even your year. There is far more to language than spelling and (2)____. Words carry a real power. The kind things people say to us, and the thoughts we hear in our own (3)____, slowly add up and shape our personal stories. Those stories, in turn, help to (4)____ who we are. This is the quiet power of language. If you pay (5)____ to the exact words people choose, you will see how each language (6)____ in the world it builds. You can also feel this power when you (7)____ a negative sentence with a positive one. Saying ''I want to feel secure'' instead of ''I don''t want to fail'' can (8)____ how you feel inside. The (9)____ is that the words we speak do not just describe our lives; they help to (10)____ them. So choose your words with care.', 165, 2, '[{"q":"1","answer":"A","options":["affected","sold","cooked","threw"],"explanation":"a sentence that affected your day 影响你一天的句子。"},{"q":"2","answer":"B","options":["traffic","grammar","weather","money"],"explanation":"spelling and grammar 拼写与语法。"},{"q":"3","answer":"C","options":["cars","shops","minds","gardens"],"explanation":"the thoughts in our own minds 我们心中的想法。"},{"q":"4","answer":"D","options":["sell","hide","waste","determine"],"explanation":"help to determine who we are 帮助决定我们是谁。"},{"q":"5","answer":"A","options":["attention","money","prices","tickets"],"explanation":"pay attention to 关注。"},{"q":"6","answer":"B","options":["sleeps","differs","eats","sells"],"explanation":"how each language differs 每种语言如何不同。"},{"q":"7","answer":"C","options":["forget","drop","replace","lose"],"explanation":"replace A with B 用 B 替换 A。"},{"q":"8","answer":"D","options":["sell","hide","cook","change"],"explanation":"change how you feel 改变你的感受。"},{"q":"9","answer":"A","options":["point","price","noise","weather"],"explanation":"The point is that… 表语从句结构。"},{"q":"10","answer":"B","options":["sell","shape","break","lose"],"explanation":"help to shape them 帮助塑造它们。"}]'::jsonb, 5, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (11, 'elective2', 'U2', 'Guiding Your Audience', 'A good speaker is a little like a guide leading people along a path. As you move from one idea to the (1)____, you must show your audience the way, or they may get lost. The best presenters do this by using small (2)____ such as ''now that I have explained this'' or ''let me turn to that''. These words are called transitions, and they quietly (3)____ what idea is coming next. Without them, even a (4)____ talk can be hard to follow. (5)____ you are speaking about science or history, clear signposts help your listeners (6)____ your argument step by step. Good transitions also give you, the speaker, a moment to (7)____ your thoughts. (8)____ makes a talk truly clear is not only strong ideas but smooth links between them. So before your next presentation, plan (9)____ you will move from point to point. The (10)____ is that the audience should never have to wonder where you are taking them.', 161, 2, '[{"q":"1","answer":"C","options":["price","noise","next","garden"],"explanation":"from one idea to the next 从一个想法到下一个。"},{"q":"2","answer":"D","options":["prices","engines","tickets","phrases"],"explanation":"small phrases 一些短语。"},{"q":"3","answer":"A","options":["signal","sell","hide","break"],"explanation":"signal what idea is coming 提示下一个想法。"},{"q":"4","answer":"B","options":["silent","brilliant","empty","cheap"],"explanation":"even a brilliant talk 即使是精彩的演讲。"},{"q":"5","answer":"C","options":["That","What","Whether","Why"],"explanation":"whether…or… 不论……还是。"},{"q":"6","answer":"D","options":["forget","lose","drop","follow"],"explanation":"follow your argument 跟上你的论证。"},{"q":"7","answer":"A","options":["organise","sell","hide","throw"],"explanation":"organise your thoughts 整理思路。"},{"q":"8","answer":"B","options":["That","What","Whether","Why"],"explanation":"主语从句缺主语 → What makes a talk clear is…。"},{"q":"9","answer":"C","options":["why","whether","how","what"],"explanation":"plan how you will move 计划如何过渡 → how。"},{"q":"10","answer":"D","options":["price","noise","weather","goal"],"explanation":"The goal is that… 表语从句结构。"}]'::jsonb, 6, 'sufe');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='elective2' AND unit='U2';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·对话 Which Language Will You Choose', '上外版选择性必修第二册 U2 · dialogue', 3, 'Lily: Have you decided which foreign language to take next year, Tom?
Tom: I''m thinking about Spanish. So many people around the world speak it.
Lily: That''s a good reason. What made you interested in the first place?
Tom: Last month I watched a Spanish film and loved how the language sounded.
Lily: I know what you mean. I want to learn Japanese myself.
Tom: Japanese? Why is that?
Lily: I love Japanese stories, and I''d like to read them in the original language.
Tom: That''s great. Learning any new language opens a door to another world.', 'Lily 问 Tom 明年选哪门外语;Tom 想学西班牙语,因为说的人多;他上个月看了部西班牙电影,喜欢那语言的声音;Lily 想学日语,因为喜欢日本故事,想读原文;Tom 说学任何新语言都会打开通往另一个世界的门。', 'uk_female', '[{"q":"Which language is Tom thinking of taking?","type":"choice","answer":"A","options":["Spanish.","Japanese.","French.","Russian."]},{"q":"Why did Tom become interested in that language?","type":"choice","answer":"B","options":["His teacher chose it for him.","He watched a film and loved how it sounded.","It is the easiest one to spell.","Almost no one else speaks it."]},{"q":"Which language does Lily want to learn?","type":"choice","answer":"A","options":["Japanese.","Spanish.","Arabic.","German."]},{"q":"Why does Lily want to learn it?","type":"choice","answer":"B","options":["She no longer likes English.","She wants to read Japanese stories in the original.","She is moving abroad next week.","Her parents made her choose it."]},{"q":"What does Tom say about learning a new language?","type":"choice","answer":"C","options":["It is mostly a waste of time.","It can harm the brain.","It opens a door to another world.","It is only useful for exams."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·短文 Languages in Australia', '上外版选择性必修第二册 U2 · passage', 2, 'Long ago, hundreds of different languages were spoken across Australia.
Today only a small number of them are still used every day.
Europeans arrived a little over two hundred years ago, and many languages slowly died out.
For Aboriginal communities, language is a central part of who they are.
It links them to their land, their history, and their sense of belonging.', '很久以前,澳大利亚有数百种不同的语言;如今只有少数仍在日常使用;欧洲人两百多年前到来,许多语言渐渐消亡;对原住民社区来说,语言是他们身份的核心;它把他们与土地、历史和归属感相连。', 'uk_female', '[{"q":"About how many languages were once spoken in Australia?","type":"choice","answer":"D","options":["Only two.","About seven.","None at all.","Hundreds."]},{"q":"How many of them are still used daily now?","type":"choice","answer":"A","options":["Only a small number.","Almost all of them.","Exactly one hundred.","More than before."]},{"q":"When did Europeans arrive, according to the talk?","type":"choice","answer":"B","options":["Only last year.","A little over two hundred years ago.","Five thousand years ago.","They never arrived."]},{"q":"What is language for Aboriginal communities?","type":"choice","answer":"C","options":["A brand-new invention.","An unimportant daily habit.","A central part of their identity.","A foreign import they dislike."]},{"q":"What does their language link them to?","type":"choice","answer":"D","options":["Only their money.","Only the weather.","Nothing in particular.","Their land, history, and sense of belonging."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·对话 Two Words for Blue', '上外版选择性必修第二册 U2 · dialogue', 3, 'Anna: Look at these two squares. Are they the same colour or different?
Igor: Different, of course. One is light blue and the other is dark blue.
Anna: Really? To me they both look just ''blue''.
Igor: In Russian we have two separate words, so I notice the line between them at once.
Anna: That''s amazing. So your language trains your eyes a little.
Igor: Maybe. Scientists say Russian speakers are faster at telling these blues apart.
Anna: I''d never have guessed that words could change how quickly we see.
Igor: It shows how deeply language and the mind are connected.', 'Anna 让 Igor 看两个方块是否同色;Igor 说不同,一个浅蓝一个深蓝;Anna 觉得两个都只是''蓝'';Igor 说俄语里有两个分开的词,所以一眼就看出界线;Anna 惊叹语言训练了眼睛;Igor 说研究表明俄语者更快区分这些蓝色;两人感叹语言与思维联系之深。', 'uk_female', '[{"q":"How do the two squares look to Anna?","type":"choice","answer":"A","options":["They both look simply ''blue''.","They look like two different reds.","They look completely black.","She cannot see them at all."]},{"q":"Why does Igor notice the difference at once?","type":"choice","answer":"B","options":["He is wearing special glasses.","Russian has two separate words for the blues.","He painted the squares himself.","English has far more colour words."]},{"q":"What do scientists say about Russian speakers?","type":"choice","answer":"C","options":["They cannot see the colour blue.","They are always much slower.","They tell these blues apart faster.","They ignore colours completely."]},{"q":"What surprises Anna about words?","type":"choice","answer":"D","options":["That words have no meaning at all.","That blue is her favourite colour.","That Russian is very easy to learn.","That words can change how quickly we see."]},{"q":"What does the talk show, according to Igor?","type":"choice","answer":"A","options":["Language and the mind are deeply connected.","Colours do not really exist.","Russian is a useless language.","Our eyes never change."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·短文 A Healthier Brain', '上外版选择性必修第二册 U2 · passage', 2, 'Speaking two languages does more than help you talk to more people.
Every time you switch between them, your brain gets a small workout.
Studies show that this effort can keep the mind sharp for longer.
It may even delay certain memory problems by several years.
So learning a language is not only useful; it is good for the brain.', '会说两种语言不只是能和更多人交流;每次在两种语言间切换,大脑都会做个小锻炼;研究表明这种努力能让头脑更久保持敏锐;甚至可能把某些记忆问题推迟数年;所以学语言不仅有用,还有益大脑。', 'uk_female', '[{"q":"What happens each time you switch languages?","type":"choice","answer":"B","options":["Your brain stops working.","Your brain gets a small workout.","You forget your first language.","Nothing at all changes."]},{"q":"What do the studies show?","type":"choice","answer":"C","options":["Two languages harm the mind.","Switching is simply impossible.","The effort can keep the mind sharp for longer.","Memory gets worse straight away."]},{"q":"What may speaking two languages delay?","type":"choice","answer":"D","options":["Learning how to read.","Growing any taller.","Making new friends.","Certain memory problems."]},{"q":"How long might it delay them?","type":"choice","answer":"A","options":["By several years.","By a few minutes.","By a single day.","Not at all."]},{"q":"What is the speaker''s main point?","type":"choice","answer":"B","options":["Languages are a waste of time.","A language is useful and good for the brain.","Only one language is ever needed.","The brain never changes."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·对话 Saving Grandpa''s Dialect', '上外版选择性必修第二册 U2 · dialogue', 3, 'Mei: My grandpa speaks an old dialect that almost no young people use now.
Sam: That''s a pity. What happens when the last speakers are gone?
Mei: A lot of stories and local knowledge could disappear with them.
Sam: So have you thought of doing anything about it?
Mei: Yes. Every weekend I record him telling old tales in his dialect.
Sam: That''s a wonderful idea. You''re saving more than just words.
Mei: Exactly. The real question is whether my generation will keep it alive.
Sam: I''m sure small efforts like yours can make a real difference.', 'Mei 说爷爷讲一种几乎没年轻人用的老方言;Sam 觉得可惜,问最后的说话者走后会怎样;Mei 说许多故事和地方知识可能随之消失;Mei 每个周末录爷爷用方言讲老故事;Sam 称赞这是在拯救不止是词语的东西;Mei 说真正的问题是她这代人能否让它存续;Sam 相信小小的努力能带来真正的改变。', 'uk_female', '[{"q":"What is special about Mei''s grandpa''s dialect?","type":"choice","answer":"C","options":["Everyone in the city speaks it.","It is a brand-new language.","Few young people still use it.","It is taught in every school."]},{"q":"What could disappear with the last speakers?","type":"choice","answer":"D","options":["Only the spelling rules.","Nothing of any value.","A few old road signs.","Stories and local knowledge."]},{"q":"What does Mei do every weekend?","type":"choice","answer":"A","options":["She records him telling old tales.","She forgets the dialect on purpose.","She studies only English.","She travels far abroad."]},{"q":"What does Sam say she is really saving?","type":"choice","answer":"B","options":["Only a little money.","More than just words.","A pile of old books.","Nothing important at all."]},{"q":"What does Mei call the real question?","type":"choice","answer":"C","options":["Where her grandpa now lives.","How old the dialect really is.","Whether her generation will keep it alive.","Why English is so useful."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U2', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (11, 'U2 听力·短文 Why You Think the Way You Do', '上外版选择性必修第二册 U2 · passage', 2, 'We have seen that speakers of different languages can think in different ways.
But this talk is not really about how people far away think.
It is about how you, yourself, think every single day.
Your language quietly shapes what you notice and what you forget.
So it is always worth asking why you see the world the way you do.', '我们看到说不同语言的人可能以不同方式思考;但这次演讲并非真的关于远方的人如何思考;而是关于你自己每天如何思考;你的语言悄悄塑造你注意什么、忽略什么;所以值得问问:你为何这样看世界。', 'uk_female', '[{"q":"What have we seen about speakers of different languages?","type":"choice","answer":"D","options":["They all think exactly the same.","They are unable to think.","They never use any words.","They can think in different ways."]},{"q":"What is this talk really about?","type":"choice","answer":"A","options":["How you yourself think.","How people far away think.","How to spell English words.","How to travel abroad cheaply."]},{"q":"What does your language quietly shape?","type":"choice","answer":"B","options":["Only how tall you grow.","What you notice and what you forget.","Only the weather outside.","Nothing about your mind."]},{"q":"How often does language shape your thinking?","type":"choice","answer":"C","options":["Only once a year.","Never in real life.","Every single day.","Only during exams."]},{"q":"What does the speaker say is worth asking?","type":"choice","answer":"D","options":["Where you were first born.","How tall your friends are.","Who your teacher is.","Why you see the world as you do."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U2', 'sufe');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='elective2' AND unit='U2';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (11, 'Write an argumentative letter about learning another foreign language(就再开一门外语写议论性书信)', 'Is English the Only Foreign Language Worth Learning?', '假设你是陈凯,你校只教英语一门外语。你希望学校能再开设一门法语课。请用英语给校长写一封约100–120词的劝说信,内容包括:① 明确提出你的主张(claim):高中生应有机会学习英语以外的语言;② 先承认对方可能的反方观点(counterclaim),再加以反驳;③ 给出一两条具体理由(如能与更多人交流、打开新世界);④ 礼貌地提出请求。注意:用上主语从句/表语从句让说理更清楚。', 'Suppose you are Chen Kai, and your school teaches only English as a foreign language. Write a letter (about 100–120 words) to your headmaster to persuade him to offer a French course. Include: 1) a clear claim that students should be able to learn languages other than English; 2) a likely counterclaim, which you then answer; 3) one or two concrete reasons; 4) a polite request. Try to use subject or predicative clauses to make your argument clear.', '["明确主张(I strongly believe that students should …)","承认并反驳反方观点(It is true that … However, …)","给出具体理由(What a new language offers is …)","礼貌请求(I would be grateful if the school could …)"]'::jsonb, 70, 100, 'Dear Headmaster,

I am writing to ask the school to offer a French course. I strongly believe that high school students should be able to learn a language other than English.

It is true that English is already used in business, science and travel around the world. However, this does not mean that one language is enough. What a new language really offers is a fresh way of seeing the world and a chance to reach millions more people. The truth is that every language we learn quietly changes how we think.

Many of my classmates feel the same way. I would be grateful if the school could consider opening a French class.

Yours sincerely,
Chen Kai', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["I strongly believe that high school students should be able to learn a language other than English.","It is true that English is widely used; however, this does not mean that one language is enough.","What a new language really offers is a fresh way of seeing the world.","The truth is that every language we learn quietly changes how we think."]'::jsonb, '[{"wrong":"I believe that students should to learn French.","correct":"I believe that students should learn French.","note":"情态动词 should 后接动词原形,不加 to。"},{"wrong":"The truth is what every language changes our thinking.","correct":"The truth is that every language changes our thinking.","note":"表语从句陈述事实、从句完整,用 that 不用 what。"},{"wrong":"What a new language offers are a new way of thinking.","correct":"What a new language offers is a new way of thinking.","note":"What 引导的主语从句作主语视为单数,谓语用 is。"}]'::jsonb, '【劝说信结构】
开头 说明目的 + 主张:I am writing to … I strongly believe that …
中间 反方+反驳:It is true that … However, this does not mean that …
中间 理由:What a new language offers is … The truth is that …
结尾 请求:I would be grateful if the school could …', 2, 'elective2', 'U2', 'sufe');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='elective2' AND unit='U2';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (11, 'elective2', 'U2', '{"title":"主语从句 & 表语从句速查","intro":"主语从句和表语从句都是名词性从句:主语从句作句子主语,表语从句跟在系动词 be 后作表语。难点是选连接词。口诀:陈述完整事实→that;表''是否''→whether(不用 if);从句缺主语/宾语→what;问方式/程度→how;问原因→why。","table":{"headers":["连接词","用法 / 例句"],"rows":[["that","从句完整、陈述事实:That language shapes thought is clear. / The truth is that words matter."],["whether","表''是否''的疑问:Whether it is true is unknown. / The question is whether we can.（不用 if）"],["what","从句缺主语或宾语:What matters is… / This is what language does（缺宾语）"],["how","问方式/程度:How the brain learns is amazing. / It is amazing how quickly they react."],["why","问原因:Why so many languages die is a mystery. / That is why he gave up."]]},"specialRules":[{"rule":"主语从句嫌句首太长 → 用 it 作形式主语,真主语后置","mark":"It is true that… = That… is true"},{"rule":"主语从句作主语,谓语一律用单数","mark":"What we say matters（is/matters，不用 are）"},{"rule":"主语/表语从句表''是否''只能用 whether,不用 if","mark":"Whether… is the question √ / If… ×"},{"rule":"The reason is + 表语从句,用 that，不用 why","mark":"The reason is that… √ / The reason is why… ×（但 That is why… √）"}],"why":["选词只看两点:① 从句缺不缺成分——缺主语/宾语就用 what(它本身在从句里当主语或宾语);不缺就在 that/whether/how/why 里按句意挑。② 句意是陈述事实(that)、还是疑问''是否''(whether)、方式(how)、原因(why)。"],"gaokaoPoints":["语法填空高频:句首主语从句或 be 后表语从句中填连接词,先看从句是否缺主宾,再看句意。","易错点:表''是否''用 whether 不用 if;The reason is that…(不用 why);what 引导的主语从句谓语用单数。"],"examVsReal":[{"exam":"What I want to say is that language shapes us.（考试/书面完整）","real":"The thing is, language shapes us.","note":"口语常用 ''The thing is,'' 起头,省去完整的主/表语从句结构。"},{"exam":"Whether it is true remains unknown.（考试用 whether）","real":"We don''t really know if it''s true.","note":"宾语位置口语可用 if;但主语/表语从句仍须用 whether。"}]}'::jsonb, 'sufe');

COMMIT;

-- ===== 自带校验(publisher='sufe') =====
SELECT 'vocab' k, count(*) v, 48 expect FROM public.junior_vocab WHERE publisher='sufe' AND volume='elective2' AND unit='U2'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='elective2' AND unit='U2')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='sufe' AND volume='elective2' AND unit='U2'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='sufe' AND volume='elective2' AND unit='U2'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='elective2' AND unit='U2'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='elective2' AND unit='U2'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='elective2' AND unit='U2' ORDER BY k;
