-- ⛔ SUPERSEDED —— 早期小批,已被 SUPERSEDED_vocab_toefl_words_full.sql 整体取代,勿单独重跑
-- 托福词库 batch1:freq_rank 前 200 词
-- 生成: node scripts/vocab/ingest-toefl.mjs --emit-sql
-- 数据源: skywind3000/ECDICT · MIT License (c) 2025 Linwei
-- ⚠️ 由 Aaron 执行。脚本本身从不写库。
--
-- 幂等性: vocab_words 走 ON CONFLICT (lower(headword))(索引 vocab_words_headword_uq),
--         vocab_word_banks 走 PK (word_id, bank_id)。重复跑不会产生重复行。
-- bank_id 用子查询取,不硬编码 uuid。

BEGIN;

-- ── 跑之前的基线 ──
SELECT 'BEFORE' AS stage,
       (SELECT count(*) FROM vocab_words) AS words,
       (SELECT count(*) FROM vocab_word_banks
         WHERE bank_id = (SELECT id FROM vocab_banks WHERE code = 'toefl')) AS toefl_links;

-- ① 词条
INSERT INTO vocab_words (headword, pos, freq_rank) VALUES
('defense', 'n.', 657),
('democrat', 'n.', 903),
('attorney', 'n.', 1069),
('participant', 'n./adj.', 1103),
('concerned', 'adj.', 1128),
('involved', 'adj.', 1174),
('neighbor', 'n./v./adj.', 1424),
('context', 'n.', 1427),
('voter', 'n.', 1452),
('grab', 'n./v.', 1477),
('theater', 'n.', 1535),
('regional', 'adj.', 1645),
('currently', 'adv.', 1700),
('ethnic', 'adj.', 1729),
('landscape', 'n./v.', 1827),
('regime', 'n.', 1848),
('perception', 'n.', 1866),
('opposition', 'n.', 1876),
('coverage', 'n.', 1877),
('intervention', 'n.', 1926),
('cite', 'v.', 1932),
('sector', 'n./v.', 1974),
('honor', 'n./v.', 2057),
('asset', 'n.', 2094),
('proceeding', 'n.', 2107),
('funding', NULL, 2141),
('therapy', 'n.', 2142),
('remaining', NULL, 2155),
('chip', 'n./v.', 2159),
('transition', 'n.', 2212),
('coalition', 'n.', 2241),
('negotiation', 'n.', 2259),
('congressional', 'adj.', 2309),
('championship', 'n.', 2326),
('deficit', 'n.', 2403),
('ally', 'n./v.', 2408),
('confront', 'v.', 2415),
('peer', 'n./v.', 2424),
('retirement', 'n.', 2442),
('literally', 'adv.', 2469),
('administrator', 'n.', 2484),
('constantly', 'adv.', 2498),
('diversity', 'n.', 2531),
('dealer', 'n.', 2575),
('clinical', 'adj.', 2584),
('fiber', 'n.', 2594),
('incorporate', 'adj./v.', 2600),
('lawsuit', 'n.', 2660),
('testimony', 'n.', 2661),
('cooperation', 'n.', 2668),
('profile', 'n./v.', 2676),
('mechanism', 'n.', 2677),
('penalty', 'n.', 2680),
('constitutional', 'adj.', 2689),
('infection', 'n.', 2692),
('initially', 'adv.', 2715),
('incentive', 'n./adj.', 2726),
('ken', 'n.', 2727),
('elite', 'n.', 2735),
('senator', 'n.', 2769),
('awareness', 'n.', 2784),
('testify', 'v.', 2790),
('founder', 'n./v.', 2800),
('originally', 'adv.', 2854),
('assault', 'n./v.', 2860),
('violation', 'n.', 2870),
('controversy', 'n.', 2876),
('defensive', 'adj./n.', 2881),
('constitute', 'v.', 2887),
('representation', 'n.', 2908),
('emission', 'n.', 2915),
('entitled', 'adj.', 2950),
('vulnerable', 'adj.', 2955),
('capability', 'n.', 2958),
('celebrity', 'n.', 2960),
('ongoing', 'adj./n.', 2970),
('counselor', 'n.', 2973),
('survivor', 'n.', 3011),
('psychologist', 'n.', 3014),
('galaxy', 'n.', 3016),
('incredible', 'adj.', 3026),
('mall', 'n.', 3050),
('conviction', 'n.', 3066),
('myth', 'n.', 3076),
('standing', 'n./adj.', 3080),
('flavor', 'n./v.', 3118),
('sue', 'v.', 3137),
('demonstration', 'n.', 3142),
('assert', 'v.', 3147),
('offensive', 'adj.', 3168),
('dominant', 'adj.', 3174),
('heritage', 'n.', 3175),
('legacy', 'n.', 3189),
('orientation', 'n.', 3196),
('inflation', 'n.', 3197),
('cluster', 'n./v.', 3200),
('depict', 'v.', 3205),
('sanction', 'n./v.', 3217),
('habitat', 'n.', 3221),
('ethics', 'n.', 3231),
('odds', 'n.', 3239),
('frustration', 'n.', 3240),
('discourse', 'n./v.', 3253),
('portray', 'v.', 3263),
('nonetheless', 'conj./adv.', 3298),
('recording', 'adj./n.', 3319),
('colonial', 'adj.', 3321),
('cognitive', 'adj.', 3344),
('fitness', 'n.', 3357),
('dramatically', 'adv.', 3364),
('makeup', 'n.', 3366),
('alliance', 'n.', 3376),
('hypothesis', 'n.', 3377),
('norm', 'n.', 3387),
('counseling', 'n.', 3399),
('ritual', 'n./adj.', 3404),
('counsel', 'n./v.', 3418),
('presidency', 'n.', 3432),
('subtle', 'adj.', 3435),
('integrity', 'n.', 3464),
('essence', 'n.', 3468),
('pitcher', 'n.', 3478),
('rumor', 'n./v.', 3498),
('humanity', 'n.', 3501),
('administrative', 'adj.', 3510),
('allegation', 'n.', 3516),
('initiate', 'n./adj./v.', 3524),
('plead', 'v.', 3525),
('seemingly', 'adv.', 3541),
('effectiveness', 'n.', 3543),
('inspector', 'n.', 3550),
('fraud', 'n.', 3551),
('contend', 'v.', 3552),
('array', 'n./v.', 3554),
('hallway', 'n.', 3559),
('monster', 'n.', 3565),
('facilitate', 'v.', 3568),
('rip', 'n./v.', 3572),
('recession', 'n.', 3576),
('supervisor', 'n.', 3589),
('arena', 'n.', 3590),
('diagnosis', 'n.', 3594),
('consistently', 'adv.', 3596),
('wright', 'n.', 3602),
('warrior', 'n.', 3607),
('prediction', 'n.', 3608),
('graphics', 'n.', 3609),
('domain', 'n.', 3627),
('weird', 'adj./n.', 3632),
('ideology', 'n.', 3644),
('chronic', 'adj./n.', 3654),
('innovation', 'n.', 3657),
('administer', 'v.', 3661),
('simultaneously', 'adv.', 3662),
('trigger', 'n./v.', 3666),
('amendment', 'n.', 3667),
('adoption', 'n.', 3674),
('convict', 'n./v.', 3678),
('indigenous', 'adj.', 3679),
('undermine', 'v.', 3697),
('traditionally', 'adv.', 3705),
('ballot', 'n./v.', 3706),
('rhetoric', 'n.', 3713),
('convinced', 'adj.', 3714),
('mandate', 'n./v.', 3724),
('profound', 'adj.', 3735),
('lobby', 'n./v.', 3736),
('trait', 'n.', 3737),
('corruption', 'n.', 3743),
('contractor', 'n.', 3745),
('doctrine', 'n.', 3746),
('complexity', 'n.', 3757),
('meaningful', 'adj.', 3769),
('spouse', 'n.', 3777),
('sodium', 'n.', 3783),
('compensation', 'n.', 3796),
('dedicate', 'v.', 3799),
('transaction', 'n.', 3813),
('counterpart', 'n.', 3816),
('amid', 'prep.', 3825),
('residential', 'adj.', 3828),
('carbohydrate', 'n.', 3831),
('diagnose', 'v.', 3832),
('donor', 'n.', 3847),
('endorse', 'v.', 3884),
('exploration', 'n.', 3885),
('spectrum', 'n.', 3893),
('expertise', 'n.', 3898),
('recipient', 'adj./n.', 3919),
('accounting', 'n.', 3921),
('flip', 'v./n./adj.', 3922),
('bias', 'n./adj./adv./v.', 3925),
('metaphor', 'n.', 3927),
('entity', 'n.', 3932),
('regulatory', 'adj.', 3939),
('diplomatic', 'adj.', 3940),
('minimize', 'v.', 3941),
('diminish', 'v.', 3958),
('intent', 'n./adj.', 3961),
('inventory', 'n./v.', 3967)
ON CONFLICT (lower(headword)) DO UPDATE
  SET pos        = COALESCE(EXCLUDED.pos, vocab_words.pos),
      freq_rank  = COALESCE(EXCLUDED.freq_rank, vocab_words.freq_rank),
      updated_at = now();

-- ② 挂到 toefl 词库
INSERT INTO vocab_word_banks (word_id, bank_id)
SELECT w.id, b.id
  FROM vocab_words w
  CROSS JOIN (SELECT id FROM vocab_banks WHERE code = 'toefl') b
 WHERE lower(w.headword) IN ('defense', 'democrat', 'attorney', 'participant', 'concerned', 'involved', 'neighbor', 'context', 'voter', 'grab', 'theater', 'regional', 'currently', 'ethnic', 'landscape', 'regime', 'perception', 'opposition', 'coverage', 'intervention', 'cite', 'sector', 'honor', 'asset', 'proceeding', 'funding', 'therapy', 'remaining', 'chip', 'transition', 'coalition', 'negotiation', 'congressional', 'championship', 'deficit', 'ally', 'confront', 'peer', 'retirement', 'literally', 'administrator', 'constantly', 'diversity', 'dealer', 'clinical', 'fiber', 'incorporate', 'lawsuit', 'testimony', 'cooperation', 'profile', 'mechanism', 'penalty', 'constitutional', 'infection', 'initially', 'incentive', 'ken', 'elite', 'senator', 'awareness', 'testify', 'founder', 'originally', 'assault', 'violation', 'controversy', 'defensive', 'constitute', 'representation', 'emission', 'entitled', 'vulnerable', 'capability', 'celebrity', 'ongoing', 'counselor', 'survivor', 'psychologist', 'galaxy', 'incredible', 'mall', 'conviction', 'myth', 'standing', 'flavor', 'sue', 'demonstration', 'assert', 'offensive', 'dominant', 'heritage', 'legacy', 'orientation', 'inflation', 'cluster', 'depict', 'sanction', 'habitat', 'ethics', 'odds', 'frustration', 'discourse', 'portray', 'nonetheless', 'recording', 'colonial', 'cognitive', 'fitness', 'dramatically', 'makeup', 'alliance', 'hypothesis', 'norm', 'counseling', 'ritual', 'counsel', 'presidency', 'subtle', 'integrity', 'essence', 'pitcher', 'rumor', 'humanity', 'administrative', 'allegation', 'initiate', 'plead', 'seemingly', 'effectiveness', 'inspector', 'fraud', 'contend', 'array', 'hallway', 'monster', 'facilitate', 'rip', 'recession', 'supervisor', 'arena', 'diagnosis', 'consistently', 'wright', 'warrior', 'prediction', 'graphics', 'domain', 'weird', 'ideology', 'chronic', 'innovation', 'administer', 'simultaneously', 'trigger', 'amendment', 'adoption', 'convict', 'indigenous', 'undermine', 'traditionally', 'ballot', 'rhetoric', 'convinced', 'mandate', 'profound', 'lobby', 'trait', 'corruption', 'contractor', 'doctrine', 'complexity', 'meaningful', 'spouse', 'sodium', 'compensation', 'dedicate', 'transaction', 'counterpart', 'amid', 'residential', 'carbohydrate', 'diagnose', 'donor', 'endorse', 'exploration', 'spectrum', 'expertise', 'recipient', 'accounting', 'flip', 'bias', 'metaphor', 'entity', 'regulatory', 'diplomatic', 'minimize', 'diminish', 'intent', 'inventory')
ON CONFLICT (word_id, bank_id) DO NOTHING;

-- ── 跑之后的实测 ──
SELECT 'AFTER' AS stage,
       (SELECT count(*) FROM vocab_words) AS words,
       (SELECT count(*) FROM vocab_word_banks
         WHERE bank_id = (SELECT id FROM vocab_banks WHERE code = 'toefl')) AS toefl_links;

-- ── count-validate:两行都必须是 t,否则 ROLLBACK ──
-- 预期(首次跑,两表都是空的): words = 200,toefl_links = 200
SELECT 'words = 200' AS expect,
       (SELECT count(*) FROM vocab_words) = 200 AS ok
UNION ALL
SELECT 'toefl_links = 200',
       (SELECT count(*) FROM vocab_word_banks
         WHERE bank_id = (SELECT id FROM vocab_banks WHERE code = 'toefl')) = 200;

COMMIT;
