-- def_zh 义项补全(强信号批次)—— 232 词补出第二义
-- 口径:以 ECDICT 为义项基准,只**加**第二义,**第一义项逐字不变**(例句锚定它,本轮不重生成例句)。
-- 另有 47 词判定"无值得教的第二义",不改。
-- 闸门 s1(第一义不变)/ s2(第二义有词典依据)/ s3(体裁 ≤8 字)全量复检 0 不合格。
-- 对照件:REVIEWAA/vocab_toefl_sense_fix_sample.md
-- ⚠️ 由 Aaron 执行。

BEGIN;

SELECT 'BEFORE' AS stage,
       count(*) FILTER (WHERE def_zh LIKE '%；%') AS two_sense_words,
       count(*) AS total
  FROM vocab_words WHERE def_zh IS NOT NULL;

UPDATE vocab_words w
   SET def_zh = v.def_zh, updated_at = now()
  FROM (VALUES
  ('ally', '盟友；结盟关系'),
  ('founder', '创始人；沉没'),
  ('sue', '起诉；请求'),
  ('chronic', '慢性的；慢性病患者'),
  ('shrimp', '虾；矮子'),
  ('secular', '世俗的；长期存在'),
  ('specialty', '专长；特产'),
  ('nutrient', '营养物质；滋养成分'),
  ('stereotype', '刻板印象；老套'),
  ('fossil', '化石；陈旧守旧'),
  ('hover', '悬停；盘旋翱翔'),
  ('antibiotic', '抗生素；抗生物'),
  ('prosecute', '起诉；彻底进行'),
  ('crab', '螃蟹；捕蟹'),
  ('exile', '流亡；流放'),
  ('merge', '合并；使消失'),
  ('posture', '姿势；态度'),
  ('precedent', '先例；在先的'),
  ('haven', '避风港；避难所'),
  ('armor', '盔甲；装甲'),
  ('cone', '圆锥；圆锥体'),
  ('reservoir', '水库；贮藏处'),
  ('upgrade', '升级；上坡'),
  ('valve', '阀门；活瓣'),
  ('excerpt', '摘录；引用'),
  ('census', '人口普查；统计调查'),
  ('nickname', '绰号；取绰号'),
  ('activate', '激活；使活动'),
  ('lethal', '致命的；致死因子'),
  ('entail', '涉及；成为必需'),
  ('foam', '泡沫；起泡'),
  ('pasture', '牧场；放牧'),
  ('bait', '诱饵；以饵引诱'),
  ('reef', '珊瑚礁；暗礁'),
  ('dietary', '饮食的；规定饮食'),
  ('underestimate', '低估；看轻'),
  ('navigate', '导航；航行驾驶'),
  ('terrace', '露台；梯田'),
  ('erode', '侵蚀；物质腐蚀'),
  ('mimic', '模仿；效颦者，模仿者'),
  ('dodge', '躲避；诡计，藏匿'),
  ('conform', '遵守；一致符合'),
  ('merchandise', '商品；交易买卖'),
  ('wholesale', '批发；大规模'),
  ('mediate', '调解；调停'),
  ('tariff', '关税；价格表'),
  ('inhibit', '抑制；禁止'),
  ('plight', '困境；宣誓保证'),
  ('default', '默认；违约责任'),
  ('fort', '堡垒；军事要塞'),
  ('subsidiary', '子公司；辅助机构'),
  ('peril', '危险；冒险行为'),
  ('wade', '涉水而行；跋涉'),
  ('lust', '欲望；色欲'),
  ('maze', '迷宫；迷惘'),
  ('rehearse', '排练；预演'),
  ('nickel', '镍；镍币'),
  ('heighten', '增强；升高变大'),
  ('sovereign', '主权；元首独立国'),
  ('cardiac', '心脏的；贲门的'),
  ('glamour', '魅力；迷惑'),
  ('converge', '汇聚；集合'),
  ('vapor', '蒸汽；蒸发现象'),
  ('mortar', '砂浆；研钵'),
  ('asphalt', '沥青；铺柏油'),
  ('volcanic', '火山的；猛烈'),
  ('restrictive', '限制性的；约束性'),
  ('apprentice', '学徒；做学徒'),
  ('smuggle', '走私；偷运'),
  ('mint', '薄荷；造币厂'),
  ('veer', '偏离；转向'),
  ('moss', '苔藓；泥沼'),
  ('disarm', '解除武装；缓和局势'),
  ('inflate', '膨胀；通货膨胀'),
  ('overlap', '重叠；重复发生'),
  ('frail', '脆弱的；虚弱之人'),
  ('soothe', '安抚；缓和'),
  ('jelly', '果冻；胶状物'),
  ('fluorescent', '荧光的；荧光现象'),
  ('fortress', '堡垒；筑要塞'),
  ('syllable', '音节；分音节'),
  ('opaque', '不透明的；不传热'),
  ('plump', '丰满；圆胖'),
  ('reshape', '重塑；整形'),
  ('assimilate', '同化；吸收'),
  ('exempt', '免除；豁免'),
  ('ascend', '上升；攀登'),
  ('wed', '结婚；结合'),
  ('sulfur', '硫；硫磺处理'),
  ('magnify', '放大；夸大'),
  ('dent', '凹痕；削弱程度'),
  ('pollen', '花粉；传授花粉'),
  ('permeate', '渗透；弥漫'),
  ('deterrent', '威慑力量；威慑手段'),
  ('dissipate', '消散；浪费掉'),
  ('manure', '肥料；施肥'),
  ('willow', '柳树；柳木制品'),
  ('clam', '蛤蜊；沉默者'),
  ('avalanche', '雪崩；大量'),
  ('serene', '宁静的；沉着'),
  ('gleam', '光辉；微光'),
  ('gait', '步态；训练步法'),
  ('tapestry', '挂毯；挂毯装饰'),
  ('scarlet', '猩红色；红衣'),
  ('infiltrate', '渗透；渗透物'),
  ('zinc', '锌；镀锌'),
  ('beacon', '灯塔；烽火'),
  ('edible', '可食用的；食品'),
  ('climax', '高潮；极点'),
  ('obstruct', '阻碍；阻隔'),
  ('daisy', '雏菊；一流人物'),
  ('refund', '退款；偿还'),
  ('defective', '有缺陷的；缺陷者'),
  ('dagger', '匕首；用剑刺'),
  ('determinant', '决定因素；决定性'),
  ('cavern', '洞穴；巨穴洞窟'),
  ('saturate', '饱和；浸透充满'),
  ('trample', '践踏；无视'),
  ('axe', '斧头；削减经费'),
  ('troupe', '剧团；巡回演出'),
  ('resin', '树脂；涂覆树脂'),
  ('fresco', '湿壁画；湿壁画制作'),
  ('camouflage', '伪装；掩饰行为'),
  ('cove', '海湾；山凹小湾'),
  ('fable', '寓言；虚构故事'),
  ('illiterate', '文盲的；目不识丁'),
  ('meditate', '冥想；沉思反省'),
  ('skyrocket', '急剧上升；焰火'),
  ('ornamental', '装饰性的；观赏植物'),
  ('legislate', '立法；立法规定'),
  ('venom', '毒液；恶意'),
  ('repress', '压制；镇压抑制'),
  ('hoax', '骗局；恶作剧'),
  ('flaunt', '炫耀；飘扬'),
  ('starch', '淀粉；浆硬'),
  ('embroider', '刺绣；镶边装饰'),
  ('diverge', '分歧；岔开'),
  ('maize', '玉米；黄色的植物'),
  ('effluent', '污水；流出水'),
  ('gradient', '梯度；倾斜度'),
  ('brawl', '斗殴；争吵'),
  ('subterranean', '地下的；秘密活动'),
  ('accordion', '手风琴；可折叠物'),
  ('barbarian', '野蛮人；野蛮的'),
  ('stimulant', '兴奋剂；兴奋性物质'),
  ('sap', '树液；活力'),
  ('additive', '添加剂；添加物'),
  ('malfunction', '故障；失灵'),
  ('consequent', '随之而来的；合乎逻辑'),
  ('varnish', '清漆；粉饰'),
  ('censure', '谴责；责难'),
  ('luster', '光泽；光彩荣誉'),
  ('slumber', '酣睡；深度睡眠'),
  ('slime', '粘液；烂泥'),
  ('saber', '军刀；马刀砍'),
  ('silt', '淤泥；使淤塞'),
  ('relapse', '复发；故态复萌'),
  ('audit', '审计；旁听'),
  ('nurture', '培养；养育'),
  ('asteroid', '小行星；星状'),
  ('crouch', '蹲下；低头'),
  ('commute', '通勤；交换折偿'),
  ('seam', '缝合处；裂痕'),
  ('swelling', '肿胀；肿胀部位'),
  ('interrogate', '审问；质问讯问'),
  ('reptile', '爬行动物；卑鄙之人'),
  ('confiscate', '没收；被没收物'),
  ('prerequisite', '先决条件；必要条件'),
  ('subversive', '颠覆性的；破坏分子'),
  ('repel', '击退；使厌恶'),
  ('digestive', '消化的；助消化剂'),
  ('mistrust', '不信任；疑惑'),
  ('predominate', '占主导地位；控制支配'),
  ('raven', '渡鸦；乌黑色'),
  ('sentry', '哨兵；岗哨'),
  ('mason', '泥瓦匠；共济会会员'),
  ('domesticated', '驯化的；家庭生活者'),
  ('surcharge', '附加费；超载'),
  ('baroque', '巴洛克风格；绮靡俗艳'),
  ('corrosive', '腐蚀性的；有害物质'),
  ('modulate', '调节；控制'),
  ('sunburn', '晒伤；晒黑'),
  ('haggle', '讨价还价；争论杀价'),
  ('reversible', '可逆的；可撤消'),
  ('sapphire', '蓝宝石；天蓝色'),
  ('consonant', '辅音；一致调和'),
  ('germinate', '发芽；使发育'),
  ('blemish', '瑕疵；污点'),
  ('sicken', '使恶心；使厌倦'),
  ('vertebrate', '脊椎动物；有脊椎的'),
  ('facsimile', '复制品；传真件'),
  ('mammalian', '哺乳类的；哺乳动物'),
  ('incubate', '孵化；培养'),
  ('monochrome', '单色，单色图像；黑白图像'),
  ('squall', '狂风；飑与喊叫'),
  ('crustacean', '甲壳类动物；甲壳纲'),
  ('crevasse', '冰川裂缝；裂缝'),
  ('lithograph', '平版画；平版印刷'),
  ('perishable', '易腐烂的；易腐坏物品'),
  ('ferret', '雪貂；搜索'),
  ('azure', '天蓝色；蔚蓝色'),
  ('recluse', '隐居者；隐遁之人'),
  ('overcharge', '过高收费；超载'),
  ('lathe', '车床；车床加工'),
  ('ultrasonic', '超声波的；超音速'),
  ('transmute', '转化；变形变质'),
  ('erudite', '博学的；博学之人'),
  ('defrost', '解冻；除霜'),
  ('refrigerant', '制冷剂；冷却剂'),
  ('cabal', '阴谋集团；秘密结社'),
  ('sallow', '病态苍白；灰黄色，气色差'),
  ('ragtime', '拉格泰姆音乐；滑稽风格'),
  ('depreciate', '贬值；降价贬低'),
  ('sublimate', '升华；使高尚'),
  ('spanking', '打屁股；清爽疾行'),
  ('ruffian', '恶棍；凶恶残暴'),
  ('obligated', '有义务的；负有责任'),
  ('defecate', '排便；净化污物'),
  ('emaciate', '使消瘦；使憔悴'),
  ('feint', '假动作；佯攻'),
  ('rawhide', '生皮；用生皮抽打'),
  ('fireproof', '防火的；具耐火性'),
  ('canter', '慢跑；流浪者'),
  ('thresh', '脱粒；反复推敲'),
  ('fossilize', '使化石化；使陈腐'),
  ('magnetize', '磁化；吸引力'),
  ('overbalance', '失衡；超重'),
  ('fagot', '酒吧；柴把束薪'),
  ('tributary', '支流；纳贡者'),
  ('intestine', '肠；内部的，国内的'),
  ('fowl', '家禽；飞禽'),
  ('indent', '缩进；凹痕')
  ) AS v(headword, def_zh)
 WHERE lower(w.headword) = v.headword;

SELECT 'AFTER' AS stage,
       count(*) FILTER (WHERE def_zh LIKE '%；%') AS two_sense_words,
       count(*) AS total
  FROM vocab_words WHERE def_zh IS NOT NULL;

-- ── count-validate:四行都必须是 t,否则 ROLLBACK ──
SELECT '本批 232 词都已是新值' AS expect,
       (SELECT count(*) FROM vocab_words WHERE lower(headword) IN ('ally', 'founder', 'sue', 'chronic', 'shrimp', 'secular', 'specialty', 'nutrient', 'stereotype', 'fossil', 'hover', 'antibiotic', 'prosecute', 'crab', 'exile', 'merge', 'posture', 'precedent', 'haven', 'armor', 'cone', 'reservoir', 'upgrade', 'valve', 'excerpt', 'census', 'nickname', 'activate', 'lethal', 'entail', 'foam', 'pasture', 'bait', 'reef', 'dietary', 'underestimate', 'navigate', 'terrace', 'erode', 'mimic', 'dodge', 'conform', 'merchandise', 'wholesale', 'mediate', 'tariff', 'inhibit', 'plight', 'default', 'fort', 'subsidiary', 'peril', 'wade', 'lust', 'maze', 'rehearse', 'nickel', 'heighten', 'sovereign', 'cardiac', 'glamour', 'converge', 'vapor', 'mortar', 'asphalt', 'volcanic', 'restrictive', 'apprentice', 'smuggle', 'mint', 'veer', 'moss', 'disarm', 'inflate', 'overlap', 'frail', 'soothe', 'jelly', 'fluorescent', 'fortress', 'syllable', 'opaque', 'plump', 'reshape', 'assimilate', 'exempt', 'ascend', 'wed', 'sulfur', 'magnify', 'dent', 'pollen', 'permeate', 'deterrent', 'dissipate', 'manure', 'willow', 'clam', 'avalanche', 'serene', 'gleam', 'gait', 'tapestry', 'scarlet', 'infiltrate', 'zinc', 'beacon', 'edible', 'climax', 'obstruct', 'daisy', 'refund', 'defective', 'dagger', 'determinant', 'cavern', 'saturate', 'trample', 'axe', 'troupe', 'resin', 'fresco', 'camouflage', 'cove', 'fable', 'illiterate', 'meditate', 'skyrocket', 'ornamental', 'legislate', 'venom', 'repress', 'hoax', 'flaunt', 'starch', 'embroider', 'diverge', 'maize', 'effluent', 'gradient', 'brawl', 'subterranean', 'accordion', 'barbarian', 'stimulant', 'sap', 'additive', 'malfunction', 'consequent', 'varnish', 'censure', 'luster', 'slumber', 'slime', 'saber', 'silt', 'relapse', 'audit', 'nurture', 'asteroid', 'crouch', 'commute', 'seam', 'swelling', 'interrogate', 'reptile', 'confiscate', 'prerequisite', 'subversive', 'repel', 'digestive', 'mistrust', 'predominate', 'raven', 'sentry', 'mason', 'domesticated', 'surcharge', 'baroque', 'corrosive', 'modulate', 'sunburn', 'haggle', 'reversible', 'sapphire', 'consonant', 'germinate', 'blemish', 'sicken', 'vertebrate', 'facsimile', 'mammalian', 'incubate', 'monochrome', 'squall', 'crustacean', 'crevasse', 'lithograph', 'perishable', 'ferret', 'azure', 'recluse', 'overcharge', 'lathe', 'ultrasonic', 'transmute', 'erudite', 'defrost', 'refrigerant', 'cabal', 'sallow', 'ragtime', 'depreciate', 'sublimate', 'spanking', 'ruffian', 'obligated', 'defecate', 'emaciate', 'feint', 'rawhide', 'fireproof', 'canter', 'thresh', 'fossilize', 'magnetize', 'overbalance', 'fagot', 'tributary', 'intestine', 'fowl', 'indent')
         AND def_zh LIKE '%；%') = 232 AS ok
UNION ALL
SELECT '总词数没变(4471)',
       (SELECT count(*) FROM vocab_words WHERE def_zh IS NOT NULL) = 4471
UNION ALL
SELECT '没有义项超 8 字',
       NOT EXISTS (
         SELECT 1 FROM vocab_words, unnest(string_to_array(def_zh, '；')) AS seg
          WHERE def_zh IS NOT NULL AND char_length(trim(seg)) > 8
       )
UNION ALL
SELECT '没有义项数超过 2',
       NOT EXISTS (
         SELECT 1 FROM vocab_words
          WHERE def_zh IS NOT NULL
            AND array_length(string_to_array(def_zh, '；'), 1) > 2
       );

COMMIT;
