-- 外研社七下(wy7B) 词表灌库 · junior_vocab · Aaron service role 跑 · 幂等(先 DELETE by publisher+volume 再 INSERT)
-- publisher=junior_fltrp / volume=wy7B / grade=7 / unit∈{U1..U6} · 381词 · 短语 pos/phonetic=NULL · freq_rank=课本顺序 · IPA照抄视觉读出
-- ★DELETE 带 publisher='junior_fltrp' AND volume='wy7B',绝不动人教/wy7A 行★
BEGIN;
DELETE FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B';
INSERT INTO public.junior_vocab (word_id, grade, word, pos, phonetic, meaning_cn, freq_rank, stage, volume, unit, source_type, source_page, confidence, publisher) VALUES
('wy7B-U1-0001', 7, 'review', 'n.', '/rɪˈvjuː/', '书评', 1, 'junior', 'wy7B', 'U1', 'wordlist', 'p.4', 'high', 'junior_fltrp'),
('wy7B-U1-0002', 7, 'chocolate', 'n.', '/ˈtʃɒklət/', '巧克力，朱古力', 2, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0003', 7, 'factory', 'n.', '/ˈfæktəri/', '工厂，制造厂', 3, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0004', 7, 'exciting', 'adj.', '/ɪkˈsaɪtɪŋ/', '令人兴奋的；使人激动的；刺激的', 4, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0005', 7, 'most', 'adv.', '/məʊst/', '最', 5, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0006', 7, 'magical', 'adj.', '/ˈmædʒɪkəl/', '奇异的，美妙的，迷人的', 6, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0007', 7, 'part', 'n.', '/pɑːt/', '部分', 7, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0008', 7, 'side', 'n.', '/saɪd/', '边，面，侧', 8, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0009', 7, 'town', 'n.', '/taʊn/', '镇，城镇，市镇', 9, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0010', 7, 'poor', 'adj.', '/pɔː/', '贫穷的，贫困的', 10, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0011', 7, 'stay', 'v.', '/steɪ/', '停留', 11, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0012', 7, 'only', 'adj.', '/ˈəʊnli/', '唯一的，仅有的', 12, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0013', 7, 'watery', 'adj.', '/ˈwɔːtəri/', '（食物）稀薄的，含水太多的；（饮料）味淡的', 13, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0014', 7, 'cabbage', 'n.', '/ˈkæbɪdʒ/', '卷心菜，洋白菜，甘蓝', 14, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0015', 7, 'freezing', 'adj.', '/ˈfriːzɪŋ/', '极冷的，严寒的', 15, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0016', 7, 'forget', 'v.', '/fəˈɡet/', '忘记，遗忘', 16, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0017', 7, 'touch', 'v.', '/tʌtʃ/', '感动，触动，打动', 17, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0018', 7, 'once', 'adv.', '/wʌns/', '曾经，过去', 18, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0019', 7, 'sunless', 'adj.', '/ˈsʌnləs/', '无阳（日）光的', 19, 'junior', 'wy7B', 'U1', 'wordlist', 'p.5', 'high', 'junior_fltrp'),
('wy7B-U1-0020', 7, 'choose', 'v.', '/tʃuːz/', '选择', 20, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0021', 7, 'everything', 'pron.', '/ˈevriθɪŋ/', '每件事物；所有事物', 21, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0022', 7, 'rich', 'adj.', '/rɪtʃ/', '有钱的，富有的', 22, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0023', 7, 'complete', 'v.', '/kəmˈpliːt/', '完成', 23, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0024', 7, 'expression', 'n.', '/ɪkˈspreʃən/', '词组', 24, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0025', 7, 'passage', 'n.', '/ˈpæsɪdʒ/', '一段，一节', 25, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0026', 7, 'comment', 'n.', '/ˈkɒment/', '意见，评论', 26, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0027', 7, 'description', 'n.', '/dɪˈskrɪpʃən/', '描述，描写，叙述，形容', 27, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0028', 7, 'theme', 'n.', '/θiːm/', '主题', 28, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0029', 7, 'agree', 'v.', '/əˈɡriː/', '同意，赞同', 29, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0030', 7, 'paragraph', 'n.', '/ˈpærəɡrɑːf/', '（文章的）段，段落', 30, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0031', 7, 'understand', 'v.', '/ˌʌndəˈstænd/', '理解', 31, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0032', 7, 'other', 'pron.', '/ˈʌðə/', '另外的人，其他的人', 32, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0033', 7, 'relate', 'v.', '/rɪˈleɪt/', '把……联系起来', 33, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0034', 7, 'experience', 'n.', '/ɪkˈspɪəriəns/', '经验；经历', 34, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0035', 7, 'opinion', 'n.', '/əˈpɪnjən/', '意见，看法', 35, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0036', 7, 'topic', 'n.', '/ˈtɒpɪk/', '话题，论题', 36, 'junior', 'wy7B', 'U1', 'wordlist', 'p.6', 'high', 'junior_fltrp'),
('wy7B-U1-0037', 7, 'grammar', 'n.', '/ˈɡræmə/', '语法', 37, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0038', 7, 'rule', 'n.', '/ruːl/', '规则', 38, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0039', 7, 'more', 'det.', '/mɔː/', '另外的，更多的', 39, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0040', 7, 'correct', 'adj.', '/kəˈrekt/', '正确的', 40, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0041', 7, 'form', 'n.', '/fɔːm/', '形式', 41, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0042', 7, 'chess', 'n.', '/tʃes/', '国际象棋', 42, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0043', 7, 'trip', 'n.', '/trɪp/', '旅游；旅行，出行', 43, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0044', 7, 'post', 'n.', '/pəʊst/', '帖子', 44, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0045', 7, 'dragon', 'n.', '/ˈdræɡən/', '龙', 45, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0046', 7, 'bath', 'v.', '/bɑːθ/', '给……洗澡', 46, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0047', 7, 'decide', 'v.', '/dɪˈsaɪd/', '决定，决断，判断', 47, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0048', 7, 'basket', 'n.', '/ˈbɑːskɪt/', '篮子；篓子；筐子', 48, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0049', 7, 'princess', 'n.', '/ˌprɪnˈses/', '公主', 49, 'junior', 'wy7B', 'U1', 'wordlist', 'p.7', 'high', 'junior_fltrp'),
('wy7B-U1-0050', 7, 'example', 'n.', '/ɪɡˈzɑːmpəl/', '例子', 50, 'junior', 'wy7B', 'U1', 'wordlist', 'p.8', 'high', 'junior_fltrp'),
('wy7B-U1-0051', 7, 'believe', 'v.', '/bɪˈliːv/', '认为', 51, 'junior', 'wy7B', 'U1', 'wordlist', 'p.8', 'high', 'junior_fltrp'),
('wy7B-U1-0052', 7, 'survey', 'n.', '/ˈsɜːveɪ/', '调查', 52, 'junior', 'wy7B', 'U1', 'wordlist', 'p.9', 'high', 'junior_fltrp'),
('wy7B-U1-0053', 7, 'empty', 'adj.', '/ˈempti/', '空的', 53, 'junior', 'wy7B', 'U1', 'wordlist', 'p.10', 'high', 'junior_fltrp'),
('wy7B-U1-0054', 7, 'happen', 'v.', '/ˈhæpən/', '发生', 54, 'junior', 'wy7B', 'U1', 'wordlist', 'p.10', 'high', 'junior_fltrp'),
('wy7B-U1-0055', 7, 'presentation', 'n.', '/ˌprezənˈteɪʃən/', '报告', 55, 'junior', 'wy7B', 'U1', 'wordlist', 'p.11', 'high', 'junior_fltrp'),
('wy7B-U1-0056', 7, 'positive', 'adj.', '/ˈpɒzətɪv/', '有信心的；积极乐观的', 56, 'junior', 'wy7B', 'U1', 'wordlist', 'p.11', 'high', 'junior_fltrp'),
('wy7B-U1-0057', 7, 'blow', 'v.', '/bləʊ/', '吹动；刮动', 57, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0058', 7, 'wave', 'v.', '/weɪv/', '挥动，摆动（某物）；（某物）上下起伏，左右摇晃', 58, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0059', 7, 'voice', 'n.', '/vɔɪs/', '说话声，嗓音；发声能力', 59, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0060', 7, 'just', 'adv.', '/dʒʌst/', '只不过，只是', 60, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0061', 7, 'himself', 'pron.', '/hɪmˈself/', '他自己', 61, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0062', 7, 'shame', 'n.', '/ʃeɪm/', '羞愧，羞耻，惭愧', 62, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0063', 7, 'finally', 'adv.', '/ˈfaɪnəli/', '最后，终于', 63, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0064', 7, 'into', 'prep.', '/ˈɪntə/', '进入，到……里面', 64, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0065', 7, 'barber', 'n.', '/ˈbɑːbə/', '男理发师', 65, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0066', 7, 'fall', 'v.', '/fɔːl/', '落下，降落，跌落', 66, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0067', 7, 'shoulder', 'n.', '/ˈʃəʊldə/', '肩膀', 67, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0068', 7, 'customer', 'n.', '/ˈkʌstəmə/', '顾客，客户', 68, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0069', 7, 'surprised', 'adj.', '/səˈpraɪzd/', '吃惊，惊奇的，惊讶的，诧异的', 69, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0070', 7, 'scissors', 'n.', '/ˈsɪzəz/', '剪刀；剪子', 70, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0071', 7, 'office', 'n.', '/ˈɒfɪs/', '办公楼，办事处，公司', 71, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0072', 7, 'receive', 'v.', '/rɪˈsiːv/', '得到，收到', 72, 'junior', 'wy7B', 'U1', 'wordlist', 'p.12', 'high', 'junior_fltrp'),
('wy7B-U1-0073', 7, 'cancer', 'n.', '/ˈkænsə/', '癌（症）', 73, 'junior', 'wy7B', 'U1', 'wordlist', 'p.13', 'high', 'junior_fltrp'),
('wy7B-U1-0074', 7, 'wig', 'n.', '/wɪɡ/', '假发', 74, 'junior', 'wy7B', 'U1', 'wordlist', 'p.13', 'high', 'junior_fltrp'),
('wy7B-U1-0075', 7, 'smart', 'adj.', '/smɑːt/', '聪颖的，机灵的；明智的', 75, 'junior', 'wy7B', 'U1', 'wordlist', 'p.13', 'high', 'junior_fltrp'),
('wy7B-U1-0076', 7, 'smile', 'v.', '/smaɪl/', '微笑', 76, 'junior', 'wy7B', 'U1', 'wordlist', 'p.13', 'high', 'junior_fltrp'),
('wy7B-U2-0001', 7, 'last but not least', NULL, NULL, '最后但同样重要的（一点）', 77, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0002', 7, 'marathon', 'n.', '/ˈmærəθən/', '马拉松赛跑', 78, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0003', 7, 'however', 'adv.', '/haʊˈevə/', '然而', 79, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0004', 7, 'still', 'adv.', '/stɪl/', '还，仍然', 80, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0005', 7, 'metre', 'n.', '/ˈmiːtə/', '（书面缩写为 m）米，公尺', 81, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0006', 7, 'line', 'n.', '/laɪn/', '线', 82, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0007', 7, 'breath', 'n.', '/breθ/', '呼出的气；吸入的气', 83, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0008', 7, 'hold your breath', NULL, NULL, '屏住呼吸；屏息静气', 84, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0009', 7, 'would', 'v.', '/wʊd/', '会', 85, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0010', 7, 'confident', 'adj.', '/ˈkɒnfɪdənt/', '有信心的，自信的', 86, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0011', 7, 'stomachache', 'n.', '/ˈstʌməkeɪk/', '胃痛；肚子痛', 87, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0012', 7, 'shall', 'v.', '/ʃəl/', '要不要……？', 88, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0013', 7, 'either', 'pron.', '/ˈaɪðə/', '（两者中的）任何一个', 89, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0014', 7, 'choice', 'n.', '/tʃɔɪs/', '选择；选择权', 90, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0015', 7, 'seem', 'v.', '/siːm/', '看来，似乎，好像', 91, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0016', 7, 'someone', 'pron.', '/ˈsʌmwʌn/', '某人，有人', 92, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0017', 7, 'neither', 'pron.', '/ˈnaɪðə/', '两者都不（的），两者中无一的', 93, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0018', 7, 'cheer', 'v.', '/tʃɪə/', '（为……）欢呼，喝彩；（为……）加油', 94, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0019', 7, 'cross', 'v.', '/krɒs/', '穿过，越过，跑过（终点线、小径等）', 95, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0020', 7, 'lifelong', 'adj.', '/ˈlaɪflɒŋ/', '终身的，毕生的', 96, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0021', 7, 'dream', 'n.', '/driːm/', '梦想，愿望，理想', 97, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0022', 7, 'past', 'prep.', '/pɑːst/', '经过', 98, 'junior', 'wy7B', 'U2', 'wordlist', 'p.20', 'high', 'junior_fltrp'),
('wy7B-U2-0023', 7, 'record', 'n.', '/ˈrekɔːd/', '记录，记载', 99, 'junior', 'wy7B', 'U2', 'wordlist', 'p.21', 'high', 'junior_fltrp'),
('wy7B-U2-0024', 7, 'none', 'pron.', '/nʌn/', '全无，没有一点', 100, 'junior', 'wy7B', 'U2', 'wordlist', 'p.21', 'high', 'junior_fltrp'),
('wy7B-U2-0025', 7, 'member', 'n.', '/ˈmembə/', '成员', 101, 'junior', 'wy7B', 'U2', 'wordlist', 'p.21', 'high', 'junior_fltrp'),
('wy7B-U2-0026', 7, 'moment', 'n.', '/ˈməʊmənt/', '某一时刻', 102, 'junior', 'wy7B', 'U2', 'wordlist', 'p.21', 'high', 'junior_fltrp'),
('wy7B-U2-0027', 7, 'if', 'conj.', '/ɪf/', '假若，要是，如果', 103, 'junior', 'wy7B', 'U2', 'wordlist', 'p.21', 'high', 'junior_fltrp'),
('wy7B-U2-0028', 7, 'possible', 'adj.', '/ˈpɒsəbəl/', '可能的，可能做到的，可能实现的', 104, 'junior', 'wy7B', 'U2', 'wordlist', 'p.21', 'high', 'junior_fltrp'),
('wy7B-U2-0029', 7, 'purpose', 'n.', '/ˈpɜːpəs/', '目的，意图', 105, 'junior', 'wy7B', 'U2', 'wordlist', 'p.22', 'high', 'junior_fltrp'),
('wy7B-U2-0030', 7, 'raise', 'v.', '/reɪz/', '筹集；筹募', 106, 'junior', 'wy7B', 'U2', 'wordlist', 'p.22', 'high', 'junior_fltrp'),
('wy7B-U2-0031', 7, 'charity', 'n.', '/ˈtʃærəti/', '慈善机构', 107, 'junior', 'wy7B', 'U2', 'wordlist', 'p.22', 'high', 'junior_fltrp'),
('wy7B-U2-0032', 7, 'encourage', 'v.', '/ɪnˈkʌrɪdʒ/', '鼓励，激励', 108, 'junior', 'wy7B', 'U2', 'wordlist', 'p.22', 'high', 'junior_fltrp'),
('wy7B-U2-0033', 7, 'teach', 'v.', '/tiːtʃ/', '教', 109, 'junior', 'wy7B', 'U2', 'wordlist', 'p.22', 'high', 'junior_fltrp'),
('wy7B-U2-0034', 7, 'note', 'n.', '/nəʊt/', '笔记', 110, 'junior', 'wy7B', 'U2', 'wordlist', 'p.22', 'high', 'junior_fltrp'),
('wy7B-U2-0035', 7, 'during', 'prep.', '/ˈdjʊərɪŋ/', '在……期间', 111, 'junior', 'wy7B', 'U2', 'wordlist', 'p.22', 'high', 'junior_fltrp'),
('wy7B-U2-0036', 7, 'consider', 'v.', '/kənˈsɪdə/', '考虑，细想', 112, 'junior', 'wy7B', 'U2', 'wordlist', 'p.22', 'high', 'junior_fltrp'),
('wy7B-U2-0037', 7, 'both', 'pron.', '/bəʊθ/', '两者，双方，两个都', 113, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0038', 7, 'sink', 'v.', '/sɪŋk/', '下沉，沉没', 114, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0039', 7, 'sink or swim', NULL, NULL, '自生自灭，成败全靠自己', 115, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0040', 7, 'as', 'prep.', '/əz/', '在某一年龄段时', 116, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0041', 7, 'surfer', 'n.', '/ˈsɜːfə/', '冲浪者', 117, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0042', 7, 'shark', 'n.', '/ʃɑːk/', '鲨（鱼）', 118, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0043', 7, 'attack', 'v.', '/əˈtæk/', '袭击，殴打；破坏', 119, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0044', 7, 'nearly', 'adv.', '/ˈnɪəli/', '几乎，差不多，将近', 120, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0045', 7, 'die', 'v.', '/daɪ/', '死去，死亡', 121, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0046', 7, 'surfing', 'n.', '/ˈsɜːfɪŋ/', '冲浪（运动）', 122, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0047', 7, 'competition', 'n.', '/ˌkɒmpəˈtɪʃən/', '比赛', 123, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0048', 7, 'compare', 'v.', '/kəmˈpeə/', '相比较；可媲美', 124, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0049', 7, 'achievement', 'n.', '/əˈtʃiːvmənt/', '成绩；成就', 125, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0050', 7, 'surfboard', 'n.', '/ˈsɜːfbɔːd/', '冲浪板', 126, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0051', 7, 'ride', 'v.', '/raɪd/', '漂浮', 127, 'junior', 'wy7B', 'U2', 'wordlist', 'p.23', 'high', 'junior_fltrp'),
('wy7B-U2-0052', 7, 'lover', 'n.', '/ˈlʌvə/', '爱好者', 128, 'junior', 'wy7B', 'U2', 'wordlist', 'p.24', 'high', 'junior_fltrp'),
('wy7B-U2-0053', 7, 'gold', 'adj.', '/ɡəʊld/', '金质的', 129, 'junior', 'wy7B', 'U2', 'wordlist', 'p.25', 'high', 'junior_fltrp'),
('wy7B-U2-0054', 7, 'medal', 'n.', '/ˈmedl/', '奖牌；勋章', 130, 'junior', 'wy7B', 'U2', 'wordlist', 'p.25', 'high', 'junior_fltrp'),
('wy7B-U2-0055', 7, 'proud', 'adj.', '/praʊd/', '自豪的，得意的', 131, 'junior', 'wy7B', 'U2', 'wordlist', 'p.26', 'high', 'junior_fltrp'),
('wy7B-U2-0056', 7, 'fit', 'adj.', '/fɪt/', '健壮的，健康的', 132, 'junior', 'wy7B', 'U2', 'wordlist', 'p.27', 'high', 'junior_fltrp'),
('wy7B-U2-0057', 7, 'final', 'n.', '/ˈfaɪnəl/', '决赛', 133, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0058', 7, 'team', 'n.', '/tiːm/', '（游戏或体育比赛的）队', 134, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0059', 7, 'even', 'adv.', '/ˈiːvən/', '甚至', 135, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0060', 7, 'worse', 'adv.', '/wɜːs/', '（badly 的比较级）更严重地；更厉害地', 136, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0061', 7, 'pay attention', NULL, NULL, '认真看，仔细听，用心思考', 137, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0062', 7, 'continue', 'v.', '/kənˈtɪnjuː/', '（使）继续；（使）延续', 138, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0063', 7, 'brave', 'adj.', '/breɪv/', '勇敢的，无畏的', 139, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0064', 7, 'action', 'n.', '/ˈækʃən/', '行为', 140, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0065', 7, 'fight', 'v.', '/faɪt/', '努力争取，为（……）斗争', 141, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0066', 7, 'score', 'v.', '/skɔː/', '（在运动、比赛或考试中）得（分）', 142, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0067', 7, 'goal', 'n.', '/ɡəʊl/', '进球；进球得分', 143, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0068', 7, 'victory', 'n.', '/ˈvɪktəri/', '胜利，成功，赢', 144, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0069', 7, 'lead', 'v.', '/liːd/', '带路，领路；引领', 145, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0070', 7, 'international', 'adj.', '/ˌɪntəˈnæʃənəl/', '国际的', 146, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0071', 7, 'chance', 'n.', '/tʃɑːns/', '机会', 147, 'junior', 'wy7B', 'U2', 'wordlist', 'p.28', 'high', 'junior_fltrp'),
('wy7B-U2-0072', 7, 'improve', 'v.', '/ɪmˈpruːv/', '改善，改进；变得更好', 148, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0073', 7, 'create', 'v.', '/kriˈeɪt/', '创造', 149, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0074', 7, 'wonder', 'v.', '/ˈwʌndə/', '想要知道', 150, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0075', 7, 'success', 'n.', '/səkˈses/', '成功，胜利，成就', 151, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0076', 7, 'explain', 'v.', '/ɪkˈspleɪn/', '解释，说明', 152, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0077', 7, 'simple', 'adj.', '/ˈsɪmpəl/', '简单的', 153, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0078', 7, 'same', 'adj.', '/seɪm/', '相同的，同一个的', 154, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0079', 7, 'courage', 'n.', '/ˈkʌrɪdʒ/', '勇气，胆量，勇敢', 155, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0080', 7, 'ahead', 'adv.', '/əˈhed/', '在前面', 156, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U2-0081', 7, 'spirit', 'n.', '/ˈspɪrɪt/', '（某一特定历史时期、地方或群体的）精神，风气', 157, 'junior', 'wy7B', 'U2', 'wordlist', 'p.29', 'high', 'junior_fltrp'),
('wy7B-U3-0001', 7, 'delicious', 'adj.', '/dɪˈlɪʃəs/', '令人愉快的；美味的', 158, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0002', 7, 'certain', 'adj.', '/ˈsɜːtn/', '某个；某些', 159, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0003', 7, 'mine', 'pron.', '/maɪn/', '我的（东西）', 160, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0004', 7, 'beef', 'n.', '/biːf/', '牛肉', 161, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0005', 7, 'carrot', 'n.', '/ˈkærət/', '胡萝卜', 162, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0006', 7, 'mutton', 'n.', '/ˈmʌtn/', '羊肉', 163, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0007', 7, 'fat', 'adj.', '/fæt/', '肥胖的', 164, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0008', 7, 'hen', 'n.', '/hen/', '母鸡', 165, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0009', 7, 'pot', 'n.', '/pɒt/', '（通常为金属制成的圆而深的）锅', 166, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0010', 7, 'onion', 'n.', '/ˈʌnjən/', '洋葱（头）', 167, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0011', 7, 'pancake', 'n.', '/ˈpænkeɪk/', '薄煎（烤，烙）饼', 168, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0012', 7, 'porridge', 'n.', '/ˈpɒrɪdʒ/', '粥', 169, 'junior', 'wy7B', 'U3', 'wordlist', 'p.36', 'high', 'junior_fltrp'),
('wy7B-U3-0013', 7, 'sweet', 'adj.', '/swiːt/', '甜的', 170, 'junior', 'wy7B', 'U3', 'wordlist', 'p.37', 'high', 'junior_fltrp'),
('wy7B-U3-0014', 7, 'plain', 'adj.', '/pleɪn/', '无装饰的，简单的，朴素的，单纯的', 171, 'junior', 'wy7B', 'U3', 'wordlist', 'p.37', 'high', 'junior_fltrp'),
('wy7B-U3-0015', 7, 'menu', 'n.', '/ˈmenjuː/', '（尤指餐馆的）菜单', 172, 'junior', 'wy7B', 'U3', 'wordlist', 'p.37', 'high', 'junior_fltrp'),
('wy7B-U3-0016', 7, 'medicine', 'n.', '/ˈmedsən/', '药，药物（尤指口服的药水）', 173, 'junior', 'wy7B', 'U3', 'wordlist', 'p.37', 'high', 'junior_fltrp'),
('wy7B-U3-0017', 7, 'than', 'prep.', '/ðən/', '比', 174, 'junior', 'wy7B', 'U3', 'wordlist', 'p.37', 'high', 'junior_fltrp'),
('wy7B-U3-0018', 7, 'pill', 'n.', '/pɪl/', '药丸；药片', 175, 'junior', 'wy7B', 'U3', 'wordlist', 'p.37', 'high', 'junior_fltrp'),
('wy7B-U3-0019', 7, 'remain', 'v.', '/rɪˈmeɪn/', '继续，依然（保持某种状态）', 176, 'junior', 'wy7B', 'U3', 'wordlist', 'p.37', 'high', 'junior_fltrp'),
('wy7B-U3-0020', 7, 'another', 'det.', '/əˈnʌðə/', '另一个，别的', 177, 'junior', 'wy7B', 'U3', 'wordlist', 'p.38', 'high', 'junior_fltrp'),
('wy7B-U3-0021', 7, 'connection', 'n.', '/kəˈnekʃən/', '（两个事实、观点、事件等之间的）联系，关联', 178, 'junior', 'wy7B', 'U3', 'wordlist', 'p.38', 'high', 'junior_fltrp'),
('wy7B-U3-0022', 7, 'prove', 'v.', '/pruːv/', '证明，证实', 179, 'junior', 'wy7B', 'U3', 'wordlist', 'p.38', 'high', 'junior_fltrp'),
('wy7B-U3-0023', 7, 'similar', 'adj.', '/ˈsɪmələ/', '相似的，近似的，类似的', 180, 'junior', 'wy7B', 'U3', 'wordlist', 'p.38', 'high', 'junior_fltrp'),
('wy7B-U3-0024', 7, 'special', 'adj.', '/ˈspeʃəl/', '特殊的，特别的', 181, 'junior', 'wy7B', 'U3', 'wordlist', 'p.38', 'high', 'junior_fltrp'),
('wy7B-U3-0025', 7, 'order', 'n.', '/ˈɔːdə/', '顺序，次序', 182, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0026', 7, 'pie', 'n.', '/paɪ/', '水果馅饼，派', 183, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0027', 7, 'sandwich', 'n.', '/ˈsænwɪdʒ/', '三明治，夹心面包', 184, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0028', 7, 'circle', 'v.', '/ˈsɜːkəl/', '圈出', 185, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0029', 7, 'scramble', 'v.', '/ˈskræmbəl/', '炒（蛋）', 186, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0030', 7, 'slice', 'n.', '/slaɪs/', '片，薄片，切片', 187, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0031', 7, 'beat', 'v.', '/biːt/', '搅拌，搅打', 188, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0032', 7, 'add', 'v.', '/æd/', '添加，增加', 189, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0033', 7, 'salt', 'n.', '/sɔːlt/', '盐，食盐', 190, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0034', 7, 'pepper', 'n.', '/ˈpepə/', '胡椒粉', 191, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0035', 7, 'oil', 'n.', '/ɔɪl/', '植物油，动物油', 192, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0036', 7, 'pan', 'n.', '/pæn/', '（长柄有盖的）锅，平底锅', 193, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0037', 7, 'mixture', 'n.', '/ˈmɪkstʃə/', '（尤指烹饪中的）混合液，混合料', 194, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0038', 7, 'stir', 'v.', '/stɜː/', '搅，搅拌，搅动', 195, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0039', 7, 'until', 'conj.', '/ʌnˈtɪl/', '直到……为止', 196, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0040', 7, 'golden', 'adj.', '/ˈɡəʊldən/', '金色的，金黄色的', 197, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0041', 7, 'plate', 'n.', '/pleɪt/', '盘，碟', 198, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0042', 7, 'loud', 'adj.', '/laʊd/', '大声的，喧闹的', 199, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0043', 7, 'heat', 'n.', '/hiːt/', '（烹饪或加热时的）温度', 200, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0044', 7, 'firm', 'adj.', '/fɜːm/', '结实的，坚实的', 201, 'junior', 'wy7B', 'U3', 'wordlist', 'p.39', 'high', 'junior_fltrp'),
('wy7B-U3-0045', 7, 'recipe', 'n.', '/ˈresəpi/', '烹饪法；食谱', 202, 'junior', 'wy7B', 'U3', 'wordlist', 'p.40', 'high', 'junior_fltrp'),
('wy7B-U3-0046', 7, 'ingredient', 'n.', '/ɪnˈɡriːdiənt/', '（烹调用的）成分，食材', 203, 'junior', 'wy7B', 'U3', 'wordlist', 'p.40', 'high', 'junior_fltrp'),
('wy7B-U3-0047', 7, 'step', 'n.', '/step/', '步骤', 204, 'junior', 'wy7B', 'U3', 'wordlist', 'p.40', 'high', 'junior_fltrp'),
('wy7B-U3-0048', 7, 'diet', 'n.', '/ˈdaɪət/', '节食；规定饮食', 205, 'junior', 'wy7B', 'U3', 'wordlist', 'p.41', 'high', 'junior_fltrp'),
('wy7B-U3-0049', 7, 'restaurant', 'n.', '/ˈrestərɒnt/', '饭店，餐馆', 206, 'junior', 'wy7B', 'U3', 'wordlist', 'p.41', 'high', 'junior_fltrp'),
('wy7B-U3-0050', 7, 'salad', 'n.', '/ˈsæləd/', '（生吃的）蔬菜沙拉', 207, 'junior', 'wy7B', 'U3', 'wordlist', 'p.41', 'high', 'junior_fltrp'),
('wy7B-U3-0051', 7, 'hamburger', 'n.', '/ˈhæmbɜːɡə/', '汉堡包', 208, 'junior', 'wy7B', 'U3', 'wordlist', 'p.42', 'high', 'junior_fltrp'),
('wy7B-U3-0052', 7, 'snack', 'n.', '/snæk/', '（正餐以外的）小吃，点心', 209, 'junior', 'wy7B', 'U3', 'wordlist', 'p.43', 'high', 'junior_fltrp'),
('wy7B-U3-0053', 7, 'chip', 'n.', '/tʃɪp/', '炸马铃薯条', 210, 'junior', 'wy7B', 'U3', 'wordlist', 'p.43', 'high', 'junior_fltrp'),
('wy7B-U3-0054', 7, 'dangerous', 'adj.', '/ˈdeɪndʒərəs/', '危险的，有危害的', 211, 'junior', 'wy7B', 'U3', 'wordlist', 'p.43', 'high', 'junior_fltrp'),
('wy7B-U3-0055', 7, 'border', 'n.', '/ˈbɔːdə/', '边界；边境', 212, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0056', 7, 'Western', 'adj.', '/ˈwestən/', '（观念或方式）西方的，欧美的', 213, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0057', 7, 'dessert', 'n.', '/dɪˈzɜːt/', '（饭后的）甜点，甜食，甜品', 214, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0058', 7, 'actually', 'adv.', '/ˈæktʃuəli/', '实际上，事实上', 215, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0059', 7, 'dynasty', 'n.', '/ˈdɪnəsti/', '朝代', 216, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0060', 7, 'store', 'v.', '/stɔː/', '贮藏，贮存，积蓄', 217, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0061', 7, 'mean', 'v.', '/miːn/', '意思是', 218, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0062', 7, 'modern', 'adj.', '/ˈmɒdn/', '现代的，近代的', 219, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0063', 7, 'folk', 'adj.', '/fəʊk/', '民间的，民俗的', 220, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0064', 7, 'tale', 'n.', '/teɪl/', '故事', 221, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0065', 7, 'emperor', 'n.', '/ˈempərə/', '皇帝', 222, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0066', 7, 'suffer', 'v.', '/ˈsʌfə/', '（身体或精神上）受苦，遭受（痛苦）', 223, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0067', 7, 'stomach', 'n.', '/ˈstʌmək/', '胃', 224, 'junior', 'wy7B', 'U3', 'wordlist', 'p.44', 'high', 'junior_fltrp'),
('wy7B-U3-0068', 7, 'totally', 'adv.', '/ˈtəʊtli/', '完全地，彻底地', 225, 'junior', 'wy7B', 'U3', 'wordlist', 'p.45', 'high', 'junior_fltrp'),
('wy7B-U3-0069', 7, 'Iranian', 'n.', '/ɪˈreɪniən/', '伊朗人', 226, 'junior', 'wy7B', 'U3', 'wordlist', 'p.45', 'high', 'junior_fltrp'),
('wy7B-U3-0070', 7, 'flat', 'adj.', '/flæt/', '平的，平坦的', 227, 'junior', 'wy7B', 'U3', 'wordlist', 'p.45', 'high', 'junior_fltrp'),
('wy7B-U3-0071', 7, 'stone', 'n.', '/stəʊn/', '石块，石子', 228, 'junior', 'wy7B', 'U3', 'wordlist', 'p.45', 'high', 'junior_fltrp'),
('wy7B-U3-0072', 7, 'symbol', 'n.', '/ˈsɪmbəl/', '代表性人物（事物）', 229, 'junior', 'wy7B', 'U3', 'wordlist', 'p.45', 'high', 'junior_fltrp'),
('wy7B-U3-0073', 7, 'American', 'adj.', '/əˈmerɪkən/', '美国的；美国人的', 230, 'junior', 'wy7B', 'U3', 'wordlist', 'p.45', 'high', 'junior_fltrp'),
('wy7B-U3-0074', 7, 'twin', 'adj.', '/twɪn/', '双胞胎之一的', 231, 'junior', 'wy7B', 'U3', 'wordlist', 'p.45', 'high', 'junior_fltrp'),
('wy7B-U3-0075', 7, 'bridge', 'n.', '/brɪdʒ/', '（事物之间的）桥梁，纽带', 232, 'junior', 'wy7B', 'U3', 'wordlist', 'p.45', 'high', 'junior_fltrp'),
('wy7B-U4-0001', 7, 'dull', 'adj.', '/dʌl/', '愚笨的，迟钝的', 233, 'junior', 'wy7B', 'U4', 'wordlist', 'p.53', 'high', 'junior_fltrp'),
('wy7B-U4-0002', 7, 'imagine', 'v.', '/ɪˈmædʒɪn/', '想象', 234, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0003', 7, 'alone', 'adv.', '/əˈləʊn/', '单独，独自', 235, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0004', 7, 'might', 'v.', '/maɪt/', '也许，可能，大概', 236, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0005', 7, 'tool', 'n.', '/tuːl/', '工具', 237, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0006', 7, 'list', 'n.', '/lɪst/', '名单，清单，目录', 238, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0007', 7, 'something', 'pron.', '/ˈsʌmθɪŋ/', '某物；某事；某种东西', 239, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0008', 7, 'novel', 'n.', '/ˈnɒvəl/', '（长篇）小说', 240, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0009', 7, 'magazine', 'n.', '/ˌmæɡəˈziːn/', '杂志，期刊', 241, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0010', 7, 'solar', 'adj.', '/ˈsəʊlə/', '利用太阳能的', 242, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0011', 7, 'media', 'n.', '/ˈmiːdiə/', '媒介物', 243, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0012', 7, 'bored', 'adj.', '/bɔːd/', '厌烦的，不感兴趣的；烦闷的', 244, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0013', 7, 'feeling', 'n.', '/ˈfiːlɪŋ/', '感觉', 245, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0014', 7, 'lift sb''s spirits', NULL, NULL, '使某人开心起来', 246, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0015', 7, 'funny', 'adj.', '/ˈfʌni/', '使人发笑的，有趣的；滑稽的', 247, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0016', 7, 'youthful', 'adj.', '/ˈjuːθfəl/', '年轻的', 248, 'junior', 'wy7B', 'U4', 'wordlist', 'p.52', 'high', 'junior_fltrp'),
('wy7B-U4-0017', 7, 'invite', 'v.', '/ɪnˈvaɪt/', '邀请', 249, 'junior', 'wy7B', 'U4', 'wordlist', 'p.53', 'high', 'junior_fltrp'),
('wy7B-U4-0018', 7, 'number', 'n.', '/ˈnʌmbə/', '数目，数量', 250, 'junior', 'wy7B', 'U4', 'wordlist', 'p.53', 'high', 'junior_fltrp'),
('wy7B-U4-0019', 7, 'a number of', NULL, NULL, '一些', 251, 'junior', 'wy7B', 'U4', 'wordlist', 'p.53', 'high', 'junior_fltrp'),
('wy7B-U4-0020', 7, 'able', 'adj.', '/ˈeɪbəl/', '有能力做……的，会做……的', 252, 'junior', 'wy7B', 'U4', 'wordlist', 'p.53', 'high', 'junior_fltrp'),
('wy7B-U4-0021', 7, 'importance', 'n.', '/ɪmˈpɔːtəns/', '重要（性）', 253, 'junior', 'wy7B', 'U4', 'wordlist', 'p.54', 'high', 'junior_fltrp'),
('wy7B-U4-0022', 7, 'detail', 'n.', '/ˈdiːteɪl/', '细节，细微之处', 254, 'junior', 'wy7B', 'U4', 'wordlist', 'p.54', 'high', 'junior_fltrp'),
('wy7B-U4-0023', 7, 'conclusion', 'n.', '/kənˈkluːʒən/', '结论', 255, 'junior', 'wy7B', 'U4', 'wordlist', 'p.54', 'high', 'junior_fltrp'),
('wy7B-U4-0024', 7, 'open-minded', 'adj.', '/ˌəʊpən ˈmaɪndɪd/', '愿意考虑不同意见的；思想开明的', 256, 'junior', 'wy7B', 'U4', 'wordlist', 'p.54', 'high', 'junior_fltrp'),
('wy7B-U4-0025', 7, 'ourselves', 'pron.', '/aʊəˈselvz/', '我们自己', 257, 'junior', 'wy7B', 'U4', 'wordlist', 'p.54', 'high', 'junior_fltrp'),
('wy7B-U4-0026', 7, 'else', 'adv.', '/els/', '另外，其他；别的，另外的（用于表示不同的人、事物、地方等）', 258, 'junior', 'wy7B', 'U4', 'wordlist', 'p.54', 'high', 'junior_fltrp'),
('wy7B-U4-0027', 7, 'differently', 'adv.', '/ˈdɪfrəntli/', '不同地；相异地', 259, 'junior', 'wy7B', 'U4', 'wordlist', 'p.54', 'high', 'junior_fltrp'),
('wy7B-U4-0028', 7, 'instruction', 'n.', '/ɪnˈstrʌkʃən/', '命令，指示', 260, 'junior', 'wy7B', 'U4', 'wordlist', 'p.55', 'high', 'junior_fltrp'),
('wy7B-U4-0029', 7, 'daily', 'adj.', '/ˈdeɪli/', '每日，每天', 261, 'junior', 'wy7B', 'U4', 'wordlist', 'p.55', 'high', 'junior_fltrp'),
('wy7B-U4-0030', 7, 'daily life', NULL, NULL, '日常生活', 262, 'junior', 'wy7B', 'U4', 'wordlist', 'p.55', 'high', 'junior_fltrp'),
('wy7B-U4-0031', 7, 'while', 'conj.', '/waɪl/', '当……时，在……时', 263, 'junior', 'wy7B', 'U4', 'wordlist', 'p.55', 'high', 'junior_fltrp'),
('wy7B-U4-0032', 7, 'housework', 'n.', '/ˈhaʊswɜːk/', '家务（劳动）', 264, 'junior', 'wy7B', 'U4', 'wordlist', 'p.55', 'high', 'junior_fltrp'),
('wy7B-U4-0033', 7, 'explore', 'v.', '/ɪkˈsplɔː/', '探讨，探究', 265, 'junior', 'wy7B', 'U4', 'wordlist', 'p.55', 'high', 'junior_fltrp'),
('wy7B-U4-0034', 7, 'discussion', 'n.', '/dɪˈskʌʃən/', '讨论，谈论，商讨', 266, 'junior', 'wy7B', 'U4', 'wordlist', 'p.55', 'high', 'junior_fltrp'),
('wy7B-U4-0035', 7, 'unforgettable', 'adj.', '/ˌʌnfəˈɡetəbəl/', '难以忘怀的', 267, 'junior', 'wy7B', 'U4', 'wordlist', 'p.55', 'high', 'junior_fltrp'),
('wy7B-U4-0036', 7, 'discover', 'v.', '/dɪˈskʌvə/', '发现，找到', 268, 'junior', 'wy7B', 'U4', 'wordlist', 'p.57', 'high', 'junior_fltrp'),
('wy7B-U4-0037', 7, 'large', 'adj.', '/lɑːdʒ/', '巨大的', 269, 'junior', 'wy7B', 'U4', 'wordlist', 'p.57', 'high', 'junior_fltrp'),
('wy7B-U4-0038', 7, 'mosquito', 'n.', '/məˈskiːtəʊ/', '蚊子', 270, 'junior', 'wy7B', 'U4', 'wordlist', 'p.57', 'high', 'junior_fltrp'),
('wy7B-U4-0039', 7, 'insect', 'n.', '/ˈɪnsekt/', '昆虫', 271, 'junior', 'wy7B', 'U4', 'wordlist', 'p.57', 'high', 'junior_fltrp'),
('wy7B-U4-0040', 7, 'set', 'v.', '/set/', '确立', 272, 'junior', 'wy7B', 'U4', 'wordlist', 'p.58', 'high', 'junior_fltrp'),
('wy7B-U4-0041', 7, 'butterfly', 'n.', '/ˈbʌtəflaɪ/', '蝴蝶', 273, 'junior', 'wy7B', 'U4', 'wordlist', 'p.59', 'high', 'junior_fltrp'),
('wy7B-U4-0042', 7, 'prince', 'n.', '/prɪns/', '王子', 274, 'junior', 'wy7B', 'U4', 'wordlist', 'p.59', 'high', 'junior_fltrp'),
('wy7B-U4-0043', 7, 'monster', 'n.', '/ˈmɒnstə/', '妖怪；怪兽，怪物', 275, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0044', 7, 'ever', 'adv.', '/ˈevə/', '在任何时候', 276, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0045', 7, 'notice', 'v.', '/ˈnəʊtɪs/', '看到；听到；感觉到；注意到', 277, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0046', 7, 'social', 'adj.', '/ˈsəʊʃəl/', '社交的', 278, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0047', 7, 'screen', 'n.', '/skriːn/', '屏幕', 279, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0048', 7, 'couch', 'n.', '/kaʊtʃ/', '长沙发', 280, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0049', 7, 'couch potato', NULL, NULL, '老泡在电视机前的人', 281, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0050', 7, 'sore', 'adj.', '/sɔː/', '疼痛的；酸痛的', 282, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0051', 7, 'neck', 'n.', '/nek/', '颈，脖子', 283, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0052', 7, 'deaf', 'adj.', '/def/', '不愿听的，不肯听取的', 284, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0053', 7, 'real', 'adj.', '/rɪəl/', '实际存在的，非想象的', 285, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0054', 7, 'balanced', 'adj.', '/ˈbælənst/', '均衡的', 286, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0055', 7, 'outside', 'adv.', '/aʊtˈsaɪd/', '在室外', 287, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0056', 7, 'jog', 'v.', '/dʒɒɡ/', '慢跑', 288, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0057', 7, 'fresh', 'adj.', '/freʃ/', '新鲜的', 289, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0058', 7, 'tennis', 'n.', '/ˈtenɪs/', '网球（运动）', 290, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0059', 7, 'hike', 'v.', '/haɪk/', '（在……）徒步旅行，远足', 291, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U4-0060', 7, 'ours', 'pron.', '/aʊəz/', '（属于）我们的', 292, 'junior', 'wy7B', 'U4', 'wordlist', 'p.61', 'high', 'junior_fltrp'),
('wy7B-U5-0001', 7, 'plateau', 'n.', '/ˈplætəʊ/', '高原', 293, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0002', 7, 'cloud', 'n.', '/klaʊd/', '云', 294, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0003', 7, 'soft', 'adj.', '/sɒft/', '柔软的', 295, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0004', 7, 'brightly', 'adv.', '/ˈbraɪtli/', '明亮地', 296, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0005', 7, 'lotus', 'n.', '/ˈləʊtəs/', '莲花（图案），荷花（图案）', 297, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0006', 7, 'sky', 'n.', '/skaɪ/', '天，天空', 298, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0007', 7, 'calm', 'adj.', '/kɑːm/', '镇静的，沉着的；心平气和的', 299, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0008', 7, 'above', 'prep.', '/əˈbʌv/', '在（……）上方', 300, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0009', 7, 'express', 'v.', '/ɪkˈspres/', '表达；表示；表现', 301, 'junior', 'wy7B', 'U5', 'wordlist', 'p.68', 'high', 'junior_fltrp'),
('wy7B-U5-0010', 7, 'grassland', 'n.', '/ˈɡrɑːslænd/', '草原', 302, 'junior', 'wy7B', 'U5', 'wordlist', 'p.69', 'high', 'junior_fltrp'),
('wy7B-U5-0011', 7, 'field', 'n.', '/fiːld/', '田地，田野', 303, 'junior', 'wy7B', 'U5', 'wordlist', 'p.69', 'high', 'junior_fltrp'),
('wy7B-U5-0012', 7, 'few', 'adj.', '/fjuː/', '很少，不多', 304, 'junior', 'wy7B', 'U5', 'wordlist', 'p.69', 'high', 'junior_fltrp'),
('wy7B-U5-0013', 7, 'present', 'n.', '/ˈprezənt/', '礼物，赠品', 305, 'junior', 'wy7B', 'U5', 'wordlist', 'p.69', 'high', 'junior_fltrp'),
('wy7B-U5-0014', 7, 'likely', 'adj.', '/ˈlaɪkli/', '可能的；可能发生的；可能属实的', 306, 'junior', 'wy7B', 'U5', 'wordlist', 'p.70', 'high', 'junior_fltrp'),
('wy7B-U5-0015', 7, 'local', 'adj.', '/ˈləʊkəl/', '地方性的，当（本）地的', 307, 'junior', 'wy7B', 'U5', 'wordlist', 'p.70', 'high', 'junior_fltrp'),
('wy7B-U5-0016', 7, 'designer', 'n.', '/dɪˈzaɪnə/', '（服装、家具、设备等的）设计师，设计者', 308, 'junior', 'wy7B', 'U5', 'wordlist', 'p.70', 'high', 'junior_fltrp'),
('wy7B-U5-0017', 7, 'guide', 'n.', '/ɡaɪd/', '指南，指南手册', 309, 'junior', 'wy7B', 'U5', 'wordlist', 'p.70', 'high', 'junior_fltrp'),
('wy7B-U5-0018', 7, 'describe', 'v.', '/dɪˈskraɪb/', '描述，描写', 310, 'junior', 'wy7B', 'U5', 'wordlist', 'p.70', 'high', 'junior_fltrp'),
('wy7B-U5-0019', 7, 'landscape', 'n.', '/ˈlændskeɪp/', '（陆上的）风景，景致，景色', 311, 'junior', 'wy7B', 'U5', 'wordlist', 'p.70', 'high', 'junior_fltrp'),
('wy7B-U5-0020', 7, 'common', 'adj.', '/ˈkɒmən/', '常见的，普遍的', 312, 'junior', 'wy7B', 'U5', 'wordlist', 'p.70', 'high', 'junior_fltrp'),
('wy7B-U5-0021', 7, 'Mount', 'n.', '/maʊnt/', '（书面缩写为 Mt）（用作山名的一部分）……山，……峰', 313, 'junior', 'wy7B', 'U5', 'wordlist', 'p.71', 'high', 'junior_fltrp'),
('wy7B-U5-0022', 7, 'tide', 'n.', '/taɪd/', '海潮，潮汐', 314, 'junior', 'wy7B', 'U5', 'wordlist', 'p.71', 'high', 'junior_fltrp'),
('wy7B-U5-0023', 7, 'exhibition', 'n.', '/ˌeksəˈbɪʃən/', '展览（会）', 315, 'junior', 'wy7B', 'U5', 'wordlist', 'p.73', 'high', 'junior_fltrp'),
('wy7B-U5-0024', 7, 'tour', 'n.', '/tʊə/', '参观，游览', 316, 'junior', 'wy7B', 'U5', 'wordlist', 'p.74', 'high', 'junior_fltrp'),
('wy7B-U5-0025', 7, 'pound', 'n.', '/paʊnd/', '英镑', 317, 'junior', 'wy7B', 'U5', 'wordlist', 'p.74', 'high', 'junior_fltrp'),
('wy7B-U5-0026', 7, 'lungfish', 'n.', '/ˈlʌŋfɪʃ/', '肺鱼', 318, 'junior', 'wy7B', 'U5', 'wordlist', 'p.75', 'high', 'junior_fltrp'),
('wy7B-U5-0027', 7, 'lung', 'n.', '/lʌŋ/', '肺', 319, 'junior', 'wy7B', 'U5', 'wordlist', 'p.75', 'high', 'junior_fltrp'),
('wy7B-U5-0028', 7, 'scientist', 'n.', '/ˈsaɪəntɪst/', '科学家', 320, 'junior', 'wy7B', 'U5', 'wordlist', 'p.75', 'high', 'junior_fltrp'),
('wy7B-U5-0029', 7, 'behaviour', 'n.', '/bɪˈheɪvjə/', '行为，举止', 321, 'junior', 'wy7B', 'U5', 'wordlist', 'p.75', 'high', 'junior_fltrp'),
('wy7B-U5-0030', 7, 'develop', 'v.', '/dɪˈveləp/', '（使）成长，（使）发展', 322, 'junior', 'wy7B', 'U5', 'wordlist', 'p.75', 'high', 'junior_fltrp'),
('wy7B-U5-0031', 7, 'land', 'n.', '/lænd/', '陆地', 323, 'junior', 'wy7B', 'U5', 'wordlist', 'p.75', 'high', 'junior_fltrp'),
('wy7B-U5-0032', 7, 'aloud', 'adv.', '/əˈlaʊd/', '出声地', 324, 'junior', 'wy7B', 'U5', 'wordlist', 'p.77', 'high', 'junior_fltrp'),
('wy7B-U5-0033', 7, 'salty', 'adj.', '/ˈsɔːlti/', '咸的，含盐的', 325, 'junior', 'wy7B', 'U5', 'wordlist', 'p.76', 'high', 'junior_fltrp'),
('wy7B-U5-0034', 7, 'lie', 'v.', '/laɪ/', '躺，平卧', 326, 'junior', 'wy7B', 'U5', 'wordlist', 'p.76', 'high', 'junior_fltrp'),
('wy7B-U5-0035', 7, 'surface', 'n.', '/ˈsɜːfɪs/', '表面，面', 327, 'junior', 'wy7B', 'U5', 'wordlist', 'p.76', 'high', 'junior_fltrp'),
('wy7B-U5-0036', 7, 'level', 'n.', '/ˈlevəl/', '水平高度；相对高度', 328, 'junior', 'wy7B', 'U5', 'wordlist', 'p.76', 'high', 'junior_fltrp'),
('wy7B-U5-0037', 7, 'less', 'det.', '/les/', '不那么多，更（较）少', 329, 'junior', 'wy7B', 'U5', 'wordlist', 'p.76', 'high', 'junior_fltrp'),
('wy7B-U5-0038', 7, 'suggest', 'v.', '/səˈdʒest/', '暗示，暗指', 330, 'junior', 'wy7B', 'U5', 'wordlist', 'p.77', 'high', 'junior_fltrp'),
('wy7B-U5-0039', 7, 'such as', NULL, NULL, '像，诸如，例如', 331, 'junior', 'wy7B', 'U5', 'wordlist', 'p.77', 'high', 'junior_fltrp'),
('wy7B-U5-0040', 7, 'snake', 'n.', '/sneɪk/', '蛇', 332, 'junior', 'wy7B', 'U5', 'wordlist', 'p.77', 'high', 'junior_fltrp'),
('wy7B-U5-0041', 7, 'wood', 'n.', '/wʊd/', '木头；木材，木料', 333, 'junior', 'wy7B', 'U5', 'wordlist', 'p.77', 'high', 'junior_fltrp'),
('wy7B-U5-0042', 7, 'disappear', 'v.', '/ˌdɪsəˈpɪə/', '消失，不见', 334, 'junior', 'wy7B', 'U5', 'wordlist', 'p.77', 'high', 'junior_fltrp'),
('wy7B-U5-0043', 7, 'glacier', 'n.', '/ˈɡlæsiə/', '冰川', 335, 'junior', 'wy7B', 'U5', 'wordlist', 'p.77', 'high', 'junior_fltrp'),
('wy7B-U5-0044', 7, 'national', 'adj.', '/ˈnæʃənəl/', '国家的，全国性的', 336, 'junior', 'wy7B', 'U5', 'wordlist', 'p.77', 'high', 'junior_fltrp'),
('wy7B-U6-0001', 7, 'airport', 'n.', '/ˈeəpɔːt/', '机场，航空站（港）', 337, 'junior', 'wy7B', 'U6', 'wordlist', 'p.84', 'high', 'junior_fltrp'),
('wy7B-U6-0002', 7, 'burn', 'v.', '/bɜːn/', '（使）（身体部位）灼痛，（使）火辣辣地痛', 338, 'junior', 'wy7B', 'U6', 'wordlist', 'p.84', 'high', 'junior_fltrp'),
('wy7B-U6-0003', 7, 'expect', 'v.', '/ɪkˈspekt/', '预料，预期，预计', 339, 'junior', 'wy7B', 'U6', 'wordlist', 'p.84', 'high', 'junior_fltrp'),
('wy7B-U6-0004', 7, 'deep', 'adj.', '/diːp/', '（呼吸或叹息）深深的', 340, 'junior', 'wy7B', 'U6', 'wordlist', 'p.84', 'high', 'junior_fltrp'),
('wy7B-U6-0005', 7, 'lemon', 'n.', '/ˈlemən/', '柠檬', 341, 'junior', 'wy7B', 'U6', 'wordlist', 'p.84', 'high', 'junior_fltrp'),
('wy7B-U6-0006', 7, 'reply', 'v.', '/rɪˈplaɪ/', '回答，答复', 342, 'junior', 'wy7B', 'U6', 'wordlist', 'p.85', 'high', 'junior_fltrp'),
('wy7B-U6-0007', 7, 'mouthful', 'n.', '/ˈmaʊθfʊl/', '（食物或饮料的）一口，一满口', 343, 'junior', 'wy7B', 'U6', 'wordlist', 'p.85', 'high', 'junior_fltrp'),
('wy7B-U6-0008', 7, 'surprisingly', 'adv.', '/səˈpraɪzɪŋli/', '惊人地，使人吃惊地，出人意料地', 344, 'junior', 'wy7B', 'U6', 'wordlist', 'p.85', 'high', 'junior_fltrp'),
('wy7B-U6-0009', 7, 'mask', 'n.', '/mɑːsk/', '假面具，假面', 345, 'junior', 'wy7B', 'U6', 'wordlist', 'p.85', 'high', 'junior_fltrp'),
('wy7B-U6-0010', 7, 'normal', 'adj.', '/ˈnɔːməl/', '正常的', 346, 'junior', 'wy7B', 'U6', 'wordlist', 'p.85', 'high', 'junior_fltrp'),
('wy7B-U6-0011', 7, 'ancient', 'adj.', '/ˈeɪnʃənt/', '古代的', 347, 'junior', 'wy7B', 'U6', 'wordlist', 'p.85', 'high', 'junior_fltrp'),
('wy7B-U6-0012', 7, 'further', 'adv.', '/ˈfɜːðə/', '更远', 348, 'junior', 'wy7B', 'U6', 'wordlist', 'p.85', 'high', 'junior_fltrp'),
('wy7B-U6-0013', 7, 'look forward to', NULL, NULL, '（兴奋地）期待，盼望', 349, 'junior', 'wy7B', 'U6', 'wordlist', 'p.85', 'high', 'junior_fltrp'),
('wy7B-U6-0014', 7, 'general', 'adj.', '/ˈdʒenərəl/', '大体的，大致的', 350, 'junior', 'wy7B', 'U6', 'wordlist', 'p.86', 'high', 'junior_fltrp'),
('wy7B-U6-0015', 7, 'in general', NULL, NULL, '通常，一般情况下；普遍地，总的说来', 351, 'junior', 'wy7B', 'U6', 'wordlist', 'p.86', 'high', 'junior_fltrp'),
('wy7B-U6-0016', 7, 'curious', 'adj.', '/ˈkjʊəriəs/', '好奇的，好打听的', 352, 'junior', 'wy7B', 'U6', 'wordlist', 'p.86', 'high', 'junior_fltrp'),
('wy7B-U6-0017', 7, 'cultural', 'adj.', '/ˈkʌltʃərəl/', '文化的；文化上的', 353, 'junior', 'wy7B', 'U6', 'wordlist', 'p.86', 'high', 'junior_fltrp'),
('wy7B-U6-0018', 7, 'main', 'adj.', '/meɪn/', '最大的，最重要的', 354, 'junior', 'wy7B', 'U6', 'wordlist', 'p.86', 'high', 'junior_fltrp'),
('wy7B-U6-0019', 7, 'prefer', 'v.', '/prɪˈfɜː/', '更喜欢', 355, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0020', 7, 'interest', 'n.', '/ˈɪntrɪst/', '吸引力', 356, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0021', 7, 'places of interest', NULL, NULL, '名胜', 357, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0022', 7, 'hotel', 'n.', '/həʊˈtel/', '宾馆，酒店', 358, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0023', 7, 'comfortable', 'adj.', '/ˈkʌmftəbəl/', '舒适的，令人舒服的', 359, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0024', 7, 'postcard', 'n.', '/ˈpəʊstkɑːd/', '明信片', 360, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0025', 7, 'waterfall', 'n.', '/ˈwɔːtəfɔːl/', '瀑布', 361, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0026', 7, 'south', 'adj.', '/saʊθ/', '在南方的', 362, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0027', 7, 'powerful', 'adj.', '/ˈpaʊəfəl/', '猛烈的，有力的', 363, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0028', 7, 'thunder', 'n.', '/ˈθʌndə/', '雷声', 364, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0029', 7, 'painting', 'n.', '/ˈpeɪntɪŋ/', '绘画（作品）', 365, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0030', 7, 'roller coaster', NULL, NULL, '过山车，云霄飞车', 366, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0031', 7, 'huge', 'adj.', '/hjuːdʒ/', '巨大的，庞大的；极大量的', 367, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0032', 7, 'ant', 'n.', '/ænt/', '蚂蚁', 368, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0033', 7, 'beauty', 'n.', '/ˈbjuːti/', '美，美丽，漂亮', 369, 'junior', 'wy7B', 'U6', 'wordlist', 'p.87', 'high', 'junior_fltrp'),
('wy7B-U6-0034', 7, 'discuss', 'v.', '/dɪˈskʌs/', '商讨，谈论，讨论', 370, 'junior', 'wy7B', 'U6', 'wordlist', 'p.88', 'high', 'junior_fltrp'),
('wy7B-U6-0035', 7, 'accept', 'v.', '/əkˈsept/', '接受；同意做', 371, 'junior', 'wy7B', 'U6', 'wordlist', 'p.89', 'high', 'junior_fltrp'),
('wy7B-U6-0036', 7, 'award', 'n.', '/əˈwɔːd/', '奖，奖赏；奖品；奖金', 372, 'junior', 'wy7B', 'U6', 'wordlist', 'p.89', 'high', 'junior_fltrp'),
('wy7B-U6-0037', 7, 'traffic', 'n.', '/ˈtræfɪk/', '路上行驶的车辆，交通', 373, 'junior', 'wy7B', 'U6', 'wordlist', 'p.91', 'high', 'junior_fltrp'),
('wy7B-U6-0038', 7, 'unexplored', 'adj.', '/ˌʌnɪkˈsplɔːd/', '（地方）未曾探索的，未经勘察的', 374, 'junior', 'wy7B', 'U6', 'wordlist', 'p.92', 'high', 'junior_fltrp'),
('wy7B-U6-0039', 7, 'seriously', 'adv.', '/ˈsɪəriəsli/', '严重地，非常', 375, 'junior', 'wy7B', 'U6', 'wordlist', 'p.92', 'high', 'junior_fltrp'),
('wy7B-U6-0040', 7, 'achieve', 'v.', '/əˈtʃiːv/', '实现；（尤指经过努力）取得，达到', 376, 'junior', 'wy7B', 'U6', 'wordlist', 'p.92', 'high', 'junior_fltrp'),
('wy7B-U6-0041', 7, 'geographical', 'adj.', '/ˌdʒiːəˈɡræfɪkəl/', '地理的；地理学的', 377, 'junior', 'wy7B', 'U6', 'wordlist', 'p.93', 'high', 'junior_fltrp'),
('wy7B-U6-0042', 7, 'discovery', 'n.', '/dɪsˈkʌvəri/', '被发现的事实（事物）', 378, 'junior', 'wy7B', 'U6', 'wordlist', 'p.93', 'high', 'junior_fltrp'),
('wy7B-U6-0043', 7, 'peak', 'n.', '/piːk/', '山顶，山峰；山，山岳', 379, 'junior', 'wy7B', 'U6', 'wordlist', 'p.93', 'high', 'junior_fltrp'),
('wy7B-U6-0044', 7, 'truth', 'n.', '/truːθ/', '事实，真相，实情', 380, 'junior', 'wy7B', 'U6', 'wordlist', 'p.93', 'high', 'junior_fltrp'),
('wy7B-U6-0045', 7, 'climb', 'v.', '/klaɪm/', '爬（山），登（山）', 381, 'junior', 'wy7B', 'U6', 'wordlist', 'p.93', 'high', 'junior_fltrp');

-- 断言
DO $$
DECLARE tot int; c int; polluted int; nulls int; dup int;
BEGIN
  SELECT count(*) INTO tot FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B';
  IF tot<>381 THEN RAISE EXCEPTION 'total=% 期望381', tot; END IF;
  SELECT count(*) INTO c FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' AND unit='U1'; IF c<>76 THEN RAISE EXCEPTION 'U1=% 期望76', c; END IF;
  SELECT count(*) INTO c FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' AND unit='U2'; IF c<>81 THEN RAISE EXCEPTION 'U2=% 期望81', c; END IF;
  SELECT count(*) INTO c FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' AND unit='U3'; IF c<>75 THEN RAISE EXCEPTION 'U3=% 期望75', c; END IF;
  SELECT count(*) INTO c FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' AND unit='U4'; IF c<>60 THEN RAISE EXCEPTION 'U4=% 期望60', c; END IF;
  SELECT count(*) INTO c FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' AND unit='U5'; IF c<>44 THEN RAISE EXCEPTION 'U5=% 期望44', c; END IF;
  SELECT count(*) INTO c FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' AND unit='U6'; IF c<>45 THEN RAISE EXCEPTION 'U6=% 期望45', c; END IF;
  SELECT count(*) INTO polluted FROM public.junior_vocab WHERE volume='wy7B' AND publisher<>'junior_fltrp';
  IF polluted<>0 THEN RAISE EXCEPTION 'pep/wy7A 行被污染=%', polluted; END IF;
  SELECT count(*) INTO nulls FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' AND (word IS NULL OR meaning_cn IS NULL);
  IF nulls<>0 THEN RAISE EXCEPTION 'word/meaning 空=%', nulls; END IF;
  SELECT count(*) INTO dup FROM (SELECT word_id FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' GROUP BY word_id HAVING count(*)>1) t;
  IF dup<>0 THEN RAISE EXCEPTION 'word_id 重复=%', dup; END IF;
  RAISE NOTICE 'OK: wy7B 词表 % 条 · 六单元计数达标 · 无污染/空值/重复', tot;
END $$;

COMMIT;
-- 复核:各单元词数
SELECT unit, count(*) FROM public.junior_vocab WHERE publisher='junior_fltrp' AND volume='wy7B' GROUP BY unit ORDER BY min(freq_rank);