-- 九年级 U13 题库灌库(幂等)。volume='9' unit='U13' grade=9。vocab 不在此(已单独按 '9' 灌)。
BEGIN;

-- ===== junior_grammar_points (预期 3) =====
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), '158797be-3277-482a-b730-75b29dfa47b4', 'g9u13.01', '①被动语态复习:环保语境', 'B1', 9, '对应:九年级 U13', 1, '9', 'U13' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u13.01');
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), 'e05f9874-6401-42f8-a361-28f1dee3a58e', 'g9u13.02', '②情态动词复习:环保行动建议', 'B1', 9, '对应:九年级 U13', 2, '9', 'U13' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u13.02');
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), '158797be-3277-482a-b730-75b29dfa47b4', 'g9u13.03', '③时态综合:现在进行时/used to/被动', 'B1', 9, '对应:九年级 U13', 3, '9', 'U13' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u13.03');

-- ===== junior_grammar_questions (预期 60) =====
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'The river ____ badly polluted now.','be','am','is','are','C','[被动] 单数 is polluted',1,1,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='The river ____ badly polluted now.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Trees ____ cut down every year.','am','are','is','be','B','[被动] 复数 are cut',2,2,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Trees ____ cut down every year.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Too much litter ____ thrown into the sea.','am','be','are','is','D','[被动] 不可数 is thrown',3,3,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Too much litter ____ thrown into the sea.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Shark fins ____ sold in some markets.','are','am','be','is','A','[被动] 复数 are sold',1,4,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Shark fins ____ sold in some markets.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Plastic bags ____ harmful to the environment.','am','is','are','be','C','[被动/系动] 复数 are harmful',2,5,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Plastic bags ____ harmful to the environment.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'The air in big cities ____ often polluted.','are','is','am','be','B','[被动] 单数 is polluted',3,6,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='The air in big cities ____ often polluted.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Many animals ____ killed for their fur.','are','be','is','am','A','[被动] 复数 are killed',1,7,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Many animals ____ killed for their fur.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Paper ____ made from trees.','am','are','be','is','D','[被动] 不可数 is made',2,8,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Paper ____ made from trees.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'The bottles can ____ recycled.','be','is','are','being','A','[被动] can be recycled',3,9,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='The bottles can ____ recycled.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Last year, the forest ____ destroyed by a fire.','are','were','is','was','D','[被动过去] was destroyed',1,10,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Last year, the forest ____ destroyed by a fire.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Old newspapers should ____ recycled.','be','is','being','are','A','[被动] should be recycled',2,11,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Old newspapers should ____ recycled.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Water ____ wasted in many homes.','are','be','is','am','C','[被动] 不可数 is wasted',3,12,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Water ____ wasted in many homes.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'The streets ____ cleaned every morning.','be','are','is','am','B','[被动] 复数 are cleaned',1,13,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='The streets ____ cleaned every morning.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Too many fish ____ caught in the ocean.','is','be','am','are','D','[被动] 复数 are caught',2,14,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Too many fish ____ caught in the ocean.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Coal ____ burned to make electricity.','is','are','be','am','A','[被动] 不可数 is burned',3,15,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Coal ____ burned to make electricity.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'These products ____ made of plastic.','is','am','are','be','C','[被动] 复数 are made',1,16,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='These products ____ made of plastic.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'The beach ____ covered with litter yesterday.','is','was','were','are','B','[被动过去] was covered',2,17,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='The beach ____ covered with litter yesterday.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Energy ____ saved when we turn off lights.','am','is','are','be','B','[被动] 不可数 is saved',3,18,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Energy ____ saved when we turn off lights.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Many trees ____ planted last spring.','was','are','were','is','C','[被动过去复数] were planted',1,19,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Many trees ____ planted last spring.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.01'), 'Glass can ____ used again and again.','being','is','are','be','D','[被动] can be used',2,20,'mcq','g9u13.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.01' AND x.stem='Glass can ____ used again and again.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ turn off the lights to save energy.','shall to','should','ought','must to','B','[情态] should + 动词原形',1,1,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ turn off the lights to save energy.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ use reusable bags instead of plastic ones.','should','ought','must to','shall to','A','[情态] should do',2,2,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ use reusable bags instead of plastic ones.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'People ____ not throw litter into rivers.','must to','ought','should','shall','C','[情态] should not',3,3,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='People ____ not throw litter into rivers.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ all take action to protect the earth.','musting','musts','must','to must','C','[情态] must do',1,4,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ all take action to protect the earth.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'You ____ recycle paper rather than throw it away.','cans','canning','to can','can','D','[情态] can do',2,5,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='You ____ recycle paper rather than throw it away.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ save water by taking shorter showers.','canning','can','cans','to can','B','[情态] can do',3,6,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ save water by taking shorter showers.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'Everyone ____ help protect the environment.','should','ought','must to','shall to','A','[情态] should do',1,7,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='Everyone ____ help protect the environment.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ stop wasting paper.','to must','musts','must','musting','C','[情态] must do',2,8,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ stop wasting paper.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'People ____ take part in saving the earth.','shall to','should','must to','ought','B','[情态] should do',3,9,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='People ____ take part in saving the earth.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ ride bikes instead of driving cars.','canning','to can','cans','can','D','[情态] can do',1,10,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ ride bikes instead of driving cars.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ not waste food.','shall','ought','must to','should','D','[情态] should not',2,11,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ not waste food.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ try to save the sharks.','to must','musts','musting','must','D','[情态] must do',3,12,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ try to save the sharks.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'You ____ put rubbish in the bin.','must to','ought','shall to','should','D','[情态] should do',1,13,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='You ____ put rubbish in the bin.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ use public transportation more often.','to can','can','canning','cans','B','[情态] can do',2,14,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ use public transportation more often.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'Factories ____ not pollute the rivers.','shall','ought','should','must to','C','[情态] should not',3,15,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='Factories ____ not pollute the rivers.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ all do our part for the earth.','should','must to','ought','shall to','A','[情态] should do',1,16,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ all do our part for the earth.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'People ____ stop cutting down trees.','musting','must','musts','to must','B','[情态] must do',2,17,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='People ____ stop cutting down trees.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ reuse old things to save money.','to can','cans','can','canning','C','[情态] can do',3,18,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ reuse old things to save money.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'We ____ turn off the tap when brushing teeth.','should','must to','shall to','ought','A','[情态] should do',1,19,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='We ____ turn off the tap when brushing teeth.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.02'), 'Everyone ____ care about the environment.','must','to must','musts','musting','A','[情态] must do',2,20,'mcq','g9u13.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.02' AND x.stem='Everyone ____ care about the environment.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'We ____ trying to save the earth.','are','am','be','is','A','[现在进行] 复数 are trying',1,1,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='We ____ trying to save the earth.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'The river used to ____ clean and clear.','is','was','be','being','C','[used to] used to be',2,2,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='The river used to ____ clean and clear.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Look! They ____ planting trees in the park.','be','am','is','are','D','[现在进行] 复数 are planting',3,3,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Look! They ____ planting trees in the park.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'This bottle can ____ recycled.','being','are','be','is','C','[被动] can be recycled',1,4,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='This bottle can ____ recycled.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'The air used to ____ much cleaner here.','be','is','was','being','A','[used to] used to be',2,5,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='The air used to ____ much cleaner here.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Right now, people ____ working hard to save water.','be','is','am','are','D','[现在进行] 复数 are working',3,6,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Right now, people ____ working hard to save water.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Many old things ____ being put to good use.','are','be','is','am','A','[现在进行被动] are being',1,7,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Many old things ____ being put to good use.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'There used to ____ many fish in this river.','was','be','is','being','B','[used to] used to be',2,8,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='There used to ____ many fish in this river.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'We ____ recycling paper at our school now.','am','are','be','is','B','[现在进行] 复数 are recycling',3,9,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='We ____ recycling paper at our school now.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Glass ____ used again and again.','am','is','be','are','B','[被动] is used',1,10,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Glass ____ used again and again.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'The town used to ____ very polluted.','being','was','is','be','D','[used to] used to be',2,11,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='The town used to ____ very polluted.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Look! The workers ____ cleaning the beach.','are','am','is','be','A','[现在进行] 复数 are cleaning',3,12,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Look! The workers ____ cleaning the beach.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'I ____ saving water by reusing it now.','is','be','are','am','D','[现在进行] I am saving',1,13,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='I ____ saving water by reusing it now.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Old metal can ____ made into art.','is','are','be','being','C','[被动] can be made',2,14,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Old metal can ____ made into art.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'There used to ____ a forest here.','was','be','being','is','B','[used to] used to be',3,15,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='There used to ____ a forest here.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Right now, we ____ trying our best to help.','are','is','be','am','A','[现在进行] 复数 are trying',1,16,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Right now, we ____ trying our best to help.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Plastic ____ thrown away every day.','be','am','is','are','C','[被动] is thrown',2,17,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Plastic ____ thrown away every day.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Our school ____ planting trees this week.','are','is','be','am','B','[现在进行] 单数 is planting',3,18,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Our school ____ planting trees this week.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'The streets used to ____ full of litter.','being','was','is','be','D','[used to] used to be',1,19,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='The streets used to ____ full of litter.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u13.03'), 'Look! She ____ putting the bottles in the bin.','be','are','is','am','C','[现在进行] 单数 is putting',2,20,'mcq','g9u13.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u13.03' AND x.stem='Look! She ____ putting the bottles in the bin.');

-- ===== junior_reading (预期 6) =====
DELETE FROM public.junior_reading WHERE volume='9' AND unit='U13';
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Save the Sharks!', 'Sharks are in danger. Every year, millions of sharks are killed for their fins. This is very cruel. Fishermen catch the sharks, cut off their fins, and throw the sharks back into the sea. Without their fins, the sharks cannot swim, and they soon die. Sharks are at the top of the food chain. They help keep the ocean''s ecosystem healthy. If all the sharks disappear, the whole ocean will be in danger. Some people eat shark fins because they think they are good for health. But no scientific studies have shown this. We should all help save the sharks. We can refuse to eat shark fins and ask others to do the same.', '说明文', 114, '[{"q": "Why are sharks in danger?", "answer": "A", "options": ["They are killed for their fins.", "The sea is too warm.", "They are too slow.", "They have no food."], "explanation": "原文:killed for their fins"}, {"q": "What happens to sharks without their fins?", "answer": "B", "options": ["They swim faster.", "They cannot swim and soon die.", "They become healthy.", "They grow new fins."], "explanation": "原文:cannot swim, and they soon die"}, {"q": "Where are sharks in the food chain?", "answer": "A", "options": ["At the top.", "At the bottom.", "In the middle.", "Outside it."], "explanation": "原文:at the top of the food chain"}, {"q": "Do scientific studies show shark fins are good for health?", "answer": "B", "options": ["Only a few.", "No.", "Sometimes.", "Yes."], "explanation": "原文:no scientific studies have shown this"}, {"q": "What should we do to help?", "answer": "C", "options": ["Eat more fins.", "Do nothing.", "Refuse to eat shark fins.", "Catch more sharks."], "explanation": "原文:refuse to eat shark fins"}]'::jsonb, '[{"word": "shark", "cn": "鲨鱼"}, {"word": "cruel", "cn": "残酷的"}, {"word": "ecosystem", "cn": "生态系统"}]'::jsonb, 3, '9', 'U13');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Rethink, Reuse, Recycle', 'We all create waste every day. But there are three simple ways to help the earth: rethink, reuse, and recycle. First, rethink. Before you buy something, ask if you really need it. The more we buy, the more waste we make. Second, reuse. Many things can be used again. You can use a glass bottle to hold water, or turn an old box into a useful container. Third, recycle. Paper, glass, and metal can all be recycled. They can be made into new things. If we all take action, we can make a big difference. Saving the earth is not hard. It just takes a little thought and effort from everyone.', '说明文', 111, '[{"q": "How many ways are there to help the earth?", "answer": "C", "options": ["Two.", "Four.", "Three.", "Five."], "explanation": "原文:three simple ways"}, {"q": "What should you do before you buy something?", "answer": "B", "options": ["Pay more.", "Ask if you really need it.", "Buy two.", "Throw it away."], "explanation": "原文:ask if you really need it"}, {"q": "What can you do with a glass bottle?", "answer": "D", "options": ["Bury it.", "Throw it away.", "Burn it.", "Use it to hold water."], "explanation": "原文:use a glass bottle to hold water"}, {"q": "What can be recycled?", "answer": "D", "options": ["Nothing.", "Only paper.", "Only food.", "Paper, glass, and metal."], "explanation": "原文:Paper, glass, and metal can all be recycled"}, {"q": "Is saving the earth hard?", "answer": "C", "options": ["Very hard.", "Yes.", "No.", "Impossible."], "explanation": "原文:not hard"}]'::jsonb, '[{"word": "recycle", "cn": "回收利用"}, {"word": "bottle", "cn": "瓶子"}, {"word": "metal", "cn": "金属"}]'::jsonb, 3, '9', 'U13');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'The Bottle House', 'In a small town, there was a man named Mr. Lee. He loved to reuse old things. One day, he had an idea. He decided to build a house using old glass bottles. People thought he was crazy. "You can''t build a house from rubbish!" they said. But Mr. Lee did not give up. He collected thousands of bottles that people had thrown away. He put them to good use. After two years, the house was finished. It was beautiful and colorful. The sun shone through the bottles like a rainbow. Now, people come from far away to see the bottle house. Mr. Lee showed everyone that old things can become a work of art.', '记叙文', 115, '[{"q": "What did Mr. Lee love to do?", "answer": "B", "options": ["Throw things away.", "Reuse old things.", "Sell bottles.", "Buy new things."], "explanation": "原文:loved to reuse old things"}, {"q": "What did he decide to build?", "answer": "B", "options": ["A school.", "A house from old glass bottles.", "A boat.", "A car."], "explanation": "原文:build a house using old glass bottles"}, {"q": "What did people think at first?", "answer": "C", "options": ["He was rich.", "He was kind.", "He was crazy.", "He was clever."], "explanation": "原文:thought he was crazy"}, {"q": "How long did it take to finish?", "answer": "A", "options": ["Two years.", "Two days.", "Two weeks.", "Two months."], "explanation": "原文:After two years"}, {"q": "What did Mr. Lee show everyone?", "answer": "C", "options": ["Rubbish is bad.", "Bottles are useless.", "Old things can become a work of art.", "Houses are cheap."], "explanation": "原文:old things can become a work of art"}]'::jsonb, '[{"word": "bottle", "cn": "瓶子"}, {"word": "reuse", "cn": "再利用"}, {"word": "work", "cn": "作品"}]'::jsonb, 3, '9', 'U13');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Plastic or Paper?', 'When we go shopping, we often have to choose between plastic bags and paper bags. Which is better for the earth? Plastic bags are cheap and strong. But they are very harmful to the environment. They do not break down for hundreds of years. Many plastic bags end up in the sea, where they hurt animals. Paper bags break down more easily, but making them uses many trees. So what is the best choice? The answer is simple: use a reusable bag! A reusable bag can be used many times. It saves money and helps the earth. Next time you go shopping, remember to bring your own bag.', '议论文', 108, '[{"q": "What do we often choose between when shopping?", "answer": "C", "options": ["Food and drink.", "Books and pens.", "Plastic bags and paper bags.", "Cars and bikes."], "explanation": "原文:between plastic bags and paper bags"}, {"q": "Why are plastic bags harmful?", "answer": "C", "options": ["They are weak.", "They are heavy.", "They do not break down for hundreds of years.", "They are expensive."], "explanation": "原文:do not break down for hundreds of years"}, {"q": "What problem do paper bags have?", "answer": "D", "options": ["They are too strong.", "They cost too much.", "They never break down.", "Making them uses many trees."], "explanation": "原文:making them uses many trees"}, {"q": "What is the best choice?", "answer": "A", "options": ["A reusable bag.", "No bag.", "A plastic bag.", "A paper bag."], "explanation": "原文:use a reusable bag"}, {"q": "What should you do next time you shop?", "answer": "B", "options": ["Buy plastic.", "Bring your own bag.", "Use both.", "Buy paper."], "explanation": "原文:bring your own bag"}]'::jsonb, '[{"word": "plastic", "cn": "塑料的"}, {"word": "harmful", "cn": "有害的"}, {"word": "reusable", "cn": "可重复使用的"}]'::jsonb, 3, '9', 'U13');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Small Actions, Big Difference', 'Saving the earth is not only the job of governments. Each of us can help, too. There are many small actions we can take. We can turn off the lights when we leave a room. This saves energy. We can ride bikes or take public transportation instead of driving cars. This makes the air cleaner. We can use less paper and recycle what we use. This saves trees. We can carry a reusable water bottle instead of buying plastic ones. We can also tell our friends and family to do the same. These small actions may seem unimportant, but together they can make a big difference. The earth is our home, and we must take care of it.', '说明文', 118, '[{"q": "Whose job is saving the earth?", "answer": "C", "options": ["Only scientists''.", "Only governments''.", "Everyone''s, not only governments''.", "Only teachers''."], "explanation": "原文:not only the job of governments"}, {"q": "What does turning off lights save?", "answer": "B", "options": ["Money only.", "Energy.", "Water.", "Trees."], "explanation": "原文:This saves energy"}, {"q": "What makes the air cleaner?", "answer": "A", "options": ["Riding bikes or taking public transportation.", "Burning coal.", "Using plastic.", "Driving more."], "explanation": "原文:ride bikes or take public transportation"}, {"q": "What does using less paper save?", "answer": "D", "options": ["Time.", "Water.", "Energy.", "Trees."], "explanation": "原文:This saves trees"}, {"q": "What can small actions do together?", "answer": "D", "options": ["Cause harm.", "Nothing.", "Waste time.", "Make a big difference."], "explanation": "原文:make a big difference"}]'::jsonb, '[{"word": "transportation", "cn": "运输;交通"}, {"word": "recycle", "cn": "回收"}, {"word": "reusable", "cn": "可重复使用的"}]'::jsonb, 3, '9', 'U13');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Green School Notice', 'GREEN SCHOOL WEEK! Let''s work together to protect our environment. Here is how you can help. MONDAY: Turn off lights and computers when you leave the classroom. Save energy! TUESDAY: Bring a reusable water bottle. Do not use plastic ones. WEDNESDAY: Use both sides of your paper. Save trees! THURSDAY: Put rubbish in the right bins. We will recycle paper, glass, and metal. FRIDAY: Walk or ride a bike to school if you can. Remember, the earth is our home. Every small action counts. Let''s take action together and make our school a greener place. Thank you for your help!', '应用文', 100, '[{"q": "What is the notice about?", "answer": "A", "options": ["Green School Week.", "A party week.", "A sports week.", "An exam week."], "explanation": "原文:GREEN SCHOOL WEEK"}, {"q": "What should you do on Monday?", "answer": "D", "options": ["Ride a bike.", "Bring a bottle.", "Use both sides of paper.", "Turn off lights and computers."], "explanation": "原文:Monday: Turn off lights and computers"}, {"q": "What should you bring on Tuesday?", "answer": "A", "options": ["A reusable water bottle.", "A book.", "A paper bag.", "A plastic bottle."], "explanation": "原文:Bring a reusable water bottle"}, {"q": "What will be recycled on Thursday?", "answer": "A", "options": ["Paper, glass, and metal.", "Only food.", "Only paper.", "Nothing."], "explanation": "原文:recycle paper, glass, and metal"}, {"q": "What counts according to the notice?", "answer": "D", "options": ["Only big actions.", "Only teachers.", "Only money.", "Every small action."], "explanation": "原文:Every small action counts"}]'::jsonb, '[{"word": "recycle", "cn": "回收"}, {"word": "reusable", "cn": "可重复使用的"}, {"word": "bin", "cn": "垃圾箱"}]'::jsonb, 3, '9', 'U13');

-- ===== junior_cloze (预期 6) =====
DELETE FROM public.junior_cloze WHERE volume='9' AND unit='U13';
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U13', 'Save the Sharks', 'Sharks are in (1)____. Every year, millions of sharks are (2)____ for their fins. This is very (3)____. Fishermen cut off their fins and (4)____ the sharks back into the sea. Without their fins, the sharks cannot (5)____ and soon die. Sharks are at the top of the food (6)____. They keep the ocean''s ecosystem (7)____. If all the sharks (8)____, the ocean will be in danger. We (9)____ all help save the sharks. We can (10)____ to eat shark fins.', 81, 3, '[{"q": "1", "answer": "D", "options": ["price", "game", "color", "danger"], "explanation": "危险 in danger"}, {"q": "2", "answer": "C", "options": ["kills", "killing", "killed", "kill"], "explanation": "被杀 are killed"}, {"q": "3", "answer": "B", "options": ["kind", "cruel", "good", "nice"], "explanation": "残酷 cruel"}, {"q": "4", "answer": "D", "options": ["build", "lose", "break", "throw"], "explanation": "扔 throw"}, {"q": "5", "answer": "C", "options": ["build", "break", "swim", "lose"], "explanation": "游泳 swim"}, {"q": "6", "answer": "A", "options": ["chain", "game", "price", "color"], "explanation": "链 food chain"}, {"q": "7", "answer": "B", "options": ["sick", "healthy", "tired", "weak"], "explanation": "健康 healthy"}, {"q": "8", "answer": "A", "options": ["disappear", "break", "lose", "build"], "explanation": "消失 disappear"}, {"q": "9", "answer": "B", "options": ["must to", "should", "ought", "shall"], "explanation": "情态 should"}, {"q": "10", "answer": "A", "options": ["refuse", "build", "lose", "break"], "explanation": "拒绝 refuse"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U13', 'The Three R''s', 'We all create (1)____ every day. But there are three ways to help the (2)____: rethink, reuse, and recycle. First, (3)____. Before you buy something, ask if you really (4)____ it. Second, reuse. Many things can be (5)____ again. You can use a glass (6)____ to hold water. Third, recycle. Paper, glass, and (7)____ can all be recycled into new things. If we all take (8)____, we can make a big (9)____. Saving the earth is not (10)____. It just takes a little effort.', 84, 3, '[{"q": "1", "answer": "C", "options": ["price", "color", "waste", "game"], "explanation": "垃圾 waste"}, {"q": "2", "answer": "B", "options": ["price", "earth", "color", "game"], "explanation": "地球 earth"}, {"q": "3", "answer": "A", "options": ["rethink", "build", "break", "lose"], "explanation": "重新思考 rethink"}, {"q": "4", "answer": "A", "options": ["need", "lose", "build", "break"], "explanation": "需要 need"}, {"q": "5", "answer": "C", "options": ["use", "uses", "used", "using"], "explanation": "被使用 be used"}, {"q": "6", "answer": "B", "options": ["color", "bottle", "price", "game"], "explanation": "瓶子 bottle"}, {"q": "7", "answer": "D", "options": ["color", "game", "price", "metal"], "explanation": "金属 metal"}, {"q": "8", "answer": "D", "options": ["color", "game", "price", "action"], "explanation": "行动 take action"}, {"q": "9", "answer": "A", "options": ["difference", "color", "game", "price"], "explanation": "差别 difference"}, {"q": "10", "answer": "B", "options": ["good", "hard", "easy", "kind"], "explanation": "难 hard"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U13', 'The Bottle House', 'In a small town, there was a man named Mr. Lee. He loved to (1)____ old things. One day, he had an (2)____. He decided to build a house using old glass (3)____. People thought he was (4)____. But Mr. Lee did not give (5)____. He collected thousands of bottles that people had (6)____ away. He put them to good (7)____. After two years, the house was (8)____. It was beautiful and colorful. Now people come to see it. Mr. Lee showed everyone that old things can become a (9)____ of art. His story is a real (10)____.', 98, 3, '[{"q": "1", "answer": "B", "options": ["lose", "reuse", "break", "build"], "explanation": "再利用 reuse"}, {"q": "2", "answer": "A", "options": ["idea", "game", "color", "price"], "explanation": "主意 idea"}, {"q": "3", "answer": "B", "options": ["prices", "bottles", "games", "colors"], "explanation": "瓶子 bottles"}, {"q": "4", "answer": "C", "options": ["kind", "good", "crazy", "nice"], "explanation": "疯狂 crazy"}, {"q": "5", "answer": "D", "options": ["in", "off", "on", "up"], "explanation": "放弃 give up"}, {"q": "6", "answer": "D", "options": ["throws", "throwing", "throw", "thrown"], "explanation": "扔掉 had thrown"}, {"q": "7", "answer": "B", "options": ["color", "use", "game", "price"], "explanation": "用途 good use"}, {"q": "8", "answer": "C", "options": ["finishing", "finish", "finished", "finishes"], "explanation": "完成 was finished"}, {"q": "9", "answer": "A", "options": ["work", "price", "game", "color"], "explanation": "作品 work of art"}, {"q": "10", "answer": "A", "options": ["inspiration", "game", "color", "price"], "explanation": "灵感 inspiration"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U13', 'Plastic or Paper?', 'When we go shopping, we often choose between (1)____ bags and paper bags. Which is better for the (2)____? Plastic bags are cheap and strong. But they are very (3)____ to the environment. They do not break (4)____ for hundreds of years. Many end up in the (5)____, where they hurt animals. Paper bags break down more (6)____, but making them uses many (7)____. So what is the best (8)____? Use a (9)____ bag! It can be used many times. Next time you shop, remember to (10)____ your own bag.', 90, 3, '[{"q": "1", "answer": "A", "options": ["plastic", "color", "game", "price"], "explanation": "塑料 plastic"}, {"q": "2", "answer": "B", "options": ["price", "earth", "color", "game"], "explanation": "地球 earth"}, {"q": "3", "answer": "C", "options": ["helpful", "good", "harmful", "useful"], "explanation": "有害 harmful"}, {"q": "4", "answer": "B", "options": ["on", "down", "in", "off"], "explanation": "分解 break down"}, {"q": "5", "answer": "D", "options": ["price", "game", "color", "sea"], "explanation": "海洋 sea"}, {"q": "6", "answer": "C", "options": ["late", "slow", "easily", "hard"], "explanation": "容易 easily"}, {"q": "7", "answer": "A", "options": ["trees", "prices", "colors", "games"], "explanation": "树 trees"}, {"q": "8", "answer": "A", "options": ["choice", "game", "price", "color"], "explanation": "选择 choice"}, {"q": "9", "answer": "B", "options": ["paper", "reusable", "new", "plastic"], "explanation": "可重复使用 reusable"}, {"q": "10", "answer": "D", "options": ["break", "lose", "build", "bring"], "explanation": "带 bring"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U13', 'Small Actions', 'Saving the earth is not only the job of (1)____. Each of us can help, too. We can turn (2)____ the lights when we leave a room. This (3)____ energy. We can ride bikes or take public (4)____ instead of driving. This makes the air (5)____. We can use (6)____ paper and recycle what we use. This saves (7)____. We can carry a reusable water (8)____ instead of buying plastic ones. These small actions may seem (9)____, but together they make a big (10)____. The earth is our home, and we must take care of it.', 96, 3, '[{"q": "1", "answer": "A", "options": ["governments", "games", "colors", "prices"], "explanation": "政府 governments"}, {"q": "2", "answer": "B", "options": ["up", "off", "in", "on"], "explanation": "关掉 turn off"}, {"q": "3", "answer": "A", "options": ["saves", "build", "lose", "break"], "explanation": "节省 saves"}, {"q": "4", "answer": "D", "options": ["color", "game", "price", "transportation"], "explanation": "交通 transportation"}, {"q": "5", "answer": "C", "options": ["dirtier", "worse", "cleaner", "older"], "explanation": "更干净 cleaner"}, {"q": "6", "answer": "B", "options": ["much", "less", "many", "more"], "explanation": "更少 less"}, {"q": "7", "answer": "B", "options": ["games", "trees", "prices", "colors"], "explanation": "树 trees"}, {"q": "8", "answer": "C", "options": ["price", "game", "bottle", "color"], "explanation": "瓶子 bottle"}, {"q": "9", "answer": "A", "options": ["unimportant", "useful", "important", "good"], "explanation": "不重要 unimportant"}, {"q": "10", "answer": "D", "options": ["game", "price", "color", "difference"], "explanation": "差别 difference"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U13', 'Green School Week', 'Green School Week is here! Let''s work (1)____ to protect our environment. On Monday, turn (2)____ lights and computers when you leave. Save (3)____! On Tuesday, bring a (4)____ water bottle. Do not use (5)____ ones. On Wednesday, use both (6)____ of your paper. Save trees! On Thursday, put rubbish in the right (7)____. We will (8)____ paper, glass, and metal. On Friday, walk or ride a bike to school. Remember, the earth is our (9)____. Every small action (10)____. Let''s make our school a greener place!', 87, 3, '[{"q": "1", "answer": "C", "options": ["away", "apart", "together", "alone"], "explanation": "一起 together"}, {"q": "2", "answer": "B", "options": ["up", "off", "on", "in"], "explanation": "关掉 turn off"}, {"q": "3", "answer": "A", "options": ["energy", "game", "price", "color"], "explanation": "能源 energy"}, {"q": "4", "answer": "C", "options": ["new", "plastic", "reusable", "paper"], "explanation": "可重复 reusable"}, {"q": "5", "answer": "A", "options": ["plastic", "price", "color", "game"], "explanation": "塑料 plastic"}, {"q": "6", "answer": "A", "options": ["sides", "games", "prices", "colors"], "explanation": "面 both sides"}, {"q": "7", "answer": "D", "options": ["games", "colors", "prices", "bins"], "explanation": "垃圾箱 bins"}, {"q": "8", "answer": "D", "options": ["build", "break", "lose", "recycle"], "explanation": "回收 recycle"}, {"q": "9", "answer": "B", "options": ["price", "home", "color", "game"], "explanation": "家 home"}, {"q": "10", "answer": "B", "options": ["lose", "counts", "build", "break"], "explanation": "重要 counts"}]'::jsonb, 6);

-- ===== junior_listening_exercises (预期 6) =====
DELETE FROM public.junior_listening_exercises WHERE volume='9' AND unit='U13';
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U13 听力·对话 Saving the Earth', '九年级 Unit13 听力·环境保护/综合复习', 2, 'W: The river near my home is so polluted now.
M: I know. It used to be clean and clear.
W: We should do something to help.
M: Yes. We can stop throwing litter into it.
W: And we should tell others to do the same.', '女:我家附近的河现在污染得很严重。
男:我知道。它以前又干净又清澈。
女:我们应该做点什么来帮忙。
男:是的。我们可以不再往里面扔垃圾。
女:我们还应该告诉别人也这样做。', 'us_male', '[{"q": "What is the problem with the river?", "type": "choice", "answer": "B", "options": ["It is gone.", "It is polluted now.", "It is frozen.", "It is dry."]}, {"q": "What did the river used to be?", "type": "choice", "answer": "B", "options": ["Dirty.", "Clean and clear.", "Small.", "Empty."]}, {"q": "What does the woman say they should do?", "type": "choice", "answer": "D", "options": ["Move away.", "Swim in it.", "Do nothing.", "Do something to help."]}, {"q": "What can they stop doing?", "type": "choice", "answer": "B", "options": ["Drinking water.", "Throwing litter into the river.", "Riding bikes.", "Planting trees."]}, {"q": "What else should they do?", "type": "choice", "answer": "C", "options": ["Leave the town.", "Keep it secret.", "Tell others to do the same.", "Buy plastic."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U13');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U13 听力·短文 Save the Sharks', '九年级 Unit13 听力·环境保护/综合复习', 2, 'Sharks are in danger today.
Every year, millions of sharks are killed for their fins.
Without their fins, the sharks cannot swim and soon die.
Sharks are at the top of the food chain.
We should all help save the sharks.', '如今鲨鱼正处于危险之中。
每年都有数百万条鲨鱼因鱼鳍而被杀。
没有了鳍,鲨鱼无法游泳,很快就会死去。
鲨鱼处于食物链的顶端。
我们都应该帮助拯救鲨鱼。', 'us_female', '[{"q": "Are sharks in danger?", "type": "choice", "answer": "B", "options": ["Sometimes.", "Yes.", "Not anymore.", "No."]}, {"q": "Why are sharks killed?", "type": "choice", "answer": "C", "options": ["For food.", "For their skin.", "For their fins.", "For sport."]}, {"q": "What happens without their fins?", "type": "choice", "answer": "B", "options": ["They swim faster.", "They cannot swim and soon die.", "They get healthy.", "They grow bigger."]}, {"q": "Where are sharks in the food chain?", "type": "choice", "answer": "D", "options": ["Outside it.", "At the bottom.", "In the middle.", "At the top."]}, {"q": "What should we do?", "type": "choice", "answer": "D", "options": ["Catch more sharks.", "Eat more fins.", "Do nothing.", "Help save the sharks."]}]'::jsonb, '[]'::jsonb, 'short', '9', 'U13');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U13 听力·对话 The Three R''s', '九年级 Unit13 听力·环境保护/综合复习', 2, 'W: Our school is starting a recycling program.
M: That''s great! What can we do?
W: We can rethink, reuse, and recycle.
M: I always reuse old bottles and boxes.
W: And we can recycle paper, glass, and metal.', '女:我们学校要开展一个回收项目。
男:太好了!我们能做什么?
女:我们可以重新思考、再利用、回收。
男:我总是把旧瓶子和旧盒子再利用。
女:我们还可以回收纸、玻璃和金属。', 'us_male', '[{"q": "What is the school starting?", "type": "choice", "answer": "B", "options": ["A music class.", "A recycling program.", "A party.", "A sports day."]}, {"q": "What three things can they do?", "type": "choice", "answer": "C", "options": ["Read, write, play.", "Buy, sell, throw.", "Rethink, reuse, and recycle.", "Eat, drink, sleep."]}, {"q": "What does the man always reuse?", "type": "choice", "answer": "A", "options": ["Old bottles and boxes.", "Old books.", "Old clothes.", "Old toys."]}, {"q": "What can they recycle?", "type": "choice", "answer": "A", "options": ["Paper, glass, and metal.", "Only food.", "Only paper.", "Nothing."]}, {"q": "How does the man feel about the program?", "type": "choice", "answer": "A", "options": ["He thinks it''s great.", "He thinks it''s bad.", "He is angry.", "He is bored."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U13');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U13 听力·短文 The Bottle House', '九年级 Unit13 听力·环境保护/综合复习', 2, 'Mr. Lee loved to reuse old things.
He decided to build a house using old glass bottles.
People thought he was crazy at first.
After two years, the beautiful house was finished.
He showed that old things can become a work of art.', '李先生喜欢再利用旧物。
他决定用旧玻璃瓶建一座房子。
起初人们以为他疯了。
两年后,这座漂亮的房子建成了。
他证明了旧物也能成为艺术品。', 'us_female', '[{"q": "What did Mr. Lee love to do?", "type": "choice", "answer": "A", "options": ["Reuse old things.", "Buy new things.", "Throw things away.", "Sell bottles."]}, {"q": "What did he build?", "type": "choice", "answer": "B", "options": ["A car.", "A house using old glass bottles.", "A boat.", "A school."]}, {"q": "What did people think at first?", "type": "choice", "answer": "D", "options": ["He was clever.", "He was kind.", "He was rich.", "He was crazy."]}, {"q": "How long did it take?", "type": "choice", "answer": "D", "options": ["Two days.", "Two weeks.", "Two months.", "Two years."]}, {"q": "What did he show?", "type": "choice", "answer": "D", "options": ["Houses are cheap.", "Rubbish is bad.", "Bottles are useless.", "Old things can become a work of art."]}]'::jsonb, '[]'::jsonb, 'short', '9', 'U13');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U13 听力·对话 A Reusable Bag', '九年级 Unit13 听力·环境保护/综合复习', 2, 'W: Do you want a plastic bag for your shopping?
M: No, thanks. I brought my own reusable bag.
W: That''s a good idea. Plastic bags are bad for the earth.
M: Yes. A reusable bag can be used many times.
W: I should start using one too.', '女:你购物需要塑料袋吗?
男:不用,谢谢。我自己带了可重复使用的袋子。
女:这是个好主意。塑料袋对地球有害。
男:是的。可重复使用的袋子可以用很多次。
女:我也应该开始用一个了。', 'us_male', '[{"q": "Does the man want a plastic bag?", "type": "choice", "answer": "C", "options": ["Two of them.", "Maybe.", "No.", "Yes."]}, {"q": "What did the man bring?", "type": "choice", "answer": "C", "options": ["A box.", "A paper bag.", "His own reusable bag.", "A plastic bag."]}, {"q": "Why are plastic bags bad?", "type": "choice", "answer": "A", "options": ["They are bad for the earth.", "They are expensive.", "They are weak.", "They are too small."]}, {"q": "How many times can a reusable bag be used?", "type": "choice", "answer": "C", "options": ["Never.", "Once.", "Many times.", "Twice."]}, {"q": "What will the woman start doing?", "type": "choice", "answer": "A", "options": ["Using a reusable bag too.", "Using nothing.", "Buying plastic.", "Buying paper."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U13');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U13 听力·短文 Green School Week', '九年级 Unit13 听力·环境保护/综合复习', 2, 'This week is Green School Week.
On Monday, turn off lights to save energy.
On Tuesday, bring a reusable water bottle.
On Thursday, put rubbish in the right bins to recycle.
Remember, every small action counts.', '这周是绿色校园周。
周一,关灯以节约能源。
周二,带一个可重复使用的水瓶。
周四,把垃圾放进正确的垃圾箱以便回收。
记住,每一个小行动都很重要。', 'us_female', '[{"q": "What week is it?", "type": "choice", "answer": "D", "options": ["Exam Week.", "Music Week.", "Sports Week.", "Green School Week."]}, {"q": "What should you do on Monday?", "type": "choice", "answer": "A", "options": ["Turn off lights to save energy.", "Bring a bottle.", "Ride a bike.", "Recycle rubbish."]}, {"q": "What should you bring on Tuesday?", "type": "choice", "answer": "C", "options": ["A plastic bottle.", "A book.", "A reusable water bottle.", "A paper bag."]}, {"q": "What should you do on Thursday?", "type": "choice", "answer": "C", "options": ["Bring a bottle.", "Walk to school.", "Put rubbish in the right bins.", "Turn off lights."]}, {"q": "What counts according to the passage?", "type": "choice", "answer": "A", "options": ["Every small action.", "Only big actions.", "Only teachers.", "Only money."]}]'::jsonb, '[]'::jsonb, 'short', '9', 'U13');

-- ===== junior_writing_prompts (预期 1) =====
INSERT INTO public.junior_writing_prompts (id, grade, topic, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, difficulty, title_en, high_sentences, error_pairs, paragraph_template, volume, unit) SELECT gen_random_uuid(), 9, 'Saving Our Environment', '写一篇关于保护环境的短文。说明你们当地的一个环境问题,并提出你的建议(用should/can表达,用被动语态描述问题)。60词左右。', 'Write a short passage on the topic: "Saving Our Environment".', '["你们当地的一个环境问题(用被动语态:is polluted/are cut down)", "为什么这是个问题", "你的建议(用should/can:We should.../We can...)", "呼吁大家一起行动"]'::jsonb, 70, 100, 'The river near my home is badly polluted. Litter is thrown into it every day, and the water used to be clean. This is harmful to fish and people. We should take action to save our environment. We can stop throwing rubbish into the river. We can also recycle paper, glass, and metal instead of throwing them away. If we all do our part, we can make a big difference. The earth is our home, and we must protect it.', 'content:含环境问题/危害/建议/呼吁(4分)；language:正确使用被动语态及should/can(3分)；structure:论证清楚、衔接得当(2分)；wordcount:词数达标、书写规范(1分)', 3, 'Saving Our Environment', '["The river/air is badly polluted.", "We should ...", "We can ...", "Trees are being cut down.", "take action", "reduce, reuse, recycle", "The earth is our home."]'::jsonb, '[]'::jsonb, '要点:你们当地的一个环境问题(用被动语态:is polluted/are cut down)；为什么这是个问题；你的建议(用should/can:We should.../We can...)；呼吁大家一起行动', '9', 'U13' WHERE NOT EXISTS (SELECT 1 FROM public.junior_writing_prompts WHERE volume='9' AND unit='U13' AND topic='Saving Our Environment');

COMMIT;

-- ===== count 校验 =====
SELECT 'grammar_points' k, count(*) v, 3 expect FROM public.junior_grammar_points WHERE volume='9' AND unit='U13'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.volume='9' AND p.unit='U13'
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='9' AND unit='U13'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='9' AND unit='U13'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='9' AND unit='U13'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='9' AND unit='U13';