-- ============================================================
-- 完形批2: 7B U3-U6 + U8 共10篇(各8空); 精简加粗解析; 答案打散(ABCD各2)
-- 含修复:U3第2篇(7)→ "Follow these ___ habits" 答案 healthy(原 healthy healthy bug)
-- 时态:U3-U4一般现在时 / U5-U6现在进行时 / U8一般过去时
-- 幂等 WHERE NOT EXISTS by title; ⚠️先跑过 cloze-step1-ddl.sql 建表
-- ============================================================

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c3000001-0a1b-4c2d-8e3f-000000000005', 7, '7B', 'U3', '七下 U3 完形:Mike’s Sports Club', 'Tim loves sports. He wants to be strong, so he (1)____ exercises after school. He joins the school basketball club. The club members meet (2)____ a week, on Tuesday and Thursday. Tim is very good at basketball. He (3)____ play it well. (4)____ does he go swimming? He goes swimming every Sunday morning. But his sister Lily (5)____ swims. She does not like water at all, so she never goes to the pool. Today, Tim''s parents are (6)____ the club to watch him play. Do you want to have a healthy (7)____? Come and (8)____ sports with us!', 98, 2, '[{"q":"1","options":["always is","always","is always","always does"],"answer":"B","explanation":"频率副词 **always** 放实义动词(exercises)前。"},{"q":"2","options":["twice","two","second","two time"],"answer":"A","explanation":"\"一周两次\"用 **twice** a week。"},{"q":"3","options":["is","must to","does","can"],"answer":"D","explanation":"**can**+动词原形 play(会、能力)。"},{"q":"4","options":["How long","How much","How often","How many"],"answer":"C","explanation":"答 every Sunday(频率)→**How often**。"},{"q":"5","options":["never","don''t","doesn''t","not"],"answer":"A","explanation":"Lily swims(带 s),副词 **never** 直接修饰单三动词。"},{"q":"6","options":["on","from","at","under"],"answer":"C","explanation":"**at** the club(在俱乐部,固定)。"},{"q":"7","options":["bodies","body","tooth","teeth"],"answer":"B","explanation":"a healthy **body**(a+可数单数)。"},{"q":"8","options":["play","run","swim","do"],"answer":"D","explanation":"**do** sports(做运动;play 接球类)。"}]'::jsonb, 1
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U3 完形:Mike’s Sports Club');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c3000002-0a1b-4c2d-8e3f-000000000006', 7, '7B', 'U3', '七下 U3 完形:Fitness Advice for Students', 'Do you want to stay fit? Here is some good (1)____ for you. First, exercise every day. Running is a good (2)____. It makes your legs (3)____ and healthy. Second, do not sit all day. Many students watch (4)____ for hours. That is bad for your eyes. You can play basketball with your (5)____ after class. It is fun and you can make new friends. Third, go to school on foot if your home is near. Walking is also a kind of exercise. Finally, get enough (6)____. A tired body cannot work well. Follow these (7)____ habits, and you can (8)____ your school life.', 104, 2, '[{"q":"1","options":["food","game","advice","rule"],"answer":"C","explanation":"全文给学生\"建议\"→**advice**。"},{"q":"2","options":["food","sport","book","room"],"answer":"B","explanation":"Running 是一种 **sport**(运动)。"},{"q":"3","options":["strong","long","short","slow"],"answer":"A","explanation":"跑步使腿 **strong**(强壮),与 healthy 并列。"},{"q":"4","options":["basketball","books","food","TV"],"answer":"D","explanation":"watch **TV** for hours→对眼睛有害。"},{"q":"5","options":["teachers","friends","dogs","parents"],"answer":"B","explanation":"后文 make new friends→和 **friends** 打球。"},{"q":"6","options":["homework","food","water","sleep"],"answer":"D","explanation":"get enough **sleep**(睡眠);A tired body 印证。"},{"q":"7","options":["healthy","bad","busy","dangerous"],"answer":"A","explanation":"跑步/打球/步行/睡眠都是 **healthy** habits(健康习惯)。"},{"q":"8","options":["lose","stop","enjoy","forget"],"answer":"C","explanation":"好习惯→**enjoy** your school life(享受)。"}]'::jsonb, 2
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U3 完形:Fitness Advice for Students');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c4000001-0a1b-4c2d-8e3f-000000000007', 7, '7B', 'U4', '七下 U4 完形:What’s for Dinner?', 'Tim and his mother are at the supermarket. They want to buy some food for dinner. "Mum, would you (1)____ some beef?" Tim asks. "Yes, let''s get some," his mother says. "We also need (2)____ vegetables. Let''s buy some tomatoes and carrots." Tim looks at the fruit. "Are there (3)____ apples in the basket?" he asks. "No, there aren''t. Let''s buy (4)____ apples." Then, they go to buy drinks. Tim wants (5)____ milk. His mother says, "Ok, let''s get two (6)____ of milk." Tim''s mother does not want (7)____ juice because it has too (8)____ sugar. Sugar is not good for teeth.', 102, 2, '[{"q":"1","options":["like","want","likes","to like"],"answer":"A","explanation":"would **like** some beef(would like 固定;疑问后用原形)。"},{"q":"2","options":["much","any","an","some"],"answer":"D","explanation":"vegetables 可数复数+肯定→**some**。"},{"q":"3","options":["some","any","much","many"],"answer":"B","explanation":"一般疑问句\"一些\"→**any**(apples 可数)。"},{"q":"4","options":["a piece of","a glass of","many","much"],"answer":"C","explanation":"apples 可数复数→**many**。"},{"q":"5","options":["many","any","a","some"],"answer":"D","explanation":"milk 不可数+肯定→**some**。"},{"q":"6","options":["bottles","bottle","piece","pieces"],"answer":"A","explanation":"two+可数量词复数→**bottles**(牛奶用瓶装)。"},{"q":"7","options":["some","many","any","an"],"answer":"C","explanation":"does not want(否定)→**any**(juice 不可数)。"},{"q":"8","options":["many","much","some","any"],"answer":"B","explanation":"too **much** sugar(too much+不可数)。"}]'::jsonb, 1
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U4 完形:What’s for Dinner?');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c4000002-0a1b-4c2d-8e3f-000000000008', 7, '7B', 'U4', '七下 U4 完形:Healthy Eating Habits', 'Healthy food gives us energy. It helps us grow well. What is a healthy meal? First, breakfast is very (1)____. For breakfast, you can drink a glass of (2)____ and eat an egg. Do not go to school with an empty stomach. For lunch and dinner, you need a balance of food. Eat some (3)____ or bread because they give you energy. Do not eat too much meat like (4)____ or fried chicken. They have too much fat. You must eat a lot of vegetables and (5)____ every day. They have vitamins. When you are (6)____, please drink water. Do not drink too much juice because it has too much (7)____. Choose your food well and stay (8)____!', 118, 2, '[{"q":"1","options":["dangerous","busy","bad","important"],"answer":"D","explanation":"早饭很 **important**(后文别空腹上学)。"},{"q":"2","options":["bread","meat","milk","rice"],"answer":"C","explanation":"a glass of **milk**(杯装液体)。"},{"q":"3","options":["water","rice","juice","tea"],"answer":"B","explanation":"与 bread 并列、给能量→**rice**(主食)。"},{"q":"4","options":["hamburgers","apples","carrots","tomatoes"],"answer":"A","explanation":"too much meat like **hamburgers** or fried chicken(肉类高脂)。"},{"q":"5","options":["sugar","salt","fruit","meat"],"answer":"C","explanation":"vegetables 和 **fruit**(含 vitamins)。"},{"q":"6","options":["thirsty","hungry","tired","happy"],"answer":"A","explanation":"**thirsty**(口渴)时 drink water。"},{"q":"7","options":["water","milk","apple","sugar"],"answer":"D","explanation":"果汁含太多 **sugar**(糖)。"},{"q":"8","options":["hungry","healthy","tired","late"],"answer":"B","explanation":"选好食物,保持 **healthy**(健康)。"}]'::jsonb, 2
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U4 完形:Healthy Eating Habits');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c5000001-0a1b-4c2d-8e3f-000000000009', 7, '7B', 'U5', '七下 U5 完形:A Busy Sunday Afternoon', 'It is a sunny Sunday afternoon. Now, all the family members (1)____ at home. What are they doing? Look! Mr. Green (2)____ a book in the living room. He always (3)____ books on Sundays. Mrs. Green is in the kitchen. She (4)____ dinner for the family. Listen! Who (5)____ in the next room? Oh, it is Mary. She is singing an English song. Where is Tom? He is in the garden. He (6)____ with his cute dog. The dog (7)____ running happily on the grass. They (8)____ having a great time at the moment!', 94, 3, '[{"q":"1","options":["is","are","am","be"],"answer":"B","explanation":"all the family members(复数)→be 用 **are**。"},{"q":"2","options":["read","reads","reading","is reading"],"answer":"D","explanation":"Look!→现在进行时,Mr. Green→**is reading**。"},{"q":"3","options":["reads","read","reading","is reading"],"answer":"A","explanation":"always(习惯)→一般现在时,He→**reads**。"},{"q":"4","options":["cook","cooks","is cooking","cooking"],"answer":"C","explanation":"此刻在厨房→**is cooking**(现在进行时)。"},{"q":"5","options":["are singing","sing","is singing","sings"],"answer":"C","explanation":"Listen!→进行时;Who 作主语默认单数→**is singing**。"},{"q":"6","options":["is playing","play","plays","playing"],"answer":"A","explanation":"Tom 此刻在玩→**is playing**。"},{"q":"7","options":["are","am","be","is"],"answer":"D","explanation":"The dog(单数)+running→进行时助动词 **is**。"},{"q":"8","options":["is","are","am","be"],"answer":"B","explanation":"at the moment+They→**are** having。"}]'::jsonb, 1
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U5 完形:A Busy Sunday Afternoon');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c5000002-0a1b-4c2d-8e3f-000000000010', 7, '7B', 'U5', '七下 U5 完形:At the Sports Center', 'Today is Saturday. The sports center is very busy (1)____. Many people are doing their favorite sports here. Look at the swimming pool. Some boys are swimming in the (2)____. They are fast like fish. In the big hall, a basketball game is happening. Ten students are playing (3)____. Many people are watching them. Near the window, two girls are dancing (4)____ music. They look very beautiful. Where is Tony? Oh, he is sitting on a chair. He is (5)____ a storybook. He is resting because he is (6)____ after running. Everyone is having a (7)____ time at the center at the (8)____.', 103, 3, '[{"q":"1","options":["now","yesterday","ago","last week"],"answer":"A","explanation":"现在进行时(are doing)→时间状语 **now**。"},{"q":"2","options":["tree","room","water","desk"],"answer":"C","explanation":"swimming pool→在 **water** 里游泳。"},{"q":"3","options":["books","food","music","basketball"],"answer":"D","explanation":"a basketball game→打 **basketball**。"},{"q":"4","options":["on","to","under","from"],"answer":"B","explanation":"dance **to** music(随着音乐跳)。"},{"q":"5","options":["writing","reading","cooking","washing"],"answer":"B","explanation":"a storybook→**reading**(看书)。"},{"q":"6","options":["happy","dangerous","fast","tired"],"answer":"D","explanation":"resting after running→**tired**(累)。"},{"q":"7","options":["bad","cold","good","noisy"],"answer":"C","explanation":"have a **good** time(玩得开心,固定)。"},{"q":"8","options":["moment","year","month","morning"],"answer":"A","explanation":"at the **moment**(此刻,进行时标志)。"}]'::jsonb, 2
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U5 完形:At the Sports Center');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c6000001-0a1b-4c2d-8e3f-000000000011', 7, '7B', 'U6', '七下 U6 完形:The Weather Today', 'Today is Saturday. How (1)____ the weather today? It is (2)____ in Beijing now. The sun is shining brightly. But the weather (3)____ different in Harbin. It is snowy and very (4)____ there. People are wearing heavy clothes. Look! Some children (5)____ a snowman in the park. They are laughing. What about London? It (6)____ raining at the moment. The trees and roads are wet. The weather changes all the time, so people in different places (7)____ doing different things now. Are you (8)____ a good time in your city today?', 91, 3, '[{"q":"1","options":["am","are","is","be"],"answer":"C","explanation":"How **is** the weather?(weather 不可数)。"},{"q":"2","options":["sunny","sun","wind","rain"],"answer":"A","explanation":"It is **sunny**(It is+形容词;后文 sun shining)。"},{"q":"3","options":["am","is","are","be"],"answer":"B","explanation":"the weather(不可数)→**is**。"},{"q":"4","options":["hot","warm","cool","cold"],"answer":"D","explanation":"snowy+穿厚衣→很 **cold**。"},{"q":"5","options":["make","makes","is making","are making"],"answer":"D","explanation":"Look!+Some children(复数)→**are making**。"},{"q":"6","options":["are","is","am","be"],"answer":"B","explanation":"at the moment+It→**is** raining。"},{"q":"7","options":["are","is","am","be"],"answer":"A","explanation":"people(复数)+now→**are** doing。"},{"q":"8","options":["have","has","having","to have"],"answer":"C","explanation":"Are you **having** a good time?(Are+ing)。"}]'::jsonb, 1
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U6 完形:The Weather Today');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c6000002-0a1b-4c2d-8e3f-000000000012', 7, '7B', 'U6', '七下 U6 完形:A Rainy Sunday', 'I don''t like rainy days because I cannot play basketball outside. Today, it is (1)____ outside and the sky is grey. Big drops of water are falling from the sky. So, I must stay (2)____ home today. My father is looking out of the (3)____. He cannot drive his car because he cannot see the road clearly in the heavy (4)____. My mother is cooking a warm soup in the kitchen. My little sister is playing with her toys. We cannot see the (5)____ today because there are too many dark clouds. I hope tomorrow can be (6)____. Then the weather can be (7)____ and we can run in the (8)____ again!', 112, 3, '[{"q":"1","options":["sunny","windy","snowy","rainy"],"answer":"D","explanation":"don''t like rainy days+drops of water→**rainy**。"},{"q":"2","options":["on","at","under","from"],"answer":"B","explanation":"stay **at** home(待在家,固定)。"},{"q":"3","options":["desk","bed","window","chair"],"answer":"C","explanation":"look out of the **window**(向窗外看)。"},{"q":"4","options":["rain","snow","wind","sun"],"answer":"A","explanation":"heavy **rain**(大雨,看不清路)。"},{"q":"5","options":["sun","rain","water","snow"],"answer":"A","explanation":"too many dark clouds→看不见 **sun**(太阳)。"},{"q":"6","options":["rainy","cloudy","sunny","cold"],"answer":"C","explanation":"希望明天天好出去玩→**sunny**(晴)。"},{"q":"7","options":["bad","fine","wet","snowy"],"answer":"B","explanation":"The weather is **fine**(天气好,固定)。"},{"q":"8","options":["kitchen","room","bed","park"],"answer":"D","explanation":"天晴去 **park** 里跑(outside)。"}]'::jsonb, 2
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U6 完形:A Rainy Sunday');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c8000001-0a1b-4c2d-8e3f-000000000013', 7, '7B', 'U8', '七下 U8 完形:The King’s Clever Dog', 'Once upon a time, there (1)____ an old king in a beautiful castle. He had a very clever dog. One day, the king (2)____ to the deep forest alone. He (3)____ see the road back because it was too dark. He was very afraid. Then, his dog looked (4)____ him. The dog ran fast and found the king by his smell. After that, the dog led the king out (5)____ the forest. Finally, they came (6)____ to the castle safely. The king was very happy. He (7)____ the dog a big piece of meat. There (8)____ many rewards for the dog after that day.', 104, 3, '[{"q":"1","options":["is","was","are","were"],"answer":"B","explanation":"Once upon a time(过去)+an old king(单数)→there **was**。"},{"q":"2","options":["go","goes","went","going"],"answer":"C","explanation":"go 的过去式→**went**。"},{"q":"3","options":["couldn''t","can''t","don''t","didn''t"],"answer":"A","explanation":"过去\"不能\"+see→**couldn’t**(can 的过去否定)。"},{"q":"4","options":["at","after","up","for"],"answer":"D","explanation":"look **for** him(寻找)。"},{"q":"5","options":["from","in","on","of"],"answer":"D","explanation":"out **of** the forest(从……里出来)。"},{"q":"6","options":["back","to","in","out"],"answer":"A","explanation":"came **back** to the castle(回到)。"},{"q":"7","options":["give","gives","gave","giving"],"answer":"C","explanation":"give 的过去式→**gave**(给狗一块肉)。"},{"q":"8","options":["is","were","was","are"],"answer":"B","explanation":"many rewards(复数)+过去→there **were**。"}]'::jsonb, 1
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U8 完形:The King’s Clever Dog');

INSERT INTO junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order)
SELECT 'c8000002-0a1b-4c2d-8e3f-000000000014', 7, '7B', 'U8', '七下 U8 完形:The Little Bird and the Big Tree', 'Long ago, a little bird lived in a green forest. She was very small, but she had a big friend. It was an old (1)____. Every day, the bird (2)____ beautiful songs on it. The tree listened (3)____ her music and felt very happy. One day, a cold winter (4)____. The weather became very cold and snowy. The little bird had to (5)____ to the warm south. Before she left, she (6)____ to the tree, "Please wait for me." The tree was very sad, but he smiled and said, "(7)____, my friend. See you next year." Finally, spring came back, and the bird returned. She found her friend again and they were (8)____ again.', 114, 3, '[{"q":"1","options":["tree","dog","cat","river"],"answer":"A","explanation":"后文 the bird on it / The tree→老 **tree**(树)。"},{"q":"2","options":["made","sang","wrote","heard"],"answer":"B","explanation":"sing 的过去式+songs→**sang**(唱歌)。"},{"q":"3","options":["at","for","on","to"],"answer":"D","explanation":"listen **to** her music(听……)。"},{"q":"4","options":["stopped","left","came","lost"],"answer":"C","explanation":"寒冬\"来临\"→**came**(后文变冷下雪)。"},{"q":"5","options":["run","swim","fly","walk"],"answer":"C","explanation":"鸟去南方→**fly**(飞)。"},{"q":"6","options":["asked","called","told","said"],"answer":"D","explanation":"said **to** the tree(对……说;后接直接引语)。"},{"q":"7","options":["Hello","Goodbye","Morning","Thanks"],"answer":"B","explanation":"要离开+See you next year→**Goodbye**(再见)。"},{"q":"8","options":["happy","sad","cold","tired"],"answer":"A","explanation":"春天重逢→很 **happy**(快乐)。"}]'::jsonb, 2
WHERE NOT EXISTS (SELECT 1 FROM junior_cloze WHERE title = '七下 U8 完形:The Little Bird and the Big Tree');

-- 校验(单独跑): 全 7B 应共 16 行(含 U7), blanks 各 8
SELECT unit, sort_order, title, word_count, jsonb_array_length(questions) AS blanks FROM junior_cloze WHERE volume='7B' ORDER BY unit, sort_order;
-- END OF FILE cloze-u3-8.sql
