-- ============================================================
-- 选择性必修二 U5(First Aid)灌库(junior_* 表,volume='elective2' unit='U5' grade=11)。幂等。
-- preflight(grade 7-12 + senior 分类)已随必修一跑过,不必再跑。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 50 =====
DELETE FROM public.junior_vocab WHERE volume='elective2' AND unit='U5';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'aid', 'n.', '/eɪd/', '帮助;救助;急救', 'Knowing first aid can help you save a life in an emergency.', '懂得急救能帮你在紧急情况下挽救生命。', 'First Aid', 1, 0, 'senior', 'wordlist', 'elective2', 'U5', 'first aid', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'acid', 'n./adj.', '/ˈæsɪd/', '酸;酸的;酸性的', 'If acid touches your skin, wash the area with cool water at once.', '如果酸接触到皮肤,立刻用凉水冲洗该处。', 'First Aid', 2, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a strong acid', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'burn', 'n./v.', '/bɜːn/', '烧伤;烫伤;燃烧;灼烧', 'Place the burn under cool running water for at least ten minutes.', '把烧伤处放在凉水下冲至少十分钟。', 'First Aid', 3, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a first-degree burn', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'wound', 'n./v.', '/wuːnd/', '伤口;创伤;使受伤', 'The nurse cleaned the wound before she covered it with a cloth.', '护士在用布盖住伤口之前先把它清洗干净。', 'First Aid', 4, 0, 'senior', 'wordlist', 'elective2', 'U5', 'clean the wound', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'victim', 'n.', '/ˈvɪktɪm/', '受害者;患者;遇难者', 'We gave first aid to the victim before the ambulance arrived.', '在救护车到来之前,我们给受害者进行了急救。', 'First Aid', 5, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a choking victim', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'ambulance', 'n.', '/ˈæmbjələns/', '救护车', 'She called an ambulance as soon as the old man collapsed.', '老人一倒下,她就叫了救护车。', 'First Aid', 6, 0, 'senior', 'wordlist', 'elective2', 'U5', 'call an ambulance', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'choke', 'v.', '/tʃəʊk/', '(使)窒息;(使)哽住;噎住', 'A man at the next table was choking on a piece of steak.', '邻桌的一个男人被一块牛排噎住了。', 'First Aid', 7, 0, 'senior', 'wordlist', 'elective2', 'U5', 'choke on food', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'collapse', 'v./n.', '/kəˈlæps/', '(突然)倒下;昏倒;倒塌', 'The patient suddenly collapsed before the doctor could reach him.', '病人在医生赶到之前突然昏倒了。', 'First Aid', 8, 0, 'senior', 'wordlist', 'elective2', 'U5', 'collapse on the floor', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'swallow', 'v.', '/ˈswɒləʊ/', '吞下;咽下', 'A child can easily choke if they swallow something too quickly.', '孩子如果吞咽得太快,很容易噎住。', 'First Aid', 9, 0, 'senior', 'wordlist', 'elective2', 'U5', 'swallow the medicine', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'throat', 'n.', '/θrəʊt/', '咽喉;喉咙', 'He was holding his throat because the food was stuck inside.', '他捂着喉咙,因为食物卡在了里面。', 'First Aid', 10, 0, 'senior', 'wordlist', 'elective2', 'U5', 'hold one''s throat', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'swell', 'v.', '/swel/', '膨胀;肿胀', 'The sprained ankle began to swell soon after she slipped.', '扭伤的脚踝在她滑倒后不久就开始肿胀。', 'First Aid', 11, 0, 'senior', 'wordlist', 'elective2', 'U5', 'start to swell', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'swollen', 'adj.', '/ˈswəʊlən/', '(身体部位)肿起的;肿胀的', 'Her swollen ankle was red and very painful to touch.', '她肿胀的脚踝又红又痛,一碰就疼。', 'First Aid', 12, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a swollen ankle', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'sprain', 'v./n.', '/spreɪn/', '扭伤(关节);扭伤', 'He fell off his bike and sprained his ankle badly.', '他从自行车上摔下来,严重扭伤了脚踝。', 'First Aid', 13, 0, 'senior', 'wordlist', 'elective2', 'U5', 'sprain one''s ankle', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'ankle', 'n.', '/ˈæŋkl/', '踝;踝关节', 'She could not stand because her ankle was broken.', '她站不起来,因为踝关节骨折了。', 'First Aid', 14, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a broken ankle', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'slip', 'v./n.', '/slɪp/', '滑倒;滑落;溜走;小错误', 'He slipped on the wet floor and hurt his back.', '他在湿地板上滑倒,伤了背。', 'First Aid', 15, 0, 'senior', 'wordlist', 'elective2', 'U5', 'slip and fall', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'drown', 'v.', '/draʊn/', '(使)淹死;溺死;淹没', 'The lifeguard ran to help the boy before he could drown.', '救生员在男孩溺水前跑过去救他。', 'First Aid', 16, 0, 'senior', 'wordlist', 'elective2', 'U5', 'rescue a drowning victim', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'urgent', 'adj.', '/ˈɜːdʒənt/', '紧急的;急迫的;急切的', 'A serious burn needs urgent attention at a hospital.', '严重烧伤需要在医院得到紧急处理。', 'First Aid', 17, 0, 'senior', 'wordlist', 'elective2', 'U5', 'urgent attention', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'panic', 'v./n.', '/ˈpænɪk/', '(使)惊慌;惊恐;恐慌', 'When you give first aid, stay calm and do not panic.', '进行急救时要保持冷静,不要惊慌。', 'First Aid', 18, 0, 'senior', 'wordlist', 'elective2', 'U5', 'do not panic', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'scream', 'v./n.', '/skriːm/', '尖叫;高声喊;尖叫声', 'He heard someone scream for help from another table.', '他听见有人从另一桌大声呼救。', 'First Aid', 19, 0, 'senior', 'wordlist', 'elective2', 'U5', 'scream for help', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'grab', 'v.', '/ɡræb/', '抓住;攫取;抢夺', 'Grab your fist tightly and push up into the person''s stomach.', '紧紧握住自己的拳头,向上推压对方的腹部。', 'First Aid', 20, 0, 'senior', 'wordlist', 'elective2', 'U5', 'grab your fist', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'fist', 'n.', '/fɪst/', '拳;拳头', 'Make a fist and place it on the upper part of the stomach.', '握成拳头,放在腹部上方。', 'First Aid', 21, 0, 'senior', 'wordlist', 'elective2', 'U5', 'make a fist', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'wrap', 'v.', '/ræp/', '包;裹;(用手臂等)围住', 'Stand behind the victim and wrap your arms around his waist.', '站在受害者身后,用双臂环住他的腰。', 'First Aid', 22, 0, 'senior', 'wordlist', 'elective2', 'U5', 'wrap your arms around', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'slap', 'v./n.', '/slæp/', '(用手掌)打、拍;拍击', 'Slapping the choking person''s back may force out the food.', '拍打噎住者的背部也许能把食物拍出来。', 'First Aid', 23, 0, 'senior', 'wordlist', 'elective2', 'U5', 'slap on the back', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'motion', 'n.', '/ˈməʊʃn/', '运动;移动;动作', 'Push up and into the stomach in one quick motion.', '用一个快速的动作向上、向内推压腹部。', 'First Aid', 24, 0, 'senior', 'wordlist', 'elective2', 'U5', 'in one motion', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'loose', 'adj.', '/luːs/', '松的;未系紧的;宽松的', 'Cover the burnt area with a loose clean cloth.', '用一块宽松干净的布盖住烧伤的部位。', 'First Aid', 25, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a loose clean cloth', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'tight', 'adj./adv.', '/taɪt/', '牢固的;紧的;绷紧的;紧紧地', 'Hold the cloth tight so that the bleeding stops.', '把布按紧,好让出血止住。', 'First Aid', 26, 0, 'senior', 'wordlist', 'elective2', 'U5', 'hold it tight', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'tightly', 'adv.', '/ˈtaɪtli/', '紧紧地;牢固地;紧密地', 'Grab your fist tightly with your other hand.', '用另一只手紧紧握住你的拳头。', 'First Aid', 27, 0, 'senior', 'wordlist', 'elective2', 'U5', 'hold tightly', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'fabric', 'n.', '/ˈfæbrɪk/', '织物;布料;结构', 'Do not pull off clothes if the fabric is sticking to the burnt skin.', '如果布料粘在烧伤的皮肤上,不要把衣服扯下来。', 'First Aid', 28, 0, 'senior', 'wordlist', 'elective2', 'U5', 'the fabric sticking to skin', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'layer', 'n.', '/ˈleɪə(r)/', '层;表层;层次', 'A serious burn can damage every layer of the skin.', '严重的烧伤会损坏皮肤的每一层。', 'First Aid', 29, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a layer of skin', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'organ', 'n.', '/ˈɔːɡən/', '(人或动植物的)器官', 'Chemicals can harm your internal organs if they are swallowed.', '化学品如果被吞下,会损害你的内脏器官。', 'First Aid', 30, 0, 'senior', 'wordlist', 'elective2', 'U5', 'an internal organ', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'nerve', 'n.', '/nɜːv/', '神经', 'A third-degree burn may damage the nerves under the skin.', '三度烧伤可能损坏皮肤下的神经。', 'First Aid', 31, 0, 'senior', 'wordlist', 'elective2', 'U5', 'damage the nerves', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'obstruction', 'n.', '/əbˈstrʌkʃn/', '阻碍;堵塞;阻塞物', 'Keep pushing until the obstruction is forced out of the throat.', '持续推压,直到阻塞物从喉咙里被推出来。', 'First Aid', 32, 0, 'senior', 'wordlist', 'elective2', 'U5', 'force out the obstruction', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'interrupt', 'v.', '/ˌɪntəˈrʌpt/', '打断;打扰;使中断', 'His dinner was interrupted when he heard someone scream.', '他听到有人尖叫,晚餐被打断了。', 'First Aid', 33, 0, 'senior', 'wordlist', 'elective2', 'U5', 'have one''s dinner interrupted', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'desperate', 'adj.', '/ˈdespərət/', '绝望的;拼命的;非常需要的', 'His desperate friends were slapping him hard on the back.', '他焦急绝望的朋友们正在用力拍他的背。', 'First Aid', 34, 0, 'senior', 'wordlist', 'elective2', 'U5', 'his desperate friends', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'minor', 'adj.', '/ˈmaɪnə(r)/', '较小的;次要的;轻微的', 'A minor burn can be treated at home with cool water.', '轻微的烧伤可以在家里用凉水处理。', 'First Aid', 35, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a minor injury', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'practical', 'adj.', '/ˈpræktɪkl/', '切实可行的;实际的;实用的', 'The Heimlich manoeuvre is quick, practical and easy to learn.', '海姆立克急救法快速、实用,而且容易学。', 'First Aid', 36, 0, 'senior', 'wordlist', 'elective2', 'U5', 'quick and practical', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'ease', 'v./n.', '/iːz/', '减轻;缓解;宽慰;容易;舒适', 'Cool water can ease the pain of a small burn.', '凉水能减轻小烧伤的疼痛。', 'First Aid', 37, 0, 'senior', 'wordlist', 'elective2', 'U5', 'ease the pain', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'delay', 'v./n.', '/dɪˈleɪ/', '推迟;耽误;延误', 'The team gave her oxygen without delay and checked her vital signs.', '急救队毫不耽搁地给她吸氧,并检查了她的生命体征。', 'First Aid', 38, 0, 'senior', 'wordlist', 'elective2', 'U5', 'without delay', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'justify', 'v.', '/ˈdʒʌstɪfaɪ/', '证明……有道理;为……辩护', 'He said he could not justify sitting there and doing nothing.', '他说他无法为坐在那里什么都不做而辩解。', 'First Aid', 39, 0, 'senior', 'wordlist', 'elective2', 'U5', 'justify doing nothing', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'welfare', 'n.', '/ˈwelfeə(r)/', '幸福;福祉;安康;福利', 'We all have a responsibility to look after one another''s welfare.', '我们都有责任照顾彼此的安康。', 'First Aid', 40, 0, 'senior', 'wordlist', 'elective2', 'U5', 'look after one''s welfare', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'elderly', 'adj.', '/ˈeldəli/', '年纪较大的;上了年纪的', 'The elderly woman lived alone and could not get up after she fell.', '这位上了年纪的妇人独自居住,摔倒后无法起身。', 'First Aid', 41, 0, 'senior', 'wordlist', 'elective2', 'U5', 'an elderly woman', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'ward', 'n.', '/wɔːd/', '病房', 'She had to stay in the hospital ward for a week.', '她不得不在医院病房里住了一周。', 'First Aid', 42, 0, 'senior', 'wordlist', 'elective2', 'U5', 'the hospital ward', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'needle', 'n.', '/ˈniːdl/', '针;缝衣针;注射针;指针', 'The paramedic put in an IV needle and gave her oxygen.', '急救医生插入静脉注射针,并给她吸氧。', 'First Aid', 43, 0, 'senior', 'wordlist', 'elective2', 'U5', 'an IV needle', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'underneath', 'prep./adv.', '/ˌʌndəˈniːθ/', '在……底下;隐藏在下面', 'A deep burn can reach the layers underneath the skin.', '深度烧伤会伤及皮肤下面的各层。', 'First Aid', 44, 0, 'senior', 'wordlist', 'elective2', 'U5', 'the skin underneath', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'toxin', 'n.', '/ˈtɒksɪn/', '毒素', 'Some insect bites leave a toxin that makes the skin swell.', '有些虫咬会留下毒素,使皮肤肿胀。', 'First Aid', 45, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a dangerous toxin', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'radiation', 'n.', '/ˌreɪdiˈeɪʃn/', '辐射;放射线', 'Strong radiation from the sun can also burn your skin.', '来自太阳的强辐射也会灼伤你的皮肤。', 'First Aid', 46, 0, 'senior', 'wordlist', 'elective2', 'U5', 'harmful radiation', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'ray', 'n.', '/reɪ/', '光线;光束;射线', 'He was woken by the bright rays of sunlight in the morning.', '早晨他被明亮的阳光照醒。', 'First Aid', 47, 0, 'senior', 'wordlist', 'elective2', 'U5', 'the sun''s rays', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'operator', 'n.', '/ˈɒpəreɪtə(r)/', '电话接线员;操作员', 'The operator stayed calm and told the boy exactly what to do.', '接线员保持镇定,准确地告诉男孩该怎么做。', 'First Aid', 48, 0, 'senior', 'wordlist', 'elective2', 'U5', 'the telephone operator', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'paramedic', 'n.', '/ˌpærəˈmedɪk/', '急救医生;护理人员', 'The paramedics checked his vital signs and took him to hospital.', '急救人员检查了他的生命体征,并把他送往医院。', 'First Aid', 49, 0, 'senior', 'wordlist', 'elective2', 'U5', 'ride with paramedics', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (11, 'manual', 'n./adj.', '/ˈmænjuəl/', '使用手册;说明书;用手的;手工的', 'He learned the steps from a first-aid manual at school.', '他在学校从一本急救手册上学会了这些步骤。', 'First Aid', 50, 0, 'senior', 'wordlist', 'elective2', 'U5', 'a first-aid manual', NULL);

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5');
DELETE FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e2u5.01', '①过去完成时(主动)表「过去的过去」', 'A2', 11, '选择性必修二 U5 — 两个过去动作中,先发生的那个用过去完成时 had done;常与 when / by + 过去时间 / before / already / by the time 连用,表示在某个过去时间点之前已完成或已持续。', 1, 'elective2', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e2u5.02', '②过去完成时被动 had been done', 'A2', 11, '选择性必修二 U5 — 当「过去的过去」里的动作是被动(主语承受动作)时,用 had been done。例如:伤口在护士包扎前已被清洗 → The wound had been cleaned。', 2, 'elective2', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e2u5.03', '③过去完成 vs 一般过去的时态对照', 'A2', 11, '选择性必修二 U5 — by the time / before / after / no sooner…than / hardly…when 等连接两个过去动作:先发生的用过去完成,后发生的用一般过去;倒装结构 No sooner had…than / Hardly had…when 固定搭配。', 3, 'elective2', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'When the doctor arrived, the man ____ breathing.', 'had already stopped', 'stops', 'has stopped', 'was stopped', 'A', '''医生到达''是过去,''停止呼吸''发生在更早 → 过去的过去用 had stopped。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'By 2010, the nurse ____ in that hospital for ten years.', 'worked', 'had worked', 'has worked', 'works', 'B', 'by + 过去时间,表示到那个过去时间点已持续 → had worked。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'By the time the ambulance came, the boy ____ first aid to his grandfather.', 'gives', 'has given', 'had given', 'was given', 'C', '''救护车来''是过去,''已给急救''更早 → had given。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'She ____ the burn under cool water before the swelling got worse.', 'puts', 'has put', 'was put', 'had put', 'D', 'before 引导另一过去动作,''放在水下''更早 → had put。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'When we reached the table, the diner ____ already on the floor.', 'had already fallen', 'falls', 'has fallen', 'is fallen', 'A', '''我们到达''是过去,''倒下''更早且 already → had fallen。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'Chen reacted fast because he ____ how to give first aid at school.', 'learns', 'had learned', 'has learned', 'was learned', 'B', '''反应快''是过去,''学过急救''在更早 → had learned。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'Before the paramedics came, the friends ____ him several times on the back.', 'slap', 'have slapped', 'had slapped', 'were slapped', 'C', 'before + 过去,''拍背''更早 → had slapped。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'By the time help arrived, the elderly woman ____ for almost an hour.', 'waits', 'has waited', 'was waited', 'had waited', 'D', 'by the time + 过去,表示已持续 → had waited。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'The victim ____ a lot of blood before anyone noticed the wound.', 'had lost', 'loses', 'has lost', 'was lost', 'A', 'before 引导后发生的过去动作,''失血''更早 → had lost。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'When the operator answered, the boy ____ his grandfather on his back.', 'lays', 'had already laid', 'has laid', 'is laid', 'B', '''接线员接听''是过去,''已让爷爷躺下''更早 → had laid。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'She realised that she ____ the medicine at home by mistake.', 'leaves', 'has left', 'had left', 'was left', 'C', '''意识到''是过去,''把药落下''发生在更早 → had left。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'By the time the doctor checked him, the patient ____ to breathe again.', 'begins', 'has begun', 'is begun', 'had begun', 'D', 'by the time + 过去,''重新呼吸''更早 → had begun。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'When I got to the kitchen, my brother ____ his hand on the hot pan.', 'had already burned', 'burns', 'has burned', 'was burned', 'A', '''我到厨房''是过去,''烫到手''更早 → had burned。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'Mrs Taylor ____ her phone to call for help before she fell over.', 'sets', 'had set', 'has set', 'was set', 'B', 'before + 过去,''设置好手机''更早 → had set。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'He told us that he ____ a first-aid course the year before.', 'takes', 'has taken', 'had taken', 'was taken', 'C', '''告诉''是过去,''上过课''在更早的一年 → had taken。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'By the time the lifeguard reached him, the swimmer ____ under the water.', 'goes', 'has gone', 'is gone', 'had gone', 'D', 'by the time + 过去,''沉入水下''更早 → had gone。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'When the nurse came back, the child ____ the whole glass of water.', 'had already swallowed', 'swallows', 'has swallowed', 'is swallowed', 'A', '''护士回来''是过去,''喝完水''更早 → had swallowed。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'She felt better because the doctors ____ her the right treatment.', 'give', 'had given', 'have given', 'were given', 'B', '''感觉好转''是过去,''给治疗''在更早 → had given。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'Before the ambulance left, the team ____ all of his vital signs.', 'check', 'have checked', 'had checked', 'was checked', 'C', 'before + 过去,''检查体征''更早 → had checked。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.01'), 'By midnight, the pain in her swollen ankle ____ a little.', 'eases', 'has eased', 'was eased', 'had eased', 'D', 'by + 过去时间,表示到那时已减轻 → had eased。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'The wound ____ before the nurse bandaged it.', 'had been cleaned', 'cleaned', 'has been cleaned', 'was cleaning', 'A', '伤口是被清洗(被动),且在包扎前已完成 → had been cleaned。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'When we got there, the victim ____ to hospital already.', 'took', 'had already been taken', 'has been taken', 'was taking', 'B', '受害者被送(被动),在我们到达前已完成 → had been taken。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'By the time the fire stopped, the burnt area ____ with a loose cloth.', 'covered', 'has been covered', 'had been covered', 'was covering', 'C', '烧伤处被盖住(被动),火停前已完成 → had been covered。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'She found that her phone ____ to call an emergency number at one touch.', 'sets up', 'has been set up', 'was setting up', 'had been set up', 'D', '手机被预先设置(被动),''发现''之前已完成 → had been set up。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'Before the doctor came, the obstruction ____ out of the man''s throat.', 'had already been forced', 'forced', 'has been forced', 'was forcing', 'A', '阻塞物被推出(被动),医生来前已完成 → had been forced。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'When the team arrived, an IV needle ____ into the patient''s arm.', 'put', 'had already been put', 'has been put', 'was putting', 'B', '注射针被插入(被动),急救队到达前已完成 → had been put。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'By the time she woke up, her cut ____ and bandaged.', 'cleaned', 'has been cleaned', 'had been cleaned', 'was cleaning', 'C', '伤口被清洗(被动),她醒前已完成 → had been cleaned。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'He realised that the medicine ____ on the table by his mother.', 'leaves', 'has been left', 'was leaving', 'had been left', 'D', '药被留下(被动),''意识到''之前已完成 → had been left。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'When the ambulance arrived, the victim ____ on his back by his friends.', 'had already been laid', 'lay', 'has been laid', 'was laying', 'A', '受害者被放平(被动),救护车到达前已完成 → had been laid。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'Before the lesson ended, the steps of CPR ____ to the whole class.', 'taught', 'had been taught', 'has been taught', 'was teaching', 'B', '步骤被教(被动),课结束前已完成 → had been taught。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'She was glad that the burn ____ under cool water in good time.', 'places', 'has been placed', 'had been placed', 'was placing', 'C', '烧伤处被放在水下(被动),''高兴''之前已完成 → had been placed。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'By the time the doctors left, the patient ____ that he was fine.', 'tells', 'has been told', 'was telling', 'had been told', 'D', '病人被告知(被动),医生离开前已完成 → had been told。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'When the rescue team came, the swimmer ____ out of the water already.', 'had already been pulled', 'pulled', 'has been pulled', 'was pulling', 'A', '游泳者被拉上岸(被动),救援队到达前已完成 → had been pulled。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'Before the manager checked, the first-aid kit ____ near the door.', 'placed', 'had been placed', 'has been placed', 'was placing', 'B', '急救箱被放置(被动),检查前已完成 → had been placed。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'She found that the loose clothes ____ off with scissors before she woke.', 'take', 'has been taken', 'had been taken', 'was taking', 'C', '衣服被剪掉(被动),她醒前已完成 → had been taken。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'By the time we reached the ward, his vital signs ____ twice.', 'check', 'have been checked', 'were checking', 'had been checked', 'D', '体征被检查(被动),到达病房前已完成 → had been checked。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'When the boy hung up, an ambulance ____ to his home already.', 'had already been sent', 'sent', 'has been sent', 'was sending', 'A', '救护车被派出(被动),挂电话前已完成 → had been sent。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'Before the family arrived, the wound ____ with a clean cloth.', 'wraps', 'had been wrapped', 'has been wrapped', 'was wrapping', 'B', '伤口被包扎(被动),家人到达前已完成 → had been wrapped。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'She was sure the oxygen ____ to the patient before the trip to hospital.', 'gives', 'has been given', 'had been given', 'was giving', 'C', '氧气被给予(被动),去医院前已完成 → had been given。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.02'), 'By the time the news spread, thousands of lives ____ by the new method.', 'save', 'have been saved', 'were saving', 'had been saved', 'D', '生命被挽救(被动),消息传开前已完成 → had been saved。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'By the time the operator answered, the old man ____ to breathe.', 'had stopped', 'stopped', 'stops', 'has stopped', 'A', 'by the time + 过去,先发生的''停止呼吸''用过去完成 → had stopped。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'The ambulance ____ as soon as the boy finished the call.', 'had arrived', 'arrived', 'arrives', 'has arrived', 'B', 'as soon as 连接的两个动作几乎同时,''到达''用一般过去 → arrived。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'No sooner ____ the steak than he began to choke.', 'he had swallowed', 'he swallowed', 'had he swallowed', 'did he swallow', 'C', 'No sooner 置于句首要倒装,且先发生用过去完成 → had he swallowed。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'Hardly had Chen sat down ____ he heard someone scream.', 'than', 'after', 'while', 'when', 'D', 'Hardly…when 是固定搭配,意为''刚……就……''。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'After she ____ the burn under cool water, she covered it with a cloth.', 'had placed', 'places', 'place', 'has placed', 'A', 'after 引导先发生的动作,用过去完成 → had placed。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'When the doctors finally came, they ____ that he was already fine.', 'had found', 'found', 'find', 'have found', 'B', '主句''发现''在过去这一刻发生,用一般过去 → found。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'No sooner had the team given him oxygen ____ his colour came back.', 'when', 'after', 'than', 'while', 'C', 'No sooner…than 固定搭配,意为''一……就……''。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'Before the nurse arrived, the friends ____ everything they could.', 'tried', 'try', 'have tried', 'had tried', 'D', 'before 引导后发生的''到达'',先发生的''尝试''用过去完成 → had tried。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'Hardly ____ the floor when she heard the front door open.', 'had she reached', 'she had reached', 'she reached', 'did she reach', 'A', 'Hardly 置于句首要倒装,且先发生用过去完成 → had she reached。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'After he ____ the Heimlich manoeuvre, the food was forced out.', 'does', 'had done', 'do', 'has done', 'B', 'after 引导先发生的动作,用过去完成 → had done。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'By the time we got the leaflet, the first-aid class ____ already.', 'finished', 'finishes', 'had finished', 'has finished', 'C', 'by the time + 过去 + already,先发生的''结束''用过去完成 → had finished。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'She ____ the emergency number the moment she saw him collapse.', 'had dialled', 'dials', 'has dialled', 'dialled', 'D', 'the moment 连接的动作几乎同时,''拨号''用一般过去 → dialled。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'No sooner had the bleeding stopped ____ the patient opened his eyes.', 'than', 'when', 'after', 'while', 'A', 'No sooner…than 固定搭配。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'After the wound ____ cleaned, the nurse put a bandage on it.', 'is', 'had been', 'be', 'has been', 'B', 'after 引导先发生的被动动作,用过去完成被动 had been (cleaned)。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'Hardly had he made a fist ____ he began the chest pushes.', 'than', 'after', 'when', 'while', 'C', 'Hardly…when 固定搭配。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'When the lights came back on, the boy ____ already given first aid.', 'did', 'does', 'has', 'had', 'D', '''灯亮''是过去,''已做急救''更早 → had (already given)。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'Before the manoeuvre ____ invented, many choking victims had died.', 'was', 'had been', 'is', 'has been', 'A', 'before 引导后发生(被发明)的动作,用一般过去被动 was invented;主句''已死亡''才用过去完成。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'After the victim ____ to hospital, his family felt much calmer.', 'is taken', 'had been taken', 'be taken', 'has been taken', 'B', 'after 引导先发生的被动动作,用过去完成被动 had been taken。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'No sooner ____ he stood up than he felt the pain in his ankle.', 'did', 'after', 'had', 'when', 'C', 'No sooner 句首倒装,先发生用过去完成 → had he stood。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5' AND code='e2u5.03'), 'By the time the radio programme ended, she ____ all the first-aid steps.', 'noted', 'notes', 'has noted', 'had noted', 'D', 'by the time + 过去,先发生的''记下步骤''用过去完成 → had noted。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE volume='elective2' AND unit='U5';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (11, 'Your Skin and Burns', 'Your skin is the largest organ of your body, and it does much more than you might think. It keeps water inside, holds your body heat, and gives you protection from many dangerous things in the world around you. Because the skin is so important, a burn can be a very serious injury. Burns are sorted into three types by how deep they go. A first-degree burn is the least serious; it touches only the top layer of skin, which turns dry and red. A second-degree burn reaches deeper, and the skin becomes red, swollen and very painful. A third-degree burn is the most serious of all. It can damage every layer of skin and sometimes the nerves underneath, so there may be little or no pain. Knowing these differences helps you decide how much first aid a burn needs and whether to take the victim to hospital.', 'First Aid', 148, '[{"q":"Why does the writer say a burn can be a serious injury?","answer":"A","options":["Because the skin does so many important jobs for the body.","Because the skin grows back very quickly.","Because skin has no feeling at all.","Because the skin is the smallest organ."],"explanation":"原文先说皮肤的多种重要作用,再说''Because the skin is so important, a burn can be a very serious injury'' 的转述。"},{"q":"What is true about a first-degree burn?","answer":"B","options":["It damages the nerves under the skin.","Only the skin''s top layer is affected.","It is the deepest kind of burn.","It causes no change in the skin''s colour."],"explanation":"原文 ''touches only the top layer of skin, which turns dry and red'' 的转述。"},{"q":"Why might a third-degree burn cause little pain?","answer":"A","options":["Because the nerves under the skin may be damaged.","Because it is not a real burn.","Because the skin turns red and swollen.","Because cool water has been used."],"explanation":"原文 ''can damage… the nerves underneath, so there may be little or no pain'' 的转述。"}]'::jsonb, '[{"word":"organ","cn":"器官"},{"word":"layer","cn":"层"},{"word":"swollen","cn":"肿胀的"},{"word":"nerve","cn":"神经"}]'::jsonb, 2, 'elective2', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (11, 'First Aid for Burns', 'If someone gets burnt, acting quickly and correctly can make a big difference. The first and most important step is to place the burn under cool running water, especially within the first ten minutes. The cool water stops the burning process and reduces the pain and swelling. After that, dry the area gently with a clean cloth. If there are clothes near the burn, you can cut them away with scissors, but never pull them off when the fabric is sticking to the skin. Next, cover the burn loosely with a clean cloth to keep it safe. Many people think that putting oil or butter on a burn helps, but this is bad advice. Oil keeps the heat inside the wound and may cause infection. If the burn is on the face, make sure the victim can still breathe. For a second-degree or third-degree burn, there is an urgent need to get the victim to hospital at once.', 'First Aid', 158, '[{"q":"What is the most important first step for a burn?","answer":"B","options":["Putting oil on it straight away.","Cooling it under running water as soon as possible.","Pulling off all the clothes near it.","Taking the victim straight to hospital."],"explanation":"原文 ''The first and most important step is to place the burn under cool running water'' 的转述。"},{"q":"When should you NOT pull clothes off a burn?","answer":"C","options":["When the burn is on the face.","When the water is too cold.","When the fabric is stuck to the skin.","When the cloth is clean."],"explanation":"原文 ''never pull them off when the fabric is sticking to the skin'' 的转述。"},{"q":"Why is putting oil on a burn a bad idea?","answer":"D","options":["It costs too much money.","It washes the burn too fast.","It makes the skin too cold.","It traps heat in the wound and may lead to infection."],"explanation":"原文 ''Oil keeps the heat inside the wound and may cause infection'' 的转述。"}]'::jsonb, '[{"word":"swelling","cn":"肿胀"},{"word":"fabric","cn":"布料"},{"word":"loosely","cn":"宽松地"},{"word":"urgent","cn":"紧急的"}]'::jsonb, 2, 'elective2', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (11, 'A Dinner Saved a Life', 'Chen Wei, a high school student in Beijing, was having dinner when he heard someone screaming at another table. A man called Zhang Tao was choking on a piece of steak. He was holding his throat, his face turning red, while his desperate friends slapped him on the back. Chen wasted no time. He had learned how to give first aid at school, so he stayed calm and ran over at once. Standing behind Zhang, he wrapped his arms around the man''s waist, made a fist, and pushed up into his stomach with a quick motion. After a few tries, the food was forced out, and Zhang could breathe again. Ten minutes later, an ambulance arrived, and the doctors checked Zhang and found that he was fine. Later, Chen said simply, "How could I justify sitting there and doing nothing? We all have a responsibility to look after one another''s welfare."', 'First Aid', 151, '[{"q":"How was Chen Wei able to act so quickly and calmly?","answer":"A","options":["He had learned first aid at school.","He was a trained doctor.","He was a friend of Zhang Tao.","He had eaten the same steak before."],"explanation":"原文 ''He had learned how to give first aid at school, so he stayed calm'' 的转述。"},{"q":"What did Chen do to help Zhang Tao?","answer":"B","options":["He slapped Zhang''s face.","He pushed up into Zhang''s stomach from behind.","He gave Zhang some water to drink.","He waited for the ambulance to come."],"explanation":"原文描述海姆立克法 ''wrapped his arms… made a fist, and pushed up into his stomach'' 的转述。"},{"q":"What does Chen''s final comment show about him?","answer":"C","options":["He wants to become a famous doctor.","He thinks first aid is too difficult.","He believes we should care for one another.","He was angry at Zhang''s friends."],"explanation":"末句 ''we all have a responsibility to look after one another''s welfare'' 体现他的责任感。"}]'::jsonb, '[{"word":"choke","cn":"噎住"},{"word":"desperate","cn":"焦急绝望的"},{"word":"justify","cn":"为……辩护"},{"word":"welfare","cn":"安康;福祉"}]'::jsonb, 2, 'elective2', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (11, 'Mrs Taylor''s Lucky Day', 'Mrs Taylor was an elderly woman who lived alone. One day, while she was cleaning the windows in her living room, she suddenly could not feel the right side of her body. As she tried to walk to her sofa, she fell over onto the carpet. She found that she could not get up, and she was having trouble breathing. Luckily, she had her mobile phone with her, and she was able to reach it with her left hand. Her phone had already been set up to call an emergency number at the push of a button, so it was easy to call for help. When Mrs Taylor could not speak, the operator knew at once that something was wrong and sent an ambulance. The team soon found her, gave her oxygen without delay, put in an IV needle, and checked her vital signs. Because she was treated so quickly, her health was in no great danger, though she had to stay in the hospital ward for a week.', 'First Aid', 169, '[{"q":"What happened to Mrs Taylor while she was cleaning the windows?","answer":"D","options":["She broke a window with her hand.","She fainted from the heat.","She dropped her phone outside.","She lost feeling on one side of her body."],"explanation":"原文 ''she suddenly could not feel the right side of her body'' 的转述。"},{"q":"How was she able to call for help so easily?","answer":"A","options":["One touch on her phone would dial the emergency number she had saved.","A neighbour heard her shouting.","She walked to the phone on the wall.","The operator called her first."],"explanation":"原文 ''phone had already been set up to call an emergency number at the push of a button'' 的转述。"},{"q":"Why was Mrs Taylor''s life not in great danger?","answer":"B","options":["Because she was not really hurt.","Because she received treatment very quickly.","Because she stayed at home alone.","Because she could still speak clearly."],"explanation":"原文 ''Because she was treated so quickly, her health was in no great danger'' 的转述。"}]'::jsonb, '[{"word":"elderly","cn":"上了年纪的"},{"word":"delay","cn":"耽搁"},{"word":"ward","cn":"病房"},{"word":"operator","cn":"接线员"}]'::jsonb, 2, 'elective2', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (11, 'Rescuing a Drowning Swimmer', 'Helping someone who is drowning takes both speed and care. The first thing to do is to get the person out of the water safely, and then call for an ambulance straight away. Once the victim is on the ground, lay him on his back and check whether he is breathing. If he is not breathing, you may need to perform rescue breathing. Lift up his chin, cover his mouth with yours, and gently blow air in. After that, push down on the centre of his chest, about twice a second. Keep going, breathing for him and pushing on his chest, until he starts to breathe by himself or until help arrives. Never give up too soon, because every minute counts. New kinds of rescue are appearing too. In Brazil, some lifeguards now use small flying machines called paramotors to reach swimmers in danger and drop them something to hold on to before the lifeguards can swim out.', 'First Aid', 158, '[{"q":"What should you do first for a drowning person?","answer":"C","options":["Push down on the chest.","Blow air into the mouth.","Bring the victim safely to land, then phone for an ambulance.","Wait for the lifeguards to come."],"explanation":"原文 ''The first thing to do is to get the person out of the water safely, and then call for an ambulance'' 的转述。"},{"q":"What does the writer mean by saying ''every minute counts''?","answer":"D","options":["You should count the minutes out loud.","Rescue always takes many minutes.","You should only try for one minute.","Acting fast is very important for the victim."],"explanation":"''every minute counts'' 强调时间宝贵、要快速行动,故 A。"},{"q":"How do some lifeguards in Brazil reach swimmers in danger?","answer":"A","options":["They use flying machines called paramotors.","They send out boats only.","They wait on the beach for help.","They throw ropes from a tower."],"explanation":"末段 ''use small flying machines called paramotors to reach swimmers'' 的转述。"}]'::jsonb, '[{"word":"drown","cn":"溺水"},{"word":"chin","cn":"下巴"},{"word":"rescue","cn":"救援"}]'::jsonb, 2, 'elective2', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (11, 'Be Ready: Make a First-Aid Kit', 'Emergencies often happen when we least expect them, so it is wise to be ready before they do. One simple way to prepare is to keep a first-aid kit at home and in the car. A good kit does not have to be expensive; most of the items can be bought cheaply at a pharmacy. It should hold things you can use to clean and cover a wound, something to ease pain, and a clean cloth to wrap around a sprained ankle. It is also a good idea to put a small information sheet inside the box. The sheet should list the emergency phone numbers, the items in the kit, and a short note on how and when to use each one. Store the kit somewhere that is easy to find, so that anyone in the family can reach it in a hurry. Being prepared will not stop accidents from happening, but it can help you stay calm and act fast when they do.', 'First Aid', 164, '[{"q":"Why does the writer suggest keeping a first-aid kit?","answer":"B","options":["Because kits are very cheap to sell.","Because emergencies can happen at any time.","Because the law says everyone must own one.","Because it looks nice in the home."],"explanation":"原文 ''Emergencies often happen when we least expect them, so it is wise to be ready'' 的转述。"},{"q":"What should the information sheet inside the kit include?","answer":"C","options":["The price of each item.","A list of family birthdays.","Emergency numbers, the items, and how to use them.","A map of the nearest hospital."],"explanation":"原文 ''list the emergency phone numbers, the items in the kit, and a short note on how and when to use each one'' 的转述。"},{"q":"According to the writer, what can being prepared do?","answer":"D","options":["Stop all accidents from ever happening.","Make the family richer over time.","Replace the need for a hospital.","It lets you keep calm and respond quickly when trouble comes."],"explanation":"末句 ''it can help you stay calm and act fast when they do'' 的转述;另一项''阻止一切事故''被原文否定。"}]'::jsonb, '[{"word":"kit","cn":"成套用品;工具箱"},{"word":"ease","cn":"减轻"},{"word":"wrap","cn":"包裹"}]'::jsonb, 2, 'elective2', 'U5');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE volume='elective2' AND unit='U5';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (11, 'elective2', 'U5', 'Why I Took a First-Aid Course', 'Last summer I joined a first-aid (1)____ at the Red Cross. At first I thought it would be (2)____, but the lessons turned out to be very useful. We learned how to stay (3)____ instead of panicking when someone is hurt. Our teacher said that the most important thing is to act fast but never (4)____. We practised cleaning a (5)____ and covering it with a clean cloth. We also learned what to do when a person is (6)____ on food and cannot breathe. By the end of the course, I felt (7)____ that I could help in a real emergency. A few weeks later, my little brother (8)____ his ankle while playing, and I knew exactly what to do. I helped him sit down and then called my mum for (9)____. That day I understood why everyone should learn these simple (10)____.', 143, 2, '[{"q":"1","answer":"A","options":["course","noise","price","season"],"explanation":"a first-aid course 急救课程。"},{"q":"2","answer":"B","options":["useful","boring","happy","loud"],"explanation":"but 表转折,与 useful 相对,前面以为''无聊''→ boring。"},{"q":"3","answer":"C","options":["angry","afraid","calm","tired"],"explanation":"stay calm 保持冷静。"},{"q":"4","answer":"D","options":["smile","sleep","leave","panic"],"explanation":"never panic 永远别惊慌。"},{"q":"5","answer":"A","options":["wound","price","song","garden"],"explanation":"cleaning a wound 清洗伤口。"},{"q":"6","answer":"B","options":["singing","choking","reading","shopping"],"explanation":"choking on food 被食物噎住。"},{"q":"7","answer":"C","options":["sorry","bored","confident","afraid"],"explanation":"felt confident 感到自信。"},{"q":"8","answer":"D","options":["sold","ate","lost","sprained"],"explanation":"sprained his ankle 扭伤脚踝。"},{"q":"9","answer":"A","options":["help","money","fun","food"],"explanation":"call for help 求助。"},{"q":"10","answer":"B","options":["prices","skills","songs","machines"],"explanation":"simple skills 简单技能。"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (11, 'elective2', 'U5', 'Cooling a Small Burn', 'One evening, my sister touched a hot pan and burnt her (1)____. She screamed in pain, but I remembered the right (2)____ to take. First, I led her to the sink and put the burn under cool running (3)____. I kept it there for about ten (4)____, which stopped the heat and (5)____ the pain. Then I gently (6)____ the area with a clean cloth. I did not put any oil on it, because oil keeps the heat (7)____ and can cause infection. After that, I covered the burn (8)____ with a clean cloth so that it stayed safe. My sister soon felt much (9)____. The burn was only a small one, so we did not need to go to (10)____, but I was glad I knew what to do.', 130, 2, '[{"q":"1","answer":"C","options":["shoe","book","hand","wall"],"explanation":"burnt her hand 烫伤了手。"},{"q":"2","answer":"D","options":["price","songs","games","steps"],"explanation":"the right steps 正确的步骤。"},{"q":"3","answer":"A","options":["water","sand","fire","smoke"],"explanation":"cool running water 凉的流动水。"},{"q":"4","answer":"B","options":["metres","minutes","years","books"],"explanation":"ten minutes 十分钟。"},{"q":"5","answer":"C","options":["raised","sold","reduced","lost"],"explanation":"reduced the pain 减轻疼痛。"},{"q":"6","answer":"D","options":["threw","ate","sold","dried"],"explanation":"dried the area 把该处擦干。"},{"q":"7","answer":"A","options":["inside","away","out","off"],"explanation":"keeps the heat inside 把热量留在里面。"},{"q":"8","answer":"B","options":["tightly","loosely","quickly","angrily"],"explanation":"covered… loosely 宽松地盖住(烧伤忌包太紧)。"},{"q":"9","answer":"C","options":["worse","louder","better","richer"],"explanation":"felt much better 感觉好多了。"},{"q":"10","answer":"D","options":["school","market","library","hospital"],"explanation":"go to hospital 去医院。"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (11, 'elective2', 'U5', 'The Call That Saved Grandpa', 'One night, a boy was at home with his (1)____ when the old man suddenly fell to the floor and stopped moving. The boy did not (2)____. He quickly picked up the phone and called the emergency (3)____. A calm operator answered and asked him to (4)____ a few simple questions. She told him to lay his grandfather on his (5)____ and check whether he was breathing. Following her clear (6)____, the boy pressed down on the centre of his grandfather''s (7)____, twice a second. The operator kept talking to him so that he would not feel (8)____. A few minutes later, an (9)____ arrived, and the paramedics took over. Thanks to the boy''s quick action and the operator''s help, his grandfather''s (10)____ was saved.', 125, 2, '[{"q":"1","answer":"A","options":["grandfather","teacher","doctor","driver"],"explanation":"with his grandfather 和爷爷在一起(下文 old man / grandfather)。"},{"q":"2","answer":"B","options":["smile","panic","sleep","sing"],"explanation":"did not panic 没有惊慌。"},{"q":"3","answer":"C","options":["shop","garden","number","market"],"explanation":"emergency number 急救电话号码。"},{"q":"4","answer":"D","options":["sell","lose","throw","answer"],"explanation":"answer a few questions 回答几个问题。"},{"q":"5","answer":"A","options":["back","shop","price","song"],"explanation":"lay him on his back 让他仰卧。"},{"q":"6","answer":"B","options":["prices","instructions","songs","tickets"],"explanation":"clear instructions 清楚的指示。"},{"q":"7","answer":"C","options":["garden","market","chest","wall"],"explanation":"centre of his chest 胸部中央。"},{"q":"8","answer":"D","options":["happy","rich","tall","afraid"],"explanation":"would not feel afraid 不会害怕。"},{"q":"9","answer":"A","options":["ambulance","umbrella","elephant","envelope"],"explanation":"an ambulance arrived 救护车到了。"},{"q":"10","answer":"B","options":["price","life","song","game"],"explanation":"his life was saved 性命被救。"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (11, 'elective2', 'U5', 'First Aid for a Chemical Burn', 'A chemical burn happens when your skin or eyes come into contact with an (1)____ or other dangerous chemicals. Such burns can be very (2)____ and need urgent attention. If the chemical is (3)____, it can even harm your internal (4)____. So first aid must be given (5)____. Begin by washing the burnt area with plenty of cool (6)____ to remove the chemical. Be careful not to let it (7)____ to other parts of the skin. After washing, (8)____ the area loosely with a clean cloth. Do not rub the skin, as this may make the (9)____ worse. Most importantly, send the person to (10)____ right away if he or she is badly burnt, because only a doctor can treat a serious chemical burn safely.', 125, 2, '[{"q":"1","answer":"C","options":["apple","answer","acid","engine"],"explanation":"an acid 酸。"},{"q":"2","answer":"D","options":["funny","cheap","quiet","dangerous"],"explanation":"very dangerous 非常危险。"},{"q":"3","answer":"A","options":["swallowed","sung","sold","painted"],"explanation":"if the chemical is swallowed 如果被吞下。"},{"q":"4","answer":"B","options":["gardens","organs","markets","machines"],"explanation":"internal organs 内脏器官。"},{"q":"5","answer":"C","options":["slowly","never","immediately","secretly"],"explanation":"given immediately 立即进行。"},{"q":"6","answer":"D","options":["fire","sand","smoke","water"],"explanation":"cool water 凉水。"},{"q":"7","answer":"A","options":["spread","sleep","smile","sing"],"explanation":"let it spread 让它扩散。"},{"q":"8","answer":"B","options":["sell","wrap","eat","lose"],"explanation":"wrap the area 包住该处。"},{"q":"9","answer":"C","options":["price","song","burn","noise"],"explanation":"make the burn worse 使烧伤更糟。"},{"q":"10","answer":"D","options":["school","market","park","hospital"],"explanation":"send… to hospital 送往医院。"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (11, 'elective2', 'U5', 'When Nancy Hurt Her Ankle', 'Nancy decided to ride her bike home one (1)____ evening because she did not want to risk having it stolen. The streets near her office were bright, but after she turned onto a side (2)____, she found herself in the dark. She slowed (3)____ and tried to see ahead, but it was impossible. Then, without (4)____, her bike hit a rock, and she fell to the (5)____. When she tried to get up, she discovered that her (6)____ was hurt and badly (7)____. She could not stand or walk, and the pain was (8)____. Luckily, she had her mobile phone with her and was able to call an (9)____. They soon arrived and took her to hospital. It was several months before her ankle (10)____, and after that Nancy was much more careful at night.', 135, 2, '[{"q":"1","answer":"A","options":["foggy","happy","cheap","polite"],"explanation":"a foggy evening 有雾的夜晚。"},{"q":"2","answer":"B","options":["song","road","price","garden"],"explanation":"a side road 一条小路。"},{"q":"3","answer":"C","options":["up","off","down","in"],"explanation":"slowed down 慢下来。"},{"q":"4","answer":"D","options":["money","music","school","warning"],"explanation":"without warning 毫无预兆。"},{"q":"5","answer":"A","options":["ground","price","song","market"],"explanation":"fell to the ground 摔到地上。"},{"q":"6","answer":"B","options":["book","ankle","shop","ticket"],"explanation":"her ankle was hurt 脚踝受伤。"},{"q":"7","answer":"C","options":["sold","sung","swollen","painted"],"explanation":"badly swollen 严重肿胀。"},{"q":"8","answer":"D","options":["funny","cheap","quiet","terrible"],"explanation":"the pain was terrible 疼痛难忍。"},{"q":"9","answer":"A","options":["ambulance","umbrella","elephant","envelope"],"explanation":"call an ambulance 叫救护车。"},{"q":"10","answer":"B","options":["disappeared","recovered","increased","escaped"],"explanation":"before her ankle recovered 脚踝痊愈之前。"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (11, 'elective2', 'U5', 'How the Heimlich Manoeuvre Works', 'When a person is (1)____ on food and cannot speak, every second matters. One quick and (2)____ way to help is the Heimlich manoeuvre. First, make (3)____ that the person is really choking, because a choking person cannot (4)____. Slapping the person on the (5)____ may force out the food. If this does not work, stand (6)____ the victim and wrap your arms around the waist. Make a (7)____ with one hand and place it on the upper part of the stomach. (8)____ your fist tightly with your other hand, then push up and into the stomach in one (9)____. Keep doing this until the food is forced (10)____. With a small child, however, you should not do this, as you may hurt the child; instead, lay the child face down and give firm slaps to the upper back.', 139, 2, '[{"q":"1","answer":"C","options":["singing","reading","choking","shopping"],"explanation":"choking on food 被食物噎住。"},{"q":"2","answer":"D","options":["funny","expensive","quiet","practical"],"explanation":"quick and practical 快速而实用。"},{"q":"3","answer":"A","options":["sure","money","noise","song"],"explanation":"make sure 确保。"},{"q":"4","answer":"B","options":["eat","speak","sell","buy"],"explanation":"cannot speak 说不出话。"},{"q":"5","answer":"C","options":["price","song","back","garden"],"explanation":"slapping on the back 拍背。"},{"q":"6","answer":"D","options":["above","between","across","behind"],"explanation":"stand behind 站在身后。"},{"q":"7","answer":"A","options":["fist","price","song","noise"],"explanation":"make a fist 握成拳头。"},{"q":"8","answer":"B","options":["Sell","Grab","Lose","Throw"],"explanation":"Grab your fist 握住你的拳头。"},{"q":"9","answer":"C","options":["garden","market","motion","machine"],"explanation":"in one motion 一个动作。"},{"q":"10","answer":"D","options":["in","up","off","out"],"explanation":"forced out 被推出来。"}]'::jsonb, 6);

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE volume='elective2' AND unit='U5';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (11, 'U5 听力·对话 Choosing a First-Aid Skill', '选择性必修二 U5 · dialogue', 3, 'Lucy: Our school is offering a first-aid club. Which skill do you want to learn most, Tom?
Tom: I want to learn how to help a choking person. My uncle once choked on a fish bone.
Lucy: That sounds really useful. I''d like to learn how to treat burns.
Tom: Why burns?
Lucy: My little sister once burnt her hand on a hot pan, and I didn''t know what to do.
Tom: I see. Then this club is perfect for both of us.
Lucy: Yes. The teacher said we will also learn how to call for an ambulance.
Tom: Great. Let''s sign up together after class.', 'Lucy 问 Tom 最想学哪项急救;Tom 想学帮噎住的人,因为叔叔曾被鱼刺噎住;Lucy 想学处理烧伤,因为妹妹曾被热锅烫伤而自己不知所措;两人决定一起报名,还会学怎么叫救护车。', 'uk_female', '[{"q":"Which first-aid skill does Tom want to learn most?","type":"choice","answer":"A","options":["How to help a choking person.","How to treat a burn.","How to stop bleeding.","How to set a broken arm."]},{"q":"Why does Tom choose that skill?","type":"choice","answer":"B","options":["His teacher told him to.","His uncle once choked on a fish bone.","It is the easiest to learn.","He saw it in a film."]},{"q":"What does Lucy want to learn?","type":"choice","answer":"A","options":["How to treat burns.","How to swim.","How to drive a car.","How to cook fish."]},{"q":"What happened to Lucy''s little sister?","type":"choice","answer":"B","options":["She fell off a bike.","She burnt her hand on a hot pan.","She caught a cold.","She was bitten by a dog."]},{"q":"What else will the club teach them?","type":"choice","answer":"C","options":["How to play football.","How to write a story.","How to call for an ambulance.","How to sell medicine."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (11, 'U5 听力·短文 Emergency Numbers', '选择性必修二 U5 · passage', 2, 'Different countries use different emergency phone numbers.
In China, you can call one-two-zero for an ambulance.
In the United States, people call nine-one-one for any emergency.
In the United Kingdom, the number is nine-nine-nine.
When you call, stay calm and tell the operator clearly where you are and what has happened.', '不同国家有不同的急救电话:在中国拨120叫救护车;在美国拨911处理任何紧急情况;在英国是999;打电话时要保持冷静,清楚地告诉接线员你在哪里、发生了什么。', 'uk_female', '[{"q":"What is the main idea of the passage?","type":"choice","answer":"D","options":["All countries use the same number.","Emergency numbers are only for fun.","You should never call for help.","Different countries use different emergency numbers."]},{"q":"Which number do you call for an ambulance in China?","type":"choice","answer":"A","options":["120.","911.","999.","112."]},{"q":"What number is used in the United States?","type":"choice","answer":"B","options":["120.","911.","999.","000."]},{"q":"What should you do when you call?","type":"choice","answer":"C","options":["Hang up quickly.","Shout as loud as you can.","Stay calm and explain clearly.","Give a false name."]},{"q":"What two things should you tell the operator?","type":"choice","answer":"D","options":["Your favourite food and colour.","Your age and your school.","The weather and the time.","Where you are and what has happened."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (11, 'U5 听力·对话 A Friend Gets Burnt', '选择性必修二 U5 · dialogue', 3, 'Mark: Anna, come quick! I burnt my arm on the cooker!
Anna: Stay calm, Mark. Let me see. It''s red but not too deep.
Mark: It really hurts. Should I put some butter on it?
Anna: No, never put butter on a burn. That keeps the heat in.
Mark: So what should I do?
Anna: Hold your arm under cool running water for about ten minutes.
Mark: That feels much better already.
Anna: Good. Then we''ll cover it loosely with a clean cloth. If it gets worse, we''ll go to hospital.', 'Mark 在灶台上烫伤了胳膊,慌忙叫 Anna;Anna 让他冷静,查看后说不深;Mark 问能否抹黄油,Anna 说绝不能,会把热留住;她让他把胳膊放凉水下冲约十分钟,Mark 感觉好多了;之后用干净布宽松地盖住,若加重就去医院。', 'uk_female', '[{"q":"How did Mark hurt himself?","type":"choice","answer":"A","options":["He burnt his arm on the cooker.","He cut his finger with a knife.","He fell down the stairs.","He sprained his wrist."]},{"q":"What does Mark first think of putting on the burn?","type":"choice","answer":"B","options":["Cool water.","Butter.","A bandage.","Some ice."]},{"q":"Why does Anna say not to use butter?","type":"choice","answer":"C","options":["It is too expensive.","It smells bad.","It keeps the heat in the burn.","It washes the burn away."]},{"q":"What does Anna tell Mark to do?","type":"choice","answer":"D","options":["Rub the burn hard.","Wrap it very tightly.","Go straight to bed.","Hold it under cool running water."]},{"q":"What will they do if the burn gets worse?","type":"choice","answer":"A","options":["Go to hospital.","Put more butter on it.","Do nothing at all.","Cover it with oil."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (11, 'U5 听力·短文 The Heimlich Manoeuvre', '选择性必修二 U5 · passage', 2, 'The Heimlich manoeuvre is a simple way to help a person who is choking.
First, make sure the person really cannot speak or breathe.
Stand behind the person and wrap your arms around the waist.
Make a fist and push up into the stomach with quick movements.
Keep doing this until the food is forced out and the person can breathe again.', '海姆立克急救法是帮助噎住者的简单方法:先确认对方确实说不出话、不能呼吸;站到其身后,用双臂环住腰;握拳并用快速动作向上推压腹部;持续进行,直到食物被推出、对方重新能呼吸。', 'uk_female', '[{"q":"What is the Heimlich manoeuvre used for?","type":"choice","answer":"B","options":["To stop bleeding.","To help a choking person.","To cool a burn.","To treat a sprained ankle."]},{"q":"What should you check first?","type":"choice","answer":"C","options":["That the person has eaten enough.","That the room is warm.","That the person really cannot speak or breathe.","That an ambulance has come."]},{"q":"Where do you stand to do the manoeuvre?","type":"choice","answer":"D","options":["In front of the person.","Beside the door.","On a chair.","Behind the person."]},{"q":"How do you use your fist?","type":"choice","answer":"A","options":["You push up into the stomach.","You hold it on the person''s head.","You wave it in the air.","You press it on the chest."]},{"q":"When do you stop?","type":"choice","answer":"B","options":["After only one push.","When the food is forced out and the person can breathe.","When you feel tired.","When other people arrive."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (11, 'U5 听力·对话 A 999 Call', '选择性必修二 U5 · dialogue', 3, 'Operator: Emergency services. What is your emergency?
Boy: My grandfather has fallen down and he isn''t moving!
Operator: Stay calm. Is he breathing?
Boy: I''m not sure. He looks very pale.
Operator: All right. Put him on his back and remove any pillows.
Boy: Okay, I''ve done that.
Operator: Now put your hand in the middle of his chest and press down, twice a second.
Boy: I''m pressing now. Please send someone quickly!
Operator: An ambulance is already on the way. Keep going until it arrives.', '接线员问发生了什么;男孩说爷爷摔倒了,不动了;接线员让他冷静,问是否在呼吸;男孩说不确定、爷爷脸色很苍白;接线员指导他让爷爷仰卧、移开枕头,把手放在胸部中央每秒按压两次;男孩照做并请求快点派人;接线员说救护车已在路上,让他坚持到车来。', 'uk_female', '[{"q":"Why does the boy call the emergency services?","type":"choice","answer":"C","options":["His house is on fire.","He has lost his way home.","His grandfather has fallen and isn''t moving.","He has burnt his hand."]},{"q":"What does the operator ask first?","type":"choice","answer":"D","options":["The boy''s name.","The boy''s home address only.","What the boy had for dinner.","Whether his grandfather is breathing."]},{"q":"What does the operator tell the boy to do with his grandfather?","type":"choice","answer":"A","options":["Put him on his back and remove any pillows.","Make him sit up in a chair.","Give him some water.","Carry him outside."]},{"q":"How often should the boy press on the chest?","type":"choice","answer":"B","options":["Once a minute.","Twice a second.","Only one time.","Every ten seconds."]},{"q":"What does the operator say about the ambulance?","type":"choice","answer":"C","options":["It cannot come tonight.","The boy must drive it himself.","It is already on the way.","It will come tomorrow."]}]'::jsonb, '[]'::jsonb, 'long', 'elective2', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (11, 'U5 听力·短文 Three Rules of First Aid', '选择性必修二 U5 · passage', 2, 'Here are three simple rules to remember when you give first aid.
First, stay calm and do not panic, even if the person is badly hurt.
Second, make sure that the place is safe before you help.
Third, call for help early, and never be afraid to ask for an ambulance.
If you follow these rules, your quick action may save someone''s life.', '给急救时要记住三条简单原则:第一,保持冷静、别惊慌,哪怕伤者伤得很重;第二,在施救前确认现场安全;第三,尽早求助,别害怕叫救护车。遵守这些原则,你的迅速行动也许能救人一命。', 'uk_female', '[{"q":"How many rules does the speaker give?","type":"choice","answer":"D","options":["Five.","Four.","Two.","Three."]},{"q":"What is the first rule?","type":"choice","answer":"A","options":["Stay calm and do not panic.","Run away at once.","Wait for an hour.","Shout for a long time."]},{"q":"What should you check before helping?","type":"choice","answer":"B","options":["The time of day.","That the place is safe.","The price of medicine.","The colour of the sky."]},{"q":"What does the third rule say?","type":"choice","answer":"C","options":["Never call anyone.","Help only your family.","Call for help early and ask for an ambulance.","Keep the problem a secret."]},{"q":"What may your quick action do?","type":"choice","answer":"D","options":["Waste a lot of time.","Make people angry.","Cost too much money.","Save someone''s life."]}]'::jsonb, '[]'::jsonb, 'short', 'elective2', 'U5');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE volume='elective2' AND unit='U5';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit) VALUES (11, 'Write a Safety Guide: First-Aid Steps for an Emergency(写一份急救步骤说明)', 'How to Give First Aid for a Burn', '假设你是学校急救社团的成员,社团要制作一本《校园急救手册》。请用英语写一段约100词的说明文,说明烧伤(或烫伤)的急救步骤。内容包括:① 先做什么、为什么(用凉水冲);② 接下来的两三个步骤(擦干、宽松包扎等);③ 一条不该做的事(如抹油);④ 什么情况下要立即送医院。注意:用 first / next / then / finally 等顺序词,使过去完成时/被动语态等在合适处自然出现。', 'Suppose you are a member of your school''s first-aid club, which is making a Campus First-Aid Manual. Write a guide of about 100 words explaining the steps of first aid for a burn. Include: 1) what to do first and why (cool running water); 2) the next two or three steps (dry it, cover it loosely, etc.); 3) one thing you should NOT do (e.g. put oil on it); 4) when to take the victim to hospital at once. Use ordering words such as first, next, then and finally.', '["第一步与原因(First, place the burn under cool running water… because it stops the burning process）","中间步骤(Next, dry the area gently. / Then cover it loosely with a clean cloth.）","一条禁忌(Never put oil on a burn, as it keeps the heat in.）","送医时机 + 顺序词连贯(Finally, if the burn is serious, take the victim to hospital at once.）"]'::jsonb, 70, 100, 'Knowing how to treat a burn can make a big difference in an emergency. First, place the burnt area under cool running water for about ten minutes, because this stops the burning process and reduces the pain. Next, dry the area gently with a clean cloth. Then cover the burn loosely with another clean cloth to keep it safe. Never put oil or butter on a burn, as this keeps the heat in the wound and may cause infection. If clothes are stuck to the skin, do not pull them off. Finally, if the burn is a serious one, take the victim to hospital at once.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["First, place the burnt area under cool running water, because this stops the burning process.","Then cover the burn loosely with a clean cloth to keep it safe.","Never put oil or butter on a burn, as this keeps the heat in the wound.","Finally, if the burn is a serious one, take the victim to hospital at once."]'::jsonb, '[{"wrong":"Put the burn under water can stop the pain.","correct":"Putting the burn under water can stop the pain.","note":"句首作主语用动名词 Putting,不用动词原形。"},{"wrong":"When I arrived, the nurse already cleaned the wound.","correct":"When I arrived, the nurse had already cleaned the wound.","note":"''我到达''前已发生,过去的过去用过去完成时 had cleaned。"},{"wrong":"The wound was clean before she covered it.","correct":"The wound had been cleaned before she covered it.","note":"伤口被清洗(被动)且在更早,用过去完成被动 had been cleaned。"}]'::jsonb, '【急救步骤说明文结构】
开头 点题:Knowing how to treat a burn can make a big difference.
第一步 First, place the burn under cool running water… because…
中间 Next, dry the area… Then cover it loosely…
禁忌 Never put oil on a burn, as it keeps the heat in.
收尾 Finally, if the burn is serious, take the victim to hospital at once.', 2, 'elective2', 'U5');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE volume='elective2' AND unit='U5';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content) VALUES (11, 'elective2', 'U5', '{"title":"过去完成时及其被动语态(had done / had been done)速查","intro":"过去完成时表示「过去的过去」:在某个过去时间点之前已经完成或已持续的动作。构成 had + 过去分词(主动 had done;被动 had been done)。判断口诀:两个过去动作,先发生的那个用过去完成。","table":{"headers":["形式","用法 / 例句"],"rows":[["had done(主动)","过去某点前已完成:When the doctor arrived, the man had stopped breathing."],["had been done(被动)","主语承受动作:The wound had been cleaned before she bandaged it."],["对照一般过去","先发生→had done;后发生→did:By the time help came, he had given first aid."],["倒装强调","No sooner had…than… / Hardly had…when…:刚一……就……"]]},"specialRules":[{"rule":"两个过去动作,先发生的用过去完成,后发生的用一般过去","mark":"She had cleaned the wound before she covered it."},{"rule":"被动语态:had + been + 过去分词","mark":"The victim had already been taken to hospital."},{"rule":"常见时间标志:by + 过去时间 / by the time / before / after / already","mark":"By 2010, she had worked there for ten years."},{"rule":"No sooner / Hardly 置于句首要部分倒装","mark":"No sooner had he swallowed it than he began to choke."}],"why":["过去完成时是为了把两个过去动作分出先后:用 had done 把更早的动作''推''到更远的过去,听者一下就知道哪件事先发生。被动时主语不是动作的执行者,就把 had done 变成 had been done。"],"gaokaoPoints":["by the time / before / after 引导的句子里时态前后呼应(过去完成 vs 一般过去),语法填空与改错高频。","No sooner had…than… 和 Hardly had…when… 的倒装与连词搭配(than 配 No sooner,when 配 Hardly),不可混用。","被动判断:看主语是否承受动作,是则用 had been done。"],"examVsReal":[{"exam":"When I arrived, he had already left.（考试严格区分先后）","real":"When I arrived, he already left.（口语有时也用一般过去）","note":"考试看到''过去的过去''必须用过去完成;日常口语里如先后很清楚,母语者偶尔用一般过去"},{"exam":"No sooner had she sat down than the phone rang.（书面/考试倒装）","real":"She had just sat down when the phone rang.（口语更常这样说）","note":"倒装结构正式、考试爱考;口语里人们更爱用 just…when 表达同样意思"}]}'::jsonb);

COMMIT;

-- ===== 自带校验 =====
SELECT 'vocab' k, count(*) v, 50 expect FROM public.junior_vocab WHERE volume='elective2' AND unit='U5'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='elective2' AND unit='U5'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='elective2' AND unit='U5'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='elective2' AND unit='U5'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='elective2' AND unit='U5'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE volume='elective2' AND unit='U5' ORDER BY k;
SELECT 'grammar' rel, correct_answer ans, count(*) FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective2' AND unit='U5') GROUP BY 2 ORDER BY 2;
