-- ============================================================
-- 选择性必修一 U1(People of Achievement)灌库(junior_* 表,volume='elective1' unit='U1' grade=10)。幂等。
-- preflight(grade 7-12 + senior 分类)已随必修一跑过,不必再跑。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 48 =====
DELETE FROM public.junior_vocab WHERE volume='elective1' AND unit='U1';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'achievement', 'n.', '/əˈtʃiːvmənt/', '成就;成绩;达到', 'Winning the Nobel Prize was her greatest achievement.', '获得诺贝尔奖是她最伟大的成就。', 'People of Achievement', 1, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a great achievement', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'physiology', 'n.', '/ˌfɪziˈɒlədʒi/', '生理学;生理机能', 'She was awarded the Nobel Prize for Physiology or Medicine.', '她被授予诺贝尔生理学或医学奖。', 'People of Achievement', 2, 0, 'senior', 'wordlist', 'elective1', 'U1', 'the prize for physiology', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'crucial', 'adj.', '/ˈkruːʃl/', '至关重要的;关键性的', 'Her research played a crucial role in treating malaria.', '她的研究在治疗疟疾中起了至关重要的作用。', 'People of Achievement', 3, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a crucial role', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'malaria', 'n.', '/məˈleəriə/', '疟疾', 'Artemisinin has become a vital treatment for malaria.', '青蒿素已成为治疗疟疾的重要药物。', 'People of Achievement', 4, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a treatment for malaria', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'vital', 'adj.', '/ˈvaɪtl/', '必不可少的;极其重要的;充满生机的', 'Her work was a vital part of the fight against the disease.', '她的工作是抗击这种疾病的重要一环。', 'People of Achievement', 5, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a vital part', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'committed', 'adj.', '/kəˈmɪtɪd/', '尽心尽力的;坚定的;忠诚的', 'Tu Youyou was a committed and patient scientist.', '屠呦呦是一位尽心尽力且有耐心的科学家。', 'People of Achievement', 6, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a committed scientist', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'objective', 'n./adj.', '/əbˈdʒektɪv/', '目标;目的;客观的', 'The team was formed with the objective of finding a new medicine.', '这个团队的成立目标是找到一种新药。', 'People of Achievement', 7, 0, 'senior', 'wordlist', 'elective1', 'U1', 'with the objective of', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'botanical', 'adj.', '/bəˈtænɪkl/', '植物学的;植物的', 'She searched ancient texts for botanical treatments.', '她在古籍中寻找植物类疗法。', 'People of Achievement', 8, 0, 'senior', 'wordlist', 'elective1', 'U1', 'botanical treatments', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'evaluate', 'v.', '/ɪˈvæljueɪt/', '评价;评估', 'Her team had to evaluate thousands of plants for their medical value.', '她的团队不得不评估数千种植物的药用价值。', 'People of Achievement', 9, 0, 'senior', 'wordlist', 'elective1', 'U1', 'evaluate plants', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'distinct', 'adj.', '/dɪˈstɪŋkt/', '清晰的;有区别的;截然不同的', 'They tested 380 distinct ancient treatments.', '他们测试了380种各不相同的古代疗法。', 'People of Achievement', 10, 0, 'senior', 'wordlist', 'elective1', 'U1', 'distinct treatments', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'extract', 'n./v.', '/ˈekstrækt/', '提取物;摘录;提取;提炼', 'She used the extract from sweet wormwood to treat the disease.', '她用青蒿的提取物来治疗这种疾病。', 'People of Achievement', 11, 0, 'senior', 'wordlist', 'elective1', 'U1', 'the extract from wormwood', 'v. 重音在后 /ɪkˈstrækt/;美音 /ˈekstrækt/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'boil', 'v.', '/bɔɪl/', '(使)沸腾;煮开;烧开', 'At first the team tried to boil the wormwood leaves.', '起初团队尝试煮青蒿叶。', 'People of Achievement', 12, 0, 'senior', 'wordlist', 'elective1', 'U1', 'boil the leaves', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'liquid', 'n./adj.', '/ˈlɪkwɪd/', '液体;液体的;液态的', 'They used the liquid obtained from the plant to treat patients.', '他们用从植物中得到的液体来治疗病人。', 'People of Achievement', 13, 0, 'senior', 'wordlist', 'elective1', 'U1', 'the liquid obtained', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'obtain', 'v.', '/əbˈteɪn/', '(尤指经努力)获得;赢得', 'She finally obtained a substance that worked.', '她最终得到了一种有效的物质。', 'People of Achievement', 14, 0, 'senior', 'wordlist', 'elective1', 'U1', 'obtain the substance', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'substance', 'n.', '/ˈsʌbstəns/', '物质;物品;事实根据', 'At a lower temperature she found a substance that cured malaria.', '在较低温度下她发现了一种能治愈疟疾的物质。', 'People of Achievement', 15, 0, 'senior', 'wordlist', 'elective1', 'U1', 'an active substance', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'insist', 'v.', '/ɪnˈsɪst/', '坚持;坚决要求', 'The team insisted on testing the medicine on themselves.', '团队坚持在自己身上测试这种药。', 'People of Achievement', 16, 0, 'senior', 'wordlist', 'elective1', 'U1', 'insist on', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'defeat', 'v./n.', '/dɪˈfiːt/', '击败;战胜;失败;挫败', 'Tu Youyou would not acknowledge defeat after many failures.', '经历多次失败后,屠呦呦也不肯认输。', 'People of Achievement', 17, 0, 'senior', 'wordlist', 'elective1', 'U1', 'acknowledge defeat', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'property', 'n.', '/ˈprɒpəti/', '性质;特征;财产', 'Boiling apparently destroyed the medical properties of the plant.', '煮沸显然破坏了这种植物的药用性质。', 'People of Achievement', 18, 0, 'senior', 'wordlist', 'elective1', 'U1', 'medical properties', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'gradually', 'adv.', '/ˈɡrædʒuəli/', '逐渐地;逐步地', 'Einstein gradually became famous throughout the world.', '爱因斯坦逐渐闻名于世。', 'People of Achievement', 19, 0, 'senior', 'wordlist', 'elective1', 'U1', 'gradually become famous', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'genius', 'n.', '/ˈdʒiːniəs/', '天才;天资;天赋', 'Einstein was not only a genius but also a kind man.', '爱因斯坦不仅是个天才,也是个善良的人。', 'People of Achievement', 20, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a gentle genius', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'gentle', 'adj.', '/ˈdʒentl/', '温柔的;文静的;轻柔的', 'People remember him as a gentle and kind figure.', '人们记得他是个温柔善良的人。', 'People of Achievement', 21, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a gentle figure', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'numerous', 'adj.', '/ˈnjuːmərəs/', '众多的;许多的', 'He made numerous contributions to modern physics.', '他对现代物理学做出了许多贡献。', 'People of Achievement', 22, 0, 'senior', 'wordlist', 'elective1', 'U1', 'numerous contributions', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'theory', 'n.', '/ˈθɪəri/', '理论;学说', 'His general theory of relativity changed science forever.', '他的广义相对论永远改变了科学。', 'People of Achievement', 23, 0, 'senior', 'wordlist', 'elective1', 'U1', 'the theory of relativity', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'formula', 'n.', '/ˈfɔːmjələ/', '公式;方程式;配方', 'His famous formula E=mc2 is known around the world.', '他著名的公式 E=mc2 闻名世界。', 'People of Achievement', 24, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a famous formula', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'passion', 'n.', '/ˈpæʃn/', '酷爱;激情;热情', 'Out of a strong passion for knowledge, he kept studying.', '出于对知识的强烈热爱,他不断学习。', 'People of Achievement', 25, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a passion for knowledge', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'doctorate', 'n.', '/ˈdɒktərət/', '博士学位', 'He earned a doctorate in physics in 1905.', '他在1905年获得物理学博士学位。', 'People of Achievement', 26, 0, 'senior', 'wordlist', 'elective1', 'U1', 'earn a doctorate', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'extraordinary', 'adj.', '/ɪkˈstrɔːdnri/', '不一般的;非凡的;意想不到的', 'That year he published four extraordinary physics papers.', '那一年他发表了四篇非凡的物理学论文。', 'People of Achievement', 27, 0, 'senior', 'wordlist', 'elective1', 'U1', 'extraordinary papers', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'circumstance', 'n.', '/ˈsɜːkəmstəns/', '条件;环境;状况', 'Circumstances changed in 1933, when Hitler came to power.', '1933年希特勒上台,情况发生了变化。', 'People of Achievement', 28, 0, 'senior', 'wordlist', 'elective1', 'U1', 'circumstances changed', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'consequence', 'n.', '/ˈkɒnsɪkwəns/', '结果;后果', 'As a consequence, Einstein had to leave Germany.', '结果,爱因斯坦不得不离开德国。', 'People of Achievement', 29, 0, 'senior', 'wordlist', 'elective1', 'U1', 'as a consequence', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'flee', 'v.', '/fliː/', '迅速离开;逃跑', 'He had to flee Germany because he was Jewish.', '因为是犹太人,他不得不逃离德国。', 'People of Achievement', 30, 0, 'senior', 'wordlist', 'elective1', 'U1', 'flee a country', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'institution', 'n.', '/ˌɪnstɪˈtjuːʃn/', '社会公共机构;制度;习俗', 'He found the doors of academic institutions closed to him.', '他发现学术机构的大门对他关闭了。', 'People of Achievement', 31, 0, 'senior', 'wordlist', 'elective1', 'U1', 'academic institutions', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'remarkable', 'adj.', '/rɪˈmɑːkəbl/', '非凡的;显著的;不寻常的', 'His remarkable achievements made him a hero to many.', '他非凡的成就使他成为许多人心中的英雄。', 'People of Achievement', 32, 0, 'senior', 'wordlist', 'elective1', 'U1', 'remarkable achievements', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'encounter', 'v./n.', '/ɪnˈkaʊntə(r)/', '偶然碰到;遇到;邂逅;遭遇', 'Einstein often encountered people who asked for his help.', '爱因斯坦常常遇到向他求助的人。', 'People of Achievement', 33, 0, 'senior', 'wordlist', 'elective1', 'U1', 'encounter people', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'mourn', 'v.', '/mɔːn/', '哀悼;忧伤', 'The whole world mourned the loss of the great scientist.', '全世界都为这位伟大科学家的离世而哀悼。', 'People of Achievement', 34, 0, 'senior', 'wordlist', 'elective1', 'U1', 'mourn the loss', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'novelist', 'n.', '/ˈnɒvəlɪst/', '小说家', 'Lu Xun is regarded as one of China''s greatest novelists.', '鲁迅被视为中国最伟大的小说家之一。', 'People of Achievement', 35, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a great novelist', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'novel', 'n.', '/ˈnɒvl/', '(长篇)小说', 'He drew on his life to write this famous novel.', '他借鉴自己的人生写下了这部著名小说。', 'People of Achievement', 36, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a famous novel', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'found', 'v.', '/faʊnd/', '创建;建立;创办', 'Florence Nightingale founded modern nursing.', '弗洛伦斯·南丁格尔创立了现代护理学。', 'People of Achievement', 37, 0, 'senior', 'wordlist', 'elective1', 'U1', 'found modern nursing', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'professor', 'n.', '/prəˈfesə(r)/', '教授', 'People often mistook him for Professor Einstein.', '人们常把他误认作爱因斯坦教授。', 'People of Achievement', 38, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a famous professor', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'scientific', 'adj.', '/ˌsaɪənˈtɪfɪk/', '科学(上)的;关于科学的', 'It is an honour for China''s scientific research.', '这是中国科研的一种荣耀。', 'People of Achievement', 39, 0, 'senior', 'wordlist', 'elective1', 'U1', 'scientific research', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'conclusion', 'n.', '/kənˈkluːʒn/', '结论;推论', 'She came to the conclusion that boiling destroyed the medicine.', '她得出结论:煮沸破坏了药效。', 'People of Achievement', 40, 0, 'senior', 'wordlist', 'elective1', 'U1', 'come to a conclusion', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'infer', 'v.', '/ɪnˈfɜː(r)/', '推断;推定', 'From her words we can infer how hard the work was.', '从她的话中我们能推断出这项工作有多艰难。', 'People of Achievement', 41, 0, 'senior', 'wordlist', 'elective1', 'U1', 'infer the reason', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'draft', 'n./v.', '/drɑːft/', '草稿;草案;起草;草拟', 'He wrote a first draft of his speech about the great scientist.', '他写了一篇关于这位伟大科学家的演讲初稿。', 'People of Achievement', 42, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a first draft', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'device', 'n.', '/dɪˈvaɪs/', '方法;技巧;装置;仪器', 'The writer used a clever device to introduce the hero.', '作者用了一个巧妙的手法来引出这位英雄。', 'People of Achievement', 43, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a rhetorical device', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'patent', 'n./adj.', '/ˈpætnt/', '专利;专利证书;有专利的', 'Einstein once worked as a clerk in the patent office.', '爱因斯坦曾在专利局当职员。', 'People of Achievement', 44, 0, 'senior', 'wordlist', 'elective1', 'U1', 'the patent office', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'gain', 'v./n.', '/ɡeɪn/', '获得;赢得;增加', 'His fame was gained through years of hard work.', '他的名声是通过多年的辛勤工作赢得的。', 'People of Achievement', 45, 0, 'senior', 'wordlist', 'elective1', 'U1', 'gain fame', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'courage', 'n.', '/ˈkʌrɪdʒ/', '勇气;胆量', 'Great people often show courage when others give up.', '在别人放弃时,伟人往往展现出勇气。', 'People of Achievement', 46, 0, 'senior', 'wordlist', 'elective1', 'U1', 'show great courage', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'honour', 'n./v.', '/ˈɒnə(r)/', '荣誉;尊敬;给以荣誉', 'She said the honour was not just hers but the whole team''s.', '她说这份荣誉不只属于她,而是属于整个团队。', 'People of Achievement', 47, 0, 'senior', 'wordlist', 'elective1', 'U1', 'a great honour', '美式拼 honor;美音 /ˈɑːnər/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'contribution', 'n.', '/ˌkɒntrɪˈbjuːʃn/', '贡献;捐献', 'He made a great contribution to the fight against the disease.', '他为抗击这种疾病做出了巨大贡献。', 'People of Achievement', 48, 0, 'senior', 'wordlist', 'elective1', 'U1', 'make a contribution', NULL);

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1');
DELETE FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e1u1.01', '①who/whom(指人)、which(指物)引导非限制性定语从句', 'A2', 10, '选择性必修一 U1 — 逗号隔开的非限制性定语从句中,先行词指人作主语用 who、作宾语用 whom,先行词指物用 which;关系代词 that 不能用于非限制性定语从句(常作干扰项)。', 1, 'elective1', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e1u1.02', '②whose / where / when 引导非限制性定语从句', 'A2', 10, '选择性必修一 U1 — whose 表所属(指人或物),where 跟在地点先行词后作地点状语,when 跟在时间先行词后作时间状语;都用逗号隔开补充信息。', 2, 'elective1', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e1u1.03', '③介词+which/whom · which 指代整个主句', 'A2', 10, '选择性必修一 U1 — some of which / all of whom / most of whom / in which case 等‘量词/介词 + which/whom’结构;以及 which 指代前面整个主句(…, which surprised us all)。', 3, 'elective1', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Tu Youyou, ____ discovered artemisinin, won the Nobel Prize.', 'who', 'which', 'whose', 'that', 'A', '非限制性、先行词 Tu Youyou 指人作主语 → who(that 不能用于非限制性)。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'The book, ____ was published in 2015, tells Einstein''s life story.', 'who', 'which', 'where', 'that', 'B', '非限制性、先行词 book 指物作主语 → which。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Einstein, ____ was Jewish, had to flee Germany in 1933.', 'which', 'whom', 'who', 'that', 'C', '非限制性、先行词 Einstein 指人作主语 → who。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Artemisinin, ____ saved many lives, is now a standard treatment.', 'who', 'whom', 'that', 'which', 'D', '非限制性、先行词 artemisinin 指物作主语 → which。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Zhong Nanshan, ____ we all admire, managed the SARS outbreak.', 'whom', 'which', 'where', 'that', 'A', '非限制性、先行词 Zhong Nanshan 指人作 admire 的宾语 → whom。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Florence Nightingale, ____ founded modern nursing, is still respected today.', 'which', 'who', 'whose', 'that', 'B', '非限制性、先行词指人作主语 → who。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'The medicine, ____ was called artemisinin, soon cured many patients.', 'who', 'whom', 'which', 'that', 'C', '非限制性、先行词 medicine 指物作主语 → which。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Wu Mengchao, ____ performed operations into his 90s, was a great doctor.', 'which', 'where', 'that', 'who', 'D', '非限制性、先行词指人作主语 → who。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'The Nobel Prize, ____ she received in 2015, is a great honour.', 'which', 'who', 'whom', 'that', 'A', '非限制性、先行词 prize 指物作 received 的宾语 → which。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Alexander Fleming, ____ discovered penicillin, changed medicine forever.', 'which', 'who', 'whose', 'that', 'B', '非限制性、先行词指人作主语 → who。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Her team examined 2,000 old texts, ____ took them many years.', 'who', 'whom', 'which', 'that', 'C', '非限制性、指前述事情(examining texts)→ which。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Lu Xun, ____ many people regard as a great writer, was born in 1881.', 'which', 'where', 'that', 'whom', 'D', '非限制性、先行词指人作 regard 的宾语 → whom。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'The patients, most of them recovered, were grateful to her, ____ pleased the whole team.', 'which', 'who', 'whom', 'that', 'A', '非限制性、which 指代前面的整件事 → which。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Cao Xueqin, ____ wrote The Dream of the Red Mansions, suffered great poverty.', 'which', 'who', 'whose', 'that', 'B', '非限制性、先行词指人作主语 → who。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'The general theory of relativity, ____ Einstein created, is famous worldwide.', 'who', 'whom', 'which', 'that', 'C', '非限制性、先行词 theory 指物作 created 的宾语 → which。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Helen Keller, ____ teacher opened a new world to her, wrote her autobiography at 22.', 'who', 'which', 'that', 'whose', 'D', '非限制性、表所属(Keller 的老师)→ whose。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Mei Lanfang, ____ took Beijing Opera to the USA, became known worldwide.', 'who', 'which', 'whom', 'that', 'A', '非限制性、先行词指人作主语 → who。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'The four papers, ____ he published in 1905, made him world-famous.', 'who', 'which', 'whom', 'that', 'B', '非限制性、先行词 papers 指物作 published 的宾语 → which。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Tu''s colleagues, ____ she worked with for years, shared in the honour.', 'which', 'where', 'whom', 'that', 'C', '非限制性、先行词指人作 worked with 的宾语 → whom。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.01'), 'Sweet wormwood, ____ grows in many places, holds an important secret.', 'who', 'whom', 'that', 'which', 'D', '非限制性、先行词指物作主语 → which。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Tu Youyou went to Hainan, ____ malaria was more common, to study patients.', 'where', 'which', 'when', 'that', 'A', '非限制性、先行词 Hainan 是地点、从句完整 → where。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Einstein moved to Princeton, ____ he worked as a researcher for years.', 'which', 'where', 'when', 'that', 'B', '非限制性、先行词 Princeton 是地点 → where。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'It happened in 1933, ____ Hitler came to power in Germany.', 'which', 'where', 'when', 'that', 'C', '非限制性、先行词 1933 是时间、从句完整 → when。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Einstein, ____ hair often stood on end, looked a little odd to the public.', 'who', 'which', 'that', 'whose', 'D', '非限制性、表所属(爱因斯坦的头发)→ whose。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'She returned to Beijing in 1969, ____ she became the head of the project.', 'when', 'which', 'where', 'that', 'A', '非限制性、先行词 1969 是时间 → when。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'The team worked in Beijing, ____ they finally succeeded in 1971.', 'which', 'where', 'when', 'that', 'B', '非限制性、先行词 Beijing 是地点 → where。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Tu Youyou, ____ research led to artemisinin, was born in Ningbo.', 'who', 'which', 'whose', 'that', 'C', '非限制性、表所属(她的研究)→ whose。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Einstein studied in Switzerland, ____ he entered university in 1896.', 'which', 'when', 'that', 'where', 'D', '非限制性、先行词 Switzerland 是地点 → where。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'He won the prize in 1922, ____ his explanation of the photoelectric effect was honoured.', 'when', 'which', 'where', 'that', 'A', '非限制性、先行词 1922 是时间 → when。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Lu Xun went to Japan, ____ he first studied medicine.', 'which', 'where', 'when', 'that', 'B', '非限制性、先行词 Japan 是地点 → where。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Mei Lanfang, ____ skill was admired worldwide, helped spread Beijing Opera.', 'who', 'which', 'whose', 'that', 'C', '非限制性、表所属(梅兰芳的技艺)→ whose。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'She graduated in 1955, ____ she began to work at a medical academy.', 'which', 'where', 'that', 'when', 'D', '非限制性、先行词 1955 是时间 → when。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Einstein took a job at the patent office, ____ he kept studying physics.', 'where', 'which', 'when', 'that', 'A', '非限制性、先行词 office 是地点 → where。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Helen Keller, ____ early life was dark and silent, learned to communicate.', 'who', 'whose', 'which', 'that', 'B', '非限制性、表所属(凯勒的早年生活)→ whose。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'The story is set in Shaoxing, ____ Lu Xun was born in 1881.', 'which', 'when', 'where', 'that', 'C', '非限制性、先行词 Shaoxing 是地点 → where。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'He passed away in 1955, ____ the whole world mourned his loss.', 'which', 'where', 'that', 'when', 'D', '非限制性、先行词 1955 是时间 → when。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Steve Jobs, ____ products changed the world, was driven to succeed.', 'whose', 'who', 'which', 'that', 'A', '非限制性、表所属(乔布斯的产品)→ whose。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'She moved her work to a lab in Beijing, ____ the final tests were carried out.', 'which', 'where', 'when', 'that', 'B', '非限制性、先行词 lab 是地点 → where。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'It all began in 1967, ____ the government formed a team of scientists.', 'which', 'where', 'when', 'that', 'C', '非限制性、先行词 1967 是时间 → when。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.02'), 'Sun Yat-sen, ____ ideas brought people together, is called the founder of modern China.', 'who', 'which', 'that', 'whose', 'D', '非限制性、表所属(孙中山的思想)→ whose。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'She examined 280,000 plants, some of ____ showed promise against malaria.', 'which', 'whom', 'that', 'where', 'A', '‘some of + which’指物的非限制性 → which(介词/量词后不用 that)。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'The medicine was tested on patients, most of ____ recovered quickly.', 'which', 'whom', 'that', 'where', 'B', '先行词 patients 指人、‘most of + whom’ → whom。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'Einstein published four papers, all of ____ became famous in science.', 'whom', 'that', 'which', 'when', 'C', '先行词 papers 指物、‘all of + which’ → which。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'She failed more than 190 times, ____ would have stopped most people.', 'who', 'whom', 'that', 'which', 'D', 'which 指代前面整个主句(失败190多次这件事)→ which。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'He met many scientists, several of ____ later won the Nobel Prize.', 'whom', 'which', 'that', 'where', 'A', '先行词 scientists 指人、‘several of + whom’ → whom。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'The team tested 380 treatments, none of ____ fully cured the disease at first.', 'whom', 'which', 'that', 'when', 'B', '先行词 treatments 指物、‘none of + which’ → which。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'Tu Youyou shared the honour with her team, ____ moved the whole country.', 'who', 'whom', 'which', 'that', 'C', 'which 指代前面整个主句(她与团队分享荣誉)→ which。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'He had many friends, both of ____ remembered his kindness for years.', 'which', 'that', 'where', 'whom', 'D', '先行词 friends 指人、‘both of + whom’ → whom。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'She read hundreds of texts, in ____ she finally found the key sentence.', 'which', 'whom', 'that', 'when', 'A', '‘介词 in + which’指物 → which(介词后不用 that)。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'Einstein forgot his friends'' birthdays, ____ amused everyone around him.', 'who', 'which', 'whom', 'that', 'B', 'which 指代前面整个主句(他忘记生日这件事)→ which。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'The project had several stages, the last of ____ proved the hardest.', 'whom', 'that', 'which', 'where', 'C', '先行词 stages 指物、‘the last of + which’ → which。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'She thanked the researchers, many of ____ had worked with her for years.', 'which', 'that', 'when', 'whom', 'D', '先行词 researchers 指人、‘many of + whom’ → whom。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'He was awarded the Nobel Prize, ____ is one of the highest honours of all.', 'which', 'who', 'whom', 'that', 'A', '非限制性、先行词 Nobel Prize 指物作主语 → which(此处也可视为单一先行词)。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'She tried two methods, neither of ____ worked at the start.', 'whom', 'which', 'that', 'where', 'B', '先行词 methods 指物、‘neither of + which’ → which。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'He gave talks to many students, some of ____ became scientists themselves.', 'which', 'that', 'whom', 'when', 'C', '先行词 students 指人、‘some of + whom’ → whom。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'The medicine finally worked, ____ proved the value of traditional medicine.', 'who', 'whom', 'that', 'which', 'D', 'which 指代前面整个主句(药终于有效这件事)→ which。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'He wrote four papers, the most famous of ____ explained relativity.', 'which', 'whom', 'that', 'where', 'A', '先行词 papers 指物、‘the most famous of + which’ → which。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'She trained young doctors, all of ____ admired her greatly.', 'which', 'whom', 'that', 'when', 'B', '先行词 doctors 指人、‘all of + whom’ → whom。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'He had to flee his country, ____ saddened him deeply for the rest of his life.', 'who', 'whom', 'which', 'that', 'C', 'which 指代前面整个主句(他被迫逃离这件事)→ which。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1' AND code='e1u1.03'), 'Tu''s team studied 2,000 texts, from ____ they drew the crucial idea.', 'whom', 'that', 'where', 'which', 'D', '‘介词 from + which’指物 → which(介词后不用 that)。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE volume='elective1' AND unit='U1';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Tu Youyou and the Nobel Prize', 'In October 2015, the Nobel Prize for Physiology or Medicine was awarded to Tu Youyou, whose research led to the discovery of artemisinin. Artemisinin is a crucial new treatment for malaria, a disease that gives over two hundred million people a fever every year and kills hundreds of thousands of them. The medicine has saved many lives and is thought to save about a hundred thousand people in Africa alone each year. Tu Youyou was a committed and patient scientist who never gave up. When she heard the news of the prize, she did not take all the honour for herself. Instead, she said that the success belonged to her whole team and to the people of her country. She added that the discovery proved the great value of traditional Chinese medicine, and that it was an honour for China''s scientific research to be known around the world.', '新闻·屠呦呦获诺奖', 148, '[{"q":"What did Tu Youyou''s research lead to?","answer":"A","options":["A new medicine that treats malaria.","A new way to grow plants.","A new kind of fever.","A new prize for science."],"explanation":"原文 ''whose research led to the discovery of artemisinin… a crucial new treatment for malaria'' 的转述。"},{"q":"How did Tu Youyou react when she won the prize?","answer":"B","options":["She kept all the honour for herself.","She gave the credit to her team and country.","She refused to accept the prize.","She said it was just luck."],"explanation":"原文 ''the success belonged to her whole team and to the people of her country'' 的转述。"},{"q":"What did the discovery prove, according to Tu Youyou?","answer":"A","options":["That traditional Chinese medicine has great value.","That foreign medicine is useless.","That she worked alone.","That malaria can never be cured."],"explanation":"末句 ''proved the great value of traditional Chinese medicine'' 的转述。"}]'::jsonb, '[{"word":"artemisinin","cn":"青蒿素"},{"word":"malaria","cn":"疟疾"},{"word":"committed","cn":"尽心尽力的"}]'::jsonb, 2, 'elective1', 'U1');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'The Long Road to Artemisinin', 'Finding artemisinin was not easy. In 1969 Tu Youyou became the head of a project and decided to look for answers in ancient Chinese medical books. Her team read more than two thousand old texts and tested hundreds of plants for their medical value. One old text suggested using sweet wormwood to treat a fever, so they boiled the leaves and used the liquid on patients. To their disappointment, it did not work. Tu Youyou would not accept defeat. She studied the texts again, and by chance found a sentence that suggested a different way to treat the plant. She realised that boiling the wormwood at a high temperature had destroyed its useful properties. So she drew out the extract at a lower temperature, and at last found a substance that worked. After failing more than a hundred and ninety times, the team finally succeeded in 1971. They even tested the new medicine on themselves to make sure it was safe.', '记叙·青蒿素发现历程', 161, '[{"q":"Why did the team''s first attempt with wormwood fail?","answer":"B","options":["They used the wrong plant.","High heat had ruined the plant''s useful qualities.","They forgot to test it.","The patients refused the medicine."],"explanation":"原文 ''boiling the wormwood at a high temperature had destroyed its useful properties'' 的转述。"},{"q":"What change finally made the medicine work?","answer":"C","options":["Boiling it for much longer.","Using a completely different plant.","Taking out the extract with less heat.","Adding more leaves."],"explanation":"原文 ''drew out the extract at a lower temperature, and at last found a substance that worked'' 的转述。"},{"q":"What does the passage tell us about Tu Youyou''s character?","answer":"D","options":["She gave up after the first failure.","She cared only about fame.","She worked without any team.","She refused to give up and kept trying."],"explanation":"原文 ''would not accept defeat… failing more than a hundred and ninety times'' 的转述。"}]'::jsonb, '[{"word":"wormwood","cn":"青蒿;艾草"},{"word":"extract","cn":"提取物"},{"word":"substance","cn":"物质"}]'::jsonb, 2, 'elective1', 'U1');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Einstein, the Gentle Genius', 'Albert Einstein is often called one of the smartest people who ever lived. He gave the world the general theory of relativity and the famous formula E=mc2. Yet he was not only a genius; he was also a kind and gentle man loved by many. Born in Germany in 1879, he failed part of a university entrance exam as a teenager, even though his scores in maths and physics were excellent. After more study, he passed and later earned a doctorate in physics. In 1905 he published four amazing papers, and the world soon saw him as a new Isaac Newton. To ordinary people, he looked a little odd, with thick hair that often stood on end. He sometimes forgot small things, such as his friends'' birthdays. He once helped a little girl with her homework when she knocked on his door. Despite his strange habits, he was warmly loved by his friends and neighbours.', '人物·爱因斯坦', 155, '[{"q":"What is Einstein best known for in science?","answer":"A","options":["His theory of relativity and famous formula.","His work as a teacher of maths.","His paintings and music.","His skill at sports."],"explanation":"原文 ''the general theory of relativity and the famous formula E=mc2'' 的转述。"},{"q":"What happened when Einstein first took the university exam?","answer":"B","options":["He passed it easily.","He failed part of it despite strong science scores.","He refused to take it.","He came first in every subject."],"explanation":"原文 ''failed part of a university entrance exam… even though his scores in maths and physics were excellent'' 的转述。"},{"q":"How did people who knew Einstein feel about him?","answer":"C","options":["They were afraid of him.","They thought he was unfriendly.","They loved him despite his odd habits.","They never spoke to him."],"explanation":"末句 ''Despite his strange habits, he was warmly loved by his friends and neighbours'' 的转述。"}]'::jsonb, '[{"word":"relativity","cn":"相对论"},{"word":"genius","cn":"天才"},{"word":"doctorate","cn":"博士学位"}]'::jsonb, 2, 'elective1', 'U1');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Florence Nightingale, the Lady with the Lamp', 'Florence Nightingale is remembered as the woman who founded modern nursing. She was born into a rich family, and at that time most people thought nursing was not a proper job for a lady. But Florence felt a strong wish to help the sick, and she decided to train as a nurse against her family''s wishes. During a war, she went to care for wounded soldiers in dirty and crowded hospitals. She cleaned the wards, brought in fresh air, and made sure the men had good food and warm beds. Far fewer soldiers died once she had improved these conditions. At night she walked among the beds with a small lamp in her hand, checking on the men, so the soldiers began to call her ''the Lady with the Lamp''. After the war, she opened a school to train nurses, and her ideas changed the way hospitals were run all over the world.', '人物·南丁格尔', 153, '[{"q":"Why was Florence Nightingale''s choice unusual for her time?","answer":"D","options":["She was too poor to study.","Women were not allowed to read.","There were no hospitals at all.","Nursing was not seen as a suitable job for a lady."],"explanation":"原文 ''most people thought nursing was not a proper job for a lady'' 的转述。"},{"q":"What was the result of the changes she made in the hospitals?","answer":"A","options":["Many fewer soldiers lost their lives.","More soldiers became ill.","The hospitals were closed.","The soldiers were sent home."],"explanation":"原文 ''Far fewer soldiers died once she had improved these conditions'' 的转述。"},{"q":"What did Florence do after the war?","answer":"B","options":["She stopped working in medicine.","She set up a place where young nurses could be trained.","She joined the army.","She moved to another country to rest."],"explanation":"原文 ''she opened a school to train nurses'' 的转述。"}]'::jsonb, '[{"word":"found","cn":"创立"},{"word":"nursing","cn":"护理"},{"word":"ward","cn":"病房"}]'::jsonb, 2, 'elective1', 'U1');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Zhong Nanshan and the Fight Against Disease', 'Zhong Nanshan is a doctor whom many Chinese people deeply respect. He became famous during the SARS outbreak, when a strange and dangerous illness was spreading fast. While many people were frightened, Zhong Nanshan stayed calm and told the public the truth about the disease. He insisted that doctors should treat the most serious patients in his own hospital, even though this put him in danger. His honesty and courage helped the country get the outbreak under control. Years later, when another illness appeared, the same trusted doctor stepped forward again, although he was already in his eighties. He travelled to where the disease was worst and gave clear advice that helped to keep people safe. To many, he is a model of what a great person should be: brave in the face of danger, honest with the public, and always ready to put others before himself.', '人物·钟南山', 147, '[{"q":"How did Zhong Nanshan behave during the SARS outbreak?","answer":"C","options":["He hid from the public.","He left the country.","He stayed calm and told people the truth.","He refused to treat any patients."],"explanation":"原文 ''stayed calm and told the public the truth about the disease'' 的转述。"},{"q":"What did he do when another illness appeared years later?","answer":"D","options":["He decided he was too old to help.","He told others to handle it alone.","He stopped being a doctor.","He stepped forward again despite his age."],"explanation":"原文 ''the same trusted doctor stepped forward again, although he was already in his eighties'' 的转述。"},{"q":"Why do many people see him as a great person?","answer":"A","options":["Because he is brave, honest and puts others first.","Because he became very rich.","Because he avoided all danger.","Because he never worked hard."],"explanation":"末句 ''brave in the face of danger, honest with the public, and always ready to put others before himself'' 的转述。"}]'::jsonb, '[{"word":"outbreak","cn":"(疾病)爆发"},{"word":"insist","cn":"坚持"},{"word":"courage","cn":"勇气"}]'::jsonb, 2, 'elective1', 'U1');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'What Does Greatness Really Mean?', 'When we hear the word ''great'', we often think of famous scientists, writers or leaders. But what does greatness really mean? Some people believe that being great is about winning prizes or becoming rich and well known. Others say that true greatness has little to do with fame. Einstein once said that we should try to become not a person of success, but rather a person of value. In other words, what matters most is not how much you gain for yourself, but how much good you do for others. A great person does not need to change the whole world. A teacher who gives up free time to help a struggling student, a doctor who stays calm in danger, or a parent who works hard for a family can all be great in their own quiet way. Greatness, then, is less about being noticed and more about caring, courage and never giving up.', '议论·伟大的意义', 154, '[{"q":"What do some people wrongly think greatness means, according to the text?","answer":"B","options":["Helping others quietly.","Winning prizes and becoming rich and famous.","Working hard for a family.","Showing courage in danger."],"explanation":"原文 ''being great is about winning prizes or becoming rich and well known'' 的转述(作者否定的观点)。"},{"q":"What did Einstein advise people to become?","answer":"C","options":["The richest person in the world.","A person who avoids all hard work.","A person of value rather than just success.","Someone who is always noticed."],"explanation":"原文 ''become not a person of success, but rather a person of value'' 的转述。"},{"q":"What is the writer''s main point about greatness?","answer":"D","options":["Only famous people can be great.","Greatness always means changing the world.","Greatness depends only on money.","Greatness is about caring, courage and not giving up."],"explanation":"末句 ''less about being noticed and more about caring, courage and never giving up'' 的转述。"}]'::jsonb, '[{"word":"greatness","cn":"伟大"},{"word":"value","cn":"价值"},{"word":"struggle","cn":"挣扎;艰难地做"}]'::jsonb, 2, 'elective1', 'U1');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE volume='elective1' AND unit='U1';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U1', 'A Discovery for the World', 'When Tu Youyou won the Nobel Prize, she did not (1)____ all the honour for herself. She said that the discovery of artemisinin was a team (2)____, and that the success belonged to her country too. For many years her team had (3)____ thousands of plants, looking for one that could fight malaria. At first, nothing seemed to (4)____, and the project nearly came to a stop. But Tu Youyou refused to (5)____ defeat. She read the ancient texts again and finally found the (6)____ to the problem. By drawing out the (7)____ at a lower temperature, she got a substance that really (8)____. After more than a hundred and ninety (9)____, the team at last succeeded. Their hard work has since (10)____ countless lives around the world.', 128, 2, '[{"q":"1","answer":"A","options":["take","lose","drop","throw"],"explanation":"take the honour 把荣誉据为己有。"},{"q":"2","answer":"B","options":["price","effort","noise","season"],"explanation":"a team effort 团队的努力。"},{"q":"3","answer":"C","options":["sold","eaten","tested","lost"],"explanation":"tested thousands of plants 测试植物。"},{"q":"4","answer":"D","options":["sleep","sell","cry","work"],"explanation":"nothing seemed to work 似乎都不起作用。"},{"q":"5","answer":"A","options":["accept","enjoy","buy","open"],"explanation":"accept defeat 认输。"},{"q":"6","answer":"B","options":["noise","answer","price","weather"],"explanation":"the answer to the problem 问题的答案。"},{"q":"7","answer":"C","options":["garden","machine","extract","market"],"explanation":"draw out the extract 提取提取物。"},{"q":"8","answer":"D","options":["failed","stopped","ended","worked"],"explanation":"a substance that worked 有效的物质。"},{"q":"9","answer":"A","options":["failures","holidays","songs","prices"],"explanation":"190 failures 失败。"},{"q":"10","answer":"B","options":["wasted","saved","sold","lost"],"explanation":"saved countless lives 拯救生命。"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U1', 'Einstein Leaves Germany', 'By the early 1930s, Albert Einstein was already (1)____ all over the world. But in 1933 his (2)____ suddenly changed, because Hitler had come to power. Einstein, who was Jewish, (3)____ the doors of universities closed to him. As a (4)____, he had to flee his home country. After (5)____ some time in Europe, he finally took up a (6)____ as a researcher in the United States. There he (7)____ to make great discoveries in physics. People in his new town soon (8)____ to love the kind and funny scientist with the wild white hair. Although he was a (9)____, he often forgot small things, like his friends'' birthdays. Yet everyone who knew him (10)____ his warm heart.', 118, 2, '[{"q":"1","answer":"C","options":["hungry","quiet","famous","empty"],"explanation":"famous all over the world 闻名世界。"},{"q":"2","answer":"D","options":["price","noise","weather","circumstances"],"explanation":"circumstances changed 情况改变。"},{"q":"3","answer":"A","options":["found","sold","ate","lost"],"explanation":"found the doors closed 发现门关上了。"},{"q":"4","answer":"B","options":["holiday","consequence","game","shop"],"explanation":"as a consequence 结果。"},{"q":"5","answer":"C","options":["selling","losing","spending","eating"],"explanation":"spending some time 度过一些时间。"},{"q":"6","answer":"D","options":["price","noise","garden","position"],"explanation":"take up a position 担任职位。"},{"q":"7","answer":"A","options":["continued","stopped","failed","refused"],"explanation":"continued to make discoveries 继续做出发现。"},{"q":"8","answer":"B","options":["stopped","began","failed","refused"],"explanation":"began to love 开始喜爱。"},{"q":"9","answer":"C","options":["price","noise","genius","market"],"explanation":"although he was a genius 虽然是天才。"},{"q":"10","answer":"D","options":["hid","sold","lost","remembered"],"explanation":"remembered his warm heart 记得他温暖的心。"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U1', 'The Lady with the Lamp', 'Florence Nightingale grew up in a rich family, but she felt a strong (1)____ to help sick people. At that time, nursing was not (2)____ a good job for a lady, yet she (3)____ on training as a nurse. During a war she went to (4)____ for wounded soldiers in dirty hospitals. She cleaned the rooms, let in fresh (5)____, and made sure the men had warm beds. Soon far (6)____ soldiers died than before. At night she walked among the beds with a small (7)____ in her hand, so the men began to call her ''the Lady with the Lamp''. After the war she (8)____ a school to train nurses, and her ideas (9)____ hospitals all over the world. Today she is still (10)____ as the founder of modern nursing.', 131, 2, '[{"q":"1","answer":"A","options":["wish","price","noise","machine"],"explanation":"a strong wish to help 强烈的愿望。"},{"q":"2","answer":"B","options":["sold","seen as","lost","eaten"],"explanation":"seen as a good job 被视为好工作。"},{"q":"3","answer":"C","options":["sold","lost","insisted","ate"],"explanation":"insisted on training 坚持受训。"},{"q":"4","answer":"D","options":["sell","sleep","shout","care"],"explanation":"care for soldiers 照料士兵。"},{"q":"5","answer":"A","options":["air","price","noise","garden"],"explanation":"fresh air 新鲜空气。"},{"q":"6","answer":"B","options":["sold","fewer","lost","ate"],"explanation":"far fewer soldiers died 死的士兵少得多。"},{"q":"7","answer":"C","options":["price","noise","lamp","market"],"explanation":"a small lamp 一盏小灯。"},{"q":"8","answer":"D","options":["sold","lost","ate","founded"],"explanation":"founded a school 创办学校。"},{"q":"9","answer":"A","options":["changed","sold","lost","ate"],"explanation":"changed hospitals 改变了医院。"},{"q":"10","answer":"B","options":["sold","remembered","lost","eaten"],"explanation":"remembered as the founder 被铭记为创立者。"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U1', 'A Doctor''s Courage', 'Zhong Nanshan is a doctor (1)____ many people in China trust deeply. He became well known during a dangerous (2)____, when a strange illness was spreading quickly. While others were (3)____, he stayed calm and told the public the (4)____ about the disease. He even (5)____ that the most serious patients be sent to his own hospital, although this put him in (6)____. His honesty and courage helped to (7)____ the outbreak. Years later, when another illness (8)____, the same trusted doctor stepped forward again, even though he was already in his (9)____. To many people, he is a fine (10)____ of what a great person should be.', 108, 2, '[{"q":"1","answer":"C","options":["which","where","whom","when"],"explanation":"the doctor whom people trust 指人作宾语。"},{"q":"2","answer":"D","options":["holiday","game","garden","outbreak"],"explanation":"a dangerous outbreak 危险的爆发。"},{"q":"3","answer":"A","options":["frightened","sold","happy","rich"],"explanation":"others were frightened 别人害怕。"},{"q":"4","answer":"B","options":["price","truth","noise","market"],"explanation":"the truth about the disease 关于疾病的真相。"},{"q":"5","answer":"C","options":["sold","lost","insisted","ate"],"explanation":"insisted that… 坚持要求。"},{"q":"6","answer":"D","options":["price","garden","song","danger"],"explanation":"put him in danger 使他处于危险。"},{"q":"7","answer":"A","options":["control","sell","sleep","shout"],"explanation":"control the outbreak 控制爆发。"},{"q":"8","answer":"B","options":["sold","appeared","lost","ate"],"explanation":"another illness appeared 又一种疾病出现。"},{"q":"9","answer":"C","options":["price","garden","eighties","market"],"explanation":"in his eighties 八十多岁。"},{"q":"10","answer":"D","options":["price","noise","machine","example"],"explanation":"a fine example 一个好榜样。"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U1', 'Lu Xun Changes His Path', 'Lu Xun, who is (1)____ as one of China''s greatest writers, was born in 1881. As a young man he went to Japan to study (2)____, hoping to save people''s lives. One day he saw a (3)____ that changed his mind. In it, a group of Chinese men did not seem to (4)____ about the suffering of their own people. From this, Lu Xun (5)____ that the real problem in China was not in people''s bodies but in their (6)____. So he decided to (7)____ medical school and become a writer instead. He believed that powerful (8)____ could wake people up. His first famous short (9)____, A Madman''s Diary, soon got published. Through his pen, he tried to make his country (10)____ and stronger.', 124, 2, '[{"q":"1","answer":"A","options":["regarded","sold","lost","eaten"],"explanation":"regarded as one of the greatest 被视为最伟大之一。"},{"q":"2","answer":"B","options":["price","medicine","noise","garden"],"explanation":"study medicine 学医。"},{"q":"3","answer":"C","options":["sold","lost","photo","ate"],"explanation":"saw a photo 看到一张照片。"},{"q":"4","answer":"D","options":["sell","sleep","shout","care"],"explanation":"care about the suffering 关心苦难。"},{"q":"5","answer":"A","options":["concluded","sold","lost","ate"],"explanation":"concluded that… 得出结论。"},{"q":"6","answer":"B","options":["price","minds","garden","market"],"explanation":"in their minds 在他们心里/精神上。"},{"q":"7","answer":"C","options":["sell","sleep","quit","shout"],"explanation":"quit medical school 退出医学院。"},{"q":"8","answer":"D","options":["sold","lost","ate","writing"],"explanation":"powerful writing 有力的文字。"},{"q":"9","answer":"A","options":["story","sold","lost","ate"],"explanation":"a short story 短篇小说。"},{"q":"10","answer":"B","options":["sold","better","lost","eaten"],"explanation":"make his country better 使国家更好。"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U1', 'What Makes a Person Great', 'What does it really (1)____ to be a great person? Many of us think first of famous (2)____, writers or leaders. But true greatness may have little to do with (3)____. Einstein once said we should try to become a person of (4)____ rather than just a person of success. In other (5)____, what matters is not how much you gain, but how much (6)____ you do for others. A great person does not need to (7)____ the whole world. A teacher who gives up free time to help a (8)____ student can be great in a quiet way. So can a parent who (9)____ hard for a family. Greatness, in the end, is more about caring, courage and never (10)____ up.', 122, 2, '[{"q":"1","answer":"C","options":["sell","sleep","mean","shout"],"explanation":"what does it mean 意味着什么。"},{"q":"2","answer":"D","options":["prices","noises","gardens","scientists"],"explanation":"famous scientists 著名科学家。"},{"q":"3","answer":"A","options":["fame","sold","lost","ate"],"explanation":"little to do with fame 与名声无关。"},{"q":"4","answer":"B","options":["price","value","noise","market"],"explanation":"a person of value 有价值的人。"},{"q":"5","answer":"C","options":["sold","lost","words","ate"],"explanation":"in other words 换句话说。"},{"q":"6","answer":"D","options":["price","garden","market","good"],"explanation":"how much good you do 做多少好事。"},{"q":"7","answer":"A","options":["change","sell","sleep","shout"],"explanation":"change the whole world 改变世界。"},{"q":"8","answer":"B","options":["sold","struggling","lost","ate"],"explanation":"a struggling student 学习吃力的学生。"},{"q":"9","answer":"C","options":["sold","lost","works","ate"],"explanation":"works hard 努力工作。"},{"q":"10","answer":"D","options":["sold","lost","eaten","giving"],"explanation":"never giving up 永不放弃。"}]'::jsonb, 6);

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE volume='elective1' AND unit='U1';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U1 听力·对话 Who Do You Admire?', '选择性必修一 U1 · dialogue', 3, 'Lily: Tom, our teacher asked us to talk about a person we admire. Who will you choose?
Tom: I''d like to talk about Tu Youyou. She discovered a new medicine for malaria.
Lily: Oh, the scientist who won the Nobel Prize? Why do you admire her?
Tom: Because she never gave up. Her team failed many times before they succeeded.
Lily: That''s true. I think I''ll choose Florence Nightingale.
Tom: The nurse? Why her?
Lily: She cared for wounded soldiers and founded modern nursing. She was very brave.
Tom: Great choice. Both of them helped a lot of people.', '老师让谈一位敬佩的人。Tom 选屠呦呦,因为她发现治疟疾的新药、屡败屡战从不放弃;Lily 选南丁格尔,因为她照料伤兵、创立现代护理、很勇敢。两人都帮助了许多人。', 'uk_female', '[{"q":"Who does Tom choose to talk about?","type":"choice","answer":"A","options":["Tu Youyou.","Florence Nightingale.","Einstein.","Lu Xun."]},{"q":"Why does Tom admire her?","type":"choice","answer":"B","options":["She was very rich.","She never gave up after failing.","She was famous in films.","She lived very long."]},{"q":"Who does Lily choose?","type":"choice","answer":"A","options":["Florence Nightingale.","Tu Youyou.","Zhong Nanshan.","Einstein."]},{"q":"What did Lily''s person do?","type":"choice","answer":"B","options":["She discovered a new medicine.","She cared for soldiers and founded nursing.","She wrote famous novels.","She built bridges."]},{"q":"What do Tom and Lily agree about the two people?","type":"choice","answer":"C","options":["Both were scientists.","Both lived in England.","Both helped many people.","Both won the Nobel Prize."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U1');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U1 听力·短文 The Meaning of Greatness', '选择性必修一 U1 · passage', 2, 'When we hear the word great, we often think of famous people.
But Einstein once said we should become a person of value, not just a person of success.
This means that helping others matters more than fame or money.
A kind teacher or a brave doctor can be great in a quiet way.
Greatness, then, is really about caring and never giving up.', '听到''伟大''我们常想到名人;但爱因斯坦说要做有价值的人,而非只追求成功;这意味着帮助别人比名利更重要;善良的老师、勇敢的医生也能以平凡的方式伟大;伟大其实关乎关爱和永不放弃。', 'uk_female', '[{"q":"What do people often think of when they hear ''great''?","type":"choice","answer":"D","options":["Money only.","Animals.","Cars.","Famous people."]},{"q":"What did Einstein say we should become?","type":"choice","answer":"A","options":["A person of value, not just success.","The richest person.","A famous actor.","A quiet person."]},{"q":"What matters more than fame or money?","type":"choice","answer":"B","options":["Winning prizes.","Helping others.","Travelling far.","Being noticed."]},{"q":"Who can be great in a quiet way?","type":"choice","answer":"C","options":["Only scientists.","Only leaders.","A kind teacher or a brave doctor.","Only writers."]},{"q":"What is greatness really about?","type":"choice","answer":"D","options":["Being rich.","Being on television.","Living a long life.","Caring and never giving up."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U1');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U1 听力·对话 An Interview About the Discovery', '选择性必修一 U1 · dialogue', 3, 'Host: Professor, can you tell us how the new medicine for malaria was found?
Guest: Of course. The team read more than two thousand old Chinese medical texts.
Host: Two thousand? That sounds like a huge amount of work.
Guest: It was. They also tested hundreds of plants, but at first nothing worked.
Host: So what was the key to success?
Guest: They drew out the extract at a lower temperature, and then it finally worked.
Host: Amazing. How many times did they fail before that?
Guest: More than a hundred and ninety times. They never gave up.', '主持人请教授讲新疟疾药如何被发现。团队读了两千多部中医古籍、测试数百种植物,起初都无效;关键是在较低温度提取提取物才成功;在此之前失败了190多次,但从不放弃。', 'uk_female', '[{"q":"How many old texts did the team read?","type":"choice","answer":"A","options":["More than two thousand.","Only ten.","About fifty.","None at all."]},{"q":"What happened when they first tested the plants?","type":"choice","answer":"B","options":["Everything worked at once.","Nothing worked at first.","They stopped the project.","They lost the texts."]},{"q":"What was the key to success?","type":"choice","answer":"C","options":["Reading more books.","Boiling at high heat.","Drawing out the extract at a lower temperature.","Using more plants."]},{"q":"How many times did they fail?","type":"choice","answer":"D","options":["Twice.","Ten times.","Fifty times.","More than 190 times."]},{"q":"What does the guest say about the team''s spirit?","type":"choice","answer":"A","options":["They never gave up.","They gave up quickly.","They worked alone.","They were not patient."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U1');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U1 听力·短文 A Trusted Doctor', '选择性必修一 U1 · passage', 2, 'Zhong Nanshan is a doctor whom many Chinese people deeply trust.
During a dangerous outbreak, he stayed calm and told the public the truth.
He insisted on treating the most serious patients himself.
Years later, even in his eighties, he stepped forward to help again.
His courage and honesty make him a model of a great person.', '钟南山是许多中国人深深信任的医生;危险爆发期间他保持冷静、说出真相;坚持亲自救治最重的病人;多年后年逾八旬仍挺身相助;他的勇气与诚实使他成为伟人的典范。', 'uk_female', '[{"q":"How do many people in China feel about Zhong Nanshan?","type":"choice","answer":"B","options":["They are afraid of him.","They deeply trust him.","They have never heard of him.","They dislike him."]},{"q":"What did he do during the dangerous outbreak?","type":"choice","answer":"C","options":["He hid at home.","He left the country.","He stayed calm and told the truth.","He stopped working."]},{"q":"Which patients did he insist on treating?","type":"choice","answer":"D","options":["The easiest ones.","Only children.","None at all.","The most serious ones."]},{"q":"What did he do years later in his eighties?","type":"choice","answer":"A","options":["He stepped forward to help again.","He retired completely.","He refused to help.","He moved abroad."]},{"q":"What makes him a model of a great person?","type":"choice","answer":"B","options":["His wealth.","His courage and honesty.","His fame on TV.","His long holidays."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U1');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U1 听力·对话 How to Write About a Hero', '选择性必修一 U1 · dialogue', 3, 'Anna: I have to write an introduction about someone I admire, but I don''t know how to start.
Ben: First, choose a person and say why he or she is great.
Anna: Okay. Then what should I write about?
Ben: Tell an impressive story from the person''s life. Stories make readers care.
Anna: Should I describe what the person looks like too?
Ben: Yes, a little. Describe the appearance and the personality.
Anna: And how should I end it?
Ben: Sum up how you feel about the person. That makes a strong ending.', 'Anna 要写敬佩之人的介绍却不知如何开头。Ben 建议:先选人并说明为何伟大;再讲一个动人的生平故事;适当描写外貌和性格;最后总结自己对此人的感受作为有力结尾。', 'uk_female', '[{"q":"What is Anna''s problem?","type":"choice","answer":"C","options":["She has no paper.","She can''t read.","She doesn''t know how to start writing.","She lost her pen."]},{"q":"What does Ben say to do first?","type":"choice","answer":"D","options":["Draw a picture.","Copy a book.","Write the ending.","Choose a person and say why they are great."]},{"q":"Why does Ben suggest telling a story?","type":"choice","answer":"A","options":["Because stories make readers care.","To make it longer.","To use big words.","To fill the page."]},{"q":"What does Ben say about describing the person?","type":"choice","answer":"B","options":["Never describe them.","Describe the appearance and personality.","Only describe their clothes.","Describe only the face."]},{"q":"How should Anna end the introduction?","type":"choice","answer":"C","options":["By stopping suddenly.","By asking a question.","By summing up how she feels.","By repeating the title."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U1');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U1 听力·短文 A Famous Saying', '选择性必修一 U1 · passage', 2, 'Here is a famous saying from Albert Einstein.
He said we should try not to become a person of success, but a person of value.
In other words, do not work only for fame or money.
Instead, do something good and useful for other people.
If we live this way, our lives will truly have meaning.', '这是爱因斯坦的一句名言:不要只想成为成功的人,而要做有价值的人;换句话说,别只为名利而努力;要为他人做一些有益的事;若这样生活,我们的人生才真正有意义。', 'uk_female', '[{"q":"Whose saying is this?","type":"choice","answer":"D","options":["Tu Youyou''s.","Lu Xun''s.","Florence Nightingale''s.","Albert Einstein''s."]},{"q":"What kind of person should we try to become?","type":"choice","answer":"A","options":["A person of value.","The richest person.","A famous singer.","A quiet person."]},{"q":"What should we NOT work only for?","type":"choice","answer":"B","options":["Friends.","Fame or money.","Health.","Family."]},{"q":"What should we do instead?","type":"choice","answer":"C","options":["Rest all day.","Travel far.","Do something good for others.","Buy more things."]},{"q":"What will happen if we live this way?","type":"choice","answer":"D","options":["We will become poor.","We will be forgotten.","Nothing will change.","Our lives will truly have meaning."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U1');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE volume='elective1' AND unit='U1';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit) VALUES (10, 'Introduce a Person of Achievement(介绍一位你敬佩的杰出人物)', 'A Person I Admire', '请用英语写一篇约100词的短文,介绍一位你敬佩的杰出人物(可以是科学家、医生等名人,也可以是身边的普通人)。内容包括:① 此人是谁、为何敬佩;② 描写其外貌或性格;③ 讲一个能体现其伟大的小故事/事迹;④ 总结你对此人的感受。注意适当使用非限制性定语从句。', 'Write a short introduction (about 100 words) about a person of achievement you admire. The person can be a famous scientist or doctor, or an ordinary person around you. Include: 1) who the person is and why you admire him/her; 2) a description of the person''s appearance or personality; 3) an impressive story or deed that shows the person''s greatness; 4) how you feel about this person. Try to use non-restrictive relative clauses.', '["点明人物及敬佩原因(The person I admire most is …, who …)","描写外貌/性格(a kind and patient person / brave and honest)","讲一个体现伟大的故事/事迹(For example, …)","总结你的感受(To me, … is truly great because …)"]'::jsonb, 70, 100, 'The person I admire most is Tu Youyou, who discovered a new medicine for malaria. She is a committed and patient scientist, and she never gives up easily. For example, her team read more than two thousand old medical texts and failed over a hundred and ninety times before they finally succeeded. When she won the Nobel Prize, which is one of the highest honours in the world, she gave the credit to her whole team and her country. To me, Tu Youyou is truly great, not because she is famous, but because she works hard and cares about other people. She has taught me to be brave and never to give up.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["The person I admire most is Tu Youyou, who discovered a new medicine for malaria.","She is a committed and patient scientist who never gives up.","When she won the Nobel Prize, which is one of the highest honours in the world, she gave the credit to her team.","To me, she is truly great, not because she is famous, but because she cares about other people."]'::jsonb, '[{"wrong":"Tu Youyou, that discovered the medicine, won the prize.","correct":"Tu Youyou, who discovered the medicine, won the prize.","note":"非限制性定语从句指人用 who,不能用 that。"},{"wrong":"She is a scientist, which never gives up.","correct":"She is a scientist who never gives up.","note":"先行词指人用 who,不能用 which。"},{"wrong":"She make great contributions to her country.","correct":"She makes great contributions to her country.","note":"主语第三人称单数,动词加 s。"}]'::jsonb, '【人物介绍结构】
第1句 点明人物及敬佩原因:The person I admire most is …, who …
第2句 外貌/性格:He/She is a … person.
第3-4句 事迹(用非限制性从句):For example, … , which …
第5句 感受:To me, … is truly great because …', 2, 'elective1', 'U1');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE volume='elective1' AND unit='U1';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content) VALUES (10, 'elective1', 'U1', '{"title":"非限制性定语从句·who / which / whose / where / when 速查","intro":"非限制性定语从句用逗号和主句隔开,只对先行词补充说明,去掉后主句仍成立。判断口诀:指人 who/whom、指物 which、表所属 whose、地点 where、时间 when;非限制性里 that 永远不能用。","table":{"headers":["关系词","用法 / 例句"],"rows":[["who","指人作主语:Tu Youyou, who discovered artemisinin, won the prize."],["whom","指人作宾语:Zhong Nanshan, whom we all admire, is brave."],["which","指物作主/宾,或指代整个主句:The book, which came out in 2015, …;She failed 190 times, which surprised us all."],["whose","表所属(人或物):Einstein, whose hair stood on end, looked odd."],["where / when","地点 / 时间:Hainan, where malaria was common, …;1933, when Hitler came to power, …"],["介词+which/whom","some of which / most of whom / in which case"]]},"specialRules":[{"rule":"非限制性定语从句里绝对不能用 that(最常见干扰项)","mark":", who √ / , that ×"},{"rule":"which 可指代前面整个主句,意为‘这件事’","mark":"She failed many times, which surprised us."},{"rule":"‘量词/介词 + which/whom’:指物用 which、指人用 whom","mark":"some of which / most of whom"},{"rule":"whose = ‘…的’,后接名词,指人指物都行","mark":"the scientist whose research led to…"}],"why":["非限制性从句给的是‘补充信息’,语气上像插一句话,所以前后用逗号;正因为它独立、可去掉,英语习惯不用 that,而用 who/which/whose/where/when。"],"gaokaoPoints":["语法填空高频:看先行词指人/指物 + 从句缺什么成分,选 who/whom/which/whose/where/when。","易错点:非限制性里误用 that;指人误用 which;which 指代整句时别误判为指某个名词。","‘介词/量词 + which/whom’结构(some of which / all of whom)是中高考常考点。"],"examVsReal":[{"exam":"Tu Youyou, who discovered artemisinin, won the prize.（考试/书面)","real":"Tu Youyou discovered artemisinin, and she won the prize.","note":"考试爱用非限制性从句;口语里常拆成两个简单句、用 and 连接"},{"exam":"She failed many times, which surprised us all.（考试)","real":"She failed many times — and that surprised us all.","note":"考试用 which 指代整句;口语常用 and that 或破折号"}]}'::jsonb);

COMMIT;

-- ===== 自带校验 =====
SELECT 'vocab' k, count(*) v, 48 expect FROM public.junior_vocab WHERE volume='elective1' AND unit='U1'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='elective1' AND unit='U1'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='elective1' AND unit='U1'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='elective1' AND unit='U1'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='elective1' AND unit='U1'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE volume='elective1' AND unit='U1' ORDER BY k;
SELECT 'grammar' rel, correct_answer ans, count(*) FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U1') GROUP BY 2 ORDER BY 2;
