-- ============================================================
-- 选择性必修一 U5(Working the Land)灌库(junior_* 表,volume='elective1' unit='U5' grade=10)。幂等。
-- preflight(grade 7-12 + senior 分类)已随必修一跑过,不必再跑。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 46 =====
DELETE FROM public.junior_vocab WHERE volume='elective1' AND unit='U5';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'hybrid', 'n.', '/ˈhaɪbrɪd/', '杂交植(动)物;杂种;混合动力车', 'Yuan Longping developed a new kind of hybrid rice.', '袁隆平培育出了一种新型杂交水稻。', 'Working the Land', 1, 0, 'senior', 'wordlist', 'elective1', 'U5', 'hybrid rice', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'yield', 'n./v.', '/jiːld/', '产量;产出;出产(作物);屈服', 'The new strain of rice gives a much higher yield.', '这种新品种水稻的产量高得多。', 'Working the Land', 2, 0, 'senior', 'wordlist', 'elective1', 'U5', 'a high yield', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'grain', 'n.', '/ɡreɪn/', '谷物;谷粒;颗粒', 'Every grain of rice is the result of hard work.', '每一粒米都是辛勤劳动的成果。', 'Working the Land', 3, 0, 'senior', 'wordlist', 'elective1', 'U5', 'a grain of rice', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'soil', 'n.', '/sɔɪl/', '泥土;土壤;国土;领土', 'Healthy crops need rich and clean soil.', '健康的庄稼需要肥沃而洁净的土壤。', 'Working the Land', 4, 0, 'senior', 'wordlist', 'elective1', 'U5', 'rich soil', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'crop', 'n.', '/krɒp/', '庄稼;作物;收成', 'Farmers grow different crops in the same field each year.', '农民每年在同一块地里种不同的作物。', 'Working the Land', 5, 0, 'senior', 'wordlist', 'elective1', 'U5', 'grow crops', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'output', 'n.', '/ˈaʊtpʊt/', '产量;输出;输出量', 'Hybrid rice has helped farmers expand their output greatly.', '杂交水稻帮助农民大大提高了产量。', 'Working the Land', 6, 0, 'senior', 'wordlist', 'elective1', 'U5', 'expand output', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'boost', 'v./n.', '/buːst/', '使增长;使兴旺;增长;激励', 'Farmers needed to boost yields in the fields they already had.', '农民需要在现有的田地里提高产量。', 'Working the Land', 7, 0, 'senior', 'wordlist', 'elective1', 'U5', 'boost yields', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'expand', 'v.', '/ɪkˈspænd/', '扩大;增加;扩展;发展', 'This hybrid enabled farmers to expand their output.', '这种杂交品种使农民得以扩大产量。', 'Working the Land', 8, 0, 'senior', 'wordlist', 'elective1', 'U5', 'expand the output', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'tackle', 'v.', '/ˈtækl/', '解决(难题);应付(局面);处理', 'He chose to study agriculture to tackle the food crisis.', '他选择学习农业,以解决粮食危机。', 'Working the Land', 9, 0, 'senior', 'wordlist', 'elective1', 'U5', 'tackle the crisis', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'crisis', 'n.', '/ˈkraɪsɪs/', '危机;危急关头', 'A serious food crisis worried farmers across the country.', '一场严重的粮食危机让全国的农民忧心忡忡。', 'Working the Land', 10, 0, 'senior', 'wordlist', 'elective1', 'U5', 'a food crisis', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'shortage', 'n.', '/ˈʃɔːtɪdʒ/', '不足;缺少;短缺', 'Many farmers once faced a serious shortage of food.', '许多农民曾面临严重的食物短缺。', 'Working the Land', 11, 0, 'senior', 'wordlist', 'elective1', 'U5', 'a food shortage', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'overcome', 'v.', '/ˌəʊvəˈkʌm/', '克服;解决;战胜', 'Through intense effort he overcame many technical difficulties.', '通过艰苦努力,他克服了许多技术难题。', 'Working the Land', 12, 0, 'senior', 'wordlist', 'elective1', 'U5', 'overcome difficulties', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'intense', 'adj.', '/ɪnˈtens/', '强烈的;激烈的;热切的', 'Only through intense effort did he succeed at last.', '只有通过强烈的努力,他最终才成功。', 'Working the Land', 13, 0, 'senior', 'wordlist', 'elective1', 'U5', 'intense effort', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'devote', 'v.', '/dɪˈvəʊt/', '把……献(给);把……专用于;专心于', 'He devoted his whole life to the farmers of China.', '他把自己的一生都献给了中国的农民。', 'Working the Land', 14, 0, 'senior', 'wordlist', 'elective1', 'U5', 'devote one''s life to', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'convince', 'v.', '/kənˈvɪns/', '使相信;使确信;说服', 'Yuan was convinced that the answer lay in hybrid rice.', '袁隆平确信答案就在杂交水稻之中。', 'Working the Land', 15, 0, 'senior', 'wordlist', 'elective1', 'U5', 'be convinced that', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'estimate', 'v./n.', '/ˈestɪmeɪt/', '估计;估算;估价', 'It is estimated that most of the rice grown comes from his strains.', '据估计,所种植的大部分水稻都来自他的品种。', 'Working the Land', 16, 0, 'senior', 'wordlist', 'elective1', 'U5', 'it is estimated that', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'generate', 'v.', '/ˈdʒenəreɪt/', '产生;引起;发(电)', 'His hybrid strains help to generate much more food.', '他的杂交品种有助于产出更多的粮食。', 'Working the Land', 17, 0, 'senior', 'wordlist', 'elective1', 'U5', 'generate more food', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'domestic', 'adj.', '/dəˈmestɪk/', '本国的;国内的;家用的;家庭的', 'Much of China''s domestic rice comes from hybrid strains.', '中国国内的许多大米来自杂交品种。', 'Working the Land', 18, 0, 'senior', 'wordlist', 'elective1', 'U5', 'domestic consumption', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'consumption', 'n.', '/kənˈsʌmpʃn/', '消耗;消耗量;消费', 'Rice consumption is very high in many Asian countries.', '在许多亚洲国家,大米消费量非常高。', 'Working the Land', 19, 0, 'senior', 'wordlist', 'elective1', 'U5', 'rice consumption', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'conventional', 'adj.', '/kənˈvenʃənl/', '传统的;习惯的;常规的', 'Hybrids usually attain a higher yield than conventional crops.', '杂交品种的产量通常比常规作物更高。', 'Working the Land', 20, 0, 'senior', 'wordlist', 'elective1', 'U5', 'conventional crops', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'characteristic', 'n./adj.', '/ˌkærəktəˈrɪstɪk/', '特征;特点;品质;典型的', 'One characteristic of hybrids is their higher yield.', '杂交品种的一个特点是产量更高。', 'Working the Land', 21, 0, 'senior', 'wordlist', 'elective1', 'U5', 'a key characteristic', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'pollinate', 'v.', '/ˈpɒləneɪt/', '授粉;传粉', 'Rice is a self-pollinating plant, which made his work harder.', '水稻是自花授粉植物,这让他的工作更难。', 'Working the Land', 22, 0, 'senior', 'wordlist', 'elective1', 'U5', 'self-pollinating plants', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'root', 'n.', '/ruːt/', '根;根茎;根部;根源', 'Many vegetables put down deep roots into the soil.', '许多蔬菜会把根深深扎进土壤。', 'Working the Land', 23, 0, 'senior', 'wordlist', 'elective1', 'U5', 'deep roots', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'wheat', 'n.', '/wiːt/', '小麦;小麦籽', 'One year a farmer may grow wheat, and beans the next.', '农民可能一年种小麦,第二年种豆子。', 'Working the Land', 24, 0, 'senior', 'wordlist', 'elective1', 'U5', 'grow wheat', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'organic', 'adj.', '/ɔːˈɡænɪk/', '有机的;不使用化肥的;有机物的', 'Organic farming is simply farming without using any chemicals.', '有机农业就是不使用任何化学品的耕作方式。', 'Working the Land', 25, 0, 'senior', 'wordlist', 'elective1', 'U5', 'organic farming', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'chemical', 'n./adj.', '/ˈkemɪkl/', '化学制品;化学品;化学的', 'These chemicals can stay in the soil for a long time.', '这些化学品会在土壤中残留很长时间。', 'Working the Land', 26, 0, 'senior', 'wordlist', 'elective1', 'U5', 'chemical fertilisers', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'pesticide', 'n.', '/ˈpestɪsaɪd/', '杀虫剂;除害药物', 'Some pesticides can harm both the land and people''s health.', '有些杀虫剂会损害土地和人们的健康。', 'Working the Land', 27, 0, 'senior', 'wordlist', 'elective1', 'U5', 'chemical pesticides', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'fertiliser', 'n.', '/ˈfɜːtəlaɪzə(r)/', '肥料', 'Organic farmers use animal waste as natural fertiliser.', '有机农民用动物粪便作天然肥料。', 'Working the Land', 28, 0, 'senior', 'wordlist', 'elective1', 'U5', 'natural fertiliser', '美式拼 fertilizer');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'nutrition', 'n.', '/njuˈtrɪʃn/', '营养;滋养', 'Crops grown too fast are often poor in nutrition.', '长得太快的作物往往营养不足。', 'Working the Land', 29, 0, 'senior', 'wordlist', 'elective1', 'U5', 'rich in nutrition', '美音 /nuˈtrɪʃn/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'nutritious', 'adj.', '/njuˈtrɪʃəs/', '有营养的;营养丰富的', 'Many people prefer fresh and nutritious food.', '许多人喜欢新鲜而有营养的食物。', 'Working the Land', 30, 0, 'senior', 'wordlist', 'elective1', 'U5', 'nutritious food', '美音 /nuˈtrɪʃəs/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'mineral', 'n.', '/ˈmɪnərəl/', '矿物;矿物质', 'Organic methods keep the soil rich in minerals.', '有机方法使土壤富含矿物质。', 'Working the Land', 31, 0, 'senior', 'wordlist', 'elective1', 'U5', 'essential minerals', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'essential', 'adj.', '/ɪˈsenʃl/', '完全必要的;极其重要的', 'Clean water and rich soil are essential to farming.', '洁净的水和肥沃的土壤对耕作极其重要。', 'Working the Land', 32, 0, 'senior', 'wordlist', 'elective1', 'U5', 'essential minerals', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'flavour', 'n.', '/ˈfleɪvə(r)/', '味道;特点;特色', 'Crops grown with chemicals often have less flavour.', '用化肥种出的作物往往味道更淡。', 'Working the Land', 33, 0, 'senior', 'wordlist', 'elective1', 'U5', 'have less flavour', '美式拼 flavor');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'salty', 'adj.', '/ˈsɔːlti/', '含盐的;咸的', 'Seawater rice can grow even on salty land.', '海水稻甚至能在含盐的土地上生长。', 'Working the Land', 34, 0, 'senior', 'wordlist', 'elective1', 'U5', 'salty land', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'digest', 'v.', '/daɪˈdʒest/', '消化;领会;领悟', 'Chemicals can stay in the crops that animals and people digest.', '化学品会残留在动物和人类消化的作物里。', 'Working the Land', 35, 0, 'senior', 'wordlist', 'elective1', 'U5', 'digest the food', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'poverty', 'n.', '/ˈpɒvəti/', '贫穷;贫困', 'More food can help millions of people escape poverty.', '更多的粮食能帮助数百万人摆脱贫困。', 'Working the Land', 36, 0, 'senior', 'wordlist', 'elective1', 'U5', 'fight poverty', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'reality', 'n.', '/riˈæləti/', '现实;实际情况;事实', 'His dream of seawater rice finally became a reality.', '他的海水稻梦想终于变成了现实。', 'Working the Land', 37, 0, 'senior', 'wordlist', 'elective1', 'U5', 'become a reality', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'vision', 'n.', '/ˈvɪʒn/', '想象;视野;远见;影像', 'Even in his later years he was still full of vision.', '即使在晚年,他仍然充满远见。', 'Working the Land', 38, 0, 'senior', 'wordlist', 'elective1', 'U5', 'full of vision', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'envision', 'v.', '/ɪnˈvɪʒn/', '展望;想象', 'Long ago he envisioned rice plants as tall as sorghum.', '很久以前他就想象稻株能长得像高粱一样高。', 'Working the Land', 39, 0, 'senior', 'wordlist', 'elective1', 'U5', 'envision a future', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'leisure', 'n.', '/ˈleʒə(r)/', '闲暇;休闲;空闲', 'He could have retired to a life of leisure, but he did not.', '他本可以退休去过悠闲的生活,但他没有。', 'Working the Land', 40, 0, 'senior', 'wordlist', 'elective1', 'U5', 'a life of leisure', '美音 /ˈliːʒər/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'urban', 'adj.', '/ˈɜːbən/', '城市的;都市的;城镇的', 'An old shelter in London was turned into an urban farm.', '伦敦一处旧防空洞被改造成了城市农场。', 'Working the Land', 41, 0, 'senior', 'wordlist', 'elective1', 'U5', 'an urban farm', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'widespread', 'adj.', '/ˈwaɪdspred/', '分布广的;普遍的;广泛的', 'Chemical pesticides have been in widespread use since the 1950s.', '自20世纪50年代以来,化学杀虫剂已被广泛使用。', 'Working the Land', 42, 0, 'senior', 'wordlist', 'elective1', 'U5', 'in widespread use', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'depth', 'n.', '/depθ/', '深(度);向下(或向里)的距离', 'Diverse crops use different depths of the soil.', '多样的作物会利用不同深度的土壤。', 'Working the Land', 43, 0, 'senior', 'wordlist', 'elective1', 'U5', 'different depths', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'strain', 'n.', '/streɪn/', '(动、植物的)系;品种;拉伤;压力', 'His hybrid strains feed people both at home and abroad.', '他的杂交品种养活了国内外的人们。', 'Working the Land', 44, 0, 'senior', 'wordlist', 'elective1', 'U5', 'hybrid strains', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'entirely', 'adv.', '/ɪnˈtaɪəli/', '完全地;全部地;完整地', 'Few people want to stop using chemicals entirely.', '很少有人想完全停止使用化学品。', 'Working the Land', 45, 0, 'senior', 'wordlist', 'elective1', 'U5', 'stop entirely', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'instance', 'n.', '/ˈɪnstəns/', '例子;实例;事例', 'For instance, peanuts grow on the ground''s surface.', '例如,花生长在地面上。', 'Working the Land', 46, 0, 'senior', 'wordlist', 'elective1', 'U5', 'for instance', NULL);

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5');
DELETE FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e1u5.01', '①动名词作主语,谓语用单数', 'A2', 10, '选择性必修一 U5 — 句首主语位用动名词(-ing),把动作''名词化'';作主语时视为单数,谓语用 is/was/feeds/widens 等单数形式。to do 可作主语但更正式且常用 it 形式;does/done 不能作主语。', 1, 'elective1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e1u5.02', '②it 作形式主语 + 动名词(常见固定句式)', 'A2', 10, '选择性必修一 U5 — it 作形式主语、动名词作真正主语后置:It is no use/no good doing…;There is no point (in) doing…;It is a waste of time doing… 等;此处只能用动名词。', 2, 'elective1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('e1u5.03', '③动名词复合结构作主语 / 动名词主语 vs 不定式主语', 'A2', 10, '选择性必修一 U5 — 动名词前可带逻辑主语(名词所有格/Tom''s/his)构成复合结构作主语;并对照''动名词主语(已发生·一般)vs 不定式主语(具体·将来)''的选用。', 3, 'elective1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ rice feeds millions of people around the world."', 'Growing', 'To grow', 'Grows', 'Grown', 'A', '句首主语位、动作名词化作主语 → 动名词 Growing;does/done 不能作主语,to grow 在此不如动名词自然。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ the land was something Yuan Longping did all his life."', 'Work', 'Working', 'Worked', 'To working', 'B', '主语位用动名词 Working;''to working'' 不成形式。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ yields in existing fields was the real solution."', 'Boost', 'Boosts', 'Boosting', 'Boosted', 'C', '动名词 Boosting 作主语,谓语用单数 was。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ hybrid rice took years of intense effort."', 'Develop', 'Develops', 'Developed', 'Developing', 'D', '主语位动作名词化 → 动名词 Developing;谓语 took 用单数。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ enough food for everyone is a huge challenge."', 'Producing', 'Produce', 'Produces', 'Produced', 'A', '动名词 Producing 作主语,谓语用单数 is。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ chemical pesticides can harm the soil and our health."', 'Use', 'Using', 'Uses', 'Used', 'B', '主语位用动名词 Using;does/done 类形式不能作主语。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ crops every year keeps the soil rich in minerals."', 'Change', 'Changes', 'Changing', 'Changed', 'C', '动名词 Changing 作主语,谓语用单数 keeps。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ animal waste as fertiliser makes the soil healthier."', 'Use', 'Uses', 'Used', 'Using', 'D', '主语位 → 动名词 Using;谓语 makes 单数。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ rice as tall as sorghum was once only a dream."', 'Imagining', 'Imagine', 'Imagines', 'Imagined', 'A', '动名词 Imagining 作主语,谓语用单数 was。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ the soil clean and rich is the goal of organic farming."', 'Keep', 'Keeping', 'Keeps', 'Kept', 'B', '主语位 → 动名词 Keeping;谓语 is 单数。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ a higher yield was what every farmer hoped for."', 'Attain', 'Attains', 'Attaining', 'Attained', 'C', '动名词 Attaining 作主语,谓语 was 单数。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ world hunger requires both science and hard work."', 'Tackle', 'Tackles', 'Tackled', 'Tackling', 'D', '主语位 → 动名词 Tackling;谓语 requires 单数。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ in the fields gave Yuan a deep love for the land."', 'Farming', 'Farm', 'Farms', 'Farmed', 'A', '动名词 Farming 作主语,谓语用单数 gave。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ different crops helps put minerals back into the ground."', 'Plant', 'Planting', 'Plants', 'Planted', 'B', '主语位 → 动名词 Planting;谓语 helps 单数。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ research has helped feed not just China but many other countries."', 'Conduct', 'Conducts', 'Conducting', 'Conducted', 'C', '动名词 Conducting 作主语,谓语 has helped。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ healthy food while protecting the land is far from easy."', 'Grow', 'Grows', 'Grown', 'Growing', 'D', '主语位 → 动名词 Growing;谓语 is 单数。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ poverty in the countryside was always close to his heart."', 'Fighting', 'Fight', 'Fights', 'Fought', 'A', '动名词 Fighting 作主语,谓语 was 单数。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ rich soil is more important than using strong chemicals."', 'Build', 'Building', 'Builds', 'Built', 'B', '主语位 → 动名词 Building;谓语 is 单数。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ from the land taught him more than any book could."', 'Learn', 'Learns', 'Learning', 'Learned', 'C', '动名词 Learning 作主语,谓语 taught 单数。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.01'), '"____ on salty land was made possible by seawater rice."', 'Farm', 'Farms', 'Farmed', 'Farming', 'D', '主语位 → 动名词 Farming;谓语 was 单数。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no use ____ over a poor harvest; just try again next year."', 'crying', 'to cry', 'cries', 'cried', 'A', 'It is no use doing 固定句式,真正主语用动名词 crying。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no good ____ about the weather; farmers must adapt."', 'to complain', 'complaining', 'complains', 'complained', 'B', 'It is no good doing 固定句式,用动名词 complaining。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"There is no point ____ chemicals if they ruin the soil."', 'to use', 'uses', 'using', 'used', 'C', 'There is no point (in) doing,用动名词 using。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is a waste of time ____ crops that no one will buy."', 'grow', 'grows', 'grown', 'growing', 'D', 'It is a waste of time doing,用动名词 growing。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no use ____ that the food problem will solve itself."', 'hoping', 'to hope', 'hopes', 'hoped', 'A', 'It is no use doing,用动名词 hoping。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no good ____ the same field every year without a break."', 'to farm', 'farming', 'farms', 'farmed', 'B', 'It is no good doing,用动名词 farming。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"There is no point ____ a hybrid that cannot survive in the fields."', 'to create', 'creates', 'creating', 'created', 'C', 'There is no point (in) doing,用动名词 creating。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is a waste of time ____ for larger fields instead of better seeds."', 'wish', 'wishes', 'wished', 'wishing', 'D', 'It is a waste of time doing,用动名词 wishing。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no use ____ the truth that the soil is becoming poorer."', 'hiding', 'to hide', 'hides', 'hid', 'A', 'It is no use doing,用动名词 hiding。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no good ____ pesticides everywhere without thinking of the cost."', 'to spread', 'spreading', 'spreads', 'spread', 'B', 'It is no good doing,用动名词 spreading。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"There is no point ____ that organic food costs more without a reason."', 'to argue', 'argues', 'arguing', 'argued', 'C', 'There is no point (in) doing,用动名词 arguing。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is a waste of time ____ about hunger but doing nothing at all."', 'talk', 'talks', 'talked', 'talking', 'D', 'It is a waste of time doing,用动名词 talking。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no use ____ that one good harvest will feed a nation forever."', 'thinking', 'to think', 'thinks', 'thought', 'A', 'It is no use doing,用动名词 thinking。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no good ____ to retire when the work is only half done."', 'to rush', 'rushing', 'rushes', 'rushed', 'B', 'It is no good doing,用动名词 rushing。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"There is no point ____ the same crop until the land is worn out."', 'to repeat', 'repeats', 'repeating', 'repeated', 'C', 'There is no point (in) doing,用动名词 repeating。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is a waste of time ____ for an easy answer to world hunger."', 'search', 'searches', 'searched', 'searching', 'D', 'It is a waste of time doing,用动名词 searching。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no use ____ the harvest if the seeds were poor to begin with."', 'blaming', 'to blame', 'blames', 'blamed', 'A', 'It is no use doing,用动名词 blaming。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is no good ____ the danger of using too many chemicals."', 'to ignore', 'ignoring', 'ignores', 'ignored', 'B', 'It is no good doing,用动名词 ignoring。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"There is no point ____ a field that gets no water and no care."', 'to keep', 'keeps', 'keeping', 'kept', 'C', 'There is no point (in) doing,用动名词 keeping。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.02'), '"It is a waste of time ____ harmful insects with the wrong methods."', 'fight', 'fights', 'fought', 'fighting', 'D', 'It is a waste of time doing,用动名词 fighting。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"Yuan''s ____ the first hybrid rice changed farming in China forever."', 'developing', 'to develop', 'develops', 'develop', 'A', '名词所有格 Yuan''s + 动名词 developing 构成复合结构作主语。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"His ____ his life to the farmers won the respect of millions."', 'to devote', 'devoting', 'devotes', 'devoted', 'B', 'his + 动名词 devoting 构成复合结构作主语。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"Tom''s ____ to organic methods surprised his whole village."', 'to switch', 'switches', 'switching', 'switched', 'C', 'Tom''s + 动名词 switching 构成复合结构作主语。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"The scientist''s ____ seawater rice gave hope to many regions."', 'create', 'creates', 'to create', 'creating', 'D', '所有格 + 动名词 creating 构成复合结构作主语。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"Grandpa''s ____ chemical fertilisers is the reason he farms organically."', 'avoiding', 'to avoid', 'avoids', 'avoid', 'A', 'Grandpa''s + 动名词 avoiding 构成复合结构作主语。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"The farmers'' ____ new strains led to far better harvests."', 'to plant', 'planting', 'plants', 'planted', 'B', '所有格 + 动名词 planting 构成复合结构作主语。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"Her ____ the soil every season keeps the land healthy."', 'to test', 'tests', 'testing', 'tested', 'C', 'her + 动名词 testing 构成复合结构作主语。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"My uncle''s ____ to the countryside let him grow his own food."', 'move', 'moves', 'to move', 'moving', 'D', '所有格 + 动名词 moving 构成复合结构作主语。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"____ rice every day reminds us how precious each grain is. (强调一般、已成习惯的事)"', 'Eating', 'To eat', 'Eats', 'Eaten', 'A', '表示一般性、习惯性的事实作主语,用动名词 Eating(而非具体一次的不定式)。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"____ enough food for a growing world is the dream of every farmer. (泛指一般情况)"', 'To grow only', 'Growing', 'Grows', 'Grown', 'B', '泛指一般情况作主语,用动名词 Growing。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"____ the soil with care brings a better harvest in the long run. (强调长期的、习惯性做法)"', 'Treat', 'Treats', 'Treating', 'Treated', 'C', '强调长期、习惯性做法作主语,用动名词 Treating。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"____ from spilt milk helps no one; farmers look to the next season. (谚语:固定用动名词)"', 'Cry', 'Cries', 'Cried', 'Crying', 'D', '谚语 Crying over spilt milk;动名词作主语。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"His ____ never to give up inspired a new generation of scientists."', 'choosing', 'to choose', 'chooses', 'choose', 'A', 'his + 动名词 choosing 构成复合结构作主语。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"The village''s ____ to natural fertiliser slowly made its fields richer."', 'to turn', 'turning', 'turns', 'turned', 'B', '所有格 + 动名词 turning 构成复合结构作主语。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"____ different crops in turn protects the land year after year. (强调反复、一般的做法)"', 'Grow', 'Grows', 'Growing', 'Grown', 'C', '强调反复、一般做法作主语,用动名词 Growing。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"Mary''s ____ organic vegetables made her shop popular in town."', 'sell', 'sells', 'to sell', 'selling', 'D', 'Mary''s + 动名词 selling 构成复合结构作主语。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"____ the land was, for Yuan, the same as serving the people. (泛指一般性的事)"', 'Serving', 'To serve', 'Serves', 'Served', 'A', '泛指一般性的事作主语,用动名词 Serving。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"The team''s ____ the experiment in the south saved another year of work."', 'to run', 'running', 'runs', 'ran', 'B', '所有格 + 动名词 running 构成复合结构作主语。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"____ good seeds matters more than owning larger fields. (泛指一般情况)"', 'Choose', 'Chooses', 'Choosing', 'Chosen', 'C', '泛指一般情况作主语,用动名词 Choosing;谓语 matters 单数。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5' AND code='e1u5.03'), '"Their ____ the soil free of chemicals kept their crops safe to eat."', 'keep', 'keeps', 'to keep', 'keeping', 'D', 'their + 动名词 keeping 构成复合结构作主语。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE volume='elective1' AND unit='U5';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'A Farmer at Heart', 'Yuan Longping, known as the father of hybrid rice, was one of China''s most famous scientists. Yet he always considered himself a farmer, because he worked the land every day in his research. His parents had wanted him to study science or medicine, but what worried him most was that farmers often had poor harvests and a serious shortage of food. To deal with this problem, he chose to study agriculture instead. After he became wealthy, he could have retired to a comfortable, easy life. He did not. Deep down, he was still a man of the soil who cared little for fame or money. Instead, he made large donations to support more farming research. Even in his later years, he was young at heart and full of vision, and everyone was always excited to hear what he would dream up next. His simple wish was to keep all people away from hunger.', '人物·袁隆平的农民之心', 153, '[{"q":"Why did Yuan Longping think of himself as a farmer?","answer":"A","options":["Because he worked on the land throughout his research.","Because his parents owned a large farm.","Because he disliked all kinds of science.","Because he had never been to school."],"explanation":"原文 ''he worked the land every day in his research'' 的转述。"},{"q":"What made Yuan choose to study agriculture?","answer":"B","options":["His wish to become rich and famous.","His worry about farmers'' poor harvests and food shortage.","His love of medicine and chemistry.","His parents'' firm orders."],"explanation":"原文 ''what worried him most was that farmers often had poor harvests…'' 的转述。"},{"q":"What did Yuan do after he became wealthy?","answer":"A","options":["He gave money to support farming research.","He stopped all his work at once.","He moved away from China.","He bought a huge, comfortable house."],"explanation":"原文 ''made large donations to support more farming research'' 的转述。"}]'::jsonb, '[{"word":"hybrid","cn":"杂交的;杂交品种"},{"word":"shortage","cn":"短缺"},{"word":"leisure","cn":"闲暇"}]'::jsonb, 2, 'elective1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'The Science of Hybrid Rice', 'After graduating in the 1950s, Yuan Longping worked as a researcher. He soon realised that larger fields were not the answer to hunger. Instead, farmers needed to boost yields in the fields they already had. But how could this be done? Yuan was convinced that the answer lay in hybrid rice. A hybrid is a cross between two or more varieties of a species. One key characteristic of hybrids is that they usually give a higher yield than conventional crops. However, rice is a self-pollinating plant, so many scientists believed a hybrid of rice simply could not be made. Through years of intense effort, Yuan overcame these enormous technical difficulties. In the 1970s he developed the first hybrid rice that could be used in real farming. This breakthrough enabled farmers to expand their output greatly, and it would later help to feed not just China but many other countries that depend on rice.', '科学·杂交水稻的原理', 153, '[{"q":"What did Yuan realise about ending hunger?","answer":"B","options":["That bigger fields were the simplest answer.","That raising the yield mattered more than field size.","That farmers should grow fewer crops.","That hybrid rice could never be useful."],"explanation":"原文 ''larger fields were not the answer… needed to boost yields'' 的转述。"},{"q":"Why did many scientists doubt a rice hybrid was possible?","answer":"C","options":["Because rice has no varieties at all.","Because rice grows only in salty land.","Because rice pollinates itself naturally.","Because rice gives a very low price."],"explanation":"原文 ''rice is a self-pollinating plant, so many scientists believed a hybrid… could not be made'' 的转述。"},{"q":"What did Yuan''s first usable hybrid rice allow farmers to do?","answer":"D","options":["Stop growing rice completely.","Sell their fields for more money.","Move to other countries to farm.","Greatly increase how much they produced."],"explanation":"原文 ''enabled farmers to expand their output greatly'' 的转述。"}]'::jsonb, '[{"word":"yield","cn":"产量"},{"word":"conventional","cn":"常规的"},{"word":"pollinate","cn":"授粉"}]'::jsonb, 2, 'elective1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Dreams as Big as a Broom', 'What impressed people most about Yuan Longping was his lifelong ability to turn dreams into reality. Long ago, he envisioned rice plants as tall as sorghum, with each ear as big as a broom and each grain as huge as a peanut. To many, this sounded like a fairy tale, yet he kept working until he produced rice that could feed more people both at home and abroad. His later vision was even bolder. He dreamed of growing rice on salty land, where ordinary crops cannot survive. After much research, his idea of seawater rice also became a reality. It potentially opened up nearly one million square kilometres of salty land in China for rice production. This meant that fields once thought to be useless might one day help feed the country. Right to the end of his life, Yuan stayed young at heart, and people always wondered what amazing goal he would set himself next.', '愿景·海水稻与晚年梦想', 156, '[{"q":"What did Yuan imagine about his future rice plants?","answer":"A","options":["That they would grow sorghum-high and carry enormous grains.","That they would never need any water.","That they would grow without any soil.","That they would be smaller than usual."],"explanation":"原文 ''rice plants as tall as sorghum… each grain as huge as a peanut'' 的转述。"},{"q":"What was special about Yuan''s seawater rice?","answer":"B","options":["It could only be grown indoors.","It could grow on salty land where normal crops fail.","It needed far more chemicals than other rice.","It produced no grain at all."],"explanation":"原文 ''growing rice on salty land, where ordinary crops cannot survive'' 的转述。"},{"q":"Why does the writer mention ''one million square kilometres''?","answer":"C","options":["To show how small Yuan''s fields were.","To explain how cheap rice had become.","To show how much salty land might now grow rice.","To prove that seawater rice failed."],"explanation":"原文 ''opened up nearly one million square kilometres of salty land… for rice production'' 的转述。"}]'::jsonb, '[{"word":"envision","cn":"展望;想象"},{"word":"salty","cn":"含盐的"},{"word":"reality","cn":"现实"}]'::jsonb, 2, 'elective1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'The Cost of Chemical Farming', 'Chemical pesticides and artificial fertilisers have been in widespread use since the middle of the last century. When they first appeared, many farmers welcomed them as a great way to fight crop disease and raise production. Over time, however, some scientists found that long-term use can harm both the land and people''s health. Pesticides, for example, kill not only harmful insects but helpful ones too. Worse still, these chemicals can stay in the soil and underground water for a long time. They then affect the crops, and in turn the animals and people who digest them. Some worry that such chemicals may make them ill or even cause serious disease. As for chemical fertilisers, crops grown with them often grow too fast to build up real nutrition. They may look beautiful on the outside, but inside there is usually more water than essential minerals, and they often have less flavour as well. For these reasons, more people now question whether chemical farming is worth its hidden cost.', '议论·化学农业的代价', 167, '[{"q":"Why did farmers first welcome chemical pesticides and fertilisers?","answer":"D","options":["They thought the chemicals were free.","They wanted to harm helpful insects.","They hoped to make their crops taste worse.","They saw them as a way to fight disease and raise output."],"explanation":"原文 ''welcomed them as a great way to fight crop disease and raise production'' 的转述。"},{"q":"What is one danger of pesticides mentioned in the text?","answer":"A","options":["They linger for years in both the ground and underground water.","They make the soil too rich.","They help every kind of insect grow.","They make crops grow more slowly."],"explanation":"原文 ''can stay in the soil and underground water for a long time'' 的转述。"},{"q":"What problem do crops grown with chemical fertilisers often have?","answer":"B","options":["They are far too small to sell.","They contain more water than minerals and taste blander.","They cannot be grown in soil at all.","They have far too many minerals inside."],"explanation":"原文 ''more water than essential minerals, and they often have less flavour'' 的转述。"}]'::jsonb, '[{"word":"pesticide","cn":"杀虫剂"},{"word":"fertiliser","cn":"肥料"},{"word":"nutrition","cn":"营养"}]'::jsonb, 2, 'elective1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'How Organic Farmers Keep Soil Rich', 'Some farmers have turned away from chemicals and chosen organic farming instead. Organic farming is simply farming without using man-made chemicals. These farmers work hard to keep their soil rich and free of disease through natural means. Many of them use animal waste as fertiliser, which makes the soil richer in minerals and keeps the air, water and crops clean. They also use clever methods to build healthy ground. One method is to change the kind of crop grown in a field each year. For instance, they may grow corn or wheat one year and then beans the next, because different crops put different minerals back into the earth. Organic farmers also plant diverse crops that use different depths of soil. Peanuts, for example, grow near the surface, while many vegetables send down deep roots. The goal of all these methods is to grow good, safe food while avoiding damage to the environment and to people''s health.', '说明·有机农业的方法', 157, '[{"q":"What is organic farming, according to the passage?","answer":"C","options":["Farming that uses the strongest chemicals.","Farming that grows only one kind of crop.","Farming carried out without man-made chemicals.","Farming that needs no soil at all."],"explanation":"原文 ''farming without using man-made chemicals'' 的转述。"},{"q":"Why do organic farmers change the crop in a field each year?","answer":"D","options":["Because they enjoy moving their fields around.","Because one crop is illegal to grow twice.","Because beans cannot grow beside corn.","Because different crops return different minerals to the soil."],"explanation":"原文 ''different crops put different minerals back into the earth'' 的转述。"},{"q":"What is the main goal of these organic methods?","answer":"A","options":["To grow safe food without harming people or the environment.","To make crops look beautiful but taste poor.","To sell chemicals to other farmers.","To use up the soil as fast as possible."],"explanation":"原文 ''grow good, safe food while avoiding damage to the environment and to people''s health'' 的转述。"}]'::jsonb, '[{"word":"organic","cn":"有机的"},{"word":"mineral","cn":"矿物质"},{"word":"depth","cn":"深度"}]'::jsonb, 2, 'elective1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Farming Under the City', 'Feeding a growing world is not easy, and people keep looking for new ideas. In London, an old underground shelter has been turned into an urban farm. Built during the Second World War, it could once protect thousands of people from bombs. After the war it was left empty for about seventy years. Then some businessmen decided to make use of it to grow fresh green vegetables for local shops and restaurants. Because there is no natural light deep below the ground, the tunnels are lit with pink lamps. The vegetables grow in special liquids instead of ordinary soil. Supporters say this kind of farming could help in two ways: it could meet the rising demand for food in crowded cities, and it could also help people deal with changes in the climate. Of course, organic farming alone is nowhere near able to feed everyone, so scientists agree there is still a long way to go before a perfect solution is found.', '现实·城市农场与粮食安全', 162, '[{"q":"What was the London shelter first built for?","answer":"B","options":["To grow vegetables underground.","To keep thousands of people safe from bombs.","To store farm machines.","To be a busy shopping centre."],"explanation":"原文 ''could once protect thousands of people from bombs'' 的转述。"},{"q":"Why are pink lamps used in the tunnels?","answer":"C","options":["Because the farmers like the colour pink.","Because the lamps are very cheap.","Because sunlight cannot reach so far beneath the ground.","Because the vegetables grow in real soil."],"explanation":"原文 ''no natural light deep below the ground, the tunnels are lit with pink lamps'' 的转述。"},{"q":"What do supporters say about this kind of urban farming?","answer":"D","options":["It can feed the whole world by itself.","It works only in very sunny places.","It is cheaper than every other method.","It could meet city food needs and help with climate change."],"explanation":"原文 ''meet the rising demand for food… deal with changes in the climate'' 的转述;''feed everyone by itself'' 与原文相反。"}]'::jsonb, '[{"word":"urban","cn":"城市的"},{"word":"tunnel","cn":"隧道"},{"word":"consumption","cn":"消费;需求"}]'::jsonb, 2, 'elective1', 'U5');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE volume='elective1' AND unit='U5';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U5', 'Learning to Work the Land', 'Last summer I stayed with my grandfather and learned how to (1)____ the land. At first I thought farming was easy, but I was (2)____. Every morning we went out to the fields before the sun was high. Grandpa taught me that good crops need rich, clean (3)____. He never used strong chemicals, because he said they could (4)____ the land and our health. Instead, he used animal waste as natural (5)____. He also told me to (6)____ the kind of crop in each field every year, so that the ground stayed rich in minerals. It was hard work, and my back often (7)____. But slowly I began to (8)____ how much care farming needs. By the end of the summer, I felt (9)____ of the vegetables we had grown together. Now I understand why Grandpa says that every (10)____ of rice is the result of hard work.', 148, 2, '[{"q":"1","answer":"A","options":["work","sell","eat","lose"],"explanation":"work the land 耕作土地。"},{"q":"2","answer":"B","options":["happy","wrong","late","rich"],"explanation":"I was wrong 我错了。"},{"q":"3","answer":"C","options":["noise","price","soil","music"],"explanation":"rich, clean soil 肥沃洁净的土壤。"},{"q":"4","answer":"D","options":["clean","build","help","harm"],"explanation":"harm the land 损害土地。"},{"q":"5","answer":"A","options":["fertiliser","machine","weather","money"],"explanation":"natural fertiliser 天然肥料。"},{"q":"6","answer":"B","options":["forget","change","sell","lose"],"explanation":"change the crop 更换作物。"},{"q":"7","answer":"C","options":["sang","smiled","hurt","slept"],"explanation":"my back often hurt 我的背常常疼。"},{"q":"8","answer":"D","options":["waste","forget","ignore","appreciate"],"explanation":"appreciate 体会到。"},{"q":"9","answer":"A","options":["proud","afraid","bored","angry"],"explanation":"felt proud of 为……自豪。"},{"q":"10","answer":"B","options":["price","grain","noise","machine"],"explanation":"every grain of rice 每一粒米。"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U5', 'The Story of One Grain', 'Have you ever thought about where the rice on your (1)____ comes from? Each grain begins as a tiny seed in the (2)____. The farmer plants it in spring and then waits for many (3)____ of hard work. The young plants need sunlight, clean water and rich (4)____ to grow well. Insects and disease can (5)____ a whole field, so the farmer must watch the crop with great care. When autumn comes, the rice turns golden and is ready to (6)____. The farmer collects every (7)____ by hand or by machine, and not a single one should be (8)____. Thanks to scientists like Yuan Longping, today''s rice can give a much higher (9)____ than the rice of the past. So the next time you eat, remember that a simple bowl of rice carries the (10)____ effort of many people.', 139, 2, '[{"q":"1","answer":"C","options":["shoe","phone","plate","book"],"explanation":"rice on your plate 盘中的米饭。"},{"q":"2","answer":"D","options":["sky","shop","city","soil"],"explanation":"a seed in the soil 土里的种子。"},{"q":"3","answer":"A","options":["months","coins","songs","games"],"explanation":"many months of hard work 数月的辛劳。"},{"q":"4","answer":"B","options":["noise","soil","music","paper"],"explanation":"rich soil 肥沃的土壤。"},{"q":"5","answer":"C","options":["build","clean","destroy","sell"],"explanation":"destroy a whole field 毁掉整片田。"},{"q":"6","answer":"D","options":["sleep","leave","lose","harvest"],"explanation":"ready to harvest 可以收割。"},{"q":"7","answer":"A","options":["grain","price","noise","ticket"],"explanation":"collects every grain 收下每一粒。"},{"q":"8","answer":"B","options":["grown","wasted","kept","saved"],"explanation":"should be wasted 不该浪费。"},{"q":"9","answer":"C","options":["noise","price","yield","weather"],"explanation":"a higher yield 更高的产量。"},{"q":"10","answer":"D","options":["empty","free","lucky","hard"],"explanation":"the hard effort 辛勤的努力。"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U5', 'Why I Love the Soil', 'My family is the one (1)____ has farmed this land for three generations. My grandfather often says that the soil is (2)____ to everything we eat. When I was small, I did not (3)____ why he spent so much time in the fields. To me, farming looked dirty and (4)____. But one spring he let me plant a few seeds, and I watched them grow day by (5)____. Slowly I came to (6)____ the magic of the land. I learned that healthy soil is full of (7)____ that plants need to grow strong. I also learned that using too many chemicals can (8)____ the very ground we depend on. Now, working in the fields no longer feels (9)____ to me; it feels like a gift. Whenever I hold a handful of dark, rich earth, I feel (10)____ to be part of such an old and honest way of life.', 149, 2, '[{"q":"1","answer":"A","options":["who","where","when","why"],"explanation":"the one who 指人作主语。"},{"q":"2","answer":"B","options":["empty","essential","salty","cheap"],"explanation":"essential to 对……极其重要。"},{"q":"3","answer":"C","options":["sell","lose","understand","forget"],"explanation":"did not understand 不明白。"},{"q":"4","answer":"D","options":["clean","easy","bright","boring"],"explanation":"dirty and boring 又脏又无聊。"},{"q":"5","answer":"A","options":["day","price","noise","city"],"explanation":"day by day 一天天地。"},{"q":"6","answer":"B","options":["waste","see","sell","lose"],"explanation":"came to see 渐渐看懂。"},{"q":"7","answer":"C","options":["noise","prices","minerals","games"],"explanation":"full of minerals 富含矿物质。"},{"q":"8","answer":"D","options":["help","clean","build","harm"],"explanation":"harm the ground 损害土地。"},{"q":"9","answer":"A","options":["hard","free","rich","late"],"explanation":"no longer feels hard 不再觉得辛苦。"},{"q":"10","answer":"B","options":["afraid","proud","sorry","angry"],"explanation":"feel proud 感到自豪。"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U5', 'A Mix-up at the Market', 'Last week my friend Tom and I went to a (1)____ to buy some vegetables. Tom picked up some bright, shiny tomatoes, but I told him to (2)____. "These look beautiful," I said, "but they were grown with a lot of (3)____." Tom was surprised. He thought beautiful vegetables were always the (4)____ ones. I explained that crops grown too (5)____ are often full of water but poor in nutrition. They may look good, yet they often have less (6)____ as well. Then I led him to a small corner that sold (7)____ vegetables, grown without any chemicals. "These are not as shiny," I said, "but they are (8)____ in minerals and much safer to eat." Tom decided to (9)____ a few and try them at home. That evening he sent me a message: the tomatoes were the most (10)____ ones he had ever tasted!', 145, 2, '[{"q":"1","answer":"C","options":["stadium","library","market","station"],"explanation":"go to a market 去市场。"},{"q":"2","answer":"D","options":["run","sleep","leave","wait"],"explanation":"told him to wait 让他等一下。"},{"q":"3","answer":"A","options":["chemicals","songs","prices","noises"],"explanation":"grown with chemicals 用化学品种的。"},{"q":"4","answer":"B","options":["worst","best","cheapest","smallest"],"explanation":"the best ones 最好的。"},{"q":"5","answer":"C","options":["slowly","late","fast","high"],"explanation":"grown too fast 长得太快。"},{"q":"6","answer":"D","options":["weather","money","noise","flavour"],"explanation":"less flavour 味道更淡。"},{"q":"7","answer":"A","options":["organic","foreign","broken","frozen"],"explanation":"organic vegetables 有机蔬菜。"},{"q":"8","answer":"B","options":["poor","rich","weak","empty"],"explanation":"rich in minerals 富含矿物质。"},{"q":"9","answer":"C","options":["hide","drop","buy","sell"],"explanation":"buy a few 买几个。"},{"q":"10","answer":"D","options":["boring","ugly","empty","nutritious"],"explanation":"the most nutritious 最有营养的(此处指美味营养)。"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U5', 'Bringing in a Better Harvest', 'When Mr Li took over the family farm, the (1)____ were small and the soil was poor. He knew he could not just hope for a better (2)____; he had to change the way he farmed. First, he stopped using so many chemical (3)____, which had been killing both harmful and helpful insects. Then he started to (4)____ the kind of crop in each field every year. One year he grew wheat, and the next he grew (5)____, which put important minerals back into the (6)____. He also chose new hybrid seeds that could (7)____ a much higher yield. The first season was hard, and many neighbours did not (8)____ that his plan would work. But by autumn his fields were full of healthy crops. His success slowly (9)____ other farmers in the village to try the same methods. Today the whole area produces far more (10)____ than it did before.', 151, 2, '[{"q":"1","answer":"A","options":["fields","shops","rivers","roads"],"explanation":"the fields were small 田地很小。"},{"q":"2","answer":"B","options":["price","harvest","noise","weather"],"explanation":"a better harvest 更好的收成。"},{"q":"3","answer":"C","options":["songs","tickets","pesticides","machines"],"explanation":"chemical pesticides 化学杀虫剂。"},{"q":"4","answer":"D","options":["forget","lose","sell","change"],"explanation":"change the kind of crop 更换作物种类。"},{"q":"5","answer":"A","options":["beans","stones","lamps","coins"],"explanation":"grew beans 种豆子(豆类还田增肥)。"},{"q":"6","answer":"B","options":["sky","soil","shop","city"],"explanation":"back into the soil 回到土壤里。"},{"q":"7","answer":"C","options":["lose","break","give","hide"],"explanation":"give a higher yield 带来更高产量。"},{"q":"8","answer":"D","options":["sell","lose","forget","believe"],"explanation":"did not believe 不相信。"},{"q":"9","answer":"A","options":["encouraged","stopped","frightened","blamed"],"explanation":"encouraged others 鼓励了别人。"},{"q":"10","answer":"B","options":["noise","food","rubbish","smoke"],"explanation":"produces far more food 产出更多粮食。"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'elective1', 'U5', 'How Hybrid Rice Changed a Village', 'My grandmother still remembers the years (1)____ our village often went hungry. The fields were the same size as today, but the (2)____ was very low. Sometimes there was a serious (3)____ of food, and people worried all winter. Then, in the 1970s, scientists developed a new kind of (4)____ rice. It could give a much higher yield than the (5)____ crops the village had grown for centuries. At first the farmers were not (6)____ that the new seeds would work, but they decided to (7)____ them anyway. To everyone''s surprise, the harvest that autumn was the biggest the village had ever (8)____. Year after year, the new rice helped families (9)____ their output and finally escape hunger. My grandmother says that one good idea, turned into (10)____, can change the life of a whole village.', 136, 2, '[{"q":"1","answer":"C","options":["where","why","when","which"],"explanation":"the years when 时间先行词用 when。"},{"q":"2","answer":"D","options":["noise","price","weather","yield"],"explanation":"the yield was low 产量很低。"},{"q":"3","answer":"A","options":["shortage","song","game","machine"],"explanation":"a serious shortage 严重短缺。"},{"q":"4","answer":"B","options":["frozen","hybrid","broken","foreign"],"explanation":"hybrid rice 杂交水稻。"},{"q":"5","answer":"C","options":["salty","urban","conventional","organic"],"explanation":"conventional crops 常规作物。"},{"q":"6","answer":"D","options":["afraid","sorry","angry","convinced"],"explanation":"not convinced 没被说服。"},{"q":"7","answer":"A","options":["try","lose","hide","sell"],"explanation":"try them 试用它们。"},{"q":"8","answer":"B","options":["lost","seen","sold","broken"],"explanation":"the biggest harvest the village had ever seen 见过的最大丰收。"},{"q":"9","answer":"C","options":["waste","lose","expand","drop"],"explanation":"expand their output 扩大产量。"},{"q":"10","answer":"D","options":["noise","trouble","danger","reality"],"explanation":"turned into reality 变成现实。"}]'::jsonb, 6);

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE volume='elective1' AND unit='U5';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·对话 Choosing to Study Agriculture', '选择性必修一 U5 · dialogue', 3, 'Lucy: What do you want to study at university, Tom?
Tom: I''ve decided to study agriculture.
Lucy: Agriculture? That''s not a common choice. Why?
Tom: My grandparents are farmers, and I grew up in the fields.
Lucy: So you really love working the land.
Tom: I do. And I want to help farmers grow more food.
Lucy: Like Yuan Longping, the father of hybrid rice?
Tom: Exactly. He is the reason I want to do this.', 'Lucy 问 Tom 想上大学读什么;Tom 决定学农业;因为祖父母是农民,他在田里长大,真心热爱耕作;他想帮农民种出更多粮食;像杂交水稻之父袁隆平那样,袁隆平正是他立志学农的原因。', 'uk_female', '[{"q":"What does Tom want to study?","type":"choice","answer":"A","options":["Agriculture.","Medicine.","Music.","History."]},{"q":"Why is Tom interested in this subject?","type":"choice","answer":"B","options":["His friends told him to.","He grew up in the fields with farming grandparents.","He wants to leave the countryside.","He thinks it is the easiest subject."]},{"q":"What does Tom hope to do in the future?","type":"choice","answer":"A","options":["Help farmers grow more food.","Stop all farming.","Sell his family''s land.","Move far away from farms."]},{"q":"Who does Tom mention as his model?","type":"choice","answer":"B","options":["A famous singer.","Yuan Longping.","A football player.","His school teacher."]},{"q":"How does Lucy feel about Tom''s choice at first?","type":"choice","answer":"C","options":["She thinks it is boring.","She thinks it is wrong.","She thinks it is an unusual choice.","She is angry about it."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·短文 The Problem of World Hunger', '选择性必修一 U5 · passage', 2, 'World hunger is still a serious problem today.
About one in ten people on the planet does not get enough food.
Wars can heavily affect how food is grown and moved.
Many poor families simply cannot afford to eat well.
Helping farmers grow more food is one important way to fight hunger.', '如今世界饥饿仍是严重问题;地球上约十分之一的人吃不饱;战争会严重影响粮食的种植和运输;许多贫困家庭根本吃不起好的食物;帮助农民种出更多粮食是抗击饥饿的重要途径之一。', 'uk_female', '[{"q":"What does the speaker say about world hunger?","type":"choice","answer":"D","options":["It has completely ended.","It only happens in cities.","It is no longer studied.","It is still a serious problem today."]},{"q":"About how many people do not get enough food?","type":"choice","answer":"A","options":["About one in ten people.","None at all.","Everyone on the planet.","Only farmers."]},{"q":"How can wars affect food, according to the passage?","type":"choice","answer":"B","options":["They make food cheaper.","They affect how food is grown and moved.","They have no effect on food.","They only help farmers."]},{"q":"Why can''t many poor families eat well?","type":"choice","answer":"C","options":["They dislike all food.","They grow too much food.","They cannot afford good food.","They live far from cities."]},{"q":"What is one important way to fight hunger?","type":"choice","answer":"D","options":["Stop all farming.","Close all the markets.","Move everyone to the city.","Help farmers grow more food."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·对话 Organic or Chemical?', '选择性必修一 U5 · dialogue', 3, 'Anna: These apples are cheaper, but I''m buying the organic ones.
Ben: Why? The cheaper ones look just as good.
Anna: Organic food is grown without chemical pesticides.
Ben: Does that really make a difference?
Anna: Yes. Chemicals can stay in the soil and even in the food.
Ben: I see. So organic food may be safer for us.
Anna: That''s right. It often has more flavour too.
Ben: All right, I''ll try the organic ones this time.', 'Anna 宁愿买稍贵的有机苹果;Ben 不解,觉得便宜的看着一样好;Anna 解释有机食品不用化学杀虫剂;化学品会残留在土壤甚至食物中;有机食品对人更安全,味道往往也更好;Ben 决定这次也试试有机的。', 'uk_female', '[{"q":"Which apples does Anna decide to buy?","type":"choice","answer":"A","options":["The organic ones.","The cheapest ones.","No apples at all.","The biggest ones."]},{"q":"How is organic food grown?","type":"choice","answer":"B","options":["With many chemicals.","Without chemical pesticides.","Only in salty land.","Without any soil."]},{"q":"Why does Anna think chemicals are a problem?","type":"choice","answer":"C","options":["They make food cheaper.","They help every insect.","They can stay in the soil and food.","They have no effect at all."]},{"q":"What does Anna say about the flavour of organic food?","type":"choice","answer":"D","options":["It tastes worse.","It has no taste.","It tastes the same.","It often has more flavour."]},{"q":"What does Ben decide at the end?","type":"choice","answer":"A","options":["To try the organic apples this time.","To buy no fruit.","To grow his own apples.","To buy the cheapest ones."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·短文 A Man of the Soil', '选择性必修一 U5 · passage', 2, 'Yuan Longping spent his whole life working the land.
He developed the first hybrid rice that farmers could really use.
His new rice gave a much higher yield than older crops.
Even after he grew rich, he still lived like a simple farmer.
His dream was to keep all people away from hunger.', '袁隆平一生都在耕耘土地;他培育出第一种农民真正能用的杂交水稻;新稻的产量远高于旧作物;即使富有了,他仍像普通农民一样生活;他的梦想是让所有人远离饥饿。', 'uk_female', '[{"q":"What did Yuan Longping spend his whole life doing?","type":"choice","answer":"B","options":["Travelling the world.","Working the land.","Selling chemicals.","Teaching music."]},{"q":"What did Yuan develop?","type":"choice","answer":"C","options":["A new kind of car.","A chemical pesticide.","The first usable hybrid rice.","A city farm."]},{"q":"How did his new rice compare with older crops?","type":"choice","answer":"D","options":["It gave less food.","It was exactly the same.","It could not be eaten.","It gave a much higher yield."]},{"q":"How did Yuan live after he grew rich?","type":"choice","answer":"A","options":["He still lived like a simple farmer.","He moved to another country.","He stopped all his work.","He became very lazy."]},{"q":"What was Yuan''s dream?","type":"choice","answer":"B","options":["To become the richest man.","To keep all people away from hunger.","To stop growing rice.","To leave the countryside."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·对话 Helping on the Farm', '选择性必修一 U5 · dialogue', 3, 'Grandpa: Could you help me in the fields this weekend, Kate?
Kate: Of course, Grandpa. What do you need me to do?
Grandpa: We need to change the crop in the east field.
Kate: Why do we change it every year?
Grandpa: Different crops put different minerals back into the soil.
Kate: So that keeps the land rich and healthy.
Grandpa: Exactly. Last year we grew wheat, so this year we''ll grow beans.
Kate: I understand now. Farming takes real care.', '爷爷请 Kate 周末到田里帮忙;Kate 答应,问要做什么;爷爷说要给东边那块地换种作物;Kate 问为什么每年都换;因为不同作物把不同矿物质还回土壤,使土地保持肥沃健康;去年种小麦,今年种豆子;Kate 明白了:务农需要真正的用心。', 'uk_female', '[{"q":"What does Grandpa ask Kate to do?","type":"choice","answer":"C","options":["Cook dinner for him.","Clean the house.","Help him in the fields.","Sell the farm."]},{"q":"What job needs doing in the east field?","type":"choice","answer":"D","options":["Building a new house.","Cutting down trees.","Selling the soil.","Changing the crop."]},{"q":"Why does Grandpa change the crop every year?","type":"choice","answer":"A","options":["Because different crops return different minerals to the soil.","Because he is bored.","Because the field is too small.","Because beans are cheap."]},{"q":"What did they grow last year, and what now?","type":"choice","answer":"B","options":["Rice last year, corn now.","Wheat last year, beans now.","Beans last year, wheat now.","Corn last year, rice now."]},{"q":"What does Kate learn from the talk?","type":"choice","answer":"C","options":["Farming is very easy.","Farming needs many chemicals.","Farming takes real care.","Farming is a waste of time."]}]'::jsonb, '[]'::jsonb, 'long', 'elective1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·短文 World Food Day', '选择性必修一 U5 · passage', 2, 'World Food Day is held every year in October.
It is celebrated in more than one hundred and fifty countries.
The day reminds people of the problems of hunger and poverty.
Schools often hold activities to teach students about food.
Its message is simple: no one in the world should go hungry.', '世界粮食日每年十月举行;在一百五十多个国家庆祝;这一天提醒人们关注饥饿与贫困问题;学校常举办活动让学生了解粮食;它的信息很简单:世界上不该有人挨饿。', 'uk_female', '[{"q":"When is World Food Day held?","type":"choice","answer":"D","options":["Every week.","Only once in history.","Every day.","Every year in October."]},{"q":"In how many countries is it celebrated?","type":"choice","answer":"A","options":["In more than one hundred and fifty countries.","In just one country.","In no countries.","Only in schools."]},{"q":"What does the day remind people of?","type":"choice","answer":"B","options":["The price of cars.","The problems of hunger and poverty.","The latest films.","The weather in summer."]},{"q":"What do schools often do on this day?","type":"choice","answer":"C","options":["Close for a holiday.","Sell food to visitors.","Hold activities to teach students about food.","Forget about the day."]},{"q":"What is the message of World Food Day?","type":"choice","answer":"D","options":["Food should be very expensive.","Only farmers matter.","Hunger cannot be solved.","No one should go hungry."]}]'::jsonb, '[]'::jsonb, 'short', 'elective1', 'U5');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE volume='elective1' AND unit='U5';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit) VALUES (10, 'Write an Argumentative Essay on Organic Farming(就有机农业写一篇议论文)', 'Why I Support Organic Farming', '假设你叫李华,你们班正就''化学农业 vs 有机农业''展开讨论。请用英语写一篇约100词的议论文,内容包括:① 明确表态你支持哪一种农业(化学/有机);② 给出两到三条理由,每条理由配一个细节;③ 写一句总结。注意:观点鲜明、条理清楚、句句围绕主题。', 'Suppose you are Li Hua. Your class is discussing ''chemical farming versus organic farming''. Write an argumentative essay (about 100 words) including: 1) a clear statement of which kind of farming you support; 2) two or three reasons, each with a supporting detail; 3) a short conclusion. Make your opinion clear and keep every sentence on topic.', '["亮明观点(In my opinion, organic farming is preferable to chemical farming.)","理由+细节1(First, organic food is safer, because no chemicals stay in the soil or the food.)","理由+细节2(Second, organic methods protect the land, for example by changing crops every year.)","总结(All in all, organic farming is better for our health and our environment.)"]'::jsonb, 70, 100, 'Recently our class has been discussing chemical farming and organic farming. In my opinion, organic farming is preferable to chemical farming. First, organic food is safer for our health. Growing crops without pesticides means that no harmful chemicals stay in the soil or in the food we eat. Second, organic methods protect the land. For instance, organic farmers change the kind of crop in each field every year, which keeps the soil rich in minerals. Of course, organic farming cannot yet feed the whole world by itself. Even so, I believe that growing food in this natural way is better for both our health and our environment.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["In my opinion, organic farming is preferable to chemical farming.","Growing crops without pesticides means that no harmful chemicals stay in the soil or in the food we eat.","Organic farmers change the kind of crop in each field every year, which keeps the soil rich in minerals.","Growing food in this natural way is better for both our health and our environment."]'::jsonb, '[{"wrong":"Grow crops without chemicals are safer.","correct":"Growing crops without chemicals is safer.","note":"动名词作主语,谓语用单数 is;不能用动词原形 Grow。"},{"wrong":"It is no use to use too many pesticides.","correct":"It is no use using too many pesticides.","note":"It is no use doing 固定句式,用动名词。"},{"wrong":"Organic farming protect the land.","correct":"Organic farming protects the land.","note":"主语第三人称单数,谓语动词加 s。"}]'::jsonb, '【农业议论文结构】
第1句 引出话题 + 亮明观点:In my opinion, organic farming is preferable to chemical farming.
第2-3句 理由1+细节:First, … because / Growing … means that …
第4-5句 理由2+细节:Second, … For instance, …
第6句 让步+总结:Of course, … Even so, I believe that …', 2, 'elective1', 'U5');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE volume='elective1' AND unit='U5';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content) VALUES (10, 'elective1', 'U5', '{"title":"动名词(-ing form)作主语 速查","intro":"把一个动作''名词化''放到句首当主语,就用动名词(doing)。动名词作主语时看作单数,谓语用 is/was/feeds 等单数形式。常与 it 形式主语、no use/no point 等固定句式搭配。","table":{"headers":["用法","例句 / 说明"],"rows":[["动名词直接作主语","Growing rice feeds millions.(谓语用单数 feeds)"],["it 作形式主语","It is no use crying over spilt milk.(真正主语是 crying)"],["no point / waste of time","There is no point (in) waiting. / It''s a waste of time complaining."],["复合结构作主语","Tom''s / His coming made us happy.(所有格 + doing)"],["动名词 vs 不定式","动名词主语=泛指/一般;不定式主语=具体/将来(常用 it 形式)"]]},"specialRules":[{"rule":"动名词作主语 → 谓语永远用单数","mark":"Reading widens our minds.（widens 单数）"},{"rule":"It is no use / no good doing … 只能跟动名词,不能跟不定式","mark":"It is no use crying √ / to cry ×"},{"rule":"There is no point (in) doing …;a waste of time doing …","mark":"no point waiting √"},{"rule":"动名词前可加名词所有格/形容词性物主代词作逻辑主语","mark":"his coming / Tom''s leaving"}],"why":["动名词兼具''动词''(有动作含义、可带宾语)和''名词''(可作主语)的双重身份,所以能稳稳地占住句首主语的位置;而 does/done 没有名词性,不能作主语。"],"gaokaoPoints":["句首主语位的填空:动名词 vs 动词原形/第三人称单数/过去分词——只有动名词能作主语,谓语用单数。","固定句式 It is no use/no good doing、There is no point (in) doing、a waste of time doing——高频考动名词。","动名词主语(泛指、一般)与不定式主语(具体、将来,常用 it 形式主语)的选用对照。"],"examVsReal":[{"exam":"Smoking is bad for your health.（考试/正式)","real":"Smoking? Bad for you.","note":"考试用完整动名词主语句;口语里常省略谓语、用碎句"},{"exam":"It is no use crying over spilt milk.（书面谚语)","real":"No point crying about it.","note":"口语里 It is 常省略,直接 No point doing"}]}'::jsonb);

COMMIT;

-- ===== 自带校验 =====
SELECT 'vocab' k, count(*) v, 46 expect FROM public.junior_vocab WHERE volume='elective1' AND unit='U5'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='elective1' AND unit='U5'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='elective1' AND unit='U5'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='elective1' AND unit='U5'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='elective1' AND unit='U5'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE volume='elective1' AND unit='U5' ORDER BY k;
SELECT 'grammar' rel, correct_answer ans, count(*) FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='elective1' AND unit='U5') GROUP BY 2 ORDER BY 2;
