-- 8B U2:回填 junior_vocab.phrase_en(英文短语/语块)。幂等:按 word_id 精确 UPDATE,可重跑。
-- 前置:必须先跑 ALTER TABLE ... ADD COLUMN phrase_en text;

UPDATE public.junior_vocab SET phrase_en = 'by ourselves' WHERE word_id = 'jr-8B-U2-0001';
UPDATE public.junior_vocab SET phrase_en = 'a sore throat' WHERE word_id = 'jr-8B-U2-0002';
UPDATE public.junior_vocab SET phrase_en = 'clear your throat' WHERE word_id = 'jr-8B-U2-0003';
UPDATE public.junior_vocab SET phrase_en = 'have a stomachache' WHERE word_id = 'jr-8B-U2-0004';
UPDATE public.junior_vocab SET phrase_en = 'have a headache' WHERE word_id = 'jr-8B-U2-0005';
UPDATE public.junior_vocab SET phrase_en = 'have a toothache' WHERE word_id = 'jr-8B-U2-0006';
UPDATE public.junior_vocab SET phrase_en = 'have a backache' WHERE word_id = 'jr-8B-U2-0007';
UPDATE public.junior_vocab SET phrase_en = 'suffer from headaches' WHERE word_id = 'jr-8B-U2-0008';
UPDATE public.junior_vocab SET phrase_en = 'press the button' WHERE word_id = 'jr-8B-U2-0009';
UPDATE public.junior_vocab SET phrase_en = 'a sudden nosebleed' WHERE word_id = 'jr-8B-U2-0010';
UPDATE public.junior_vocab SET phrase_en = 'see the dentist' WHERE word_id = 'jr-8B-U2-0011';
UPDATE public.junior_vocab SET phrase_en = 'an empty stomach' WHERE word_id = 'jr-8B-U2-0012';
UPDATE public.junior_vocab SET phrase_en = 'avoid junk food' WHERE word_id = 'jr-8B-U2-0013';
UPDATE public.junior_vocab SET phrase_en = 'natural gas' WHERE word_id = 'jr-8B-U2-0014';
UPDATE public.junior_vocab SET phrase_en = 'aches and pains' WHERE word_id = 'jr-8B-U2-0015';
UPDATE public.junior_vocab SET phrase_en = 'take an X-ray' WHERE word_id = 'jr-8B-U2-0016';
UPDATE public.junior_vocab SET phrase_en = 'a careless mistake' WHERE word_id = 'jr-8B-U2-0017';
UPDATE public.junior_vocab SET phrase_en = 'a runny nose' WHERE word_id = 'jr-8B-U2-0018';
UPDATE public.junior_vocab SET phrase_en = 'have a cough' WHERE word_id = 'jr-8B-U2-0019';
UPDATE public.junior_vocab SET phrase_en = 'a bruised knee' WHERE word_id = 'jr-8B-U2-0020';
UPDATE public.junior_vocab SET phrase_en = 'an eye test' WHERE word_id = 'jr-8B-U2-0021';
UPDATE public.junior_vocab SET phrase_en = 'have the flu' WHERE word_id = 'jr-8B-U2-0022';
UPDATE public.junior_vocab SET phrase_en = 'take some medicine' WHERE word_id = 'jr-8B-U2-0023';
UPDATE public.junior_vocab SET phrase_en = 'wear a mask' WHERE word_id = 'jr-8B-U2-0024';
UPDATE public.junior_vocab SET phrase_en = 'a computer virus' WHERE word_id = 'jr-8B-U2-0025';
UPDATE public.junior_vocab SET phrase_en = 'a clear description' WHERE word_id = 'jr-8B-U2-0026';
UPDATE public.junior_vocab SET phrase_en = 'be patient' WHERE word_id = 'jr-8B-U2-0027';
UPDATE public.junior_vocab SET phrase_en = 'a minor injury' WHERE word_id = 'jr-8B-U2-0028';
UPDATE public.junior_vocab SET phrase_en = 'a common illness' WHERE word_id = 'jr-8B-U2-0029';
UPDATE public.junior_vocab SET phrase_en = 'a kitchen knife' WHERE word_id = 'jr-8B-U2-0030';
UPDATE public.junior_vocab SET phrase_en = 'road safety' WHERE word_id = 'jr-8B-U2-0031';
UPDATE public.junior_vocab SET phrase_en = 'a clear sky' WHERE word_id = 'jr-8B-U2-0032';
UPDATE public.junior_vocab SET phrase_en = 'ease the pain' WHERE word_id = 'jr-8B-U2-0033';
UPDATE public.junior_vocab SET phrase_en = 'screen brightness' WHERE word_id = 'jr-8B-U2-0034';
UPDATE public.junior_vocab SET phrase_en = 'protect the environment' WHERE word_id = 'jr-8B-U2-0035';
UPDATE public.junior_vocab SET phrase_en = 'cross the road' WHERE word_id = 'jr-8B-U2-0036';
UPDATE public.junior_vocab SET phrase_en = 'by themselves' WHERE word_id = 'jr-8B-U2-0037';
UPDATE public.junior_vocab SET phrase_en = 'a hot stove' WHERE word_id = 'jr-8B-U2-0038';
UPDATE public.junior_vocab SET phrase_en = 'play happily' WHERE word_id = 'jr-8B-U2-0039';
UPDATE public.junior_vocab SET phrase_en = 'burn the toast' WHERE word_id = 'jr-8B-U2-0040';
UPDATE public.junior_vocab SET phrase_en = 'a candle flame' WHERE word_id = 'jr-8B-U2-0041';
UPDATE public.junior_vocab SET phrase_en = 'don''t panic' WHERE word_id = 'jr-8B-U2-0042';
UPDATE public.junior_vocab SET phrase_en = 'throw the ball' WHERE word_id = 'jr-8B-U2-0043';
UPDATE public.junior_vocab SET phrase_en = 'roll the ball' WHERE word_id = 'jr-8B-U2-0044';
UPDATE public.junior_vocab SET phrase_en = 'a quick rest' WHERE word_id = 'jr-8B-U2-0045';
UPDATE public.junior_vocab SET phrase_en = 'a first aid kit' WHERE word_id = 'jr-8B-U2-0046';
UPDATE public.junior_vocab SET phrase_en = 'a fire extinguisher' WHERE word_id = 'jr-8B-U2-0047';
UPDATE public.junior_vocab SET phrase_en = 'see you tonight' WHERE word_id = 'jr-8B-U2-0048';
UPDATE public.junior_vocab SET phrase_en = 'sadly true' WHERE word_id = 'jr-8B-U2-0049';
UPDATE public.junior_vocab SET phrase_en = 'no smoking here' WHERE word_id = 'jr-8B-U2-0050';
UPDATE public.junior_vocab SET phrase_en = 'luckily on time' WHERE word_id = 'jr-8B-U2-0051';
UPDATE public.junior_vocab SET phrase_en = 'badly needed' WHERE word_id = 'jr-8B-U2-0052';
UPDATE public.junior_vocab SET phrase_en = 'no harm done' WHERE word_id = 'jr-8B-U2-0053';
UPDATE public.junior_vocab SET phrase_en = 'take a pill' WHERE word_id = 'jr-8B-U2-0054';
UPDATE public.junior_vocab SET phrase_en = 'hit the ball' WHERE word_id = 'jr-8B-U2-0055';
UPDATE public.junior_vocab SET phrase_en = 'a big shock' WHERE word_id = 'jr-8B-U2-0056';
UPDATE public.junior_vocab SET phrase_en = 'stop the bleeding' WHERE word_id = 'jr-8B-U2-0057';
UPDATE public.junior_vocab SET phrase_en = 'check your homework' WHERE word_id = 'jr-8B-U2-0058';
UPDATE public.junior_vocab SET phrase_en = 'a tight knot' WHERE word_id = 'jr-8B-U2-0059';
UPDATE public.junior_vocab SET phrase_en = 'wait nervously' WHERE word_id = 'jr-8B-U2-0060';
UPDATE public.junior_vocab SET phrase_en = 'allergic to nuts' WHERE word_id = 'jr-8B-U2-0061';
UPDATE public.junior_vocab SET phrase_en = 'suffer from a cold' WHERE word_id = 'jr-8B-U2-7001';
UPDATE public.junior_vocab SET phrase_en = 'take my temperature' WHERE word_id = 'jr-8B-U2-7002';
UPDATE public.junior_vocab SET phrase_en = 'stop it from falling' WHERE word_id = 'jr-8B-U2-7003';
UPDATE public.junior_vocab SET phrase_en = 'what''s more' WHERE word_id = 'jr-8B-U2-7004';
UPDATE public.junior_vocab SET phrase_en = 'catch fire easily' WHERE word_id = 'jr-8B-U2-7005';
UPDATE public.junior_vocab SET phrase_en = 'turn on the light' WHERE word_id = 'jr-8B-U2-7006';
UPDATE public.junior_vocab SET phrase_en = 'no way' WHERE word_id = 'jr-8B-U2-7007';
UPDATE public.junior_vocab SET phrase_en = 'be about to leave' WHERE word_id = 'jr-8B-U2-7008';
UPDATE public.junior_vocab SET phrase_en = 'a first aid kit' WHERE word_id = 'jr-8B-U2-7009';
UPDATE public.junior_vocab SET phrase_en = 'eat out tonight' WHERE word_id = 'jr-8B-U2-7010';
UPDATE public.junior_vocab SET phrase_en = 'from now on' WHERE word_id = 'jr-8B-U2-7011';

-- 校验:本单元已回填条数(应 = 72)
SELECT count(*) FILTER (WHERE phrase_en IS NOT NULL) AS filled, count(*) AS total
FROM public.junior_vocab WHERE grade = 8 AND volume = '8B' AND unit = 'U2';
