-- 8A U4:回填 junior_vocab.phrase_en(英文短语/语块)。幂等:按 word_id 精确 UPDATE,可重跑。
-- 前置:必须先跑 ALTER TABLE ... ADD COLUMN phrase_en text;

UPDATE public.junior_vocab SET phrase_en = 'care about others' WHERE word_id = 'jr-8A-U4-7001';
UPDATE public.junior_vocab SET phrase_en = 'lend me a hand' WHERE word_id = 'jr-8A-U4-7002';
UPDATE public.junior_vocab SET phrase_en = 'feel free to ask' WHERE word_id = 'jr-8A-U4-7003';
UPDATE public.junior_vocab SET phrase_en = 'up to ten people' WHERE word_id = 'jr-8A-U4-7004';
UPDATE public.junior_vocab SET phrase_en = 'take a walk' WHERE word_id = 'jr-8A-U4-7005';
UPDATE public.junior_vocab SET phrase_en = 'connected with nature' WHERE word_id = 'jr-8A-U4-7006';
UPDATE public.junior_vocab SET phrase_en = 'in fact' WHERE word_id = 'jr-8A-U4-7007';
UPDATE public.junior_vocab SET phrase_en = 'for this reason' WHERE word_id = 'jr-8A-U4-7008';
UPDATE public.junior_vocab SET phrase_en = 'in order to learn' WHERE word_id = 'jr-8A-U4-7009';
UPDATE public.junior_vocab SET phrase_en = 'home to many animals' WHERE word_id = 'jr-8A-U4-7010';
UPDATE public.junior_vocab SET phrase_en = 'play an important role' WHERE word_id = 'jr-8A-U4-7011';
UPDATE public.junior_vocab SET phrase_en = 'a small accident' WHERE word_id = 'jr-8A-U4-9001';
UPDATE public.junior_vocab SET phrase_en = 'expect good news' WHERE word_id = 'jr-8A-U4-9002';
UPDATE public.junior_vocab SET phrase_en = 'a silver coin' WHERE word_id = 'jr-8A-U4-9003';
UPDATE public.junior_vocab SET phrase_en = 'a difficult situation' WHERE word_id = 'jr-8A-U4-9004';
UPDATE public.junior_vocab SET phrase_en = 'touch the screen' WHERE word_id = 'jr-8A-U4-9005';
UPDATE public.junior_vocab SET phrase_en = 'lend me a pen' WHERE word_id = 'jr-8A-U4-9006';
UPDATE public.junior_vocab SET phrase_en = 'thank goodness' WHERE word_id = 'jr-8A-U4-9007';
UPDATE public.junior_vocab SET phrase_en = 'a useful tool' WHERE word_id = 'jr-8A-U4-9008';
UPDATE public.junior_vocab SET phrase_en = 'actually true' WHERE word_id = 'jr-8A-U4-9009';
UPDATE public.junior_vocab SET phrase_en = 'shoot a basketball' WHERE word_id = 'jr-8A-U4-9010';
UPDATE public.junior_vocab SET phrase_en = 'appear suddenly' WHERE word_id = 'jr-8A-U4-9011';
UPDATE public.junior_vocab SET phrase_en = 'raise your hand' WHERE word_id = 'jr-8A-U4-9012';
UPDATE public.junior_vocab SET phrase_en = 'African animals' WHERE word_id = 'jr-8A-U4-9013';
UPDATE public.junior_vocab SET phrase_en = 'a red rose' WHERE word_id = 'jr-8A-U4-9014';
UPDATE public.junior_vocab SET phrase_en = 'a beautiful peony' WHERE word_id = 'jr-8A-U4-9015';
UPDATE public.junior_vocab SET phrase_en = 'a lotus flower' WHERE word_id = 'jr-8A-U4-9016';
UPDATE public.junior_vocab SET phrase_en = 'a beautiful butterfly' WHERE word_id = 'jr-8A-U4-9017';
UPDATE public.junior_vocab SET phrase_en = 'a bird''s wing' WHERE word_id = 'jr-8A-U4-9018';
UPDATE public.junior_vocab SET phrase_en = 'a little frog' WHERE word_id = 'jr-8A-U4-9019';
UPDATE public.junior_vocab SET phrase_en = 'weigh ten kilos' WHERE word_id = 'jr-8A-U4-9020';
UPDATE public.junior_vocab SET phrase_en = 'five kg of rice' WHERE word_id = 'jr-8A-U4-9021';
UPDATE public.junior_vocab SET phrase_en = 'a ginkgo tree' WHERE word_id = 'jr-8A-U4-9022';
UPDATE public.junior_vocab SET phrase_en = 'believe in yourself' WHERE word_id = 'jr-8A-U4-9023';
UPDATE public.junior_vocab SET phrase_en = 'a southern province' WHERE word_id = 'jr-8A-U4-9024';
UPDATE public.junior_vocab SET phrase_en = 'connect to the internet' WHERE word_id = 'jr-8A-U4-9025';
UPDATE public.junior_vocab SET phrase_en = 'closely connected' WHERE word_id = 'jr-8A-U4-9026';
UPDATE public.junior_vocab SET phrase_en = 'without water' WHERE word_id = 'jr-8A-U4-9027';
UPDATE public.junior_vocab SET phrase_en = 'imagine the future' WHERE word_id = 'jr-8A-U4-9028';
UPDATE public.junior_vocab SET phrase_en = 'green moss' WHERE word_id = 'jr-8A-U4-9029';
UPDATE public.junior_vocab SET phrase_en = 'a tall redwood' WHERE word_id = 'jr-8A-U4-9030';
UPDATE public.junior_vocab SET phrase_en = 'a fast cheetah' WHERE word_id = 'jr-8A-U4-9031';
UPDATE public.junior_vocab SET phrase_en = 'a folding chair' WHERE word_id = 'jr-8A-U4-9032';
UPDATE public.junior_vocab SET phrase_en = 'a bamboo forest' WHERE word_id = 'jr-8A-U4-9033';
UPDATE public.junior_vocab SET phrase_en = 'yeah, sure' WHERE word_id = 'jr-8A-U4-9034';
UPDATE public.junior_vocab SET phrase_en = 'a popular song' WHERE word_id = 'jr-8A-U4-9035';
UPDATE public.junior_vocab SET phrase_en = 'a jar of honey' WHERE word_id = 'jr-8A-U4-9036';
UPDATE public.junior_vocab SET phrase_en = 'feel disappointed' WHERE word_id = 'jr-8A-U4-9037';
UPDATE public.junior_vocab SET phrase_en = 'a strong connection' WHERE word_id = 'jr-8A-U4-9038';
UPDATE public.junior_vocab SET phrase_en = 'plant pollination' WHERE word_id = 'jr-8A-U4-9039';
UPDATE public.junior_vocab SET phrase_en = 'collect pollen' WHERE word_id = 'jr-8A-U4-9040';
UPDATE public.junior_vocab SET phrase_en = 'take action now' WHERE word_id = 'jr-8A-U4-9041';
UPDATE public.junior_vocab SET phrase_en = 'fifty percent' WHERE word_id = 'jr-8A-U4-9042';
UPDATE public.junior_vocab SET phrase_en = 'our planet earth' WHERE word_id = 'jr-8A-U4-9043';
UPDATE public.junior_vocab SET phrase_en = 'store food' WHERE word_id = 'jr-8A-U4-9044';
UPDATE public.junior_vocab SET phrase_en = 'a golden honeycomb' WHERE word_id = 'jr-8A-U4-9045';
UPDATE public.junior_vocab SET phrase_en = 'communicate with others' WHERE word_id = 'jr-8A-U4-9046';
UPDATE public.junior_vocab SET phrase_en = 'a healthy ecosystem' WHERE word_id = 'jr-8A-U4-9047';
UPDATE public.junior_vocab SET phrase_en = 'protect the environment' WHERE word_id = 'jr-8A-U4-9048';
UPDATE public.junior_vocab SET phrase_en = 'great importance' WHERE word_id = 'jr-8A-U4-9049';
UPDATE public.junior_vocab SET phrase_en = 'float on water' WHERE word_id = 'jr-8A-U4-9050';
UPDATE public.junior_vocab SET phrase_en = 'human beings' WHERE word_id = 'jr-8A-U4-9051';
UPDATE public.junior_vocab SET phrase_en = 'a tiny ant' WHERE word_id = 'jr-8A-U4-9052';
UPDATE public.junior_vocab SET phrase_en = 'full of happiness' WHERE word_id = 'jr-8A-U4-9053';
UPDATE public.junior_vocab SET phrase_en = 'never disappoint others' WHERE word_id = 'jr-8A-U4-9054';
UPDATE public.junior_vocab SET phrase_en = 'a fresh mushroom' WHERE word_id = 'jr-8A-U4-9055';
UPDATE public.junior_vocab SET phrase_en = 'a ton of rice' WHERE word_id = 'jr-8A-U4-9056';
UPDATE public.junior_vocab SET phrase_en = 'an important role' WHERE word_id = 'jr-8A-U4-9057';
UPDATE public.junior_vocab SET phrase_en = 'green peas' WHERE word_id = 'jr-8A-U4-9058';
UPDATE public.junior_vocab SET phrase_en = 'a warm climate' WHERE word_id = 'jr-8A-U4-9059';
UPDATE public.junior_vocab SET phrase_en = 'the deep ocean' WHERE word_id = 'jr-8A-U4-9060';
UPDATE public.junior_vocab SET phrase_en = 'everyone except me' WHERE word_id = 'jr-8A-U4-9061';
UPDATE public.junior_vocab SET phrase_en = 'a tiny insect' WHERE word_id = 'jr-8A-U4-9062';
UPDATE public.junior_vocab SET phrase_en = 'a lively city' WHERE word_id = 'jr-8A-U4-9063';

-- 校验:本单元已回填条数(应 = 74)
SELECT count(*) FILTER (WHERE phrase_en IS NOT NULL) AS filled, count(*) AS total
FROM public.junior_vocab WHERE grade = 8 AND volume = '8A' AND unit = 'U4';
