-- ============================================================
-- 必修一 U5(Languages Around the World)灌库(junior_* 表,volume='required1' unit='U5' grade=10)。幂等。
-- preflight(grade 7-12 + senior 分类)已随 U1 跑过,不必再跑。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 44 =====
DELETE FROM public.junior_vocab WHERE volume='required1' AND unit='U5';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'system', 'n.', '/ˈsɪstəm/', '体系;系统;制度', 'The Chinese writing system has lasted thousands of years.', '汉字书写系统已延续数千年。', 'Languages Around the World', 1, 0, 'senior', 'wordlist', 'required1', 'U5', 'the writing system', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'character', 'n.', '/ˈkærəktə(r)/', '文字;符号;角色;品质;特点', 'Some ancient symbols can still be seen in today''s characters.', '一些古老的符号至今仍能在汉字中看到。', 'Languages Around the World', 2, 0, 'senior', 'wordlist', 'required1', 'U5', 'Chinese characters', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'calligraphy', 'n.', '/kəˈlɪɡrəfi/', '书法;书法艺术', 'Chinese calligraphy is an important part of the culture.', '中国书法是文化的重要组成部分。', 'Languages Around the World', 3, 0, 'senior', 'wordlist', 'required1', 'U5', 'Chinese calligraphy', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'civilisation', 'n.', '/ˌsɪvəlaɪˈzeɪʃn/', '文明;文明世界', 'China is known for its ancient civilisation.', '中国以其古老的文明而闻名。', 'Languages Around the World', 4, 0, 'senior', 'wordlist', 'required1', 'U5', 'ancient civilisation', '美式拼 civilization;美音 /ˌsɪvələˈzeɪʃn/');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'dynasty', 'n.', '/ˈdɪnəsti/', '王朝;朝代', 'The writing system developed during the Shang Dynasty.', '书写系统在商朝得到发展。', 'Languages Around the World', 5, 0, 'senior', 'wordlist', 'required1', 'U5', 'the Qin Dynasty', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'symbol', 'n.', '/ˈsɪmbl/', '符号;象征', 'Ancient people carved symbols onto bones and shells.', '古人把符号刻在骨头和龟甲上。', 'Languages Around the World', 6, 0, 'senior', 'wordlist', 'required1', 'U5', 'carve symbols', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'carve', 'v.', '/kɑːv/', '雕刻', 'The symbols were carved by ancient Chinese people.', '这些符号是古代中国人刻上去的。', 'Languages Around the World', 7, 0, 'senior', 'wordlist', 'required1', 'U5', 'carve onto bone', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'bone', 'n.', '/bəʊn/', '骨头;骨', 'Early writing was done on animal bones.', '早期文字写在动物骨头上。', 'Languages Around the World', 8, 0, 'senior', 'wordlist', 'required1', 'U5', 'animal bones', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'shell', 'n.', '/ʃel/', '壳;贝壳', 'Symbols were carved onto bones and shells.', '符号被刻在骨头和龟甲上。', 'Languages Around the World', 9, 0, 'senior', 'wordlist', 'required1', 'U5', 'bones and shells', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'dialect', 'n.', '/ˈdaɪəlekt/', '方言;地方话', 'People who speak different dialects can still read the same characters.', '说不同方言的人仍能读懂同样的汉字。', 'Languages Around the World', 10, 0, 'senior', 'wordlist', 'required1', 'U5', 'different dialects', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'means', 'n.', '/miːnz/', '方式;方法;途径', 'Writing is a means by which the past connects with the present.', '文字是连接过去与现在的一种方式。', 'Languages Around the World', 11, 0, 'senior', 'wordlist', 'required1', 'U5', 'a means of', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'classic', 'adj./n.', '/ˈklæsɪk/', '经典的;典型的;经典作品', 'People today can read the classic works of the past.', '今天的人能读懂过去的经典作品。', 'Languages Around the World', 12, 0, 'senior', 'wordlist', 'required1', 'U5', 'classic works', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'regard', 'v./n.', '/rɪˈɡɑːd/', '把……视为;尊重;关注', 'Chinese people hold their writing system in high regard.', '中国人非常看重自己的书写系统。', 'Languages Around the World', 13, 0, 'senior', 'wordlist', 'required1', 'U5', 'high regard', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'unify', 'v.', '/ˈjuːnɪfaɪ/', '统一;(使)成一体', 'Emperor Qinshihuang unified the writing system.', '秦始皇统一了文字。', 'Languages Around the World', 14, 0, 'senior', 'wordlist', 'required1', 'U5', 'unify the country', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'variety', 'n.', '/vəˈraɪəti/', '变体;多样化;种类', 'Over time, many varieties of characters appeared.', '随着时间推移,出现了许多文字变体。', 'Languages Around the World', 15, 0, 'senior', 'wordlist', 'required1', 'U5', 'a variety of', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'major', 'adj.', '/ˈmeɪdʒə(r)/', '主要的;重要的;大的', 'The writing system was a major factor in uniting the people.', '书写系统是团结人民的一个主要因素。', 'Languages Around the World', 16, 0, 'senior', 'wordlist', 'required1', 'U5', 'a major factor', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'factor', 'n.', '/ˈfæktə(r)/', '因素;要素', 'Many factors helped the culture survive.', '许多因素帮助这一文化得以延续。', 'Languages Around the World', 17, 0, 'senior', 'wordlist', 'required1', 'U5', 'an important factor', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'despite', 'prep.', '/dɪˈspaɪt/', '尽管;即使', 'The civilisation continued despite many ups and downs.', '尽管历经诸多起伏,这一文明仍延续下来。', 'Languages Around the World', 18, 0, 'senior', 'wordlist', 'required1', 'U5', 'despite the difficulties', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'develop', 'v.', '/dɪˈveləp/', '发展;开发;成长', 'The symbols developed into a writing system.', '这些符号发展成了一套书写系统。', 'Languages Around the World', 19, 0, 'senior', 'wordlist', 'required1', 'U5', 'develop into', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'modern', 'adj.', '/ˈmɒdn/', '现代的;近代的', 'The ancient civilisation has continued into modern times.', '这一古老文明一直延续到现代。', 'Languages Around the World', 20, 0, 'senior', 'wordlist', 'required1', 'U5', 'modern times', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'ancient', 'adj.', '/ˈeɪnʃənt/', '古代的;古老的', 'People in modern times can read ancient writing.', '现代人能读懂古代的文字。', 'Languages Around the World', 21, 0, 'senior', 'wordlist', 'required1', 'U5', 'ancient symbols', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'communicate', 'v.', '/kəˈmjuːnɪkeɪt/', '交流;沟通;传达', 'People across China can communicate in writing.', '中国各地的人都能用文字交流。', 'Languages Around the World', 22, 0, 'senior', 'wordlist', 'required1', 'U5', 'communicate in writing', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'native', 'adj./n.', '/ˈneɪtɪv/', '本地的;出生地的;本地人', 'Chinese has the most native speakers in the world.', '汉语是世界上母语使用者最多的语言。', 'Languages Around the World', 23, 0, 'senior', 'wordlist', 'required1', 'U5', 'native speakers', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'global', 'adj.', '/ˈɡləʊbl/', '全球的;全世界的', 'China plays a greater role in global affairs today.', '如今中国在全球事务中发挥着更大作用。', 'Languages Around the World', 24, 0, 'senior', 'wordlist', 'required1', 'U5', 'global affairs', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'billion', 'num.', '/ˈbɪljən/', '十亿', 'These languages are spoken by billions of people.', '这些语言被数十亿人使用。', 'Languages Around the World', 25, 0, 'senior', 'wordlist', 'required1', 'U5', 'billions of people', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'attitude', 'n.', '/ˈætɪtjuːd/', '态度;看法', 'My attitude towards language learning changed over time.', '我对语言学习的态度逐渐改变了。', 'Languages Around the World', 26, 0, 'senior', 'wordlist', 'required1', 'U5', 'a positive attitude', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'struggle', 'n./v.', '/ˈstrʌɡl/', '斗争;奋斗;艰难地做', 'At first, studying German was a real struggle for me.', '起初,学德语对我来说很吃力。', 'Languages Around the World', 27, 0, 'senior', 'wordlist', 'required1', 'U5', 'a struggle', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'tongue', 'n.', '/tʌŋ/', '舌头;语言', 'The new words felt strange on my tongue.', '这些新词读起来很别扭。', 'Languages Around the World', 28, 0, 'senior', 'wordlist', 'required1', 'U5', 'on my tongue', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'appreciate', 'v.', '/əˈpriːʃieɪt/', '欣赏;重视;感激;领会', 'Students begin to appreciate China''s culture through the language.', '学生们通过这门语言开始欣赏中国文化。', 'Languages Around the World', 29, 0, 'senior', 'wordlist', 'required1', 'U5', 'appreciate the culture', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'specific', 'adj.', '/spəˈsɪfɪk/', '特定的;明确的;具体的', 'Scan the text to find specific information such as dates.', '略读课文,寻找日期等具体信息。', 'Languages Around the World', 30, 0, 'senior', 'wordlist', 'required1', 'U5', 'specific information', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'reference', 'n.', '/ˈrefrəns/', '指称关系;参考;提及', 'Pronouns refer to something mentioned earlier in the text.', '代词指代文中前面提到的事物。', 'Languages Around the World', 31, 0, 'senior', 'wordlist', 'required1', 'U5', 'make a reference to', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'relate', 'v.', '/rɪˈleɪt/', '联系;讲述;相关', 'Each sentence should relate to the main idea.', '每个句子都应与中心思想相关。', 'Languages Around the World', 32, 0, 'senior', 'wordlist', 'required1', 'U5', 'relate to', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'gap', 'n.', '/ɡæp/', '差距;间隔;缺口', 'A few kind words can bridge the gap between strangers.', '几句友善的话能拉近陌生人之间的距离。', 'Languages Around the World', 33, 0, 'senior', 'wordlist', 'required1', 'U5', 'bridge the gap', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'increase', 'v.', '/ɪnˈkriːs/', '增加;增长', 'An increasing number of students are learning Chinese.', '越来越多的学生在学习汉语。', 'Languages Around the World', 34, 0, 'senior', 'wordlist', 'required1', 'U5', 'an increasing number', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'spell', 'v.', '/spel/', '拼写;拼出', 'English words are spelt according to how they sound.', '英语单词按发音拼写。', 'Languages Around the World', 35, 0, 'senior', 'wordlist', 'required1', 'U5', 'spell a word', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'advice', 'n.', '/ədˈvaɪs/', '建议;忠告', 'Wang Le asked the forum for advice on listening.', '王乐在论坛上请教听力方面的建议。', 'Languages Around the World', 36, 0, 'senior', 'wordlist', 'required1', 'U5', 'give advice', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'polite', 'adj.', '/pəˈlaɪt/', '礼貌的;客气的', 'It is hard to know how to be polite in another language.', '在另一种语言里很难掌握如何表达礼貌。', 'Languages Around the World', 37, 0, 'senior', 'wordlist', 'required1', 'U5', 'be polite', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'request', 'n./v.', '/rɪˈkwest/', '请求;要求', '"Could you open the window?" is a polite request.', '"你能开下窗户吗?"是一个礼貌的请求。', 'Languages Around the World', 38, 0, 'senior', 'wordlist', 'required1', 'U5', 'a polite request', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'depend', 'v.', '/dɪˈpend/', '依靠;取决于', 'How polite to be depends on who you are talking to.', '该多礼貌取决于你在和谁说话。', 'Languages Around the World', 39, 0, 'senior', 'wordlist', 'required1', 'U5', 'depend on', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'record', 'v.', '/rɪˈkɔːd/', '录(音);记录', 'Sometimes I record my voice to compare my pronunciation.', '有时我录下自己的声音来比较发音。', 'Languages Around the World', 40, 0, 'senior', 'wordlist', 'required1', 'U5', 'record my voice', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'trouble', 'n.', '/ˈtrʌbl/', '困难;麻烦', 'I''m having a lot of trouble with my listening.', '我的听力遇到了很多困难。', 'Languages Around the World', 41, 0, 'senior', 'wordlist', 'required1', 'U5', 'have trouble with', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'foreign', 'adj.', '/ˈfɒrən/', '外国的;外来的', 'There are many reasons why people learn a foreign language.', '人们学外语有许多原因。', 'Languages Around the World', 42, 0, 'senior', 'wordlist', 'required1', 'U5', 'a foreign language', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'history', 'n.', '/ˈhɪstri/', '历史;历程', 'The civilisation continued despite the ups and downs in its history.', '尽管历史几经起伏,这一文明仍延续下来。', 'Languages Around the World', 43, 0, 'senior', 'wordlist', 'required1', 'U5', 'through history', NULL);
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip) VALUES (10, 'connect', 'v.', '/kəˈnekt/', '连接;联系', 'Written Chinese connects the present with the past.', '汉字把现在与过去连接起来。', 'Languages Around the World', 44, 0, 'senior', 'wordlist', 'required1', 'U5', 'connect the past and present', NULL);

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5');
DELETE FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('u5.01', '①when(时间先行词 = on/in/at which)', 'A2', 10, '必修一 U5 — 先行词表时间(day/time/year/moment 等)、从句不缺主语或宾语(只缺时间状语)时,用关系副词 when(= 介词+which)。', 1, 'required1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('u5.02', '②where(地点先行词 = in/at/on which)', 'A2', 10, '必修一 U5 — 先行词表地点(place/country/city/room 等)、从句只缺地点状语时,用关系副词 where(= 介词+which)。', 2, 'required1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth) VALUES ('u5.03', '③why(原因)+ 关系副词 vs 关系代词判断', 'A2', 10, '必修一 U5 — 先行词为 reason、从句缺原因状语时用 why;但若从句缺主语/宾语,即使先行词表时间/地点也要用关系代词 that/which;介词后只能用 which。', 3, 'required1', 'U5', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0);
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"I still remember the day ____ I first wrote a Chinese character."', 'when', 'which', 'where', 'that', 'A', '先行词 day 表时间,从句不缺主宾(只缺时间状语)→ when。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"There was a time ____ people in China were divided by dialects."', 'which', 'when', 'where', 'that', 'B', '先行词 time、从句完整 → when。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"Spring is the season ____ many students start learning a new language."', 'which', 'where', 'when', 'that', 'C', '先行词 season 表时间 → when。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"1949 was the year ____ the country began a new chapter."', 'which', 'where', 'that', 'when', 'D', '先行词 year 表时间 → when。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"I will never forget the moment ____ I could finally think in German."', 'when', 'which', 'where', 'that', 'A', '先行词 moment 表时间 → when。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"That was the day ____ Emperor Qinshihuang unified the writing system."', 'which', 'when', 'where', 'that', 'B', '先行词 day、从句完整 → when。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"There comes a point ____ a foreign language no longer feels foreign."', 'which', 'where', 'when', 'that', 'C', 'point 在此表''时刻''→ when。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"Sunday is the day ____ I usually practise my calligraphy."', 'which', 'where', 'that', 'when', 'D', '先行词 day → when。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"He still recalls the night ____ he gave his first speech in English."', 'when', 'which', 'where', 'that', 'A', '先行词 night 表时间 → when。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"There is an age ____ children begin to learn characters."', 'which', 'when', 'where', 'that', 'B', 'age 在此表''时期''→ when。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"That was the period ____ many varieties of characters appeared."', 'which', 'where', 'when', 'that', 'C', '先行词 period 表时间 → when。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"I remember the week ____ I first started the German course."', 'which', 'where', 'that', 'when', 'D', '先行词 week 表时间 → when。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"Autumn is the time of year ____ we hold the language festival."', 'when', 'which', 'where', 'that', 'A', '先行词 time of year → when。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"It was an era ____ writing was done on bones and shells."', 'which', 'when', 'where', 'that', 'B', '先行词 era 表时间 → when。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"I''ll never forget the first day ____ Mrs Haus introduced herself to us."', 'which', 'where', 'when', 'that', 'C', '先行词 day、从句完整 → when。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"There was a time ____ I really wanted to give up learning."', 'which', 'where', 'that', 'when', 'D', '先行词 time → when。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"I remember the morning ____ I read my first book in Latin."', 'when', 'which', 'where', 'that', 'A', '先行词 morning 表时间 → when。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"That was the moment ____ the whole room suddenly fell silent."', 'which', 'when', 'where', 'that', 'B', '先行词 moment → when。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"202 BCE was the year ____ the Han Dynasty began."', 'which', 'where', 'when', 'that', 'C', '先行词 year → when。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.01'), '"I''ll always remember the day ____ I finally understood my mum''s words."', 'which', 'where', 'that', 'when', 'D', '先行词 day、从句完整 → when。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"Qinshihuang built a unified country ____ the writing system developed in one direction."', 'where', 'which', 'when', 'that', 'A', '先行词 country 表地点、从句完整 → where。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"I had finally come to a place ____ I could think in this foreign language."', 'which', 'where', 'when', 'that', 'B', '先行词 place 表地点 → where。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"This is the school ____ I first learned to write Chinese."', 'which', 'when', 'where', 'that', 'C', '先行词 school 表地点 → where。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"Canada is a country ____ several languages are spoken."', 'which', 'when', 'that', 'where', 'D', '先行词 country 表地点 → where。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"That is the classroom ____ Mrs Haus taught us German."', 'where', 'which', 'when', 'that', 'A', '先行词 classroom → where。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"I once wished to live in a country ____ German was spoken every day."', 'which', 'where', 'when', 'that', 'B', '先行词 country 表地点 → where。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"China is a place ____ people of different dialects communicate in writing."', 'which', 'when', 'where', 'that', 'C', '先行词 place → where。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"We visited the museum ____ ancient bones and shells are kept."', 'which', 'when', 'that', 'where', 'D', '先行词 museum 表地点 → where。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"It was a small room ____ we met for our language classes."', 'where', 'which', 'when', 'that', 'A', '先行词 room 表地点 → where。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"There are still villages ____ an old dialect is spoken today."', 'which', 'where', 'when', 'that', 'B', '先行词 villages 表地点 → where。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"The library is the place ____ I quietly studied Latin every afternoon."', 'which', 'when', 'where', 'that', 'C', '先行词 place → where。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"That is the building ____ the summer German course was held."', 'which', 'when', 'that', 'where', 'D', '先行词 building 表地点 → where。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"Reading opened a window to a world ____ I could see meanings, not just words."', 'where', 'which', 'when', 'that', 'A', '先行词 world 表抽象地点 → where。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"It was a time and a land ____ people were divided geographically."', 'which', 'where', 'when', 'that', 'B', '先行词 land 表地点 → where。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"I found a quiet corner ____ I could read in peace."', 'which', 'when', 'where', 'that', 'C', '先行词 corner 表地点 → where。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"That is the office ____ our German teacher used to work."', 'which', 'when', 'that', 'where', 'D', '先行词 office 表地点 → where。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"Rome was a city ____ Latin was once the main language."', 'where', 'which', 'when', 'that', 'A', '先行词 city 表地点 → where。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"This is the studio ____ Chinese calligraphy is taught."', 'which', 'where', 'when', 'that', 'B', '先行词 studio 表地点 → where。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"He showed me the hall ____ the old dictionary was first written."', 'which', 'when', 'where', 'that', 'C', '先行词 hall 表地点 → where。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.02'), '"There is a website ____ students can practise foreign languages for free."', 'which', 'when', 'that', 'where', 'D', 'website 视作抽象地点 → where。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The reason ____ he gave up was simply a lack of practice."', 'why', 'that', 'which', 'where', 'A', '先行词 reason、从句缺原因状语 → why。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"There are many reasons ____ people learn a foreign language."', 'that', 'why', 'which', 'where', 'B', '先行词 reasons → why。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"I finally understood the reason ____ my mum had encouraged me."', 'that', 'which', 'why', 'where', 'C', '先行词 reason → why。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"One reason ____ this has been possible is the writing system."', 'that', 'which', 'where', 'why', 'D', '先行词 reason → why。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"That is the reason ____ Mrs Haus''s students loved German so much."', 'why', 'that', 'which', 'where', 'A', '先行词 reason → why。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"This is the main reason ____ written Chinese has survived so long."', 'that', 'why', 'which', 'where', 'B', '先行词 reason → why。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"I don''t know the reason ____ he suddenly stopped studying Latin."', 'that', 'which', 'why', 'where', 'C', '先行词 reason → why。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"There must be a reason ____ so many students choose Chinese."', 'that', 'which', 'where', 'why', 'D', '先行词 reason → why。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The day ____ changed my view of language was truly special."', 'that', 'when', 'where', 'why', 'A', '先行词 day 虽表时间,但从句缺主语 → 用关系代词 that(不是 when)。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The book ____ I read that summer opened a whole new world."', 'when', 'that', 'where', 'why', 'B', '先行词 book、从句缺宾语 → 关系代词 that。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The language ____ she loved most of all was German."', 'when', 'where', 'that', 'why', 'C', '先行词 language、从句缺主语 → that。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The place ____ I visited last week was a calligraphy museum."', 'when', 'where', 'why', 'that', 'D', '先行词 place 虽表地点,但从句缺宾语(visited ___)→ 用 that(不是 where)。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The words ____ felt strange at first soon began to make sense."', 'that', 'when', 'where', 'why', 'A', '先行词 words、从句缺主语 → that。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The first character ____ I learned to write was 马 (horse)."', 'when', 'that', 'where', 'why', 'B', '先行词 character、从句缺宾语 → that。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The goal ____ I had been fighting for was finally within reach."', 'when', 'where', 'that', 'why', 'C', '先行词 goal、从句缺宾语 → that。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The dialect ____ they speak at home is hard for outsiders to follow."', 'when', 'where', 'why', 'that', 'D', '先行词 dialect、从句缺宾语 → that。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"These were animal bones and shells on ____ symbols were carved."', 'which', 'that', 'when', 'where', 'A', '介词 on 后只能用 which(不可 that)。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"That was the way in ____ the writing system developed."', 'that', 'which', 'when', 'where', 'B', 'the way in which;介词 in 后用 which。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"Calligraphy is a means by ____ China''s present connects with its past."', 'that', 'when', 'which', 'where', 'C', 'a means by which;介词 by 后用 which。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5' AND code='u5.03'), '"The brush with ____ calligraphy is done must be held correctly."', 'that', 'when', 'where', 'which', 'D', '介词 with 后指物用 which。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE volume='required1' AND unit='U5';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'The Chinese Writing System', 'China is widely known for its ancient civilisation, which has continued into modern times despite the many ups and downs in its history. There are many reasons why this has been possible, but one of the main factors has been the Chinese writing system. At the beginning, written Chinese was a picture-based language. It dates back thousands of years to symbols carved on animal bones and shells. By the Shang Dynasty, these symbols had become a well-developed writing system. Over time, the system developed into different forms, and many varieties of characters appeared. This changed under Emperor Qinshihuang of the Qin Dynasty, who united the seven major states into one country where the writing system began to develop in one direction. That writing system was of great importance in uniting the Chinese people and culture.', '说明·汉字书写系统', 135, '[{"q":"According to the text, what has helped Chinese civilisation continue?","answer":"A","options":["Mainly the Chinese writing system.","Only its large population.","The weather of the country.","Foreign trade alone."],"explanation":"原文 ''one of the main factors has been the Chinese writing system'' 的转述。"},{"q":"What was written Chinese like at the very beginning?","answer":"B","options":["It was based on sounds.","It was a picture-based language.","It had no symbols at all.","It was the same as today''s hanzi."],"explanation":"原文 ''written Chinese was a picture-based language''(中段)。"},{"q":"What did Emperor Qinshihuang do for the writing system?","answer":"A","options":["He united the country so it developed in one direction.","He removed all characters.","He made it picture-based again.","He banned the use of writing."],"explanation":"末段 ''united the seven major states… develop in one direction'' 的转述。"}]'::jsonb, '[{"word":"civilisation","cn":"文明"},{"word":"system","cn":"体系;系统"},{"word":"unify","cn":"统一"}]'::jsonb, 2, 'required1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'The Art of Chinese Calligraphy', 'Written Chinese has become an important means by which China''s present is connected with its past. People today can read the classic works that were written in ancient times. The high regard for the writing system can be seen in the development of Chinese characters as an art form, known as Chinese calligraphy. Calligraphy is not only a beautiful art done with a brush, but also a way of showing the character of the person behind the brush. It is difficult to say exactly when calligraphy began, but it dates back at least to the Han Dynasty. Today, anyone from small children to old people can enjoy practising this art. As China plays a greater role in global affairs, an increasing number of international students are beginning to appreciate Chinese culture through this amazing language.', '说明·中国书法', 135, '[{"q":"What can people today still read, thanks to the writing system?","answer":"B","options":["Only modern newspapers.","The classic works written long ago.","Pictures with no words.","Nothing from the past."],"explanation":"原文 ''read the classic works that were written in ancient times'' 的转述。"},{"q":"Besides being beautiful, what does calligraphy show?","answer":"C","options":["The price of the brush.","The weather of the day.","The personality of the writer holding the brush.","The age of the paper."],"explanation":"原文 ''a way of showing the character of the person behind the brush''(中段)。"},{"q":"Why are more international students appreciating Chinese culture?","answer":"D","options":["Because Chinese is easy to spell.","Because calligraphy is free.","Because no one studies English now.","Because China is becoming more important in the world."],"explanation":"末句 ''As China plays a greater role in global affairs…'' 的转述。"}]'::jsonb, '[{"word":"calligraphy","cn":"书法"},{"word":"classic","cn":"经典的"},{"word":"appreciate","cn":"欣赏"}]'::jsonb, 2, 'required1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Why Learn a Foreign Language', 'There are about seven thousand languages in the world, but only a few are spoken by very large numbers of people. Chinese and English have the most speakers, and the official languages of the United Nations are spoken by around 2.8 billion people as a native or second language. So why do so many students study a foreign language? Some think it means better job chances in the future. Others want to enjoy films, music or books in their original language. A few simply love the sound of a language and want to travel to the countries where it is spoken. Whatever the reason, learning a new language opens a door to a different way of thinking. It lets you see the world from another point of view, and that, many believe, is worth all the hard work.', '议论·为何学外语', 138, '[{"q":"How many languages are there in the world, according to the text?","answer":"A","options":["About seven thousand.","Only a few hundred.","Exactly 2.8 billion.","Just two."],"explanation":"原文 ''about seven thousand languages in the world'' 的转述。"},{"q":"Why do some students learn a foreign language?","answer":"B","options":["To forget their own language.","Because it may improve their future job prospects.","Because they are forced to.","To avoid travelling abroad."],"explanation":"原文 ''better job chances in the future''(中段,众多原因之一)。"},{"q":"What does the writer say learning a language gives you?","answer":"C","options":["Less free time.","A worse memory.","A new way of seeing the world.","Fewer friends."],"explanation":"末段 ''see the world from another point of view'' 的转述。"}]'::jsonb, '[{"word":"native","cn":"本地的;母语的"},{"word":"billion","cn":"十亿"},{"word":"point of view","cn":"观点"}]'::jsonb, 2, 'required1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'My Struggle with German', 'When I started studying German, it was a real struggle. The words felt strange on my tongue, and the grammar would not stay in my head. I told my mum that I wanted to give up. But she said that studying a language was not just for my future; it was exercise for the brain. The more I learned of a language, she said, the more my brain would grow. So I kept going. Then came the day when German suddenly no longer felt like a foreign language. I had finally reached a place where I could think in it and see the world from a different point of view. I could open a book and see meanings, not just a sea of words. That was when I finally understood the reason why my mum had encouraged me not to give up.', '记叙·学德语的奋斗', 142, '[{"q":"How did the writer feel when first studying German?","answer":"D","options":["It was very easy.","It was boring and useless.","It felt like a holiday.","It felt very difficult at first."],"explanation":"原文 ''it was a real struggle'' 的转述。"},{"q":"What did the writer''s mum compare language learning to?","answer":"A","options":["Exercise for the brain.","A waste of time.","A game with no rules.","A short holiday."],"explanation":"原文 ''it was exercise for the brain''(中段)。"},{"q":"What finally happened after the writer kept going?","answer":"B","options":["The writer gave up completely.","The writer could think in German and see meanings.","German became harder than ever.","The mum stopped helping."],"explanation":"末段 ''could think in it… see meanings, not just a sea of words'' 的转述。"}]'::jsonb, '[{"word":"struggle","cn":"艰难;奋斗"},{"word":"tongue","cn":"舌头;语言"},{"word":"attitude","cn":"态度"}]'::jsonb, 2, 'required1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Two Kinds of English', 'English is not exactly the same everywhere. British English and American English use different words for the same things. For example, what British people call petrol, Americans call gas; the British underground is the American subway; a British flat is an American apartment. Sometimes these differences can cause funny misunderstandings. A Chinese student once told his British friend that he wanted to buy some pants. In American English, pants means trousers, but in British English the same word means underwear. They both laughed when they understood the mix-up. These differences are not mistakes; they are just two ways of speaking the same language. If you are not sure which word someone means, it is always polite to ask, "Sorry, what do you mean by that?"', '说明·英美英语差异', 125, '[{"q":"What is the British word for the American ''gas''?","answer":"C","options":["Subway.","Apartment.","Petrol.","Underground."],"explanation":"原文 ''what British people call petrol, Americans call gas''。"},{"q":"Why did the two friends laugh?","answer":"D","options":["Because the student spoke no English.","Because they could not find a shop.","Because the word did not exist.","Because ''pants'' means different things in the two kinds of English."],"explanation":"原文 ''pants means trousers… means underwear… laughed when they understood''(中段)。"},{"q":"What does the writer suggest doing when you are unsure of a word?","answer":"A","options":["Politely ask what the person means.","Stop speaking English.","Guess and say nothing.","Use only Chinese."],"explanation":"末句 ''it is always polite to ask…'' 的转述。"}]'::jsonb, '[{"word":"dialect","cn":"方言"},{"word":"apartment","cn":"公寓"},{"word":"polite","cn":"礼貌的"}]'::jsonb, 2, 'required1', 'U5');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (10, 'Help with Learning English', 'On an online forum, Chinese students share their biggest problems with learning English. Wang Le says he used to get high marks but now has trouble with listening; when native speakers talk fast, he can catch only a few words. Jia Xin advises listening to English radio programmes to get used to the speed, and even recording your own voice to compare your pronunciation with the host''s. Jia Xin''s own headache is being polite: it is easy to say "Open the window", but harder to choose between "Open the window, please" and "Would you mind opening the window?" Li Rui explains that the right choice depends on who you are talking to. With a close friend, a few short words are enough; with someone you do not know well, a longer and more polite question is better. For Li Rui, though, the biggest problem is simply remembering so many new words.', '应用·学英语困难与建议', 151, '[{"q":"What is Wang Le''s main problem with English now?","answer":"B","options":["He cannot read at all.","He has trouble with listening.","He forgets how to write.","He dislikes English films."],"explanation":"原文 ''now has trouble with listening'' 的转述。"},{"q":"What does Jia Xin advise doing to improve listening?","answer":"C","options":["Stop listening to English.","Only read silently.","Listen to English radio and record your own voice.","Speak Chinese more often."],"explanation":"原文 ''listening to English radio programmes… recording your own voice''(中段)。"},{"q":"According to Li Rui, what does being polite in English depend on?","answer":"D","options":["The time of day.","The weather.","How loud you speak.","The person you are speaking with."],"explanation":"原文 ''the right choice depends on who you are talking to''(后段)。"}]'::jsonb, '[{"word":"advice","cn":"建议"},{"word":"trouble","cn":"困难"},{"word":"depend","cn":"取决于"}]'::jsonb, 2, 'required1', 'U5');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE volume='required1' AND unit='U5';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required1', 'U5', 'Learning to Write Chinese', 'When I first started learning Chinese, the characters looked like tiny pictures that I could not (1)____. My teacher told me that each character is a (2)____ with its own meaning and story. She said that written Chinese (3)____ back thousands of years to symbols carved on bones. At first it was a real (4)____, and the strokes felt strange on my hand. But slowly I began to (5)____ how beautiful the writing was. I learned that people who speak different (6)____ across China can still read the same characters. That is the (7)____ why written Chinese has helped to (8)____ the country for so long. Now I practise a few characters every (9)____, and each one feels like a small window into an ancient (10)____. Learning to write Chinese has changed the way I see the world.', 138, 2, '[{"q":"1","answer":"A","options":["read","eat","buy","throw"],"explanation":"could not read 看不懂。"},{"q":"2","answer":"B","options":["price","symbol","noise","season"],"explanation":"a symbol 一个符号。"},{"q":"3","answer":"C","options":["looks","gives","dates","puts"],"explanation":"date back 追溯到。"},{"q":"4","answer":"D","options":["holiday","game","joke","struggle"],"explanation":"a real struggle 一种艰难。"},{"q":"5","answer":"A","options":["appreciate","forget","waste","lose"],"explanation":"appreciate 欣赏。"},{"q":"6","answer":"B","options":["foods","dialects","songs","games"],"explanation":"different dialects 不同方言。"},{"q":"7","answer":"C","options":["price","noise","reason","weather"],"explanation":"the reason why 原因。"},{"q":"8","answer":"D","options":["break","leave","sell","unify"],"explanation":"unify the country 统一国家。"},{"q":"9","answer":"A","options":["day","year","century","never"],"explanation":"every day 每天。"},{"q":"10","answer":"B","options":["machine","civilisation","market","garden"],"explanation":"ancient civilisation 古老文明。"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required1', 'U5', 'The Story of a Character', 'Many Chinese characters began as simple (1)____ of real things. Long ago, ancient people (2)____ marks onto animal bones and shells to record their lives. The character for ''horse'', for example, once looked like a real horse with four (3)____ and a tail. Over the (4)____, the picture slowly became simpler, until it turned into the character we (5)____ today. This is one (6)____ why Chinese is such an interesting language to learn: behind each character there is often a small (7)____. By the Shang Dynasty, these pictures had developed into a complete writing (8)____. Even now, some of the ancient (9)____ can still be seen inside modern characters. Learning where a character comes from makes it much easier to (10)____.', 121, 2, '[{"q":"1","answer":"C","options":["prices","noises","pictures","machines"],"explanation":"pictures of real things 实物的图画。"},{"q":"2","answer":"D","options":["sold","ate","lost","carved"],"explanation":"carved marks 刻下记号。"},{"q":"3","answer":"A","options":["legs","books","wheels","wings"],"explanation":"four legs 四条腿。"},{"q":"4","answer":"B","options":["minutes","years","seconds","metres"],"explanation":"over the years 多年间。"},{"q":"5","answer":"C","options":["buy","drop","use","hide"],"explanation":"the character we use 我们使用的字。"},{"q":"6","answer":"D","options":["price","shop","city","reason"],"explanation":"one reason why 一个原因。"},{"q":"7","answer":"A","options":["story","price","noise","error"],"explanation":"a small story 一个小故事。"},{"q":"8","answer":"B","options":["machine","system","garden","market"],"explanation":"writing system 书写系统。"},{"q":"9","answer":"C","options":["songs","prices","symbols","tickets"],"explanation":"ancient symbols 古老符号。"},{"q":"10","answer":"D","options":["forget","lose","sell","remember"],"explanation":"easier to remember 更容易记住。"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required1', 'U5', 'Why I Love Calligraphy', 'My grandfather is the person (1)____ first showed me Chinese calligraphy. He told me it is an (2)____ form done with a soft brush. At first my lines were shaky and ugly, and I almost wanted to give (3)____. But Grandpa said that calligraphy shows the (4)____ of the person behind the brush, so I should be patient. Little by little, I learned to hold the brush correctly and to (5)____ each stroke slowly. Now calligraphy is the hobby (6)____ I enjoy most. It makes me feel (7)____ and helps me forget the stress of school. It also (8)____ me to the past, because people have practised this art for thousands of (9)____. Whenever I pick up my brush, I feel proud to be part of such an ancient (10)____.', 130, 2, '[{"q":"1","answer":"A","options":["who","which","where","when"],"explanation":"the person who 指人作主语。"},{"q":"2","answer":"B","options":["exam","art","error","event"],"explanation":"an art form 一种艺术形式。"},{"q":"3","answer":"C","options":["in","off","up","out"],"explanation":"give up 放弃。"},{"q":"4","answer":"D","options":["price","weather","noise","character"],"explanation":"the character of the person 人的品格。"},{"q":"5","answer":"A","options":["draw","throw","sell","lose"],"explanation":"draw each stroke 画好每一笔。"},{"q":"6","answer":"B","options":["who","that","where","when"],"explanation":"the hobby that I enjoy 指物作宾语。"},{"q":"7","answer":"C","options":["angry","afraid","calm","bored"],"explanation":"feel calm 感到平静。"},{"q":"8","answer":"D","options":["sells","breaks","loses","connects"],"explanation":"connects me to the past 把我和过去相连。"},{"q":"9","answer":"A","options":["years","minutes","metres","seconds"],"explanation":"thousands of years 数千年。"},{"q":"10","answer":"B","options":["shop","art","game","city"],"explanation":"an ancient art 古老的艺术。"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required1', 'U5', 'A Funny Misunderstanding', 'Last week my American friend Tom and I had a funny (1)____. I told him I needed to buy some ''pants'', and he started to (2)____. In American English, ''pants'' means trousers, but I had learned the (3)____ in British English, where it means underwear! When we finally (4)____ the mix-up, we both laughed. Tom explained that British and American English often use different (5)____ for the same thing. For example, the British say ''petrol'' while Americans say ''gas'', and a British ''flat'' is an American (6)____. These are not (7)____; they are just two ways of speaking the same (8)____. Now, whenever I am not (9)____ what someone means, I simply ask, "Sorry, what do you mean by that?" Being willing to (10)____ has saved me from many funny mistakes.', 131, 2, '[{"q":"1","answer":"C","options":["holiday","machine","misunderstanding","market"],"explanation":"a funny misunderstanding 有趣的误会。"},{"q":"2","answer":"D","options":["cry","sleep","leave","laugh"],"explanation":"start to laugh 开始笑。"},{"q":"3","answer":"A","options":["word","price","song","game"],"explanation":"learned the word 学的词。"},{"q":"4","answer":"B","options":["forgot","understood","sold","lost"],"explanation":"understood the mix-up 弄懂误会。"},{"q":"5","answer":"C","options":["prices","noises","words","tickets"],"explanation":"different words 不同的词。"},{"q":"6","answer":"D","options":["garden","stadium","castle","apartment"],"explanation":"American apartment 美式公寓。"},{"q":"7","answer":"A","options":["mistakes","songs","prices","games"],"explanation":"not mistakes 不是错误。"},{"q":"8","answer":"B","options":["food","language","city","machine"],"explanation":"the same language 同一种语言。"},{"q":"9","answer":"C","options":["rich","late","sure","busy"],"explanation":"not sure 不确定。"},{"q":"10","answer":"D","options":["hide","forget","leave","ask"],"explanation":"willing to ask 愿意询问。"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required1', 'U5', 'Improving My Spoken English', 'My biggest (1)____ with English used to be speaking politely. It is easy to say "Open the window", but in English that can sound quite (2)____. So I had to learn to (3)____ between "Open the window, please" and "Would you mind opening the window?" My friend Li Rui told me that the right choice (4)____ on who you are talking to. With a close friend, a few short words are (5)____; but with someone you do not know well, a longer, more polite (6)____ is better. To practise, I listen to English radio every day to get (7)____ to how fast native speakers talk. Sometimes I even (8)____ my own voice and compare it with the host''s. Step by step, my speaking has (9)____, and I feel much more (10)____ when I talk to foreign visitors now.', 138, 2, '[{"q":"1","answer":"A","options":["trouble","song","price","game"],"explanation":"biggest trouble 最大困难。"},{"q":"2","answer":"B","options":["polite","rude","happy","quiet"],"explanation":"sound rude 听起来无礼。"},{"q":"3","answer":"C","options":["sleep","sell","choose","lose"],"explanation":"choose between 在……之间选择。"},{"q":"4","answer":"D","options":["sells","breaks","leaves","depends"],"explanation":"depends on 取决于。"},{"q":"5","answer":"A","options":["enough","wrong","empty","late"],"explanation":"are enough 就够了。"},{"q":"6","answer":"B","options":["noise","request","price","game"],"explanation":"a polite request 礼貌的请求。"},{"q":"7","answer":"C","options":["lost","afraid","used","tired"],"explanation":"get used to 习惯于。"},{"q":"8","answer":"D","options":["throw","sell","hide","record"],"explanation":"record my own voice 录下声音。"},{"q":"9","answer":"A","options":["improved","stopped","failed","disappeared"],"explanation":"has improved 提高了。"},{"q":"10","answer":"B","options":["afraid","confident","bored","sorry"],"explanation":"more confident 更自信。"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (10, 'required1', 'U5', 'How Writing United China', 'Long ago, China was a land (1)____ people were divided by mountains and rivers. Different regions spoke different (2)____, and they could not easily understand one another''s speech. However, there was one thing they (3)____: their written characters. No matter (4)____ a person lived, the same character carried the same (5)____. This is the main reason (6)____ written Chinese became so important. When Emperor Qinshihuang (7)____ the country, he made the writing system develop in one (8)____, which helped to bring the people together. Even today, written Chinese is a (9)____ by which the past and the present are connected. People can still read works that were (10)____ thousands of years ago, and in this way the long story of Chinese culture continues.', 123, 2, '[{"q":"1","answer":"C","options":["which","when","where","why"],"explanation":"a land where 地点先行词用 where。"},{"q":"2","answer":"D","options":["foods","songs","games","dialects"],"explanation":"different dialects 不同方言。"},{"q":"3","answer":"A","options":["shared","lost","sold","broke"],"explanation":"one thing they shared 共有的。"},{"q":"4","answer":"B","options":["what","where","who","which"],"explanation":"no matter where 不论在哪里。"},{"q":"5","answer":"C","options":["price","noise","meaning","weather"],"explanation":"the same meaning 相同的意义。"},{"q":"6","answer":"D","options":["which","where","when","why"],"explanation":"the reason why 原因。"},{"q":"7","answer":"A","options":["unified","left","sold","lost"],"explanation":"unified the country 统一国家。"},{"q":"8","answer":"B","options":["garden","direction","market","machine"],"explanation":"in one direction 朝一个方向。"},{"q":"9","answer":"C","options":["price","noise","means","game"],"explanation":"a means by which 一种途径。"},{"q":"10","answer":"D","options":["eaten","sold","thrown","written"],"explanation":"works that were written 被写下的作品。"}]'::jsonb, 6);

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE volume='required1' AND unit='U5';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·对话 Which Language to Learn', '必修一 U5 · dialogue', 3, 'Amy: What foreign language do you want to study, Ben?
Ben: I really want to study French. I think it sounds beautiful.
Amy: Why French? Do you want to go to France one day?
Ben: Yes, and French is used by many international organisations.
Amy: That''s true. I''d like to learn Russian myself.
Ben: Russian? Why is that?
Amy: My father does business with Russians, so I can help him.
Ben: That''s a great reason. Good luck with it!', 'Amy 问 Ben 想学哪门外语;Ben 想学法语,觉得好听;因为想去法国、且许多国际组织用法语;Amy 想学俄语;因为父亲和俄罗斯人做生意,她可以帮忙。', 'uk_female', '[{"q":"Which language does Ben want to study?","type":"choice","answer":"A","options":["French.","Russian.","German.","Japanese."]},{"q":"Why does Ben like that language?","type":"choice","answer":"B","options":["It is the easiest to spell.","He thinks it sounds beautiful.","It has the most speakers.","His teacher chose it."]},{"q":"Which language does Amy want to learn?","type":"choice","answer":"A","options":["Russian.","French.","Arabic.","Korean."]},{"q":"Why does Amy want to learn it?","type":"choice","answer":"B","options":["To watch cartoons.","Her father does business with Russians.","To travel to France.","Because it is required at school."]},{"q":"What is one extra reason Ben gives for his choice?","type":"choice","answer":"C","options":["It is spoken only in France.","No one else speaks it.","Many international organisations use it.","It has no grammar."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·短文 Languages of the World', '必修一 U5 · passage', 2, 'There are about seven thousand languages in the world today.
Chinese and English have the most native speakers.
The official languages of the United Nations are spoken by billions of people.
People study a foreign language for many different reasons.
Learning one opens a door to a new way of thinking.', '当今世界约有七千种语言;汉语和英语母语者最多;联合国官方语言被数十亿人使用;人们学外语原因各异;学一门语言会打开通往新思维方式的大门。', 'uk_female', '[{"q":"About how many languages are there in the world?","type":"choice","answer":"D","options":["About seventy.","About seven million.","Only two.","About seven thousand."]},{"q":"Which two languages have the most native speakers?","type":"choice","answer":"A","options":["Chinese and English.","French and German.","Russian and Arabic.","Korean and Japanese."]},{"q":"Who speaks the UN''s official languages?","type":"choice","answer":"B","options":["Only a few people.","Billions of people.","Nobody today.","Only students."]},{"q":"Why do people study a foreign language?","type":"choice","answer":"C","options":["For only one reason.","Because they are forced to.","For many different reasons.","To forget their own language."]},{"q":"What does learning a language open, according to the passage?","type":"choice","answer":"D","options":["A shop.","A window to the past only.","A box of money.","A door to a new way of thinking."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·对话 A Word with Two Meanings', '必修一 U5 · dialogue', 3, 'Zhou Wei: I really need to buy some pants today.
Martin: Pants? That''s funny. I don''t usually shop for pants with friends.
Zhou Wei: You don''t? Don''t you want someone to tell you if they look good?
Martin: Wait, do you mean trousers, the ones we wear on our legs?
Zhou Wei: Yes! That''s American English for trousers.
Martin: Ah, I see. In British English, ''pants'' means underwear.
Zhou Wei: Oh! No wonder you looked surprised.
Martin: Don''t worry. It''s just two ways of speaking the same language.', '周伟说要买 pants;Martin 觉得好笑;原来周伟说的是美式英语里的''裤子'';而英式英语里 pants 指内裤;两人弄懂这只是同一语言的两种说法。', 'uk_female', '[{"q":"What did Zhou Wei want to buy?","type":"choice","answer":"A","options":["Trousers (he called them ''pants'').","A pair of shoes.","A new book.","Some food."]},{"q":"Why did Martin find it funny at first?","type":"choice","answer":"B","options":["He had no money.","He thought ''pants'' meant underwear.","He did not like Zhou Wei.","He could not hear well."]},{"q":"In American English, what does ''pants'' mean?","type":"choice","answer":"C","options":["Underwear.","Shoes.","Trousers.","A hat."]},{"q":"In British English, what does ''pants'' mean?","type":"choice","answer":"D","options":["Trousers.","A coat.","Socks.","Underwear."]},{"q":"How does Martin explain the difference?","type":"choice","answer":"A","options":["It is two ways of speaking the same language.","One of them is wrong.","Zhou Wei made a mistake.","English is too hard."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·短文 The Chinese Writing System', '必修一 U5 · passage', 2, 'Written Chinese began thousands of years ago as simple pictures.
Ancient people carved symbols onto animal bones and shells.
By the Shang Dynasty, these became a complete writing system.
No matter what dialect people speak, they can read the same characters.
In this way, written Chinese has helped to unite the people.', '汉字数千年前始于简单的图画;古人把符号刻在动物骨头和龟甲上;到商朝已成完整书写系统;不论说什么方言,人们都能读同样的字;这样汉字帮助团结了人民。', 'uk_female', '[{"q":"What did written Chinese begin as?","type":"choice","answer":"B","options":["Spoken sounds only.","Simple pictures.","Foreign words.","Modern letters."]},{"q":"Where did ancient people carve the symbols?","type":"choice","answer":"C","options":["On paper books.","On metal coins.","On animal bones and shells.","On glass."]},{"q":"By which dynasty had it become a complete system?","type":"choice","answer":"D","options":["The Tang Dynasty.","The Ming Dynasty.","No dynasty.","The Shang Dynasty."]},{"q":"Who can read the same characters?","type":"choice","answer":"A","options":["People who speak different dialects.","Only one region.","Only scholars.","Only foreigners."]},{"q":"What has written Chinese helped to do?","type":"choice","answer":"B","options":["Divide the people.","Unite the people.","End all dialects.","Replace speaking."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·对话 Advice on Learning English', '必修一 U5 · dialogue', 3, 'Wang Le: I have so much trouble with my listening. Any advice?
Jia Xin: Try listening to English radio every day.
Wang Le: Does that really help?
Jia Xin: Yes. It helps you get used to how fast native speakers talk.
Wang Le: That''s a good idea. What else can I do?
Jia Xin: Record your own voice and compare it with the speaker''s.
Wang Le: I see. So I can hear my own mistakes.
Jia Xin: Exactly. Little by little, your listening will improve.', '王乐听力困难求建议;佳欣建议每天听英语广播;能帮助习惯母语者语速;还建议录下自己声音和原声比较,听出自己的错误;一点点听力就会进步。', 'uk_female', '[{"q":"What problem does Wang Le have?","type":"choice","answer":"C","options":["Trouble with writing.","Trouble with reading.","Trouble with listening.","Trouble with spelling."]},{"q":"What is Jia Xin''s first piece of advice?","type":"choice","answer":"D","options":["Stop studying English.","Only read silently.","Watch films with no sound.","Listen to English radio every day."]},{"q":"How does that advice help?","type":"choice","answer":"A","options":["It helps you get used to native speakers'' speed.","It saves money.","It makes English easier to spell.","It teaches new grammar rules."]},{"q":"What is the second piece of advice?","type":"choice","answer":"B","options":["Speak only Chinese.","Record your voice and compare it.","Never listen to others.","Read the dictionary."]},{"q":"What will happen little by little?","type":"choice","answer":"C","options":["Wang Le will give up.","His English will get worse.","His listening will improve.","Nothing will change."]}]'::jsonb, '[]'::jsonb, 'long', 'required1', 'U5');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (10, 'U5 听力·短文 A Tip for Language Learners', '必修一 U5 · passage', 2, 'Here is a simple tip for anyone learning a new language.
Do not be afraid to make mistakes when you speak.
Every mistake is a chance to learn something new.
If you are not sure what a word means, just ask politely.
A few brave words today can open many doors tomorrow.', '给学新语言的人一个小贴士:说话时别怕犯错;每个错误都是学新东西的机会;不确定词义就礼貌地问;今天几句勇敢的话,明天能打开许多扇门。', 'uk_female', '[{"q":"Who is this tip for?","type":"choice","answer":"D","options":["Only teachers.","Only children.","Only native speakers.","Anyone learning a new language."]},{"q":"What does the speaker say about making mistakes?","type":"choice","answer":"A","options":["Do not be afraid of them.","Never speak at all.","Mistakes are useless.","Avoid speaking to anyone."]},{"q":"What is every mistake, according to the passage?","type":"choice","answer":"B","options":["A reason to quit.","A chance to learn something new.","A waste of time.","A serious problem."]},{"q":"What should you do if unsure of a word''s meaning?","type":"choice","answer":"C","options":["Pretend to understand.","Stop the conversation.","Just ask politely.","Speak only Chinese."]},{"q":"What can a few brave words today do?","type":"choice","answer":"D","options":["Cost a lot of money.","Make people angry.","Waste your time.","Open many doors tomorrow."]}]'::jsonb, '[]'::jsonb, 'short', 'required1', 'U5');

-- ===== 6) 写作 1篇(旅行邮件) =====
DELETE FROM public.junior_writing_prompts WHERE volume='required1' AND unit='U5';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit) VALUES (10, 'Write a Blog about English Study(写一篇英语学习博客)', 'A Travel Email', '假设你叫李华,你常逛一个中国学生学英语的论坛。请用英语写一篇约80词的博客,内容包括:① 清楚描述你在学英语时遇到的一个困难(如听力/口语礼貌/词汇);② 给出一两条解决这个困难的方法;③ 鼓励有同样困难的同学。注意:每句都要围绕中心、用代词正确指代。', 'Suppose you are Li Hua. You often visit a forum where Chinese students discuss learning English. Write a blog (about 80 words) including: 1) a clear description of one problem you have in learning English (e.g. listening, being polite, vocabulary); 2) one or two ways to solve it; 3) some encouragement for classmates with the same problem.', '["清楚描述困难(My biggest problem is … / I have trouble with …)","解决方法(One thing that works for me is … / You might try …)","鼓励同学(Don''t give up — it gets easier!)","每句围绕中心、代词指代清楚"]'::jsonb, 70, 100, 'Hi everyone! My biggest problem in learning English is listening. When native speakers talk fast, I can catch only a few words and miss the main idea. One thing that really works for me is listening to English radio every day, so I get used to the speed. I also record my own voice and compare it with the speaker''s, which helps me hear my mistakes. If you have the same problem, don''t give up — little by little, it gets much easier. We can all improve together!', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["My biggest problem in learning English is listening.","One thing that really works for me is listening to English radio every day.","I record my own voice and compare it with the speaker''s, which helps me hear my mistakes.","Little by little, it gets much easier."]'::jsonb, '[{"wrong":"I have trouble in listening.","correct":"I have trouble with listening.","note":"have trouble with sth 固定搭配。"},{"wrong":"The radio help me a lot.","correct":"The radio helps me a lot.","note":"主语第三人称单数,动词加 s。"},{"wrong":"It is a way which I can improve.","correct":"It is a way in which I can improve.","note":"way 后从句缺方式状语,用 in which / that / 省略。"}]'::jsonb, '【英语学习博客结构】
第1句 描述困难:My biggest problem is …
第2-3句 方法:One thing that works for me is … I also … , which helps me …
第4句 鼓励:If you have the same problem, don''t give up — it gets easier!', 2, 'required1', 'U5');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE volume='required1' AND unit='U5';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content) VALUES (10, 'required1', 'U5', '{"title":"限制性定语从句·关系副词 when / where / why 速查","intro":"关系副词在从句中作状语(时间/地点/原因),等于「介词+which」。判断口诀:从句缺状语→用关系副词,缺主语/宾语→用关系代词 that/which。","table":{"headers":["关系副词","用法 / 例句 / 等价"],"rows":[["when","时间先行词(day/time/year):the day when = on/in which"],["where","地点先行词(place/country/room):the place where = in/at which"],["why","原因(reason):the reason why = for which"],["介词+which","从句缺主宾、或表达更正式:on which / in which / by which"]]},"specialRules":[{"rule":"从句只缺状语(时间/地点/原因)→ 才用关系副词","mark":"the day when I arrived(缺时间状语)"},{"rule":"从句缺主语/宾语 → 即使先行词是时间/地点也用 that/which","mark":"the day that changed my life(缺主语→that)"},{"rule":"the day when = on/in which;the place where = in/at which;the reason why = for which","mark":"等价替换"},{"rule":"介词后只能用 which,不可用 that","mark":"on which √ / on that ×"}],"why":["关系副词 = 介词 + which,在从句里充当状语,所以从句的主语、宾语都不缺;一旦主语或宾语缺了,就要换成关系代词 that/which。"],"gaokaoPoints":["when/where/why 与 which/that 的判断(看从句缺什么成分);介词+which;语法填空高频。","the way 后的定语从句:用 that / in which / 或省略,但不用 which 单独引导。"],"examVsReal":[{"exam":"the house where I live（考试/书面）","real":"the house I live in","note":"考试用 where;口语常省略关系词、把介词放句末"},{"exam":"the reason why he gave up（考试）","real":"the reason he gave up / the reason that he gave up","note":"考试用 why;口语里 why 常被省略或用 that"}]}'::jsonb);

COMMIT;

-- ===== 自带校验(跑完一眼确认) =====
SELECT 'vocab' k, count(*) v, 44 expect FROM public.junior_vocab WHERE volume='required1' AND unit='U5'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='required1' AND unit='U5'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='required1' AND unit='U5'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='required1' AND unit='U5'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='required1' AND unit='U5'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE volume='required1' AND unit='U5' ORDER BY k;
-- 分布校验:语法/阅读/完形/听力答案分布(应均匀)
SELECT 'grammar' rel, correct_answer ans, count(*) FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE volume='required1' AND unit='U5') GROUP BY 2 ORDER BY 2;
