-- ============================================================
-- 上外(sufe) 必修一 U1(Nature)灌库(junior_* 表,publisher='sufe' volume='required2' unit='U1' grade=10)。幂等。
-- ★DELETE 全带 publisher='sufe',绝不动人教。Aaron service role 跑。
-- ============================================================
BEGIN;

-- ===== 1) 词汇 46 =====
DELETE FROM public.junior_vocab WHERE publisher='sufe' AND volume='required2' AND unit='U1';
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'nature', 'n.', '/ˈneɪtʃə(r)/', '自然;大自然;本性', 'We should learn to live in harmony with nature.', '我们应该学会与大自然和谐相处。', 'Nature', 1, 0, 'senior', 'wordlist', 'required2', 'U1', 'the balance of nature', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'native', 'adj.', '/ˈneɪtɪv/', '原产于某地的;土生的;当地的', 'These flowers are native to this part of the world.', '这些花原产于世界的这一带。', 'Nature', 2, 0, 'senior', 'wordlist', 'required2', 'U1', 'native plants', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'rare', 'adj.', '/reə(r)/', '稀有的;珍贵的;稀少的', 'Many rare plants only grow in this forest.', '许多稀有植物只生长在这片森林里。', 'Nature', 3, 0, 'senior', 'wordlist', 'required2', 'U1', 'a rare species', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'insect', 'n.', '/ˈɪnsekt/', '昆虫', 'Tiny insects help the flowers grow in the garden.', '小昆虫帮助花园里的花生长。', 'Nature', 4, 0, 'senior', 'wordlist', 'required2', 'U1', 'tiny insects', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'balance', 'n.', '/ˈbæləns/', '平衡;均衡;均势', 'Every creature plays a part in the balance of nature.', '每一种生物都在自然的平衡中发挥作用。', 'Nature', 5, 0, 'senior', 'wordlist', 'required2', 'U1', 'keep the balance', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'destroy', 'v.', '/dɪˈstrɔɪ/', '摧毁;毁灭;破坏', 'People should not destroy the homes of wild animals.', '人们不应该破坏野生动物的家园。', 'Nature', 6, 0, 'senior', 'wordlist', 'required2', 'U1', 'destroy the forest', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'delicate', 'adj.', '/ˈdelɪkət/', '易损的;脆弱的;精巧的', 'The balance of nature is delicate and easy to break.', '自然的平衡很脆弱,容易被打破。', 'Nature', 7, 0, 'senior', 'wordlist', 'required2', 'U1', 'a delicate balance', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'damage', 'v./n.', '/ˈdæmɪdʒ/', '损害;破坏;损坏', 'We are damaging the natural world far too fast.', '我们破坏自然界的速度太快了。', 'Nature', 8, 0, 'senior', 'wordlist', 'required2', 'U1', 'damage the environment', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'beyond', 'prep.', '/bɪˈjɒnd/', '超出;在……较远的一边', 'Some damage to nature may soon be beyond repair.', '对自然的某些破坏可能很快就无法修复了。', 'Nature', 9, 0, 'senior', 'wordlist', 'required2', 'U1', 'beyond repair', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'generation', 'n.', '/ˌdʒenəˈreɪʃn/', '一代人;一代', 'We must protect nature for future generations.', '我们必须为子孙后代保护大自然。', 'Nature', 10, 0, 'senior', 'wordlist', 'required2', 'U1', 'future generations', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'preserve', 'v.', '/prɪˈzɜːv/', '保护;保存;维护', 'It is our duty to preserve wild forests and rivers.', '保护原始森林和河流是我们的责任。', 'Nature', 11, 0, 'senior', 'wordlist', 'required2', 'U1', 'preserve nature', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'appreciate', 'v.', '/əˈpriːʃieɪt/', '欣赏;重视;领会;感激', 'Learn to appreciate the beauty all around us in nature.', '学会欣赏我们身边大自然的美。', 'Nature', 12, 0, 'senior', 'wordlist', 'required2', 'U1', 'appreciate the beauty', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'transform', 'v.', '/trænsˈfɔːm/', '使改变形态;使转变', 'Snow can transform a familiar landscape into a white wonderland.', '雪能把熟悉的景色变成银白的仙境。', 'Nature', 13, 0, 'senior', 'wordlist', 'required2', 'U1', 'transform the landscape', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'familiar', 'adj.', '/fəˈmɪliə(r)/', '熟悉的;通晓的;常见的', 'The hill near my home is a familiar sight to me.', '我家附近的小山对我来说是熟悉的景象。', 'Nature', 14, 0, 'senior', 'wordlist', 'required2', 'U1', 'a familiar view', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'landscape', 'n.', '/ˈlændskeɪp/', '风景;景色;乡村风景画', 'The painter loved to draw the landscape of the countryside.', '这位画家喜欢画乡村的风景。', 'Nature', 15, 0, 'senior', 'wordlist', 'required2', 'U1', 'a beautiful landscape', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'affect', 'v.', '/əˈfekt/', '影响;对……产生作用', 'The weather can deeply affect the way we feel.', '天气会深深影响我们的感受。', 'Nature', 16, 0, 'senior', 'wordlist', 'required2', 'U1', 'affect our moods', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'mood', 'n.', '/muːd/', '情绪;心情', 'A sunny morning often puts me in a good mood.', '阳光明媚的早晨常让我心情很好。', 'Nature', 17, 0, 'senior', 'wordlist', 'required2', 'U1', 'a cheerful mood', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'responsible', 'adj.', '/rɪˈspɒnsəbl/', '作为原因的;有责任的;负责的', 'Nature is responsible for the sun, rain and snow.', '自然带来了阳光、雨水和雪。', 'Nature', 18, 0, 'senior', 'wordlist', 'required2', 'U1', 'be responsible for', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'romantic', 'adj.', '/rəʊˈmæntɪk/', '浪漫的;富有情调的;美妙的', 'The moonlight over the lake made the night feel romantic.', '湖面上的月光让这个夜晚显得很浪漫。', 'Nature', 19, 0, 'senior', 'wordlist', 'required2', 'U1', 'a romantic night', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'frozen', 'adj.', '/ˈfrəʊzn/', '冻硬的;冰冻的;冷冻的', 'In spring a small flower pushes through the frozen ground.', '春天里,一朵小花从冻硬的土地中钻出。', 'Nature', 20, 0, 'senior', 'wordlist', 'required2', 'U1', 'the frozen ground', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'aware', 'adj.', '/əˈweə(r)/', '知道的;意识到的;明白的', 'Becoming more aware of nature can change our lives.', '更多地留意自然能够改变我们的生活。', 'Nature', 21, 0, 'senior', 'wordlist', 'required2', 'U1', 'be aware of', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'positive', 'adj.', '/ˈpɒzətɪv/', '积极的;乐观的;自信的', 'Time in nature has a positive effect on our minds.', '亲近自然对我们的心灵有积极的影响。', 'Nature', 22, 0, 'senior', 'wordlist', 'required2', 'U1', 'a positive effect', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'cruel', 'adj.', '/ˈkruːəl/', '残酷的;残忍的;引起痛苦的', 'Some people think it is cruel to keep animals in cages.', '有些人认为把动物关在笼子里很残忍。', 'Nature', 23, 0, 'senior', 'wordlist', 'required2', 'U1', 'cruel to animals', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'debate', 'v./n.', '/dɪˈbeɪt/', '讨论;辩论;争论', 'We often debate whether zoos are good for animals.', '我们常常争论动物园对动物是否有益。', 'Nature', 24, 0, 'senior', 'wordlist', 'required2', 'U1', 'debate the issue', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'establishment', 'n.', '/ɪˈstæblɪʃmənt/', '机构;大型机关;企业', 'Many people do not support these establishments at all.', '许多人根本不支持这些机构。', 'Nature', 25, 0, 'senior', 'wordlist', 'required2', 'U1', 'support the establishment', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'welfare', 'n.', '/ˈwelfeə(r)/', '幸福;福祉;安康', 'Animal welfare is a growing concern in our society.', '动物福利在我们的社会中越来越受关注。', 'Nature', 26, 0, 'senior', 'wordlist', 'required2', 'U1', 'animal welfare', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'concern', 'n.', '/kənˈsɜːn/', '担心;忧虑;关切', 'The future of wild tigers is a serious concern.', '野生老虎的未来令人深感忧虑。', 'Nature', 27, 0, 'senior', 'wordlist', 'required2', 'U1', 'a growing concern', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'argue', 'v.', '/ˈɑːɡjuː/', '论证;主张;争辩', 'Some people argue that zoos are cruel to animals.', '有些人认为动物园对动物很残忍。', 'Nature', 28, 0, 'senior', 'wordlist', 'required2', 'U1', 'argue that', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'remove', 'v.', '/rɪˈmuːv/', '移开;拿走;去除', 'It is wrong to remove animals from their natural homes.', '把动物从它们的自然家园中带走是不对的。', 'Nature', 29, 0, 'senior', 'wordlist', 'required2', 'U1', 'remove animals from', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'habitat', 'n.', '/ˈhæbɪtæt/', '生活环境;栖息地', 'Each animal has its own natural habitat in the wild.', '每种动物在野外都有自己的天然栖息地。', 'Nature', 30, 0, 'senior', 'wordlist', 'required2', 'U1', 'natural habitat', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'cage', 'n.', '/keɪdʒ/', '笼子', 'A bird kept in a cage cannot fly freely.', '关在笼子里的鸟不能自由飞翔。', 'Nature', 31, 0, 'senior', 'wordlist', 'required2', 'U1', 'kept in a cage', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'hunt', 'v.', '/hʌnt/', '打猎;猎取;搜寻', 'Wild animals must hunt for food every single day.', '野生动物每天都必须觅食。', 'Nature', 32, 0, 'senior', 'wordlist', 'required2', 'U1', 'hunt for food', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'additionally', 'adv.', '/əˈdɪʃənəli/', '另外;此外', 'Additionally, some animals become unhappy in small spaces.', '此外,有些动物在狭小的空间里会变得不快乐。', 'Nature', 33, 0, 'senior', 'wordlist', 'required2', 'U1', 'additionally, ...', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'exhibit', 'v.', '/ɪɡˈzɪbɪt/', '展览;展出;表现出', 'Zoos exhibit animals from all over the world.', '动物园展出来自世界各地的动物。', 'Nature', 34, 0, 'senior', 'wordlist', 'required2', 'U1', 'exhibit animals', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'adjust', 'v.', '/əˈdʒʌst/', '适应;调整;调节', 'Animals must adjust to different climates and seasons.', '动物必须适应不同的气候和季节。', 'Nature', 35, 0, 'senior', 'wordlist', 'required2', 'U1', 'adjust to', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'climate', 'n.', '/ˈklaɪmət/', '气候', 'Some plants only flourish in a warm and wet climate.', '有些植物只在温暖潮湿的气候中茁壮生长。', 'Nature', 36, 0, 'senior', 'wordlist', 'required2', 'U1', 'a warm climate', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'location', 'n.', '/ləʊˈkeɪʃn/', '地点;位置;场所', 'The zoo''s location decides which animals can live there.', '动物园的位置决定了哪些动物能在那里生活。', 'Nature', 37, 0, 'senior', 'wordlist', 'required2', 'U1', 'a perfect location', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'design', 'v./n.', '/dɪˈzaɪn/', '设计;构思;意欲', 'Workers design the park to look like a real habitat.', '工人们把公园设计得像真正的栖息地。', 'Nature', 38, 0, 'senior', 'wordlist', 'required2', 'U1', 'design a park', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'extinction', 'n.', '/ɪkˈstɪŋkʃn/', '灭绝;绝种;消亡', 'Many rare animals are now close to extinction.', '许多稀有动物如今濒临灭绝。', 'Nature', 39, 0, 'senior', 'wordlist', 'required2', 'U1', 'save from extinction', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'conservation', 'n.', '/ˌkɒnsəˈveɪʃn/', '(对自然环境的)保护', 'Conservation helps to keep the whole ecosystem healthy.', '环境保护有助于保持整个生态系统的健康。', 'Nature', 40, 0, 'senior', 'wordlist', 'required2', 'U1', 'wildlife conservation', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'essential', 'adj.', '/ɪˈsenʃl/', '必不可少的;极其重要的', 'Clean water is essential for every living thing.', '清洁的水对每一个生物都必不可少。', 'Nature', 41, 0, 'senior', 'wordlist', 'required2', 'U1', 'an essential part', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'threat', 'n.', '/θret/', '威胁;构成威胁的事物', 'Pollution is a serious threat to wild plants and animals.', '污染对野生动植物构成严重威胁。', 'Nature', 42, 0, 'senior', 'wordlist', 'required2', 'U1', 'a threat to nature', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'particularly', 'adv.', '/pəˈtɪkjələli/', '特别;尤其', 'These trees grow particularly well in warm valleys.', '这些树在温暖的山谷里长得特别好。', 'Nature', 43, 0, 'senior', 'wordlist', 'required2', 'U1', 'particularly important', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'exist', 'v.', '/ɪɡˈzɪst/', '存在;生存', 'Thousands of species exist together in this forest.', '成千上万的物种共同生存在这片森林里。', 'Nature', 44, 0, 'senior', 'wordlist', 'required2', 'U1', 'exist in nature', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'species', 'n.', '/ˈspiːʃiːz/', '物种;种类', 'Losing one species can put many others in danger.', '失去一个物种会让许多其他物种陷入危险。', 'Nature', 45, 0, 'senior', 'wordlist', 'required2', 'U1', 'different species', NULL, 'sufe');
INSERT INTO public.junior_vocab (grade, word, pos, phonetic, meaning_cn, example_en, example_cn, theme, freq_rank, star_level, stage, source_type, volume, unit, phrase_en, tip, publisher) VALUES (10, 'restore', 'v.', '/rɪˈstɔː(r)/', '恢复;修复;使复原', 'It takes many years to restore the balance of nature.', '恢复自然的平衡需要很多年。', 'Nature', 46, 0, 'senior', 'wordlist', 'required2', 'U1', 'restore nature', NULL, 'sufe');

-- ===== 2) 语法 3点/60题 =====
DELETE FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1');
DELETE FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1';
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s2u1.01', '①who / whom(指人)', 'A2', 10, '上外版必修第二册 U1 — 先行词指人:从句缺主语用 who;从句缺宾语用 whom(口语/非正式也可 who),不可用 which。', 1, 'required2', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s2u1.02', '②which / that(指物)', 'A2', 10, '上外版必修第二册 U1 — 先行词指物(限制性定语从句):缺主语或宾语用 which 或 that,不可用 who/whose。', 2, 'required2', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_points (code, title, cefr, grade, summary, sort_order, volume, unit, category_id, examples, content_depth, publisher) VALUES ('s2u1.03', '③whose(所属)· 介词 + which / whom', 'A2', 10, '上外版必修第二册 U1 — 表所属关系(……的)用 whose + 名词,指人指物皆可;关系词作介词宾语提前时,指物用「介词+which」、指人用「介词+whom」,介词后不可用 that。', 3, 'required2', 'U1', (SELECT id FROM public.junior_grammar_categories WHERE code='senior' LIMIT 1), '[]'::jsonb, 0, 'sufe');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The young man ____ explained the mystery had grown up near the king''s gardens.', 'who', 'which', 'whose', 'where', 'A', '先行词 man 指人、从句缺主语 → who。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'It was a wise nobleman ____ first noticed that the gardens were empty.', 'which', 'who', 'whom', 'whose', 'B', '先行词 nobleman 指人、从句缺主语 → who。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'People ____ love nature often feel calm when they walk in a forest.', 'which', 'whose', 'who', 'where', 'C', '先行词 people 指人、从句缺主语 → who。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'Scientists ____ study wild animals warn us about the loss of species.', 'which', 'whose', 'where', 'who', 'D', '先行词 scientists 指人、从句缺主语 → who。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The farmer ____ planted the old tree saved the beauty of the gardens.', 'who', 'which', 'whom', 'whose', 'A', '先行词 farmer 指人、从句缺主语 → who。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'Children ____ spend time outdoors learn to care about nature.', 'which', 'who', 'whose', 'where', 'B', '先行词 children 指人、从句缺主语 → who。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The expert ____ the reporter spoke to studies the balance of nature.', 'which', 'whose', 'whom', 'where', 'C', '先行词 expert 指人、从句缺宾语(spoke to ___)→ whom。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The guide ____ we met at the zoo knows every animal by name.', 'which', 'whose', 'where', 'whom', 'D', '先行词 guide 指人、从句缺宾语(met ___)→ whom。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The advisers ____ the king sent for could not solve the problem.', 'whom', 'which', 'whose', 'where', 'A', '先行词 advisers 指人、从句缺宾语(sent for ___)→ whom。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The volunteers ____ work at the park help to protect rare birds.', 'which', 'who', 'whose', 'whom', 'B', '先行词 volunteers 指人、从句缺主语 → who。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'He is the only person ____ truly understands how the forest lives.', 'which', 'where', 'who', 'whose', 'C', '先行词 person 指人、从句缺主语 → who。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The poet ____ many readers admire wrote about the beauty of spring.', 'which', 'where', 'whose', 'whom', 'D', '先行词 poet 指人、从句缺宾语(admire ___)→ whom。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The neighbours ____ care for the woods often plant new trees there.', 'who', 'which', 'whose', 'where', 'A', '先行词 neighbours 指人、从句缺主语 → who。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'A gardener ____ loves plants will treat every flower with care.', 'which', 'who', 'whom', 'whose', 'B', '先行词 gardener 指人、从句缺主语 → who。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The friends ____ I invited to the lake enjoyed watching the wild ducks.', 'which', 'whose', 'whom', 'where', 'C', '先行词 friends 指人、从句缺宾语(invited ___)→ whom。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The students ____ the teacher praised had cleaned up the river bank.', 'which', 'whose', 'where', 'whom', 'D', '先行词 students 指人、从句缺宾语(praised ___)→ whom。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The king listened to the man ____ everyone else had laughed at.', 'whom', 'which', 'whose', 'where', 'A', '先行词 man 指人、从句缺宾语(laughed at ___)→ whom。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The workers ____ built the new park left a space for the trees.', 'which', 'who', 'whose', 'whom', 'B', '先行词 workers 指人、从句缺主语 → who。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'The travellers ____ we guided through the woods saw a family of deer.', 'which', 'where', 'whom', 'whose', 'C', '先行词 travellers 指人、从句缺宾语(guided ___)→ whom。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.01'), 'Anyone ____ destroys a forest may harm the balance of nature.', 'which', 'where', 'whose', 'who', 'D', '先行词 anyone 指人、从句缺主语 → who。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The old tree ____ stood in the middle of the gardens was cut down.', 'which', 'who', 'whom', 'whose', 'A', '先行词 tree 指物、从句缺主语 → which(也可 that)。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The plants ____ grow here are native to this part of the world.', 'who', 'that', 'whom', 'whose', 'B', '先行词 plants 指物、从句缺主语 → that(也可 which)。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The garden ____ the king destroyed could not be restored quickly.', 'who', 'whom', 'which', 'whose', 'C', '先行词 garden 指物、从句缺宾语(destroyed ___)→ which(也可 that)。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The river ____ flows past our town is home to many fish.', 'who', 'whom', 'whose', 'that', 'D', '先行词 river 指物、从句缺主语 → that(也可 which)。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'These are the moths ____ keep the whole garden alive and colourful.', 'which', 'who', 'whom', 'whose', 'A', '先行词 moths 指物、从句缺主语 → which(也可 that)。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The book ____ I read described how nature keeps its balance.', 'who', 'that', 'whom', 'whose', 'B', '先行词 book 指物、从句缺宾语(read ___)→ that(也可 which)。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The forests ____ once covered this area have now been destroyed.', 'who', 'whom', 'which', 'whose', 'C', '先行词 forests 指物、从句缺主语 → which(也可 that)。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The flowers ____ the children picked soon withered in the sun.', 'who', 'whom', 'whose', 'that', 'D', '先行词 flowers 指物、从句缺宾语(picked ___)→ that(也可 which)。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The lake ____ lies beyond the hills freezes hard every winter.', 'which', 'who', 'whom', 'whose', 'A', '先行词 lake 指物、从句缺主语 → which(也可 that)。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The painting ____ shows a snowy landscape hangs in the hall.', 'who', 'that', 'whom', 'whose', 'B', '先行词 painting 指物、从句缺主语 → that(也可 which)。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The seeds ____ the wind carried away grew into tall trees.', 'who', 'whom', 'which', 'whose', 'C', '先行词 seeds 指物、从句缺宾语(carried ___)→ which(也可 that)。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The rare bird ____ we saw at dawn has almost disappeared.', 'who', 'whom', 'whose', 'that', 'D', '先行词 bird 指物(动物)、从句缺宾语(saw ___)→ that(也可 which)。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The fountains ____ replaced the old tree looked beautiful at first.', 'which', 'who', 'whom', 'whose', 'A', '先行词 fountains 指物、从句缺主语 → which(也可 that)。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The story ____ the young man told changed the way the king thought.', 'who', 'that', 'whom', 'whose', 'B', '先行词 story 指物、从句缺宾语(told ___)→ that(也可 which)。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The mountains ____ surround the valley keep it warm in spring.', 'who', 'whom', 'which', 'whose', 'C', '先行词 mountains 指物、从句缺主语 → which(也可 that)。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The food ____ the animals could not find in the zoo was easy to get in the wild.', 'who', 'whom', 'whose', 'that', 'D', '先行词 food 指物、从句缺宾语(find ___)→ that(也可 which)。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The clouds ____ gathered above the sea soon turned the sky grey.', 'which', 'who', 'whom', 'whose', 'A', '先行词 clouds 指物、从句缺主语 → which(也可 that)。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The habitat ____ the new park created saved several rare species.', 'who', 'that', 'whom', 'whose', 'B', '先行词 habitat 指物、从句缺宾语(created ___)→ that(也可 which)。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The wild grass ____ covers the field turns golden in autumn.', 'who', 'whom', 'which', 'whose', 'C', '先行词 grass 指物、从句缺主语 → which(也可 that)。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.02'), 'The photos ____ she took of the sunset filled the whole album.', 'who', 'whom', 'whose', 'that', 'D', '先行词 photos 指物、从句缺宾语(took ___)→ that(也可 which)。', 2, 20, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'The king offered a reward to anyone ____ solution would be effective.', 'whose', 'who', 'which', 'where', 'A', '表所属(……的 solution)→ whose + 名词。', 2, 1, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'We protect animals ____ homes have been destroyed by pollution.', 'who', 'whose', 'which', 'whom', 'B', '表所属(动物的 homes)→ whose + 名词。', 2, 2, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'These were the bones on ____ ancient symbols had been carved.', 'that', 'whom', 'which', 'whose', 'C', '介词 on 后指物 → which(不可用 that)。', 2, 3, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'He is the scientist to ____ the rare plant was first sent.', 'which', 'that', 'who', 'whom', 'D', '介词 to 后指人 → whom。', 2, 4, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'The girl ____ photo of the forest won the prize loves nature.', 'whose', 'who', 'which', 'whom', 'A', '表所属(女孩的 photo)→ whose + 名词。', 2, 5, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'I visited a village ____ people still live close to nature.', 'who', 'whose', 'which', 'that', 'B', '表所属(村庄的 people)→ whose + 名词。', 2, 6, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'Nature is the means by ____ the seasons renew the earth.', 'that', 'whom', 'which', 'whose', 'C', '介词 by 后指物 → which。', 2, 7, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'She is the expert with ____ we discussed the loss of species.', 'which', 'that', 'who', 'whom', 'D', '介词 with 后指人 → whom。', 2, 8, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'It was a tree ____ branches reached high above the garden wall.', 'whose', 'who', 'which', 'whom', 'A', '表所属(树的 branches)→ whose + 名词。', 2, 9, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'We met a farmer ____ land had once been a barren hillside.', 'who', 'whose', 'which', 'that', 'B', '表所属(农夫的 land)→ whose + 名词。', 2, 10, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'This is the river in ____ many kinds of fish make their home.', 'that', 'whom', 'which', 'whose', 'C', '介词 in 后指物 → which。', 2, 11, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'He is the writer for ____ the beauty of nature was a favourite subject.', 'which', 'that', 'who', 'whom', 'D', '介词 for 后指人 → whom。', 2, 12, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'They saved a bird ____ wing had been hurt by a sharp branch.', 'whose', 'who', 'which', 'whom', 'A', '表所属(鸟的 wing)→ whose + 名词。', 2, 13, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'We studied a plant ____ leaves change colour with the climate.', 'who', 'whose', 'which', 'that', 'B', '表所属(植物的 leaves)→ whose + 名词。', 2, 14, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'That is the hill on ____ a clump of wild flowers grows each spring.', 'that', 'whom', 'which', 'whose', 'C', '介词 on 后指物 → which。', 2, 15, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'He is the guide from ____ I learned how the forest keeps its balance.', 'which', 'that', 'who', 'whom', 'D', '介词 from 后指人 → whom。', 2, 16, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'The king destroyed a tree ____ roots had quietly fed the whole garden.', 'whose', 'who', 'which', 'whom', 'A', '表所属(树的 roots)→ whose + 名词。', 2, 17, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'We helped a family ____ garden had been ruined by the storm.', 'who', 'whose', 'which', 'that', 'B', '表所属(一家人的 garden)→ whose + 名词。', 2, 18, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'This is the lake beside ____ the old palace once stood.', 'that', 'whom', 'which', 'whose', 'C', '介词 beside 后指物 → which。', 2, 19, 'mcq');
INSERT INTO public.junior_grammar_questions (point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type) VALUES ((SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1' AND code='s2u1.03'), 'She is the teacher to ____ the children showed their nature drawings.', 'which', 'that', 'who', 'whom', 'D', '介词 to 后指人 → whom。', 2, 20, 'mcq');

-- ===== 3) 阅读 6 篇 =====
DELETE FROM public.junior_reading WHERE publisher='sufe' AND volume='required2' AND unit='U1';
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'The King and His Empty Gardens', 'There once lived a king who had a palace with beautiful gardens. In those gardens lived thousands of creatures of many different kinds. The only thing the king disliked was an old, dry tree standing in the middle. So he had it cut down and put fountains in its place. Some time later, a wise visitor told him that the gardens looked empty, for not a single animal could be seen. The king was shocked to find this was true. He offered a reward to anyone with a solution, but no one could explain the mystery. Years later, a young man arrived. He said the gardens had died because the tree was gone. Every spring, moths had come out of that tree. The moths fed the birds, the birds fed bigger animals, and so all the life in the gardens had been linked together. By removing one old tree, the king had broken the whole chain.', 'Nature', 156, '[{"q":"Why did the king have the old tree cut down?","answer":"A","options":["It was the one thing he did not like in the gardens.","It was blocking the main gate.","A visitor had told him to remove it.","Its branches had fallen on the palace."],"explanation":"原文 ''The only thing the king disliked was an old, dry tree'' 的转述。"},{"q":"What surprising change did the wise visitor point out?","answer":"B","options":["The fountains had stopped working.","No animals could be seen in the gardens any more.","The palace had become too small.","The flowers had grown too tall."],"explanation":"原文 ''the gardens looked empty, for not a single animal could be seen'' 的转述。"},{"q":"According to the young man, what had really caused the problem?","answer":"A","options":["Removing the tree had broken the chain of life.","The king had planted too many fountains.","The weather had suddenly turned cold.","The animals had been frightened by visitors."],"explanation":"末段 ''由 moths→birds→bigger animals 串起整座花园,砍掉一棵树就断了整条链'' 的转述。"}]'::jsonb, '[{"word":"creature","cn":"生物"},{"word":"fountain","cn":"喷泉"},{"word":"moth","cn":"蛾"}]'::jsonb, 2, 'required2', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'How Nature Stays in Balance', 'An environment works best when many different species live in it together. Here is one example from the sea. Green sea turtles love to eat sea grass, but they cannot stay in one spot for too long, because sharks in the area hunt them. Without the sharks, the turtles would eat all the best sea grass, and that grass is the home for many smaller animals. If just one species in this chain disappeared, the others connected to it might be in danger too. So losing a single kind of animal or plant can quietly harm many others. There are possibly billions of species of plants, animals and other living things in the world, but people have only recorded about two million of them. Many of these known and unknown species face an uncertain future. We can help keep the whole system healthy by working to protect every part of it, large or small.', 'Nature', 154, '[{"q":"Why can''t the green sea turtles stay in one place for long?","answer":"B","options":["The sea grass there tastes bad.","Sharks in that area hunt them.","The water is too cold for them.","They need to lay eggs on land."],"explanation":"原文 ''sharks in the area hunt them'' 的转述。"},{"q":"What does the example mainly show about nature?","answer":"C","options":["Sharks are the most important animals in the sea.","Sea grass grows faster than any other plant.","The loss of one species may put many others in danger.","Turtles eat more than any other sea animal."],"explanation":"原文 ''失去一个物种会悄悄伤害许多其他物种'' 的概括。"},{"q":"How many species have people actually recorded so far?","answer":"D","options":["About one billion.","Almost all of them.","Fewer than a thousand.","About two million."],"explanation":"原文 ''recorded about two million of them'' 的转述。"}]'::jsonb, '[{"word":"sea grass","cn":"海草"},{"word":"shark","cn":"鲨鱼"},{"word":"chain","cn":"链条"}]'::jsonb, 2, 'required2', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Nature and Our Feelings', 'Nature does more than fill the world with beauty; it also gently shapes the way we feel. On a bright, sunny morning we often feel cheerful inside, while a grey and rainy sky can leave us feeling low. A starry night with soft moonlight can make us feel calm and even romantic. Because of this, nature can quietly change our plans and our moods without our noticing. There is also beauty everywhere if we slow down to look for it. Nature can set the sky on fire at sunset, or turn a familiar field into a white wonderland after a night of snow. When we see a small flower pushing up through the frozen ground in spring, fresh hope rises in us. The writer believes that learning to be more aware of these changes has a positive effect on our lives. It teaches us to look at things in a kinder way and to feel better about ourselves.', 'Nature', 158, '[{"q":"What does the writer say nature can do besides making the world beautiful?","answer":"A","options":["It can shape the way we feel.","It can make us richer.","It can stop the seasons from changing.","It can teach us to paint."],"explanation":"原文 ''it also gently shapes the way we feel'' 的转述。"},{"q":"How do we often feel on a grey, rainy day?","answer":"B","options":["Cheerful and excited.","Low in spirits.","Calm and romantic.","Full of fresh hope."],"explanation":"原文 ''a grey and rainy sky can leave us feeling low'' 的转述。"},{"q":"According to the writer, what is the effect of becoming more aware of nature?","answer":"C","options":["It makes us forget our problems for ever.","It removes all bad weather.","It improves the way we view the world and ourselves.","It makes the days longer."],"explanation":"末段 ''learning to be more aware… has a positive effect on our lives'' 的转述。"}]'::jsonb, '[{"word":"moonlight","cn":"月光"},{"word":"wonderland","cn":"仙境"},{"word":"sunset","cn":"日落"}]'::jsonb, 2, 'required2', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Zoos: Cruel or Caring?', 'Last weekend I visited a zoo with a friend, and we soon began to debate whether zoos are a good thing. Animal welfare is a growing concern today, and many people argue that zoos are cruel. They say it is wrong to remove animals from their natural habitats and keep them in cages. An animal in a zoo lives a very different life from one in the wild; for example, it never has to hunt for food. Some animals also become unhappy because there is not enough space, and they must adjust to a climate that is not their own. For human visitors, however, a trip to the zoo can be a real chance to learn. Children who may never travel far can still see animals from all over the world. Good modern zoos also help to protect rare species and even bring some back from the edge of extinction. So the question is not simple, and people will go on discussing it for a long time.', 'Nature', 167, '[{"q":"What do people who dislike zoos mainly argue?","answer":"D","options":["Zoos are too expensive to visit.","Zoos are usually too far from cities.","Animals in zoos eat the wrong food.","It is cruel to keep animals away from their natural homes."],"explanation":"原文 ''把动物从栖息地带走、关进笼子是残忍的'' 的转述。"},{"q":"What does the writer say is one good point of zoos for visitors?","answer":"A","options":["They give people, especially children, a chance to learn.","They are always free of charge.","They let people take the animals home.","They are open all night."],"explanation":"原文 ''a trip to the zoo can be a real chance to learn'' 的转述。"},{"q":"What is the writer''s overall view of the question?","answer":"B","options":["Zoos should all be closed at once.","There is no easy answer, and people keep arguing about it.","Zoos are clearly better than the wild.","Only children should be allowed in zoos."],"explanation":"末句 ''the question is not simple… discussing it for a long time'' 的转述。"}]'::jsonb, '[{"word":"welfare","cn":"福利"},{"word":"habitat","cn":"栖息地"},{"word":"extinction","cn":"灭绝"}]'::jsonb, 2, 'required2', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Saving Species from Extinction', 'Around the world, many rare animals and plants are close to extinction. Some are hunted for money, while others lose their homes when forests are cut down or rivers are polluted. Once a species is gone, it can never come back, and the loss often hurts other living things that depend on it. This is why conservation has become so important. Conservation means protecting the natural world so that wild plants and animals can survive. Workers may guard a forest, clean a river, or design a safe park where rare animals can live and breed. Sometimes a few of the last animals of a kind are cared for carefully until their numbers slowly rise again. Scientists also study how each species fits into the balance of nature, because saving one kind of animal often means protecting its whole habitat. By acting in time, people can give threatened species a real chance to survive into the future.', 'Nature', 156, '[{"q":"What is one reason given for animals becoming close to extinction?","answer":"C","options":["They grow too quickly in number.","They move to colder countries.","They are hunted or lose their homes.","They stop eating natural food."],"explanation":"原文 ''被猎杀,或森林被砍、河流被污染而失去家园'' 的转述。"},{"q":"What does conservation mean, according to the passage?","answer":"D","options":["Building more zoos in every city.","Moving all wild animals into parks.","Stopping people from visiting forests.","Protecting nature so wild species can survive."],"explanation":"原文 ''protecting the natural world so that wild plants and animals can survive'' 的转述。"},{"q":"Why does saving one species often mean protecting its habitat?","answer":"A","options":["Every kind of animal has its own place in nature''s balance.","Habitats are cheaper to build than parks.","Animals dislike living near people.","Habitats are easy to move from place to place."],"explanation":"原文 ''each species fits into the balance of nature'' 的转述。"}]'::jsonb, '[{"word":"pollute","cn":"污染"},{"word":"breed","cn":"繁殖"},{"word":"survive","cn":"幸存"}]'::jsonb, 2, 'required2', 'U1', 'sufe');
INSERT INTO public.junior_reading (grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit, publisher) VALUES (10, 'Bringing a Creek Back to Life', 'Not all damage to nature lasts for ever; sometimes people can bring a place back to life. Suzhou Creek in Shanghai is a good example. In the past it was a busy, healthy waterway, full of fish and shrimp. By the 1980s, however, heavy pollution had made the water dark and dirty, and almost all the fish and shrimp had disappeared. The smell was so bad that people living nearby kept their windows closed. Then the city decided to act. Between 1993 and 2008, three large projects were carried out to clean the creek and stop dirty water from flowing in. Slowly the water became clearer, and the living things began to return. Today fish and shrimp can once again be found in the creek, and the people who live along its banks enjoy a much better quality of life. The story shows that with time, money and care, even a badly damaged river can be restored.', 'Nature', 157, '[{"q":"What had happened to Suzhou Creek by the 1980s?","answer":"B","options":["It had become wider than before.","Pollution had killed off almost all its fish and shrimp.","It had completely dried up.","It had been turned into a park."],"explanation":"原文 ''heavy pollution had made the water dark… almost all the fish and shrimp had disappeared'' 的转述。"},{"q":"What did the city do to deal with the problem?","answer":"C","options":["It moved all the residents away.","It filled in the creek with earth.","It carried out three large clean-up projects.","It built a wall around the water."],"explanation":"原文 ''three large projects were carried out to clean the creek'' 的转述。"},{"q":"What main lesson does the story of the creek teach?","answer":"D","options":["Rivers should never be used by people.","Pollution can never really be cleaned up.","Fish and shrimp always come back on their own.","With time and care, even a heavily polluted river can recover."],"explanation":"末句 ''even a badly damaged river can be restored'' 的转述。"}]'::jsonb, '[{"word":"creek","cn":"小河"},{"word":"shrimp","cn":"虾"},{"word":"waterway","cn":"水道"}]'::jsonb, 2, 'required2', 'U1', 'sufe');

-- ===== 4) 完形 6篇/60空 =====
DELETE FROM public.junior_cloze WHERE publisher='sufe' AND volume='required2' AND unit='U1';
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U1', 'A Walk in the Woods', 'Last Sunday my grandfather took me for a long (1)____ in the woods near our village. The morning air was fresh, and tiny (2)____ buzzed quietly among the wild flowers. Grandpa told me to walk slowly and to (3)____ everything around me. He pointed at a (4)____ bird high in a tree and said it was seldom seen these days. He explained that every plant and animal in the forest is (5)____ to the others, like links in a chain. If we (6)____ even one part, he warned, the whole balance could be harmed. I began to feel how (7)____ this living world really was. By the time we walked home, my (8)____ had completely changed; I felt calm and full of (9)____. That quiet walk taught me to (10)____ the beauty of nature far more than before.', 138, 2, '[{"q":"1","answer":"A","options":["walk","song","price","noise"],"explanation":"a long walk 一次长途漫步。"},{"q":"2","answer":"B","options":["machines","insects","letters","prices"],"explanation":"tiny insects 小昆虫。"},{"q":"3","answer":"C","options":["sell","throw","notice","lose"],"explanation":"notice everything 留意周围一切。"},{"q":"4","answer":"D","options":["loud","cheap","round","rare"],"explanation":"a rare bird 一只稀有的鸟。"},{"q":"5","answer":"A","options":["connected","sold","lost","broken"],"explanation":"connected to the others 与其他相连。"},{"q":"6","answer":"B","options":["enjoy","destroy","buy","draw"],"explanation":"destroy one part 破坏一部分。"},{"q":"7","answer":"C","options":["cheap","loud","delicate","empty"],"explanation":"how delicate 多么脆弱。"},{"q":"8","answer":"D","options":["price","machine","ticket","mood"],"explanation":"my mood changed 我的心情变了。"},{"q":"9","answer":"A","options":["hope","anger","fear","noise"],"explanation":"full of hope 充满希望。"},{"q":"10","answer":"B","options":["forget","appreciate","sell","waste"],"explanation":"appreciate the beauty 欣赏美。"}]'::jsonb, 1, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U1', 'My Little Balcony Garden', 'When my family moved to the city, I missed the green fields of my (1)____ village. So I decided to grow a small garden on our (2)____. At first the work was harder than I had (3)____. The young plants were so (4)____ that a strong wind could break them. I had to learn how much water and sunlight each one (5)____. Slowly, green leaves began to (6)____, and one morning I found that a flower had opened. Bees and other small (7)____ soon came to visit, and the balcony felt alive. Caring for these plants taught me how (8)____ nature really is, even in a busy city. Now, whenever I feel tired or sad, I sit by my garden and my (9)____ lifts at once. A few green plants have brought a piece of (10)____ right into my home.', 140, 2, '[{"q":"1","answer":"C","options":["loud","cheap","native","frozen"],"explanation":"native village 故乡的村庄。"},{"q":"2","answer":"D","options":["price","noise","machine","balcony"],"explanation":"on our balcony 在阳台上。"},{"q":"3","answer":"A","options":["expected","sold","lost","thrown"],"explanation":"harder than I had expected 比预想的难。"},{"q":"4","answer":"B","options":["loud","delicate","cheap","round"],"explanation":"so delicate 如此脆弱。"},{"q":"5","answer":"C","options":["sold","lost","needed","broke"],"explanation":"each one needed 各自需要。"},{"q":"6","answer":"D","options":["sell","throw","lose","appear"],"explanation":"leaves began to appear 叶子开始出现。"},{"q":"7","answer":"A","options":["insects","prices","machines","letters"],"explanation":"small insects 小昆虫。"},{"q":"8","answer":"B","options":["loud","essential","cheap","empty"],"explanation":"how essential 多么重要。"},{"q":"9","answer":"C","options":["price","noise","mood","machine"],"explanation":"my mood lifts 心情好起来。"},{"q":"10","answer":"D","options":["money","noise","traffic","nature"],"explanation":"a piece of nature 一片自然。"}]'::jsonb, 2, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U1', 'Shells on the Beach', 'On a warm summer day, my cousin and I went to (1)____ shells along the quiet beach. The waves were gentle, and the soft light at (2)____ turned the whole sky pink and gold. As we walked, we tried not to (3)____ the small crabs that lived in the wet sand. My cousin, who studies the sea, told me that the beach is a kind of (4)____ where many tiny creatures live together. He said that even rubbish left by people can (5)____ these little animals. So we picked up the plastic bags that other visitors had (6)____ behind. It felt good to leave the beach cleaner than we (7)____ it. By keeping the shore clean, he explained, we help to (8)____ the home of all these creatures. That afternoon I learned that even a (9)____ action can make a real difference. Protecting nature, I now believe, is everybody''s (10)____.', 150, 2, '[{"q":"1","answer":"A","options":["collect","sell","throw","lose"],"explanation":"collect shells 捡贝壳。"},{"q":"2","answer":"B","options":["noise","sunset","price","machine"],"explanation":"light at sunset 日落时分的光。"},{"q":"3","answer":"C","options":["buy","sell","harm","draw"],"explanation":"not to harm 不去伤害。"},{"q":"4","answer":"D","options":["price","noise","machine","habitat"],"explanation":"a kind of habitat 一种栖息地。"},{"q":"5","answer":"A","options":["damage","sell","enjoy","draw"],"explanation":"damage these little animals 伤害这些小动物。"},{"q":"6","answer":"B","options":["sold","left","bought","drawn"],"explanation":"left behind 留下。"},{"q":"7","answer":"C","options":["sold","drew","found","threw"],"explanation":"cleaner than we found it 比我们发现时更干净。"},{"q":"8","answer":"D","options":["break","sell","lose","preserve"],"explanation":"preserve the home 保护家园。"},{"q":"9","answer":"A","options":["small","loud","cheap","frozen"],"explanation":"a small action 一个小举动。"},{"q":"10","answer":"B","options":["price","duty","noise","machine"],"explanation":"everybody''s duty 每个人的责任。"}]'::jsonb, 3, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U1', 'The Bird with a Hurt Wing', 'One cold morning I found a small bird lying on the (1)____ ground beneath a tree. One of its wings had been (2)____, and it could not fly. I felt deep (3)____ for the poor creature, so I gently carried it home. My mother helped me to (4)____ a warm box where it could rest. We were (5)____ that it might be too weak to live, but we did our best. Day by day the bird grew stronger, and we were careful not to (6)____ it from its quiet corner too often. We knew that a wild bird should never spend its life in a (7)____. After two weeks, the wing had healed, and the bird could (8)____ its wings again. On a bright afternoon we carried it outside and let it go. Watching it fly back to (9)____ filled me with joy. Caring for that bird taught me to (10)____ every living thing around me.', 156, 2, '[{"q":"1","answer":"C","options":["loud","cheap","frozen","round"],"explanation":"the frozen ground 冻硬的地面。"},{"q":"2","answer":"D","options":["sold","bought","drawn","damaged"],"explanation":"had been damaged 受了伤。"},{"q":"3","answer":"A","options":["concern","price","noise","machine"],"explanation":"deep concern 深切的担忧。"},{"q":"4","answer":"B","options":["sell","design","lose","throw"],"explanation":"design a warm box 弄一个暖和的盒子。"},{"q":"5","answer":"C","options":["loud","cheap","afraid","round"],"explanation":"were afraid 担心害怕。"},{"q":"6","answer":"D","options":["sell","buy","draw","remove"],"explanation":"remove it 把它挪走。"},{"q":"7","answer":"A","options":["cage","price","noise","machine"],"explanation":"in a cage 在笼子里。"},{"q":"8","answer":"B","options":["sell","spread","lose","throw"],"explanation":"spread its wings 展开翅膀。"},{"q":"9","answer":"C","options":["noise","money","nature","traffic"],"explanation":"back to nature 回归自然。"},{"q":"10","answer":"D","options":["forget","sell","waste","value"],"explanation":"value every living thing 珍视万物。"}]'::jsonb, 4, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U1', 'The Morning After Snow', 'When I woke up and looked out of the window, the snow had (1)____ our whole street into a white wonderland. Everything (2)____ looked so different and beautiful. The familiar trees in the (3)____ now wore soft white coats, and the world was wonderfully (4)____. I quickly got dressed and ran outside to (5)____ the fresh, clean air. As I walked, I became more (6)____ of small wonders I usually missed: ice on a leaf, footprints of a bird, light shining on the snow. Such a quiet scene had a deeply (7)____ effect on my mind, and I felt calm and happy. Nature, I thought, can (8)____ an ordinary place into something magical overnight. I took out my phone to take a few (9)____ of the view, but no picture could really hold its beauty. That morning reminded me to (10)____ such simple gifts of the natural world.', 148, 2, '[{"q":"1","answer":"A","options":["transformed","sold","lost","bought"],"explanation":"transformed ... into 把……变成。"},{"q":"2","answer":"B","options":["price","familiar","machine","noise"],"explanation":"everything familiar 一切熟悉的事物;此处 familiar 修饰 everything。"},{"q":"3","answer":"C","options":["price","noise","landscape","machine"],"explanation":"trees in the landscape 风景中的树。"},{"q":"4","answer":"D","options":["loud","cheap","round","quiet"],"explanation":"wonderfully quiet 出奇地安静。"},{"q":"5","answer":"A","options":["enjoy","sell","throw","lose"],"explanation":"enjoy the fresh air 享受清新的空气。"},{"q":"6","answer":"B","options":["loud","aware","cheap","round"],"explanation":"more aware of 更留意。"},{"q":"7","answer":"C","options":["loud","cheap","positive","round"],"explanation":"a positive effect 积极的影响。"},{"q":"8","answer":"D","options":["sell","lose","throw","transform"],"explanation":"transform a place 改变一个地方。"},{"q":"9","answer":"A","options":["photos","prices","noises","machines"],"explanation":"take a few photos 拍几张照片。"},{"q":"10","answer":"B","options":["waste","treasure","sell","forget"],"explanation":"treasure such gifts 珍惜这些礼物。"}]'::jsonb, 5, 'sufe');
INSERT INTO public.junior_cloze (grade, volume, unit, title, body, word_count, difficulty, questions, sort_order, publisher) VALUES (10, 'required2', 'U1', 'Our Class Plants Trees', 'Every spring our class spends one day planting young trees on a bare (1)____ outside the town. Years ago this place was a green forest, but people had (2)____ most of the trees for wood. Without them, the soil grew poor and many animals lost their (3)____. Our teacher told us that planting trees is one way to (4)____ damaged nature. Each of us dug a hole and placed a (5)____ tree inside it with great care. The work was tiring, but we felt (6)____ to be helping the earth. Our teacher said that in many years these trees would grow tall and bring back a healthy (7)____ for birds and insects. She reminded us that nature cannot be (8)____ and that real change takes time. Even so, every small tree we planted was a (9)____ of hope. I now understand that protecting the natural world is the (10)____ of us all.', 152, 2, '[{"q":"1","answer":"C","options":["price","noise","hillside","machine"],"explanation":"a bare hillside 光秃秃的山坡。"},{"q":"2","answer":"D","options":["sold","bought","drawn","cut"],"explanation":"cut most of the trees 砍掉大部分树。"},{"q":"3","answer":"A","options":["homes","prices","noises","machines"],"explanation":"lost their homes 失去家园。"},{"q":"4","answer":"B","options":["sell","restore","lose","break"],"explanation":"restore damaged nature 修复受损的自然。"},{"q":"5","answer":"C","options":["loud","cheap","young","frozen"],"explanation":"a young tree 一棵小树。"},{"q":"6","answer":"D","options":["loud","cheap","round","proud"],"explanation":"felt proud 感到自豪。"},{"q":"7","answer":"A","options":["habitat","price","noise","machine"],"explanation":"a healthy habitat 健康的栖息地。"},{"q":"8","answer":"B","options":["sold","rushed","bought","drawn"],"explanation":"cannot be rushed 不能急于求成。"},{"q":"9","answer":"C","options":["price","noise","sign","machine"],"explanation":"a sign of hope 希望的象征。"},{"q":"10","answer":"D","options":["price","noise","machine","duty"],"explanation":"the duty of us all 我们所有人的责任。"}]'::jsonb, 6, 'sufe');

-- ===== 5) 听力 6篇/30题(audio_url 待 TTS) =====
DELETE FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='required2' AND unit='U1';
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·对话 A Plan to Go Hiking', '上外版必修第二册 U1 · dialogue', 3, 'Lucy: Tom, are you free this Saturday? I''m planning to go hiking in the hills.
Tom: That sounds great. I really need some time in nature after a busy week.
Lucy: Me too. They say there are many rare birds in that forest.
Tom: Wonderful. Should we bring a camera to take some photos?
Lucy: Yes, but let''s be quiet so we don''t frighten the animals.
Tom: Good idea. And we must take all our rubbish home with us.
Lucy: Of course. We should leave the woods as clean as we find them.
Tom: Agreed. Let''s meet at the bus stop at eight in the morning.', 'Lucy 邀 Tom 周六去山里爬山;两人都想在忙碌一周后亲近自然;那片森林里据说有许多稀有鸟类;他们决定带相机拍照,但要保持安静以免惊扰动物;还要把垃圾带回家、让森林和来时一样干净;约定早上八点在公交站见面。', 'uk_female', '[{"q":"What does Lucy plan to do on Saturday?","type":"choice","answer":"A","options":["Go hiking in the hills.","Visit a city museum.","Stay at home and rest.","Go shopping with Tom."]},{"q":"Why does Tom want to join her?","type":"choice","answer":"B","options":["He wants to buy a new camera.","He needs some time in nature.","He has never seen the hills.","He wants to meet new people."]},{"q":"What does the forest have, according to Lucy?","type":"choice","answer":"A","options":["Many rare birds.","A large car park.","A famous restaurant.","A small shopping centre."]},{"q":"Why do they decide to stay quiet?","type":"choice","answer":"B","options":["So they can hear the radio.","So they do not frighten the animals.","So they do not get lost.","So they can talk on the phone."]},{"q":"What will they do with their rubbish?","type":"choice","answer":"C","options":["Leave it under a tree.","Burn it in the forest.","Take it all home with them.","Throw it into the river."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·短文 Why Bees Matter', '上外版必修第二册 U1 · passage', 2, 'Bees are small, but they play a huge part in nature. As they fly from flower to flower, they help plants to make seeds and fruit. Without bees, many plants could not grow, and the animals that eat those plants would lose their food. In this way, these tiny insects help to keep the balance of nature. Sadly, bees are now in danger because of pollution and the loss of wild flowers. We can help them by growing more flowers and by keeping our gardens free of harmful chemicals. Protecting bees means protecting a healthy world for us all.', '蜜蜂虽小,却在自然中作用巨大。它们在花丛间飞舞,帮助植物结出种子和果实。没有蜜蜂,许多植物无法生长,以这些植物为食的动物也会失去食物。就这样,这些小昆虫维系着自然的平衡。可惜由于污染和野花减少,蜜蜂如今处境危险。我们可以多种花、不在花园里使用有害化学品来帮助它们。保护蜜蜂就是为大家保护一个健康的世界。', 'uk_female', '[{"q":"How do bees help plants?","type":"choice","answer":"D","options":["By eating harmful insects.","By bringing them water.","By keeping them warm.","By helping them make seeds and fruit."]},{"q":"What would happen to some animals without bees?","type":"choice","answer":"A","options":["They would lose their food.","They would grow much bigger.","They would move to the city.","They would stop sleeping."]},{"q":"What do bees help to keep, according to the passage?","type":"choice","answer":"B","options":["The price of fruit.","The balance of nature.","The speed of the wind.","The colour of flowers."]},{"q":"Why are bees now in danger?","type":"choice","answer":"C","options":["Because they fly too far.","Because gardens are too large.","Because of pollution and the loss of wild flowers.","Because people grow too many flowers."]},{"q":"What is one way we can help bees?","type":"choice","answer":"D","options":["Keep them inside small cages.","Move them to colder places.","Feed them only sugar.","Grow more flowers in our gardens."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·对话 Should We Keep a Wild Bird?', '上外版必修第二册 U1 · dialogue', 3, 'Ben: Look, Mum, I found this little bird in the park. Can we keep it at home?
Mum: It''s lovely, Ben, but I''m not sure a wild bird should live in a cage.
Ben: But it might be safer with us. Outside, bigger animals could hunt it.
Mum: I understand, yet a wild bird belongs in its natural home, where it can fly freely.
Ben: So what should we do? It looks a little weak.
Mum: Let''s care for it until it is strong, and then set it free.
Ben: That sounds fair. I don''t want it to be unhappy in a small cage.
Mum: Good boy. Helping an animal back to nature is the kindest thing we can do.', 'Ben 在公园里捡到一只小鸟,想带回家养;妈妈觉得野鸟不该关在笼子里;Ben 说在外面会被大动物猎食,跟着他们更安全;妈妈理解,但认为野鸟属于能自由飞翔的自然家园;两人决定先把鸟养到强壮,再放它回归自然;Ben 也不想鸟在小笼子里不快乐;妈妈说帮助动物回归自然是最善良的事。', 'uk_female', '[{"q":"What does Ben want to do at first?","type":"choice","answer":"A","options":["Keep the wild bird at home.","Sell the bird to a friend.","Leave the bird in the park.","Give the bird to a zoo."]},{"q":"Why is Mum unsure about the idea?","type":"choice","answer":"B","options":["The bird is too noisy.","A wild bird should not live in a cage.","They have no room at home.","The bird costs too much to feed."]},{"q":"What reason does Ben give for keeping it?","type":"choice","answer":"C","options":["It would be cheaper than buying one.","It can sing very beautifully.","It might be safer from bigger animals.","It is a very rare kind of bird."]},{"q":"What do they finally decide to do?","type":"choice","answer":"D","options":["Keep it in a cage for ever.","Take it to the city zoo.","Give it to a neighbour.","Care for it, then set it free."]},{"q":"What does Mum say is the kindest thing to do?","type":"choice","answer":"A","options":["Help the animal back to nature.","Teach the bird to talk.","Keep the bird as a pet.","Take photos of the bird."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·短文 Everything in the Sea Is Linked', '上外版必修第二册 U1 · passage', 2, 'Life in the ocean is closely linked together. Small fish eat tiny sea plants, and bigger fish eat the small fish. Even the largest animals depend on this long chain of life. When people take too many fish from the sea, the whole chain can be broken. Other animals then lose their food and may fall in number too. This shows that the balance of the ocean is easy to harm but hard to repair. By fishing carefully and keeping the water clean, we can help to protect every living thing in the sea, from the smallest plant to the greatest whale.', '海洋中的生命紧密相连。小鱼吃微小的海洋植物,大鱼吃小鱼,就连最大的动物也依赖这条漫长的生命链。当人们从海里捕捞过多的鱼,整条链条就可能断裂。其他动物随之失去食物,数量也可能下降。这说明海洋的平衡容易被破坏却难以修复。通过谨慎捕鱼、保持水质清洁,我们就能保护海里从最小的植物到最大的鲸鱼的每一个生命。', 'uk_female', '[{"q":"What do the small fish in the sea eat?","type":"choice","answer":"B","options":["Bigger fish.","Tiny sea plants.","Large whales.","Sea birds."]},{"q":"What can break the chain of life in the sea?","type":"choice","answer":"C","options":["Too much rain.","Plants growing too fast.","People taking too many fish.","Whales swimming too far."]},{"q":"What does the passage say about the balance of the ocean?","type":"choice","answer":"D","options":["It can never be harmed.","It repairs itself quickly.","It does not matter to people.","It is easy to harm but hard to repair."]},{"q":"What happens to other animals when the chain is broken?","type":"choice","answer":"A","options":["They lose their food and may fall in number.","They grow much larger.","They learn to eat plants.","They move onto the land."]},{"q":"What is one way to protect sea life, according to the passage?","type":"choice","answer":"B","options":["Catch as many fish as possible.","Fish carefully and keep the water clean.","Build walls across the sea.","Move all the fish into one place."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·对话 A Visit to the Nature Reserve', '上外版必修第二册 U1 · dialogue', 3, 'Guide: Welcome to our nature reserve. Here we protect many rare plants and animals.
Anna: It''s beautiful here. Why was this reserve set up?
Guide: Years ago, this forest was almost destroyed, and many species nearly disappeared.
Anna: That''s sad. So what did people do to save it?
Guide: We stopped the hunting, cleaned the rivers, and planted thousands of young trees.
Anna: And did the animals come back?
Guide: Yes, slowly. Restoring nature takes many years, but the balance is returning.
Anna: What a wonderful job. I''d love to help with conservation one day.', '向导欢迎大家来到自然保护区,这里保护着许多稀有动植物;Anna 觉得很美,问保护区为何设立;向导说多年前这片森林几乎被毁,许多物种濒临消失;Anna 问人们如何拯救;向导说他们禁止狩猎、清理河流、种下成千上万棵小树;动物慢慢回来了;恢复自然需要很多年,但平衡正在回归;Anna 希望将来也能参与环境保护。', 'uk_female', '[{"q":"What does the reserve mainly do?","type":"choice","answer":"C","options":["Sell food to visitors.","Train animals for shows.","Protect rare plants and animals.","Build new roads in the forest."]},{"q":"Why was the reserve set up?","type":"choice","answer":"D","options":["To make money from tourists.","Because the city needed more space.","To keep animals in cages.","Because the forest was almost destroyed."]},{"q":"What did people do to save the forest?","type":"choice","answer":"A","options":["They stopped hunting and cleaned the rivers.","They cut down the old trees.","They moved all animals to a zoo.","They built houses in the woods."]},{"q":"What does the guide say about restoring nature?","type":"choice","answer":"B","options":["It is quick and easy.","It takes many years.","It can never really work.","It needs no help from people."]},{"q":"What does Anna hope to do one day?","type":"choice","answer":"C","options":["Open her own zoo.","Cut down the forest.","Help with conservation.","Sell rare animals."]}]'::jsonb, '[]'::jsonb, 'long', 'required2', 'U1', 'sufe');
INSERT INTO public.junior_listening_exercises (grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit, publisher) VALUES (10, 'U1 听力·短文 A Tip for Nature Lovers', '上外版必修第二册 U1 · passage', 2, 'Here is a simple tip for anyone who loves nature. The next time you feel tired or worried, try spending a little time outdoors. Walk in a park, sit by a river, or just watch the clouds in the sky. Studies show that time in nature can lift our mood and have a positive effect on our minds. You do not need to travel far; even a small green space near your home can help. While you are there, look closely and be aware of the beauty around you. A few quiet minutes with nature today can leave you feeling calmer and happier.', '给所有热爱自然的人一个简单建议:下次当你感到疲惫或烦恼时,试着到户外待一会儿。在公园散步、坐在河边,或只是看看天上的云。研究表明,亲近自然能提升我们的心情,对头脑有积极的影响。你不必走远,哪怕是家附近一小片绿地也能帮上忙。在那里,仔细观察、留意身边的美。今天与自然共度几分钟安静时光,就能让你感到更平静、更快乐。', 'uk_female', '[{"q":"Who is this tip for?","type":"choice","answer":"D","options":["Only park workers.","Only scientists.","Only children.","Anyone who loves nature."]},{"q":"What does the speaker suggest doing when you feel worried?","type":"choice","answer":"A","options":["Spend a little time outdoors.","Stay inside all day.","Buy something new.","Sleep the whole afternoon."]},{"q":"What do studies show about time in nature?","type":"choice","answer":"B","options":["It makes people sleepy.","It can lift our mood.","It costs a lot of money.","It makes the days shorter."]},{"q":"Do you need to travel far, according to the passage?","type":"choice","answer":"C","options":["Yes, you must go to the mountains.","Yes, you must visit the sea.","No, even a small green space can help.","Yes, you must leave the city."]},{"q":"What can a few quiet minutes with nature do?","type":"choice","answer":"D","options":["Make you feel more tired.","Cost you a lot of time.","Make you forget your friends.","Leave you feeling calmer and happier."]}]'::jsonb, '[]'::jsonb, 'short', 'required2', 'U1', 'sufe');

-- ===== 6) 写作 1篇 =====
DELETE FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='required2' AND unit='U1';
INSERT INTO public.junior_writing_prompts (grade, topic, title_en, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, high_sentences, error_pairs, paragraph_template, difficulty, volume, unit, publisher) VALUES (10, 'Describe a scene in nature in spatial order(按空间顺序描写一处自然景色)', 'A View of Nature', '请选择一幅你喜欢的风景画或一张自然照片,用英语写一段约80词的短文,按空间顺序(如从左到右、从近到远)描写其中的景色。要求:① 抓住最重要的细节;② 用表示方位的词语让画面有条理(in front of / on the left / in the distance 等);③ 结尾写出这处景色给你的整体感受。', 'Choose a landscape painting or a nature photo you like. Write a paragraph of about 80 words describing the scene in spatial order (e.g. from near to far, or from left to right). You should: 1) include the most important details; 2) use prepositions of place to organise the picture (in front of / on the left / in the distance); 3) end with the overall feeling the scene gives you.', '["选定观察角度并抓住主要细节(A stream / trees / mountains …)","用方位词组织画面(in front of us / on the left / in the distance)","按空间顺序由近及远(或从左到右)展开","结尾点出整体感受(All these present a peaceful view of nature.)"]'::jsonb, 70, 100, 'In front of us, a clear stream flows gently from the left to the far right through a green grassland. At our feet, wild flowers grow brightly on the bank. On the other side, tall trees stand strong and quiet. Further in the distance, a small palace rises against the hills, and the sun is setting beside it, casting a soft golden glow on the clouds above. All these details combine to present a peaceful and beautiful view of nature at dusk. Looking at it, I feel calm and full of hope.', '【15 分制】A 档(13-15):五要素齐全、组织有条理、语言准确多样;B 档(10-12):要点较全、少量错误;C 档(7-9):要点偏少、句型简单;D 档(0-6):内容不完整、错误多。', '["In front of us, a clear stream flows gently from the left to the far right.","Further in the distance, a small palace rises against the hills.","The sun is setting beside it, casting a soft golden glow on the clouds above.","All these details combine to present a peaceful view of nature at dusk."]'::jsonb, '[{"wrong":"The trees stands on the left.","correct":"The trees stand on the left.","note":"主语 trees 为复数,动词不加 s。"},{"wrong":"A stream which flows past the field it is clear.","correct":"A stream which flows past the field is clear.","note":"定语从句后不再重复主语 it。"},{"wrong":"In the distance, a palace stand against the hills.","correct":"In the distance, a palace stands against the hills.","note":"主语 a palace 第三人称单数,动词加 s。"}]'::jsonb, '【按空间顺序写景结构】
第1句 定位起笔:In front of us, …
第2句 近景:At our feet, …
第3句 中景:On the other side, …
第4句 远景:Further in the distance, …
第5句 收束感受:All these present a peaceful view of nature.', 2, 'required2', 'U1', 'sufe');

-- ===== 7) 语法小知识 =====
DELETE FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='required2' AND unit='U1';
INSERT INTO public.junior_grammar_tips (grade, volume, unit, content, publisher) VALUES (10, 'required2', 'U1', '{"title":"限制性定语从句·关系代词 who / whom / that / which / whose 速查","intro":"关系代词在从句里替代先行词并充当主语、宾语或表所属。判断口诀:看先行词「指人还是指物」+ 从句「缺什么成分」。指人缺主语用 who、缺宾语用 whom;指物用 which/that;表「……的」用 whose;关系词跟在介词后,指物用 which、指人用 whom。","table":{"headers":["关系代词","用法 / 例句"],"rows":[["who","指人作主语:the man who explained the mystery"],["whom","指人作宾语(尤介词后):the expert whom we spoke to / to whom we spoke"],["which","指物作主/宾语:the tree which stood there;the book which I read"],["that","指人或物作主/宾语(限制性):the plants that grow here"],["whose","表所属(……的)+ 名词,指人指物皆可:anyone whose solution works;a tree whose roots fed the garden"]]},"specialRules":[{"rule":"从句缺宾语时,关系代词可省略","mark":"the book (that/which) I read"},{"rule":"介词提到关系词前时,指物只能用 which、指人只能用 whom,不可用 that","mark":"the bones on which symbols were carved √ / on that ×"},{"rule":"whose 后面直接跟名词,表示「……的」","mark":"a bird whose wing was hurt"},{"rule":"先行词为 all/anyone/everything 等,或带 the only/最高级时,多用 that","mark":"the only thing that he disliked"}],"why":["关系代词既要替代先行词,又要在从句里充当成分;所以判断时先问『先行词指人还是指物』,再看『从句缺主语、缺宾语还是表所属』,二者一对照,关系词就定了。"],"gaokaoPoints":["who/whom/which/that/whose 的选用(看指人指物 + 从句缺什么成分);语法填空与单句改错高频。","介词 + which / 介词 + whom 的提前结构:介词后绝不能用 that 或 who。"],"examVsReal":[{"exam":"the expert to whom we spoke（考试/正式）","real":"the expert we spoke to","note":"考试爱考 to whom 提前;口语里常省略关系词、把介词留在句末"},{"exam":"the tree which stood there（考试）","real":"the tree that stood there / the tree standing there","note":"口语里 which 常换成 that 或直接用现在分词,更简洁"}]}'::jsonb, 'sufe');

COMMIT;

-- ===== 自带校验(publisher='sufe') =====
SELECT 'vocab' k, count(*) v, 46 expect FROM public.junior_vocab WHERE publisher='sufe' AND volume='required2' AND unit='U1'
UNION ALL SELECT 'grammar_points', count(*), 3 FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions WHERE point_id IN (SELECT id FROM public.junior_grammar_points WHERE publisher='sufe' AND volume='required2' AND unit='U1')
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE publisher='sufe' AND volume='required2' AND unit='U1'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE publisher='sufe' AND volume='required2' AND unit='U1'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE publisher='sufe' AND volume='required2' AND unit='U1'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE publisher='sufe' AND volume='required2' AND unit='U1'
UNION ALL SELECT 'grammar_tips', count(*), 1 FROM public.junior_grammar_tips WHERE publisher='sufe' AND volume='required2' AND unit='U1' ORDER BY k;
