-- 九年级 U3 题库灌库(幂等)。volume='9' unit='U3' grade=9。vocab 不在此(已单独按 '9' 灌)。
BEGIN;

-- ===== junior_grammar_points (预期 3) =====
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), 'c49e0d84-1b6d-4bea-bb83-35ff7558dc8f', 'g9u3.01', '①宾语从句:语序还原(疑问句→陈述语序)', 'B1', 9, '对应:九年级 U3', 1, '9', 'U3' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u3.01');
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), 'c49e0d84-1b6d-4bea-bb83-35ff7558dc8f', 'g9u3.02', '②宾语从句:连接词选择(疑问词 vs if/whether)', 'B1', 9, '对应:九年级 U3', 2, '9', 'U3' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u3.02');
INSERT INTO public.junior_grammar_points (id, category_id, code, title, cefr, grade, summary, sort_order, volume, unit) SELECT gen_random_uuid(), 'e05f9874-6401-42f8-a361-28f1dee3a58e', 'g9u3.03', '③礼貌委婉句型(请求/问路)', 'B1', 9, '对应:九年级 U3', 3, '9', 'U3' WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_points WHERE code='g9u3.03');

-- ===== junior_grammar_questions (预期 60) =====
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Could you tell me where ____?','the post office is','the post office does','does the post office be','is the post office','A','[语序] 宾从用陈述语序 主+谓',1,1,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Could you tell me where ____?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Do you know when ____?','does he arrive','will he arrive','he will arrive','arrive he will','C','[语序] 陈述语序 he will arrive',2,2,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Do you know when ____?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'I wonder how ____ to the museum.','get I can','I can get','do I get','can I get','B','[语序] 陈述语序 I can get',3,3,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='I wonder how ____ to the museum.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Could you please tell me where ____ a stamp?','I can buy','buy I can','can I buy','do I buy','A','[语序] 陈述语序 I can buy',1,4,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Could you please tell me where ____ a stamp?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Please tell me what ____ yesterday.','did he buy','bought he','he bought','did he bought','C','[语序] 陈述语序,过去时不用did',2,5,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Please tell me what ____ yesterday.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Can you tell me why ____ so happy today?','does she be','she does','is she','she is','D','[语序] 陈述语序 she is',3,6,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Can you tell me why ____ so happy today?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Do you know where ____ this morning?','they went','went they','do they went','did they go','A','[语序] 陈述语序 they went',1,7,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Do you know where ____ this morning?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Could you tell me how much ____?','is this dictionary','this dictionary is','this dictionary does','does this dictionary','B','[语序] 陈述语序 this dictionary is',2,8,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Could you tell me how much ____?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'I wonder where ____ to spend the holiday.','going they are','do they going','are they going','they are going','D','[语序] 陈述语序 they are going',3,9,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='I wonder where ____ to spend the holiday.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Please tell me what ____ just now.','did he say','does he say','said he','he said','D','[语序] 陈述语序 he said',1,10,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Please tell me what ____ just now.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Do you know how far ____ from here?','is it','it does','it is','does it be','C','[语序] 陈述语序 it is',2,11,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Do you know how far ____ from here?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Could you tell me who ____ talking with?','you are','you do','are you','do you','A','[语序] 陈述语序 you are',3,12,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Could you tell me who ____ talking with?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'I''d like to know why ____ late again.','did they be','they did','were they','they were','D','[语序] 陈述语序 they were',1,13,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='I''d like to know why ____ late again.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Tell me what ____ for lunch today.','are they eating','eating they','do they eating','they are eating','D','[语序] 陈述语序 they are eating',2,14,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Tell me what ____ for lunch today.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Please tell me when ____ finished.','does the work','the work is','the work does','is the work','B','[语序] 陈述语序 the work is',3,15,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Please tell me when ____ finished.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Do you know whose umbrella ____?','this is','this does','does this be','is this','A','[语序] 陈述语序 this is',1,16,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Do you know whose umbrella ____?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'I want to know where ____ now.','she live','does she live','she lives','live she','C','[语序] 陈述语序,三单 she lives',2,17,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='I want to know where ____ now.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Could you tell me how long ____ here?','you have stayed','stayed you have','have you stayed','do you stayed','A','[语序] 陈述语序 you have stayed',3,18,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Could you tell me how long ____ here?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'Please tell me which way ____ to the station.','is lead','leads','does lead','do lead','B','[语序] which way作主语,直接接谓语 leads',1,19,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='Please tell me which way ____ to the station.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.01'), 'I wonder what ____ after school.','they do usually','usually do they','do they usually','they usually do','D','[语序] 陈述语序 they usually do',2,20,'mcq','g9u3.01','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.01' AND x.stem='I wonder what ____ after school.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I wonder ____ he will come to the party.','if','what','how','where','A','[if] 一般疑问句作宾语→if/whether',1,1,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I wonder ____ he will come to the party.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Could you tell me ____ the ticket office is?','where','if','that','whether','A','[疑问词] be动词后缺表语(地点)→只能where;whether the ticket office is 后无表语不成立',2,2,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Could you tell me ____ the ticket office is?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Do you know ____ the library is open today?','when','what','whether','how','C','[if] 一般疑问句→if/whether',3,3,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Do you know ____ the library is open today?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I''m not sure ____ they have finished the report.','why','where','whether','who','C','[if] 一般疑问句→if/whether',1,4,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I''m not sure ____ they have finished the report.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Please tell me ____ bus I should take.','if','which','that','whether','B','[疑问词] ____ bus 作定语→只能which(if/whether不修饰名词)',2,5,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Please tell me ____ bus I should take.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I wonder ____ the train has arrived.','what','why','if','who','C','[if] 一般疑问句→if/whether',3,6,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I wonder ____ the train has arrived.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Could you tell me ____ the museum is?','whether','that','if','where','D','[疑问词] be句缺表语→只能where;whether the museum is 不成立',1,7,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Could you tell me ____ the museum is?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I want to know ____ she likes the gift.','what','whether','how','where','B','[if] 一般疑问句→if/whether',2,8,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I want to know ____ she likes the gift.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Can you tell me ____ the bank is?','if','where','that','whether','B','[疑问词] be句缺表语→只能where;whether the bank is 不成立',3,9,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Can you tell me ____ the bank is?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Do you know ____ they will do during the holiday?','if','what','that','whether','B','[疑问词] do后缺宾语→只能what;whether they will do 后无宾语不成立',1,10,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Do you know ____ they will do during the holiday?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I''m wondering ____ the store opens on Sundays.','how','what','whether','who','C','[if] 一般疑问句→if/whether',2,11,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I''m wondering ____ the store opens on Sundays.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Please tell me ____ you want to buy.','that','whether','if','what','D','[疑问词] 特殊疑问→what',3,12,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Please tell me ____ you want to buy.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I don''t know ____ it is going to rain.','why','where','if','how','C','[if] 一般疑问句→if/whether',1,13,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I don''t know ____ it is going to rain.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Can you tell me ____ we should do next?','if','what','that','whether','B','[疑问词] 特殊疑问→what',2,14,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Can you tell me ____ we should do next?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I wonder ____ he passed the exam.','where','if','what','when','B','[if] 一般疑问句→if/whether',3,15,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I wonder ____ he passed the exam.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Do you know ____ got the first prize?','that','if','whether','who','D','[疑问词] 特殊疑问→who(who作主语)',1,16,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Do you know ____ got the first prize?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Please tell me ____ I should put my bag.','where','that','if','whether','A','[疑问词] put my bag后缺地点→只能where',2,17,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Please tell me ____ I should put my bag.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I''m not sure ____ he is at home now.','where','what','whether','how','C','[if] 一般疑问句→if/whether',3,18,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I''m not sure ____ he is at home now.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'Can you tell me ____ you feel now?','that','whether','if','how','D','[疑问词] 特殊疑问→how',1,19,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='Can you tell me ____ you feel now?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.02'), 'I wonder ____ they need any help.','what','where','whether','who','C','[if] 一般疑问句→if/whether',2,20,'mcq','g9u3.02','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.02' AND x.stem='I wonder ____ they need any help.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ tell me the way to the post office?','Are you please','Do you must','Could you please','Will you must','C','[句型] 礼貌请求 Could you please…?',1,1,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ tell me the way to the post office?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____, could you tell me where the bank is?','Excuse me','Sorry for','Thank you','Never mind','A','[句型] 问路开头礼貌语 Excuse me',2,2,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____, could you tell me where the bank is?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ telling me how to get to the station?','Would you like','Would you mind','Could you mind','Do you want','B','[句型] Would you mind + doing 委婉请求',3,3,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ telling me how to get to the station?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), 'I ____ you could help me find the museum.','hope what','think how','wonder if','want that','C','[句型] I wonder if… 委婉请求',1,4,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='I ____ you could help me find the museum.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ tell me where I can buy a map?','Must you to','Could you please','Are you can','Do you will','B','[句型] Could you please…? 礼貌请求',2,5,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ tell me where I can buy a map?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), 'Excuse me, ____ tell me when the show starts?','will you must','are you','must you','could you','D','[句型] could you…? 礼貌问询',3,6,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='Excuse me, ____ tell me when the show starts?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ showing me the way to the library?','Would you mind','Do you mind to','Could you like','Would you like to','A','[句型] Would you mind + doing',1,7,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ showing me the way to the library?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ you tell me how far the airport is?','Shall to','Could','May to','Must','B','[句型] Could you…? 礼貌请求',2,8,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ you tell me how far the airport is?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), 'Sorry to ____ you, but could you help me?','welcome','thank','bother','mind','C','[句型] Sorry to bother you 礼貌打扰语',3,9,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='Sorry to ____ you, but could you help me?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ I ask you a question about the city?','Must','Need','Ought','May','D','[句型] May I…? 礼貌请求许可',1,10,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ I ask you a question about the city?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ tell me where the nearest hospital is?','Could you please','Are you please to','Do you please','Will you please to','A','[句型] Could you please…?',2,11,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ tell me where the nearest hospital is?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ you mind if I sat here?','Would','Must','Should','Could','A','[句型] Would you mind if…? 委婉征求',3,12,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ you mind if I sat here?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), 'I''d ____ to know if there is a bus stop nearby.','want','hope','like','wish to','C','[句型] I''d like to know… 委婉表达',1,13,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='I''d ____ to know if there is a bus stop nearby.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ me, do you know where the restroom is?','Please for','Thank','Sorry','Excuse','D','[句型] Excuse me 问路开头',2,14,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ me, do you know where the restroom is?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ you please show me how to use the map?','Could','May to','Must','Shall to','A','[句型] Could you please…?',3,15,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ you please show me how to use the map?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), 'Would you ____ telling me the way to the park?','want','like','hope','mind','D','[句型] Would you mind + doing',1,16,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='Would you ____ telling me the way to the park?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ tell me if the store is open, please?','Are you to','Can you','Must you','Will you to','B','[句型] Can you…, please? 礼貌请求',2,17,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ tell me if the store is open, please?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), 'I wonder ____ you could tell me the time.','how','what','that','if','D','[句型] I wonder if… 委婉请求(句型固定搭配)',3,18,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='I wonder ____ you could tell me the time.');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), '____ I help you find your way?','May','Need to','Ought','Must','A','[句型] May I help you? 礼貌提供帮助',1,19,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='____ I help you find your way?');
INSERT INTO public.junior_grammar_questions (id, point_id, stem, option_a, option_b, option_c, option_d, correct_answer, explanation, difficulty, sort_order, question_type, grammar_topic, distractors) SELECT gen_random_uuid(), (SELECT id FROM public.junior_grammar_points WHERE code='g9u3.03'), 'Thank you ____ much for your help.','quite a','very','too','so a','B','[句型] Thank you very much 礼貌致谢',2,20,'mcq','g9u3.03','[]'::jsonb WHERE NOT EXISTS (SELECT 1 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.code='g9u3.03' AND x.stem='Thank you ____ much for your help.');

-- ===== junior_reading (预期 6) =====
DELETE FROM public.junior_reading WHERE volume='9' AND unit='U3';
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Asking for Directions Politely', 'When you visit a new place, you will often need to ask for directions. Knowing how to ask politely can make a big difference. First, get the person''s attention in a friendly way. A simple "Excuse me" is the best start. Then, use a polite question form, such as "Could you please tell me where the station is?" instead of a direct "Where is the station?" A polite question shows respect and makes people more willing to help. If the directions are not clear, you can politely ask the person to repeat them. Finally, don''t forget to say "Thank you" before you leave. These small steps can turn a stranger into a helpful friend and make your trip much smoother.', '说明文', 120, '[{"q": "What is the passage mainly about?", "answer": "A", "options": ["How to ask for directions politely.", "How to read a map.", "How to make friends at school.", "Why cities are big."], "explanation": "主旨:讲如何礼貌地问路"}, {"q": "What is the best way to get someone''s attention?", "answer": "C", "options": ["Touching their arm.", "Shouting loudly.", "Saying \"Excuse me\".", "Waving a map."], "explanation": "原文:A simple Excuse me is the best start"}, {"q": "Why is a polite question better than a direct one?", "answer": "D", "options": ["It saves money.", "It is easier to say.", "It is shorter.", "It shows respect and makes people willing to help."], "explanation": "原文:shows respect and makes people more willing to help"}, {"q": "What should you do if the directions are not clear?", "answer": "A", "options": ["Politely ask the person to repeat them.", "Guess the way.", "Ask a different question.", "Walk away."], "explanation": "原文:politely ask the person to repeat them"}, {"q": "What does the writer suggest doing before leaving?", "answer": "D", "options": ["Giving money.", "Shaking hands.", "Taking a photo.", "Saying \"Thank you\"."], "explanation": "原文:don''t forget to say Thank you before you leave"}]'::jsonb, '[]'::jsonb, 3, '9', 'U3');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'At the Information Desk', 'Tourist: Excuse me, could you please tell me how I can get to the City Library?
Clerk: Of course. Go straight along this street and turn left at the second corner. It''s next to the post office.
Tourist: Thank you. Do you know if the library is open on Sundays?
Clerk: Yes, it is, but only in the morning, from nine to twelve.
Tourist: Great. One more question — is there a place to eat near the library?
Clerk: There''s a nice cafe across from it. The sandwiches there are very popular.
Tourist: That''s very helpful. Thank you so much!
Clerk: You''re welcome. Enjoy your day!', '对话', 106, '[{"q": "Where does the tourist want to go?", "answer": "A", "options": ["The City Library.", "The post office.", "A cafe.", "The information desk."], "explanation": "原文:how I can get to the City Library"}, {"q": "Where is the library?", "answer": "D", "options": ["Inside the station.", "Across from a cafe only.", "At the second corner shop.", "Next to the post office."], "explanation": "原文:turn left… It''s next to the post office"}, {"q": "When is the library open on Sundays?", "answer": "D", "options": ["All day.", "Only in the afternoon.", "It is closed.", "Only in the morning, nine to twelve."], "explanation": "原文:only in the morning, from nine to twelve"}, {"q": "What is popular at the cafe?", "answer": "C", "options": ["The juice.", "The cakes.", "The sandwiches.", "The coffee."], "explanation": "原文:The sandwiches there are very popular"}, {"q": "How would you describe the clerk?", "answer": "C", "options": ["Tired and bored.", "Angry and busy.", "Polite and helpful.", "Rude and impatient."], "explanation": "推断:全程礼貌耐心回答"}]'::jsonb, '[]'::jsonb, 3, '9', 'U3');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'A Kind Stranger', 'Last summer, I traveled to a small town alone for the first time. After I got off the train, I felt completely lost. The streets all looked the same, and I could not find my hotel. I was too shy to ask anyone at first. Finally, I saw an old man sitting on a bench. I walked up to him and said, "Excuse me, sir. Could you please tell me how I can get to the Sunshine Hotel?" He smiled warmly and stood up. Instead of just pointing, he walked with me for five minutes until we reached the hotel gate. I thanked him again and again. That day, I learned that being polite and brave enough to ask can turn a stranger into a friend.', '记叙文', 126, '[{"q": "Why did the writer feel lost?", "answer": "C", "options": ["It was raining.", "The train was late.", "The streets all looked the same.", "The hotel was closed."], "explanation": "原文:the streets all looked the same"}, {"q": "How did the writer feel about asking at first?", "answer": "A", "options": ["Too shy.", "Angry.", "Excited.", "Happy."], "explanation": "原文:I was too shy to ask anyone at first"}, {"q": "What did the old man do to help?", "answer": "B", "options": ["He drew a map.", "He walked with the writer to the hotel.", "He called a taxi.", "He gave money."], "explanation": "原文:he walked with me… until we reached the hotel"}, {"q": "What polite phrase did the writer use?", "answer": "A", "options": ["Could you please tell me…", "Where is the hotel, now.", "Give me the way.", "Take me there."], "explanation": "原文用了 Could you please tell me how I can get to…"}, {"q": "What did the writer learn?", "answer": "A", "options": ["Being polite and brave can turn a stranger into a friend.", "Travel alone is dangerous.", "Maps are useless.", "Never trust strangers."], "explanation": "原文结尾:being polite and brave… turn a stranger into a friend"}]'::jsonb, '[]'::jsonb, 3, '9', 'U3');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'A Letter Before the Trip', 'Dear Mike, I''m so glad you are coming to visit my city next month! Let me give you some useful tips. When you arrive at the airport, you can take the airport bus to the city center. If you are not sure which bus to take, just ask the staff politely. You can say, "Could you please tell me which bus goes to the city center?" People here are friendly and will be happy to help. If you get lost in the streets, don''t worry. Look for a police officer or go into a shop and ask, "Excuse me, do you know where I am on this map?" Remember to say "thank you" afterwards. I''m sure you will enjoy your trip. See you soon! Yours, Anna', '书信', 126, '[{"q": "Why does Anna write this letter?", "answer": "A", "options": ["To give Mike travel tips before his trip.", "To say goodbye.", "To cancel the trip.", "To borrow money."], "explanation": "信的目的是出行前给建议"}, {"q": "How can Mike get to the city center from the airport?", "answer": "C", "options": ["By taxi only.", "On foot.", "By the airport bus.", "By train."], "explanation": "原文:take the airport bus to the city center"}, {"q": "What should Mike do if he is unsure which bus to take?", "answer": "B", "options": ["Take any bus.", "Ask the staff politely.", "Go home.", "Wait there."], "explanation": "原文:just ask the staff politely"}, {"q": "If Mike gets lost, who does Anna suggest asking?", "answer": "D", "options": ["A tourist.", "No one.", "A bus driver only.", "A police officer or shop staff."], "explanation": "原文:look for a police officer or go into a shop and ask"}, {"q": "What does Anna remind Mike to do after asking?", "answer": "A", "options": ["Say thank you.", "Leave quickly.", "Take a photo.", "Pay money."], "explanation": "原文:Remember to say thank you afterwards"}]'::jsonb, '[]'::jsonb, 3, '9', 'U3');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'Why Politeness Matters When Asking', 'When we need help from a stranger, the way we ask is very important. Some people think that asking directly, like "Where is the station?", saves time. However, a direct question can sound rude. A polite question, such as "Could you please tell me where the station is?", shows respect. People are more willing to help someone who is polite. Politeness also makes the other person feel comfortable. In a new place, you may need to ask many people for help, so good manners can make your trip much smoother. Of course, being polite does not mean using long, difficult sentences. A simple "Excuse me" at the beginning is often enough. In short, a little politeness goes a long way.', '议论文', 120, '[{"q": "What is the main idea of the passage?", "answer": "A", "options": ["Politeness matters when asking for help.", "Travel is difficult.", "Asking directly saves time.", "Strangers never help."], "explanation": "主旨:问路时礼貌很重要"}, {"q": "Why can a direct question be a problem?", "answer": "C", "options": ["It is hard to say.", "It wastes money.", "It can sound rude.", "It is too long."], "explanation": "原文:a direct question can sound rude"}, {"q": "According to the passage, people are more willing to help someone who is ____.", "answer": "A", "options": ["polite", "rich", "fast", "quiet"], "explanation": "原文:more willing to help someone who is polite"}, {"q": "Does being polite mean using long difficult sentences?", "answer": "A", "options": ["No, a simple Excuse me is often enough.", "Yes, always.", "It is not mentioned.", "Yes, the longer the better."], "explanation": "原文:does not mean using long, difficult sentences"}, {"q": "What does \"a little politeness goes a long way\" mean?", "answer": "B", "options": ["You must walk a long way.", "A small amount of politeness brings big results.", "Politeness takes a long time.", "Politeness is useless."], "explanation": "谚语义:少许礼貌带来很大效果"}]'::jsonb, '[]'::jsonb, 3, '9', 'U3');
INSERT INTO public.junior_reading (id, grade, title, body, topic, word_count, questions, vocab_notes, difficulty, volume, unit) VALUES (gen_random_uuid(), 9, 'City Information Guide', 'Welcome to Greentown! Here is some useful information for visitors. TOURIST CENTER: Located at No. 5 Center Street, open from 9:00 a.m. to 6:00 p.m. The staff can answer your questions and give you a free map. RESTROOMS: Public restrooms can be found in the Central Park and near the bus station. ASKING FOR HELP: If you need directions, look for people wearing blue "Helper" shirts. They are city volunteers. You can also ask shop workers politely. USEFUL TIP: Save the city emergency number 110 in your phone. ENJOY YOUR STAY: Greentown is a safe and friendly city. Don''t be afraid to ask for help — we are always glad to welcome visitors!', '应用文', 113, '[{"q": "Where is the Tourist Center?", "answer": "C", "options": ["In Central Park.", "Near the bus station.", "At No. 5 Center Street.", "At the airport."], "explanation": "原文:Located at No. 5 Center Street"}, {"q": "What can you get for free at the Tourist Center?", "answer": "C", "options": ["A hotel room.", "A bus ticket.", "A map.", "A meal."], "explanation": "原文:give you a free map"}, {"q": "Where can visitors find public restrooms?", "answer": "D", "options": ["Only at the airport.", "In every shop.", "At the Tourist Center.", "In the Central Park and near the bus station."], "explanation": "原文:in the Central Park and near the bus station"}, {"q": "Who are the people in blue \"Helper\" shirts?", "answer": "B", "options": ["Shop owners.", "City volunteers.", "Bus drivers.", "Police officers."], "explanation": "原文:They are city volunteers"}, {"q": "What is the main purpose of this guide?", "answer": "D", "options": ["To advertise a hotel.", "To sell maps.", "To describe the weather.", "To give visitors useful information."], "explanation": "应用文:给游客提供有用信息"}]'::jsonb, '[]'::jsonb, 3, '9', 'U3');

-- ===== junior_cloze (预期 6) =====
DELETE FROM public.junior_cloze WHERE volume='9' AND unit='U3';
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U3', 'Lost in a New City', 'Last week, I traveled to a new city by myself. After I left the station, I soon got (1)____. All the streets looked the same. I wanted to ask for help, but I was a little (2)____ at first. Finally, I saw a kind-looking woman and walked up to her. "Excuse me," I said (3)____, "could you please tell me how I can get to the Grand Hotel?" She smiled and (4)____ me the way. "Go straight and turn (5)____ at the second corner," she said. I (6)____ her and followed her directions. Soon I found the hotel. I learned that being (7)____ when you ask makes people happy to help. A simple "Excuse me" and "Thank you" can (8)____ a big difference. Now I am never (9)____ to ask for directions, because most people are (10)____ to help a polite stranger.', 142, 3, '[{"q": "1", "answer": "B", "options": ["tired", "lost", "hungry", "late"], "explanation": "迷路 got lost"}, {"q": "2", "answer": "C", "options": ["happy", "proud", "shy", "angry"], "explanation": "一开始有点害羞 shy"}, {"q": "3", "answer": "A", "options": ["politely", "quickly", "loudly", "sadly"], "explanation": "礼貌地说 politely"}, {"q": "4", "answer": "D", "options": ["asked", "gave", "took", "told"], "explanation": "告诉我路 told me the way"}, {"q": "5", "answer": "B", "options": ["out", "left", "up", "off"], "explanation": "左转 turn left"}, {"q": "6", "answer": "D", "options": ["left", "asked", "followed", "thanked"], "explanation": "谢了她 thanked her"}, {"q": "7", "answer": "A", "options": ["polite", "rude", "quiet", "busy"], "explanation": "礼貌 being polite"}, {"q": "8", "answer": "C", "options": ["have", "do", "make", "take"], "explanation": "产生不同 make a difference"}, {"q": "9", "answer": "A", "options": ["afraid", "glad", "ready", "sure"], "explanation": "不再害怕 never afraid"}, {"q": "10", "answer": "B", "options": ["sorry", "glad", "busy", "tired"], "explanation": "乐意帮忙 glad to help"}]'::jsonb, 1);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U3', 'A Helpful Travel Tip', 'When you travel to a foreign country, it is important to know how to ask for help (1)____. In many places, people may not speak your (2)____. So a polite smile and a few simple words can (3)____ a lot. Instead of saying "Where is the bank?", it is (4)____ to say "Excuse me, could you please tell me where the bank is?" This kind of question shows (5)____. Most people are happy to (6)____ a polite visitor. If you do not understand the (7)____, you can ask the person to say it again slowly. Remember to (8)____ them afterwards. Being polite does not (9)____ much time, but it can make your trip much more (10)____. Good manners are welcome everywhere in the world.', 124, 3, '[{"q": "1", "answer": "B", "options": ["sadly", "politely", "loudly", "quickly"], "explanation": "礼貌地求助 politely"}, {"q": "2", "answer": "B", "options": ["money", "language", "food", "name"], "explanation": "语言 not speak your language"}, {"q": "3", "answer": "D", "options": ["lose", "take", "cost", "mean"], "explanation": "礼貌能意味很多 can mean a lot"}, {"q": "4", "answer": "C", "options": ["worse", "harder", "better", "easier"], "explanation": "更好 it is better to say"}, {"q": "5", "answer": "A", "options": ["respect", "money", "fear", "anger"], "explanation": "显示尊重 shows respect"}, {"q": "6", "answer": "C", "options": ["sell", "leave", "help", "stop"], "explanation": "乐意帮助 happy to help"}, {"q": "7", "answer": "B", "options": ["photos", "directions", "prices", "tickets"], "explanation": "听不懂方向 the directions"}, {"q": "8", "answer": "D", "options": ["ask", "watch", "call", "thank"], "explanation": "记得感谢 thank them"}, {"q": "9", "answer": "A", "options": ["take", "keep", "do", "make"], "explanation": "不花太多时间 take much time"}, {"q": "10", "answer": "A", "options": ["pleasant", "difficult", "boring", "strange"], "explanation": "更愉快 pleasant"}]'::jsonb, 2);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U3', 'The Polite Way', 'My grandmother always tells me that good (1)____ open many doors. When I was young, I used to ask questions in a (2)____ way. For example, I would say "Give me water!" instead of asking (3)____. One day, my grandmother taught me a lesson. She said, "If you want people to (4)____ you, you must ask kindly." From then on, I (5)____ to use polite words like "please" and "thank you". I noticed that people became much (6)____ to me. My teachers smiled more, and my friends were happy to (7)____ me. Being polite did not (8)____ anything, but it changed how people (9)____ me. Now I understand that a few kind words can make the world a (10)____ place. My grandmother was right all along.', 126, 3, '[{"q": "1", "answer": "B", "options": ["grades", "manners", "games", "clothes"], "explanation": "好的礼貌 good manners"}, {"q": "2", "answer": "B", "options": ["funny", "rude", "kind", "quiet"], "explanation": "粗鲁的方式 rude way"}, {"q": "3", "answer": "A", "options": ["politely", "loudly", "slowly", "sadly"], "explanation": "礼貌地问 asking politely"}, {"q": "4", "answer": "A", "options": ["respect", "watch", "stop", "leave"], "explanation": "想让别人尊重你 respect you"}, {"q": "5", "answer": "B", "options": ["failed", "learned", "forgot", "refused"], "explanation": "学会用礼貌词 learned to use"}, {"q": "6", "answer": "C", "options": ["angrier", "quieter", "friendlier", "busier"], "explanation": "对我更友好 friendlier"}, {"q": "7", "answer": "D", "options": ["stop", "leave", "fight", "help"], "explanation": "乐意帮我 happy to help"}, {"q": "8", "answer": "D", "options": ["keep", "take", "make", "cost"], "explanation": "不花费任何 didn''t cost anything"}, {"q": "9", "answer": "A", "options": ["treated", "left", "called", "forgot"], "explanation": "别人如何待我 treated me"}, {"q": "10", "answer": "C", "options": ["worse", "smaller", "better", "colder"], "explanation": "更美好的世界 better place"}]'::jsonb, 3);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U3', 'At the Train Station', 'Tom arrived at the train station, but he could not (1)____ the right platform. He felt a little worried because his train would (2)____ in twenty minutes. He looked around and saw a station worker. Tom walked over and asked (3)____, "Excuse me, could you please tell me (4)____ platform I should go to?" The worker pointed to the (5)____ and said, "Go up the stairs and turn right. It''s at the (6)____ of the hall." Tom (7)____ him and hurried there. On the way, he also wanted to know (8)____ he could buy some water. A kind passenger showed him a small (9)____ near the platform. Thanks to these helpful people, Tom (10)____ his train just in time. He was very grateful for their kindness.', 126, 3, '[{"q": "1", "answer": "C", "options": ["make", "take", "find", "buy"], "explanation": "找不到站台 find the platform"}, {"q": "2", "answer": "A", "options": ["leave", "stay", "open", "stop"], "explanation": "火车将离开 train would leave"}, {"q": "3", "answer": "B", "options": ["angrily", "politely", "quickly", "loudly"], "explanation": "礼貌地问 asked politely"}, {"q": "4", "answer": "B", "options": ["why", "which", "that", "how"], "explanation": "问哪个站台 which platform(后接名词只能which)"}, {"q": "5", "answer": "A", "options": ["stairs", "tree", "door", "window"], "explanation": "指向楼梯 pointed to the stairs"}, {"q": "6", "answer": "D", "options": ["start", "top", "side", "end"], "explanation": "大厅尽头 at the end"}, {"q": "7", "answer": "C", "options": ["asked", "left", "thanked", "called"], "explanation": "谢了他 thanked him"}, {"q": "8", "answer": "D", "options": ["why", "that", "when", "where"], "explanation": "在哪买水 where he could buy"}, {"q": "9", "answer": "A", "options": ["shop", "park", "bank", "school"], "explanation": "小商店 a small shop"}, {"q": "10", "answer": "B", "options": ["lost", "caught", "sold", "missed"], "explanation": "正好赶上火车 caught his train"}]'::jsonb, 4);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U3', 'Helping a Visitor', 'One afternoon, I was walking home when a (1)____ stopped me. He looked confused and was holding a (2)____. "Excuse me," he said politely, "do you know (3)____ I can find the City Museum?" I was happy to (4)____ him. "It''s not far," I said. "Go (5)____ this road and turn left at the bank." He thanked me, but he still looked (6)____. So I decided to (7)____ him there myself. As we walked, we talked about his (8)____ to our city. He told me he was from another country and loved Chinese (9)____. When we arrived, he shook my hand and thanked me warmly. Helping him made me feel (10)____. A small kind act can brighten someone''s whole day.', 120, 3, '[{"q": "1", "answer": "D", "options": ["driver", "friend", "teacher", "stranger"], "explanation": "陌生人 a stranger"}, {"q": "2", "answer": "A", "options": ["map", "book", "phone", "bag"], "explanation": "拿着地图 holding a map"}, {"q": "3", "answer": "B", "options": ["that", "where", "when", "why"], "explanation": "问博物馆在哪 where I can find"}, {"q": "4", "answer": "C", "options": ["leave", "stop", "help", "watch"], "explanation": "乐意帮他 help him"}, {"q": "5", "answer": "B", "options": ["off", "along", "up", "out"], "explanation": "沿这条路 go along this road"}, {"q": "6", "answer": "D", "options": ["angry", "tired", "happy", "confused"], "explanation": "仍然困惑 still looked confused"}, {"q": "7", "answer": "C", "options": ["buy", "sell", "take", "make"], "explanation": "带他去 take him there"}, {"q": "8", "answer": "A", "options": ["trip", "plan", "photo", "book"], "explanation": "他的旅行 his trip"}, {"q": "9", "answer": "A", "options": ["food", "weather", "money", "homework"], "explanation": "喜欢中国美食 Chinese food"}, {"q": "10", "answer": "B", "options": ["tired", "happy", "bored", "sorry"], "explanation": "感到开心 feel happy"}]'::jsonb, 5);
INSERT INTO public.junior_cloze (id, grade, volume, unit, title, body, word_count, difficulty, questions, sort_order) VALUES (gen_random_uuid(), 9, '9', 'U3', 'Good Manners Around the World', 'Good manners are important everywhere, but they can be a little (1)____ in different countries. In most places, however, being polite when you ask for (2)____ is always welcome. For example, starting with "Excuse me" is a (3)____ way to get someone''s attention. In some countries, people speak in a very (4)____ and indirect way to be polite. In others, people are more direct but still (5)____. No matter where you are, a (6)____ and a "thank you" are understood by everyone. When you visit a new place, it is (7)____ to learn a few polite words in the local language. This shows that you (8)____ the local culture. People will be more willing to (9)____ you if you make an effort. In the end, kindness and respect are a (10)____ that everyone understands.', 134, 3, '[{"q": "1", "answer": "A", "options": ["different", "hard", "easy", "same"], "explanation": "有点不同 a little different"}, {"q": "2", "answer": "B", "options": ["food", "directions", "money", "time"], "explanation": "问路时 ask for directions"}, {"q": "3", "answer": "B", "options": ["slow", "good", "strange", "bad"], "explanation": "好方法 a good way"}, {"q": "4", "answer": "A", "options": ["soft", "fast", "short", "loud"], "explanation": "温和的方式 soft and indirect"}, {"q": "5", "answer": "D", "options": ["sad", "rude", "lazy", "friendly"], "explanation": "仍然友好 still friendly"}, {"q": "6", "answer": "B", "options": ["ticket", "smile", "map", "key"], "explanation": "微笑 a smile"}, {"q": "7", "answer": "C", "options": ["hard", "boring", "helpful", "useless"], "explanation": "学几句很有用 helpful"}, {"q": "8", "answer": "C", "options": ["leave", "sell", "respect", "forget"], "explanation": "尊重当地文化 respect the culture"}, {"q": "9", "answer": "D", "options": ["fight", "leave", "stop", "help"], "explanation": "更愿意帮你 help you"}, {"q": "10", "answer": "A", "options": ["language", "game", "story", "price"], "explanation": "通用的语言 a language everyone understands"}]'::jsonb, 6);

-- ===== junior_listening_exercises (预期 6) =====
DELETE FROM public.junior_listening_exercises WHERE volume='9' AND unit='U3';
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U3 听力·对话 Asking the Way to the Library', '九年级 Unit3 听力·问路与礼貌请求', 2, 'Visitor: Excuse me, could you please tell me how I can get to the public library?
Local: Sure. Go straight down this street and you''ll see a big bank on your left. The library is right next to it.
Visitor: Thank you. Is it far from here?
Local: No, it''s just a five-minute walk.
Visitor: Great. Do you know if it''s open now?
Local: Yes, it stays open until six in the evening.
Visitor: Thanks a lot for your help!
Local: You''re welcome.', '访客:打扰一下,能告诉我怎么去公共图书馆吗?
当地人:当然。沿这条街直走,会看到左边有个大银行。图书馆就在它旁边。
访客:谢谢。离这儿远吗?
当地人:不远,走路五分钟。
访客:太好了。你知道现在开门吗?
当地人:开着,一直到晚上六点。
访客:非常感谢你的帮助!
当地人:不客气。', 'us_male', '[{"q": "Where does the visitor want to go?", "type": "choice", "answer": "D", "options": ["The bank.", "The station.", "A shop.", "The public library."]}, {"q": "Where is the library?", "type": "choice", "answer": "A", "options": ["Next to the bank.", "Across from the bank.", "Behind the bank.", "Inside the bank."]}, {"q": "How far is it?", "type": "choice", "answer": "B", "options": ["Two stops by bus.", "A five-minute walk.", "A ten-minute walk.", "Very far."]}, {"q": "When does the library close?", "type": "choice", "answer": "C", "options": ["It is closed.", "At five.", "At six in the evening.", "At noon."]}, {"q": "How does the local person sound?", "type": "choice", "answer": "B", "options": ["Angry.", "Helpful and friendly.", "Rude and busy.", "Tired and bored."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U3');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U3 听力·对话 Asking About Places to Visit', '九年级 Unit3 听力·问路与礼貌请求', 2, 'Tourist: Hi, could you tell me if there are any interesting places to visit here?
Guide: Of course! The City Museum is very famous, and many people enjoy it.
Tourist: That sounds great. Do you know when it opens?
Guide: It opens at nine in the morning and closes at five on weekdays.
Tourist: Perfect. How can I get there from the hotel?
Guide: You can take Bus No. 7. It stops right in front of the museum.
Tourist: Thank you so much for the information!
Guide: My pleasure. Enjoy your visit!', '游客:你好,能告诉我这里有什么好玩的地方吗?
导游:当然!城市博物馆很有名,很多人都喜欢。
游客:听起来不错。你知道它几点开门吗?
导游:工作日早上九点开,下午五点关。
游客:太好了。从酒店怎么去那里?
导游:你可以坐7路公交,它就停在博物馆门口。
游客:非常感谢你的信息!
导游:不客气,玩得开心!', 'us_male', '[{"q": "What does the guide recommend?", "type": "choice", "answer": "A", "options": ["The City Museum.", "A cinema.", "A park.", "A restaurant."]}, {"q": "When does the museum open?", "type": "choice", "answer": "B", "options": ["At ten.", "At nine in the morning.", "At noon.", "At eight."]}, {"q": "When does it close on weekdays?", "type": "choice", "answer": "B", "options": ["At six.", "At five.", "At seven.", "At four."]}, {"q": "How can the tourist get there?", "type": "choice", "answer": "C", "options": ["By taxi.", "On foot.", "By Bus No. 7.", "By subway."]}, {"q": "Where are the two people probably talking?", "type": "choice", "answer": "C", "options": ["In a classroom.", "In a museum.", "At a tourist information desk.", "At home."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U3');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U3 听力·对话 Ordering at a Restaurant', '九年级 Unit3 听力·问路与礼貌请求', 2, 'Customer: Good evening. Could you please tell me where I can wash my hands first?
Waiter: Certainly. The restrooms are at the end of the hall, next to the stairs.
Customer: Thank you. I''d also like to know what is popular here.
Waiter: Our beef noodles and dumplings are the most popular dishes.
Customer: I''ll have a bowl of beef noodles and a cup of green tea, please.
Waiter: No problem. Your food will be ready in about ten minutes.
Customer: Great, thank you.
Waiter: You''re welcome. Enjoy your meal!', '顾客:晚上好。能告诉我先去哪里洗手吗?
服务员:当然。洗手间在走廊尽头,楼梯旁边。
顾客:谢谢。我还想知道这里什么最受欢迎。
服务员:我们的牛肉面和饺子最受欢迎。
顾客:请给我一碗牛肉面和一杯绿茶。
服务员:没问题,大约十分钟做好。
顾客:太好了,谢谢。
服务员:不客气,祝您用餐愉快!', 'us_male', '[{"q": "Where does the customer want to go first?", "type": "choice", "answer": "C", "options": ["The kitchen.", "The cashier.", "The restroom.", "The stairs."]}, {"q": "Where are the restrooms?", "type": "choice", "answer": "C", "options": ["Upstairs.", "Near the entrance.", "Next to the stairs.", "Behind the kitchen."]}, {"q": "What does the customer order?", "type": "choice", "answer": "D", "options": ["Dumplings and juice.", "Chicken rice and coffee.", "Beef noodles and milk.", "Beef noodles and green tea."]}, {"q": "How long will the food take?", "type": "choice", "answer": "D", "options": ["About twenty minutes.", "About fifteen minutes.", "About five minutes.", "About ten minutes."]}, {"q": "What best describes the conversation?", "type": "choice", "answer": "B", "options": ["A closed restaurant.", "A polite request for information and an order.", "A refusal to help.", "A complaint about food."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U3');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U3 听力·对话 Shopping for Books', '九年级 Unit3 听力·问路与礼貌请求', 2, 'Customer: Excuse me, could you please tell me where I can find English dictionaries?
Assistant: Certainly. They''re on the second floor, next to the reading area.
Customer: Thanks. I''m also looking for a notebook.
Assistant: Notebooks are on the same floor. Just walk past the dictionaries.
Customer: Do you have any on sale today?
Assistant: Yes. If you buy two, you get the third one at half price.
Customer: That sounds good. I''ll take three notebooks and one dictionary.
Assistant: Great. Please pay at the cashier near the exit.', '顾客:打扰一下,能告诉我哪里能找到英语词典吗?
店员:当然。在二楼,阅读区旁边。
顾客:谢谢。我还想买笔记本。
店员:笔记本在同一层,经过词典区就是。
顾客:今天有打折的吗?
店员:有。买两本第三本半价。
顾客:不错。我要三本笔记本和一本词典。
店员:好的,请到出口附近的收银台付款。', 'us_male', '[{"q": "What is the customer looking for first?", "type": "choice", "answer": "D", "options": ["Pens.", "Notebooks.", "Storybooks.", "English dictionaries."]}, {"q": "Where are the dictionaries?", "type": "choice", "answer": "A", "options": ["On the second floor.", "At the entrance.", "On the first floor.", "Near the exit."]}, {"q": "What is the special offer?", "type": "choice", "answer": "D", "options": ["Buy one, get one free.", "Free dictionary.", "20% off all books.", "Buy two notebooks, get the third at half price."]}, {"q": "What does the customer finally buy?", "type": "choice", "answer": "A", "options": ["Three notebooks and one dictionary.", "One notebook and one dictionary.", "Three dictionaries.", "Two notebooks."]}, {"q": "Where should the customer pay?", "type": "choice", "answer": "A", "options": ["At the cashier near the exit.", "At the reading area.", "On the second floor.", "At the entrance."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U3');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U3 听力·短文 Welcome to Maple City', '九年级 Unit3 听力·问路与礼貌请求', 2, 'Welcome to Maple City! Before you start your trip, here is some useful information. The Visitor Center is across from the train station. There you can get free maps, ask for directions, or buy bus cards. The staff are friendly and always ready to help. The City Museum is open from nine in the morning to half past five. If you want to visit Green Park, you can take Bus No. 15, and the ride takes about twenty minutes. Please remember to keep the city clean and be polite when asking questions. A smile and a simple "thank you" can make your trip even more enjoyable. We hope you have a wonderful time here!', '欢迎来到枫叶城!开始旅行前,这里有些有用信息。游客中心在火车站对面。在那里你可以领免费地图、问路或买公交卡。工作人员很友好,随时乐意帮忙。城市博物馆早九点到下午五点半开放。想去绿园公园,可坐15路公交,车程约二十分钟。请记得保持城市整洁、礼貌提问。一个微笑和一句谢谢能让旅行更愉快。祝你在这里玩得开心!', 'us_female', '[{"q": "Where is the Visitor Center?", "type": "choice", "answer": "B", "options": ["At the bus stop.", "Across from the train station.", "Inside Green Park.", "Next to the museum."]}, {"q": "What can visitors NOT do at the Visitor Center?", "type": "choice", "answer": "D", "options": ["Buy bus cards.", "Get free maps.", "Ask for directions.", "Buy museum tickets."]}, {"q": "How can visitors get to Green Park?", "type": "choice", "answer": "C", "options": ["By subway.", "By taxi.", "By Bus No. 15.", "By Bus No. 5."]}, {"q": "How long does the ride to Green Park take?", "type": "choice", "answer": "A", "options": ["About twenty minutes.", "About thirty minutes.", "About fifteen minutes.", "About ten minutes."]}, {"q": "What does the speaker advise visitors to do?", "type": "choice", "answer": "A", "options": ["Be polite and keep the city clean.", "Speak loudly.", "Travel at night.", "Walk everywhere."]}]'::jsonb, '[]'::jsonb, 'short', '9', 'U3');
INSERT INTO public.junior_listening_exercises (id, grade, title, topic, difficulty, transcript, translation_cn, speaker, questions, key_vocab, kind, volume, unit) VALUES (gen_random_uuid(), 9, '九年级 U3 听力·对话 Asking for Help at School', '九年级 Unit3 听力·问路与礼貌请求', 2, 'Student: Excuse me, Ms. Brown. Could you please tell me where the language lab is?
Teacher: Of course. Go down this hallway and turn right at the end. It''s on the second floor, next to the computer room.
Student: Thank you. I also want to borrow an English dictionary. Is there a library here?
Teacher: Yes. The library is on the first floor, and it''s open until half past five.
Student: Do I need a student card to borrow books?
Teacher: Yes, you do. Just show your card at the front desk.
Student: I see. Thank you for your help.
Teacher: You''re welcome. Have a good day!', '学生:打扰一下,Brown老师。能告诉我语言实验室在哪吗?
老师:当然。沿走廊走,尽头右转。在二楼,电脑室旁边。
学生:谢谢。我还想借本英语词典。这里有图书馆吗?
老师:有。图书馆在一楼,开到五点半。
学生:借书需要学生证吗?
老师:需要。在服务台出示你的卡就行。
学生:明白了,谢谢您的帮助。
老师:不客气,祝你愉快!', 'us_male', '[{"q": "Where does the student want to go first?", "type": "choice", "answer": "A", "options": ["The language lab.", "The library.", "The computer room.", "The playground."]}, {"q": "Where is the language lab?", "type": "choice", "answer": "B", "options": ["Next to the library.", "On the second floor, next to the computer room.", "On the first floor.", "Across from the playground."]}, {"q": "What does the student want to borrow?", "type": "choice", "answer": "C", "options": ["A school map.", "A magazine.", "An English dictionary.", "A science book."]}, {"q": "What does the student need to borrow books?", "type": "choice", "answer": "C", "options": ["A library key.", "A notebook.", "A student card.", "A bus card."]}, {"q": "What is the main purpose of the conversation?", "type": "choice", "answer": "D", "options": ["To discuss homework.", "To borrow money.", "To invite the teacher out.", "To ask for directions and school information politely."]}]'::jsonb, '[]'::jsonb, 'long', '9', 'U3');

-- ===== junior_writing_prompts (预期 1) =====
INSERT INTO public.junior_writing_prompts (id, grade, topic, prompt_cn, prompt_en, requirements, min_words, max_words, sample_answer, scoring_rubric, difficulty, title_en, high_sentences, error_pairs, paragraph_template, volume, unit) SELECT gen_random_uuid(), 9, 'A Guide for My Foreign Friend', '你的外国朋友 David 下个月要来你的城市旅游,想去市图书馆(City Library)但不知道怎么走。请写一封约80词的邮件,告诉他怎么去、可以怎样礼貌地问路,并表示欢迎。', 'Write a short passage on the topic: "A Guide for My Foreign Friend".', '["欢迎David来访", "市图书馆的位置/怎么从火车站去(公交或步行)", "教他礼貌问路的句型(Excuse me / Could you please tell me...?)", "迷路时怎么办(找路标或礼貌问当地人)"]'::jsonb, 70, 100, 'Hi David,
I''m glad you''ll visit my city next month. The City Library isn''t far from the train station. You can take Bus No. 8, or walk there in about fifteen minutes. If you need help, just ask politely. You can say, "Excuse me, could you please tell me how I can get to the City Library?" If you get lost, don''t worry — look for road signs or kindly ask a local person. People here are very friendly. Welcome to my city!
Best,
Li Hua', 'content:涵盖4要点(欢迎/位置怎么去/礼貌问路句型/迷路怎么办)；language:正确使用礼貌问路句型 Could you please…?；指路表达 go straight/turn left/next to；structure:邮件格式齐(称呼+正文+落款)、条理清晰；wordcount:约80词', 3, 'A Guide for My Foreign Friend', '["I''m glad you''ll visit...", "Excuse me, could you please tell me...?", "Go straight / turn left / It''s next to...", "If you get lost, don''t worry...", "Welcome to my city!"]'::jsonb, '[]'::jsonb, '要点:欢迎David来访；市图书馆的位置/怎么从火车站去(公交或步行)；教他礼貌问路的句型(Excuse me / Could you please tell me...?)；迷路时怎么办(找路标或礼貌问当地人)', '9', 'U3' WHERE NOT EXISTS (SELECT 1 FROM public.junior_writing_prompts WHERE volume='9' AND unit='U3' AND topic='A Guide for My Foreign Friend');

COMMIT;

-- ===== count 校验 =====
SELECT 'grammar_points' k, count(*) v, 3 expect FROM public.junior_grammar_points WHERE volume='9' AND unit='U3'
UNION ALL SELECT 'grammar_questions', count(*), 60 FROM public.junior_grammar_questions x JOIN public.junior_grammar_points p ON x.point_id=p.id WHERE p.volume='9' AND p.unit='U3'
UNION ALL SELECT 'reading', count(*), 6 FROM public.junior_reading WHERE volume='9' AND unit='U3'
UNION ALL SELECT 'cloze', count(*), 6 FROM public.junior_cloze WHERE volume='9' AND unit='U3'
UNION ALL SELECT 'listening', count(*), 6 FROM public.junior_listening_exercises WHERE volume='9' AND unit='U3'
UNION ALL SELECT 'writing', count(*), 1 FROM public.junior_writing_prompts WHERE volume='9' AND unit='U3';