-- g7.xx / g9.xx grammar points + 5-level question banks for junior hub
-- Generated by scripts/generate_junior_g7_g9_grammar_migration.py

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.01', 'be 动词 · Verb be (am/is/are)', 'A2', 7, '对应：7A 问候与自我介绍', E'【结构】I am / You are / He is / She is / It is / We are / They are
【用法】表身份、状态、位置。
【例句】I am fine. / She is a student.
【易错】✗ He are → ✓ He is', '[]'::jsonb, 101, 1 FROM junior_grammar_categories WHERE code = 'tense' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.02', '指示代词 this/that · Demonstratives', 'A2', 7, '对应：7A SU2', E'【结构】This is ... / That is ...
【用法】this 近处，that 远处。
【例句】This is a ruler. / What''s that in English?', '[]'::jsonb, 102, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.03', 'What color · 颜色问句', 'A2', 7, '对应：7A SU3', E'【结构】What color is it? — It''s + 颜色.
【例句】What color is your bag? — It''s blue.', '[]'::jsonb, 103, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.04', '名词所有格 · Possessive ''s', 'A2', 7, '对应：7A U2', E'【结构】名词 + ''s + 名词
【例句】This is my sister''s book.
【易错】✗ my sister book → ✓ my sister''s book', '[]'::jsonb, 104, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.05', '一般疑问句 Is this...? · Yes/No Questions', 'A2', 7, '对应：7A U3', E'【结构】Beach/Are + 主语 + 名词?
【回答】Yes, it is. / No, it isn''t.
【例句】Is this your pencil?', '[]'::jsonb, 105, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.06', 'Where 问句与介词 · Where + prepositions', 'A2', 7, '对应：7A U4', E'【结构】Where is ...? — It''s on/in/under...
【例句】Where''s my schoolbag? — It''s on the chair.', '[]'::jsonb, 106, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.07', 'Do you have...? · Have questions', 'A2', 7, '对应：7A U5', E'【结构】Do you have + 名词?
【回答】Yes, I do. / No, I don''t.
【例句】Do you have a soccer ball?', '[]'::jsonb, 107, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.08', 'Do you like + countable nouns', 'A2', 7, '对应：7A U6', E'【结构】Do you like + 复数/不可数?
【例句】Do you like bananas? — Yes, I do.', '[]'::jsonb, 108, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.09', 'How much 与价格 · How much', 'A2', 7, '对应：7A U7', E'【结构】How much is/are ...?
【例句】How much are these socks? — They''re five dollars.', '[]'::jsonb, 109, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.10', 'When 与序数词 · When + ordinals', 'A2', 7, '对应：7A U8', E'【结构】When is your birthday? — It''s on + 日期.
【例句】My birthday is on May 2nd.', '[]'::jsonb, 110, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.11', 'Why 与 because · Why/because', 'A2', 7, '对应：7A U9 / 7B U5', E'【结构】Why do you like ...? — Because ...
【例句】Why do you like science? — Because it''s interesting.', '[]'::jsonb, 111, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.12', 'can 表能力 · Modal can', 'A2', 7, '对应：7B U1', E'【结构】Can + 主语 + 动词原形?
【例句】Can you play the guitar? — Yes, I can.', '[]'::jsonb, 112, 1 FROM junior_grammar_categories WHERE code = 'verb' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.13', 'What time · 时刻表达', 'A2', 7, '对应：7B U2', E'【结构】What time do you ...? — I ... at + 时刻.
【例句】What time do you go to school? — At seven o''clock.', '[]'::jsonb, 113, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.14', 'How 问交通方式 · How + transport', 'A2', 7, '对应：7B U3', E'【结构】How do you get to ...? — By bus/bike/on foot.
【例句】How do you get to school? — I take the bus.', '[]'::jsonb, 114, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.15', '祈使句与 don''t · Imperatives', 'A2', 7, '对应：7B U4 / 8A U8', E'【结构】动词原形开头 / Don''t + 动词原形
【例句】Don''t eat in class. / Be quiet, please.', '[]'::jsonb, 115, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.16', 'There be 句型 · There is/are', 'A2', 7, '对应：7B U8', E'【结构】There is + 单数 / There are + 复数
【例句】Is there a post office near here? — Yes, there is.', '[]'::jsonb, 116, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.17', 'What does he look like? · Appearance', 'A2', 7, '对应：7B U9', E'【结构】What does ... look like? — He/She is tall/has...
【例句】What does he look like? — He is of medium height.', '[]'::jsonb, 117, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g7.18', 'would like 点餐 · Would like', 'A2', 7, '对应：7B U10', E'【结构】I''d like + 名词 / Would you like ...?
【例句】I''d like some noodles, please.', '[]'::jsonb, 118, 1 FROM junior_grammar_categories WHERE code = 'verb' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g9.01', '一般现在时被动 · Present Passive', 'A2', 9, '对应：9 U1', E'【结构】am/is/are + 过去分词
【例句】English is spoken in many countries.', '[]'::jsonb, 101, 1 FROM junior_grammar_categories WHERE code = 'tense' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g9.02', 'used to 与感叹句 · used to / exclamations', 'A2', 9, '对应：9 U2', E'【结构】used to + 动词原形 / What + (a/an) + adj + n!
【例句】I used to be shy. / What a beautiful day!', '[]'::jsonb, 102, 1 FROM junior_grammar_categories WHERE code = 'tense' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g9.03', '过去完成时 · Past Perfect', 'A2', 9, '对应：9 U8', E'【结构】had + 过去分词
【用法】过去的过去。
【例句】When I got home, he had already left.', '[]'::jsonb, 103, 1 FROM junior_grammar_categories WHERE code = 'tense' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g9.04', '情态动词表推测 · Modals for deduction', 'A2', 9, '对应：9 U11', E'【结构】must / can''t / might + 动词原形
【例句】He must be at home. / It can''t be true.', '[]'::jsonb, 104, 1 FROM junior_grammar_categories WHERE code = 'verb' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

INSERT INTO junior_grammar_points (category_id, code, title, cefr, grade, summary, explanation_md, examples, sort_order, content_depth) SELECT id, 'g9.05', '中考语法综合 · Review mix', 'A2', 9, '对应：9 U12–U14', E'综合复习：时态、从句、被动、情況等中考高频考点。', '[]'::jsonb, 105, 1 FROM junior_grammar_categories WHERE code = 'other' ON CONFLICT (code) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, explanation_md = EXCLUDED.explanation_md, content_depth = GREATEST(junior_grammar_points.content_depth, 1);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.01')
  AND sort_order BETWEEN 7100 AND 7199;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.01')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('I ___ a student.', 'mcq', 'am', 'is', 'are', 'be', 'A', NULL::text[], 'I → am。', '{}'::jsonb, NULL, 'g7.01', false, 1, 7100),
  ('She ___ my English teacher.', 'mcq', 'am', 'is', 'are', 'be', 'B', NULL::text[], 'She → is。', '{}'::jsonb, NULL, 'g7.01', false, 1, 7101),
  ('They ___ in Class 3.', 'mcq', 'am', 'is', 'are', 'be', 'C', NULL::text[], 'They → are。', '{}'::jsonb, NULL, 'g7.01', false, 1, 7102),
  ('— How ___ you? — I''m fine.', 'mcq', 'am', 'is', 'are', 'be', 'C', NULL::text[], 'How are you?', '{}'::jsonb, NULL, 'g7.01', false, 1, 7103),
  ('Tom ____ (be) very happy today.', 'fill', NULL, NULL, NULL, NULL, 'is', ARRAY['is']::text[], 'Tom 单数 → is。', '{}'::jsonb, NULL, 'g7.01', false, 1, 7104),
  ('We ____ (be) good friends.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], 'We → are。', '{}'::jsonb, NULL, 'g7.01', false, 1, 7105),
  ('My parents ____ (be) at home now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], 'parents 复数。', '{}'::jsonb, NULL, 'g7.01', false, 1, 7106),
  ('改错： "He are a boy."', 'correction', NULL, NULL, NULL, NULL, 'He is a boy.', ARRAY['He is a boy.']::text[], 'He → is。', '{}'::jsonb, NULL, 'g7.01', true, 2, 7107),
  ('改错： "I is fine, thank you."', 'correction', NULL, NULL, NULL, NULL, 'I am fine, thank you.', ARRAY['I am fine, thank you.']::text[], 'I → am。', '{}'::jsonb, NULL, 'g7.01', true, 2, 7108),
  ('句型转换（否定）： "She is a nurse."', 'transform', NULL, NULL, NULL, NULL, 'She is not a nurse.', ARRAY['She is not a nurse.']::text[], 'be + not。', '{}'::jsonb, NULL, 'g7.01', true, 2, 7109),
  ('句型转换（疑问）： "They are students."', 'transform', NULL, NULL, NULL, NULL, 'Are they students?', ARRAY['Are they students?']::text[], 'be 提前。', '{}'::jsonb, NULL, 'g7.01', true, 2, 7110),
  ('把这句话译成英文：我是七年级学生。', 'translation', NULL, NULL, NULL, NULL, 'I am a Grade 7 student.', ARRAY['I am a Grade 7 student.']::text[], 'I am + 名词。', '{}'::jsonb, NULL, 'g7.01', true, 3, 7111)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.02')
  AND sort_order BETWEEN 7200 AND 7299;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.02')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「指示代词 this/that」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查指示代词 this/that。', '{}'::jsonb, NULL, 'g7.02', false, 1, 7200),
  ('Which sentence uses 「指示代词 this/that」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.02。', '{}'::jsonb, NULL, 'g7.02', false, 1, 7201),
  ('Fill in: This question tests 「指示代词 this/that」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], '指示代词 this/that基础题。', '{}'::jsonb, NULL, 'g7.02', false, 1, 7202),
  ('「指示代词 this/that」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.02。', '{}'::jsonb, NULL, 'g7.02', false, 1, 7203),
  ('Complete: (g7.02) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.02', false, 1, 7204),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.02', false, 1, 7205),
  ('Fill: They ____ (be) learning 「指示代词 this/that」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.02', false, 1, 7206),
  ('改错： "This sentence have a 「指示代词 this/that」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「指示代词 this/that」 mistake.', ARRAY['This sentence has a 「指示代词 this/that」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.02', true, 2, 7207),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「指示代词 this/that」.', ARRAY['He doesn''t know 「指示代词 this/that」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.02', true, 2, 7208),
  ('句型转换： "I learn 「指示代词 this/that」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「指示代词 this/that」?', ARRAY['Do you learn 「指示代词 this/that」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.02', true, 2, 7209),
  ('句型转换： "She likes 「指示代词 this/that」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「指示代词 this/that」.', ARRAY['She doesn''t like 「指示代词 this/that」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.02', true, 2, 7210),
  ('把这句话译成英文：我学习了指示代词 this/that。', 'translation', NULL, NULL, NULL, NULL, 'I learned 指示代词.', ARRAY['I learned 指示代词.']::text[], '翻译考查指示代词 this/that。', '{}'::jsonb, NULL, 'g7.02', true, 3, 7211)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.03')
  AND sort_order BETWEEN 7300 AND 7399;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.03')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「What color」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查What color。', '{}'::jsonb, NULL, 'g7.03', false, 1, 7300),
  ('Which sentence uses 「What color」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.03。', '{}'::jsonb, NULL, 'g7.03', false, 1, 7301),
  ('Fill in: This question tests 「What color」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'What color基础题。', '{}'::jsonb, NULL, 'g7.03', false, 1, 7302),
  ('「What color」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.03。', '{}'::jsonb, NULL, 'g7.03', false, 1, 7303),
  ('Complete: (g7.03) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.03', false, 1, 7304),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.03', false, 1, 7305),
  ('Fill: They ____ (be) learning 「What color」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.03', false, 1, 7306),
  ('改错： "This sentence have a 「What color」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「What color」 mistake.', ARRAY['This sentence has a 「What color」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.03', true, 2, 7307),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「What color」.', ARRAY['He doesn''t know 「What color」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.03', true, 2, 7308),
  ('句型转换： "I learn 「What color」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「What color」?', ARRAY['Do you learn 「What color」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.03', true, 2, 7309),
  ('句型转换： "She likes 「What color」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「What color」.', ARRAY['She doesn''t like 「What color」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.03', true, 2, 7310),
  ('把这句话译成英文：我学习了What color。', 'translation', NULL, NULL, NULL, NULL, 'I learned What.', ARRAY['I learned What.']::text[], '翻译考查What color。', '{}'::jsonb, NULL, 'g7.03', true, 3, 7311)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.04')
  AND sort_order BETWEEN 7400 AND 7499;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.04')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「名词所有格」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查名词所有格。', '{}'::jsonb, NULL, 'g7.04', false, 1, 7400),
  ('Which sentence uses 「名词所有格」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.04。', '{}'::jsonb, NULL, 'g7.04', false, 1, 7401),
  ('Fill in: This question tests 「名词所有格」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], '名词所有格基础题。', '{}'::jsonb, NULL, 'g7.04', false, 1, 7402),
  ('「名词所有格」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.04。', '{}'::jsonb, NULL, 'g7.04', false, 1, 7403),
  ('Complete: (g7.04) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.04', false, 1, 7404),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.04', false, 1, 7405),
  ('Fill: They ____ (be) learning 「名词所有格」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.04', false, 1, 7406),
  ('改错： "This sentence have a 「名词所有格」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「名词所有格」 mistake.', ARRAY['This sentence has a 「名词所有格」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.04', true, 2, 7407),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「名词所有格」.', ARRAY['He doesn''t know 「名词所有格」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.04', true, 2, 7408),
  ('句型转换： "I learn 「名词所有格」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「名词所有格」?', ARRAY['Do you learn 「名词所有格」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.04', true, 2, 7409),
  ('句型转换： "She likes 「名词所有格」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「名词所有格」.', ARRAY['She doesn''t like 「名词所有格」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.04', true, 2, 7410),
  ('把这句话译成英文：我学习了名词所有格。', 'translation', NULL, NULL, NULL, NULL, 'I learned 名词所有格.', ARRAY['I learned 名词所有格.']::text[], '翻译考查名词所有格。', '{}'::jsonb, NULL, 'g7.04', true, 3, 7411)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.05')
  AND sort_order BETWEEN 7500 AND 7599;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.05')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「一般疑问句 Is this...?」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查一般疑问句 Is this...?。', '{}'::jsonb, NULL, 'g7.05', false, 1, 7500),
  ('Which sentence uses 「一般疑问句 Is this...?」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.05。', '{}'::jsonb, NULL, 'g7.05', false, 1, 7501),
  ('Fill in: This question tests 「一般疑问句 Is this...?」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], '一般疑问句 Is this...?基础题。', '{}'::jsonb, NULL, 'g7.05', false, 1, 7502),
  ('「一般疑问句 Is this...?」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.05。', '{}'::jsonb, NULL, 'g7.05', false, 1, 7503),
  ('Complete: (g7.05) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.05', false, 1, 7504),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.05', false, 1, 7505),
  ('Fill: They ____ (be) learning 「一般疑问句 Is this...?」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.05', false, 1, 7506),
  ('改错： "This sentence have a 「一般疑问句 Is this...?」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「一般疑问句 Is this...?」 mistake.', ARRAY['This sentence has a 「一般疑问句 Is this...?」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.05', true, 2, 7507),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「一般疑问句 Is this...?」.', ARRAY['He doesn''t know 「一般疑问句 Is this...?」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.05', true, 2, 7508),
  ('句型转换： "I learn 「一般疑问句 Is this...?」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「一般疑问句 Is this...?」?', ARRAY['Do you learn 「一般疑问句 Is this...?」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.05', true, 2, 7509),
  ('句型转换： "She likes 「一般疑问句 Is this...?」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「一般疑问句 Is this...?」.', ARRAY['She doesn''t like 「一般疑问句 Is this...?」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.05', true, 2, 7510),
  ('把这句话译成英文：我学习了一般疑问句 Is this...?。', 'translation', NULL, NULL, NULL, NULL, 'I learned 一般疑问句.', ARRAY['I learned 一般疑问句.']::text[], '翻译考查一般疑问句 Is this...?。', '{}'::jsonb, NULL, 'g7.05', true, 3, 7511)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.06')
  AND sort_order BETWEEN 7600 AND 7699;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.06')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「Where 问句与介词」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查Where 问句与介词。', '{}'::jsonb, NULL, 'g7.06', false, 1, 7600),
  ('Which sentence uses 「Where 问句与介词」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.06。', '{}'::jsonb, NULL, 'g7.06', false, 1, 7601),
  ('Fill in: This question tests 「Where 问句与介词」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'Where 问句与介词基础题。', '{}'::jsonb, NULL, 'g7.06', false, 1, 7602),
  ('「Where 问句与介词」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.06。', '{}'::jsonb, NULL, 'g7.06', false, 1, 7603),
  ('Complete: (g7.06) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.06', false, 1, 7604),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.06', false, 1, 7605),
  ('Fill: They ____ (be) learning 「Where 问句与介词」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.06', false, 1, 7606),
  ('改错： "This sentence have a 「Where 问句与介词」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「Where 问句与介词」 mistake.', ARRAY['This sentence has a 「Where 问句与介词」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.06', true, 2, 7607),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「Where 问句与介词」.', ARRAY['He doesn''t know 「Where 问句与介词」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.06', true, 2, 7608),
  ('句型转换： "I learn 「Where 问句与介词」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「Where 问句与介词」?', ARRAY['Do you learn 「Where 问句与介词」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.06', true, 2, 7609),
  ('句型转换： "She likes 「Where 问句与介词」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「Where 问句与介词」.', ARRAY['She doesn''t like 「Where 问句与介词」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.06', true, 2, 7610),
  ('把这句话译成英文：我学习了Where 问句与介词。', 'translation', NULL, NULL, NULL, NULL, 'I learned Where.', ARRAY['I learned Where.']::text[], '翻译考查Where 问句与介词。', '{}'::jsonb, NULL, 'g7.06', true, 3, 7611)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.07')
  AND sort_order BETWEEN 7700 AND 7799;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.07')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「Do you have...?」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查Do you have...?。', '{}'::jsonb, NULL, 'g7.07', false, 1, 7700),
  ('Which sentence uses 「Do you have...?」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.07。', '{}'::jsonb, NULL, 'g7.07', false, 1, 7701),
  ('Fill in: This question tests 「Do you have...?」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'Do you have...?基础题。', '{}'::jsonb, NULL, 'g7.07', false, 1, 7702),
  ('「Do you have...?」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.07。', '{}'::jsonb, NULL, 'g7.07', false, 1, 7703),
  ('Complete: (g7.07) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.07', false, 1, 7704),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.07', false, 1, 7705),
  ('Fill: They ____ (be) learning 「Do you have...?」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.07', false, 1, 7706),
  ('改错： "This sentence have a 「Do you have...?」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「Do you have...?」 mistake.', ARRAY['This sentence has a 「Do you have...?」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.07', true, 2, 7707),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「Do you have...?」.', ARRAY['He doesn''t know 「Do you have...?」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.07', true, 2, 7708),
  ('句型转换： "I learn 「Do you have...?」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「Do you have...?」?', ARRAY['Do you learn 「Do you have...?」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.07', true, 2, 7709),
  ('句型转换： "She likes 「Do you have...?」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「Do you have...?」.', ARRAY['She doesn''t like 「Do you have...?」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.07', true, 2, 7710),
  ('把这句话译成英文：我学习了Do you have...?。', 'translation', NULL, NULL, NULL, NULL, 'I learned Do.', ARRAY['I learned Do.']::text[], '翻译考查Do you have...?。', '{}'::jsonb, NULL, 'g7.07', true, 3, 7711)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.08')
  AND sort_order BETWEEN 7800 AND 7899;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.08')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「Do you like + countable nouns」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查Do you like + countable nouns。', '{}'::jsonb, NULL, 'g7.08', false, 1, 7800),
  ('Which sentence uses 「Do you like + countable nouns」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.08。', '{}'::jsonb, NULL, 'g7.08', false, 1, 7801),
  ('Fill in: This question tests 「Do you like + countable nouns」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'Do you like + countable nouns基础题。', '{}'::jsonb, NULL, 'g7.08', false, 1, 7802),
  ('「Do you like + countable nouns」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.08。', '{}'::jsonb, NULL, 'g7.08', false, 1, 7803),
  ('Complete: (g7.08) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.08', false, 1, 7804),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.08', false, 1, 7805),
  ('Fill: They ____ (be) learning 「Do you like + countable nouns」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.08', false, 1, 7806),
  ('改错： "This sentence have a 「Do you like + countable nouns」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「Do you like + countable nouns」 mistake.', ARRAY['This sentence has a 「Do you like + countable nouns」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.08', true, 2, 7807),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「Do you like + countable nouns」.', ARRAY['He doesn''t know 「Do you like + countable nouns」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.08', true, 2, 7808),
  ('句型转换： "I learn 「Do you like + countable nouns」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「Do you like + countable nouns」?', ARRAY['Do you learn 「Do you like + countable nouns」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.08', true, 2, 7809),
  ('句型转换： "She likes 「Do you like + countable nouns」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「Do you like + countable nouns」.', ARRAY['She doesn''t like 「Do you like + countable nouns」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.08', true, 2, 7810),
  ('把这句话译成英文：我学习了Do you like + countable nouns。', 'translation', NULL, NULL, NULL, NULL, 'I learned Do.', ARRAY['I learned Do.']::text[], '翻译考查Do you like + countable nouns。', '{}'::jsonb, NULL, 'g7.08', true, 3, 7811)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.09')
  AND sort_order BETWEEN 7900 AND 7999;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.09')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「How much 与价格」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查How much 与价格。', '{}'::jsonb, NULL, 'g7.09', false, 1, 7900),
  ('Which sentence uses 「How much 与价格」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.09。', '{}'::jsonb, NULL, 'g7.09', false, 1, 7901),
  ('Fill in: This question tests 「How much 与价格」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'How much 与价格基础题。', '{}'::jsonb, NULL, 'g7.09', false, 1, 7902),
  ('「How much 与价格」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.09。', '{}'::jsonb, NULL, 'g7.09', false, 1, 7903),
  ('Complete: (g7.09) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.09', false, 1, 7904),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.09', false, 1, 7905),
  ('Fill: They ____ (be) learning 「How much 与价格」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.09', false, 1, 7906),
  ('改错： "This sentence have a 「How much 与价格」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「How much 与价格」 mistake.', ARRAY['This sentence has a 「How much 与价格」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.09', true, 2, 7907),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「How much 与价格」.', ARRAY['He doesn''t know 「How much 与价格」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.09', true, 2, 7908),
  ('句型转换： "I learn 「How much 与价格」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「How much 与价格」?', ARRAY['Do you learn 「How much 与价格」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.09', true, 2, 7909),
  ('句型转换： "She likes 「How much 与价格」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「How much 与价格」.', ARRAY['She doesn''t like 「How much 与价格」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.09', true, 2, 7910),
  ('把这句话译成英文：我学习了How much 与价格。', 'translation', NULL, NULL, NULL, NULL, 'I learned How.', ARRAY['I learned How.']::text[], '翻译考查How much 与价格。', '{}'::jsonb, NULL, 'g7.09', true, 3, 7911)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.10')
  AND sort_order BETWEEN 8000 AND 8099;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.10')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「When 与序数词」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查When 与序数词。', '{}'::jsonb, NULL, 'g7.10', false, 1, 8000),
  ('Which sentence uses 「When 与序数词」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.10。', '{}'::jsonb, NULL, 'g7.10', false, 1, 8001),
  ('Fill in: This question tests 「When 与序数词」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'When 与序数词基础题。', '{}'::jsonb, NULL, 'g7.10', false, 1, 8002),
  ('「When 与序数词」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.10。', '{}'::jsonb, NULL, 'g7.10', false, 1, 8003),
  ('Complete: (g7.10) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.10', false, 1, 8004),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.10', false, 1, 8005),
  ('Fill: They ____ (be) learning 「When 与序数词」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.10', false, 1, 8006),
  ('改错： "This sentence have a 「When 与序数词」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「When 与序数词」 mistake.', ARRAY['This sentence has a 「When 与序数词」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.10', true, 2, 8007),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「When 与序数词」.', ARRAY['He doesn''t know 「When 与序数词」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.10', true, 2, 8008),
  ('句型转换： "I learn 「When 与序数词」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「When 与序数词」?', ARRAY['Do you learn 「When 与序数词」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.10', true, 2, 8009),
  ('句型转换： "She likes 「When 与序数词」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「When 与序数词」.', ARRAY['She doesn''t like 「When 与序数词」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.10', true, 2, 8010),
  ('把这句话译成英文：我学习了When 与序数词。', 'translation', NULL, NULL, NULL, NULL, 'I learned When.', ARRAY['I learned When.']::text[], '翻译考查When 与序数词。', '{}'::jsonb, NULL, 'g7.10', true, 3, 8011)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.11')
  AND sort_order BETWEEN 8100 AND 8199;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.11')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「Why 与 because」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查Why 与 because。', '{}'::jsonb, NULL, 'g7.11', false, 1, 8100),
  ('Which sentence uses 「Why 与 because」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.11。', '{}'::jsonb, NULL, 'g7.11', false, 1, 8101),
  ('Fill in: This question tests 「Why 与 because」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'Why 与 because基础题。', '{}'::jsonb, NULL, 'g7.11', false, 1, 8102),
  ('「Why 与 because」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.11。', '{}'::jsonb, NULL, 'g7.11', false, 1, 8103),
  ('Complete: (g7.11) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.11', false, 1, 8104),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.11', false, 1, 8105),
  ('Fill: They ____ (be) learning 「Why 与 because」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.11', false, 1, 8106),
  ('改错： "This sentence have a 「Why 与 because」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「Why 与 because」 mistake.', ARRAY['This sentence has a 「Why 与 because」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.11', true, 2, 8107),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「Why 与 because」.', ARRAY['He doesn''t know 「Why 与 because」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.11', true, 2, 8108),
  ('句型转换： "I learn 「Why 与 because」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「Why 与 because」?', ARRAY['Do you learn 「Why 与 because」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.11', true, 2, 8109),
  ('句型转换： "She likes 「Why 与 because」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「Why 与 because」.', ARRAY['She doesn''t like 「Why 与 because」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.11', true, 2, 8110),
  ('把这句话译成英文：我学习了Why 与 because。', 'translation', NULL, NULL, NULL, NULL, 'I learned Why.', ARRAY['I learned Why.']::text[], '翻译考查Why 与 because。', '{}'::jsonb, NULL, 'g7.11', true, 3, 8111)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.12')
  AND sort_order BETWEEN 8200 AND 8299;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.12')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('___ you play the guitar?', 'mcq', 'Can', 'Do', 'Are', 'Does', 'A', NULL::text[], 'Can 表能力。', '{}'::jsonb, NULL, 'g7.12', false, 1, 8200),
  ('— Can Tom swim? — Yes, ___.', 'mcq', 'he can', 'he does', 'he is', 'he can''t', 'A', NULL::text[], 'Yes, he can。', '{}'::jsonb, NULL, 'g7.12', false, 1, 8201),
  ('She ___ play chess.', 'mcq', 'can', 'cans', 'can to', 'can plays', 'A', NULL::text[], 'can + 原形。', '{}'::jsonb, NULL, 'g7.12', false, 1, 8202),
  ('___ they speak English?', 'mcq', 'Can', 'Do', 'Are', 'Does', 'A', NULL::text[], 'Can they ...?', '{}'::jsonb, NULL, 'g7.12', false, 1, 8203),
  ('____ (can) you draw?', 'fill', NULL, NULL, NULL, NULL, 'Can', ARRAY['Can']::text[], 'Can you ...?', '{}'::jsonb, NULL, 'g7.12', false, 1, 8204),
  ('He ____ (can not) play the drums.', 'fill', NULL, NULL, NULL, NULL, 'can''t', ARRAY['can''t']::text[], 'can''t + 原形。', '{}'::jsonb, NULL, 'g7.12', false, 1, 8205),
  ('We ____ (can) sing and dance.', 'fill', NULL, NULL, NULL, NULL, 'can', ARRAY['can']::text[], 'can + 原形。', '{}'::jsonb, NULL, 'g7.12', false, 1, 8206),
  ('改错： "Can she plays the piano?"', 'correction', NULL, NULL, NULL, NULL, 'Can she play the piano?', ARRAY['Can she play the piano?']::text[], 'can 后原形。', '{}'::jsonb, NULL, 'g7.12', true, 2, 8207),
  ('改错： "I can to swim."', 'correction', NULL, NULL, NULL, NULL, 'I can swim.', ARRAY['I can swim.']::text[], 'can 后不用 to。', '{}'::jsonb, NULL, 'g7.12', true, 2, 8208),
  ('句型转换： "I can play basketball." → 疑问', 'transform', NULL, NULL, NULL, NULL, 'Can you play basketball?', ARRAY['Can you play basketball?']::text[], 'Can you ...?', '{}'::jsonb, NULL, 'g7.12', true, 2, 8209),
  ('句型转换： "He can draw well." → 否定', 'transform', NULL, NULL, NULL, NULL, 'He can''t draw well.', ARRAY['He can''t draw well.']::text[], 'can''t。', '{}'::jsonb, NULL, 'g7.12', true, 2, 8210),
  ('把这句话译成英文：你会弹吉他吗？', 'translation', NULL, NULL, NULL, NULL, 'Can you play the guitar?', ARRAY['Can you play the guitar?']::text[], 'Can you play ...?', '{}'::jsonb, NULL, 'g7.12', true, 3, 8211)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.13')
  AND sort_order BETWEEN 8300 AND 8399;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.13')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「What time」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查What time。', '{}'::jsonb, NULL, 'g7.13', false, 1, 8300),
  ('Which sentence uses 「What time」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.13。', '{}'::jsonb, NULL, 'g7.13', false, 1, 8301),
  ('Fill in: This question tests 「What time」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'What time基础题。', '{}'::jsonb, NULL, 'g7.13', false, 1, 8302),
  ('「What time」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.13。', '{}'::jsonb, NULL, 'g7.13', false, 1, 8303),
  ('Complete: (g7.13) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.13', false, 1, 8304),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.13', false, 1, 8305),
  ('Fill: They ____ (be) learning 「What time」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.13', false, 1, 8306),
  ('改错： "This sentence have a 「What time」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「What time」 mistake.', ARRAY['This sentence has a 「What time」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.13', true, 2, 8307),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「What time」.', ARRAY['He doesn''t know 「What time」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.13', true, 2, 8308),
  ('句型转换： "I learn 「What time」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「What time」?', ARRAY['Do you learn 「What time」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.13', true, 2, 8309),
  ('句型转换： "She likes 「What time」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「What time」.', ARRAY['She doesn''t like 「What time」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.13', true, 2, 8310),
  ('把这句话译成英文：我学习了What time。', 'translation', NULL, NULL, NULL, NULL, 'I learned What.', ARRAY['I learned What.']::text[], '翻译考查What time。', '{}'::jsonb, NULL, 'g7.13', true, 3, 8311)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.14')
  AND sort_order BETWEEN 8400 AND 8499;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.14')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「How 问交通方式」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查How 问交通方式。', '{}'::jsonb, NULL, 'g7.14', false, 1, 8400),
  ('Which sentence uses 「How 问交通方式」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.14。', '{}'::jsonb, NULL, 'g7.14', false, 1, 8401),
  ('Fill in: This question tests 「How 问交通方式」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'How 问交通方式基础题。', '{}'::jsonb, NULL, 'g7.14', false, 1, 8402),
  ('「How 问交通方式」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.14。', '{}'::jsonb, NULL, 'g7.14', false, 1, 8403),
  ('Complete: (g7.14) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.14', false, 1, 8404),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.14', false, 1, 8405),
  ('Fill: They ____ (be) learning 「How 问交通方式」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.14', false, 1, 8406),
  ('改错： "This sentence have a 「How 问交通方式」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「How 问交通方式」 mistake.', ARRAY['This sentence has a 「How 问交通方式」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.14', true, 2, 8407),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「How 问交通方式」.', ARRAY['He doesn''t know 「How 问交通方式」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.14', true, 2, 8408),
  ('句型转换： "I learn 「How 问交通方式」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「How 问交通方式」?', ARRAY['Do you learn 「How 问交通方式」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.14', true, 2, 8409),
  ('句型转换： "She likes 「How 问交通方式」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「How 问交通方式」.', ARRAY['She doesn''t like 「How 问交通方式」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.14', true, 2, 8410),
  ('把这句话译成英文：我学习了How 问交通方式。', 'translation', NULL, NULL, NULL, NULL, 'I learned How.', ARRAY['I learned How.']::text[], '翻译考查How 问交通方式。', '{}'::jsonb, NULL, 'g7.14', true, 3, 8411)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.15')
  AND sort_order BETWEEN 8500 AND 8599;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.15')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「祈使句与 don''t」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查祈使句与 don''t。', '{}'::jsonb, NULL, 'g7.15', false, 1, 8500),
  ('Which sentence uses 「祈使句与 don''t」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.15。', '{}'::jsonb, NULL, 'g7.15', false, 1, 8501),
  ('Fill in: This question tests 「祈使句与 don''t」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], '祈使句与 don''t基础题。', '{}'::jsonb, NULL, 'g7.15', false, 1, 8502),
  ('「祈使句与 don''t」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.15。', '{}'::jsonb, NULL, 'g7.15', false, 1, 8503),
  ('Complete: (g7.15) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.15', false, 1, 8504),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.15', false, 1, 8505),
  ('Fill: They ____ (be) learning 「祈使句与 don''t」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.15', false, 1, 8506),
  ('改错： "This sentence have a 「祈使句与 don''t」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「祈使句与 don''t」 mistake.', ARRAY['This sentence has a 「祈使句与 don''t」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.15', true, 2, 8507),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「祈使句与 don''t」.', ARRAY['He doesn''t know 「祈使句与 don''t」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.15', true, 2, 8508),
  ('句型转换： "I learn 「祈使句与 don''t」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「祈使句与 don''t」?', ARRAY['Do you learn 「祈使句与 don''t」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.15', true, 2, 8509),
  ('句型转换： "She likes 「祈使句与 don''t」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「祈使句与 don''t」.', ARRAY['She doesn''t like 「祈使句与 don''t」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.15', true, 2, 8510),
  ('把这句话译成英文：我学习了祈使句与 don''t。', 'translation', NULL, NULL, NULL, NULL, 'I learned 祈使句与.', ARRAY['I learned 祈使句与.']::text[], '翻译考查祈使句与 don''t。', '{}'::jsonb, NULL, 'g7.15', true, 3, 8511)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.16')
  AND sort_order BETWEEN 8600 AND 8699;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.16')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「There be 句型」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查There be 句型。', '{}'::jsonb, NULL, 'g7.16', false, 1, 8600),
  ('Which sentence uses 「There be 句型」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.16。', '{}'::jsonb, NULL, 'g7.16', false, 1, 8601),
  ('Fill in: This question tests 「There be 句型」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'There be 句型基础题。', '{}'::jsonb, NULL, 'g7.16', false, 1, 8602),
  ('「There be 句型」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.16。', '{}'::jsonb, NULL, 'g7.16', false, 1, 8603),
  ('Complete: (g7.16) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.16', false, 1, 8604),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.16', false, 1, 8605),
  ('Fill: They ____ (be) learning 「There be 句型」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.16', false, 1, 8606),
  ('改错： "This sentence have a 「There be 句型」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「There be 句型」 mistake.', ARRAY['This sentence has a 「There be 句型」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.16', true, 2, 8607),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「There be 句型」.', ARRAY['He doesn''t know 「There be 句型」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.16', true, 2, 8608),
  ('句型转换： "I learn 「There be 句型」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「There be 句型」?', ARRAY['Do you learn 「There be 句型」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.16', true, 2, 8609),
  ('句型转换： "She likes 「There be 句型」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「There be 句型」.', ARRAY['She doesn''t like 「There be 句型」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.16', true, 2, 8610),
  ('把这句话译成英文：我学习了There be 句型。', 'translation', NULL, NULL, NULL, NULL, 'I learned There.', ARRAY['I learned There.']::text[], '翻译考查There be 句型。', '{}'::jsonb, NULL, 'g7.16', true, 3, 8611)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.17')
  AND sort_order BETWEEN 8700 AND 8799;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.17')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「What does he look like?」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查What does he look like?。', '{}'::jsonb, NULL, 'g7.17', false, 1, 8700),
  ('Which sentence uses 「What does he look like?」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.17。', '{}'::jsonb, NULL, 'g7.17', false, 1, 8701),
  ('Fill in: This question tests 「What does he look like?」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'What does he look like?基础题。', '{}'::jsonb, NULL, 'g7.17', false, 1, 8702),
  ('「What does he look like?」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.17。', '{}'::jsonb, NULL, 'g7.17', false, 1, 8703),
  ('Complete: (g7.17) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.17', false, 1, 8704),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.17', false, 1, 8705),
  ('Fill: They ____ (be) learning 「What does he look like?」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.17', false, 1, 8706),
  ('改错： "This sentence have a 「What does he look like?」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「What does he look like?」 mistake.', ARRAY['This sentence has a 「What does he look like?」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.17', true, 2, 8707),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「What does he look like?」.', ARRAY['He doesn''t know 「What does he look like?」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.17', true, 2, 8708),
  ('句型转换： "I learn 「What does he look like?」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「What does he look like?」?', ARRAY['Do you learn 「What does he look like?」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.17', true, 2, 8709),
  ('句型转换： "She likes 「What does he look like?」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「What does he look like?」.', ARRAY['She doesn''t like 「What does he look like?」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.17', true, 2, 8710),
  ('把这句话译成英文：我学习了What does he look like?。', 'translation', NULL, NULL, NULL, NULL, 'I learned What.', ARRAY['I learned What.']::text[], '翻译考查What does he look like?。', '{}'::jsonb, NULL, 'g7.17', true, 3, 8711)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g7.18')
  AND sort_order BETWEEN 8800 AND 8899;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g7.18')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「would like 点餐」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查would like 点餐。', '{}'::jsonb, NULL, 'g7.18', false, 1, 8800),
  ('Which sentence uses 「would like 点餐」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g7.18。', '{}'::jsonb, NULL, 'g7.18', false, 1, 8801),
  ('Fill in: This question tests 「would like 点餐」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'would like 点餐基础题。', '{}'::jsonb, NULL, 'g7.18', false, 1, 8802),
  ('「would like 点餐」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g7.18。', '{}'::jsonb, NULL, 'g7.18', false, 1, 8803),
  ('Complete: (g7.18) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g7.18', false, 1, 8804),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g7.18', false, 1, 8805),
  ('Fill: They ____ (be) learning 「would like 点餐」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g7.18', false, 1, 8806),
  ('改错： "This sentence have a 「would like 点餐」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「would like 点餐」 mistake.', ARRAY['This sentence has a 「would like 点餐」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g7.18', true, 2, 8807),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「would like 点餐」.', ARRAY['He doesn''t know 「would like 点餐」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g7.18', true, 2, 8808),
  ('句型转换： "I learn 「would like 点餐」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「would like 点餐」?', ARRAY['Do you learn 「would like 点餐」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g7.18', true, 2, 8809),
  ('句型转换： "She likes 「would like 点餐」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「would like 点餐」.', ARRAY['She doesn''t like 「would like 点餐」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g7.18', true, 2, 8810),
  ('把这句话译成英文：我学习了would like 点餐。', 'translation', NULL, NULL, NULL, NULL, 'I learned would.', ARRAY['I learned would.']::text[], '翻译考查would like 点餐。', '{}'::jsonb, NULL, 'g7.18', true, 3, 8811)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g9.01')
  AND sort_order BETWEEN 9100 AND 9199;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g9.01')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('English ___ in many countries.', 'mcq', 'speaks', 'is spoken', 'spoke', 'was speak', 'B', NULL::text[], '被动 is spoken。', '{}'::jsonb, NULL, 'g9.01', false, 1, 9100),
  ('The room ___ every day.', 'mcq', 'cleans', 'is cleaned', 'cleaned', 'was clean', 'B', NULL::text[], '一般现在被动。', '{}'::jsonb, NULL, 'g9.01', false, 1, 9101),
  ('Rice ___ in the south of China.', 'mcq', 'grows', 'is grown', 'grew', 'was grow', 'B', NULL::text[], 'is grown。', '{}'::jsonb, NULL, 'g9.01', false, 1, 9102),
  ('These books ___ in the library.', 'mcq', 'keep', 'are kept', 'kept', 'are keep', 'B', NULL::text[], '复数 are kept。', '{}'::jsonb, NULL, 'g9.01', false, 1, 9103),
  ('The window ____ (break) by the boy.', 'fill', NULL, NULL, NULL, NULL, 'is broken', ARRAY['is broken']::text[], '被动 is broken。', '{}'::jsonb, NULL, 'g9.01', false, 1, 9104),
  ('Tea ____ (drink) in China.', 'fill', NULL, NULL, NULL, NULL, 'is drunk', ARRAY['is drunk']::text[], 'is drunk。', '{}'::jsonb, NULL, 'g9.01', false, 1, 9105),
  ('Many trees ____ (plant) every spring.', 'fill', NULL, NULL, NULL, NULL, 'are planted', ARRAY['are planted']::text[], 'are planted。', '{}'::jsonb, NULL, 'g9.01', false, 1, 9106),
  ('改错： "English speaks in Canada."', 'correction', NULL, NULL, NULL, NULL, 'English is spoken in Canada.', ARRAY['English is spoken in Canada.']::text[], '被动语态。', '{}'::jsonb, NULL, 'g9.01', true, 2, 9107),
  ('改错： "The song is sing by her."', 'correction', NULL, NULL, NULL, NULL, 'The song is sung by her.', ARRAY['The song is sung by her.']::text[], 'sing → sung。', '{}'::jsonb, NULL, 'g9.01', true, 2, 9108),
  ('句型转换： "People speak Chinese in China." → 被动', 'transform', NULL, NULL, NULL, NULL, 'Chinese is spoken in China.', ARRAY['Chinese is spoken in China.']::text[], '被动转换。', '{}'::jsonb, NULL, 'g9.01', true, 2, 9109),
  ('句型转换： "They make bikes in this factory." → 被动', 'transform', NULL, NULL, NULL, NULL, 'Bikes are made in this factory.', ARRAY['Bikes are made in this factory.']::text[], '复数被动。', '{}'::jsonb, NULL, 'g9.01', true, 2, 9110),
  ('把这句话译成英文：这些花每天都被浇水。', 'translation', NULL, NULL, NULL, NULL, 'These flowers are watered every day.', ARRAY['These flowers are watered every day.']::text[], '一般现在被动。', '{}'::jsonb, NULL, 'g9.01', true, 3, 9111)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g9.02')
  AND sort_order BETWEEN 9200 AND 9299;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g9.02')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「used to 与感叹句」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查used to 与感叹句。', '{}'::jsonb, NULL, 'g9.02', false, 1, 9200),
  ('Which sentence uses 「used to 与感叹句」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g9.02。', '{}'::jsonb, NULL, 'g9.02', false, 1, 9201),
  ('Fill in: This question tests 「used to 与感叹句」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], 'used to 与感叹句基础题。', '{}'::jsonb, NULL, 'g9.02', false, 1, 9202),
  ('「used to 与感叹句」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g9.02。', '{}'::jsonb, NULL, 'g9.02', false, 1, 9203),
  ('Complete: (g9.02) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g9.02', false, 1, 9204),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g9.02', false, 1, 9205),
  ('Fill: They ____ (be) learning 「used to 与感叹句」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g9.02', false, 1, 9206),
  ('改错： "This sentence have a 「used to 与感叹句」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「used to 与感叹句」 mistake.', ARRAY['This sentence has a 「used to 与感叹句」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g9.02', true, 2, 9207),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「used to 与感叹句」.', ARRAY['He doesn''t know 「used to 与感叹句」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g9.02', true, 2, 9208),
  ('句型转换： "I learn 「used to 与感叹句」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「used to 与感叹句」?', ARRAY['Do you learn 「used to 与感叹句」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g9.02', true, 2, 9209),
  ('句型转换： "She likes 「used to 与感叹句」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「used to 与感叹句」.', ARRAY['She doesn''t like 「used to 与感叹句」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g9.02', true, 2, 9210),
  ('把这句话译成英文：我学习了used to 与感叹句。', 'translation', NULL, NULL, NULL, NULL, 'I learned used.', ARRAY['I learned used.']::text[], '翻译考查used to 与感叹句。', '{}'::jsonb, NULL, 'g9.02', true, 3, 9211)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g9.03')
  AND sort_order BETWEEN 9300 AND 9399;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g9.03')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('When I arrived, he ___ already left.', 'mcq', 'has', 'had', 'was', 'did', 'B', NULL::text[], '过去的过去 had left。', '{}'::jsonb, NULL, 'g9.03', false, 1, 9300),
  ('She ___ finished her homework before dinner.', 'mcq', 'has', 'had', 'was', 'did', 'B', NULL::text[], 'had finished。', '{}'::jsonb, NULL, 'g9.03', false, 1, 9301),
  ('By 2020, I ___ learned English for 5 years.', 'mcq', 'have', 'had', 'was', 'did', 'B', NULL::text[], 'by + 过去时间 → had。', '{}'::jsonb, NULL, 'g9.03', false, 1, 9302),
  ('They ___ gone home when we got there.', 'mcq', 'have', 'had', 'were', 'did', 'B', NULL::text[], 'had gone。', '{}'::jsonb, NULL, 'g9.03', false, 1, 9303),
  ('When I got to school, the class ____ (start).', 'fill', NULL, NULL, NULL, NULL, 'had started', ARRAY['had started']::text[], 'had + 过去分词。', '{}'::jsonb, NULL, 'g9.03', false, 1, 9304),
  ('He ____ (leave) before I called him.', 'fill', NULL, NULL, NULL, NULL, 'had left', ARRAY['had left']::text[], 'had left。', '{}'::jsonb, NULL, 'g9.03', false, 1, 9305),
  ('By last year, she ____ (live) here for ten years.', 'fill', NULL, NULL, NULL, NULL, 'had lived', ARRAY['had lived']::text[], 'had lived for ...。', '{}'::jsonb, NULL, 'g9.03', false, 1, 9306),
  ('改错： "When I arrived, he has left."', 'correction', NULL, NULL, NULL, NULL, 'When I arrived, he had left.', ARRAY['When I arrived, he had left.']::text[], '过去完成时。', '{}'::jsonb, NULL, 'g9.03', true, 2, 9307),
  ('改错： "She had go home before 6."', 'correction', NULL, NULL, NULL, NULL, 'She had gone home before 6.', ARRAY['She had gone home before 6.']::text[], 'go → gone。', '{}'::jsonb, NULL, 'g9.03', true, 2, 9308),
  ('句型转换： "I finished homework. Then Mom came home." → 合并', 'transform', NULL, NULL, NULL, NULL, 'Mom came home after I had finished my homework.', ARRAY['Mom came home after I had finished my homework.']::text[], '过去完成表先后。', '{}'::jsonb, NULL, 'g9.03', true, 2, 9309),
  ('句型转换： "He left. I arrived." → 用 before', 'transform', NULL, NULL, NULL, NULL, 'He had left before I arrived.', ARRAY['He had left before I arrived.']::text[], 'had ... before。', '{}'::jsonb, NULL, 'g9.03', true, 2, 9310),
  ('把这句话译成英文：我到车站时，火车已经开走了。', 'translation', NULL, NULL, NULL, NULL, 'When I got to the station, the train had already left.', ARRAY['When I got to the station, the train had already left.']::text[], '过去完成时。', '{}'::jsonb, NULL, 'g9.03', true, 3, 9311)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g9.04')
  AND sort_order BETWEEN 9400 AND 9499;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g9.04')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「情态动词表推测」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查情态动词表推测。', '{}'::jsonb, NULL, 'g9.04', false, 1, 9400),
  ('Which sentence uses 「情态动词表推测」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g9.04。', '{}'::jsonb, NULL, 'g9.04', false, 1, 9401),
  ('Fill in: This question tests 「情态动词表推测」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], '情态动词表推测基础题。', '{}'::jsonb, NULL, 'g9.04', false, 1, 9402),
  ('「情态动词表推测」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g9.04。', '{}'::jsonb, NULL, 'g9.04', false, 1, 9403),
  ('Complete: (g9.04) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g9.04', false, 1, 9404),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g9.04', false, 1, 9405),
  ('Fill: They ____ (be) learning 「情态动词表推测」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g9.04', false, 1, 9406),
  ('改错： "This sentence have a 「情态动词表推测」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「情态动词表推测」 mistake.', ARRAY['This sentence has a 「情态动词表推测」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g9.04', true, 2, 9407),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「情态动词表推测」.', ARRAY['He doesn''t know 「情态动词表推测」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g9.04', true, 2, 9408),
  ('句型转换： "I learn 「情态动词表推测」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「情态动词表推测」?', ARRAY['Do you learn 「情态动词表推测」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g9.04', true, 2, 9409),
  ('句型转换： "She likes 「情态动词表推测」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「情态动词表推测」.', ARRAY['She doesn''t like 「情态动词表推测」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g9.04', true, 2, 9410),
  ('把这句话译成英文：我学习了情态动词表推测。', 'translation', NULL, NULL, NULL, NULL, 'I learned 情态动词表推测.', ARRAY['I learned 情态动词表推测.']::text[], '翻译考查情态动词表推测。', '{}'::jsonb, NULL, 'g9.04', true, 3, 9411)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);

DELETE FROM junior_grammar_questions
WHERE point_id = (SELECT id FROM junior_grammar_points WHERE code = 'g9.05')
  AND sort_order BETWEEN 9500 AND 9599;

WITH p AS (SELECT id FROM junior_grammar_points WHERE code = 'g9.05')
INSERT INTO junior_grammar_questions
  (point_id, stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
   accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
   difficulty, sort_order)
SELECT p.id, q.stem, q.question_type, q.option_a, q.option_b, q.option_c, q.option_d,
       q.correct_answer, q.accepted_answers, q.explanation, q.distractors,
       q.natural_note, q.grammar_topic, q.use_ai_grading, q.difficulty, q.sort_order
FROM p, (VALUES
  ('Choose the best answer for 「中考语法综合」: ___ is correct.', 'mcq', 'Option A', 'Option B', 'Option C', 'Option D', 'A', NULL::text[], '考查中考语法综合。', '{}'::jsonb, NULL, 'g9.05', false, 1, 9500),
  ('Which sentence uses 「中考语法综合」 correctly?', 'mcq', 'Wrong form A', 'Correct form B', 'Wrong form C', 'Wrong form D', 'B', NULL::text[], '正确用法见g9.05。', '{}'::jsonb, NULL, 'g9.05', false, 1, 9501),
  ('Fill in: This question tests 「中考语法综合」 — choose ___ .', 'mcq', 'the right one', 'a wrong one', 'another wrong', 'none', 'A', NULL::text[], '中考语法综合基础题。', '{}'::jsonb, NULL, 'g9.05', false, 1, 9502),
  ('「中考语法综合」 — pick the answer.', 'mcq', 'Answer 1', 'Answer 2', 'Answer 3', 'Answer 4', 'C', NULL::text[], '对应g9.05。', '{}'::jsonb, NULL, 'g9.05', false, 1, 9503),
  ('Complete: (g9.05) ____ (test) this grammar point.', 'fill', NULL, NULL, NULL, NULL, 'tests', ARRAY['tests']::text[], '动词原形/正确形式。', '{}'::jsonb, NULL, 'g9.05', false, 1, 9504),
  ('Fill: She ____ (study) this topic every day.', 'fill', NULL, NULL, NULL, NULL, 'studies', ARRAY['studies']::text[], '第三人称单数。', '{}'::jsonb, NULL, 'g9.05', false, 1, 9505),
  ('Fill: They ____ (be) learning 「中考语法综合」 now.', 'fill', NULL, NULL, NULL, NULL, 'are', ARRAY['are']::text[], '复数 be 动词。', '{}'::jsonb, NULL, 'g9.05', false, 1, 9506),
  ('改错： "This sentence have a 「中考语法综合」 mistake."', 'correction', NULL, NULL, NULL, NULL, 'This sentence has a 「中考语法综合」 mistake.', ARRAY['This sentence has a 「中考语法综合」 mistake.']::text[], '主谓一致 has。', '{}'::jsonb, NULL, 'g9.05', true, 2, 9507),
  ('改错： "He dont know 「{topic}」."', 'correction', NULL, NULL, NULL, NULL, 'He doesn''t know 「中考语法综合」.', ARRAY['He doesn''t know 「中考语法综合」.']::text[], '第三人称 doesn''t。', '{}'::jsonb, NULL, 'g9.05', true, 2, 9508),
  ('句型转换： "I learn 「中考语法综合」." → 一般疑问句', 'transform', NULL, NULL, NULL, NULL, 'Do you learn 「中考语法综合」?', ARRAY['Do you learn 「中考语法综合」?']::text[], 'Do you ...?', '{}'::jsonb, NULL, 'g9.05', true, 2, 9509),
  ('句型转换： "She likes 「中考语法综合」." → 否定句', 'transform', NULL, NULL, NULL, NULL, 'She doesn''t like 「中考语法综合」.', ARRAY['She doesn''t like 「中考语法综合」.']::text[], 'doesn''t + 原形。', '{}'::jsonb, NULL, 'g9.05', true, 2, 9510),
  ('把这句话译成英文：我学习了中考语法综合。', 'translation', NULL, NULL, NULL, NULL, 'I learned 中考语法综合.', ARRAY['I learned 中考语法综合.']::text[], '翻译考查中考语法综合。', '{}'::jsonb, NULL, 'g9.05', true, 3, 9511)
) AS q(stem, question_type, option_a, option_b, option_c, option_d, correct_answer,
       accepted_answers, explanation, distractors, natural_note, grammar_topic, use_ai_grading,
       difficulty, sort_order);
