// This file is automatically generated. Do not edit it directly.
// 例外:下方 global.fetch 超时封装为手动加(性能/可用性修复,防国内弱网请求永久挂起),重新生成时请保留。
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// 全局请求超时:任何 Supabase 请求(PostgREST/auth/functions)超过 10s 自动中止 → 抛错,
// 页面据此显示"加载失败,点此重试",绝不让用户永远卡在 Loading。国内弱网"打不开"的直接堵点。
const REQUEST_TIMEOUT_MS = 10_000;
const timeoutFetch: typeof fetch = (input, init = {}) => {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(new DOMException("请求超时", "TimeoutError")), REQUEST_TIMEOUT_MS);
  const signal = init.signal ? AbortSignal.any([init.signal, ctrl.signal]) : ctrl.signal;
  return fetch(input, { ...init, signal }).finally(() => clearTimeout(timer));
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: timeoutFetch },
});