// This file is automatically generated. Do not edit it directly.
// 例外:下方 global.fetch 超时封装为手动加(性能/可用性修复,防国内弱网请求永久挂起),重新生成时请保留。
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// 全局请求超时:任何 Supabase 请求(PostgREST/auth/functions)超过 10s 自动中止 → 抛错,
// 页面据此显示"加载失败,点此重试",绝不让用户永远卡在 Loading。国内弱网"打不开"的直接堵点。
const REQUEST_TIMEOUT_MS = 10_000;
const timeoutFetch: typeof fetch = (input, init = {}) => {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(new DOMException("请求超时", "TimeoutError")), REQUEST_TIMEOUT_MS);
  const signal = init.signal ? AbortSignal.any([init.signal, ctrl.signal]) : ctrl.signal;
  return fetch(input, { ...init, signal }).finally(() => clearTimeout(timer));
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: { fetch: timeoutFetch },
});

// 例外二(手动加,重新生成时请保留):把 edge function 的**上游响应体**透出到 error.message。
//
// ★为什么必须有★ supabase-js 的 invoke 出错时只给一句 "Edge Function returned a
// non-2xx status code",真正的原因在响应体里、被默认吞掉。2026-07-26 就是因为这个,
// 「写作批改一直坏着」查了好几轮才发现上游返回的是 403 PERMISSION_DENIED
// (Google 项目被停用)—— 而那条信息其实一直躺在 body 里没人看见。
//
// 在客户端包一层,31 处调用点全部受益,不用逐个改(逐个改必漏)。
// 读的是 clone(),不动原始 Response,调用方仍可自行读取。
const rawInvoke = supabase.functions.invoke.bind(supabase.functions);
supabase.functions.invoke = (async (fnName: string, options?: unknown) => {
  const res = await (rawInvoke as (n: string, o?: unknown) => Promise<{ data: unknown; error: unknown }>)(fnName, options);
  const err = res?.error as (Error & { context?: Response }) | null;
  if (err && err.context && typeof err.context.clone === "function") {
    try {
      const body = await err.context.clone().text();
      if (body) err.message = `${err.message} | ${fnName}: ${body.slice(0, 500)}`;
    } catch {
      /* 响应体读不出(已消费/非文本)→ 保持原样,不因为诊断代码本身再抛错 */
    }
  }
  return res;
}) as typeof supabase.functions.invoke;